### ISSUE TITLE
WiFi SSID

### ISSUE THREAD

**Issue by ageorgios** [RavenSystem/esp-homekit-devices#1]
How do you configure WiFi SSID / password?

**Comment by RavenSystem** [comment]
To configure Wifi, device enters in access point mode, so you can connect directly to it, and a web page will appear automatically to let you to configure your wifi network.

**Comment by ageorgios** [comment]
Uploaded the firmware on a Sonoff TH16, connected to power, no SSID from it comming... What SSID name am I looking for?

**Comment by RavenSystem** [comment]
SSID is "SonoffTH <end_of_mad_addr>". It's 2.4GHz Wifi.

What is your UART output?

**Comment by ageorgios** [comment]
`/home/ageorgios/esptool/esptool.py -p /dev/ttyUSB0 --baud 115200 write_flash -fs 8m -fm dout -ff 40m 0x0 /home/ageorgios/temp4/esp-homekit-devices/sdk/esp-open-rtos/bootloader/firmware_prebuilt/rboot.bin 0x1000 /home/ageorgios/temp4/esp-homekit-devices/sdk/esp-open-rtos/bootloader/firmware_prebuilt/blank_config.bin 0x2000 ./firmware/Sonoff_TH.bin`

**Comment by RavenSystem** [comment]
Your UART output when you power-on your Sonoff, after flashing.

**Comment by ageorgios** [comment]
I dont really know how to do this.

The difference is that I used external esptool v2.3, and the command directly instead of the 
`make -C devices/Sonoff_TH test`
because the esptool included in the sdk is v1.2 and does not work, stopping at this stage:
```
make: Entering directory '/home/ageorgios/temp4/esp-homekit-devices/devices/Sonoff_TH'
esptool.py -p /dev/ttyUSB0 --baud 115200 write_flash -fs 8m -fm dout -ff 40m \
	0x0 /home/ageorgios/temp4/esp-homekit-devices/sdk/esp-open-rtos/bootloader/firmware_prebuilt/rboot.bin 0x1000 /home/ageorgios/temp4/esp-homekit-devices/sdk/esp-open-rtos/bootloader/firmware_prebuilt/blank_config.bin 0x2000 ./firmware/Sonoff_TH.bin 
esptool.py v1.2
Connecting...
Running Cesanta flasher stub...
Flash params set to 0x0320
Writing 4096 @ 0x0... 
```

**Comment by RavenSystem** [comment]
Ok. Don't worry. Follow those steps, assuming that your Sonoff is connected to your FTDI:

1. Disconnect your FTDI from USB.
2. Connect it to USB.
3. In your terminal, run:
```shell
cd ~/temp4/esp-homekit-devices/devices/Sonoff_TH/
export ESPPORT=/dev/ttyUSB0
make  monitor
```

Now you will see the UART output.

**Comment by ageorgios** [comment]
```
ageorgios@ubuntu:~/temp4/esp-homekit-devices/devices/Sonoff_TH$ make monitor
/home/ageorgios/temp4/esp-homekit-devices/sdk/esp-open-rtos//utils/filteroutput.py --port /dev/ttyUSB0 --baud 115200 --elf ./build/Sonoff_TH.out
Opening /dev/ttyUSB0 at 115200bps...
```
No output..

I think I will use the precompiled firmwares you just uploaded

**Comment by RavenSystem** [comment]
It's strange. Maybe your FTDI has not enough power for Sonoff TH. If you have connected sensor, please, disconnect it.

**Comment by ageorgios** [comment]
Success with your precompiled firmware using this:
```
/home/ageorgios/esptool/esptool.py -p /dev/ttyUSB0 --baud 115200 write_flash -fs 8m -fm dout -ff 40m 0x0 /home/ageorgios/Desktop/Sonoff_TH_v0.1.0.bin
```

**Comment by RavenSystem** [comment]
Can you setup your wifi now?

**Comment by ageorgios** [comment]
Yes

I am adding the accessory in Home app

What is the HomeKit password?

**Comment by ageorgios** [comment]
021-82-017 I guess?

**Comment by RavenSystem** [comment]
I'm writing the Wiki just now :)

https://github.com/RavenSystem/esp-homekit-devices/wiki/General-user-manual

**Comment by ageorgios** [comment]
Cannot pair it with this number :(

**Comment by RavenSystem** [comment]
Sometime pairing fails, in that case, you can unpower your device, repower it, and start HomeKit setup again (Wifi config keeps configured).

**Comment by ageorgios** [comment]
Success after repowering the sonoff!
Thanx for the great work! Keep it up! I will test it and report my experiences!

**Comment by ageorgios** [comment]
Sonoff TH16 is recognized as Sonoff Thermostat
Would be great to have option to configure it on demand (like just a switch)

**Comment by RavenSystem** [comment]
I'm going to write specific user manual for Sonoff TH, but some info:
- Auto mode has no effect because device has only one relay.
- Sensor is read every 30 seconds.
- If you have connected a heater, then you must use Heat mode, and if you have connected a cooler, then you must use Cool mode.
- If sensor fails, relay turn off automatically.
- You can select operating mode using the Sonoff button (1 LED flash: off; 2 LED flash: heat; 3 LED flash: cool).

**Comment by RavenSystem** [comment]
If you want a normal switch, you can flash the Sonoff_Basic firmware.
