### ISSUE TITLE
does fan service support Temperature sensor?

### ISSUE THREAD

**Issue by cab113** [RavenSystem/esp-homekit-devices#1000]
Hi all,

i have setup a fan service with 3 speed.Does the fan service Type 65, support temperature sensor to show inside the fan device like it does in thermostat service. Application is for home ventilation system.
currently i have temperature loading as separate accessory. below is my config. 

1. Fan service 65 - 3 speed - 1 relay at a time interlocking to make sure fan doesnt receive more than one speed signal at anyone time. 
2. Temperature sensor - DHT 11 - with some Y wildcards for speed control and off
3. Switch for turning heat transfer/roof damper on/off.

{
  "c":{"l":13,"b":[{"g":0,"t":5}]},
  "a":[{
    "t":65,
    "e":3,
    "0":{"r":[{"g":15},{"g":12},{"g":14}]},
    "y0":[
      {"v":1, "0":{"r":[{"g":15,"v":1},{"g":12, "v": 0},{"g":14, "v": 0}]} },
      {"v":2, "0":{"r":[{"g":15,"v":0},{"g":12, "v": 1},{"g":14, "v": 0}]} },
      {"v":3, "0":{"r":[{"g":15,"v":0},{"g":12, "v": 0},{"g":14, "v": 1}]} }]},
	  
    {"t": 24,
    "g": 4,
    "n": 1,
    "j": 30,
     "y0": [
	 { 
	 
      "v": 35,
      "r": 1,
      "0":{"r":[{"g":15,"v":0},{"g":12, "v": 0},{"g":14, "v": 1}]}
    },
	{
      "v": 28,
      "r": 1,
      "0":{"r":[{"g":15,"v":0},{"g":12, "v": 1},{"g":14, "v": 0}]} 
    },
	{
      "v": 22,
      "r": 1,
      "0":{"r":[{"g":15,"v":1},{"g":12, "v": 0},{"g":14, "v": 0}]} 
    },
	{
      "v": 19,
      "0": { "r": [{ "g": 12, "v": 0 }] },
	  "0": { "r": [{ "g": 14, "v": 0 }] },
	  "0": { "r": [{ "g": 15, "v": 0 }] }
    }]
	
  
    },{
      "t":1,
      "1":{"r":[{"g":2}]},
      "0":{"r":[{"g":2,"v":1}]},
      "b":[{"g":0}]
    }
	
  ]
}

**Comment by i3laze** [comment]
Nope, it doesn’t. Stick with a fan + thermostat accessories.
Your config looks great.

You could add some digital inputs to the switch (so it would be displayed as turned on) and improve config readability by using [inter-accessory Notifications ](https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#Accessory-Notifications), but unfortunately Fan supports only On/Off notifications. 
We should ask @RavenSystem for some extra “speed9 notification.
