### ISSUE TITLE
Sonoff mini and fault code 1 in Eve App

### ISSUE THREAD

**Issue by marithpl** [RavenSystem/esp-homekit-devices#1006]
I installed Sonoff mini it's working fine but I found an error in Eve App.
`Fault: The accessory reports fault code 1. Please refer to its user manual.`

Do you know what a problem might be?

**Comment by permaMonk** [comment]
Any reliable solution for this?
I’ve got these errors too - rare but periodically about every half year. I take the power plug out and in again. Sometimes it works, sometimes not. Just now it disappears - not. :(
