### ISSUE TITLE
How to flash Sonoff mini to HAA in Mac OS?

### ISSUE THREAD

**Issue by tlagarto** [RavenSystem/esp-homekit-devices#1009]
I've surfed the wiki and can't find an answer to this one.
I'm sure it's a dumb questions, but I only have a Mac and no Windows PC.
What tools should I use to flash a sonoff mini to HAA?

Thanks!

**Comment by bj-tracer** [comment]
I soldered wires to the pcb and normally flash with ttl-adapter.
![WhatsApp Image 2020-04-07 at 17 48 00](https://user-images.githubusercontent.com/50882159/85021283-56496b00-b17a-11ea-8fd7-030b148d1f97.jpeg)

**Comment by tlagarto** [comment]
Yes, I built a jig to flash it without soldering every time.
But I already found a way (command line) to flash the devices.
Thanks anyway.
![1](https://user-images.githubusercontent.com/61150429/85030896-e933d680-b175-11ea-9f63-81aacf9826c1.jpeg)
![2](https://user-images.githubusercontent.com/61150429/85030901-eafd9a00-b175-11ea-9427-752870768c97.jpeg)
