### ISSUE TITLE
RF support for sonoff fan03

### ISSUE THREAD

**Issue by alifarooq1991** [RavenSystem/esp-homekit-devices#1014]
Please add rf remote support for sonoff fan03

**Comment by bj-tracer** [comment]
Hello!
It work like rf-bridge, I think.
RF-bridge has the rf to uart controller that send an uart-requests to the esp.
HAA can’t read this requests.

**Comment by wayn3** [comment]
Here is a request to add support for receiving UART commands into HAA
https://github.com/RavenSystem/esp-homekit-devices/issues/915
