### ISSUE TITLE
Looking for json sonoff SV with one contact sensor

### ISSUE THREAD

**Issue by homekiciarz** [RavenSystem/esp-homekit-devices#1018]
Hi. I find
{"c":{"l":13,"b":[{"g":0,"t":5}]},
 "a":[{
"0":{"r":[{"g":12,"v":1,"i":0.5}]},
"1":{"a":0},
"2":{"r":[{"g":12,"i":1.5},{"g":12,"v":1,"i":0.5},{"g":12,"v":1,"i":2}]},
"3":{"a":2},"t":40,"d":6,
"f3":[{"g":14,"t":0}],
"f4":[{"g":14}],
"f2":[{"g":4,"t":0}],
"f5":[{"g":4}]}]}

But i want to remove second contact sensor (gpio04)

**Comment by pawelosin** [comment]
Just remove the section wIth gpio4.

{"c":{"l":13,"b":[{"g":0,"t":5}]},
"a":[{
"0":{"r":[{"g":12,"v":1,"i":0.5}]},
"1":{"a":0},
"2":{"r":[{"g":12,"i":1.5},{"g":12,"v":1,"i":0.5},{"g":12,"v":1,"i":2}]},
"3":{"a":2},"t":40,"d":6,
"f3":[{"g":14,"t":0}],
"f4":[{"g":14}]}]}
