### ISSUE TITLE
Shelly RGBW with external Push Button

### ISSUE THREAD

**Issue by Hanimaniac** [RavenSystem/esp-homekit-devices#1022]
Hey Homekit Friends,

I'm using a shelly rgbw for 4 white, dimmable LED Stripes with this String:

{"c":{"b":[{"g":0,"t":5}],"n":"shelly-rgbw"},"a":[{"t":30,"w":15,"b":[{"g":0}]},{"t":30,"w":12,"b":[{"g":0}]},{"t":30,"w":14,"b":[{"g":0}]},{"t":30,"w":4,"b":[{"g":0}]}]}

It works fine but i have two Questions.

1. Is it possible to show the 4 Stripes from picture 1 as one "switch" like in picture 2?
   (in picture 2 its a shelly 2.5 wit old RC installed).

![image](https://user-images.githubusercontent.com/45320732/85221288-f093f380-b3b2-11ea-8191-d3dc8bdf2b56.png)
 

![image](https://user-images.githubusercontent.com/45320732/85221279-dd812380-b3b2-11ea-8881-e5cef19648af.png)

2. I can't figure out how it is possible to add a pushbutton that can turn on/off all stripes.

I Hope you can help me.

Best regards
Hanimaniac

**Comment by CannyFoxx** [comment]
You can Home app for grouping your devices
![Apple Home](https://user-images.githubusercontent.com/2915109/85412911-c8eb8980-b572-11ea-93d4-f05bd9b0a9d7.jpg)
If your device have free GRIO (usually it is GRIO0) - you can add physical button

**Comment by Hanimaniac** [comment]
CannyFoxx,
thanks for your answer. 
If I Group with other Accessories the Hone App, I just have One Button to controll all of the grouped lights. 
In my second picture you can see i have 2 switches for two lights in one Accessoirie. 

in the following picture I found out that the button is. gpio13 but werent able to use it. 

![image](https://user-images.githubusercontent.com/45320732/85503401-e0198e00-b5e9-11ea-8b2d-c3a07f83017c.jpeg)

greets
Hanimaniac
