### ISSUE TITLE
Sonoff Zigbee Bridge compatibility?

### ISSUE THREAD

**Issue by Silencer0001** [RavenSystem/esp-homekit-devices#1026]
Hi,

I’m interested in the “Sonoff Zigbee Bridge” if it could be made compatible with Homekit. Are there any plans to support this device in the future? Thanks and keep up the good work! I’m new to smart home and currently exploring my options. This firmware seems great :-)

**Comment by Jeroen207** [comment]
Well, what you also can do is use Zigbee2MQTT in combination with Homebridge.

**Comment by jakudo** [comment]
Hi,
+1 for me. I would like to buy Sonoff Zigbee Bridge and have a possibility to ad dit to HomeKit via Homebridge. However, I would still prefer to flash it with HAA. If it would be possible, it will be awesome!

**Comment by St0nehead** [comment]
+1
