### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by tarontop** [RavenSystem/esp-homekit-devices#1028]
I have a key switch. If I press the key quickly (about twice in three seconds) for about ten times, then homekit will lose its response and all functions will be disabled, so I can only restart it.
my json:
`{"c":{"l":4,"b":[{"g":13,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":13}]}]}`

**Comment by Bene2103** [comment]
Maybe this could be your problem?

> Entering Setup Mode

> To enter setup mode, you must quickly toggle any action switch/button 8 times (physical or from Home App). You can secure this method by declaring a time after device boot to perform it.
