### ISSUE TITLE
Where is compiled all in one firmware

### ISSUE THREAD

**Issue by yusufd1** [RavenSystem/esp-homekit-devices#103]
Hi where is the downloadable version of the latest firmware without OTA. I cannot find it anymore.

**Comment by rechin304** [comment]
https://github.com/RavenSystem/ravencore/releases/

**Comment by RavenSystem** [comment]
<img width="1256" alt="captura de pantalla 2018-11-28 a las 13 28 32" src="https://user-images.githubusercontent.com/8655274/49151943-9be0e180-f311-11e8-8a7a-763b1892a5ee.png">
