### ISSUE TITLE
Looking for json for LG TV remote 

### ISSUE THREAD

**Issue by borissov** [RavenSystem/esp-homekit-devices#1034]
Hello, 
I am looking for json config for LG TV remote. I use NodeMCU with BC547 + TSAL6100 connected on GPIO4 and is work with my script, but now I want to use it with HAA. 

Hire is all codes of LG remote:
https://gitlab.com/snippets/1690600

With this function in my script works:
irsend.sendNEC(request.toInt(), 32);

I think the protocol is NEC. 
I tested with Panasonic example in wiki and led works. Thanks!

**Comment by Rahulsharma0810** [comment]
Able to figure this out ?

**Comment by borissov** [comment]
Nope, I modified it by adding a DHT11 and turned it into an air conditioning controller with a custom script based on: https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266 .
