### ISSUE TITLE
sonoff sv lock mechanism

### ISSUE THREAD

**Issue by dosha25** [RavenSystem/esp-homekit-devices#1036]
Hi. I add sonoff sv with templates lock mechanism. In homekit I see it. But relay don’t give 12v on 3s, what I do wrong?
I use this templates:
{
  "a":[{
    "t":4,
    "i":3,
    "0":{"r":[{"g":4,"v":1,"i":0.5}]},
    "1":{"r":[{"g":4}]},
    "b":[{"g":5,"p":0,"i":1,"t":0}]
  }]
}

**Comment by hillaliy** [comment]
Sonoff SV - Loc mechanism with contact sensor

{"c":{"l":13,"i":0,"b":[{"g":0,"t":1}]},"a":[{"t":4,"i":3,"1":{"r":[{"g":12}]},"0":{"r":[{"g":12,"v":1,"i":3}]},"b":[{"g":0,"i":3}]},{"t":5,"f0":[{"g":5,"t":0}],"f1":[{"g":5}]}]}

**Comment by dosha25** [comment]
> Sonoff SV - Lock mechanism with contact sensor
> 
> {"c":{"l":13,"i":0,"b":[{"g":0,"t":1}]},"a":[{"t":4,"i":3,"1":{"r":[{"g":12}]},"0":{"r":[{"g":12,"v":1,"i":3}]},"b":[{"g":0,"i":3}]},{"t":5,"f0":[{"g":5,"t":0}],"f1":[{"g":5}]}]}

Thanks work. Maybe you have templates Sonoff SV - Lock mechanism without contact sensor?

**Comment by hillaliy** [comment]
"c":{"l":13,"i":0,"b":[{"g":0,"t":1}]},"a":[{"t":4,"i":3,"1":{"r":[{"g":12}]},"0":{"r":[{"g":12,"v":1,"i":3}]},"b":[{"g":0,"i":3}]} ]}

**Comment by karnas99** [comment]
> Sonoff SV - Lock mechanism with contact sensor
> 
> {"c":{"l":13,"i":0,"b":[{"g":0,"t":1}]},"a":[{"t":4,"i":3,"1":{"r":[{"g":12}]},"0":{"r":[{"g":12,"v":1,"i":3}]},"b":[{"g":0,"i":3}]},{"t":5,"f0":[{"g":5,"t":0}],"f1":[{"g":5}]}]}

Hi,

can I ask you how to connect contact sensor? I just tried GIO5 pins S and G and I burned it. 

Thanks

**Comment by karnas99** [comment]
> you need this sensor:
> https://he.aliexpress.com/item/4000138461602.html?spm=a2g0s.9042311.0.0.27424c4dssws1U
> connect one wire to gpis 5 and the other to ground

I have mechanic sensor integrated in the door lock but I believe it works pretty same. Have no idea why it was burned. Now I am waiting for new sonoff to be delivered

**Comment by hillaliy** [comment]
the GPIO work on 3.3v
maybe your build in sensor work on 12v

**Comment by karnas99** [comment]
> the GPIO work on 3.3v
> maybe your build in sensor work on 12v

build sensor is just switch it does't it does not produce any electric. However input voltage is 12V

**Comment by hillaliy** [comment]
that what I mean. the input is 12v and the output from the SV is 3.3. because of that it's burn.

**Comment by karnas99** [comment]
> that what I mean. the input is 12v and the output from the SV is 3.3. because of that it's burn.

Alright so I have connected 12V power input which is giving 12V output and unlock door lock. With this circumstances is there any way how to use sensor - switch on  GPIO 5 and not to burn it?

**Comment by hillaliy** [comment]
yes use 3.3 contact sensor
