### ISSUE TITLE
Magichome rgb 

### ISSUE THREAD

**Issue by dosha25** [RavenSystem/esp-homekit-devices#1041]
Hi. I search templates with flash light mode. Please help

**Comment by hire-vladimir** [comment]
I assume this is for RGB led strip? If its one of these https://tasmota.github.io/docs/devices/MagicHome-with-ESP8285/

i've had good luck with below config.

```
{
  "c": {
    "q": 850,
    "b": [
      {
        "g": 0,
        "t": 5
      }
    ]
  },
  "a": [
    {
      "t": 30,
      "r": 5,
      "g": 12,
      "v": 13,
      "w": 15,
      "b": [
        {
          "g": 1
        }
      ]
    }
  ]
}
```

**Comment by dosha25** [comment]
> I assume this is for RGB led strip? If its one of these https://tasmota.github.io/docs/devices/MagicHome-with-ESP8285/
> 
> i've had good luck with below config.
> 
> ```
> {
>   "c": {
>     "q": 850,
>     "b": [
>       {
>         "g": 0,
>         "t": 5
>       }
>     ]
>   },
>   "a": [
>     {
>       "t": 30,
>       "r": 5,
>       "g": 12,
>       "v": 13,
>       "w": 15,
>       "b": [
>         {
>           "g": 1
>         }
>       ]
>     }
>   ]
> }
> ```

Thanks my friend. But I search templates with flash effects:
![DD0AC4EC-B32E-4877-AFC8-8A41015211FF](https://user-images.githubusercontent.com/67960646/88486990-4b100900-cf8a-11ea-82b2-48f5cb745f2a.jpeg)

**Comment by vijaydembla1** [comment]
Hey
Any luck with the template search and config?

**Comment by dosha25** [comment]
> Hey
> Any luck with the template search and config?
Unlucky. I search templates and this time

**Comment by than-sad** [comment]
Hi, I found this page referring to how to define the effects, but I don't know how to made it in HAA and I can't see any references to effects in Wiki.

Can anyone give us some tips on how to do it?

Best regards.
