### ISSUE TITLE
Water flood and level sensor

### ISSUE THREAD

**Issue by sorriso93** [RavenSystem/esp-homekit-devices#1046]
Hello
I was thinking to use a sensor like this [link](https://www.aliexpress.com/item/32656104046.html?spm=a2g0s.9042311.0.0.27424c4dCFC9xy) in combination with a water valve but I fear it is not possible to use it as a contact sensor due to the analog output based on the level of water.
In Haa is there already an accessory using a range of value on Analog input (A0)? In this case should be a matter to encapsulate the reading of the arduino pin in relative homekit accessory characteristics.
I'm not an expert but If I understand correctly it seems in homekit there is waterlevel characteristic

let HMCharacteristicTypeWaterLevel: String
The water level measured by an accessory.
let HMCharacteristicTypeValveType: String
The type of automated valve that controls fluid flow.
let HMCharacteristicTypeLeakDetected: String
A leak detection indicator.

Do you have plan to implement it?
Many thanks

**Comment by pilot1981** [comment]
I used a JSN SR04T with water leak sensor HAA accessory and a fixed distance: it works fine!
