### ISSUE TITLE
JSON config string "&para" is converted to "¶"

### ISSUE THREAD

**Issue by rjblake** [RavenSystem/esp-homekit-devices#1048]
Have tried to include an HTTP PUT command into the JSON, but it does not get accepted as updates part of the command string from "&param" to a paragraph marker "¶m". Can't seem to find a way around this, so perhaps a bug in the HTTP code?

**Relevant line of JSON:**
`"f2":[{"g":12,"t":0},{"h":[{"h":"192.168.1.14", "p":8084, "u":"json.htm?type=command&param=switchlight&idx=613&switchcmd=On"}]}]`

**Gets saved as:**
`"f2":[{"g":12,"t":0},{"h":[{"h":"192.168.1.14", "p":8084, "u":"json.htm?type=command¶m=switchlight&idx=613&switchcmd=On"}]}]`

**Comment by rjblake** [comment]
Any update on this issue?

**Comment by rjblake** [comment]
@RavenSystem - has this been fixed in current version? Can't seem to find any reference to it in the latest code, but could have missed it.

**Comment by rjblake** [comment]
@RavenSystem - is this on the backlog to fix at all?

**Comment by RavenSystem** [comment]
JSON is saved fine. Special character appears only into html text area.

**Comment by rjblake** [comment]
> JSON is saved fine. Special character appears only into html text area.

Understand that this is correct first time around. If you connect again to edit/modify JSON, you need to make sure to replace all instances of "¶" with &para or else incorrect JSON is saved.

**Comment by RavenSystem** [comment]
> Understand that this is correct first time around. If you connect again to edit/modify JSON, you need to make sure to replace all instances of "¶" with &para or else incorrect JSON is saved.

I must test it.

**Comment by RavenSystem** [comment]
Process of replacing that rare character can need so much RAM in some scenarios. I will no fix it.

As workaround, make sure to replace all instances of "¶" with &para or else incorrect JSON is saved.
