### ISSUE TITLE
Will HAA work on Shelly i3?

### ISSUE THREAD

**Issue by gijsstegehuis** [RavenSystem/esp-homekit-devices#1049]
A Shelly i3 would make a perfect Homekit stateless button.
Can it be done using the current firmware?

It has three channels. Would it be possible to make it show up as 3 stateless buttons in Homekit?

**Comment by RavenSystem** [comment]
You can install HAA to Shelly i3, and you could create 3 stateless buttons in HomeKit, or 2 buttons and one movement sensor, or which you want. You have 3 digital binary inputs.

**Comment by gijsstegehuis** [comment]
Just received the Shelly i3's. Will test asap.
Do you happen to know the GPIO numbers for the inputs? it's not on their official website.

**Comment by RavenSystem** [comment]
You can follow circuit tracks, or you can setup a simple homekit switch and attach a GPIO number to it, and then change GPIO number and test it. You can create a bunch of switches too.

**Comment by lociii** [comment]
![i3_back](https://user-images.githubusercontent.com/366967/88367171-6234d800-cd8b-11ea-81b5-3bc6d8ec2e1f.jpg)
![i3_front](https://user-images.githubusercontent.com/366967/88367175-63660500-cd8b-11ea-974c-5132d59f71a5.jpg)

Here's the inner workings of the i3 with circuit tracks from input to the ESP

**Comment by gijsstegehuis** [comment]
@lociii awesome! danke

**Comment by lociii** [comment]
Don't expect too much. I couldn't get it running with ESPHome as the inputs are floating and I didn't find any way to make them behave correctly.

**Comment by gijsstegehuis** [comment]
I am not into the hardware side of things, but isn't this wat the pull-up resistor is for?
There's a config setting for it in HAA.

**Comment by lociii** [comment]
Usually yes, but with pullup enabled, there is no signal at all.
I mean, try your luck. I didn't have some :)

**Comment by gijsstegehuis** [comment]
Thx. I will see if i can get it working.

**Comment by gijsstegehuis** [comment]
@lociii what sort of connector or cables are you using to flash the i3?
I soldered cables to a male/male header pin with 1,27mm pitch, but i can't get a decent connection to the ftdi adapter.

are there any standardized connectors around?

**Comment by lociii** [comment]
I used a self made 1.27 pitch connector too. You have to make sure they do in deep enough and are all pretty much the same length.

**Comment by AndreWillems** [comment]
just soldered some wires to the (small) connector. see pin-out on the picture. I flashed it the usual way like all other Sonoffs and Shelly's and it works perfect. I'm not using Tasmota or anything, build my own MQTT code for such IoT devices. 

![Shelly I3 pinout2](https://user-images.githubusercontent.com/63243459/88476555-82a29500-cf39-11ea-89d1-93aba3716de9.jpg)

**Comment by lociii** [comment]
@AndreWillems was there anything special you had to change on your code to get the inputs working? Is it publicly available?

**Comment by AndreWillems** [comment]
> @AndreWillems was there anything special you had to change on your code to get the inputs working? Is it publicly available?

@lociii, no nothing special. obviously changes the inputs based on the 3 switches from this Shelly device. Flashed it serial once and after I use OTA. drop me a mail if you want my source code.

**Comment by gijsstegehuis** [comment]
@AndreWillems can you share the json configuration you used?

**Comment by AndreWillems** [comment]
> @AndreWillems can you share the json configuration you used?

sorry @gijsstegehuis, I'm not using HAA or Tasmota. just wrote my own code once for Sonoff/Shelly and used this for Shelly I3 as well. no JSON config files.... but hopefully the picture with IO's can help you/others to make the appropriate JSON file ?

**Comment by craigueh** [comment]
Hi AndreWilliams

Could you provide your code to flash to the i3?

I tried esphome but can’t get the floating inputs to behave correctly.

**Comment by martinjuhasz** [comment]
I managed to get it working. You need to add a delayed_on_off. See my sample config here:
https://github.com/esphome/issues/issues/1459

**Comment by gijsstegehuis** [comment]
For anyone stumbling upon this issue:
https://github.com/mongoose-os-apps/shelly-homekit just released version 2.5.0 which has support for Shelly i3

**Comment by pilot1981** [comment]
anyone is able to use shelly i3 with HAA? can you share JSON?

**Comment by RavenSystem** [comment]
`{"c":{"l":0,"b":[{"g":2,"t":5}]},"a":[{"t":3,"f0":[{"g":14,"p":0,"m":1}],"f1":[{"g":14,"t":2}],"f2":[{"g":14,"t":3}]},{"t":3,"f0":[{"g":12,"p":0,"m":1}],"f1":[{"g":12,"t":2}],"f2":[{"g":12,"t":3}]},{"t":3,"f0":[{"g":13,"p":0,"m":1}],"f1":[{"g":13,"t":2}],"f2":[{"g":13,"t":3}]},{"t":22,"n":5}]}`

**Comment by sonicpixel2020** [comment]
Hey. Thanks for this Config. I would like to have Sensor to see if the switch is on or off. Is that also possible? I could not get this working. Can you send a Config for this? Thank you.
