### ISSUE TITLE
OTA update from stock firmware

### ISSUE THREAD

**Issue by gijsstegehuis** [RavenSystem/esp-homekit-devices#1054]
Just fried the flash/debug pins on my new Shelly i3.
...which made me wonder: can HAA be installed from stock firmware by [using the same trick they use here](https://github.com/mongoose-os-apps/shelly-homekit#updating-from-stock-firmware)?

**Comment by pfandrade** [comment]
This is an excellent question. Would make flashing devices so much easier.

**Comment by brymonster** [comment]
No kidding, especially for those devices that are stuck on lower HAA unable to update OTA. I still haven't had the time to reflash them manually!
But OTA initial install would be a removing a huge barrier to entry into the HAA system.

**Comment by wayn3** [comment]
I think this can be used as an intermediate firmware to jump to HAA https://github.com/yaourdt/mgos-to-tasmota

_however I haven’t tried it_

**Comment by RavenSystem** [comment]
https://github.com/yaourdt/mgos-to-tasmota
