### ISSUE TITLE
MagicHome One-color Controller

### ISSUE THREAD

**Issue by ptath** [RavenSystem/esp-homekit-devices#1056]
Lightbulb
15: White
```
{"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"w":15,"b":[{"g":0}]}]}
```
Why can't we to edit Wiki? =)

**Comment by hire-vladimir** [comment]
you can add your config to https://github.com/RavenSystem/esp-homekit-devices/issues/689

**Comment by mafyata** [comment]
Can someone tell me the code for HAA v12? I have 3 Magic Home single color controllers and want to flash with HAA.
