### ISSUE TITLE
8. Garage Door with siri

### ISSUE THREAD

**Issue by hmbarbosa** [RavenSystem/esp-homekit-devices#106]
Hi just a question re the garage door.. When door closed if you ask Siri to close garage will open instead of Siri recognise that us alread closed... Same if open... Anyway to avoid this? 

Cheers

**Comment by RavenSystem** [comment]
It is necessary to add a control feature in the firmware to avois this. Stay tuned, a bug fix in on the way.

**Comment by RavenSystem** [comment]
Try version 0.5.2.

**Comment by hmbarbosa** [comment]
Thanks Mate!! seems all good now!!! Ill keep testing any problem ill let you know.

Cheers
Beto

**Comment by RavenSystem** [comment]
Many thanks for your feedback!
