### ISSUE TITLE
Request for magichome RGBWW

### ISSUE THREAD

**Issue by toshibochan** [RavenSystem/esp-homekit-devices#1062]
I try magichome RGBW from exemple here and work good. But from this setup when I turn on white color the cold white(RGB) and the warm led turn on. But I have RGBWW led strip and I want only the W be on when white color is on. Anyone know how I can do that?

**Comment by toshibochan** [comment]
Anyone can help?

**Comment by toshibochan** [comment]
Hi @RavenSystem you can look this https://github.com/maccoylton/esp-homekit-rgbw-strip.  Maccoylton Magichome version have pure white opinion in he’s code. I was using he’s code but it keep loosing connection to homekit. So I start using yours today. But I love to have pure white if possible. Can you take look he’s version and try to and in yours magichome version. Please
Thank you for sharing amazing work with us.

**Comment by kevinjohncutler** [comment]
Shoot, I'm also trying to figure this out.
