### ISSUE TITLE
Múltiples sensores de temperatura DS18B20

### ISSUE THREAD

**Issue by viccur** [RavenSystem/esp-homekit-devices#107]
Hola.
Estoy entusiasmado con tu trabajo. Estoy a punto de prescindir de homebridge.
Me gustaría saber si considerarías útil (y posible) poner varios sensores de temperatura DS18B20 en bus con una sola entrada (GPIO) para tener varias lecturas de temperatura diferentes con un solo Sonoff.
Muchas gracias.

**Comment by pandarek** [comment]
The Si7021 temperature / humidity sensor will work?

**Comment by RavenSystem** [comment]
@viccur Tendría que pensarlo, porque ahora mismo el código está orientado a usar un único sensor  de temperatura, pero por supuesto que es posible. 

@pandarek it doesn’t work: 
https://github.com/RavenSystem/esp-homekit-devices/issues/77
