### ISSUE TITLE
Sonoff Mini not accessible via web after adding to HK

### ISSUE THREAD

**Issue by avatar25pl** [RavenSystem/esp-homekit-devices#1071]
I installed HAA using OTA to sonoff mini. 

After that all worked and added device to HomeKit. 
However I want to change Json config but now cannot connect to Setup page anymore. 
I was flicking power without any success to restore setup screen. 
I installed another one and when added to homekit it is no longer available via web? 

Is there any way to restore web access to device without flashing?

**Comment by peros550** [comment]
The web access is not always on. You have to bring your device into this state. 
You can try switching your device on / off very quick for around 8 times (I always try more, it never hurts)  and it will eventually go into set up mode. In this mode, the web access is activated and your device is not responding in home app.

**Comment by avatar25pl** [comment]
I tried to switch 20 times power without any luck. It is still connected to wifi but not setup page :( 
What is the point of having reset homekit ID option if I cannot even access it?

**Comment by avatar25pl** [comment]
Thanks. It works finally.
