### ISSUE TITLE
Sonoff Basic R2 use GPIO2: External toggle.not work after the power is restored

### ISSUE THREAD

**Issue by pro19hsu** [RavenSystem/esp-homekit-devices#1075]
GPIO2 is connected to GND, Sonoff Basic R2 cannot be turned on.
When the power fails, GPIO2 is connected to GND, and it will not work after the power is restored.
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":2},{"g":2,"t":0}]}]}

**Comment by pilot1981** [comment]
If isn’t so good use GPIO2 ... you have to way to solve it:
- use GPIO2 with pulled up
- use another GPIO...


Please see here:

https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

**Comment by pro19hsu** [comment]
Thank you for the information.
I know what to do.
