### ISSUE TITLE
shelly 2.5 as a roller shutter with external pushbuttons needs a double click

### ISSUE THREAD

**Issue by Leonoerlemans** [RavenSystem/esp-homekit-devices#1079]
Hi,

Still most grateful for this firmware.
How come that I need to push my momentary switch twice to get it into action (as well up as down). When I update by pushing the buttons 8 times and then wait, that problem is gone, but after a day or so the problem returns and I need to do it again.
Have you a solution?

I used  the exact json from the provided device database

Kind regards,

Leon

**Comment by Leonoerlemans** [comment]
Hi!

Does anyone else have or had  this problem or has a solution?

Kind regards

Leon

**Comment by Leonoerlemans** [comment]
@RavenSystem I am sorry to nag about it, but do you have an idea what is causing this problem?

Kind regards,

Leon

**Comment by RavenSystem** [comment]
I am not able to replicate your issue.
