### ISSUE TITLE
18b20 temperature sensor

### ISSUE THREAD

**Issue by stepanyurkiv** [RavenSystem/esp-homekit-devices#108]
18b20 temperature sensor, temprature is recognized well, only after some time the device is not seen in homekit (Version 0.5.0; 0.5.1; 0.5.2) in modes    5. Thermostat;   6. Switch Basic + TH Sensor; 9. Socket + Button + TH Sensor.

**Comment by accessoremoto** [comment]
I have same problem with 18b20 and firmware 0.5.2

**Comment by RavenSystem** [comment]
How much time is necessary to get the issue?

**Comment by stepanyurkiv** [comment]
As soon as I choose one of the modes, sometimes longer, but after some time it becomes invisible in the homekit. 18B20 soldered permanently and other modes in which there is no temperature measurement is good.

**Comment by stepanyurkiv** [comment]
https://drive.google.com/file/d/1ogiFAZkTc7b3oypwDsPPYgiDbLMF-b9N/view?usp=sharing

**Comment by stepanyurkiv** [comment]
Already works an hour. OK! I watch next.
