### ISSUE TITLE
Shelly 1 Setup Mode

### ISSUE THREAD

**Issue by luckyclan** [RavenSystem/esp-homekit-devices#1080]
I configured Shelly 1 as Contact Sensor, without any additional button.
How can i now return to Setup Mode?

**Comment by Murdrock** [comment]
Straight from wiki:


Emergency Setup Mode: If a device has its power cut or freezes within 3 seconds of boot, next time it boots it will go directly to setup mode.

So unplug, plug, unplug, plug and you are good to go.

**Comment by luckyclan** [comment]
Thanks, it worked! However i had to connect/disconnect the cable instead of plug-unolug the adapter, probably because my ac/dc apapter holds voltage for some time after unplugging.
