### ISSUE TITLE
Problem to load info from HAA device using iOS app Controller for HomeKit 

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#1081]
Hi,
I’m using iOS controller for HomeKit to backup HomeKit configuration:

https://apps.apple.com/it/app/controller-for-homekit/id1198176727

But this app isn’t able to load information related to HAA devices...

There is some standard/protocol not already deployed In HAA firmware?

**Comment by peros550** [comment]
in case you haven't tried, it would be a good idea to also contact the developer of the app about this. I remember I had a question about the way the backup function used to work and emailed them. They responded within a few days.

**Comment by pilot1981** [comment]
Thanks @peros550, I already contacted app developer, I’m waiting for an answer...

**Comment by pilot1981** [comment]
Hi @RavenSystem,
Developer answered:

“I guess the problem with HAA is that there is no serial number set.”

It’s possible have serial number set in our HAA devices?

**Comment by RavenSystem** [comment]
HAA devices have serial number. You can see it under accessory details.

**Comment by pilot1981** [comment]
I’m waiting for update from app developer

**Comment by pilot1981** [comment]
App developer don’t answer...

I notice app read serial number of dummy switch HAA and official HomeKit devices, but not for real HAA devices...

I don’t understand...

**Comment by pilot1981** [comment]
@RavenSystem you think last version 3.5 can fix this problem? Changing the use of serial number?! I will try...

**Comment by pilot1981** [comment]
Issue related to serial number problem. Solved in HAA version 3.5
