### ISSUE TITLE
No wifi hotspot. Sonoff basin R3

### ISSUE THREAD

**Issue by toddc01b** [RavenSystem/esp-homekit-devices#1082]
I’m new to this.
 I have just tried to flash Sonoff basic R3 using NodeMCU PyFlasher and the latest “fullhaaboot.bin”. It says “firmware successfully flashed” but once I re-apply power I can’t seem to find the wifi hotspot for the Sonoff. Also the wifi light on the Sonoff remains off. 
Any help would be much appreciated.

**Comment by Murdrock** [comment]
The light remains off that's normal. You don't see the HAASOMTHING hotspot;

**Comment by toddc01b** [comment]
Thanks for the reply. 
Yes that's correct. I can't see the hotspot which means I can't configure it and connect it to my wifi. 
Any suggestions?

**Comment by Murdrock** [comment]
Well it seems like a dead end... maybe someone with more experience could help. You seem to do the steps correct....

**Comment by Murdrock** [comment]
Any screen shoot of the flash program before flahsing?
