### ISSUE TITLE
Question: Light switch (i.e. on/off without dimmer function)

### ISSUE THREAD

**Issue by rjblake** [RavenSystem/esp-homekit-devices#1085]
Added a Light (Type 30) but it is non-dimmable. Is the only way to get it as an on/off type (i.e. without any dimmer slider) to specify it as (Type 1)?

**Comment by wayn3** [comment]
Yeah set as type 1 then change the icon to a light bulb in Homekit

**Comment by rjblake** [comment]
@wayn3 - thanks for the confirmation. Already amended as such. Question can be closed
