### ISSUE TITLE
magic home rgb controller JSON problem

### ISSUE THREAD

**Issue by exrector** [RavenSystem/esp-homekit-devices#1090]
The standard code works but has a mix of R, G and V colors:
{"c": {"q": 850,"b": [{"g": 0,"t": 5}]},"a": [{"t": 30,"r": 12,"g": 5,"v": 13,"b": [{"g": 0}]}]} 
I only changed digits and the device does not appear to connect to homekit:
{"c": {"q": 850,"b": [{"g": 0,"t": 5}]},"a": [{"t": 30,"r": 5,”g”: 13,”v”: 12, ”b”: [{"g": 0}]}]} - (this sequence is correct)

**What is the problem????????**

**Comment by gonzabur** [comment]
You have a problem with the semicolons. Try to use plain text.

**Comment by xrust83** [comment]
Возможно кавычки от пустой раскладки не подходят ;-)

**Comment by exrector** [comment]
Thanks to everyone who responded and gave me hints. I've removed all the spaces. Will change only numerical values. The code worked!

`{"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":5,"g":12,"v":13,"b":[{"g":0}]}]}`

**Comment by xrust83** [comment]
Так ото ж
