### ISSUE TITLE
Pls Help Config Tuya TYMC-1 Door Window Sensor

### ISSUE THREAD

**Issue by genging** [RavenSystem/esp-homekit-devices#1093]
I Have Tuya TYMC-1 Door Window Sensor With HAA v.4 2.5.7

GPIO01 | Tuya Tx
GPIO03 | Tuya Rx

[16:05:32] tele/contact_01/RESULT {"TuyaReceived"{"Data":"55AA0005000501010001000C","Cmnd":5,"CmndData":"0101000100"}}
[16:05:32] stat/contact_01/RESULT {"POWER":"OFF"}
[16:05:32] stat/contact_01/POWER OFF

[16:05:33] tele/contact_01/RESULT {"TuyaReceived{"Data":"55AA0005000501010001010D","Cmnd":5,"CmndData":"0101000101"}}
[16:05:33] stat/contact_01/RESULT {"POWER":"ON"}
[16:05:33] stat/contact_01/POWER ON

My config Is Not work
{"c":{"1":0,"o":3,"r":[{"n":0,"s":9600}]},"a":[{"0":{"u":[{"v":"55AA0005000501010001000C"}]},"1":{"u":[{"v":"55AA0005000501010001010D"}]},"t":5,"s":0}]}

**Comment by wayn3** [comment]
Hey Genging,

Currently HAA can only push serial commands but not receive them, since you want to read the status of a window or door via serial this is currently not possible, see this issue

https://github.com/RavenSystem/esp-homekit-devices/issues/915

**Comment by peros550** [comment]
Just wondering, how good is this sensor from a battery life perspective?

**Comment by genging** [comment]
> Just wondering, how good is this sensor from a battery life perspective?
I have 5 devices, 3 tasmota installations, operate through MQTT.
4 months and the battery is still not dead
Open and close the door approximately 20 times a day.

**Comment by genging** [comment]
> Hey Genging,
> 
> Currently HAA can only push serial commands but not receive them, since you want to read the status of a window or door via serial this is currently not possible, see this issue
> 
> #915

Thank you very much, I'm still waiting.
