### ISSUE TITLE
After succesfull flash, no HAA-XXXX wifi accesspoint

### ISSUE THREAD

**Issue by PJDamen** [RavenSystem/esp-homekit-devices#1095]
After succesfully flashing two sonoff mini's v1.2 (no DIY header) to the latest HAA firmware and restarting it the HAA-XXXX wifi accesspoint doesn't appear. Tried everything but I'm clueless. I have succesfully flashed (in the past) and currently using 5 other modules but they are still running on HAA 0.3.5.

Any suggetions would be appreciated!

**Comment by wrx5** [comment]
Hi,

I wonder how did you solve it?? I used DOUT as well but no luck.

C:\Python\Python38-32\Scripts>esptool.py.exe -p COM3 --baud 115200 write_flash -fs 1MB -fm dout -ff 40m 0x0 fullhaaboot.bin
esptool.py v2.8
Serial port com3
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
Crystal is 26MHz
MAC: 2c:6a🆎05:9d:3b
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Compressed 401388 bytes to 284499...
Wrote 401388 bytes (284499 compressed) at 0x00000000 in 25.4 seconds (effective 126.6 kbit/s)...
Hash of data verified.
