### ISSUE TITLE
Air Quality Sensor

### ISSUE THREAD

**Issue by ericklil** [RavenSystem/esp-homekit-devices#1098]
Hello José,

Is there a chance you may add an Air Quality Sensor to the [Sensors](https://github.com/RavenSystem/esp-homekit-devices/wiki/Sensors) section in one of the future updates:

#### From the Homekit Accessory Protocol:
`9.70 Air Quality. Paired, Read, Notify
uint8
0 5 1
 0 "Unknown" 1 "Excellent" 2 "Good"
3 "Fair"
4 "Inferior" 5 "Poor"`

[Air Quality Sensor on Amazon.es](https://www.amazon.es/Waveshare-Dust-Sensor-GP2Y1010AU0F-Conditioner/dp/B07P94LCFZ/ref=sr_1_3?__mk_es_ES=ÅMÅŽÕÑ&dchild=1&keywords=Pm2.5+Sensor+Pm2.5+Air+Particle+Monitor&qid=1598203280&sr=8-3)

**Comment by RavenSystem** [comment]
I have plans to add MQ-135 support, and I2C bus too. But now I have not much time for coding.
