### ISSUE TITLE
wdt reset

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#110]
I get this error when I press the temperature increase button.
Sometimes and at random, can someone tell me what the problem is ?

Here is the code -  https://github.com/Kristian8606/homeKitThermostat/tree/master/src 

> ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x40100000, len 2292, room 16

0x40100000: _stext at ??:?

tail 4
chksum 0x57
load 0x3ffe8000, len 772, room 4
tail 0
chksum 0x0b
csum 0x0b

**Comment by RavenSystem** [comment]
Maybe a hardware problem. Try to attach button to another GPIO.

**Comment by Kristian8606** [comment]
When I increase the wait time of ssd1306_task and I press the button quickly and repeatedly I get another error.

> ets Jan 8 2013,rst cause:2, boot mode:(3,7)
