### ISSUE TITLE
REQUEST: Sonoff SV as a simple "push button" for opening gate

### ISSUE THREAD

**Issue by Gejza75** [RavenSystem/esp-homekit-devices#1100]
Can someone generate JSON for **Sonoff SV** which work as a simple push button - ON/OFF in a 0,5 seconds, please? No additional sensors, nothing. Just simple push button. Thank you very much.

**Comment by NikDevx** [comment]
> Can someone generate JSON for **Sonoff SV** which work as a simple push button - ON/OFF in a 0,5 seconds, please? No additional sensors, nothing. Just simple push button. Thank you very much.

https://github.com/RavenSystem/esp-homekit-devices/wiki/Stateless-Button

You can user configurator https://glumb.github.io/haa-configurator/

**Comment by Gejza75** [comment]
Thanks Nik. Tried but without success.. I tried to modify Garage Door, but it works just partly. I would be greatful, if someone would help me with that.

Thank you very much for any help!

**Comment by QDUNI** [comment]
Do you mean a switch ?

**Comment by QDUNI** [comment]
Do you mean a physical push button? Or a push button in the home app?

**Comment by QDUNI** [comment]
Try this config of a stateless button: 

`{
  "c": {
    "b": [{ "g": 0, "t": 5 }]
  },
  "a": [{
    "t": 3,
    "0": {"r":[{"g":12,"v":1,"i":0.5}]},
    "f0": [{ "g": 0, "t": 1 }]
  }]
}`

**In one line:**

`{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":3,"0":{"r":[{"g":12,"v":1,"i":0.5}]},"f0":[{"g":0,"t":1}]}]}`

**Comment by Gejza75** [comment]
Hi all. After couple of testing and playing I found formula. And finally it works like I wanted. Here it is:

{"c": {"l": 13,"b": [{"g": 0,"t": 5}]},"a": [{"0": {"r": [{"g": 12}]},"1": {"r": [{"g": 12,"v": 1}]}, "b": [{"g": 0,"t": 2,"p": 0,"i": 0}],"s": 0,"i": 0.2}]}

Thanks to all, who try to help. If there is possibility, please put it in device database.

Thank you.
