### ISSUE TITLE
Lightbulb PWM frequency maximum is 76Hz

### ISSUE THREAD

**Issue by blaxwan01** [RavenSystem/esp-homekit-devices#1102]
Json parameter "q" is definitely working but quite unpredictable because I can set values less then 76 Hz in Setup Mode and I see the difference on oscilloscope and even with naked eye its not actually that I set up before, BUT I cant make it greater than 76Hz. Any thoughts?

**Comment by blaxwan01** [comment]
How to increase pwm frequency to any value greater than 76Hz? I'm puzzled

**Comment by RavenSystem** [comment]
Since HAA v5.0.0, I use my own PWM driver. Now it works as expected.

**Comment by blaxwan01** [comment]
thank you, sent some € to you)
