### ISSUE TITLE
Garage Door

### ISSUE THREAD

**Issue by stepanyurkiv** [RavenSystem/esp-homekit-devices#111]
I break the garage door, go out of HomeKit and go in again and the gate opens, why?

**Comment by RavenSystem** [comment]
Can you provide more details, please.

**Comment by RavenSystem** [comment]
What version are you using actually? Did prior version work right? Has this issue begun after something concrete?

**Comment by stepanyurkiv** [comment]
0.5.3

**Comment by RavenSystem** [comment]
Did prior version work right?
Has this issue begun after something concrete?

**Comment by stepanyurkiv** [comment]
yes, to 0.5

**Comment by RavenSystem** [comment]
Can you provide logs when opening Home App in your iPhone?

**Comment by stepanyurkiv** [comment]
I know how to do it on the iPhone

**Comment by stepanyurkiv** [comment]
0.5.4. now good.

**Comment by RavenSystem** [comment]
Many thanks for your feedback!
