### ISSUE TITLE
unreachable due to hue bridge? 

### ISSUE THREAD

**Issue by QDUNI** [RavenSystem/esp-homekit-devices#1110]
Hi, 

I just installed racencore on a Sonoff SV and used it as a garage opener.
Now it worked great for a few days until I plugged in my hue bridge.... very often the garage opener is unavailable. When I unplug my hue bridge from power, the Sonoff SV will work stable. Its a very annoying issue because I need both accessoires to work. any idea how I can fix this? 

thnx !

**Comment by WizBangCrash** [comment]
Hi @QDUNI,
It might be that your WiFi and Zigbee RF channels are interfering with each other. Its worth reading [this](https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence) article to understand how to separate the two.
