### ISSUE TITLE
BUG: Garage door logic - opened vs. opening

### ISSUE THREAD

**Issue by rjblake** [RavenSystem/esp-homekit-devices#1111]
When using HomeKit to open/close the door, behaviour seems normal (i.e. from Closed->Opening->Opened (then notification)) and vice versa. However, if you use the actual garage door opener (e.g. remote), it goes from Closed->Opening (immediate notification that door was opened despite status in HomeKit still showing 'Opening'. i.e. does not wait for sensor input to actually confirm door is opened. When closing door with remote, the sequence is correct (Open->Closing->Closed (then notification)). I have 2 magnetic sensors (for open & closed state).

JSON
`{"c":{"n":"garagecontroller","u":0,"l":2,"b":[{"g":0,"t":5}]},"a":[{"t":40,"d":18,"s":5,"0":{"r":[{"g":12,"v":1,"i":0.5},{"g":12,"v":1}]},"1":{"a":0},"2":{"r":[{"g":12,"i":1.5},{"g":12,"v":1,"i":0.5},{"g":12,"v":1,"i":2}]},"3":{"a":2},"f3":[{"g":5,"t":0}],"f4":[{"g":5}],"f2":[{"g":4,"t":0}],"f5":[{"g":4}],"b":[{"g":0}]},{"1":{"s":[{"a":1}]}},{"t":1,"s":5,"0":{"r":[{"g":14,"v":1}]},"1":{"r":[{"g":14,"v":0}]}}]}`

**Comment by gitigit6** [comment]
very similar problem,  it goes from Closed->Opening  (and stays very long on status "opening", and
It takes very long till "opened" does appear) 
problem is same with original remote and with iphone
I have 1 sensor for closed state
