### ISSUE TITLE
Zemismart 2 gang light swtich (esp8285) - no HAA-XXXX wifi accesspoint

### ISSUE THREAD

**Issue by wrx5** [RavenSystem/esp-homekit-devices#1112]
I have successfully flashed the device with v3.0.1 fullhaaboot.bin however I cannot see the wifi. (I have erased it before flashing)

If I flash it with tasmota.bin it works without an issue.

According to this video it is possible: https://www.youtube.com/watch?v=n0jWtVfp_Xk

Could you help? Here is the flashing results

C:\Python\Python38-32\Scripts>esptool.py.exe -p COM3 erase_flash
esptool.py v2.8
Serial port com3
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
Crystal is 26MHz
MAC: 2c:6a:ab:05:9d:3b
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 1.3s
Hard resetting via RTS pin...

C:\Python\Python38-32\Scripts>esptool.py.exe -p COM3 --baud 115200 write_flash -fs 1MB -fm dout -ff 40m 0x0 fullhaaboot.bin
esptool.py v2.8
Serial port com3
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
Crystal is 26MHz
MAC: 2c:6a:ab:05:9d:3b
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Compressed 401388 bytes to 284499...
Wrote 401388 bytes (284499 compressed) at 0x00000000 in 25.4 seconds (effective 126.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**Comment by L4RGER** [comment]
Have you tried uploading fullhaaboot.bin from tasmota front end?

**Comment by wrx5** [comment]
Once tasmota was up and running I found upgrade option which I tried it for fullhaaaboot.bin. Process was successful but same result no wifi. 

did I do wrong?
