### ISSUE TITLE
Sonoff POW R2

### ISSUE THREAD

**Issue by alifarooq1991** [RavenSystem/esp-homekit-devices#1122]
Please anyone share json for sonoff pow with power measurement

**Comment by d0minikh** [comment]
+1 would be nice to get it to work :)

**Comment by RavenSystem** [comment]
Sorry, it uses UART and it's not supported.

**Comment by i3laze** [comment]
Although it might work as a generic HAA-switch, you will loose the metering functionality.
Check Sonoff POW GPIO, if needed:
https://templates.blakadder.com/sonoff_Pow_R2.html

**Comment by i3laze** [comment]
Maybe, maybe there could be some inspiration in Tasmota code? 
They support Pow R2 with CSE7766 chip for years:
https://github.com/arendst/Tasmota/blob/5e805e0c4ac1304bfe86a3abd1b6b99b7dda2daa/tasmota/xnrg_02_cse7766.ino

**Comment by Aaqu** [comment]
I can become a tester when the release comes out

**Comment by novellaip** [comment]
Jumping wire from CSE7759B PIN CF to ESP8285 I05 (I04) can monitor the power only.

**Comment by i3laze** [comment]
@RavenSystem still no change of mind on UART? Got two POW R2 units for tests.

**Comment by tonysprenk** [comment]
> @RavenSystem still no change of mind on UART? Got two POW R2 units for tests.

Reading serial commands is a confirmed feature coming in HAA 10.0!

**Comment by rg2k** [comment]
Any chance this is now working with HAA 10 being released?

**Comment by MukatP** [comment]
Sonoff POW 1 v. 2.0 works on HHA 12. in App Home it does not show parameters. Works as a switch. Everything is in the HAA Home Manager app.

**Comment by i3laze** [comment]
@RavenSystem , sorry for necroposting.
Amy updates on power measurement via UART since?

**Comment by vglucas** [comment]
Script MEPLHAA
Sonoff Pow Power Monitoring Switch Module

https://github.com/RavenSystem/esp-homekit-devices/discussions/2294
