### ISSUE TITLE
RGBW & RGB CW WW bulbs flicker when turning on using wall switch ("s":1)

### ISSUE THREAD

**Issue by peros550** [RavenSystem/esp-homekit-devices#1125]
Hi guys. I have a little issue with two bulbs RGBW & RGB-CW-WW. For the RGBW I have the below json : {"c":{"n":"Led-BW-LT21","u":1,"b":[{"g":0}]},"a":[{"t":30,"r":14,"g":12,"v":5,"w":15,"b":[{"g":0}]}]} which works fine. Today I thought I would add automatic turn on after power failure. So I did a slight change to the json as follows: {"c":{"n":"Led-BW-LT21","u":1,"b":[{"g":0}]},"a":[{"t":30,**"s":1**,"r":14,"g":12,"v":5,"w":15,"b":[{"g":0}]}]}

So here is the thing. When I turn on the bulb using my wall switch, the bulb turns on, but it goes into a flickering state. The flickering effect is not so drastic, meaning you can barely see it  but it's definitely there. If I control the bulb through the homekit , then it turns on normally without flickering. Any ideas why that happens? I should note that my bulb is on firmware 1.6.4 as I can't upgrade it due to the github issue but same issue found on bulb running 2.5.7.

**Comment by knowsnotmuch** [comment]
Hello @peros550 - I have this same issue - what did you need to do to fix this?
