### ISSUE TITLE
OTA update from HAA 1.3.1 to latest

### ISSUE THREAD

**Issue by kafes33** [RavenSystem/esp-homekit-devices#1126]
Hi, is it possible OTA update from HAA 1.3.1 to latest? 
My devices is still on 1.3.1:(
I set it update mode, I set up OTA update, nothing happen and devices  is after reboot still on 1.3.1. 
did I miss something? I'm doing something wrong?

Thanx a lot

**Comment by Kienz** [comment]
No, it's not possible.
See https://github.com/RavenSystem/esp-homekit-devices/issues/825
