### ISSUE TITLE
Shelly dimmer 2

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#1128]
I could not find an answer to the question Shelly dimmer 2 will work with HAA?

**Comment by ndv27** [comment]
Sure, just use for config JSON from Shelly Dimmer from the Device database. It's works.

**Comment by jerzytraczynski** [comment]
Are you sure?
https://github.com/RavenSystem/esp-homekit-devices/issues/497

**Comment by RavenSystem** [comment]
I have not a Shelly Dimmer 2, but I think that UART commands will be same like Dimmer 1.
