### ISSUE TITLE
Add support for AС (air conditioner)

### ISSUE THREAD

**Issue by NikDevx** [RavenSystem/esp-homekit-devices#1129]
Hello, @RavenSystem!
Thanks you for this amazing work!
Will you be adding AC support in the future?

**Comment by hillaliy** [comment]
Hi HAA support AC.
see wiki, thermostat 25

**Comment by NikDevx** [comment]
> Hi HAA support AC.
> see wiki, thermostat 25

Hi 
Homekit has different interface and device type fo AC

https://developer.apple.com/homekit/specification/

**Comment by RavenSystem** [comment]
There is not any new HomeKit interface for AC since summer 2019.

**Comment by NikDevx** [comment]
> There is not any new HomeKit interface for AC since summer 2019.

Does the thermostat and AC have the same function?

**Comment by pro19hsu** [comment]
> 自2019年夏季以來，AC沒有任何新的HomeKit接口。

The working mode of HAA Infra Red is different from that of my air-conditioning remote control Infra Red.
My air-conditioning remote will send Config at once.
Is there a corresponding setting method?

**Comment by pro19hsu** [comment]
> There is not any new HomeKit interface for AC since summer 2019.

The working mode of HAA Infra Red is different from that of general air-conditioning remote control Infra Red.
Generally, the air-conditioning remote control will send Config once.
Is there a corresponding setting method?

**Comment by pro19hsu** [comment]
> There is not any new HomeKit interface for AC since summer 2019.

@RavenSystem 
The working mode of HAA Infra Red is different from that of general air-conditioning remote control Infra Red.
Generally, the air-conditioning remote control will send Config once.
Is there a corresponding setting method?

**Comment by RavenSystem** [comment]
I don't know how General Electric AC works. HAA has been tested with Mitsubishi, Daikin, Fujitsu, Samsung and others similar AC managed by IR. If General AC works with a special system sending config only once and does not allow to send full commands each time, it can be difficult to manage with HAA. You can send several commands at same time, with a custom delay, it could work with General AC, but you must try it.
