### ISSUE TITLE
Question with: "Removed needed of resseting HomeKit ID when JSON has changed HomeKit data."

### ISSUE THREAD

**Issue by tlagarto** [RavenSystem/esp-homekit-devices#1136]
In one of the latest change logs, one ca read:
Home Accessory Architect v3.0.1
"Removed needed of resseting HomeKit ID when JSON has changed HomeKit data."

I'm not sure what this means.
Can I change the JSON string from 1 button to 2 buttons without having to reset the HomKit ID?

Example:
A Sonoff mini working as simple switch in HomeKit.
Now I want to change it to a switch with external toggle (by changing the Json string).
Do I have to reset the HomeKit ID? Or just change the JSON and save it?

**Comment by Murdrock** [comment]
Anyone know?
