### ISSUE TITLE
Offset Temp

### ISSUE THREAD

**Issue by accessoremoto** [RavenSystem/esp-homekit-devices#114]
Hi, it's possible add an offset (-10 / + 10 ° C) to temperature read on config menu? Regards

**Comment by RavenSystem** [comment]
Yes, but why?

**Comment by accessoremoto** [comment]
for probe calibration

**Comment by RavenSystem** [comment]
Added to [TODO list](https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List).

**Comment by accessoremoto** [comment]
Ok thank's. Great job
