### ISSUE TITLE
iOS14 - Valve Timers

### ISSUE THREAD

**Issue by lfiocco** [RavenSystem/esp-homekit-devices#1140]
Hello. Has anyone else noticed that the valves can now only stay open for 5-10 minutes in iOS 14? is this Apple trying to save the planet? (again)

**Comment by GuyCoast** [comment]
Same problem and also not possible insert water valve in the automation

**Comment by ss83** [comment]
I have the same issue atm.
Was there any solution? Within the eve app I can choose a longer time.
