### ISSUE TITLE
Please examples for doorbell

### ISSUE THREAD

**Issue by toshibochan** [RavenSystem/esp-homekit-devices#1144]
Anyone have examples for push button for doorbell config?

**Comment by toshibochan** [comment]
Doorbell button can trigger camera? I want doorbell send existing homekit security cameras as doorbell.

**Comment by shanghaix** [comment]
Yes you can do that, using the homebridge camera plugin, when someone presses on a switch that you can define it will send a notification with a capture from your camera.

**Comment by bj-tracer** [comment]
"This accessory works like a binary sensor, and it only sends a notification when status 0 is reached."
It sends notification like a door or window switch, I think.

**Comment by toshibochan** [comment]
I have homekit compatible camera so I no need plugin for the camera. I just need the button to trigger the notification

**Comment by bj-tracer** [comment]
> I have homekit compatible camera so I no need plugin for the camera. I just need the button to trigger the notification

Try to place cam and button to the same room at the Home app.

**Comment by toshibochan** [comment]
I did but not working

**Comment by pilot1981** [comment]
it's possibile to have an example of HAA JSON of doorbell without using homebridge??

**Comment by ooomakon** [comment]
{"c":{"b":[{"g":0,"t":5}],"l":13},"a":[{"t":13,"s":0,"f1":[{"g":14,"t":1}],"i":2}]}

**Comment by RavenSystem** [comment]
Doorbell example accessory, with button connected to GPIO 14:

`{"t":13,"f0":[{"g":14}]}`

**Comment by toshibochan** [comment]
Thanks I will try later. I need to buy more esp8266.

**Comment by pilot1981** [comment]
So it’s better to add a dummy switch to enter easily in setup mode?!

**Comment by bj-tracer** [comment]
Yesterday test this.
It can't to activate any camera because HK see it like interkom or camera.
If you try to change a settings for this device at HK then app faulting.
It sends notification only and nothing else.

**Comment by lukasa1993** [comment]
@RavenSystem any update on this ? it seems ios doenst accept button as doorbell camera is required
