### ISSUE TITLE
Sonoff Basic New Board Layout

### ISSUE THREAD

**Issue by pandarek** [RavenSystem/esp-homekit-devices#115]
"GPIO14 is not inuse anymore. Instead you can use GPIO2 labled as IO2 on the board."
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Basic

Can you implement the GPIO14 or GPIO2 selection configuration for the new sonoff? The idea is that GPIO2 has the same functionality (toggle) as GPIO14.

More info and photo:
https://github.com/arendst/Sonoff-Tasmota/issues/4515

**Comment by RavenSystem** [comment]
Of course.

**Comment by pandarek** [comment]
A similar situation will be with TH Sensor and Sonoff Basic without GPIO14

**Comment by RavenSystem** [comment]
Added to [TODO List](https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List).

**Comment by RavenSystem** [comment]
@triak3ak if you want help to install Tasmota firmware, ask on Tasmota web.

**Comment by RavenSystem** [comment]
@pandarek try v0.5.5 for new board layout.

**Comment by wroblewski6** [comment]
So for this moment if I have new sonoff basic I am not able to use it with your firmware with wall switch connected to gpio14 and gnd?? And there is no option to change It to gpio02 at this moment in your setup ??
