### ISSUE TITLE
Esooli light switch analogous to sonoff T1

### ISSUE THREAD

**Issue by ArchiMsk** [RavenSystem/esp-homekit-devices#1154]
![5ACC6E3E-EBA5-4CA0-9696-A90D2A20ECC0](https://user-images.githubusercontent.com/72271963/94952613-af59c680-04ff-11eb-9324-41650edbeded.jpeg)
After flashing, the switch often becomes unavailable in homekit, brand Esooli switch, firmware 3.4.6. Other sonoff switches work in homekit without problems.
![52666427-2CC0-443F-8298-E12631F454C2](https://user-images.githubusercontent.com/72271963/94952872-17101180-0500-11eb-8304-c4eef5e0d8c3.jpeg)

**Comment by nickforev** [comment]
Press and hold the sensor for about 15-17 seconds (if there is a buzzer on the board, it will beep once, and after 5 seconds a double beep).
After that, find your switch for mac and ip, and go to the setup page, tick the reset wifi and reset homekit id.
save.
Then find a new HAA network and set up as new ...

**Comment by mixza2** [comment]
Can someone throw me json for this switch ?(1gang)
