### ISSUE TITLE
Issue with WIKI. "Example of double lock mechanism" seems 

### ISSUE THREAD

**Issue by peking84** [RavenSystem/esp-homekit-devices#1155]
Following discord conversation: 
https://discord.com/channels/594630635696553994/594630635696553996/761561240896012289

@WizBangCrash:

Wiki problems found. 
Explanation and proposed solution below.
Please doublecheck and correct those when you have time. :beers: 

Ref:
https://github.com/RavenSystem/esp-homekit-devices/wiki/Lock-Mechanism

"Example of double lock mechanism" is misleading and seems bahaving differently than described.

Issue 0) 
 Type t:44 instead of t:4

Issue 1)
Single lock uses an inverted button, where 
   Switch ON "1" inverted -> action 0 -> Unlock with inching
 Switch OFF "0" inverted -> action 1 -> Lock

Double lock uses notification to trigger type44 action 0/1 and action 2/3.
 Switch 1 OFF acc2 action 0 -> acc1 action 0 -> LOCK1 / Unlock with inching
   Switch 1 ON acc2 action 1 -> acc1 action 1 -> LOCK1 / Lock

 Switch 2 OFF acc3 action 0 -> acc1 action 2 -> LOCK2 / Unlock with inching
   Switch 2 ON acc3 action 1 -> acc1 action 3 -> LOCK2 / Lock mechanism

acc2 and acc3 should trigger the inverted ones

Issue 2) 
There is no "i2" parameter. Inching won't work for the second lock.

header.h gave the hint what to use instead in the documentation
    #define AUTOSWITCH_TIME                     "i"
    #define AUTOSWITCH_TIME_1                   "i1"

I'm attaching a JSON worked for me as a reference that matches the described example in the wiki.
Tested on NodeMCUv3.

{"c":{"o":4,"b":[{"g":0,"t":3}]},"a":[{"t":44,"i":3,"i1":10,"0":{"r":[{"g":4,"v":1,"i":0.5}]},"1":{"r":[{"g":4}]},"2":{"r":[{"g":12,"v":1,"i":0.5}]},"3":{"r":[{"g":12}]}},{"t":1,"0":{"m":[{"g":1,"v":1}]},"1":{"m":[{"g":1,"v":0}]}},{"t":1,"0":{"m":[{"g":1,"v":3}]},"1":{"m":[{"g":1,"v":2}]}},{"t":1,"0":{},"1":{"s":[{"a":1}]}}]}

**Comment by WizBangCrash** [comment]
@peking84 Thanks for the feedback. I have reviewed and added your suggested fixes to the Lock Mechanism Wiki page.
