### ISSUE TITLE
Feature Request: Button for Wild Cards

### ISSUE THREAD

**Issue by wayn3** [RavenSystem/esp-homekit-devices#1160]
In the same way that you can have a button to toggle between actions 1 and 0 I would like the ability to declare a button that cycles through Wild Card actions

A use case for this is a fan speed button, each click of the button increases the speed, when there are no more wild card actions the first wild card is selected

**Comment by L4RGER** [comment]
This would be handy!

**Comment by wayn3** [comment]
☝🏼

**Comment by wayn3** [comment]
.

**Comment by L4RGER** [comment]
Still want this!

**Comment by wayn3** [comment]
.

**Comment by wayn3** [comment]
this would still be nice (if it hasn't already been implemented)
