### ISSUE TITLE
Carbon Dioxide Sensor

### ISSUE THREAD

**Issue by Friseurazubi** [RavenSystem/esp-homekit-devices#1163]
Wich piece of hardware ist supported for carbon dioxide and how do I configure it?

**Comment by gerarddvb** [comment]
Ive had an Wemos D1 mini with Me Gas Sensor MQ2.
If you wire the digital output of the gas sensor to GPIO 5 it should work iirc.

{"c":{"o":0},"a":[{"t":10,"s":0,"f0":[{"g":5,"t":1,"i":1}],"i":60}]}
