### ISSUE TITLE
Thermostat (type 25) issue after iPadOS/iOS.. 14 update

### ISSUE THREAD

**Issue by paulzhdanov** [RavenSystem/esp-homekit-devices#1167]
Good morning,
I found an issue with Thermostat (type 25). I have thermostat virtually connected to boiler with a simple automation: if thermostat turns on -> turn on boiler. It was tested in Aug and everything was perfect before (I guess) AppleTV update. Thermostat works as usual and turns on, but there is no reactions on boiler side. The issue was not obvious for me, I checked older firmware flased from scratch, but later I found the reason: thermostat operates with 4 parameters - inactive, idle, heating, cooling. In HK there are only 2 parameters: on/off in native HK automation is useless, it just do nothing. To make it work you have to use 3rd party software kinda HK Controller to create automation with proper states: if ( thermostat is active and thermostat state is heating ) -> run scene to ... 

I wonder if it's possible to update your firmware to have proper states in native HK? As I wrote now it's 4 of them.

PS For those guys who use wired connection of thermostat, everything goes fine as it was before, issue related to virtual connections only

**Comment by RavenSystem** [comment]
Sorry, it is not possible. Only Apple can do it.
