### ISSUE TITLE
Change Wi-Fi settings, how?

### ISSUE THREAD

**Issue by komarofleo** [RavenSystem/esp-homekit-devices#1168]
Anybody pls, help. How can I change the wi-fi settings after flashing?!
My steps:
1. Input via browser http://HAA-number.local
2. Remove wifi settings
3. Entering setup mode - AP + 192.168.4.1 
4. Input new ssd and wifi password and hit save and... NOTHING (chip not rebooting)
So I cant change wi-fi settings. 

screenshots on usb to 
![IMG_7004](https://user-images.githubusercontent.com/66205833/95924299-03965d80-0dc0-11eb-82a2-7e9b17ccbde2.jpg)
![IMG_7003](https://user-images.githubusercontent.com/66205833/95924336-13ae3d00-0dc0-11eb-912c-89889609644e.PNG)
![IMG_7002](https://user-images.githubusercontent.com/66205833/95924346-1741c400-0dc0-11eb-8a21-b587de8ed9f3.PNG)
![IMG_7001](https://user-images.githubusercontent.com/66205833/95924359-1c9f0e80-0dc0-11eb-81c1-57ad22d9f0e6.jpg)
![IMG_6999](https://user-images.githubusercontent.com/66205833/95924397-2e80b180-0dc0-11eb-829d-42348434d82e.PNG)

monitor and phone screen are attached here...

**Comment by rjblake** [comment]
I've found in the past if the JSON is not correct it would not save. Share the JSON?

**Comment by komarofleo** [comment]
JSON is correct and perfectly works 
{
  "c": { "l": 0, "b": [{ "g": 2, "p": 0, "t": 5 }] },
  "a": [{
    "t": 45,
    "o": 1,
    "c": 1,
    "f": 10,
    "0": { "r": [{ "g": 15, "v": 1 }, { "g": 4 }] },
    "1": { "r": [{ "g": 15 }, { "g": 4, "v": 1 }] },
    "2": { "r": [{ "g": 15 }, { "g": 4 }] },
    "3": { "r": [{ "g": 15, "i": 1 }, { "g": 4 }] },
    "4": { "r": [{ "g": 15 }, { "g": 4, "i": 1 }] },
    "f0": [{ "g": 5, "p": 0 }],
    "f1": [{ "g": 13, "p": 0 }],
    "f2": [{ "g": 5, "t": 0 }, { "g": 13, "t": 0 }]
  }]
}

**Comment by komarofleo** [comment]
The problem is absent in previous version, So I cant change wifi (

**Comment by rjblake** [comment]
Odd - I've just changed the WiFi to another SSID on my network. It saved without issue, ESP8266 restarted and connected to new SSID. Went back in and changed again and working correctly. I did this through Chrome browser on Mac, did not tick the box "Remove WiFi Settings", just selected the new SSID and entered password

**Comment by komarofleo** [comment]
Can you tell me - how you have entered to setup mode?
And how did you connected to web interface of esp (haa-xxx or 192.168.4.1)

**Comment by rjblake** [comment]
To enter setup mode, I have a button configured in HomeKit, but I also tried using Emergency (press Reset button on ESP8266 twice within 3 seconds). For the initial connection I accessed using 192.168.4.1 and after that the IP address assigned from my DHCP server

From a new install on the ESP8266:
1. Restart the ESP8266, on computer connect WiFi to device (192.168.4.1)
2. Configure JSON as needed
3. Click on "WiFi Networks" button to refresh SSIDs available
4. Select SSID and enter password for network
5. Click on "Save"
6. Device restarts and connects to network
7. To change network connection from this stage, restart device (press reset 2x on ESP8266 in less than 3 secs)
8. Connect using browser to assigned IP and change as needed. If at different location, I'd start from step 1

**Comment by komarofleo** [comment]
Thank u, I've done it 100 times before and all was vonderfull. But now - I can't pass the 5-th step - when I press SAVE (green button) - it is stack and nothing happens, data not saved. I was trying 5 different modules, sad....

**Comment by rjblake** [comment]
Did you try going back to earlier version?

**Comment by komarofleo** [comment]
How can I do it? Is it possible to downgrade? Please teel me!

**Comment by rjblake** [comment]
You can download an earlier version you know worked from this link [here](https://github.com/RavenSystem/haa/releases). The go through the initial install using 
`esptool.py -p /dev/<your_ESPPort> erase_flash`
`esptool.py -p /dev/<your_ESPPort> --baud 115200 write_flash -fs 1MB -fm dout -ff 40m 0x0 fullhaaboot.bin`
with the version of `fullhaaboot.bin` you downloaded. Then follow instructions under "Installation without OTA"
Make sure to untick Auto OTA updates (just in case). Alternatively add all files to a "Custom Server" so I can easily change to a different version if needed

**Comment by komarofleo** [comment]
Thanx a lot man - I will try!

**Comment by rjblake** [comment]
Also use compact JSON to save white space and memory:
`{"c":{"l":0,"b":[{"g":2,"p":0,"t":5}]},"a":[{"t":45,"o":1,"c":1,"f":10,"0":{"r":[{"g":15,"v":1},{"g":4}]},"1":{"r":[{"g":15},{"g":4,"v":1}]},"2":{"r":[{"g":15},{"g":4}]},"3":{"r":[{"g":15,"i":1},{"g":4}]},"4":{"r":[{"g":15},{"g":4,"i":1}]},"f0":[{"g":5,"p":0}],"f1":[{"g":13,"p":0}],"f2":[{"g":5,"t":0},{"g":13,"t":0}]}]}`

**Comment by Partizan7676** [comment]
@komarofleo try to make settings as far as possible from wifi - it helps in my case. dont know why, but better use 3.5.8 - is more stable. a open an issue for that. todays 3.5.10 also have that bug - device no response, only if access it on its AP(to which device is connected)

**Comment by komarofleo** [comment]
So I can definitely say - When I hit Reset WiFi - I can't then press Save button and update wifi settings - it does/nt respond and dont want to reboot with new wi-f- config.

**Comment by komarofleo** [comment]
So - thanx all of you. I finally found the solution. It's work perfect for me.
1. I have flashed with old version 3-3-3 wihout OTA
2. All works perfect - wifi settings are stored easy!!!

Thank you all - wish for somebody it will be useful.

**Comment by komarofleo** [comment]
rjblake - thank you man!!! Can you text me via social network (whatsup or viber pls. or mail me - 80509048505@mail.ru)

**Comment by Partizan7676** [comment]
try 3.5.8 and get same issue - settings not saved. flashing 3.3.3 - settings are apply, but device dont have remote access. i.e. i switch my iphone to LTE network and get no response from 3.3.3. what is strange it is connected to the same AP as device with firmware 3.5.8 and one device response, other not. any idea?

**Comment by Partizan7676** [comment]
got it!
This must be included in wiki as preparation stage. in my case domain was not "local" it was ubnt and i add ubnt.local so that is out of rules for mDNS. thats all ))) check it simple. for ex you add device HAA-xxxx, just try to ping it by its name with .local ie HAA-xxxx.local when it says unable to resolve name - it means that your local domain is different and multicast to 224.0.0.251 port 5353 UDP are blocked.
@RavenSystem you fully described router config, but that moment will be great to add to wiki too

**Comment by rjblake** [comment]
> try 3.5.8 and get same issue - settings not saved. flashing 3.3.3 - settings are apply, but device dont have remote access. i.e. i switch my iphone to LTE network and get no response from 3.3.3. what is strange it is connected to the same AP as device with firmware 3.5.8 and one device response, other not. any idea?

@Partizan7676 - since you are using Ubiquiti equipment (not sure what firmware versions or controller version), you may want to check the following (had issues with my IoT devices):

Under Settings->Wireless Networks->Advanced, look for PMF and make sure it is Disabled (unless of course you need it for other reasons). In my case this solved some problems. I have 2x test devices running on 3.5.10 and have no issues with "no response" or changing and saving changes to WiFi

**Comment by peros550** [comment]
guys I have the same issue. I am unable to flash by wire. Did you find any solution?

**Comment by Partizan7676** [comment]
@peros550 check mDNS in your network

**Comment by peros550** [comment]
@Partizan7676 I have a device which I tried to configure on an another SSID. I tried reset wifi settings, and now the device always startup on setup mode and announce its AP. When I connect to it , it searches for available wifi settings, I try to select a new on but the device does not save my settings, hence it remains in AP mode. 

Does all this make sense to you? mDNS would be an option if the device was connected to my router, but that's not the case :(

**Comment by komarofleo** [comment]
New release where launched just now - be happy )))

**Comment by ali199011** [comment]
Wi‑Fi

**Comment by ali199011** [comment]
sky.net/status

**Comment by ali199011** [comment]
sky.net/status
