### ISSUE TITLE
Please add support for Sonoff 1 Channel Inching /self-locking WiFi Wireless Switch 5V 12V

### ISSUE THREAD

**Issue by smsroman** [RavenSystem/esp-homekit-devices#117]
It's hard to flash but many of us need it badly!
https://www.itead.cc/inching-self-locking-wifi-wireless-switch.html

**Comment by smsroman** [comment]
No. Is it worth trying?

**Comment by GPL71** [comment]
@RavenSystem @smsroman 
Hi boys ....
Have you news about this device?
Is it compatible with ravencore? I've 3 of them
Please can you advise me if it is compatible and how to enter in flash mode
Thank you!!!

**Comment by GPL71** [comment]
@smsroman another user @lizzus did it 
the @RavenSystem work fine.
you have a bistable relay and when you push the button on the board you have an inching closing
