### ISSUE TITLE
WIKI change - add alternative installation for Mac users

### ISSUE THREAD

**Issue by rjblake** [RavenSystem/esp-homekit-devices#1183]
@WizBangCrash - perhaps you can update Wiki to include alternative tool/method to install. I have been using NodeMCU-PyFlasher-4.0 to install with great success (on Adafruit and NodeMCU ESP8266). Tool can be downloaded from [here](https://github.com/marcelstoer/nodemcu-pyflasher/releases/latest) and there are versions for Mac, Win32 and Win64. All versions have a UI and usage is self explanatory.

**Comment by WizBangCrash** [comment]
@rjblake Thanks for the suggestion. I have added it to the list of 3rd party install tools.
