### ISSUE TITLE
how to turn a light with ESP without wifi (home away)

### ISSUE THREAD

**Issue by fadi9696** [RavenSystem/esp-homekit-devices#1191]
I just done the ESP homekit and its working perfectly, but i want to control it outside my home without wifi (with 4G)
Which portforwarding should  i use on my router ?

**Comment by aleroot** [comment]
You just need an HomeKit hub in your home: https://support.apple.com/en-us/HT207057

**Comment by bj-tracer** [comment]
You will not be able to use them without Wi-Fi a priori.
ESP is a wi-fi based system.
