### ISSUE TITLE
MagicHome RGB Controller Issue

### ISSUE THREAD

**Issue by epicsepi** [RavenSystem/esp-homekit-devices#1200]
I have 3 same MagicHome RGB controller, and 3-4 different LED strip. I tried some json, but doesnt working all color in one time. 
![2AB62ACB-B97F-4A30-A632-6ED81AB31C64](https://user-images.githubusercontent.com/73914360/98046255-2b5e6b80-1e2a-11eb-8085-9c42e6314d38.png)
![9757F25F-C3D5-4B27-96C7-F137DA7E7DCA](https://user-images.githubusercontent.com/73914360/98046267-2ef1f280-1e2a-11eb-8609-73f4c072514d.jpeg)
![CE61E2EF-B4F6-467A-ACEE-9E5E438F69D6](https://user-images.githubusercontent.com/73914360/98046271-30bbb600-1e2a-11eb-8b0f-77c7d46ead04.jpeg)

Red doesnt lightning, why?

**Comment by wayn3** [comment]
Guessing the config for the red led is setup with the wrong gpio?

**Comment by epicsepi** [comment]
Its possible. But, i dont know what I have to do. Where Can I change the gpio?

**Comment by wayn3** [comment]
In your json config, post it here and I'll show you

**Comment by wayn3** [comment]
Taking a guess, this is what I would expect (including a virtual switch to enter setup mode)
```
{
	"c":{
		"n":"MagicHomeRGB"
	},
	"a":[{
		"t":30,
		"r":5,
		"g":12,
		"v":13
	},{
		"1":{"s":[{"a":1}]},
		"i":0.5
	}]
}

**Comment by epicsepi** [comment]
{"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":15,"g":13,"v":12,"b":[{"g":0}]}]}

I saw this in device database. Thank you very much!!!

**Comment by epicsepi** [comment]
Ok, its working. Red is red, blue is blue, green is green, but white (middle of the color scale) is not close to white. Its light purple. What I have to change in the json, to get true white? Thanks!!!! 

this is the json, what you told: {"c":{"n":"MagicHomeRGB"},"a":[{"t":30,"r":5,"g":12,"v":13},{"1":{"s":[{"a":1}]},"i":0.5}]}

**Comment by wayn3** [comment]
RGB strips never really produce a great white light, often ends up blue~ish, you could try setting factors but I haven’t use this functionality

https://github.com/RavenSystem/esp-homekit-devices/wiki/Lightbulb#RGBW-Factor

**Comment by epicsepi** [comment]
Okey, no problem!! Thank you all!! You saved my life!!🙌🙌😋
