### ISSUE TITLE
Feature Request: Support MCP9808 Temperature sensors (I2C)

### ISSUE THREAD

**Issue by rjblake** [RavenSystem/esp-homekit-devices#1205]
Would be great if support for the MCP9808 temperature sensors could be added. They are accurate and fairly simple. ESPHome included - [repo here](https://github.com/esphome/esphome/tree/dev/esphome/components/mcp9808) as reference

**Comment by RavenSystem** [comment]
Better, post it in Discussions. But currently I have not any plan for this sensor.
