### ISSUE TITLE
Factory reset, wifi change

### ISSUE THREAD

**Issue by arturlukosek** [RavenSystem/esp-homekit-devices#1208]
I do have a sonoff basic with dry contact and door sensor to open and close the gate. Since I have changed the router cant put the sonoff back to the mode I can set the new wifi password. 
How to reset on the device to get to the wifi configuration settings?

**Comment by rbrtsluk** [comment]
> I do have a sonoff basic with dry contact and door sensor to open and close the gate. Since I have changed the router cant put the sonoff back to the mode I can set the new wifi password.
> How to reset on the device to get to the wifi configuration settings?

Hey mate can I do this with a basic r3?
Do you have a tutorial you went by or you just know what your doing?

**Comment by xrust83** [comment]
8 times quickly turn on turn off the relay, then go to the IP in the browser
