### ISSUE TITLE
Improving thermostat logic 

### ISSUE THREAD

**Issue by axxxkh** [RavenSystem/esp-homekit-devices#1209]
Hi. I have gas-fired boiler and haa thermostat. When I set up target temperature for example to 19° and deadband set to 1, thermostat start heating on 18.5 and stops on 19.5, but radiators stay hot for some time and temperature continue rising for about 0.5° and reach almost 20° 
So question, it’s possible to make two deadbands 
![0CF73AA3-B062-4F0B-BF43-8DB726A83EF5](https://user-images.githubusercontent.com/72781301/98934116-41cf8b80-24ea-11eb-89fb-b8906858c598.jpeg)

Like deadband 1 is 0.8 deadband 2 0.2, so in this case if setpoint is 19.0°, thermostat will start heating at 18.2° and stop heating at 19.2° And real temperature will rise to 19.6-19.7°

**Comment by xrust83** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Thermostat

Isn't that something in the parameters  (df) and (ds)?
