### ISSUE TITLE
Great core for homekit! ..and for Amazon Alexa?

### ISSUE THREAD

**Issue by manimac79** [RavenSystem/esp-homekit-devices#121]
Superb! this firmware makes all Sonoff the perfect partners for Homekit, It's possible to make compatible with Amazon Echo too? Should be a line on the to do list :-)

**Comment by RavenSystem** [comment]
Sorry, but this firmware is and will be HomeKit, only HomeKit, and forever HomeKit. For performance and security reasons, it will be only HomeKit forever and ever.

**Comment by manimac79** [comment]
You know what? I agree with you :-)
