### ISSUE TITLE
Support request: Nodemcu + HC-SR501 PIR sensor

### ISSUE THREAD

**Issue by csupi003** [RavenSystem/esp-homekit-devices#1210]
Hi, 

Is there anyone who had success with HC-SR501 sensor? 

I tried a few options but it doesn't work. 

Thanks in advance,

**Comment by vsidlu** [comment]
Hi!

json - {"c":{"o":1,"l":2,"i":1,"n":"table-motion","b":[{"g":0,"t":1}]},"a":[{"t":12,"i":10,"f1":[{"g":13,"p":0,"i":1,"t":0}]}]}

See PIR VCC connection in picture.

![IMG_5035](https://user-images.githubusercontent.com/30963646/98975134-69404b80-251e-11eb-8d7d-7e4e9a4b3259.jpg)

![IMG_5036](https://user-images.githubusercontent.com/30963646/98975206-8117cf80-251e-11eb-9e5a-ad5ac84205cc.jpg)

**Comment by csupi003** [comment]
@vsidlu Thanks a lot, works perfectly.
