### ISSUE TITLE
Accessory type - window

### ISSUE THREAD

**Issue by navoye** [RavenSystem/esp-homekit-devices#1218]
Can You please add accessory type - window? I'm using Sonoff 2CH as window covering witch external push buton to control my roof windows. It would be nice to see them as a windows.

**Comment by xrust83** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/General-Configuration#homekit-device-category

**Comment by xrust83** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Window-Covering
