### ISSUE TITLE
MagicHome RGB Controller help!!!

### ISSUE THREAD

**Issue by epicsepi** [RavenSystem/esp-homekit-devices#1219]
I have two MagicHome RGB controller, but I got 4 swiches in Home app: The two standard rgb switch + two single on/off switch (doesn’t works) I can’t delete this two unnecessary switch. I think thease are the bridges or something?!...?!!!

I think JSON is the problem. Current JSON:

{"c":{"n":"MagicHomeRGB"},"a":[{"t":30,"r":5,"g":12,"v":13},{"1":{"s":[{"a":1}]},"i":0.5}]}
![BAA7A3ED-A23A-4772-B824-8660A9E56D4A](https://user-images.githubusercontent.com/73914360/99829989-5270a900-2b5d-11eb-9af9-db45965a63c6.jpeg)

Please help me how to delete these.

**Comment by pilot1981** [comment]
Perhaps, they Are dummy switch to enter in setup mode?! Please group them in a separate room to Maintanance purpose!

**Comment by Kristian8606** [comment]
Remove it from JSON and it will disappear

**Comment by epicsepi** [comment]
> Remove it from JSON and it will disappear

Ok, but how? What I have to remove from Json?

**Comment by Kristian8606** [comment]
Try this code
`{
  "c": 
  {
    "n": "MagicHomeRGB"
  },
  "a": 
  {
    "t": 30,
    "r": 5,
    "g": 12,
    "v": 13
  }
} `

**Comment by Kristian8606** [comment]
I'm not sure if it works since I edited it over the phone

**Comment by wayn3** [comment]
### With setup switch (current)
```
{
	"c":{
		"n":"MagicHomeRGB"
	},
	"a":[{
		"t":30,
		"r":5,
		"g":12,
		"v":13
	},{
		"1":{"s":[{"a":1}]},
		"i":0.5
	}]
}
```
### without setup switch
```
{
	"c":{
		"n":"MagicHomeRGB"
	},
	"a":[{
		"t":30,
		"r":5,
		"g":12,
		"v":13
	}]
}
```
