### ISSUE TITLE
Timbre 

### ISSUE THREAD

**Issue by arturodiazad1** [RavenSystem/esp-homekit-devices#122]
Hola, habría posibilidad de utilizar el Sonoff sv como timbre y abridor de puerta? Sería crear el accesorio timbre conectándolo a una de las entradas el pulsador  y en la salida de relé conectarlo a la apertura de la cerradura o con el sonoff basico pulsador para accionar el timbre y salida de relé para conectarlo a a un dispositivo sonoro con corriente ac

**Comment by RavenSystem** [comment]
¿El timbre no lo había quitado Apple de su lista de tipos de accesorio?

**Comment by arturodiazad1** [comment]
Ahhh, he estado leyendo y es verdad. Si vuelve a ponerlo estaría bien hacerlo, a mi me iría genial,  gracias.
