### ISSUE TITLE
Sonoff TH LED blue 

### ISSUE THREAD

**Issue by pixidixi88** [RavenSystem/esp-homekit-devices#1228]
Hello,
I would like to use blue LED in my Sonoff TH and present it in the home app as standard switch. It doesn't work. What is wrong with below json.

Thank You!

{
  "c": {
    "b": [
      {
        "g": 0,
        "t": 5
      }
    ]
  },
  "a": [
    {
      "0": {
        "r": [
          {
            "g": 12
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 12,
            "v": 1
          }
        ]
      },
      "b": [],
      "s": 0
    },
    {
      "0": {
        "r": [
          {
            "g": 13,
            "v": 1
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 13,
            "v": 0
          }
        ]
      },
      "t": 1,
      "b": [],
      "s": 0,
      "f0": []
    },
    {
      "t": 3,
      "b": [],
      "s": 0,
      "f0": [
        {
          "g": 0,
          "t": 1
        }
      ],
      "f1": [
        {
          "g": 0,
          "t": 2
        }
      ],
      "f2": [
        {
          "g": 0,
          "t": 3
        }
      ]
    }
  ]
}

**Comment by xrust83** [comment]
{"c":{"b":[{"g":0,"t":5}],"l":13},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[],"s":0},{"0":{" r ":[{" g ":13," v ":1}]}," 1 ":{" r ":[{"g":13,"v":0}]},"t":1,"b":[],"s":0,"f0":[]},{"t":3,"b":[],"s":0,"f0":[{"g":0,"t":1}],"f1":[{"g":0,"t":2}],"f2":[{"g":0,"t":3}]}]}

https://glumb.github.io/haa-configurator/

**Comment by pixidixi88** [comment]
Yes, I did it in the configurator and also copy paste from above post but still it doesn't work.

**Comment by xrust83** [comment]
{"c":{"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12},{"g":13,"v":0}]},"1":{"r":[{"g":12,"v":1},{"g":13,"v":1}]},"b":[],"s":0},{"t":3,"b":[],"s":0,"f0":[{"g":0,"t":1}],"f1":[{"g":0,"t":2}],"f2":[{"g":0,"t":3}]}]}
