### ISSUE TITLE
[QUESTION] One physical button managing window states

### ISSUE THREAD

**Issue by fcrespo82** [RavenSystem/esp-homekit-devices#1238]
Hi folks. I'm building a custom device with HAA support. Is it possible to have one physical button manage the states of a window covering on HAA depending of its state? 

Eg. On a closed window covering, first push open, second push stop, third push close and in a opened window do the reverse

I'm new to HAA and trying to figure if this is possible...

**Comment by fcrespo82** [comment]
Pinging @RavenSystem, can you help me understand this?

**Comment by RavenSystem** [comment]
Declare your button GPIO with "b":[{"g":your_gpio}]

**Comment by fcrespo82** [comment]
Actually what I was looking for was the window covering State inputs. Just made it work today.

Thank you for the firmware!
