### ISSUE TITLE
List/report of devices wih HAA versions

### ISSUE THREAD

**Issue by wrx5** [RavenSystem/esp-homekit-devices#1239]
Hi All,

I have 27 light switches around the house with HAA OTA firmware. Is there way to see their firmware version without put it into setup mode and connect one by one?

**Comment by tonysprenk** [comment]
You can see it in settings in the home app.

**Comment by tonysprenk** [comment]
Long press the accessory and swipe down.

**Comment by pilot1981** [comment]
You can see both from Apple home app? Firmware HAA version and HAAT OTA version?

**Comment by wrx5** [comment]
Hi Guys,

thanks for the responses. What I am after is not one by one approach. I was planning to write a simple HTML page where it accesses each device with a URL to get a response. 

For example: 

http://192.168.1.10/status.html?name
http://192.168.1.10/status.html?version

I can do this for all devices on one page to see all together instead of doing it one by one.

Thanks

**Comment by wrx5** [comment]
> 
> 
> Hi Guys,
> 
> thanks for the responses. What I am after is not one by one approach. I was planning to write a simple HTML page where it accesses each device with a URL to get a response.
> 
> For example:
> 
> http://192.168.1.10/status.html?name
> http://192.168.1.10/status.html?version
> 
> I can do this for all devices on one page to see all together instead of doing it one by one.
> 
> Thanks

No Luck with this?
