### ISSUE TITLE
Question: Basic sonoff switch

### ISSUE THREAD

**Issue by lars05** [RavenSystem/esp-homekit-devices#124]
Hi

I've read the wiki, but did not find any answer to my question. 

I am currently using a different homekit software on my sonoff basics but missing the following function. 
Is it possible to get the function as described below?

light switch off -> light switch on -> sonoff on
Regardless the last state of the sonoff (either on or off), the sonoff would be on when getting electricity.

Just as any Ikea Tradfri or Hue lamps. 

Currently it is impossible to turn on the sonoff without using homekit. My girlfriend and any guest hates this :) 

Thank you

**Comment by RavenSystem** [comment]
From the Wiki:

> light switch off -> light switch on -> sonoff on

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#gpio14-toggle-default-off

> Regardless the last state of the sonoff (either on or off), the sonoff would be on when getting electricity.

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#init-state-sw1-4-default-0
