### ISSUE TITLE
Water Valve Sonoff 4ch Pro

### ISSUE THREAD

**Issue by STijeras91** [RavenSystem/esp-homekit-devices#125]
Buenas!

Ante todo muchísimas felicidades por tu trabajazo, te comento, me gustaría poner el SonOff 4ch Pro con los cuatros canales en modo Válvula de Agua, el motivo de no usar SonOff Basic's es que las electrovalvulas funcionan a 24v y seria un engorro hacer la instalación con los Basic's, existiría la posibilidad de hacer lo que te comento?

Muchisimas gracias!

**Comment by RavenSystem** [comment]
No, lo siento. Controlar 4 válvulas de agua supone mucha carga de trabajo para un sólo esp8266: https://github.com/RavenSystem/esp-homekit-devices/issues/98

Puesto que vas a tener que usar una fuente de alimentación de 24V para las válvulas, lo que yo te recomiendo es que uses 4 Sonoff SV, que pueden funcionar a 24V y puedes aislar fácilmente el relé. Mira el "Isolated mode": https://www.itead.cc/wiki/Sonoff_SV
