### ISSUE TITLE
Garage Door Wiki GPIO5 and TH

### ISSUE THREAD

**Issue by pandarek** [RavenSystem/esp-homekit-devices#126]
Hello, in the Garage Door wiki at the Has Opened Sensor point you write about GPIO5 but in the code I did not find GPIO5 use for Garage Door. Maybe you can use GPIO5 for TH? It would be very useful to me;)

It would also be useful if the device type was only TH, with a GPIO selection for the sensor.
Good job José 👍

**Comment by pandarek** [comment]
one more thing about GIPO5, you can add the choice of using "OBSTRUCTION_DETECT" from homekit characteristic and add functionality to the code.

**Comment by RavenSystem** [comment]
OBSTRUCTION_DETECT will be added in a future release. But if you want a TH, you will must use another device.
