### ISSUE TITLE
Wemos D1 mini lock

### ISSUE THREAD

**Issue by arjunaukta** [RavenSystem/esp-homekit-devices#1261]
I am using a wemos D1 mini as a lock accessory but everytime when the wemos powers up the relay is triggered once. The json I am using is

{"c":{"l":2},"a":[{"t":4,"i":3,"0":{"r":[{"g":5,"v":1,"i":5}]},"1":{"r":[{"g":5}]}}]}

What changes should be made to the string to ensure the relay isn’t triggers in case the wemos restarts after a power failure event?

**Comment by arjunaukta** [comment]
Are we still addressing issues related to the firmware?

**Comment by DFC1990** [comment]
{"c":{"l":2,"cd":2},"a":[{"t":4,"i":3,"0":{"r":[{"g":5,"v":1,"i":5}]},"1":{"r":[{"g":5}]}}]}

Try this Code :)

**Comment by arjunaukta** [comment]
Did you mean “CT”:2 the wiki doesn’t talk about “cd” anywhere?
