### ISSUE TITLE
Update through Home App

### ISSUE THREAD

**Issue by macjl** [RavenSystem/esp-homekit-devices#1263]
Hello,

Since iOS 14.3, it seems there is the possibility to update Homekit Devices through Home App. The device that need an update can appear in Home Settings/Updates, like an HomePod.

I don't really know how this is working, but it could be a great way for updating HAA devices, without using dedicated switches.

**Comment by buarle** [comment]
This would be a awesome feature on top of this great code!

**Comment by aleroot** [comment]
This issue should not be closed

**Comment by RavenSystem** [comment]
Don't worry. I am interested personally.
