### ISSUE TITLE
Problem Configuration

### ISSUE THREAD

**Issue by TheReiner** [RavenSystem/esp-homekit-devices#1267]
Hi,

Firs, english is not my native language...
i have this problem, i have a bulb CW-WW, but my configuration don't work. After save, the bulb reboot on setup mode.

{“c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"cw":14,"ww":12,"b":[{"g":0}]},{"t":1,"1":{"s":[{"a":1}]}}]}

Thanks a lot :)

**Comment by RavenSystem** [comment]
First quote has a bad format.

**Comment by TheReiner** [comment]
Ok... It's better ^^
No reboot on setup mode, but my bulb don't work. Nothing ...

If i use this configuration like RGB
{"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":14,"g":12,"v":5,"b":[{"g":0}]},{"t":1,"1":{"s":[{"a":1}]}}]}
It's work .. But with bad colour (it's Logic ^^)

How to do that ? is it possible like this ?
![Screenshot 2020-12-20 at 21 12 50](https://user-images.githubusercontent.com/18024918/102723463-52083100-4308-11eb-9838-ba337e081df2.png)

**Comment by TheReiner** [comment]
Hi,
No Solution for me ?
Thanks :)

**Comment by Kienz** [comment]
Some people are working on better colors - there is also a beta HAA version. You can join the Discord chat https://discord.gg/v8hyxj2 (Channel "lightning").
In the latest beta 5.50.13 is a bug - so don't use this and wait until next beta is released.
