### ISSUE TITLE
Gate accessory type?

### ISSUE THREAD

**Issue by mariusvasss** [RavenSystem/esp-homekit-devices#1274]
Can we have this accessory like the fibaro gate icon?

**Comment by morphix9** [comment]
Is this a new (official) type?

**Comment by mariusvasss** [comment]
I saw at fibaro an accessory to open gates and they have a nice icon for it. We can program HAA to use it with gates but we don't have the icon.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Window-Covering#covering-type
