### ISSUE TITLE
Question about thread networking

### ISSUE THREAD

**Issue by toshibochan** [RavenSystem/esp-homekit-devices#1276]
Anyone know about thread network? If need new hardware or is just software update? If is just software can be implement here?

**Comment by macjl** [comment]
Hello,

I was wondering the same thing this afternoon. It seems that Thread is based on 802.15.4 physical protocol. Not surest , but I think ESP8266 should not be able to handle it.

But this protocol is the same than Zigbee. So maybe, a Sonoff BASICZBR3 or Sonoff SNZB-01 could be hacked to support it?

**Comment by pilot1981** [comment]
I think it's more related to bluetooth...
