### ISSUE TITLE
Gosund SP111

### ISSUE THREAD

**Issue by xDuk3x** [RavenSystem/esp-homekit-devices#1278]
Hello everybody,

after updating from 3.3.0 to 4.4.3 for the Power measurement update. I Only get the informations for the used Watts, Volts and Amps are showing zero. The Json string is the one from the wiki.

Thanks in Advice
Best Regards
Ronny

**Comment by WojtekWro** [comment]
Hi, try update to the last version. 
I have 4.4.6 right now and it works fine. The JSON string from the wiki as well.

**Comment by lukaszwitkowski** [comment]
Do you have sp111 with working voltage etc meter ? And in what app do you see that power consupmpcion

**Comment by lukaszwitkowski** [comment]
> Hi, try update to the last version. 
> 
> I have 4.4.6 right now and it works fine. The JSON string from the wiki as well. 

Do you have voltage status in home app or only in HAA menager?
