### ISSUE TITLE
 Switch On/Off

### ISSUE THREAD

**Issue by minitoine** [RavenSystem/esp-homekit-devices#128]
Hi,

Could it be possible to add the option to reverse ON/OFF from switch if wanted (e.g. OFF on the Sonoff is seen as ON in Homekit and vice-versa ).
Could be useful for French radiators and other devices where no electric signal means HEAT ON and electric signal means HEAT OFF.

Thanks

**Comment by RavenSystem** [comment]
Added to [TO-DO List](https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List)

**Comment by minitoine** [comment]
Works like a charm. 

:)
