### ISSUE TITLE
Need Help with Router configuration

### ISSUE THREAD

**Issue by sblitzer** [RavenSystem/esp-homekit-devices#1281]
Hi All,

Recently I replaced my router with a new one Asus RT-AX88U.
All HAA devices (41) are perfectly working without any issue, but after firmware update the device never goes online unless I hard reset it or reboot the router.
Please see the attached configuration of 2.4GHz & 5GHz and pro settings.
Any advice? 
<img width="923" alt="Screen Shot 2021-01-02 at 20 47 31" src="https://user-images.githubusercontent.com/44753136/103464569-723ee380-4d3d-11eb-97a0-5fb600a4344b.png">
<img width="942" alt="Screen Shot 2021-01-02 at 20 47 48" src="https://user-images.githubusercontent.com/44753136/103464570-7539d400-4d3d-11eb-95e0-8d34c4894fb1.png">
<img width="769" alt="Screen Shot 2021-01-02 at 20 49 24" src="https://user-images.githubusercontent.com/44753136/103464572-7b2fb500-4d3d-11eb-8a4f-7ed71d048d65.png">

**Comment by Kienz** [comment]
What error occurs? Which device do you want to pair? JSON of the device? Is it pingable?

**Comment by sblitzer** [comment]
I've managed to fix all the issues except one after I perform a firmware update the device never goes online again until I hard reset it (plug off the power and on) or reboot the router.

**Comment by macjl** [comment]
Hello, how long did you wait for the device to reconnect after a firmware update?
I’ve noticed same behaviors with some device, but they’re always reconnect after a while, without doing anything. It can take 15 to 20 mn in my case.

**Comment by sblitzer** [comment]
They never reconnect again unless I hard reset it or reboot the router.
This issue is definitely router configuration because with my old router this never happened
