### ISSUE TITLE
Bug supposed: fan accessory (t: 65) ignores notifications sent by other accessory

### ISSUE THREAD

**Issue by vsevolod-volkov** [RavenSystem/esp-homekit-devices#1288]
HAA v4.5.1, v4.6.1, other version not tested.

v:1 notifications are ignored although v:0 notification produces corresponding 0-action well (fan stop).

```
"a": [
    {
...
    },
    {
      "t": 65,
      "sn": "FAN",
      "0": { "r": [ { "g": 15 } ] },
      "1": { "r": [ { "g": 15, "v": 1 } ], "m": [ { "g": 3, "v": -1 } ] }
    },
    {
      "d": 1200,
      "sn": "FAN-TIMER",
      "0": { "m": [ { "g": 2, "v": 0 } ] },
      "1": { "m": [ { "g": 2, "v": 1 } ] }
    },
...
  ]
```

**Comment by RavenSystem** [comment]
It is not a bug:
`0` is off.
`1` to `100` set fan target speed.
`101` is on.

**Comment by vsevolod-volkov** [comment]
Thank you for fast reply. Have already tested as you suggested - it really works.
May be better to reflect that in accessory 65 notification doc?
<img width="1050" alt="Screenshot 2021-01-11 at 19 07 42" src="https://user-images.githubusercontent.com/57314451/104206272-6095c400-5440-11eb-9f09-6139f61d8357.png">

**Comment by RavenSystem** [comment]
Yes, I see it. Thanks!

**Comment by RavenSystem** [comment]
Done!
