### ISSUE TITLE
New Tuya Smart Life APP WiFi WWCW/RGB/RGBW/RGBCCT LED Strip Controller

### ISSUE THREAD

**Issue by brymonster** [RavenSystem/esp-homekit-devices#1295]
Has anyone successfully flashed [one](https://www.ebay.com/itm/124307977925) of these devices? 
Seems like a much better build than the Magic Home equivalents, plus an external switch. 
Could it be flashed with tuya-convert then HAA?

**Comment by tokamac** [comment]
Can you please show a web page for the product that doesn't expire?
