### ISSUE TITLE
Inverted PWM Logic - possible?

### ISSUE THREAD

**Issue by Fafex** [RavenSystem/esp-homekit-devices#1299]
Hello,

I've got a problem with my self made PWM dimmer. I was using my own "Arduino made" MQTT software but I would love to switch to HAA. 

The problem is that mosfet driving the LED strip is driven by another transistor. Schematic attached
![ESP LED](https://user-images.githubusercontent.com/23432849/104851849-c928e900-58f7-11eb-85a8-73ddffdf3ffb.png)

Here's my config:

`{"c":{"o":1,"l":13,"i":0,"q":850,"b":[{"g":0,"t":5}]},"a":[{"w":4,"t":30,"s":0}]}`

But now the off state gives me 12V on the output, and 100% on gives me 0V.

Is there a way to invert the PWM logic or will I have to do some soldering?

Thanks for any reply.

**Comment by RavenSystem** [comment]
Currently, no. But v5.0 will have that option.

**Comment by RavenSystem** [comment]
Now you can declare PWM GPIOs with inverted logic.
https://github.com/RavenSystem/esp-homekit-devices/wiki/Lightbulb#RGBW-GPIO-Channels
