### ISSUE TITLE
shelly1 bootloop

### ISSUE THREAD

**Issue by borissov** [RavenSystem/esp-homekit-devices#1304]
Hello, 
I install HAA on Shelly1 but get bootloop :( 

My flash settings:

![image](https://user-images.githubusercontent.com/2177740/105509889-ac652a80-5cd6-11eb-87e1-cb2ecaf333d3.png)

This is serial log:

![image](https://user-images.githubusercontent.com/2177740/105510113-f0582f80-5cd6-11eb-832f-b022fae38a6e.png)

Where am I wrong? I think the bootloader is not original from shelly? Thanks in advance!

**Comment by Kristian8606** [comment]
Подозирам, че пишете в паметта, където не би трябвало, това може да бъде причинено от невалидни указатели.

**Comment by borissov** [comment]
> Подозирам, че пишете в паметта, където не би трябвало, това може да бъде причинено от невалидни указатели.

//In Bulgarian: След загубени няколко часа, вероятно става въпрос за проблем със захранването на чипа, но все още не съм го оправил проблема и вече малко се изнервих. Оказва се че или не записва като хората в чипа или не може да буутне. Тъй като нямам друг uart адаптер няма как да тествам, сега съм го закачил на лабораторно захранване, което по принцип е доста точно и тока няма много пулсации и си буутна.

**Comment by Kristian8606** [comment]
Захранването беше следващото ми предложение :)
