### ISSUE TITLE
HTTP Post with XML

### ISSUE THREAD

**Issue by seiken27** [RavenSystem/esp-homekit-devices#1309]
Hey guys

I can see we can do HTTP post with URL's but was wondering if we could HTTP Post with XML.

Sony TV's (android OS) can be controlled via HTTP Post with XML containing IIRCCodes.

I'm assuming content "c" is where it should go but not sure how it should be formatted. Plus with all the commands being like below, it would consume quite a bit of memory. 

Any help would be great :)

*Headers
SOAPACTION: "urn:schemas-sony-com:service:IRCC:1#X_SendIRCC"
X-Auth-PSK: 0000

*Body
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <u:X_SendIRCC xmlns:u="urn:schemas-sony-com:service:IRCC:1">
            <IRCCCode>AAAAAQAAAAEAAAAuAw==</IRCCCode>
        </u:X_SendIRCC>
    </s:Body>
</s:Envelope>

**Comment by zip87** [comment]
I've same issue
