### ISSUE TITLE
Can’t connect to WiFi after setting SSID/password

### ISSUE THREAD

**Issue by caligari74** [RavenSystem/esp-homekit-devices#131]
Hi, first of all thank you for the great software!  After flashing and selecting the SSID and password and then waiting 10 minutes or more, my Sonoff Basic never connects to my home WiFi.  I can’t add it to HomeKit.  The router is an Apple Time capsule.  The AP is always visible (Ravencore-xxxxxx).  Should this disappear when connected?  My authentication on the time capsule is set to WPA/WPA2. Any suggestions?

**Comment by RavenSystem** [comment]
AP should dissapear when device connects to your wifi. 

Can you provide logs, please?

**Comment by caligari74** [comment]
The Time Capsule doesn't have any logs.  Unbelievable.  
I did try to connect it to my iPhone hotspot, and got the same behavior.  I flashed another Sonoff Basic and it behaves the same way.  No connection to WIFI. I haven't had this ever happen with other devices.
Unfortunately I don't have a spare router to try out. 
I'd love to get this working.  Any ideas for things I could try?

**Comment by RavenSystem** [comment]
I was talking about logs from your Sonoff.

**Comment by caligari74** [comment]
**solved**

After checking the log (via screen) I saw the Sonoff was indeed trying to connect to my WIFI:

> no Above&amp;Beyond found, reconnect after 1s
> reconnect
> scandone
> scandone
> reconnect
> RC >>> Toggle Switch manual
> RC >>> Relay 1 -> 0
> scandone
> no Above&amp;Beyond found, reconnect after 1s
> reconnect
> RC >>> Saving last states
> scandone
> no Above&amp;Beyond found, reconnect after 1s
> reconnect

My WIFI SSID is **Above&Beyond**.  I guess the code doesn't like that.  I changed the SSID name to something else and now it works great.  Maybe a fix will come in a future update?
Thanks very much for your help!  Really great software!

**Comment by caligari74** [comment]
Ah boy...the code here won't display what the log showed.  &amp is converted into & the way it should.  Here's a screenshot.
<img width="355" alt="bildschirmfoto 2018-12-13 um 17 56 49" src="https://user-images.githubusercontent.com/45814557/49954339-874f3c80-ff00-11e8-9448-912cc6424c38.png">

**Comment by caligari74** [comment]
Hope this info helps.  Closing this issue.
