### ISSUE TITLE
Shelly uni flash

### ISSUE THREAD

**Issue by pasparakis** [RavenSystem/esp-homekit-devices#1313]
Hi everyone!!! has anyone flashed this device?  any available Json string?![image](https://user-images.githubusercontent.com/74431015/105745354-d886e280-5f46-11eb-89fb-ca01443b6ede.jpeg)
![image](https://user-images.githubusercontent.com/74431015/105745384-df155a00-5f46-11eb-8cc2-4d730d259dc1.jpeg)

https://shelly.cloud/products/shelly-uni-smart-home-automation-device/

**Comment by macjl** [comment]
Hello. I did. Here is my JSON for a window opener with setup mode button. 

`{"c":{"z":0,"o":3,"l":0,"i":0,"0":{"r":[{"g":4},{"g":15}]}},"a":[{"t":45,"w":1,"o":18,"c":14,"0":{"r":[{"g":15,"v":1},{"g":4}]},"1":{"r":[{"g":15},{"g":4,"v":1}]},"2":{"r":[{"g":15},{"g":4}]},"3":{"r":[{"g":15,"i":0.2},{"g":4}]},"4":{"r":[{"g":15},{"g":4,"i":0.2}]}},{"t":1,"1":{"s":[{"a":1}]}}]} `

**Comment by pasparakis** [comment]
Thank you friend!!!

**Comment by pasparakis** [comment]
any json string for doorbell?  has anyone tried it?

**Comment by ra1nb0w** [comment]
Probably the json example of @macjl can be posted to the database's wiki page.
