### ISSUE TITLE
how to make the switch auto turn off after 1 second, using for a door lock please help

### ISSUE THREAD

**Issue by mahdy89** [RavenSystem/esp-homekit-devices#1316]
how to make the switch auto turn off after 1 second, using for a door lock please help

**Comment by mariusvasss** [comment]
here is the JSON

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12,"v":1,"i":1}]},"1":{"r":[{"g":12,"v":0}]},"t":4,"b":[],"s":1,"i":1}]}

i use it on a sonoff mini, you have to change your "g" number if its another device

**Comment by mahdy89** [comment]
thank youuuu, can we make it unlock twice? my door dont open from first try

**Comment by mariusvasss** [comment]
Extend your time, you want 2 pulses?

**Comment by mahdy89** [comment]
yes i want 2 pulse

**Comment by mahdy89** [comment]
are you able to help me with that please? i will be verry thankfull

**Comment by mariusvasss** [comment]
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12,"v":1,"i":1},{"g":12,"v":1,"i":1}]},"1":{"r":[{"g":12,"v":0}]},"t":4,"b":[],"s":1,"i":3}]}

i think this is it. try an confirm!

**Comment by mahdy89** [comment]
tried it.. didnt work :(

**Comment by mariusvasss** [comment]
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12,"i":1},{"g":12,"v":1,"i":1},{"g":12,"v":1,"i":1}]},"1":{"r":[{"g":12,"v":0}]},"t":4,"b":[],"s":1,"i":1}]}

if this doesn't work, i don't know.....

**Comment by mariusvasss** [comment]
It worked?
