### ISSUE TITLE
Dump/backup original firmware

### ISSUE THREAD

**Issue by serial8killer** [RavenSystem/esp-homekit-devices#1318]
Hey Guys, 

Has the title suggests, is there any way to dump or backup in any way the original devices firmware?

It there was it would be easier to experiment with firmware's with different devices.

**Comment by axxxkh** [comment]
Yes, it’s possible, you should make a backup of original firmware. Just google how to do a backup of esp8266. It’s depends what you use. Mac or pc

**Comment by nickforev** [comment]
Hi. From pc, before erase chip, I use esptool.py --port COM8 read_flash 0x00000 0x100000 HAA-.bin
I flash original backup, all works ok.
