### ISSUE TITLE
Tuya Devices

### ISSUE THREAD

**Issue by MarkM500** [RavenSystem/esp-homekit-devices#1319]
Hi,

is it possible to flash Tuya Devices, like Door sensors, leak sensors or fire/smoke sensors?
like this one fror example: https://de.aliexpress.com/item/1005001622897859.html?spm=a2g0s.9042311.0.0.27424c4dWHObjA or this one:
https://de.aliexpress.com/item/4001077711202.html?spm=a2g0s.9042311.0.0.27424c4d2OVSqD

Inside view:
![image](https://user-images.githubusercontent.com/77006589/106031222-5118ab00-60cf-11eb-871c-0a4eb3088fd5.png)

Often the MCU is also working, not only the ESP8266?! How to find out, which GPIO is taken?

Thanks for your ideas.
Would be nice, if something like this is possible.
Mark

**Comment by morphix9** [comment]
What about https://www.npmjs.com/package/homebridge-tuya ?

**Comment by MarkM500** [comment]
Hi thanks for your answer, but it is not possible to integrate "Sensors" in home bridge-tuya, because the problem, that these sensors give only signal with the event and after that they going to sleep.

Mark

**Comment by tonton-RISK** [comment]
> Hi thanks for your answer, but it is not possible to integrate "Sensors" in home bridge-tuya, because the problem, that these sensors give only signal with the event and after that they going to sleep.
> 
> Mark

Hi Mark,

Look this
[<a href='https://www.casimages.com/i/210213050014280790.jpg.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/02/13/210213050014280790.jpg' border='0' alt='Mon image' /></a>](url)

[<a href='https://www.casimages.com/i/210213050002435387.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/02/13/210213050002435387.png' border='0' alt='Mon image' /></a>](url)

json : {"NAME":"TUYA SENSOR","GPIO":[0,107,0,108,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":54}

**Comment by branigan** [comment]
I've flashed multiple tuya devices using tuya convert https://github.com/ct-Open-Source/tuya-convert

**Comment by pilot1981** [comment]
@branigan also tuya devices with lastest firmware? which workaround do you used for it?

**Comment by branigan** [comment]
I flash the firmware about 3 months ago. I don't know version firmware. 
I'use a laptop with ubuntu with wifi as access point. 
I've flashed 2 outlets , 2 switches and 2 outlets with leds (maxcio)

PS: If you want to use door sensor with HomeKit devices you can use Xiaomi sensor with v3 gateway (wifi, zigbee, and bt) that are native compatible with HomeKit from Xiaomi app. (Recently I've buy two and works flaw sly)
door sensor:
https://de.aliexpress.com/item/32749227652.html
gateway:
https://de.aliexpress.com/item/4000493652299.html
