### ISSUE TITLE
nodemcu ch2102 4 relay+motion sensor(HC-SR501) +dht11(Thermometer & Humidity Sensor) sensor haa json code

### ISSUE THREAD

**Issue by irfanumut** [RavenSystem/esp-homekit-devices#1333]
Hello, I wrote such a code, but the device does not appear on the homekit. Where am I doing a mistake? thanks in advance 
Sorry bad english  :(
i Json code: 
{ "c":{ "l":13, "i":1 }, "a":[ {"0":{"r":[{"g":12,"v":0}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0 ,"p":0},{"g": 0,"t":1}]}, {"0":{"r":[{"g":5, "v":0}]},"1":{"r":[{"g":5 ,"v":1}]},"b":[{"g":9 ,"p":0},{"g": 9,"t":1}]}, {"0":{"r":[{"g":4, "v":0}]},"1":{"r":[{"g":4 ,"v":1}]},"b":[{"g":10,"p":0},{"g":10,"t":1}]}, {"0":{"r":[{"g":15,"v":0}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":14,"p":0},{"g":14,"t":1}]}, { "t": 24, "b": [], "g": 16, "n": 1 }, "f0": [ { "g": 1, "t": 0 } ]
Sensors: 
Dht11 thermometer
HC-SR501 motion sensor
4 relay switch

**Comment by pawelosin** [comment]
Try this
{
	"c": {
		"l": 13,
		"i": 1
	},
	"a": [{
		"0": {
			"r": [{
				"g": 12,
				"v": 0
			}]
		},
		"1": {
			"r": [{
				"g": 12,
				"v": 1
			}]
		},
		"b": [{
			"g": 0,
			"p": 0
		}, {
			"g": 0,
			"t": 1
		}]
	}, {
		"0": {
			"r": [{
				"g": 5,
				"v": 0
			}]
		},
		"1": {
			"r": [{
				"g": 5,
				"v": 1
			}]
		},
		"b": [{
			"g": 9,
			"p": 0
		}, {
			"g": 9,
			"t": 1
		}]
	}, {
		"0": {
			"r": [{
				"g": 4,
				"v": 0
			}]
		},
		"1": {
			"r": [{
				"g": 4,
				"v": 1
			}]
		},
		"b": [{
			"g": 10,
			"p": 0
		}, {
			"g": 10,
			"t": 1
		}]
	}, {
		"0": {
			"r": [{
				"g": 15,
				"v": 0
			}]
		},
		"1": {
			"r": [{
				"g": 15,
				"v": 1
			}]
		},
		"b": [{
			"g": 14,
			"p": 0
		}, {
			"g": 14,
			"t": 1
		}]
	}, {
		"t": 24,
		"b": [],
		"g": 16,
		"n": 1
	}, {
		"t": 12,
		"f0": [{
			"g": 1,
			"t": 0
		}]
	}]
}
