### ISSUE TITLE
Sonoff SA-018 & Home Accessory Architect v4.9.0 ok

### ISSUE THREAD

**Issue by tonton-RISK** [RavenSystem/esp-homekit-devices#1334]
Hi, 
need help
Device ---- Sonoff SA-018
Accessory description --- Switch.
Json -----  {"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]}]}
its on Home Accessory Architect v4.9.0

after switching to Home Accessory Architect v4.9.0 the black wires no longer work.

Thank for your help

[<a href='https://www.casimages.com/i/210210100220625693.jpg.html' title='Mon image' target='_blank'><img src='https://nsa40.casimages.com/img/2021/02/10/mini_210210100220625693.jpg' border='0' alt='Mon image' /></a>](url)
[<a href='https://www.casimages.com/i/210210100225206624.jpg.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/02/10/210210100225206624.jpg' border='0' alt='Mon image' /></a>](url)
[<a href='https://www.casimages.com/i/210210100228659650.jpg.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/02/10/210210100228659650.jpg' border='0' alt='Mon image' /></a>](url)

**Comment by tonton-RISK** [comment]
More picture of SA-018
[<a href='https://www.casimages.com/i/210211110525117597.jpg.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/02/11/210211110525117597.jpg' border='0' alt='Mon image' /></a>](url)

[[URL=https://www.casimages.com/i/210211110533155807.jpg.html][IMG]https://nsa40.casimages.com/img/2021/02/11/210211110533155807.jpg[/IMG][/URL]](url)

[[URL=https://www.casimages.com/i/210211110542653965.jpg.html][IMG]https://nsa40.casimages.com/img/2021/02/11/210211110542653965.jpg[/IMG][/URL]](url)

thanks for help

**Comment by nickforev** [comment]
json
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":4},{"g":4,"t":0}]}]}

**Comment by tonton-RISK** [comment]
Hi nickforev,
Thanks for your help , 
Ahan thanks a lot 
I test this 8:00 pm
