### ISSUE TITLE
possible to update from v1.2?

### ISSUE THREAD

**Issue by mozzaLB** [RavenSystem/esp-homekit-devices#1336]
I have a couple of old switches on RavenCore v1.2. They were controlled by EVE app if I remember right and could be updated through this app. However I do not see the update button in the eve setup anymore. Is it still possible to update them to the latest HAA version?

**Comment by mozzaLB** [comment]
is it possible with the LCM update https://github.com/RavenSystem/esp-homekit-devices/issues/1327? It is however not clear to me how to do this. Are there any instructions for noobs like me?

**Comment by tonysprenk** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/686

**Comment by mozzaLB** [comment]
thanks for your response! I also found that solution but the problem is that i do not see FIRMWARE UPDATE in eve setup mode. All the other option are there except that one. Any idea why?

**Comment by mozzaLB** [comment]
found it already. I did not install it using LCM. This is the reason i do not see the firmware update option in Eve

**Comment by tonysprenk** [comment]
Yes so I believe only option is to flash by connecting to ftdi adapter.

**Comment by mozzaLB** [comment]
I also think so. Thanks
