### ISSUE TITLE
WiFi SSID truncated so it is impossible to connect during auto update

### ISSUE THREAD

**Issue by aleroot** [RavenSystem/esp-homekit-devices#1337]
Hi,
I have a WiFi network from the provider router with name: `533C Hyperoptic 1Gb Fibre 2.4Ghz`, when it is saved by HAA setup tool the last character is truncated and so it is impossible to connect to the WiFi ...

Log :

```
no 533C Hyperoptic 1Gb Fibre 2.4Gh found, reconnect after 1s
reconnect
scandone
```

Mximum WiFi SSID length should be 32, I have a name long 32, but last character gets truncated.
The problem is already in the listed wifi that is already listed with last char truncated.
Even inserting the SSID manually doesn't work, it gets truncated at the saving operation.

**Comment by aleroot** [comment]
Looks like the issue is in the sdk_bss_info definition in: https://github.com/SuperHouse/esp-open-rtos/blob/503e66a500419e8863998b7ea784c5e26a7a5f7c/include/espressif/esp_sta.h it is defined as 32 char array while it should be 33 since it is null terminated.

**Comment by RavenSystem** [comment]
Forget PR. I will fix it by myself:
```
Jan 01 00:00:03 connected with 533C Hyperoptic 1Gb Fibre 2.4Ghz, channel 9
Jan 01 00:00:03 dhcp client start...
```
