### ISSUE TITLE
Shelly RGBW2 - JSON for external AC switch

### ISSUE THREAD

**Issue by jatoka** [RavenSystem/esp-homekit-devices#1338]
Hi,
I connected an external 230V AC dimmer switch to Shelly RGBW2, according to the manufacturer's schematic, but Shelly does not turn on. On a standard on/off switch same thing.

Do I need to change the JSON for the dimmer or on/off switch to work?
I have the standard JSON code:
{"c":{"l":2,"b":[{"g":13,"t":5}]},"a":[{"t":30,"r":15,"g":12,"v":14,"w":4,"b":[{"g":5,"p":0},{"g":5,"t":0},{"g":13}]}]}
![rgbw_led_strip_shelly](https://user-images.githubusercontent.com/79064752/107892628-bb7e7780-6f26-11eb-803d-6de32c2c15c5.png)

**Comment by BartoszGan** [comment]
Have you found any solution for this issue?
