### ISSUE TITLE
Garage door HomeKit animation

### ISSUE THREAD

**Issue by 4Xsample** [RavenSystem/esp-homekit-devices#134]
Hi
First of all, as usual, thank you for this great work with this firmware.
Is fucking amazing and full of posibilities.
But now lets go to business.
I have a bunch of Sonoff Basic and I discovered your firmware a couple days ago so I flashed a handfull of them for xmas lights and so, off course with the last version aviable.
I tried the option for garage door with one, isolated the rele, and all this.
Is set up as no sensor and no stop step, and it works but... 
The animation on Home app is not working at all. When I click on there the animation says Opening and never changes.
If I click again on the door's button it just change the animation to Closed but does nothing to the real door and to close it I must click it twice again, one to close it and the second one to stop the animation.
I don't know if when I set up some sensor there it can solve the problem (aniway I'm waiting some sensors from amazon to do it) but is an issue.
You had the same issue somwhere else?
It will be fixed when I recive and set up the open and closed sensors?

**Comment by pandarek** [comment]
I tested with opening and closing sendors and it works correctly.

**Comment by 4Xsample** [comment]
With open sensor too?
It was difficult to solder the GPIO04?
Is the only thing is keeping me away by now.
Is so small the place where it should go and I thing I don’t have the skills to do it.

**Comment by pandarek** [comment]
I used sonoff sv. Both sensors.

**Comment by RavenSystem** [comment]
Closing sensor is mandatory, opening sensor is optional, but you must setup your environment with EVE App.

All is explain in [Garage Door Wiki section](https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#8-garage-door).

**Comment by 4Xsample** [comment]
Ok!
Then it works as is expected.
I leave the wires ready and when I get the real sensor I’ll install it and done :)
