### ISSUE TITLE
Loop by installing HAA

### ISSUE THREAD

**Issue by jRaufe** [RavenSystem/esp-homekit-devices#1340]
Hi,
Trying to install HAA in a Shelly 1, I’m in a loop!

_> iPad Pro de Jose $ nc -kulnw0 45678 
> 
> Advanced ESP Logger (c) 2020 José Antonio Jiménez Campos
> 
> 0003.732 192.168.1.126-A9A494: DNS check result  = OK
> 0009.080 192.168.1.126-A9A494: DNS..OK Socket..OK Connect..OK SSL..OK set_fd to github.com port 443..OK
> 0009.085 192.168.1.126-A9A494: sent OK
> ossorigin=anonymous; as=script,<https://github.githubassets.com/assets/behaviors-bf28db4d.js>; integrity=sha512-vyjbTdEGTiemoiT41KyVSh3+NxJv285wa1qlccyGrTsQsAAvhBSUrT0t1LZbJVEfccSTx+zLAyTekiljOX2wKA==; rel=preload; crossorigin=anonymous; as=script,<https://github.githubassets.com/assets/environment-f0adafbf.js>; integrity=sha512-8K2vvwbW+6H27Nad5ydg8PA2/aMD/LKq+EiK9s0U0hhVZxCI2tWBsYk9beAtisRw2j+Or5k2/F+6dk02nmj/PA==; rel=preload; crossorigin=anonymous; as=script
> 0011.309 192.168.1.126-A9A494: Vary: X-PJAX, Accept
> 
> 0011.311 192.168.1.126-A9A494: 
> 0011.312 192.168.1.126-A9A494: HTTP returns 302
> 
> 0011.312 192.168.1.126-A9A494: 
> 0011.316 192.168.1.126-A9A494: !!! SERVER ERROR
> 
> 0011.317 192.168.1.126-A9A494: 
> 0011.317 192.168.1.126-A9A494: !!! Error downloading OTAMAIN signature
> 
> 0011.318 192.168.1.126-A9A494: 
> 
> 0016.328 192.168.1.126-A9A494: 
> 0016.329 192.168.1.126-A9A494: *** STARTING UPDATE PROCESS
> 
> 0016.329 192.168.1.126-A9A494: 
> 
> 0016.329 192.168.1.126-A9A494: 
> 0016.330 192.168.1.126-A9A494: Running HAABOOT
> 
> 0016.330 192.168.1.126-A9A494: 
> 0016.330 192.168.1.126-A9A494: HomeKit data migration...
> 0016.331 192.168.1.126-A9A494: Data is already migrated
> 
> 0016.332 192.168.1.126-A9A494: 
> 0016.332 192.168.1.126-A9A494: Get sign
> 
> 0016.332 192.168.1.126-A9A494: 
> 0016.333 192.168.1.126-A9A494: DOWNLOADING FILE
> 
> 0016.333 192.168.1.126-A9A494: 
> 0016.334 192.168.1.126-A9A494: Forwarding: github.com/RavenSystem/haa/releases/latest/download/otamain.bin.sec
> 0016.337 192.168.1.126-A9A494: -----
> 0016.338 192.168.1.126-A9A494: GET /RavenSystem/haa/releases/latest/download/otamain.bin.sec HTTP/1.1
> 0016.344 192.168.1.126-A9A494: Host: github.com
> 0016.346 192.168.1.126-A9A494: Range: bytes=0-1
> 
> 0016.347 192.168.1.126-A9A494: 
> 
> 0016.328 192.168.1.126-A9A494: 
> 0016.329 192.168.1.126-A9A494: *** STARTING UPDATE PROCESS
> 
> 0016.329 192.168.1.126-A9A494: 
> 
> 0016.329 192.168.1.126-A9A494: 
> 0016.330 192.168.1.126-A9A494: Running HAABOOT
> 
> 0016.330 192.168.1.126-A9A494: 
> 0016.330 192.168.1.126-A9A494: HomeKit data migration...
> 0016.331 192.168.1.126-A9A494: Data is already migrated
> 
> 0016.332 192.168.1.126-A9A494: 
> 0016.332 192.168.1.126-A9A494: Get sign
> 
> 0016.332 192.168.1.126-A9A494: 
> 0016.333 192.168.1.126-A9A494: DOWNLOADING FILE
> 
> 0016.333 192.168.1.126-A9A494: 
> 0016.334 192.168.1.126-A9A494: Forwarding: github.com/RavenSystem/haa/releases/latest/download/otamain.bin.sec
> 0016.337 192.168.1.126-A9A494: -----
> 0016.338 192.168.1.126-A9A494: GET /RavenSystem/haa/releases/latest/download/otamain.bin.sec HTTP/1.1
> 0016.344 192.168.1.126-A9A494: Host: github.com
> 0016.346 192.168.1.126-A9A494: Range: bytes=0-1
> 
> 0016.347 192.168.1.126-A9A494: 
> 0016.348 192.168.1.126-A9A494: -----
> 
> 0016.350 192.168.1.126-A9A494: 
> 0016.350 192.168.1.126-A90017.486 192.168.1.126-A9A494: DNS..OK Socket..OK Connect..OK SSL..OK set_fd to github.com port 443..OK
> 0017.491 192.168.1.126-A9A494: sent OK
> 
> Advanced ESP Logger (c) 2020 José Antonio Jiménez Campos
> 
> 
> 0005.663 192.168.1.126-A9A494: 
> 
> 0005.664 192.168.1.126-A9A494: 
> 0005.664 192.168.1.126-A9A494: HAA Installer Version: 4.5.0
> 
> 0005.664 192.168.1.126-A9A494: 
> 
> 0005.664 192.168.1.126-A9A494: 
> 0005.677 192.168.1.126-A9A494: - Server: github.com/RavenSystem/haa/releases/latest/download
> 0005.678 192.168.1.126-A9A494: - Port:   443
> 0005.678 192.168.1.126-A9A494: - SSL:    yes
> 
> 0005.678 192.168.1.126-A9A494: 
> 0005.681 192.168.1.126-A9A494: Current HAAMAIN version installed: 0.0.0
> 
> 0005.681 192.168.1.126-A9A494: 
> 0005.682 192.168.1.126-A9A494: INIT
> 0005.815 192.168.1.126-A9A494: DNS check result  = OK
> 
> 0007.823 192.168.1.126-A9A494: 
> 0007.824 192.168.1.126-A9A494: *** STARTING UPDATE PROCESS
> 
> 0007.824 192.168.1.126-A9A494: 
> 
> 0007.824 192.168.1.126-A9A494: 
> 0007.824 192.168.1.126-A9A494: Running HAABOOT
> 
> 0007.824 192.168.1.126-A9A494: 
> 0007.825 192.168.1.126-A9A494: HomeKit data migration...
> 0007.825 192.168.1.126-A9A494: Data is already migrated
> 
> 0007.826 192.168.1.126-A9A494: 
> 0007.827 192.168.1.126-A9A494: Get sign
> 
> 0007.827 192.168.1.126-A9A494: 
> 0007.827 192.168.1.126-A9A494: DOWNLOADING FILE
> 
> 0007.827 192.168.1.126-A9A494: 
> 0007.828 192.168.1.126-A9A494: Forwarding: github.com/RavenSystem/haa/releases/latest/download/otamain.bin.sec
> 0007.832 192.168.1.126-A9A494: -----
> 0007.832 192.168.1.126-A9A494: GET /RavenSystem/haa/releases/latest/download/otamain.bin.sec HTTP/1.1
> 0007.839 192.168.1.126-A9A494: Host: github.com
> 0007.840 192.168.1.126-A9A494: Range: bytes=0-1
> 
> 0007.842 192.168.1.126-A9A494: 
> 0007.844 192.168.1.126-A9A494: -----
> 
> 0007.844 192.168.1.126-A9A494: 
> 0007.845 192.168.1.126-A90008.996 192.168.1.126-A9A494: DNS..OK Socket..OK Connect..OK SSL..OK set_fd to github.com port 443..OK
> 0009.001 192.168.1.126-A9A494: sent OK
> script,<https://github.githubassets.com/assets/behaviors-bf28db4d.js>; integrity=sha512-vyjbTdEGTiemoiT41KyVSh3+NxJv285wa1qlccyGrTsQsAAvhBSUrT0t1LZbJVEfccSTx+zLAyTekiljOX2wKA==; rel=preload; crossorigin=anonymous; as=script,<https://github.githubassets.com/assets/environment-f0adafbf.js>; integrity=sha512-8K2vvwbW+6H27Nad5ydg8PA2/aMD/LKq+EiK9s0U0hhVZxCI2tWBsYk9beAtisRw2j+Or5k2/F+6dk02nmj/PA==; rel=preload; crossorigin=anonymous; as=script
> 0009.161 192.168.1.126-A9A494: Vary: X-PJAX, Accept
> 
> 0009.163 192.168.1.126-A9A494: 
> 0009.167 192.168.1.126-A9A494: HTTP returns 302
> 
> 0009.167 192.168.1.126-A9A494: 
> 0009.171 192.168.1.126-A9A494: !!! SERVER ERROR
> 
> 0009.172 192.168.1.126-A9A494: 
> 0009.173 192.168.1.126-A9A494: !!! Error downloading OTAMAIN signature
> 
> 0009.173 192.168.1.126-A9A494: 
> 
> 0014.182 192.168.1.126-A9A494: 
> 0014.183 192.168.1.126-A9A494: *** STARTING UPDATE PROCESS
> 
> 0014.183 192.168.1.126-A9A494: 
> 
> 0014.184 192.168.1.126-A9A494: 
> 0014.184 192.168.1.126-A9A494: Running HAABOOT
> 
> 0014.184 192.168.1.126-A9A494: 
> 0014.184 192.168.1.126-A9A494: HomeKit data migration...
> 0014.185 192.168.1.126-A9A494: Data is already migrated
> 
> 0014.186 192.168.1.126-A9A494: 
> 0014.186 192.168.1.126-A9A494: Get sign
> 
> 0014.187 192.168.1.126-A9A494: 
> 0014.187 192.168.1.126-A9A494: DOWNLOADING FILE
> 
> 0014.187 192.168.1.126-A9A494: 
> 0014.188 192.168.1.126-A9A494: Forwarding: github.com/RavenSystem/haa/releases/latest/download/otamain.bin.sec
> 0014.191 192.168.1.126-A9A494: -----
> 0014.192 192.168.1.126-A9A494: GET /RavenSystem/haa/releases/latest/download/otamain.bin.sec HTTP/1.1
> 0014.198 192.168.1.126-A9A494: Host: github.com
> 0014.200 192.168.1.126-A9A494: Range: bytes=0-1
> 
> 0014.201 192.168.1.126-A9A494: 
> 
> 0014.182 192.168.1.126-A9A494: 
> 0014.183 192.168.1.126-A9A494: *** STARTING UPDATE PROCESS
> 
> 0014.183 192.168.1.126-A9A494: 
> 
> 0014.184 192.168.1.126-A9A494: 
> 0014.184 192.168.1.126-A9A494: Running HAABOOT
> 
> 0014.184 192.168.1.126-A9A494: 
> 0014.184 192.168.1.126-A9A494: HomeKit data migration...
> 0014.185 192.168.1.126-A9A494: Data is already migrated
> 
> 0014.186 192.168.1.126-A9A494: 
> 0014.186 192.168.1.126-A9A494: Get sign
> 
> 0014.187 192.168.1.126-A9A494: 
> 0014.187 192.168.1.126-A9A494: DOWNLOADING FILE
> 
> 0014.187 192.168.1.126-A9A494: 
> 0014.188 192.168.1.126-A9A494: Forwarding: github.com/RavenSystem/haa/releases/latest/download/otamain.bin.sec
> 0014.191 192.168.1.126-A9A494: -----
> 0014.192 192.168.1.126-A9A494: GET /RavenSystem/haa/releases/latest/download/otamain.bin.sec HTTP/1.1
> 0014.198 192.168.1.126-A9A494: Host: github.com
> 0014.200 192.168.1.126-A9A494: Range: bytes=0-1
> 
> 0014.201 192.168.1.126-A9A494: 
> 0014.202 192.168.1.126-A9A494: -----
> 
> 0014.204 192.168.1.126-A9A494: 
> 0014.204 192.168.1.126-A90018.196 192.168.1.126-A9A494: DNS..OK Socket..OK Connect..OK SSL..OK set_fd to github.com port 443..OK
> 0018.200 192.168.1.126-A9A494: sent OK
> ://github.githubassets.com/assets/behaviors-bf28db4d.js>; integrity=sha512-vyjbTdEGTiemoiT41KyVSh3+NxJv285wa1qlccyGrTsQsAAvhBSUrT0t1LZbJVEfccSTx+zLAyTekiljOX2wKA==; rel=preload; crossorigin=anonymous; as=script,<https://github.githubassets.com/assets/environment-f0adafbf.js>; integrity=sha512-8K2vvwbW+6H27Nad5ydg8PA2/aMD/LKq+EiK9s0U0hhVZxCI2tWBsYk9beAtisRw2j+Or5k2/F+6dk02nmj/PA==; rel=preload; crossorigin=anonymous; as=script
> 0018.369 192.168.1.126-A9A494: Vary: X-PJAX, Accept
> 
> 0018.371 192.168.1.126-A9A494: 
> 0018.373 192.168.1.126-A9A494: HTTP returns 302
> 
> 0018.373 192.168.1.126-A9A494: 
> 0018.377 192.168.1.126-A9A494: !!! SERVER ERROR
> 
> 0018.378 192.168.1.126-A9A494: 
> 0018.378 192.168.1.126-A9A494: !!! Error downloading OTAMAIN signature
> 
> 0018.379 192.168.1.126-A9A494: 
> 
> 0018.395 192.168.1.126-A9A494: 
> 0018.396 192.168.1.126-A9A494: Restarting...
> 
> Advanced ESP Logger (c) 2020 José Antonio Jiménez Campos
> 
> 
> 0005.772 192.168.1.126-A9A494: 
> 0005.773 192.168.1.126-A9A494: *** STARTING UPDATE PROCESS
> 
> 0005.773 192.168.1.126-A9A494: 
> 
> 0005.773 192.168.1.126-A9A494: 
> 0005.773 192.168.1.126-A9A494: Running HAABOOT
> 
> 0005.773 192.168.1.126-A9A494: 
> 0005.774 192.168.1.126-A9A494: HomeKit data migration...
> 0005.774 192.168.1.126-A9A494: Data is already migrated
> 
> 0005.775 192.168.1.126-A9A494: 
> 0005.776 192.168.1.126-A9A494: Get sign
> 
> 0005.776 192.168.1.126-A9A494: 
> 0005.776 192.168.1.126-A9A494: DOWNLOADING FILE
> 
> 0005.776 192.168.1.126-A9A494: 
> 0005.777 192.168.1.126-A9A494: Forwarding: github.com/RavenSystem/haa/releases/latest/download/otamain.bin.sec
> 0005.781 192.168.1.126-A9A494: -----
> 0005.781 192.168.1.126-A9A494: GET /RavenSystem/haa/releases/latest/download/otamain.bin.sec HTTP/1.1
> 0005.788 192.168.1.126-A9A494: Host: github.com
> 0005.789 192.168.1.126-A9A494: Range: bytes=0-1
> 
> 0005.792 192.168.1.126-A9A494: 
> 0005.792 192.168.1.126-A9A494: -----
> 
> 0005.793 192.168.1.126-A9A494: 
> 0005.793 192.168.1.126-A9A494: *** NEW CONNECTION
> 0006.892 192.168.1.126-A9A494: DNS..OK Socket..OK Connect..OK SSL..OK set_fd to github.com port 443..OK
> 0006.896 192.168.1.126-A9A494: sent OK
> 0006.958 192.168.1.126-A9A494: ret = 1024
> 
> 0006.959 192.168.1.126-A9A494: 
> 0006.959 192.168.1.126-A9A494: HTTP/1.1 302 Found
> 0006.959 192.168.1.126-A9A494: Date: Tue, 16 Feb 2021 20:46:58 GMT
> 0006.959 192.168.1.126-A9A494: Content-Type: text/html; charset=utf-8
> 0006.959 192.168.1.126-A9A494: Server: GitHub.com
> 0006.960 192.168.1.126-A9A494: Link: <https://github.githubassets.com/assets/chunk-frameworks-aaac5e7e.js>; integrity=sha512-qqxefjEZzhP8x0ed+F3sDEdSogyDs+0ThK6EYXtqye9PJ26t5C996Q9EuRBr+296TAbc1rimsOSeZjZXJac1cA==; rel=preload; crossorigin=anonymous; as=script,<https://github.githubassets.com/assets/chunk-vendor-6594a208.js>; integrity=sha512-ZZSiCHJ85gkTIyggKfuBXsl3a7e+GPhw6iUguJ6eki2dXkGnOFBpQlUUG+gcTSJzgE8ii1cYyM7aLYXZeSeDbA==; rel=preload; crossorigin=anonymous; as=script,<https://github.githubassets.com/assets/behaviors-bf28db4d.js>; integrity=sha512-vyjbTdEGTiemoiT41KyVSh3+NxJv285wa1qlccyGrTsQsAAvhBSUrT0t1LZbJVEfccSTx+zLAyTekiljOX2wKA==; rel=preload; crossorigin=anonymous; as=script,<https://github.githubassets.com/assets/environment-f0adafbf.js>; integrity=sha512-8K2vvwbW+6H27Nad5ydg8PA2/aMD/LKq+EiK9s0U0hhVZxCI2tWBsYk9beAtisRw2j+Or5k2/F+6dk02nmj/PA==; rel=preload; crossorigin=anonymous; as=script
> 0007.036 192.168.1.126-A9A494: Vary: X-PJAX, Accept
> 
> 0007.038 192.168.1.126-A9A494: 
> 0007.040 192.168.1.126-A9A494: HTTP returns 302
> 
> 0007.040 192.168.1.126-A9A494: 
> 0007.045 192.168.1.126-A9A494: !!! SERVER ERROR
> 
> 0007.046 192.168.1.126-A9A494: 
> 0007.046 192.168.1.126-A9A494: !!! Error downloading OTAMAIN signature
> 
> 0007.046 192.168.1.126-A9A494: 
> 
> 0012.051 192.168.1.126-A9A494: 
> 0012.052 192.168.1.126-A9A494: *** STARTING UPDATE PROCESS
> 
> 0012.052 192.168.1.126-A9A494: 
> 
> 0012.052 192.168.1.126-A9A494: 
> 0012.052 192.168.1.126-A9A494: Running HAABOOT
> 
> 0012.052 192.168.1.126-A9A494: 
> 0012.053 192.168.1.126-A9A494: HomeKit data migration...
> 0012.053 192.168.1.126-A9A494: Data is already migrated
> 
> 0012.054 192.168.1.126-A9A494: 
> 0012.055 192.168.1.126-A9A494: Get sign
> 
> 0012.055 192.168.1.126-A9A494: 
> 0012.057 192.168.1.126-A9A494: DOWNLOADING FILE
> 
> 0012.057 192.168.1.126-A9A494: 
> 0012.058 192.168.1.126-A9A494: Forwarding: github.com/RavenSystem/haa/releases/latest/download/otamain.bin.sec
> 0012.060 192.168.1.126-A9A494: -----
> 0012.060 192.168.1.126-A9A494: GET /RavenSystem/haa/releases/latest/download/otamain.bin.sec HTTP/1.1
> 0012.067 192.168.1.126-A9A494: Host: github.com
> 0012.068 192.168.1.126-A9A494: Range: bytes=0-1
> 
> 0012.070 192.168.1.126-A9A494: 
> 0012.070 192.168.1.126-A9A494: -----
> 
> 0012.072 192.168.1.126-A9A494: 
> 0012.073 192.168.1.126-A90013.598 192.168.1.126-A9A494: DNS..OK Socket..OK Connect..OK SSL..OK set_fd to github.com port 443..OK
> in=anonymous; as=script,<https://github.githubassets.com/assets/behaviors-bf28db4d.js>; integrity=sha512-vyjbTdEGTiemoiT41KyVSh3+NxJv285wa1qlccyGrTsQsAAvhBSUrT0t1LZbJVEfccSTx+zLAyTekiljOX2wKA==; rel=preload; crossorigin=anonymous; as=script,<https://github.githubassets.com/assets/environment-f0adafbf.js>; integrity=sha512-8K2vvwbW+6H27Nad5ydg8PA2/aMD/LKq+EiK9s0U0hhVZxCI2tWBsYk9beAtisRw2j+Or5k2/F+6dk02nmj/PA==; rel=preload; crossorigin=anonymous; as=script
> 0013.781 192.168.1.126-A9A494: Vary: X-PJAX, Accept
> 
> 0013.782 192.168.1.126-A9A494: 
> 0013.784 192.168.1.126-A9A494: HTTP returns 302
> 
> 0013.785 192.168.1.126-A9A494: 
> 0013.790 192.168.1.126-A9A494: !!! SERVER ERROR
> 
> 0013.792 192.168.1.126-A9A494: 
> 0013.792 192.168.1.126-A9A494: !!! Error downloading OTAMAIN signature
> 
> 0013.793 192.168.1.126-A9A494: 
> 
> 0013.821 192.168.1.126-A9A494: 
> 0013.823 192.168.1.126-A9A494: Restarting...
> _

Any idea what to do?

**Comment by RavenSystem** [comment]
GitHub server side issue:
https://github.com/HomeACcessoryKid/life-cycle-manager/issues/23#issuecomment-780155826

**Comment by nickforev** [comment]
Work it now!

**Comment by jRaufe** [comment]
👍

**Comment by weishiji** [comment]
> Work it now!

I met the same problem, how to solve it?
