### ISSUE TITLE
Home vpn

### ISSUE THREAD

**Issue by brkysnol** [RavenSystem/esp-homekit-devices#1342]
I set up a vpn service to access the home network from the outside. How do I manage connected apple home kit devices at home with vpn ?

**Comment by tonysprenk** [comment]
You dont have a home hub (Apple TV, ipad, HomePod)?

**Comment by brkysnol** [comment]
I'm afraid I don't have any of this. I only have a vpn on my home network.

**Comment by brkysnol** [comment]
> You dont have a home hub (Apple TV, ipad, HomePod)?

I'm afraid I don't have any of this. I only have a vpn on my home network.

**Comment by adamkasprzak** [comment]
I ended up using home hub. Firstly iPad, then ATV. Homekit doesn't work via VPN in my case.

**Comment by brkysnol** [comment]
> Ana hub'ı kullanmayı bıraktım. Önce iPad, ardından ATV. Homekit benim durumumda VPN üzerinden çalışmıyor.

I don't have any of this :( how to access it remotely.

**Comment by jakudo** [comment]
I believe that the VPN doesn't help with your problem. You need some hub (Apple TV, iPad, HomePod). Without it you cannot use homekit remotely.

**Comment by tonysprenk** [comment]
It can be done but it’s not easy. HomeKit uses Bonjour which does notebook over vpn. You need to setup some service to relay Bonjour messages. Easier would be to buy a cheap Apple TV or iPad.

**Comment by peros550** [comment]
Technically you could enable insecure mode in HAA ("u":1) and find a way to control accessories using http get requests from your mobile. This could work over vpn.

I'm not endorsing insecure mode, however it's there if you want to use it. 

But, with an Apple TV you can do so much more

**Comment by brkysnol** [comment]
> Yapılabilir ama kolay değil. HomeKit, dizüstü bilgisayarı vpn üzerinden yapan Bonjour kullanır. Bonjour mesajlarını iletmek için bazı servisler kurmanız gerekir. Daha kolay, ucuz bir Apple TV veya iPad satın almak olacaktır.



> Teknik olarak HAA'da güvenli olmayan modu etkinleştirebilir ("u": 1) ve cep telefonunuzdan http alma isteklerini kullanarak aksesuarları kontrol etmenin bir yolunu bulabilirsiniz. Bu vpn üzerinden çalışabilir.
> 
> Güvensiz modu onaylamıyorum, ancak kullanmak istiyorsanız orada.
> 
> Ancak bir Apple TV ile çok daha fazlasını yapabilirsiniz

Thank you for your answers, I want to do what you say. Are there any sources ?
