### ISSUE TITLE
Network Request Actions / wait for response

### ISSUE THREAD

**Issue by freddair** [RavenSystem/esp-homekit-devices#1344]
Hi, I use Network Request Actions on a HAA device (Gosund SP111) to control a non-HomeKit Shelly Dimmer as a lightbulb. The problem is that it sends the commands but isn't able to receive status updates if the Shelly is controlled outside HAA. Is there a possible solution that polls the status for example using the polled HTTP content?

I don't understand the "w" Option of "Send Network Request Actions" - the Wiki does not explain it further than:

Wait for response	"w" = Wait for a response when a TCP/HTTP request is sent

Thanks!

**Comment by RavenSystem** [comment]
When using Wait for response with "w":1 value, device will wait 2 seconds for a response from target host, but received data will not be processed. That feature is needed for some devices that needs to send any kind of acknowledgment to work properly (Eg. Philips HUE Bridge).

Now it is documented in the Wiki.
