### ISSUE TITLE
Feature Request : Faster on

### ISSUE THREAD

**Issue by rhjensen79** [RavenSystem/esp-homekit-devices#135]
Is it possible to make the on feature, faster after the power comes on ?
Today the delay from power comes on, until the light (og whatever you have connected) is about 2-5 seconds.

It would be great if it was instant (or close), so the Sonoff is invisible, in the setup.

**Comment by RavenSystem** [comment]
I understand that your device is set to turn on light on boot, and you want to reduce the delay between device powers on and relay turns on, is it?

**Comment by rhjensen79** [comment]
Exactly. Sorry for not being more clear :-)


/Robert

**Comment by RavenSystem** [comment]
It id caused by a delayed initial timer, but I want to remove it.

**Comment by RavenSystem** [comment]
Try v0.5.5.

**Comment by rhjensen79** [comment]
It works. 
Now on is almost instant. 

Thanks.

I'm closing the issue.
