### ISSUE TITLE
Sonoff Dual Lock Json

### ISSUE THREAD

**Issue by asbesto01** [RavenSystem/esp-homekit-devices#1350]
Hello everybody,

can someone create for me a json to open a lock for 0.6 seconds, then relock it?

I have this one for the Sonoff 4CH pro R2, help please!

{"c":{"l":13,"i":1,"b":[{"g":0,"t":5}]},"a":[{"t":4,"i":0.4,"0":{"r":[{"g":12,"v":1}]},"1":{"r":[{"g":12,"v":0}]},"b":[{"g":0}]},{"t":4,"i":0.4,"0":{"r":[{"g":5,"v":1}]},"1":{"r":[{"g":5,"v":0}]},"b":[{"g":9}]},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":10}]},{"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":14}]}]}

Thank you so much!!

**Comment by tonysprenk** [comment]
This example is from the [wiki](https://github.com/RavenSystem/esp-homekit-devices/wiki/Lock-Mechanism#example-of-single-lock-mechanism) but I changed “i” to 6: 
```

{
  "a":[{
    "t":4,
    "i":3,
    "0":{"r":[{"g":4,"v":1,"i":6}]},
    "1":{"r":[{"g":4}]},
    "b":[{"g":5,"p":0,"i":1,"t":0}]
  }]
}

```

the lock mechanism is connected to gpio 4 and it has a button connected to gpio 5.

**Comment by asbesto01** [comment]
{
   "c":{
      "o":1,
      "l":13,
      "i":1
   },
   "a":[
      {
         "t":4,
         "i":0.4,
         "0":{
            "r":[
               {
                  "g":12,
                  "v":1
               }
            ]
         },
         "1":{
            "r":[
               {
                  "g":12,
                  "v":0
               }
            ]
         },
                  "1":{
            "r":[
               {
                  "g":5,
                  "v":1
               }
            ]
         },
         "b":[
            {
               "g":9
            }
         ]
      }
   ]
}


this is the right json, I wrote it by myself and it works, I am so proud!!!!!
