### ISSUE TITLE
v5.0.5 - breaks Garage Door logic when using Garage Door Remote/hard wired button

### ISSUE THREAD

**Issue by rjblake** [RavenSystem/esp-homekit-devices#1351]
On a test bed, have updated to v5.0.5 and notice a change in the behaviour as follows:

Garage Door is in closed state
- Open with HomeKit, Close with HomeKit - behaviour is normal
- Open with Garage remote - status goes from Closed to Closing. Even when relay for Open is connected, still shows as Closing. This is only in HomeKit, as still get popup alert stating Open or Closed. v4.9.0 does not show this behaviour and works correctly.

`{"c":{"0":{"r":[{"g":5,"v":1},{"g":2,"v":0}]},"n":"GDC-D1-2","l":1,"o":0,"ntp":"pool.ntp.org","tz":"CET-1CEST-2,M3.5.0/2,M10.5.0/2","b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":5,"i":0.5}]},"1":{"r":[{"g":5,"i":0.5}]},"2":{"r":[{"g":5,"v":1,"i":1.5},{"g":5,"i":0.3},{"g":5,"i":2.0}]},"3":{"a":2},"t":40,"d":30,"c":40,"e":50,"f3":[{"g":14,"t":0}],"f4":[{"g":14}],"f2":[{"g":12,"t":0}],"f5":[{"g":12}],"b":[{"g":0}],"s":0},{"1":{"s":[{"a":1}]},"b":[],"s":0},{"0":{"r":[{"g":4,"v":1}]},"1":{"r":[{"g":4,"v":0}]},"t":2,"s":5,"b":[]},{"t":24,"n":2,"g":13,"j":30}]}`

**Comment by RavenSystem** [comment]
Fixed with v5.0.8.
