### ISSUE TITLE
Doorbell json required

### ISSUE THREAD

**Issue by okanduzyel** [RavenSystem/esp-homekit-devices#1353]
Hi,

here https://github.com/RavenSystem/esp-homekit-devices/issues/1144 your discussion about a doorbell json example. I tried that but After the downloading of HAA, the device doesn't respond. I think, the json has problem. Because I tried other your json examples. They are okay.

Can you share a json of doorbell example?

**Comment by okanduzyel** [comment]
`{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":13,"f0":[{"g":14,"t":0}]}]}`

This is your example that it is okay. But It is unfortunately just a stateless button.

**Comment by mariusvasss** [comment]
> 
> 
> Hi,
> 
> here #1144 your discussion about a doorbell json example. I tried that but After the downloading of HAA, the device doesn't respond. I think, the json has problem. Because I tried other your json examples. They are okay.
> 
> Can you share a json of doorbell example?

Sonoff mini doorbell with buton on gpio 4, chime to gpio 12, upgrade classic doorbell 

{"c":{"n":"Doorbell","l":13,"b":[{"g":0,"t":5}],"0":{"r":[{"g":12}]}},"a":[{"t":13,"f0":[{"g":4,"p":0,"i":1,"t":0}],"0":{"r":[{"g":12,"v":1,"i":0.5}]}}]}

**Comment by Przylepzwm** [comment]
t: 13 is a doorbell, but I see it as a contact sensor. Is it correct?
