### ISSUE TITLE
Window-Covering

### ISSUE THREAD

**Issue by okanduzyel** [RavenSystem/esp-homekit-devices#1354]
Hi, 

I have a window covering that has a step motor inside. I looked at your examples about window covering and found this https://github.com/RavenSystem/esp-homekit-devices/wiki/Window-Covering.

The motor driver of my window covering is a4988. It requires PWM input for each step movement of step motor. If I can add a PWM output that gives only output under opening-closing times, I can use your HAA.

How can I add single-pin PWM output for that?

```
{
  "c": { "l": 0, "b": [{ "g": 2, "p": 0, "t": 5 }], "0": { "r": [{ "g": 15 }, { "g": 16 }] } },
  "a": [{
    "t": 45,
    "o": 18,
    "c": 14,
    "f": 70,
    "cd": 2,
    "0": { "r": [{ "g": 15, "v": 1 }, { "g": 4 }] },
    "1": { "r": [{ "g": 15 }, { "g": 4, "v": 1 }] },
    "2": { "r": [{ "g": 15 }, { "g": 4 }] },
    "3": { "r": [{ "g": 15, "i": 0.2 }, { "g": 4 }] },
    "4": { "r": [{ "g": 15 }, { "g": 4, "i": 0.2 }] },
    "f0": [{ "g": 5, "i": 1, "p": 0, "t":0 }],
    "f1": [{ "g": 13, "i": 1, "p": 0, "t":0 }],
    "f2": [{ "g": 5 }, { "g": 13 }]
  }]
}
```

**Comment by okanduzyel** [comment]
If I understand correctly, the window covering device type hasn't PWM output capability. 
Could you add it for me? Because there are a lot of solutions that use step motor...

**Comment by pilot1981** [comment]
Are you trying to use HAA to control swing windows?

**Comment by okanduzyel** [comment]
Nope. Roller blind curtain.

![harrow-mid-grey-36-roller-blind-a](https://user-images.githubusercontent.com/38145537/109411029-0cbf4a00-79b0-11eb-8362-99deea334bdd.jpg)

**Comment by okanduzyel** [comment]
I tried to trigger via a notification to a light bulb which creates a single PWM. But this JSON, I put below, doesn't work. What am I missing?

```
{
  "c": { "q":1500, "l": 2, "b": [{ "g": 2, "p": 0, "t": 5 }], "0": { "r": [{ "g": 15 }, { "g": 16 }] } },
  "a": [{
    "t": 45,
    "o": 18,
    "c": 14,
    "f": 70,
    "cd": 2,
    "0": { "r": [{ "g": 15, "v": 1 }, { "g": 4 }], "m":[[ 2, -10001 ]]},
    "1": { "r": [{ "g": 15 }, { "g": 4, "v": 1 }], "m":[[ 2, -10001 ]]},
    "2": { "r": [{ "g": 15 }, { "g": 4 }], "m":[[ 2, -10000 ]]},
    "3": { "r": [{ "g": 15, "i": 0.2 }, { "g": 4 }], "m":[[ 2, -10001 ]]},
    "4": { "r": [{ "g": 15 }, { "g": 4, "i": 0.2 }], "m":[[ 2, -10001 ]]},
    "f0": [{ "g": 5, "i": 1, "p": 0, "t":0 }],
    "f1": [{ "g": 13, "i": 1, "p": 0, "t":0 }],
    "f2": [{ "g": 5 }, { "g": 13 }]
  },
  {
    "t":30,
    "it": [50],
    "g":[12],
    "b":[{"g":0}]
  }]
}
```
