### ISSUE TITLE
Activation relay problem SONOFF DUAL v1

### ISSUE THREAD

**Issue by f1jsh** [RavenSystem/esp-homekit-devices#136]
Hello
I use a relay SONOFF DUAL and I can not activate the relays.
I can see the SONOFF DUAL in HOMEKIT
When I activate a relay the blue LED blinks well with each transmission but no activation of the relays.
Do you have an idea ? I am using versionRAVECORE 0.5.4
I also use a SONOFF 4CH module that works perfectly
Thanks for your help.

**Comment by f1jsh** [comment]
Hi, 
is it compatible with SONOFF DUAL (version 1) and SONOFF DUAL V2 ??

**Comment by RavenSystem** [comment]
Can you tell me the GPIO map of both, please?

**Comment by RavenSystem** [comment]
Sorry, but Sonoff Dual old version is not supported, and it will never be supported.

**Comment by sblitzer** [comment]
Can you please advise how can I know if I have v1 or v2?
