### ISSUE TITLE
HAA Menager: Update devices

### ISSUE THREAD

**Issue by Przylepzwm** [RavenSystem/esp-homekit-devices#1362]
How to update devices from version 0.8.6 to the latest version to use the HAA Manager application?  In Setup Mode, I only have Reset ID and WiFi

**Comment by tonysprenk** [comment]
Then you probably did not do the original install with OTA. You must re-flash following installation instructions in the wiki.

**Comment by Przylepzwm** [comment]
Thank you. It will be difficult to disassemble them all, and I will lose my automations
