### ISSUE TITLE
Automatically update?

### ISSUE THREAD

**Issue by okanduzyel** [RavenSystem/esp-homekit-devices#1363]
Hi,

Does HAA automatically update itself when the new version has released?

**Comment by okanduzyel** [comment]
![Initial_Setup_Mode_Page](https://user-images.githubusercontent.com/38145537/111052653-da145780-846d-11eb-890d-441fbe3a8801.jpg)

My question looks isn't clear, sorry. I flashed my esp device and adapted to my home and works now. I marked that checkbox before configured my device. Will it update itself when new version of HAA released?

**Comment by pawelosin** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Setup-Mode#auto-ota-updates

**Comment by okanduzyel** [comment]
Ok. How can I learn my device's HAA version?

**Comment by pawelosin** [comment]
It can be found in the device settings in the home app.

**Comment by okanduzyel** [comment]
v5.0.14 released but my device still in v5.0.10. I marked Auto OTA update checkbox. Why didn't It update itself?

**Comment by pawelosin** [comment]
Sorry, I don't know, but if it's a thermostat, that it must be updated from Setup mode, selecting "Update all now".

**Comment by okanduzyel** [comment]
> Enabling the Auto OTA Updates option causes the firmware to search for an OTA update from the configured OTA repository every time the setup mode is selected and the setup webpage has not been loaded in a browser within 90 seconds.
> 
> If setup web page is loaded, device will restart automatically after 15 minutes, or try to update if auto OTA updates is enabled.

When It downloads and flashes itself? I have HAA v5.0.10, I can quickly open configuration page via that IP 192.168.1.38:4567, auto-update have already checked. I am confusing. 

> Sorry, I don't know, but if it's a thermostat, that it must be updated from Setup mode, selecting "Update all now".

That is sonoff basic lamb

**Comment by pawelosin** [comment]
Put the device in setup mode and do nothing more. Just wait about 15 minutes.

**Comment by okanduzyel** [comment]
> Put the device in setup mode and do nothing more. Just wait about 15 minutes.

Okay, It did. Thank you so much ✋🏻
