### ISSUE TITLE
4ch pro after power loss - mode 4

### ISSUE THREAD

**Issue by dwhp** [RavenSystem/esp-homekit-devices#137]
Hi. When powering on a 4ch pro in mode 4. Ch1 and Ch3 momentarily turns on and off again (ch2 & Ch4 off), before any set initial state applies. Same thing happens with both my 4ch pro and 4ch pro r2. If it does a soft reboot (eg after change setting) it’s ok. Is it something I have done or can change? Dip switches are set as instructed.

**Comment by dwhp** [comment]
Above is only initial power on. All relays turn off (or set initial state) when WiFi connects

**Comment by RavenSystem** [comment]
It is a software issue that will be fixed soon.
