### ISSUE TITLE
HAA Manager does not update from 5.0.3

### ISSUE THREAD

**Issue by mrmaximas** [RavenSystem/esp-homekit-devices#1371]
"Update all HAA devices" does not work
![IMG_2904](https://user-images.githubusercontent.com/61165387/112048796-d6fd2380-8b5f-11eb-9291-ec519d3833a5.png)
![IMG_2905](https://user-images.githubusercontent.com/61165387/112048807-d9f81400-8b5f-11eb-9548-1dd92ed7d86e.png)

**Comment by tonysprenk** [comment]
It only works from version 5.0.12. Update to latest the old fashioned way, after that you can update with HAA manager app.

**Comment by xrust83** [comment]
very interesting screenshot.  explain where to read, how to set up how to use it please.

**Comment by mrmaximas** [comment]
> It only works from version 5.0.12. Update to latest the old fashioned way, after that you can update with HAA manager app.

thanks!

**Comment by mrmaximas** [comment]
> very interesting screenshot. explain where to read, how to set up how to use it please.

https://apps.apple.com/by/app/haa-manager/id1556105121

**Comment by cirrusflyer** [comment]
I'm on 5.0.18 and can't get updates to work via the app.  And not sure how to do this via the web interface either.
