### ISSUE TITLE
Light sensor

### ISSUE THREAD

**Issue by ooomakon** [RavenSystem/esp-homekit-devices#1375]
Hello, please help me to make the light sensor work, I connected it in all known ways with different resistors, it shows 0.0001, how to make it work?

**Comment by okanduzyel** [comment]
I don't know exactly but It still looks under construction, resistor value, power value etc.

https://github.com/RavenSystem/esp-homekit-devices/wiki/Light-Sensor

**Comment by ooomakon** [comment]
Tried various options, doesn't show

**Comment by WojtekWro** [comment]
@ooomakon 
Could you share your json?
Did you add "g": option with sensor gpio

**Comment by ooomakon** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Light-Sensor

**Comment by WojtekWro** [comment]
I know this example but there is missing gpio for the light sensor. That's why I asked about the "g": option.

**Comment by okanduzyel** [comment]
> I know this example but there is missing gpio for the light sensor. That's why I asked about the "g": option.

- LDR is an analog device so, It must be using the analog input pin. 
- There is only one analog input. Therefore, there should not be a definition for it. 

Try to use the analog input pin. (it could be different located-named for various boards) But I don't think it is an accomplished accessory. 

![ESP8266-ESP-12E-chip-pinout-gpio-pin png kopyası](https://user-images.githubusercontent.com/38145537/113518740-d10c3700-9590-11eb-8a6f-74e1fae2cb5d.png)

**Comment by ooomakon** [comment]
> Я знаю этот пример, но отсутствует gpio для датчика освещенности. Вот почему я спросил об варианте "g":.

Did you earn it?

**Comment by WojtekWro** [comment]
> * LDR is an analog device so, It must be using the analog input pin.
> * There is only one analog input. Therefore, there should not be a definition for it.

Thanks @okanduzyel for your explanation.
I didn't know that. 
 I have sensor board with both analog and digital output. I use it as a contact sensor 😜. However I'm looking forward to see full support to light sensors.
