### ISSUE TITLE
WiFi Hotspot problem with 5.0.14.

### ISSUE THREAD

**Issue by epicsepi** [RavenSystem/esp-homekit-devices#1378]
Hey! First, thank you Raven for HAA. 

My problem is, after I connect to the HAA-XXXXXX WiFi hotspot, nothing appear like before. So I cant put the ESP device to my own WiFi.

Tested on MacBook and iPhone too. Any Idea?

Thanks,
Adam

**Comment by tonysprenk** [comment]
The method has changed. See updated [installation instructions](https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation).

**Comment by epicsepi** [comment]
> The method has changed. See updated [installation instructions](https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation).

Very big thanks! I dont saw this new method. I hope it will works to add Home app as well. 

I have an another question. Some of tutorial videos when flashing ESP board, they flahsed with tasmota firmware first, and than HAA, with ticking the "erase the firmware". Why is this important? Now I used only fullhaaboot.bin.

**Comment by Daveblanche** [comment]
If you flash with tasmota( usually a “light”version) then I found it eases the transition to uploading the larger fullhaaboot file. 
I’ve bricked a few sonoff mini (OTA) by trying to use the haa method alone, but they don’t have the memory to cope with it. Using tasmota here has smoothed the ride, for me.

**Comment by epicsepi** [comment]
> If you flash with tasmota( usually a “light”version) then I found it eases the transition to uploading the larger fullhaaboot file. I’ve bricked a few sonoff mini (OTA) by trying to use the haa method alone, but they don’t have the memory to cope with it. Using tasmota here has smoothed the ride, for me.
> […](#)

thank you!!

**Comment by epicsepi** [comment]
> The method has changed. See updated [installation instructions](https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation).
I still have a problem. After add it to WiFi (successfully), in the Home app doesnt apper. Im just waited 30 min, plugged off and plugged in but nothing...

**Comment by jiuwei000** [comment]
HAA can run perfectly on 8266, but when I use 8266-01s, I can't enter the configuration through the web page after connecting to its WiFi.

**Comment by jiuwei000** [comment]
I have the same problem. HAA can run perfectly on 8266, but when I use 8266-01s, I can't enter the configuration through the web page after connecting to its WiFi.

**Comment by Quimeric** [comment]
> > The method has changed. See updated [installation instructions](https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation).
> 
> I still have a problem. After add it to WiFi (successfully), in the Home app doesnt apper. Im just waited 30 min, plugged off and plugged in but nothing...

I'm have the same problem!

My Sonoff SV was updated and since that i can't find to pair again, even when i roll back a previous version.

Making some tests i removed my Sonoff Mini from the Home App and i can't find it either.
