### ISSUE TITLE
Flash ISSUE with MagicHome LED Controller and with NodeMCU PyFlasher 

### ISSUE THREAD

**Issue by epicsepi** [RavenSystem/esp-homekit-devices#1379]
![IMG_5559](https://user-images.githubusercontent.com/73914360/112866852-8f741b80-90ba-11eb-984f-f325c4d509de.jpg)
![IMG_5560](https://user-images.githubusercontent.com/73914360/112866874-9438cf80-90ba-11eb-9dc9-5a760c908913.JPG) 

<img width="794" alt="Képernyőfotó 2021-03-29 - 18 15 43" src="https://user-images.githubusercontent.com/73914360/112867088-c8ac8b80-90ba-11eb-968b-9599c4b09797.png">

What do you think, what is the problem?

**Comment by pasparakis** [comment]
I have same problem...😐

**Comment by arvet333** [comment]
Hi, try to use this app
![Снимок экрана 2021-03-31 145023](https://user-images.githubusercontent.com/80627426/113139983-7a20fd80-9230-11eb-871c-c0f91a15aacf.jpg)
