### ISSUE TITLE
only W on in RGBW bulb?

### ISSUE THREAD

**Issue by toshibochan** [RavenSystem/esp-homekit-devices#1380]
how to turn on only W ON on RGBW bulb or led strip when white is selected?

**Comment by mariusvasss** [comment]
Make a switch just for W, a separate tile in HomeKit

**Comment by toshibochan** [comment]
This is the magichome config. How I change for W as separated tile?

{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"g":[15,13,12,14],"b":[{"g":0}]}]}

**Comment by toshibochan** [comment]
And how set the button to turn ON(100%) and OFF the W color?

**Comment by mariusvasss** [comment]
I'll give you a JSON tomorow

**Comment by toshibochan** [comment]
Thank you @mariusvasss

**Comment by mariusvasss** [comment]
{"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":5,"g":12,"v":13,"b":[{"g":0}]},{"t":30,"w":15,"b":[{"g":4,"p":0},{"g":4,"t":0}]}]}

@toshibochan 

i hope it helps u

**Comment by mariusvasss** [comment]
you can use IR pads for external switch just for white

**Comment by toshibochan** [comment]
@mariusvasss thank you
in "b":[{"g":4,"p":0} who the "p" is for?

**Comment by mariusvasss** [comment]
I don't know. If it works, it's Ok for you. I did it a year ago...

**Comment by toshibochan** [comment]
{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"g":[12,5,13],"b":[{"g":0,"t":3}]},{"t":30,"g":[15],"b":[{"g":0}]}]}
for now when i press once turn ON to de last brightness but what i want is "g":[15] to press once turn ON 100% brightness, press again turn OFF.

**Comment by mariusvasss** [comment]
Have you tried to make it virtual button and duble press for 100%?

**Comment by mariusvasss** [comment]
Or just make it a switch

**Comment by toshibochan** [comment]
I want the button as backup if the device is showing not response so I can turn on manually W color to 100% brightness.

**Comment by mariusvasss** [comment]
Switch is the solution...

**Comment by toshibochan** [comment]
can you make the config using this
{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"g":[12,5,13],"b":[{"g":0,"t":3}]},{"t":30,"g":[15],"b":[{"g":0}]}]}

**Comment by mariusvasss** [comment]
?

**Comment by toshibochan** [comment]
can you give me example

**Comment by mariusvasss** [comment]
{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"g":[12,5,13],"b":[{"g":0,"t":3}]},{"t":1,"g":[15],"b":[{"g":0}]}]}

i think this works. just changed t30 with t1 - switch
