### ISSUE TITLE
HomeKit Device Category not working

### ISSUE THREAD

**Issue by uluozgur** [RavenSystem/esp-homekit-devices#1381]
Hello. I've used the garage door accessory code to run my _[EuroCylinder Lock](http://en.desi.com.tr/utopic-r-ubrc-100)_ on my main door. Since it needs two separate inputs for Open and Close commands, I cannot use Lock Mechanism code. 

After many tries, now I have a perfectly automated HomeKit connected door lock running on Wemos D1 Mini. **Many thanks**.

However, although it is a door lock, it is shown in Home app as a garage door (type 40). I have tried to override this cosmetic problem by using Customized Device Category ("ct" option) in the config section. I have tried both Lock (6) and Door (12). During adding accessory, the icon shown is a door or lock. But after adding it, the icon turns into a garage door (40).

Is this a HAA issue? Or a HomeKit issue? Can it be fixed? Just wanted to draw attention to this "cosmetic" issue. 

Please advise if any further information is needed.

**Comment by kfalkiewicz** [comment]
I have exactly the same issue. Wanted to use "Alarm" ct for my home alarm device (it works like a lock accessory). In the process of adding device I saw correct Icon, but after I added it to HomeKit it changed to normal lock icon.
