### ISSUE TITLE
New wifi network

### ISSUE THREAD

**Issue by orson32** [RavenSystem/esp-homekit-devices#1386]
I changed the name and password of my network, how can I reconfigure the devices for the new network?

**Comment by toshibochan** [comment]
You have to go to setup mode and go to you browse device IP:4567

**Comment by orson32** [comment]
> You have to go to setup mode and go to you browse device IP:4567

how do i go to setup mode? And what is url?

**Comment by toshibochan** [comment]
If you have a button connect to gpio 0, hold for 8 sec or more and release, go to the browser. Use device IP address. Example 192.168.1.67:4567

**Comment by toshibochan** [comment]
Or https://github.com/RavenSystem/esp-homekit-devices/wiki/Setup-Mode

**Comment by orson32** [comment]
> If you have a button connect to gpio 0, hold for 8 sec or more and release, go to the browser. Use device IP address. Example 192.168.1.67:4567

Excelent! Thanks so much

**Comment by xrust83** [comment]
https://youtu.be/EjFnVP9Jsj8
