### ISSUE TITLE
Sonoff Basic RF

### ISSUE THREAD

**Issue by Codkit** [RavenSystem/esp-homekit-devices#139]
Hi there,

May i ask if its possible to flash Sonoff basic RF (esp8285) ? Thank you.

**Comment by RavenSystem** [comment]
Resolved here: https://github.com/RavenSystem/esp-homekit-devices/issues/140

**Comment by brunokelo** [comment]
Hello, can I put raven in a sonff rf? and let the rf pairing function work?
