### ISSUE TITLE
TV Service only show power on/off and source

### ISSUE THREAD

**Issue by xyhh** [RavenSystem/esp-homekit-devices#1391]
![image](https://user-images.githubusercontent.com/3736113/113896676-c05ff900-97fc-11eb-8a88-f8eecbed993f.png)

**Comment by toshibochan** [comment]
In the setting you have to select show volume as dimmer
![3DD2A0A9-1639-4D0C-B0B2-878314A6B9C7](https://user-images.githubusercontent.com/15816913/113901866-22304c80-9784-11eb-9024-8cda373fa7b8.png)

**Comment by xrust83** [comment]
And what relationship does your homebridge plugin have if I'm not mistaken "lg webostv" to the HAA Remote device that is asked about above?

**Comment by toshibochan** [comment]
Sorry was mistake

**Comment by tonysprenk** [comment]
The “remote” in the home app only shows sources so you can setup automations with them. The remote in control centre should show a remote with all buttons. Once your in the remote in control centre you can use the physical volume buttons of your iPhone to control the volume of your tv.

**Comment by xyhh** [comment]
THX
