### ISSUE TITLE
Config for firmware update?

### ISSUE THREAD

**Issue by toshibochan** [RavenSystem/esp-homekit-devices#1396]
Have dummy switch example for firmware update?

**Comment by okanduzyel** [comment]
```
  {
    "i":0.5,
    "1":{ "s":[{ "a":1 }]}
  }
```

**Comment by toshibochan** [comment]
This will enter in firmware update without need to go setup mode?

**Comment by okanduzyel** [comment]
I don't think so. It opens setup mode and I guess you need to enter setup mode via IP address like 192.xxxxxxxx:4567.

**Comment by toshibochan** [comment]
I wish I could do firmware update without go to web interface.

**Comment by WojtekWro** [comment]
{
    "sn":"UPD",
    "1":{"s":[{"a":2}]}
    },
    {
    "sn":"SET",
    "1":{"s":[{"a":1}]}
    }

**Comment by WojtekWro** [comment]
The first one updates firmware without entering setup mode. 
The second one is entering setup mode.

**Comment by toshibochan** [comment]
@WojtekWro it works thanks thanks thanks

**Comment by toshibochan** [comment]
have way to show device ip address in HomeKit?

**Comment by Quimeric** [comment]
> {
> "sn":"UPD",
> "1":{"s":[{"a":2}]}
> },
> {
> "sn":"SET",
> "1":{"s":[{"a":1}]}
> }

I have some devices with old firmware (2.3.2 and 3.5.1) but i never done OTA update and i don't know exactly how. 

Just adding the first button will do the job?
