### ISSUE TITLE
DHT11 module + ESP-01S

### ISSUE THREAD

**Issue by andrewbpowers** [RavenSystem/esp-homekit-devices#1402]
Hello!

I try to connect a module with a DHT11 (temperature and humidity sensor) and a ESP-01S, but it doesn't work.
This is the JSON Config I use: { "c":{ "sn":"ESP01-1", "n":"ESP01-1" }, "a":[ { "t":24, "g":2, "n":1 } ] }

Does anyone have a solution or an idea what the problem could be?
Thank you very much!

**Comment by komarofleo** [comment]
Hi, use this 
{ "c":{ "sn":"ESP01-1", "n":"ESP01-1" }, "a":[ { "t":24, "g":2, "n":1 } ] }
and try 3.3V power supply!

**Comment by andrewbpowers** [comment]
Thank you very much!
Ok, I erase everything with esptool.py and flashing the fullhaaboot.bin.
But, after some minutes "Connecting to Sensor"... again "Unable to Add Accessory". :-(

**Comment by andrewbpowers** [comment]
I restart the router, the sensor module with the ESP-01S and the iPhone. After that, it was possible to add... crazy. But I seems it was the typically Homekit "no response" error thing, which is really annoying. 

Thank you very much for your help!
