### ISSUE TITLE
dw2-WiFi 

### ISSUE THREAD

**Issue by mwouda** [RavenSystem/esp-homekit-devices#1405]
Hi,
Is there any chance to support Sonoff DW2 door, window Contact sensor with ESP-homekit firmware?

https://sonoff.tech/product/wifi-smart-home-security/dw2

If anyone have bin able to flash the device.. could you tell me where the GPIO0 is located?

thx. mark

**Comment by ChristianH99** [comment]
Hi, I don't think so because it is running on an OPL1000 chip instead of the ESP8266. I never had success with other chips.

**Comment by pilot1981** [comment]
I’m able to flash a sonoff basic RFR3 with HAA firmware: it is able to connect to SONOFF DW1
