### ISSUE TITLE
Power Strip

### ISSUE THREAD

**Issue by okanduzyel** [RavenSystem/esp-homekit-devices#1409]
Hi @RavenSystem, 

Do you have any plan to support power strip accessory in next HAA versions?

**Comment by okanduzyel** [comment]
I want to create exactly that accessory, not independent outlets. 

![Ekran_Resmi_2021-04-21_01 11 56](https://user-images.githubusercontent.com/38145537/115785936-d22ec800-a3c8-11eb-8d62-242574e4899c.png)
![Ekran_Resmi_2021-04-21_01 12 06](https://user-images.githubusercontent.com/38145537/115785941-d529b880-a3c8-11eb-8206-10f8c737fd3f.png)

**Comment by okanduzyel** [comment]
the last info:

HAA hasn't support that accessory, yet. 

**Questions and answers:** 
+ Will it is supported?
- Eh, Yes.
+ In the near future? 
- I don't know.

**Comment by mariusvasss** [comment]
You know you can group them and use afterwards just like that. Long press on the group and use individual accessories....

**Comment by okanduzyel** [comment]
They are pretty close but not the same. I think the definition of a power strip is very simple in the homekit coding structure. Although looks very easy to implement in code, It must be a new accessory. It means, new JSON structure, new definitions, and features, etc.

**Comment by RavenSystem** [comment]
Power strip accessory doesn't exist. It is an accessory with 3 or more outlet services.

**Comment by okanduzyel** [comment]
> Power strip accessory doesn't exist. It is an accessory with 3 or more outlet services.

I say the same thing. If the definition of outlets individual for HAA like this:

> "a": [{
>     "t": 2,
>     "s": 5,
>     "0": { "r": [{ "g": 12, "v": 0 }] },
>     "1": { "r": [{ "g": 12, "v": 1 }] },
>     "b": []
>   },{
>     "t": 2,
>     "s": 5,
>     "0": { "r": [{ "g": 4, "v": 0 }] },
>     "1": { "r": [{ "g": 4, "v": 1 }] },
>     "b": []
>   }{
>     "t": 2,
>     "s": 5,
>     "0": { "r": [{ "g": 5, "v": 0 }] },
>     "1": { "r": [{ "g": 5, "v": 1 }] },
>     "b": []
>   }]

Homekit can recognize it as a hub. So, never show it power strip. Its code definition must be like this, under one accessory id definition, three or more outlets.

> homekit_accessory_t *accessories[] = {
>     HOMEKIT_ACCESSORY(.id=1, .category=homekit_accessory_category_switch, .services=(homekit_service_t*[]){
>         HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]){
>             &name,
>             &manufacturer,
>             &serial,
>             &model,
>             &revision,
>             HOMEKIT_CHARACTERISTIC(IDENTIFY, identify),
>             NULL
>         }),
>         HOMEKIT_SERVICE(SWITCH, .primary=true, .characteristics=(homekit_characteristic_t*[]){
>             HOMEKIT_CHARACTERISTIC(NAME, "Socket 1"),
>             &socket_one,
>             NULL
>         }),
>         HOMEKIT_SERVICE(SWITCH, .primary=false, .characteristics=(homekit_characteristic_t*[]){
>             HOMEKIT_CHARACTERISTIC(NAME, "Socket 2"),
>             &socket_two,
>             NULL
>         }),
>         HOMEKIT_SERVICE(SWITCH, .primary=false, .characteristics=(homekit_characteristic_t*[]){
>             HOMEKIT_CHARACTERISTIC(NAME, "Socket 3"),
>             &socket_three,
>             NULL
>         }),
>         HOMEKIT_SERVICE(SWITCH, .primary=false, .characteristics=(homekit_characteristic_t*[]){
>             HOMEKIT_CHARACTERISTIC(NAME, "Socket USB"),
>             &socket_usb,
>             &ota_trigger,
>             &wifi_reset,
>             &task_stats,
>             NULL
>         }),
>         NULL
>     }),
>     NULL
> };

(This code is an example. Not represent HAA)
