### ISSUE TITLE
Request: Use humidity to trigger relay

### ISSUE THREAD

**Issue by moenster** [RavenSystem/esp-homekit-devices#142]
When selecting device type 5 on a TH, it would be nice, if you could use humidity to trigger the relay. In my case specifically, I want to use humidity to trigger if the relay should start a ventilator. It could be a new device type but my point is to use humidity to trigger a fan and not temperatur.

**Comment by RavenSystem** [comment]
You are asking for a HOMEKIT_SERVICE_HUMIDIFIER_DEHUMIDIFIER.

**Comment by digiservice2001** [comment]
The Humidifier/Dehumidifier accessory is very useful. I hope, You will make it asap... 😀

Btw, many many Thanx for Your excellent work! 👍

**Comment by moenster** [comment]
> You are asking for a HOMEKIT_SERVICE_HUMIDIFIER_DEHUMIDIFIER.

Yes, that would cover what I need, and then some.
Thanks a lot, for considering it.

**Comment by RavenSystem** [comment]
Ok, ok, added to TODO List: 
https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List

**Comment by RickNunn** [comment]
+1 to wanting this
