### ISSUE TITLE
iFan03 - no speed control in Home Assistant

### ISSUE THREAD

**Issue by 400HPMustang** [RavenSystem/esp-homekit-devices#1424]
Posing here to see if anyone can help me figure this out. I have a Sonoff iFan03 flashed with HAA 5.0.18. 

When I add it directly to HomeKit the fan has 3 speeds 33%/67%/100% as it should. 

When I add the Sonoff to Home Assistant via HomeKit Controller the fan works only as on/off, no speed control. Additionally when adding the fan back to HomeKit using HomeKit integration the fan has a slider but only works as on/off. 

I tried tackling this from the Home Assistant side with no success, hoping maybe I could get somewhere on this side. 

Thanks!

**Comment by RavenSystem** [comment]
HomeAssistant has to add support for fan speeds. Nothing to do with HAA.
