### ISSUE TITLE
About adjusting the temperature of air conditioning

### ISSUE THREAD

**Issue by WindowsMEMZ** [RavenSystem/esp-homekit-devices#1426]
My air conditioner can only increase or decrease by 1 degree at a time, but the module above that controls the air conditioning can only increase or decrease by 0.5 degrees at a time. How can I set up my JSON so that it can only increase or decrease by 1 degree at a time in HomeKit? @RavenSystem

**Comment by RavenSystem** [comment]
Don't worry about your A/C. HAA works as a fully thermostat and it will manage temperatures, not your A/C.
