### ISSUE TITLE
re-accessing setup mode

### ISSUE THREAD

**Issue by jdohn15** [RavenSystem/esp-homekit-devices#1428]
I cannot go into setup mode if I have already accessed it once and changed the config, this is when I already have the device setup on my network. Is there a way to get around this besides re flashing the device?

**Comment by tonysprenk** [comment]
What is your json?

**Comment by jdohn15** [comment]
> What is your json?

I figured out what was wrong, it was my fault. I did not realize that I had to press the power button 8 times before I could access setup mode.

Thanks
