### ISSUE TITLE
Shelly RGBW2 - always switch on to white colour

### ISSUE THREAD

**Issue by kompak23** [RavenSystem/esp-homekit-devices#1432]
Hello, 
I have an issue, I use Shelly RGBW2 with RGB LED strip as main lighting. 
I use physical switch on the wall to tur on the light, but I need to turn on always white colour.
Is it possible? I have found that there is "it" parremater which can set default colour, but it works only after booting device. 
When someone change colour to other and then turn off light, and after I press switch, the colour is remebered. 

Can somebody help me? 

Thanks, 
kompak23

**Comment by mariusvasss** [comment]
Use a separate accessory only for white with the switch, and colours only in the home app... hope this helps.

**Comment by RavenSystem** [comment]
@kompak23 enter Discord chat and ask there. Other user did that. It is possible using service notifications.

**Comment by kompak23** [comment]
> Use a separate accessory only for white with the switch, and colours only in the home app... hope this helps.

how to set up accessory as white bulb, when there is RGB light strip?
