### ISSUE TITLE
Uncertified Accessory

### ISSUE THREAD

**Issue by richardlimaa** [RavenSystem/esp-homekit-devices#1436]
My devices stopped work after last update 6.0.4, and when deleted from home app i cant add anymore, keet receiving Uncertified Accessory, or Unable to Add Accessory failed with OSStatus code -6764 (kCountErr)

**Comment by ex725** [comment]
I am having the exact same problem.

**Comment by Daveblanche** [comment]
Have you reset the HomeKit I’d on the haa unit? This is required if you remove it from HomeKit or update the json.

**Comment by ex725** [comment]
I've tried all the known ways.
including flashing again.
This situation is like a ban

**Comment by RavenSystem** [comment]
Try v6.0.5.

**Comment by ex725** [comment]
> Try v6.0.5.

everything started working properly.  thanks.

**Comment by kimol88** [comment]
Same
