### ISSUE TITLE
about Using a custom server for OTA updates

### ISSUE THREAD

**Issue by mildrabbit** [RavenSystem/esp-homekit-devices#1446]
I can't connect to GitHub normally. I need to set up my own intranet update server. What are the requirements of intranet server? What software platform do you need? FTP?

**Comment by RavenSystem** [comment]
FTP is not supported, only HTTP.

You need a web server with partial content support, like Apache web server or Nginx.

**Comment by chillmelon** [comment]
> FTP is not supported, only HTTP.
> 
> You need a web server with partial content support, like Apache web server or Nginx.

I appreciate your work but I'm wondering if there is a way to flash with other firmware, for example like tasmota.
