### ISSUE TITLE
Option to delay/sleep? I.e. perform certain action after X seconds?

### ISSUE THREAD

**Issue by Rickth64** [RavenSystem/esp-homekit-devices#1449]
Hi,

Not sure if this is already possible, or that I'm more or less doing a feature request here..

Is it possible to add a delay before performing an action? For example, when having both a light and a fan connected, I would like to turn on the light immediately, but wait a minute before turning on the fan as well..

To make it more complicated. The action should be canceled when the light is turned off within that minute..

Thanks! Great work btw!!

**Comment by i3laze** [comment]
I workaround such things by adding an extra inching switch accessory.
When it goes off after N sec it makes a notification action on the accessory needed.

This way my garage door closes 15 sec after movement detected. All without HomeKit automations.
