### ISSUE TITLE
hi request power meter

### ISSUE THREAD

**Issue by oremic** [RavenSystem/esp-homekit-devices#145]
Congratulations for everything.
there is a library for 8266 for the MCP39F501 microchip, for a project in progress

**Comment by jukorp** [comment]
Koogeek uses this chip HLW8032.
direct pulse out ”Wh” or UART

characteristic
(1) Active power, apparent power, current, and voltage rms can be measured
(2) Active energy pulse PF pin output
(3) Measurement error of active power reaches 0.2% within the dynamic range of 1000:1
(4) In the dynamic range of 1000:1, the effective current measurement error reaches 0.5%.
(5) Within the dynamic range of 1000:1, the effective voltage measurement error reaches 0.5%.
(6) Built-in frequency oscillator
(7) Built-in voltage reference Source
(8) Built-in power supply monitoring circuit
(9) UART communication
(10) SOP8 package type

**Comment by oremic** [comment]
thanks for the advice
the microchip MCP39F501 is already mounted but I can not find the library to be integrated.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki
