### ISSUE TITLE
iFan03 only works at 100%

### ISSUE THREAD

**Issue by Gomeyy** [RavenSystem/esp-homekit-devices#1450]
I just flashed my Sonoff iFan03 using the config 

`{
  "c":{"l":13,"b":[{"g":0,"t":5}]},
  "a":[{
    "t":65,
    "e":3,
    "0":{"r":[{"g":15},{"g":12},{"g":14}]},
    "y0":[
      {"v":1, "0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]} },
      {"v":2, "0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]} },
      {"v":3, "0":{"r":[{"g":15,"v":1},{"g":4},{"g":14}]} }
    ]
    },{
      "t":1,
      "1":{"r":[{"g":9}]},
      "0":{"r":[{"g":9,"v":1}]},
      "b":[{"g":0}]
    }
  ]
}`
When I change the speed to anything other than 100% it turns on briefly and then turns off. Unsure what the cause of this is, would appreciate any help. Thanks

**Comment by bencharlesrhys** [comment]
This is what I used. Works perfectly.

`{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":65,"e":3,"0":{"r":[{"g":15},{"g":12},{"g":14}]},"y0":[{"v":1,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]}},{"v":2,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]}},{"v":3,"0":{"r":[{"g":15,"v":1},{"g":4},{"g":14}]}}]},{"1":{"r":[{"g":9}]},"0":{"r":[{"g":9,"v":1}]},"b":[{"g":0}]}]}`
