### ISSUE TITLE
D1 mini + 4 relay + remote to control garage door. How to code Json config?

### ISSUE THREAD

**Issue by MJdinkel** [RavenSystem/esp-homekit-devices#1451]
Hi, 
It’s my first time to DIY a smart device. I use D1 mini + 4 relay + remote (as the image) to flash Tasmota and upgrade HAA. I have no idea about Json config. I think this ([haa-configurator](https://glumb.github.io/haa-configurator/) ) might be helpful.  But I don’t know how to make the correct code.
![0659E66D-7F5E-42A8-8952-8350285030FF](https://user-images.githubusercontent.com/86388038/123197781-a0c49c80-d4de-11eb-8eee-cf4f420b2dc0.jpeg)

**Comment by MJdinkel** [comment]
Can I use this Jason code?

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"i":0.5,"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":14}]},{"i":0.5,"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"i":0.5,"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]},{"i":0.5,"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":10}]}]}

**Comment by ch0w7** [comment]
did you figure out the code? I have a d1 mini and a 4 relay and looking to get HAA configuration
