### ISSUE TITLE
MagicHome rgb stop working

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#1453]
Hi, my rgb controller stop working last night. The controller is connected to wifi but in my router settings is shown as haa-f8f4fc, not the name I entered in json. Now it is not shown in home app. I tried reset settings, reset homekit id , but the problem is same. 
![AC7EFD07-ECE1-499D-82EA-47717E855FA2](https://user-images.githubusercontent.com/48009267/123536604-fe9df200-d733-11eb-81a6-035eec9d72fb.png)
![73D984B2-45E9-4E87-8C4B-DD2C23AE21A2](https://user-images.githubusercontent.com/48009267/123536606-0198e280-d734-11eb-9207-64298da2d477.png)
![A119258F-6DBE-4E0B-8981-3E2D4CE8B535](https://user-images.githubusercontent.com/48009267/123536607-02317900-d734-11eb-879f-462ed5d33b16.png)

**Comment by mafyata** [comment]
This is my json that worked until last night. 
{"c":{"n":"Hol-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13,"fr":5,"fg":5,"fv":5},{"0":{"r":[]},"1":{"r":[],"s":[{"a":1}]},"t":1,"b":[],"s":0}]}

**Comment by Hanimaniac** [comment]
I had an similar Issue, while updating to the latest Version.
I had had to change the rgb gpio lines in the jason from "r":5,"g":12,"v":13 to "g":[5,12,13]. This is a newer confic scheme from HAA. After that Change, my Controller worked again (but was shown in home all the time, maybe you have to change some other parts of your json).

**Comment by mafyata** [comment]
Can someone help with new scheme.

**Comment by mafyata** [comment]
Everything is ok now. Thanks.
