### ISSUE TITLE
Are the new Sonoff devices compatible with HAA (not actually an issue)

### ISSUE THREAD

**Issue by tlagarto** [RavenSystem/esp-homekit-devices#1457]
This is not actually an issue but I wanted to know if these devices are compatible with HAA fw:
SONOFF DUALR3
SONOFF TX Series
SONOFF MINIR2
SONOFF T4EU1C

Could some one help?
Thanks in advance

**Comment by mariusvasss** [comment]
Mini r2 is, tested!

**Comment by mariusvasss** [comment]
@tlagarto if you mean the touch wall switch, tested all 1,2,3 gangs.

**Comment by Murdrock** [comment]
how about SONOFF DUALR3 ? Will there be any support soon?

Thanks in advance.

**Comment by mariusvasss** [comment]
If it's an esp will work and I think it is.

**Comment by Murdrock** [comment]
I have a couple of em coming. I'll make a test. But I see that it is ESP32. Will I be able to firmware it?

**Comment by mikwayhk** [comment]
> @tlagarto if you mean the touch wall switch, tested all 1,2,3 gangs.

I'm currently using the T2UK version, one 1 gang & two 3 gangs. Could u tell me how to flash HAA into the chips? Cuz i have trouble to find which spot connecting PC....
