### ISSUE TITLE
how to change the HomeKit pairing code

### ISSUE THREAD

**Issue by huanghyw** [RavenSystem/esp-homekit-devices#1461]
like title says, how can i change the HomeKit pairing code?
if con't change, can i add other devices?

**Comment by Daveblanche** [comment]
Go Into setup mode and click the box that says “reset HomeKit ID”.

**Comment by tonysprenk** [comment]
It is illegal to change HomeKit pairing code. You can add as many devices to the home app as you want using the same code.

**Comment by Daveblanche** [comment]
> It is illegal to change HomeKit pairing code. You can add as many devices to the home app as you want using the same code.

Ah. I misunderstood the question. Apologies.

**Comment by huanghyw** [comment]
thanks, @tonysprenk and @Daveblanche
