### ISSUE TITLE
IR HEX to HAA IR code Conversions

### ISSUE THREAD

**Issue by dwhp** [RavenSystem/esp-homekit-devices#1464]
Recently I flashed a Generic Amazon IR blaster transmitter (Jinvoo WiFi Smart Universal Remote Controller). I can find a selection of codes in HEX on remotecentral.com. specifically the Foxtel IQ3 (Australian PayTV Cable TVBox). My Question is if there is a way to convert to raw or to work out HAA protocol & code from the HEX string easily? THANKS in advance for any insight :)

Example of a Key:
Power
0000 0073 0000 0012 000F 000A 0006 000A 0006 0016 0006 000A 0006 0010 0006 0016 0006 0016 0006 000A 0006 000A 0006 000A 0006 0016 0006 0010 0006 0016 0006 000A 0006 000A 0006 001C 0006 000A 0006 0C94

Result using iConvert:
{
  "frequency": 36000,
  "irCode": "15,10,6,10,6,22,6,10,6,16,6,22,6,22,6,10,6,10,6,10,6,22,6,16,6,22,6,16,6,16,6,22,6,16,6,3208",
  "preamble": "",
  "repeat": 1
}

For anyone that's interested:
Jinvoo WiFi Smart Universal Remote Controller
TYWE3S
GPIO 04 - Status LED
GPIO 05 - RX IR LED
GPIO 13 - RST SWITCH 
GPIO 14 - TX IR LEDs

![Jinvoo](https://user-images.githubusercontent.com/45319492/124429967-e8d2a180-ddb1-11eb-912f-e9a5030bd794.jpg)

**Comment by xrust83** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Infra-Red

you have to learn each button yourself according to the instructions, or wait for someone to do it for you and lay out the codes to the remote control.

https://github.com/RavenSystem/esp-homekit-devices/issues/823
