### ISSUE TITLE
Sonoff 4CH Pro Unable join to homekit

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#147]
Hello.....
Just tried flash no.2 sonoff 4 Ch Pro R2 and I'm having problem to join to homekit
- esptool wrote me flash is ok
- Typed required settings on OTA (wifi, password, repository)
- Leave device for 10 minutes to download firmware 
- unplug and plug to power and try join device to homekit but Home APP wont see 
After I setted the K5 and S6 dip switch, led of ch 1,2,3 switch on with red color but switches on left side don't work

Any suggestion?
Where is wrong? Thank you

**Comment by Partizan7676** [comment]
is that device flashing on this firmware first time? do you use it before with homekit?

**Comment by GPL71** [comment]
Solved but ......
- I'd flash the 4Ch pro R2 with main.bin. rboot.bin and blank_config.bin and all is ok and I was able add to homekit. Now it's working.

The problem is the OTABOOT.bin
I can flash every kind of SONOFF (just tried with others new brand Ch 4 Pro R2 and Dual R2)
I've downloaded the 3 .bin updated (and I tried with the oldest too)
Flashing go to the end without problem
I'm able set the repository and the net.
The update operation start but I don't know if it is OK (I think yes because the device is missing in AP list of wifi)
After 15 min I unplug and plug the device, but nothing seem starting and HOME APP couldn't see it

May be a problem beetween repository and OTABOOT.bin?

I'd erase and flash module several time without success...

I think OTA update is a very important feature

Thanks for help

**Comment by GPL71** [comment]
@RavenSystem  
Hello .... please can you help me to solve the strange problem I have with latest releases?
I’d flash more devices by OTA without problems.
But I’d flash 2 4ch pro r2 and 1 dual r2 by OTA. 
The system after flashing and typed the new repository seems start to download firmware, but nothing change after several miutes.
Instead flashing the main.bin the module start soon 
But I need the OTA update 

Thank you for your help

**Comment by netRunner0** [comment]
I encountered the same problem. The device constantly reconnects to the network, approximately every 3-4 seconds.
while it loads something, but not more than 10 megabytes in 30 minutes.

I cleared the flash and flashed it 5 times, but nothing changes. There is a solution?

**Comment by Partizan7676** [comment]
Netrunner0 can you try it with other Apple ID ? Same?

**Comment by netRunner0** [comment]
Partizan7676 I do not think this is related to the account. Based on the logs of the router, the device is constantly connected to the network every 3-5 seconds which is not normal. At the same time, I successfully flashed 1 Basic and TH-16.

Problems are observed in the second Basic and 4ch pro ...
