### ISSUE TITLE
HAA Manager

### ISSUE THREAD

**Issue by cirrusflyer** [RavenSystem/esp-homekit-devices#1471]
Should I be able to update the firmware on my devices using the HAA Manager?  When try, nothing happens.  Is there another way to update to the latest version?  Currently at 5.0.18 firmware.

**Comment by Daveblanche** [comment]
There is the standard push of the bottom on the unit for 8seconds or turn the unit on and off 8 times. You can also try powering it on then off (form the power source ) within (?) 5seconds to make it go into setup mode. Then use <ip.address>:4567 to look for the unit once it is in setup mode. Or you can use „radar“ in the manager App to highlight any units that are in set up mode. 
that lot should keep you busy.

**Comment by cirrusflyer** [comment]
Thanks.  I can get them into setup, but I don't recall a way to update them to the latest version once there.

**Comment by Daveblanche** [comment]
tick the bock next to "update all" and then click save. As long as you are viewing it through your wife network then it will update. If you are viewing it through its own Hotspot then you will have to input the correct wifi credentials first.

**Comment by xrust83** [comment]
> Thanks.  I can get them into setup, but I don't recall a way to update them to the latest version once there.

![image](https://user-images.githubusercontent.com/58448955/125478593-16c2de0a-f0bb-46c9-bf7e-7c49014d4718.jpeg)

**Comment by cirrusflyer** [comment]
Ah yes, I recall now the last time I tried that and it made no difference.  I'll try again now.

**Comment by krzysztofKubiakVizlib** [comment]
Did you solve your issue @cirrusflyer ?

**Comment by cirrusflyer** [comment]
Yes, thanks.  The firmware updated recently with  the last two versions.  9.x and 10.x.
