### ISSUE TITLE
relay4 trigger once when device power on

### ISSUE THREAD

**Issue by justlight220** [RavenSystem/esp-homekit-devices#1473]
Hi,
after flash fullhaaboot.bin firmware, relay4 not tigger when device power on
but, after setting up wifi , relay4 tigger once when device power on.
is any solution can fix it?

Device: Sonoff 4ch pro r3
Json Config
```json
{
    "c": {
        "l": 13,
        "b": [
            {
                "g": 0,
                "t": 5
            }
        ]
    },
    "a": [
        {
            "i": 0.5,
            "0": {
                "r": [
                    {
                        "g": 15
                    }
                ]
            },
            "1": {
                "r": [
                    {
                        "g": 15,
                        "v": 1
                    }
                ]
            },
            "b": [
                {
                    "g": 14
                }
            ]
        },
        {
            "i": 0.5,
            "0": {
                "r": [
                    {
                        "g": 12
                    }
                ]
            },
            "1": {
                "r": [
                    {
                        "g": 12,
                        "v": 1
                    }
                ]
            },
            "b": [
                {
                    "g": 0
                }
            ]
        },
        {
            "i": 0.5,
            "0": {
                "r": [
                    {
                        "g": 5
                    }
                ]
            },
            "1": {
                "r": [
                    {
                        "g": 5,
                        "v": 1
                    }
                ]
            },
            "b": [
                {
                    "g": 9
                }
            ]
        },
        {
            "i": 0.5,
            "0": {
                "r": [
                    {
                        "g": 4
                    }
                ]
            },
            "1": {
                "r": [
                    {
                        "g": 4,
                        "v": 1
                    }
                ]
            },
            "b": [
                {
                    "g": 10
                }
            ]
        }
    ]
}
```

**Comment by justlight220** [comment]
device power on video
https://user-images.githubusercontent.com/75196944/125927185-6fbb224d-2e0e-43f1-ad0f-f233da2c587c.mov

**Comment by RavenSystem** [comment]
Which GPIO uses relay 4?

**Comment by justlight220** [comment]
relay use GPIO 15 
button use GPIO 14 

<img width="682" alt="Screen Shot 2021-07-16 at 6 16 48 PM" src="https://user-images.githubusercontent.com/75196944/125932860-105940d3-943f-4b99-b9a7-783217d3ebd5.png">

**Comment by RavenSystem** [comment]
Let me some minutes to rebuild a beta version.

**Comment by Daveblanche** [comment]
Awesome!

**Comment by RavenSystem** [comment]
Try beta v6.53.1:

https://github.com/RavenSystem/haabeta

**Comment by justlight220** [comment]
I'm not sure update success or not
update use these step
1. change Custom server for updates: to github.com/RavenSystem/haabeta/releases/download/6.53.1
2. change port to 443
3. enable Secure connection
4. selected Update all now (HAA OTA v4.9.0)
5. click save
6. screen show ok

setup mode still show Home Accessory Architect v6.3.0
what other step need to do?
<img width="992" alt="Screen Shot 2021-07-16 at 8 49 49 PM" src="https://user-images.githubusercontent.com/75196944/125950382-16274880-86ba-457b-9560-a874dc115354.png">

**Comment by RavenSystem** [comment]
Change Custom server for updates to: github.com/RavenSystem/haabeta/releases/latest/download

And do other steps again.

**Comment by justlight220** [comment]
It works. Thank for your help.

**Comment by RavenSystem** [comment]
Can you try last BETA version 6.54.0, please?

**Comment by justlight220** [comment]
Also work. relay4 not trigger when power on.
<img width="951" alt="Screen Shot 2021-07-17 at 12 24 55 AM" src="https://user-images.githubusercontent.com/75196944/125979123-b3c99ce5-6857-42fa-938e-6cab96f15a6d.png">

**Comment by RavenSystem** [comment]
Many thanks. 

You can leave beta repo removing all content of "Custom server for updates".

HAA v6.4.0 has been released including changes about this matter.

**Comment by justlight220** [comment]
Got it. Thank you for your help.
