### ISSUE TITLE
Problem after updating to 6.70

### ISSUE THREAD

**Issue by BartoszGan** [RavenSystem/esp-homekit-devices#1479]
After updating to 6.70 all shelly 2.5 stop responding from HomeKit? any idea ?

**Comment by kx3kx3kx3** [comment]
same problem

**Comment by RavenSystem** [comment]
A fix is incoming.

**Comment by RavenSystem** [comment]
Update to v6.7.1.

**Comment by BartoszGan** [comment]
everything works! thanks a lot
