### ISSUE TITLE
Uncertified Accessory 6.7.2

### ISSUE THREAD

**Issue by kimol88** [RavenSystem/esp-homekit-devices#1483]
My devices stopped work on some devices after last update 6.7.2, and when deleted from home app i cant add anymore, keet receiving Uncertified Accessory, or Unable to Add Accessory failed with OSStatus code -6764 (kCountErr)
 #1436

**Comment by RavenSystem** [comment]
JSON?

**Comment by kimol88** [comment]
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"s":5,"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"i":1,"b":[{"g":0}]},{"s":5,"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"i":1,"b":[{"g":9}]},{"s":5,"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":10}]}]}

**Comment by RavenSystem** [comment]
What version was you using before?

**Comment by kimol88** [comment]
6.5.2

**Comment by kimol88** [comment]
Is it works? I want downgrsde
github.com/RavenSystem/haa/releases/download/6.6.0

**Comment by RavenSystem** [comment]
You can downgrade, but check available versions here: https://github.com/RavenSystem/haa/releases

Are you using iOS 15?

**Comment by richardlimaa** [comment]
Can i do downgrade from web? or need to flash again?

**Comment by kimol88** [comment]
> You can downgrade, but check available versions here: https://github.com/RavenSystem/haa/releases
> 
> Are you using iOS 15?

So link without download?

No iOS 14.6

**Comment by RavenSystem** [comment]
I can pair it without any issue. iPhone 12 iOS with 14.7.

**Comment by kimol88** [comment]
I did it after downgrade to 6.0.7

**Comment by kimol88** [comment]
I think something wrong in my home :/
On 4 devices when I have 6.5.2 on wife's iPhone everything fine. When I'm update to 6.7.2 this devices on my iPhone everything fine but on my wife iPhone "no reponse" :(

Wife's AppleID is main in HomeKit

Maybe You know fix?

**Comment by RavenSystem** [comment]
OSStatus code -6764 (kCountErr) will be showed when a device is already paired.

**Comment by richardlimaa** [comment]
Thanks RAven! After update to 6.8 everything is ok
