### ISSUE TITLE
ESP2866 RELAY V3

### ISSUE THREAD

**Issue by richardlimaa** [RavenSystem/esp-homekit-devices#1486]
Hi,

Im trying to use this device as locker mechanism but, no GPIO works, any one already tryied?

http://www.chinalctech.com/uploads/allimg/190125/153933J43-1.jpg

**Comment by tonysprenk** [comment]
I believe this device uses a secondary mcu. The esp sends serial commands to the secondary mcu. HAA supports sending serial commands but not receiving. If you figure out what the right command is to trigger the relay it should work.

**Comment by RavenSystem** [comment]
Some people on Discord chat have it working. Better, ask there.

**Comment by todely** [comment]
Try to check:
https://github.com/RavenSystem/esp-homekit-devices/issues/1552
