### ISSUE TITLE
Upgrade RavenCore 1.2 to HAA

### ISSUE THREAD

**Issue by rickdhoy** [RavenSystem/esp-homekit-devices#1488]
Hi All,

I have been reading and reading everything I can find and feel really stupid.

I am trying to update my Ravencore devices to HAA but for the life of me I can not find the set up menu showing the ability to do the update in the EVE app. I have even downloaded an older version of the EVE App but for the life of me I can not find how to enter set up !!

I have been trying to follow these instructions:

https://github.com/RavenSystem/esp-homekit-devices/issues/686

To do the update.

For example I have not been able to find the window in the image below.

![65042146-8b5d2e80-d958-11e9-8601-acbe92942aa6](https://user-images.githubusercontent.com/61440572/126951647-22af38d0-c69f-4494-b01d-a6d102f74c17.jpeg)

I have paid and downloaded the HAA Manager from the developer but that won't also let me update the devices.

You can see a few opt the devices below.

![IMG_1702](https://user-images.githubusercontent.com/61440572/126951998-60f2ba24-e5ca-4eac-8116-770ea8a188f9.PNG)

I am using the latest IOS and have tried both the EVE Legacy App and the latest version from the App store.

I am sure thuis is simple and I will kick myself but really need some help.

**Comment by tonysprenk** [comment]
If I’m not mistaken OTA update of older Ravenscore devices is only possible when they were originally flashed with LCM OTA. It looks like your device wasn’t. The only way to update it would be to flash it by wire.

**Comment by xrust83** [comment]
You are right, most likely you will not be able to just update and there are at least 3 reasons for this

1. Upgrading from ravencore to haa worked for a short period of time about 1.5 months.  a special repository was opened for this.

2. haa manager application works with version 5.0.18 if I'm not mistaken that it doesn't suit you either.

3.you could flash your devices to a version without OTA or (the last swan) that do not support updating through the air.

the best advice is to remove your devices and flash them again via the cable to the latest firmware and in the future to update the devices to the latest versions.

**Comment by i3laze** [comment]
Sorry, but the instruction you’ve used ends with he words “GitHub OTA issues”.

Out of nowhere 1.5 months after HAA initial release GitHub proxy-servers hosted at Amazon introduced case-sensitive HTML Headers (specifically “Location”), which was totally incompatible with existing legacy RavenCore and HAA code.

You have to re-flash by wire.

**Comment by rickdhoy** [comment]
Hi All, Thanks for the quick response. This is going to era  really painful process as I have so many of these devices :-) Ohh well.

Thanks

**Comment by i3laze** [comment]
Not to mention you’ll have to learn HAA JSON syntax using Wiki.
I strongly suggest you begin with web-configurator:
https://glumb.github.io/haa-configurator/
