### ISSUE TITLE
Shelly2 firmware

### ISSUE THREAD

**Issue by maxricmag** [RavenSystem/esp-homekit-devices#149]
The firmware work with shelly 2? If no, do you do the firmware for shelly 2?

**Comment by RavenSystem** [comment]
No. But if you are interested, post here gpio map of Shelly2 and I could support it.

**Comment by maxricmag** [comment]
Max

**Comment by peros550** [comment]
I may be wrong but I think Shelly 2 is not designed to be open like Shelly 1.

**Comment by AramVartanyan** [comment]
I have just examined the pins. They are as follows:
SW1 - GPIO14
SW2 - GPIO10
Relay1 - GPIO4
Relay2 - GPIO5

Only the MCP39F501 left to be understood.

**Comment by maxricmag** [comment]
I have see in interneet that some one has do the firmware for shelly 2 for HomeKit...

https://www.musicjinni.co/4roOlLFK4ij/Homekit-Apple-su-Shelly-2-per-Gestione-Tapparelle-e-Garage-Firmware-senza-bridge.html?9ec59bf0d05ab4bbfe46366da9023c70

Max

**Comment by gnomosg** [comment]
Hi, I flashed shelly2 successfully - great job José :)
but I don't see the second relay in Eve nor Home app. 
I tested all 3 Board Types with no success (with device type=13).
Could anyone test and confirm visibility of second relay in application?
Thanks in advance...

**Comment by RavenSystem** [comment]
@gnomosg It is a bug, sorry. It will be fixed with the next update.

**Comment by RavenSystem** [comment]
@gnomosg Please, update to version 0.5.14 and test it.
