### ISSUE TITLE
Feature request: Sonoff TH humidity support

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#15]
I'd like to have a rain sensor (humidity > 60%), which will trigger other HomeKit accessories.
Sonoff TH10 with AM2301 (or better Si7021) looks perfect, but according to Wiki humidity is not supported yet:
https://github.com/RavenSystem/esp-homekit-devices/wiki/Sonoff-TH
Or is it? Thermostat = Temp + Hum?

What's the main cause for Si7021?

Actually I'd like to toggle a lamp using TH10 relay on schedule, absolutely not related to Temp/Hum.
And use Humidity data for other devices. Is there a solution for such scenario, other than HomeBridge with one device added twice or purchasing separate Sonoff Basic?

**Comment by RavenSystem** [comment]
The sensor used by this firmware is any DHT22 compatible. I tested Si7020 sensor with DHT11 and DHT22 and it didn’t work. 

Youa can code a firmware that uses Sonoff TH as temperature and humidity monitor, and a separate switch to manage its relay. 

You can obtain examples and documentation of coding HomeKit here: 
https://github.com/maximkulkin/esp-homekit
https://github.com/maximkulkin/esp-homekit-demo

**Comment by i3laze** [comment]
I see, that currently HomeKit can't yet trigger on temp/humidity values
 _BTW, Tasmota can do such thing using rules, but that's much more complicated level of automation._

Si7021 sensor support is still welcome.
Topic closed for now.

**Comment by RavenSystem** [comment]
HomeKit can trigger on temp/humidity thresholds, but you need a third-party App, like ElGatoEVE or this: https://itunes.apple.com/us/app/home-smart-home-automation/id995994352?mt=8

**Comment by RavenSystem** [comment]
Si7021 has not support planned, only DTH11 and DTH22 will be supported.

Sonoff TH firmware is showed as thermostat device. A 2-devices (temp/hum and switch) version will be done when I get some free time to continue development.

**Comment by RavenSystem** [comment]
Upcoming Sonoff RavenCore firmware will have DTH11 and DTH22 support, and a switch + temp/hum sensor will be an option too (Not thermostat).

**Comment by RavenSystem** [comment]
new firmware that supports a switch + temp/hum sensor  has been release:
https://github.com/RavenSystem/esp-homekit-devices/wiki/Sonoff-RavenCore

**Comment by seritos** [comment]
Will be possible to support the original sensor AM2301?

Thanx!

**Comment by RavenSystem** [comment]
AM2301 is a DHT22 type sensor.

**Comment by pandarek** [comment]
and it works great

**Comment by minitoine** [comment]
Could the AM2301 be connected to the Sonoff TH (10 in my case) via the "jack" port ?
