### ISSUE TITLE
Termostato 

### ISSUE THREAD

**Issue by arturodiazad1** [RavenSystem/esp-homekit-devices#150]
Hola, es posible crear un termostato con un Sonoff básico? He intentado crearlo conectando un sensor DS18B20 al GPIO14, pero no lee la temperatura

**Comment by seritos** [comment]
Si el sonoff es la ultima revision, tienes que seleccionar el GPIO2. Puedes configurarlo en EVE

**Comment by arturodiazad1** [comment]
Gracias, me puedes explicar como compruebo si es la última revisión el sonoff?

**Comment by seritos** [comment]
Abrelo y dale la vuelta. Si es como este, es la version antigua. Se que ademas hay alguna variacion en la serigrafia en la parte de arriba, pero no puedo confirmarte exactamente que pone.

https://1.bp.blogspot.com/-Wm5Uy32MjMA/XBuk9_5JR5I/AAAAAAAADH0/rnwhZl8bNVYzJyTXCT48jpB8xC_H8V0QwCLcBGAs/s1600/IMG_20181220_141352.jpg

Tendras, ademas, que asegurarte que tienes la ultima version de ravencore

**Comment by arturodiazad1** [comment]
Todos los sonoff son como la imagen, la versión antigua, me puedes indicar el criterio de búsqueda o alguna referencia para poder buscar y comprar los sonoff de última revisión? Muchas gracias.

**Comment by seritos** [comment]
Cualquiera que compres ahora sera de la nueva revision. De todas formas, porque quieres comprar uno nuevo? Deberia funcionarte perfectamente con uno de los antiguos.  
Has configurado correctamente el sensor en la aplicacion de EVE?

**Comment by RavenSystem** [comment]
Yo opino que el tipo de sensor no está bien configurado (tiene que ser el 3), y otra cosa, tiene que ser un DS18B20 one-wire, que creo recordar que estos sensores también los hay I2C.

**Comment by seritos** [comment]
Pueba primero a configurarlo como un sonoff basico + termometro. 

Tipo 6 y sensor tipo 3.

Si te funciona, pues pones en modo termostato ( 5 )
