### ISSUE TITLE
Sonoff T2US3c json? 

### ISSUE THREAD

**Issue by nikogeek** [RavenSystem/esp-homekit-devices#1501]
i need the 3 channel sonoff json.

I used this but it didn't work: 
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":10}]}]}

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave issues only for issues.

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
