### ISSUE TITLE
Sonoff T0US3C json?

### ISSUE THREAD

**Issue by nikogeek** [RavenSystem/esp-homekit-devices#1503]
Hi there! I need help. I have several sonoffs already working with homekit, all of them with 1 or 2 channels. The only one I'm missing is a 3-channel one, but it shows me an error every time I want to link it with homekit. The json that I am using is:

Could anyone help me?

`{
  "c": {
    "l": 13,
    "b": [
      {
        "g": 0,
        "t": 5
      }
    ]
  },
  "a": [
    {
      "0": {
        "r": [
          {
            "g": 12
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 12,
            "v": 1
          }
        ]
      },
      "b": [
        {
          "g": 0
        }
      ],
      "s": 0
    },
    {
      "0": {
        "r": [
          {
            "g": 5
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 5,
            "v": 1
          }
        ]
      },
      "b": [
        {
          "g": 9
        }
      ],
      "s": 0
    },
    {
      "0": {
        "r": [
          {
            "g": 4
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 4,
            "v": 1
          }
        ]
      },
      "b": [
        {
          "g": 10
        }
      ],
      "s": 0
    }
  ]
}`

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave issues only for issues.

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
