### ISSUE TITLE
What does this sentence mean? "c": { "l": 1, "b": [{ "g": 2, "t": 5 }] },

### ISSUE THREAD

**Issue by Bohan-Song** [RavenSystem/esp-homekit-devices#1505]
What does this sentence mean? I don’t understand. Can anyone help me explain

{
  **"c": { "l": 1, "b": [{ "g": 2, "t": 5 }] },**
  "a": [{
    "t": 1,
    "s": 1,                                     
    "0": { "r": [{ "g": 0, "v": 1 }] },
    "1": { "r": [{ "g": 0, "v": 0 }] },
    "b": [{ "g": 2 }]
  }]
}

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave issues only for issues.

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
