### ISSUE TITLE
How to compile HAA by myself on mac?

### ISSUE THREAD

**Issue by Romadhonfajar** [RavenSystem/esp-homekit-devices#1507]
Hi everybody, I'm new on HAA community and I get a little confused how to compile HAA by myself on mac. Can I get some instructions? Because I already read the wiki but still not get the answer.
I'm very glad if I can get some help from you guys. Thank you.

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
