### ISSUE TITLE
Can't connect to HAA network

### ISSUE THREAD

**Issue by miguelpruivo** [RavenSystem/esp-homekit-devices#1510]
Hi, I've flashed my bulb (with Tasmota) and by the first time it worked properly and allowed me to enter the correct settings in the config page, however, nothing seems to work, neither the bulb itself nor the homekit detection for which I suspect I could have entered the wrong configs.

Now, I'm trying to try new configs but I can't seem to be able to reach the config page again. Already tried turning off, on/off 8 times etc. and I can see briefly the HAA network showing up in my iPhone/Mac, but I can't connect at all to it.

What solutions have I left?

Thanks!

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
