### ISSUE TITLE
Ice melt thermostat

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#152]
Ice melt system is a relay with two thermostat controllers to limit working temp.
Such system usually turn on heaters on the roof/ramp/driveway when outdoor temp is between -3C and +5C to help icicles melt:
https://www.ojelectronics.com/business-areas/electric-floor-heating/products/thermostat-for-heating-cable-in-gutters-prod336
Even more advanced system with humidity sensor:
https://www.midselec.co.uk/erc-snow-and-ice-melting-controller-and-sensor.html

A. One Sonoff with DH22/DS18B20 might be represented as two dependant thermostats (a heater and a cooler). 
Or 
B. A regular heater thermostat with an option (hidden in Eve.app) to turn off above some T=5C.

How about such device mode?

**Comment by RavenSystem** [comment]
It is not possible. Target temperature of an Apple HomeKit thermostat is between 10ºC and 38ºC.

**Comment by Korcsog** [comment]
@i3laze No need for that. I'm using one Sonoff Basic with DS18B20 for this purpose... You could create two automations in the Eve app... one for turning on the thermostat when temp is below e.g. -3 degree and an another one for turning off the thermostat when +5 degree reached!

**Comment by i3laze** [comment]
Thanks! Will go Tasmota here.

Happy New Year!
