### ISSUE TITLE
Energy meter with GPIO pulses?

### ISSUE THREAD

**Issue by therealbat** [RavenSystem/esp-homekit-devices#1520]
Is there a way to add GPIO pulse based energy measurement? i'd like to integrate DIN rail mounted power measure equipment with S0 output. per minute rate and total power consumption would be really nice.

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
