### ISSUE TITLE
SONOFF DUAL pilot wire for electrical radiator management

### ISSUE THREAD

**Issue by f1jsh** [RavenSystem/esp-homekit-devices#154]
Hello José,
thank you for your development, very nice work! really good!
Consider developing a mode of operation for the management of electric radiator heating modes with pilot wire.
It is very simple to add two diodes in the SONOFF DUAL module to pilot the radiator.
What do you think ?
Thank you and happy new year 2019
Oliver

https://www.planete-domotique.com/blog/2012/01/05/piloter-un-radiateur-grace-a-son-fil-pilote/

![image](https://user-images.githubusercontent.com/7425260/50573326-3da49400-0dd2-11e9-9e12-3841cc1b177a.png)

**Comment by shingle-smith** [comment]
Without adding diodes to the Sonoff, do you think it would still be possible to trigger 'eco' mode with 240V AC from the relay?

**Comment by shingle-smith** [comment]
Thanks - but in theory a signal from a Sonoff Basic single relay through the pilot wire should work as a trigger for eco/réduit mode, correct? (230V pleine alternance)

**Comment by shingle-smith** [comment]
I’ve now tested this using a Dimplex Q-Rad electric radiator, which can use a pilot wire energised at 230/240V AC.

When the Sonoff basic is switched off, the heater is in Comfort mode (and starts heating up), and when the relay is on, the heater turns to Setback mode, 5c lower than comfort.

There is no way of setting fully ‘off’ as that would require a diode to filter positive/negative.

**Comment by f1jsh** [comment]
The ideal is to take a SONOFF DUAL module and integrate the two diodes.
That way you have all the operating cases.
And that makes a chaffage comamnde very practical and powerful. I asked JOSE to integrate this feature but so far no response.
He must be very busy!


![image](https://user-images.githubusercontent.com/7425260/51489609-1fb2c980-1da9-11e9-8242-46817eeba255.png)

**Comment by topzoe** [comment]
Do you have a HAA Json for SONOFF DUAL for drive pilot wire?
