### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by kivanc87** [RavenSystem/esp-homekit-devices#1540]
![image](https://user-images.githubusercontent.com/83796711/131310262-57f9d8fd-ac9e-40bc-8081-123070df89e2.jpeg)

**Comment by paulzhdanov** [comment]
I have the same message after thermostat update and reset...

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
