### ISSUE TITLE
ESP8266 LCtech relay x2 impossible to find correct JSON

### ISSUE THREAD

**Issue by todely** [RavenSystem/esp-homekit-devices#1552]
Hello,

I have something like this:
![image](https://user-images.githubusercontent.com/11060244/132375473-31de08ac-cfd5-4a26-88cd-d53ec69ec525.png)

I didn't succes to find the right JSON configuration (try all GPIO) but i think it's not possible for this x2 relay because it's serial command right ?

Thanks for your help

**Comment by tonysprenk** [comment]
Yes. It uses a secondary mcu. It is compatible but you have to know the commands.

**Comment by todely** [comment]
Hello
I don’t know how to find command, hope someone have same esp + relay and have found solution…

**Comment by novellaip** [comment]
![9EEB9248-A132-4537-9B4C-7E6A4B9C4978](https://user-images.githubusercontent.com/69299111/132530534-d66fdc23-6d52-4c0b-bc92-6f34af4dbcf6.jpeg)
![0DABFDAD-C00A-41DF-9BE4-4337BD316E0B](https://user-images.githubusercontent.com/69299111/132530558-f90e3e80-f140-4f14-a175-db47c907bd2e.jpeg)

Worth a try.

**Comment by todely** [comment]
that's exactly my module (LCtech) but how add hex command in json ?

**Comment by novellaip** [comment]
Can refer to UART Configuration and UART Action in Wiki section. Since the spec. did not list the baud rate, you may need to try all of them. Typically 9600 n 8 1.

**Comment by todely** [comment]
I have try this json:
{"c":{"l":13,"b":[{"g":0,"t":5}],"r":[{"n":0,"s":115200,"p":0,"b":0}]},"a":[{"t":1,"0":{"u":[{"n":0,"v":"a00101a2"}]},"1":{"u":[{"n":0,"v":"a00100a1"},]}}]}

but can't find my device with homekit ? does a wrong json avoid homekit to find device?

**Comment by todely** [comment]
can't find right json for second relay...

**Comment by novellaip** [comment]
{"c":{"l":13,"b":[{"g":0,"t":5}],"r":[{"n":0, "s":115200, "p":0, "b":0}]},"a": [{"t": 1,"0":{"u":[{"n":0,"v":"a00100a1"}]},"1":{"u":[{"n":0,"v":"a00101a2"}]}}, {"t": 1,"0":{"u":[{"n":0,"v":"a00200a2"}]},"1":{"u":[{"n":0,"v":"a00201a3"}]}}]}

You need to add one more accessory(Switch) in array “a”. Using JSON verification can help you understand.

**Comment by todely** [comment]
yep i have use JSON verificator and find my mistake

**Comment by ksn135** [comment]
JSON for garage doors:
`{
  "c":{"o":0,"l":13,"r":[{"n":0, "s":115200, "p":0, "b":0}]},
  "a":[{
    "t":40,
    "d":18,
    "0":{"u":[{"n":0,"v":"a00101a2","d":1000},{"n":0,"v":"a00100a1","d":1000}]},
    "1":{"a":0},
    "2":{"a":0},
    "3":{"a":0},
    "10":{"a":0},
    "12":{"a":0},
    "13":{"a":0}
  },{
    "t":40,
    "d":18,
    "0":{"u":[{"n":0,"v":"a00201a3","d":1000},{"n":0,"v":"a00200a2","d":1000}]},
    "1":{"a":0},
    "2":{"a":0},
    "3":{"a":0},
    "10":{"a":0},
    "12":{"a":0},
    "13":{"a":0}
  }]
}
`
