### ISSUE TITLE
After update to v7.2.1 - ESP is in setup mode only

### ISSUE THREAD

**Issue by andrewbpowers** [RavenSystem/esp-homekit-devices#1556]
Hello!

After I update a ESP-01s to HAA v7.2.1, nothing works anymore.
The ESP is now only in config mode. And no, nothing has been changed in the JSON config.
Only logging on to a WiFi network works. 

I have also flashed another ESP-01S. It does not accept the JSON config either and remains in config mode.

What is this problem again?

Best regards...

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
