### ISSUE TITLE
HAA Manager: Historical data is.. where?

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#1557]
Hi!
Got latest HAA.app update v2.0.0 and firmware v7.2.1.

Is the Historical data invoked by an **“i”** button at the top right corner, which does nothing? (tested this button on iPad mini 4 and iPhone 7 both latest iOS 14.7.1)

Some fresh screenshots or explanation in the AppStore are welcome.

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
