### ISSUE TITLE
SONOFF 5V Wifi Really Module.

### ISSUE THREAD

**Issue by rickdhoy** [RavenSystem/esp-homekit-devices#1558]
I am trying too use a Sonoff 5v WIFI Really Module to control our Front gate and Garage Door.

I have been trying to work out the JSON to make the switch contact/Toggle for 1 to 2 seconds and then release.

At the moment of course in Apple Homekit it simply shows as on and I have to then switch it again to turn it off and then again to activate it again :-) Hopefully the above make sense. :-0

I am currently using this JSON

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":4},{"g":4,"t":0}]}]}

I have tried adapting the following JSON a few times from the Garage door setup for the SONOFF SV but I keep breaking it :-)

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":40,"d":18,"f3":[{"g":14,"t":0}],"f4":[{"g":14}],"f2":[{"g":4,"t":0}],"f5":[{"g":4}],"0":{"r":[{"g":12,"v":1,"i":0.5}]},"1":{"a":0},"2":{"r":[{"g":12,"i":1.5},{"g":12,"v":1,"i":0.5},{"g":12,"v":1,"i":2}]},"3":{"a":2},"10":{"a":0}},{"i":1,"1":{"m":[[1,2]]}}]}

Any help would be appreciated :-)

Rick

**Comment by bencharlesrhys** [comment]
Hey have you tried using https://glumb.github.io/haa-configurator/

Your switch is currently set to use a Service Notification: "m":[[1,2]] which means it will turn on the 1st (1) accessory to the action (2). So will run this part of the code: "2":{"r":[{"g":12,"i":1.5},{"g":12,"v":1,"i":0.5},{"g":12,"v":1,"i":2}]}. Is that what you intended to do?

It's not 100% clear what you are trying to do. Could you try replacing "m":[[1,2]] with "m":[[1,0]]?

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
