### ISSUE TITLE
Enhancement request: Serial relay support

### ISSUE THREAD

**Issue by dezral** [RavenSystem/esp-homekit-devices#156]
I have a few of these devices that uses serial for switching relays (1x1 channel 1x 4 channel)

[link](https://www.banggood.com/ESP8266-5V-WiFi-Relay-Module-Internet-Of-Things-Smart-Home-Phone-APP-Remote-Control-Switch-p-1126605.html?rmmds=search)

they work great with tasmota and switching via SerialSend5 command and rule.
like "SerialSend5 A00101A2" for relay 1 ON.

im using the 4 channel for my heating system.

one more request: thermostat with external temperature support like via json/mqtt

**Comment by RavenSystem** [comment]
Use serial for switching relays will not be supported, sorry.

> one more request: thermostat with external temperature support like via json/mqtt

For security reasons, no.
