### ISSUE TITLE
Flash Sonoof HAA RavenCore

### ISSUE THREAD

**Issue by msmicka** [RavenSystem/esp-homekit-devices#1568]
Flash Sonoff MINI R2 

Today I discovered a strange problem. With FLASH Sonoff mini R2. Everything goes by default until I configure JSON and after restarting the Mini it does not respond even after 10 or more minutes. I also failed to run the latest version of fullhaaboot after the flash.

**Comment by asbesto01** [comment]
I am having the same issue.

Fortunately I have downloaded a very old HAA version (2.2.1) and I have been able to install it offline (non OTA method).

@RavenSystem help needed to understand what's happening, seems HAA servers are down?
