### ISSUE TITLE
HeaterCooler: Fixes sensor startup bug - still have problem

### ISSUE THREAD

**Issue by joddye2** [RavenSystem/esp-homekit-devices#1569]
**Detailed steps to reproduce it**
I've updated to the latest (7.4) version from an older 5.x version.
After the update the DHT22 sensor shows 0.0.
Before the update the same thing happened, and if the device reboots and get 0.0 the heater starts heating.

**JSON String**
{
  "c": {
    "o": 0
  },
  "a": [
    {
      "0": {
        "r": [
          {
            "g": 15,
            "v": 0
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 15,
            "v": 0
          }
        ]
      },
      "3": {
        "r": [
          {
            "g": 15,
            "v": 1
          }
        ]
      },
      "t": 25,
      "b": [],
      "g": 2,
      "n": 2,
      "j": 3,
      "w": 1,
      "m": 15,
      "x": 30,
      "d": 0.5,
      "s": 5
    }
  ]
}

**Used device**
Wemos D1 mini

**HAA version**
7.4.0

**iOS/iPadOS version**
15

**Logs**
A .txt file with logs. Read [how to capture logs from your device](https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#capture-logs)

**Screen-shots or videos showing issue**
![IMG_0605](https://user-images.githubusercontent.com/77693599/134217670-cc5538f6-6b35-4a82-a08d-dc51f1c12d06.PNG)

**Comment by Hanimaniac** [comment]
I had the same problem after reboot.
Disconnecting the sensor from the Wemos D1 and plugging it in again solved the problem.

**Comment by joddye2** [comment]
Yes that can be help or rebooting is enough sometimes. The problem is when it reboots for any reason and starts heating.
Yesterday I changed the GPIO (2->14)…now testing…

**Comment by Hanimaniac** [comment]
Maybe you have to configure the general section with a boot action like here:
https://github.com/RavenSystem/esp-homekit-devices/wiki/General-Configuration#Buttons-to-invoke-setup-mode
That you can say, after bboot, turn gpio 2 off.
