### ISSUE TITLE
after New IP address assigned from the router, device no response

### ISSUE THREAD

**Issue by OwenL1** [RavenSystem/esp-homekit-devices#1595]
My router time to time reassigns IP address to connected devices, every time it do that the HAA device will be no response, I need to restart the device to get it working again. 

Anyone know how to fix the issue?

**Comment by RavenSystem** [comment]
It is an issue of your router, IP address should be same. But I added a check and HAA will send a mDNS announce if IP address changes. In addition, a new device action can be exec if IP address changes, allowing to, for example, restart the device automatically.

https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_9.0.0
