### ISSUE TITLE
Could not enable suggested automation “When I Leave Home, Turn Off Thermostat”

### ISSUE THREAD

**Issue by tokamac** [RavenSystem/esp-homekit-devices#1609]
**Detailed steps to reproduce it**
I have two Sonoff TH16, each with its AM2301 temp+humidity sensor, connected to an electric heater and configured with HAA as "HeaterCooler with Humidity Sensor" with name "Thermostat" in two different rooms. All works fine including hourly programming, except I cannot activate the automation based on Location Services **“When I Leave Home, Turn Off Thermostat”** with an error displayed in Home.app — Everything is up-to-date from iOS to HAA. The title of this bug report is the error message displayed, that you can also see below in the attached screenshot. Location Services for HomeKit are enabled in Settings → Privacy → Location Services → HomeKit, as well as "Precise Location" in the sub-setting "Home".

**JSON String**
`{"c":{"l":13,"b":[{"g":0,"t":5}],"n":"thermostat"},"a":[{"0":{"r":[{"g":12}]},"1":{"a":0},"3":{"r":[{"g":12,"v":1}]},"5":{"a":0},"t":25,"w":1,"s":5,"g":14,"n":2,"z":0}]}`

**Used device**
iPhone X

**HAA version**
9.0.3 Griffon

**iOS/iPadOS version**
iOS 15.1

**Screen-shot showing issue**
![IMG_3467](https://user-images.githubusercontent.com/3685009/140313330-65d4ca3a-ee18-4e4b-8eb0-1305c497705a.PNG)

**Comment by tokamac** [comment]
Just updated through OTA all my compatible accessories to HAA 9.0.4, but issue is still the same.

However, this may be a HomeKit issue and not an HAA issue (?) because if I set up a similar automation manually, it seems to work as expected (see screenshot below). What does not work is Apple's preconfigured automation with the virtual green switch in Home.app

As a conclusion, this issue is a minor one as there is an easy (manual) workaround.

![IMG_3468](https://user-images.githubusercontent.com/3685009/140316948-8834a8d7-f3da-4e67-9493-fb91d1a5887e.PNG)

**Comment by Soldiiier** [comment]
I get a similar issue with an offical supported Hk thermostat device, when enabling suggested automations. I don't think this is attributed to HAA

**Comment by RavenSystem** [comment]
This issue is related to HomeKit, not HAA. Feel free to create a Discussion to get help. Thanks!
