### ISSUE TITLE
IR Not seen in HAA

### ISSUE THREAD

**Issue by sgsteyn** [RavenSystem/esp-homekit-devices#1613]
All of my HAA devices are visible and manageable in the HAA app except my IR hub which is completely missing but working flawlessly in the Home app.

I see there were some post back in 2019 that IR is not supported in HAA, has anything changed?

`{"c":{"n":"living-ir","t":14,"p":"J(J(AcAcAcDFAc"},"a":[{"t":60,"xa":0,"i":[{"n":"CCTV","0":{"i":[{"r":3,"c":"E2AsAkAmAkAkB*AlB*AlC0AbAkAkB*AlAlApB(AlAkAkB*ApB*AlAgAkAlAlAkw0E&AgAkApAgApB(ApB&AlB*AlAlApB(AlAkAlB-AgAlAlB:AlB(ApAgApAgAkAkv-E(AgAgAkAlApB&AlB-AlB*AlAgApB,AkAgApB(ApAhAoB*AlB*AlAgApAgApAg"}]}}],"0":{"i":[{"r":3,"w":"E3AqCBAcB:AmB*AlB*AkAgApB(ApAgApB*AlAgAoAhAoAgApAg7JE(AhB(ApB_AgB(ApB&ApAgApB*AkAhAoB,AkAgApAgApAgAoAg7VE!AjB,AkB(ApB,AkB,AkAhApB(ApAgApB*AlAgApAgApAgApAg"}]},"1":{"i":[{"r":3,"w":"E2AxAgAqB*AlB-AgB(AkAlApB,AlAgApB(AkAlApAgApAgApAh8rE@AmAgApB,AfB,ApB(AqAgAkB_AkAgApB*AkAgArAgAmAhApAg82E@AlAgApB,ApB&AkB,AlAgAoB,ApAbApB*AlAgApAgApAgAuAb"}]}},{"i":0.5,"1":{"s":[{"a":1}]}}]}`

Blitzwolf RC1
HAA version 2.0.0
IOS version 15.1

**Comment by tonysprenk** [comment]
It has an older version of haa which is not supported by the haa manager app. Update to the latest version and it will show up.

**Comment by sgsteyn** [comment]
Also thought so but update yesterday from 8.0.0 to 9.0.4 but didn't make a difference l
![EB2826B0-7174-4B79-B055-AD66C9EEFC1D](https://user-images.githubusercontent.com/30214608/140634359-6a1aaf82-a4a9-4f13-829d-73e7f104834f.jpeg)

**Comment by xrust83** [comment]
In fact, this is a TV service that should not be supported by a HAA manager.

![image](https://user-images.githubusercontent.com/58448955/140638626-20f423c5-629b-46d3-a7a1-dc6510d4fe82.jpeg)

**Comment by sgsteyn** [comment]
Thank you, remembered it about that now.
