### ISSUE TITLE
Esp8266 Nodemcu, relay, switch on/off

### ISSUE THREAD

**Issue by lukaszwitkowski** [RavenSystem/esp-homekit-devices#1620]
Hello ,
What is max relay and switch (on/off) not button we can connect to esp8266 i try 4 but i have only 3 working and i can't find another that working afrer reboot.
When i use some pins for on/off whitch after reboot my esp/haa dont work.image photo from other project![image](https://user-images.githubusercontent.com/36861888/140899841-9fcf6fb7-e991-4221-9d20-96b558b30cbf.png)

**Comment by RavenSystem** [comment]
Not an issue. Continue here: https://github.com/RavenSystem/esp-homekit-devices/discussions/1619
