### ISSUE TITLE
ESP8266EX problem.

### ISSUE THREAD

**Issue by nickforev** [RavenSystem/esp-homekit-devices#1630]
Hi. I found bug in release 9.1.0. Sonoff TH16 ver 2.1 after flash dont load. Chip ESP8266EX problem. I downgrade to release 8.0.0 and all works fine.
![image](https://user-images.githubusercontent.com/67782540/141982260-10cbdda3-fb00-41ea-80c7-8f8af7fdc16f.png)

![A26F7C0D-09C4-4CAD-8ADB-78EA8498C140](https://user-images.githubusercontent.com/67782540/141982482-c1a7a67d-06d2-4e3e-9a57-c8c770c054ae.jpeg)
![image](https://user-images.githubusercontent.com/67782540/141982592-3ff73200-f38a-4da3-8667-b78d5271ecc7.png)

**Comment by nickforev** [comment]
After update work normal. 
![Uploading A3CAC871-29E7-4838-BABD-F560E6CDD64F.png…]()

**Comment by VaBanck** [comment]
А в чём проблема? Я так и не понял

**Comment by nickforev** [comment]
> А в чём проблема? Я так и не понял
Проблема в том что на последней прошивке esp8266ex не запускается. Только если зашить 8.0.0, а потом обновить работает.
Проверено на нескольких ТН16, все одинаково.
Это отчет про случайно найденый баг.

**Comment by nickforev** [comment]
HAA 9.2.0 same problem!

**Comment by RavenSystem** [comment]
I have tested it, and works as expected. About 10 seconds after flash, HAA wifi hotspot is reachable.

**Comment by RavenSystem** [comment]
Could you try this, please? (Unzip it first)
[fullhaaboot.bin.zip](https://github.com/RavenSystem/esp-homekit-devices/files/7586979/fullhaaboot.bin.zip)

**Comment by RavenSystem** [comment]
Try this, please:

[fullhaaboot.bin.zip](https://github.com/RavenSystem/esp-homekit-devices/files/7587768/fullhaaboot.bin.zip)

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/1637
