### ISSUE TITLE
Sonoff SV after HAA flash not showing AP WIFI

### ISSUE THREAD

**Issue by Herwarth2019** [RavenSystem/esp-homekit-devices#1642]
Hello Mr. José Antonio Jiménez Campos,

firstly thank you for your great work on this DIY Homekit system - the HAA. I used your software till first RavenCore and was 100% satisfied after that I migrated to the HAA and was much happier because of JSON possibilities... Yesterday I came back to your software to update my Sonoff SV devices but with that I stucked in the 3. part of your installation guidline - when I flash the Sonoff SV (everything went well - see screenshot) the device wont show the Wifi AP so Iam not able to connect it. Iam able to repeat the 1.-3. step (everything actual) but still it stucks in "not showing wifi AP - cant see "HAA...". I tried other devices (Sonoff Basic, RF,..) but just the SV do this issue :-/... Iam getting out of my mind because tried around 80-100 flashes/per one device and sometimes it works like 20-30 flashes/1 working SV but mostly it gets stuck without the wifi AP... Do you know whats happening? note tried around 5 new Sonoff SV everything do the same...

Thanks for any advice,
Best regards
David

![Test1](https://user-images.githubusercontent.com/52852609/142942272-958780e6-fdd8-4683-8ed9-b6836fa1d073.PNG)

**Comment by Herwarth2019** [comment]
update: tried for the first time to install latest Tasmota - just changed the .bin file and flashed. Worked 100% and after reboot in around 2s shows wifi AP tasmota. Then I put the fullhaaboot and it did the same issue again :-/...So I checked that the device and connection work there must be something else...

**Comment by RavenSystem** [comment]
Could you try this, please? (Unzip it first)
[fullhaaboot.bin.zip](https://github.com/RavenSystem/esp-homekit-devices/files/7584872/fullhaaboot.bin.zip)

**Comment by RavenSystem** [comment]
Try this, please:

[fullhaaboot.bin.zip](https://github.com/RavenSystem/esp-homekit-devices/files/7587763/fullhaaboot.bin.zip)

**Comment by xrust83** [comment]
let me interfere.  When copying the json code, I developed a situation when, due to the keyboard layout and language, for example, the quotes did not match the encoding.  and if you look closely, you can see that they even look differently.  accordingly, such a code was not saved and haa the device was rebooted and re-entered the configuration mode.  To avoid this, enter json into the system, or, before inserting it into the device, first insert it into the address, into any window where styles and text encodings are killed.  It helped me once.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/1637

**Comment by Herwarth2019** [comment]
Thank you! It works! :-) Have a great day. DH
