### ISSUE TITLE
Sonoff Dual

### ISSUE THREAD

**Issue by cyclad** [RavenSystem/esp-homekit-devices#168]
the relays do not fire, sonoff dual board Ver 2.0, RavenCore v0.5.7

**Comment by RavenSystem** [comment]
First, update to version 0.5.8. Then, what board type config  are you using?

**Comment by cyclad** [comment]
I have already tried board type 1 and 2,  I will use it with another dual sonoff as it may be my board defective. Thanks for answering!

**Comment by RavenSystem** [comment]
I understand that you see both switches in Home App, but when you turn on them, relays don't work. Remember that device must be connected to 230VAC in order to relays work.

**Comment by cyclad** [comment]
Exactly is powered at 110VAC in Brazil , buttons 1 and 2 when triggered activates the relays, but the status in the home app does not change!
