### ISSUE TITLE
No Response 

### ISSUE THREAD

**Issue by yusufd1** [RavenSystem/esp-homekit-devices#169]
I now have 6 ravencore sonoffs around my house. After I added the last two I have noticed that certain devices that were working properly previously now randomly say no response. They tend to come right after a while but then will go back to no response. It’s not specific to any one device and can impact any of them. In one location I have two sonoffs literally on top of each other.  Could this close proximity be causing some interference?  I also have another 5 sonoffs that are in the home app but not on ravencore. They on tasmota with raspberry pi. Does anybody have any ideas what could be wrong. I have tried rebooting everything. Also reinstalled firmware etc. etc. but I still get the problem of no response. I need to resolve this as I am going to be fitting some ravencore sonoffs in my ceiling and won’t be able to access that location easily once installed. Will appreciate any feedback. Thanks in advance.

**Comment by peros550** [comment]
Do you have any Wifi extender on your wifi? 

You may want to try the wifi settings as proposed to this similar discussion and see if they work for you: 

https://github.com/RavenSystem/esp-homekit-devices/issues/130

**Comment by seritos** [comment]
Im experiencing the same issue increased in 0.5.7, had to unplug the devices/restart the router to get service again several times.

What does the extender has to do in all this? 
Thanx

**Comment by peros550** [comment]
> What does the extender has to do in all this?
> Thanx

It seems that one of the reasons causing this situation could be the wifi and on how it is configured. If you have an extender, I would propose (as a troubleshooting step) to turn it off for a while, restart the device and let us know if the issue disappears.

**Comment by claire078** [comment]
I have this problem after an update and my network hasn’t changed. 
Right now I have installed the 0.5.8, I will see there’s any changes.

**Comment by yusufd1** [comment]
I do have an ASUS dsl ac 68-u router and also range extender. Will try the settings. So far I can see my Bluetooth was not on Pre-emtive. Making the change now and will see how that goes. I see those settings are in Spanish so I tried to follow it on the English menu as best I could. But my router does not have all of it.

**Comment by RavenSystem** [comment]
Anyone was using device type 1 with gpio14 toggle enabled? Now this has changed, and there was a bug in 0.5.7 with that and devices using gpio14 toggle crashed. This is solved with 0.5.8. Please, read Wiki to configure gpio14 toggle, now called external toggle 1.

**Comment by seritos** [comment]
Not in my case. No toggles connected to GPIO14.
I just had to restartthe device now, because of no response. Updated to the 0.5.8 just after the lauch.
Has anything related with connectivity changed from 0.5.7 on?

**Comment by RavenSystem** [comment]
Do you erased flash and reinstalled 0.5.7?

**Comment by seritos** [comment]
Yes, I erased flash and install from zero as you suggested.
I also restarted the router. I will do it once again last it longer to ensure that it reboots properly

**Comment by seritos** [comment]
Meanwhile... would it be possible to know the signal strenght in the EVE menu?

**Comment by RavenSystem** [comment]
> FYI, while no response is happening, the device still answers to a ping request...

Try removing accessory from HomeKit using Home App when it is responding (not factory reset), restart your router, and add it again to HomeKit.

> Meanwhile... would it be possible to know the signal strenght in the EVE menu?

Great idea. I will investigate it.

**Comment by RavenSystem** [comment]
FYI I had this problem too, and I solved it rebooting my AppleTV and my iPhone. My iPad showed response, but my iPhone showed no response, and only when I rebooted my AppleTV, it worked again.

**Comment by claire078** [comment]
The 0.5.8 update seems solved the problem for me. 👍

**Comment by yusufd1** [comment]
I am at work at the moment so I could not do any further testing but rebooting did not really help. Also changing to the suggested wifi settings on my Asus router also has not really helped. Two devices are showing as no response and don't seem to want to come back online. I also realised that the only thing I did differently with these two devices is that I set them up in a different location using a different router with the same SSID and wifi password as my home Asus router. So when I came home and booted them up they auto connected to the home router and were working perfectly fine except for the intermittent "No Response" issue. Could this have caused some problem ie) setting them up initially on a different router. Anyway when I get home I will try and update to 0.5.8 disconnect from home app and also factory reset and connect to home Asus router from start.

**Comment by peros550** [comment]
> I did differently with these two devices is that I set them up in a different location using a different router with the same SSID and wifi password as my home Asus router. So when I came home and booted them up they auto connected to the home router and were working perfectly fine except for the intermittent "No Response" issue.

Yes, try 0.5.8 because someone also mentioned that the "no response" goes away after the update. 

Because the "no response" symptom seems to be caused by many factors I would like to give you my observations so far related to the wifi connectivity. 

It's a big coincidence what you mentioned above about using the same wifi name & pass in two locations. I also do the same in two houses and experienced similar situation. 

Especially, in my primary house I have an Asus router and a TP-Link Powerline which also has Wifi capabilities. I have setup both the Asus router and the TP-Link to use the same SSID so that my devices would not have to change SSID. In this way, if I'm having a video call and moving around the house the call never gets dropped. 

However, I had experienced many times the "no response" situation in devices working in version 0.5.4. Also, after a general AC power cut, the TP-LINK AP seemed to become available sooner than the Asus router. But the Asus router provides the IP address through DHCP, therefore the Sonoffs were trying to connect to the network through the TP-Link but could not get a valid IP (keep in mind that all sonoffs are closer to the router rather than the TP-Link). In my observations, the Sonoff never tried to connected to the Asus router SSID if their first attempt after reboot was to connect to the TP LINK device. I tried several reboots but it was a very random situation. 

I also tried to put MAC filtering on the TP-Link so that no Sonoff would not be allowed to get connected there. No help. 

I finally changed the SSID name to something different. Now all Sonoffs connect normally to the Asur router and the "no response" went away.

**Comment by seritos** [comment]
Your test are similar to the ones I have carried out. I have moved 3 Sonoff to a new location in a different house. 
They are working much better in the new location. I have made no changes in the firmware ( 0.5.8 ) in both of them. Router is an Apple time capsule and there are no wifi extensors. 
There are some sporadical no responses, but in the other location I had to reboot the entire system ( as RavenCore suggests) to make them work, as some "no response" where impossible to remove any other way. 

I would differenciate the no responses in two types: the self solve after some seconds (short, from 10s to 60s ) and the other (lets call them " stucked no response"), which you have to reset router/device to bring them back to life.  
I believe, as you said, that this is a multi-origin issue, but for sure, having a wifi extensor or medium-low wifi coverage can cause many problems, especially in the in the "stucked ones". Had only the short ones in the new location without extensors. 

Someone posted a while ago, that could be very interesting that the device try to go back to client mode after the AP mode. If you reboot the router and takes more than x time to reboot, or its unplugged for whatever reason, the Sonoff turns into AP mode and never tries to connect again unless you turn off/on again. Sometimes this could be a bit tricky if the Sonoff is integrated into the electrical wiring system of the house.

**Comment by peros550** [comment]
> Someone posted a while ago, that could be very interesting that the device try to go back to client mode after the AP mode.

:) it was me, speaking from my bad experience. I hope it's feasible!

**Comment by yusufd1** [comment]
Unfortunately I am still having issues even on 0.5.8. It seems to be a stuck no response now. I think you guys are correct in highlighting the range extender as a culprit. As the issue is with my 2 sonoffs that are deployed at my pool area which is probably being covered by the range extender more than the primary router. I have noticed that if I deploy one Sonoff in that area then the no response goes away. As soon as I add a second Sonoff there to control my light in addition to the pump then the no response returns and affects any ravencore Sonoff in the system. My other 6 sonoffs that are running on tasmota don't have any issues even those connected to the range extender. I need to do more testing and trial and error scenarios. For now I have disconnected the two sonoffs at the pool and all remaining ravencore sonoffs are stable with no "no response" impacting the system. I am going to try and run the two problematic sonoffs in the home near the primary router connected to nothing to see if "no response" returns. If it does not then I know the matter is isolated to the pool location and the wifi signal there, either low wifi or connecting to the range extender.

**Comment by peros550** [comment]
@yusufd1 good points! It's seems to be revealed a relationship between range extenders and the stucked "no response" . This was also my observation.  

Looking forward for your test results!

**Comment by RavenSystem** [comment]
Some useful info:
- IMO, devices don't lose wifi connectivity: If a device loses wifi connectivity, it will try to reconnect every second indefinitely to the same wifi.
- "No response" issue is related with mDNS responder and multicast transmissions.
- A "no response" device can force others to get "no response" status too because they use concatenated responses.
- A workaround is to configure a lower value of DTIM parameter in routers/wifi extenders (3 are recommended, but you can try with 2 and 1).
- Wifi range extenders are not companions with multicast traffic, especially cheaper range extenders.
- Tasmota works fine because doesn't use multicast.

**Comment by peros550** [comment]
@RavenSystem thank you for your valuable information. 

In my tests, when devices were in stuck no response status , all of them didn't respond to ping requests neither. (Todo: if I reproduce the problem again I'l check the Wifi connected devices at router's page)

I have little knowledge of mDNS protocol. If there was any mDNS client that would possibly monitor in real time any kind of information it would be very helpful? In this way, we could try to find the source of the issue. 

Who is responsible for the current mDNS implementation? Perhaps we could try to open an issue at their repo or search there for possible similar issues...

**Comment by dvelardi** [comment]
Someone have link to download EVE app on IOS?

DV

Il giorno 8 gen 2019, alle ore 15:11, peros550 <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@RavenSystem<https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fRavenSystem&umid=4f965ae2-d56c-4c4b-8060-0b3654dd92a3&auth=48278bb8638c59b19e6a5c9ee0648ca7e9c732c1-168852420c42ae44d970e413720e6d36702cfb91> thank you for your valuable information.

In my tests, when devices were in stuck no response status , all of them didn't respond to ping requests neither. (Todo: if I reproduce the problem again I'l check the Wifi connected devices at router's page)

I have little knowledge of mDNS protocol. If there was any mDNS client that would possibly monitor in real time any kind of information it would be very helpful? In this way, we could try to find the source of the issue.

Who is responsible for the current mDNS implementation? Perhaps we could try to open an issue at their repo or search there for possible similar issues...

**Comment by seritos** [comment]
Here it goes: 

https://itunes.apple.com/us/app/eve-for-homekit/id917695792

Is under the Wiki tab of the Ravencore site

**Comment by peros550** [comment]
By “PLC” you mean powerline extenders ? If yes, I would also confirm your findings. When I set all my Sonoffs/WemosD1 to use the router’s  AP and applied the Wi-Fi settings proposed by Jose the “no response” issue cleared. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seritos** [comment]
Correct @peros550 its a power line extender. 
In many cases, there are power line extender with WIFI integrated, and I understand that the router could not be as good as expected and cause some network issues, however, in my case the plc is just a wired extension without a router integrated. 
Both routers, origin and extensor are high quality ones. 

I wonder is there is anything we could do.

**Comment by claire078** [comment]
I have this problem sometimes again since last two updates. 😔 Interesting, I have another device with newer PCB, closer to WLAN router and it has no problem at all.
