### ISSUE TITLE
Garage door obstruction ignored

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#1692]
I use a dummy switch accessory to enable garage door obstruction state. This allows me to block the door for a while to perform some load/unload stuff..
`    {
      "0": {
        "m": [
          {
            "g": 1,
            "v": 3
          }
        ]
      },
      "1": {
        "m": [
          {
            "g": 1,
            "v": 4
          }
        ]
      },
      "t": 1,
      "b": [],
      "s": 0
    },`
https://github.com/RavenSystem/esp-homekit-devices/wiki/Garage-Door#Service-Notifications
    
Dummy switch did work fine until autumn may be.
Now even if obstruction state is detected (triggered by dummy above), I'm still able to open/close the door via HomeKit and other internal notifications trigger the movement too.

`"When an obstruction is detected, the door cannot be operated until the obstruction is removed."`
Please re-check if obstruction feature still works. 

P.S. Didn't set obstruction detection timer, as I got both open and closed reed sensors. Should I?

**Comment by RavenSystem** [comment]
It is a Wiki error, now fixed. If you want to disable garage door when obstruction is detected, you must use internal HAA notifications: https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#target-service-value

**Comment by i3laze** [comment]
A small question,

What If I want several notifications for an action?
`The service notification object is a list object and can contain multiple accessory notifications.`

What would the syntax be? Like that?
`{"0":{"m":[[1,3],[1,-10001]]},"1":{"m":[[1,-10000],[1,4]]}`
