### ISSUE TITLE
Auto OTA Updates started after setup even if it didn't been selected.

### ISSUE THREAD

**Issue by Ljzd-PRO** [RavenSystem/esp-homekit-devices#1694]
**Detailed steps to reproduce it**
I didn't select `Auto OTA Updates`, but when I save the configuration, according to the log, it still start searching updates on GitHub, and during updating I can't find ESP device in iOS Home App.
**JSON String**
```
{"c":{"l":0,"n":"DHT11_Temp_Hum"},"a":[{"t":24,"g":2,"n":1,"j":30,"z":-0.1,"h":-0.1}]}
```
**Used device**
ESP-01
**HAA version**
9.5.1b
**iOS/iPadOS version**
iOS15.2
**Logs**
A .txt file with logs. Read [how to capture logs from your device](https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#capture-logs)
```
HAA INSTALLER
Wifi clean
scandone
no none found, reconnect after 1s
reconnect
scandone
Saved BSSID: 3ccd57ad8dc9
Wifi Mode: Normal

* NORMAL

scandone
add 0
aid 2
cnt

connected with Redmi_AC2100, channel 1
dhcp client start...
ip:192.168.0.224,mask:255.255.255.0,gw:192.168.0.1


HAA Installer v5.8.2


REPO https://github.com/RavenSystem/haa/releases/latest/download:443
Installed HAA v0.0.0

INIT

*** STARTING


HAABOOT

>>> Get sign
*** DOWNLOADING
*** FORWARDING: github.com:443/RavenSystem/haa/releases/latest/download/otamain.bin.sec
*** CONNECT
DNS..OK
Socket..OK
Connect..OK
SSL..OK
FD..OK
SNI..OK
SSLConnect..OK
Write..OK
```

**Comment by RavenSystem** [comment]
It is running haaboot. Install system is mandatory.
