### ISSUE TITLE
Ota in Sonoff Raven_Core

### ISSUE THREAD

**Issue by sn0wst0rm** [RavenSystem/esp-homekit-devices#17]
@RavenSystem
Hello, I was reading your code to better understand the functionalities of the homekit lib. I'm really interested in including an ota upgrade method, I've already understood the ota update mechanism in open-rtos, but what I am not understanding is what you are doing in this example.
I've tried to flash it to figure out, for example, the meaning of the modified characteristics you have made. In home app, it isn't shown any of them, either figures any button to reboot the device.
So my question is: after implementing that ota function, needed to switch between ROMs, how do you actually upload and flash it?

Thank you in advance!

**Comment by kiralikbeyin** [comment]
I will try this https://github.com/SuperHouse/esp-open-rtos/tree/master/examples/http_client_ota

**Comment by RavenSystem** [comment]
OTA firmware update system used by Sonoff_RavenCore is this: https://github.com/HomeACcessoryKid/life-cycle-manager

**Comment by kiralikbeyin** [comment]
@RavenSystem please can you put some screenshots or video to wiki? 
https://github.com/HomeACcessoryKid/life-cycle-manager#how-to-use-it is not enough for a beginner like me.

**Comment by kiralikbeyin** [comment]
Need tutorial

**Comment by RavenSystem** [comment]
OTA is not ready yet. When it is ready, a tutorial will be published.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Sonoff-RavenCore

**Comment by kiralikbeyin** [comment]
I checked "ota_repo" word and only found in devices/Sonoff_RavenCore/main.c line 703
```status = sysparam_get_string("ota_repo", &char_value);```

Where do you "sysparam_set_string" ? 

Nothing about ota found in https://github.com/RavenSystem/esp-homekit-devices/blob/master/libs/legacy_config/content/index.html

**Comment by RavenSystem** [comment]
It's explain in the wiki:
> Sonoff RavenCore is an unified firmware for several Sonoff devices, with OTA updates and some user settings. It uses a OTA update system called Life-Cycle-Manager (LCM) from @HomeACessoryKid.

**Comment by kiralikbeyin** [comment]
Thanks this is very useful. 

Where is repo of otaboot.bin image how did you make it?

**Comment by RavenSystem** [comment]
All is explained in the wiki:
> Sonoff RavenCore is an unified firmware for several Sonoff devices, with OTA updates and some user settings. It uses a OTA update system called [Life-Cycle-Manager (LCM)](https://github.com/HomeACcessoryKid/life-cycle-manager) from @HomeACessoryKid.
https://github.com/HomeACcessoryKid/life-cycle-manager
And there you can read:
> Meanwhile, the development area is at https://github.com/HomeACcessoryKid/ota 
And there you can find https://github.com/HomeACcessoryKid/ota/releases

**Comment by i3laze** [comment]
A question:

If I flash main.bin, I will have no OTA (for doing f/w updates via Eve.app) like forever?

**Comment by RavenSystem** [comment]
@i3laze I don't know. That kind of questions is better that you ask in official OTA repo: 
https://github.com/HomeACcessoryKid/life-cycle-manager

**Comment by HomeACcessoryKid** [comment]
No, the ota concept depends on loading the ota-main program in the second partition.

if you start with ota-boot, that loads the ota-main in there and oat-main then loads the user-main in the primary partition
If you load the user-main directly into the primary partition, then no ota can happen

hope this is clear,
HacK
