### ISSUE TITLE
adv_button_create vs. adv_toggle_create

### ISSUE THREAD

**Issue by mgoeller** [RavenSystem/esp-homekit-devices#170]
Hi,

I saw that you use different code handling button presses (internal Sonoff buttons) vs. buttons / toggles / switches (whatever you want to name them) that are connected via the headers. Why is that? You could just use the adv_button_create function also for an switch that is attached via the headers, right? I see that you don't have to care for the timings when using a adv_create_toggle, but on the other hand we run into a problem when using a Shelly, correct?

Since the Shelly devices don't have internal buttons, we can only do a reset using a switch connected to the SW terminal. I would like to use the switch for both tasks. E.g. resetting in the first 120s when for example 10 times switched, and other than that just use as a normal switch (may it be a "real" switch or just a button).

What do you suggest?

**Comment by RavenSystem** [comment]
> I saw that you use different code handling button presses (internal Sonoff buttons) vs. buttons / toggles / switches (whatever you want to name them) that are connected via the headers. Why is that? You could just use the adv_button_create function also for an switch that is attached via the headers, right?

No, buttons use adv_button_create, and toggles use adv_toggle_create. Avd_toggle uses a filter to avoid interferences, necessary when header pins are used, but this filter requieres a little delay that doesn't allow the use of double press, for example. 

> I see that you don't have to care for the timings when using a adv_create_toggle, but on the other hand we run into a problem when using a Shelly, correct?

I don’t undertand what you say. 

> Since the Shelly devices don't have internal buttons, we can only do a reset using a switch connected to the SW terminal. I would like to use the switch for both tasks. E.g. resetting in the first 120s when for example 10 times switched, and other than that just use as a normal switch (may it be a "real" switch or just a button).

Actually you can do a factory reset switching 10 times quickly within 3 seconds in the first 120 seconds since device boots, but Wiki has not been updated yet.

**Comment by mgoeller** [comment]
You are totally correct, thank you for clarifying. I found your factory_default_toggle function now in the code :)
