### ISSUE TITLE
Please elaborate on a second example:

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#1749]
Please elaborate on a second example:
“I need to turn on GPIO1 now and GPIO2 three seconds later.”
How this is currently possible without a dummy inching switch or turning GPIO1 off?
Make two simultaneous actions  g:2, v:1 and g:2, v:0, i:3?

_Originally posted by @i3laze in https://github.com/RavenSystem/esp-homekit-devices/discussions/1748#discussioncomment-2211010_

**Comment by RavenSystem** [comment]
Please, use Discussions section and leave Issues section only for issues. Thanks!

https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
