### ISSUE TITLE
sonoff sv - does not enter the configuration mode

### ISSUE THREAD

**Issue by Aureliusz1** [RavenSystem/esp-homekit-devices#176]
If I want to enter the configuration mode again, press the button and hold 10 -30 s and nothing happens. The wi-fi network can not be reconfigured.

**Comment by GPL71** [comment]
Are you referring after OTA setup?

**Comment by RavenSystem** [comment]
@Aureliusz1 It must work. Try this:
- connect dev to ac power or USB power. 
- wait 30 seconds
- push and hold button for at least 15 seconds.
