### ISSUE TITLE
ESP8266（nodemcu）

### ISSUE THREAD

**Issue by dydingjiawei** [RavenSystem/esp-homekit-devices#177]
Can I flush RavenCore to ESP8266 (NODEMCU)?I can connect to the homekit,but I can't find the controlled GPIO port, I want to control the relay.

**Comment by dydingjiawei** [comment]
> If you set the device to "Device Type 10" then you have to connect the relay to GPIO2 which is labeled on the NodeMCU as D4. If you want a Button too, you have to connect it to GPIO0 -> D3.
> 
> For more information take a look at the Wiki under Device type 10

Emmmm, how to change the Device Type??😂😂

**Comment by yukonx** [comment]
LED_GPIO                        13
DOOR_OPENED_GPIO                4
DOOR_OBSTRUCTION_GPIO           5
DOOR_CLOSED_GPIO                14
TOGGLE_GPIO                     14
BUTTON1_GPIO                    0
BUTTON2_GPIO                    9
BUTTON3_GPIO                    10
BUTTON4_GPIO                    14
RELAY1_GPIO                     12
RELAY2_GPIO                     5
RELAY3_GPIO                     4
RELAY4_GPIO                     15



**change the Device Type**

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#user-settings

**Comment by dydingjiawei** [comment]
![image](https://user-images.githubusercontent.com/19380683/50951412-10e63000-14e8-11e9-83f9-6c917f03b614.png)
In afct, i can't control my realy, The Relay is benn connected to GPIO0 (D3)
![image](https://user-images.githubusercontent.com/19380683/50951482-4ee35400-14e8-11e9-998d-36126e59d68d.png)

**Comment by yukonx** [comment]
> ![圖片](https://user-images.githubusercontent.com/19380683/50951412-10e63000-14e8-11e9-83f9-6c917f03b614.png)
> 在afct，我無法控制我的真實，繼電器已連接到GPIO0（D3）
> ![圖片](https://user-images.githubusercontent.com/19380683/50951482-4ee35400-14e8-11e9-998d-36126e59d68d.png)


type1&10   RY use gpio2

**Comment by dydingjiawei** [comment]
![img_3902](https://user-images.githubusercontent.com/19380683/50951990-088ef480-14ea-11e9-8e09-dae270c4f110.JPG)
![img_3903](https://user-images.githubusercontent.com/19380683/50951993-09c02180-14ea-11e9-84fd-140fde48f540.JPG)
I have tried it and still not working.

**Comment by dydingjiawei** [comment]
![img_3905](https://user-images.githubusercontent.com/19380683/50952113-63c0e700-14ea-11e9-9aa4-d8f794d4c468.PNG)
When I press the FLASH button on the ESP8266, my phone will change.

**Comment by yukonx** [comment]
> ![img_3905](https://user-images.githubusercontent.com/19380683/50952113-63c0e700-14ea-11e9-9aa4-d8f794d4c468.PNG)
> When I press the FLASH button on the ESP8266, my phone will change.

我也是使用 ESP8266 去做的 你的GPIO 因為程式的限制要改成 gpio12 ,gpio0 是用來閃存或當作按鈕用的

**Comment by yukonx** [comment]
> > 我也是使用 ESP8266 去做的 你的GPIO 因為程式的限制要改成 gpio12 ,gpio0 是用來閃存或當作按鈕用的
> 
> 所以我要连接到GPIO12吗？还是不起作用，我是刷的main.bin,blank_config.bin,rboot.bin

程序是沒問題的 要用gpio12 才會動作  你用GND+gpio0 看看iphone上狀態會不會改變,會就是程序正常

**Comment by dydingjiawei** [comment]
> > > 我也是使用 ESP8266 去做的 你的GPIO 因為程式的限制要改成 gpio12 ,gpio0 是用來閃存或當作按鈕用的
> > 
> > 
> > 所以我要连接到GPIO12吗？还是不起作用，我是刷的main.bin,blank_config.bin,rboot.bin
> 
> 程序是沒問題的 要用gpio12 才會動作 你用GND+gpio0 看看iphone上狀態會不會改變,會就是程序正常

GND+GPIO0,看串口上的信息显示是板子直接重启服务了

**Comment by yukonx** [comment]
> > > > 我也是使用 ESP8266 去做的 你的GPIO 因為程式的限制要改成 gpio12 ,gpio0 是用來閃存或當作按鈕用的
> > > 
> > > 
> > > 所以我要连接到GPIO12吗？还是不起作用，我是刷的main.bin,blank_config.bin,rboot.bin
> > 
> > 
> > 程序是沒問題的 要用gpio12 才會動作 你用GND+gpio0 看看iphone上狀態會不會改變,會就是程序正常
> 
> GND+GPIO0,看串口上的信息显示是板子直接重启服务了
> 然后iPhone上homekit显示该配件无反应，我必须要重新刷一边固件才可以添加上去，这个现象正常吗？

不正常,,我是直接用ESP12E做的 操作上都正常

**Comment by dydingjiawei** [comment]
> > > > > 我也是使用 ESP8266 去做的 你的GPIO 因為程式的限制要改成 gpio12 ,gpio0 是用來閃存或當作按鈕用的
> > > > 
> > > > 
> > > > 所以我要连接到GPIO12吗？还是不起作用，我是刷的main.bin,blank_config.bin,rboot.bin
> > > 
> > > 
> > > 程序是沒問題的 要用gpio12 才會動作 你用GND+gpio0 看看iphone上狀態會不會改變,會就是程序正常
> > 
> > 
> > GND+GPIO0,看串口上的信息显示是板子直接重启服务了
> > 然后iPhone上homekit显示该配件无反应，我必须要重新刷一边固件才可以添加上去，这个现象正常吗？
> 
> 不正常,,我是直接用ESP12E做的 操作上都正常

我也不清楚我板子上的WIFI模组具体型号，没有标注。

**Comment by yukonx** [comment]
> > > GND+GPIO0,看串口上的信息显示是板子直接重启服务了
> > > 然后iPhone上homekit显示该配件无反应，我必须要重新刷一边固件才可以添加上去，这个现象正常吗？
> > 
> > 
> > 不正常,,我是直接用ESP12E做的 操作上都正常
> 
> 我也不清楚我板子上的WIFI模组具体型号，没有标注。

那個應該沒差    D3=GPIO0  D6=GPIO12 你有這樣接嗎?

**Comment by dydingjiawei** [comment]
> > > > GND+GPIO0,看串口上的信息显示是板子直接重启服务了
> > > > 然后iPhone上homekit显示该配件无反应，我必须要重新刷一边固件才可以添加上去，这个现象正常吗？
> > > 
> > > 
> > > 不正常,,我是直接用ESP12E做的 操作上都正常
> > 
> > 
> > 我也不清楚我板子上的WIFI模组具体型号，没有标注。
> 
> 那個應該沒差 D3=GPIO0 D6=GPIO12 你有這樣接嗎?

将两根阵脚直接连接起来?

**Comment by yukonx** [comment]
> > 那個應該沒差 D3=GPIO0 D6=GPIO12 你有這樣接嗎?
> 
> 将两根阵脚直接连接起来?我试试

不用我只是確定一下你有沒有接對,等我下班回家再照我的給你參考

**Comment by dydingjiawei** [comment]
> > > 那個應該沒差 D3=GPIO0 D6=GPIO12 你有這樣接嗎?
> > 
> > 
> > 将两根阵脚直接连接起来?我试试
> 
> 不用我只是確定一下你有沒有接對,等我下班回家再照我的給你參考

好的，那就麻烦大佬了

**Comment by yukonx** [comment]
> 好的，那就麻烦大佬了

我接這樣就可以用了，你用那個板子應該也是一樣就可以了


https://drive.google.com/open?id=1T945lJFUvOM2cngdB_uuS1zvU8Qll2n8
https://drive.google.com/open?id=1a-AqF2GiT4QJ3imrbnmUw42Sg9Kg7a9u
https://drive.google.com/open?id=1aSLMF20UxHmpVccRMO0UoVJqOglo6F6U

影片

https://youtu.be/Ly2AtoLystg

**Comment by dydingjiawei** [comment]
> > 好的，那就麻烦大佬了
> 
> 我接這樣就可以用了，你用那個板子應該也是一樣就可以了
> 
> https://drive.google.com/open?id=1T945lJFUvOM2cngdB_uuS1zvU8Qll2n8
> https://drive.google.com/open?id=1a-AqF2GiT4QJ3imrbnmUw42Sg9Kg7a9u
> https://drive.google.com/open?id=1aSLMF20UxHmpVccRMO0UoVJqOglo6F6U
> 
> 影片
> 
> https://youtu.be/Ly2AtoLystg

我才发现一个问题，我的继电器好像突然坏掉了，前天还好好的。
