### ISSUE TITLE
Makefile question

### ISSUE THREAD

**Issue by peros550** [RavenSystem/esp-homekit-devices#179]
I have seen the following options: 

```
HOMEKIT_SMALL = 0
HOMEKIT_OVERCLOCK = 0
HOMEKIT_OVERCLOCK_PAIR_SETUP = 0
HOMEKIT_OVERCLOCK_PAIR_VERIFY = 0
```

Anybody knows what these settings do? Is it safe to turn on the overclocking? :)

Many thanks in advance

**Comment by RavenSystem** [comment]
https://github.com/maximkulkin/esp-homekit/blob/c2e67c468890b376343bf867309b31390af0dad9/component.mk

But actually it needs some changes in Makefile to work.

**Comment by RavenSystem** [comment]
See new RavenCore Makefile.
