### ISSUE TITLE
Wrong Value after Update to v10.4.2

### ISSUE THREAD

**Issue by Gandalf8266** [RavenSystem/esp-homekit-devices#1793]
Hello,

after Update to 10.4.2, on ESP device shows wrong Values. 
I'm using a DHT22 Sensor connected to ESP-01 Board .
My config:
{"c":{"o":0},"a":[{"t":24,"b":[],"n":2,"g":2}]}
![IMG_4440](https://user-images.githubusercontent.com/38372908/158115021-9b0439e6-3d51-4e3d-b5a3-3ec67fc9a1af.jpeg)

**Comment by VaBanck** [comment]
Off and on the device

**Comment by Gandalf8266** [comment]
Still the same.

**Comment by Gandalf8266** [comment]
Now it works again, I didn't change anything...
