### ISSUE TITLE
Sonoff Thermostat mode

### ISSUE THREAD

**Issue by Codi878** [RavenSystem/esp-homekit-devices#180]
Hi Jose

I use sonoff TH modified for dry contact to control the gas boiler and from my observations after setting the set temperature quite often the boiler turns on and off. 

Is it possible to implement such a solution as for example in this project:

https://www.npmjs.com/package/homebridge-pi-thermostat

"minimumOnOffTime": 120000,
 "blowerTurnOffTime": 80000,
 "startDelay": 10000,
 "temperatureCheckInterval": 10000

A protection against too frequent switching on was used here and it would be nice if you could configure Sonoff TH in RavenCore firmware in the hidden Eve menu

**Comment by Codi878** [comment]
Hi Jose,

Could you add this upgrade to your road map? 

is there an option to add such a solution to thermostat?

**Comment by RavenSystem** [comment]
Don't worry. In the new firmware there will be Thermostat (2 relays), AC (1 relay) and Heater (1 relay) accessory types.

**Comment by Kristian8606** [comment]
In my example, I added a pause of 0.2 degrees
