### ISSUE TITLE
TH10 / TH16 Temperature error (Stuck at 85ºC)

### ISSUE THREAD

**Issue by Alexandre-Mainardi** [RavenSystem/esp-homekit-devices#1805]
### TH10 / TH16 stuck at 85ºC

Apparently the DS18B20 needs to be delayed 1 second before first temperature read to show the correct temp.

Anyone know how to fix it?

### I found this solution:

_It is reported when it the sensor hasn't had time to do its conversion. This can take as long as 750ms.No, it doesn't. It lies in understanding how the sensor works, i.e. reading the data sheet, or the various tutorials.CorrectI submit the only fix you need is this line

 delay(1000);  //added to give the onewire stuff time to initialize._

(Here is the  source https://forum.arduino.cc/t/why-does-this-fix-work-for-ds18b20-error-code-85/529580/10)

**Detailed steps to reproduce it**

TH10 or TH16 with DS18B20 temperature only sensor.

**JSON String**
{
  "c": { "l": 13 },
  "a": [{
    "t": 1,
    "0": { "r": [{ "g": 12, "v": 0  }] },
    "1": { "r": [{ "g": 12, "v": 1 }] },
    "b": [{ "g": 0 }],
    "s": 5
  }, {
    "t": 22,
    "g": 14,
    "n": 3,
    "j": 30
  }]
}

**Used device**
ITEAD Sonoff TH16

**HAA version**
10.4.4

**iOS/iPadOS version**
iOS15.3.1

**Screen-shots or videos showing issue**

![IMG_2C357B4BB456-1](https://user-images.githubusercontent.com/14119130/160430550-a19ee6e2-4d17-46a4-94ff-4dd80bb3de48.jpeg)
![IMG_104395980C47-1](https://user-images.githubusercontent.com/14119130/160430682-288c0b40-b80c-43e8-80ae-8b4235e85150.jpeg)

**Comment by xrust83** [comment]
the ds18b20 sensor is digital and it sends an 8 bit code.  When power is applied, the sensor sends the code 0101 0101 so it coincided that this code corresponds to a temperature of 85 degrees.  You may have connected the sensor in a two-wire circuit, perhaps the wire to the sensor is too thin, a bad missing contact, or other reasons that prevent the sensor from working in the mode.  if it is overloaded by power, it will send the code 0101 0101, the value of which you see.
