### ISSUE TITLE
Shelly 2.5 firmware flash

### ISSUE THREAD

**Issue by pyrotechnik** [RavenSystem/esp-homekit-devices#1809]
Hi,
I use the latest HAA firmware on the sonoff mini R2 without any problems. I have a problem with flash execution on shelly 2.5. I connect GPIO0 to GND during startup, but I still can't connect to the shelly. I use ESP 01 and MacOS. 
I get: A fatal error occurred: Failed to connect to ESP32: No serial data received.

**Comment by OwenL1** [comment]
I have the same problem on Shelly dimmer 2. Hope someone can help us here.

**Comment by Fudalii** [comment]
You have new version Shelly with **ESP32**!! HAA not work with this chip, And you're probably writing about shelly 2P. 
I don't know anything about changing the WiFi chip to 2.5. 
More and more devices are changing ESP82xx to ESP32. Author, it's time to think about compiling for this chip :)
