### ISSUE TITLE
All devices stop work

### ISSUE THREAD

**Issue by richardlimaa** [RavenSystem/esp-homekit-devices#1816]
**Detailed steps to reproduce it**
All my devices stop working with haa manager and home, even after update, anyone same problem?

**Comment by richardlimaa** [comment]
![796C980E-6681-4566-9726-A490F6BD86FE](https://user-images.githubusercontent.com/48089559/163085529-53601046-bece-4bd7-8698-464d18020494.png)
![CAB343F6-B1E6-48D2-A035-ED50F61D8493](https://user-images.githubusercontent.com/48089559/163085532-924986cb-f7f6-4092-b33f-80660257eb21.png)
![76312632-302B-4E17-A337-668E8C5516EB](https://user-images.githubusercontent.com/48089559/163085533-71b872a9-2a69-4c59-a76d-66b2e513ed1e.png)

**Comment by Ucoz3000** [comment]
some devices are not available after flashing HAA_10.4.6
back to firmware HAA_10.4.5 devices available

**Comment by richardlimaa** [comment]
There is a way to do it without remove from wall?

**Comment by Ucoz3000** [comment]
Firmware can also be downgraded by placing an older copy of the files on your web server.

**Comment by richardlimaa** [comment]
Happy Easter, and thanks for this, but can i use for example a raven webserver to downgrade once i dont have my own webserver?

**Comment by Ucoz3000** [comment]
Local server XAMPP

**Comment by richardlimaa** [comment]
![Uploading 48803DAD-E54A-4735-AA0A-DFBD0FD3C3B2.png…]()

**Comment by richardlimaa** [comment]
I tried many versions but i cant manager randon firmwares

**Comment by richardlimaa** [comment]
@
![Uploading C6A44770-8F45-4B1D-A5EF-6E998B948616.png…]()

**Comment by richardlimaa** [comment]
@`
![Uploading C5D58322-241D-43A3-B22B-6CEBDA9243A3.png…]()
`

**Comment by richardlimaa** [comment]
![C55A1CDD-6F24-4D60-81FB-44BBDF1531F0](https://user-images.githubusercontent.com/48089559/163894381-ff199299-67b9-4ba0-a448-fba594a523e9.png)

.

**Comment by HonzaJaros** [comment]
> **Detailed steps to reproduce it**
> All my devices stop working with haa manager and home, even after update, anyone same problem?

Same here as well, just waiting for new firmware and then I’ll flick switch twice, goes to setup (if broken booting up) and auto update….
Hopefully new version is gonna be soon

**Comment by richardlimaa** [comment]
Everything is ok after 10.5.1, without change nothing thanks 🙏🏼
