### ISSUE TITLE
Feature request: Auto close Garage Door

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#182]
**Basic mode** (without Obstruction sensor): 
My garage door controller has own physical autoclose timer knob set for 2 min and the door closes back on timer. Currently I have to undo 3 screws to tune this knob.
It's easy to implement such Auto Close Timer in software instead.

**Advanced mode** (with Obstruction sensor):
Often my door auto-closes before the car arrives/leaves (neighbors chat or other setbacks). Further increasing auto-close value is a simple solution, but not as elegant as close on motion. How about to   highjack an Obstruction sensor for an “Auto close” feature?

When the door is Open, I'd love it to remain fully opened until something passes the Obstruction sensor (and then close after CloseOnMotion Timer, like 20 sec).
An opened door should eventually close after Auto Close Timer, like 5-30 min.

**Comment by Partizan7676** [comment]
If you don’t use obstruction sensor. How control that?

**Comment by i3laze** [comment]
Of course, most physical door controllers have the obstruction sensors.

If no obstruction sensor is attached to RavenCore, then just Basic mode (trigger auto close after 2 min).

**Comment by Partizan7676** [comment]
its safety certificate - auto close feature only work with sensor.

**Comment by i3laze** [comment]
True, and physical controller has it.
Why don’t replicate it in software?

**Comment by RavenSystem** [comment]
This firmware is not focused on replacing your garage door driver. It's an extension to add HomeKit capability to your current garage door driver. If you want auto close your garage door, replace your driver, because this firmware can not guarantee a good working as stand alone driver.

**Comment by i3laze** [comment]
The driver has obstruction sensors and manages the security just fine.

I already wired an open sensor from the driver to Sonoff. I just wanted extra features based on obstruction sensor.
