### ISSUE TITLE
1 device - 3 buttons 

### ISSUE THREAD

**Issue by MarcosFFurtado** [RavenSystem/esp-homekit-devices#1820]
I have this device Json String but when I ad it to homekit, they apear as 3 devices. Is it possible to have one device with 3 buttons under it?

{"c":{"b":[{"g":0,"t":5}],"o":0,"i":0,"l":1},"a":[{"0":{"r":[{"g":14,"v":0}]},"1":{"r":[{"g":14,"v":1}]},"b":[{"g":4}],"s":0},{"0":{"r":[{"g":12,"v":0}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":5}],"s":0},{"0":{"r":[{"g":13,"v":0}]},"1":{"r":[{"g":13,"v":1}]},"b":[{"g":3}],"s":0}]}

**Comment by pawelosin** [comment]
Try to use Extra Services https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#extra-services.
{"c": {"b": [{"g": 0,"t": 5}],"o": 0,"i": 0,"l": 1},
"a": [{"0": {"r": [{"g": 14,"v": 0}]},"1": {"r": [{"g": 14,"v": 1}]},"b": [{"g": 4}],"s": 0,
"es":[{"0": {"r": [{"g": 12,"v": 0}]},"1": {"r": [{"g": 12,"v": 1}]},"b": [{"g": 5}],"s": 0},
          {"0": {"r": [{"g": 13,"v": 0}]},"1": {"r": [{"g": 13,"v": 1}]},"b": [{"g": 3}],"s": 0 }]}]}

**Comment by MarcosFFurtado** [comment]
Thx a lot !!!! Worked Perfectly!
