### ISSUE TITLE
https://templates.blakadder.com/lenovo_ZG38C02793.html

### ISSUE THREAD

**Issue by mccding** [RavenSystem/esp-homekit-devices#1823]
Lenovo SE-341A Plug (ZG38C02793) json！how do it

**Comment by xrust83** [comment]
https://www.youtube.com/watch?v=2aregv5_mpU

**Comment by steini72** [comment]
Should work ?
{"c":{"l":12,"b":[{"g":4,"t":5}]},"a":[{"t":2,"0":{"r":[{"g":5},{"g":14,"v":1}]},"1":{"r":[{"g":5,"v":1},{"g":14}]},"b":[{"g":4}]}]}
