### ISSUE TITLE
json update to the new version SP111

### ISSUE THREAD

**Issue by mickelk** [RavenSystem/esp-homekit-devices#1832]
hi, I have gosund sp111 with HAA version 5.0.14 with such json

{"c":{"b":[{"g":13,"t":5}],"l":2},"a":[{"0":{"r":[{"g":15},{"g":0,"v":1}]},"1":{"r":[{"g":15,"v":1},{"g":0}]},"t":2,"s":5,"d":0,"b":[{"g":13}],"s":0},{"t":75,"xa":0,"j":10,"y0":[{"0":{"m":[{"g":1}]},"v":245}],"y1":[{"0":{"m":[{"g":1}]},"v":13}],"y2":[{"0":{"m":[{"g":2,"v":0}]},"v":0},{"0":{"m":[{"g":2,"v":1}]},"v":3}],"c0":5,"c1":4,"sl":12,"vf":0.1299,"cf":0.01249,"pf":1.3839}]}

after updating to the latest version, the switch does not work, because the configuration has changed, is anyone able to correct the code to the new version?

it is a switch that has a presence sensor that opens when the voltage is above 3W

**Comment by xrust83** [comment]
My config for Teckin SP22 

{"c":{"l":2,"n":"Smart Plug","b":[{"g":13,"t":5}]},"a":[{"0":{"r":[{"g":15},{"g":0,"v":1}]},"1":{"r":[{"g":15,"v":1},{"g":0}]},"t":2,"b":[{"g":13}],"es":[{"t":75,"j":10,"dt":[5,14,12],"vf":0.1536,"cf":0.0106,"pf":1.5957,"y0":[{"0":{"m":[[1]]},"v":245}],"y1":[{"0":{"m":[[1]]},"v":15}],"y2":[{"0":{"m":[[1]]},"v":2200}]}]}]}
