### ISSUE TITLE
The possibility of choosing the watering time has disappeared. The timer doesn't work.

### ISSUE THREAD

**Issue by sergoo-lbt** [RavenSystem/esp-homekit-devices#1847]
The ability to scroll through the menu and select the watering time has disappeared. The buttons are not active.

**JSON String**

{
  "c": { "l": 13, "b": [{ "g": 0, "t": 5 }] },
  "a": [{
    "t": 20,
    "0": { "r": [{ "g": 12, "v": 0 }] },
    "1": { "r": [{ "g": 12, "v": 1 }] },
    "b": [{ "g": 0, "t": 1 }],
    "s": 0,
    "w": 1,
    "d": 25
  }, {"i":0.5,"1":{"s":[{"a":1}]}}
]
}

**Used device** iphone 13

**HAA version** 10.7.4

**iOS/iPadOS version** 16 public beta 

**Screen-shots or videos showing issue**
![1250332A-8499-4822-9E42-B51D9758FEFE](https://user-images.githubusercontent.com/64399012/178783126-e7bc3114-72de-4f75-85d0-71f936d2e3e4.png)

**Comment by VaBanck** [comment]
https://discord.gg/v8hyxj2 заходи сюда
