### ISSUE TITLE
Fujitsu AC JSON and device

### ISSUE THREAD

**Issue by borissov** [RavenSystem/esp-homekit-devices#1848]
Hello, I'm looking for JSON config and device for Fujitsu AC control, the remote control is AR-RCE1E?

**Comment by Kristian8606** [comment]
You might want to try this one
 https://github.com/maximkulkin/esp-ir-thermostat

**Comment by borissov** [comment]
I write simple script with this libraries:

https://github.com/crankyoldgit/IRremoteESP8266/blob/master/examples/TurnOnFujitsuAC/TurnOnFujitsuAC.ino
https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266
