### ISSUE TITLE
Network Request, #HAA@000X parameters issue

### ISSUE THREAD

**Issue by paulzhdanov** [RavenSystem/esp-homekit-devices#1865]
I used almost same example as documented with NodeMCU and DHT22 on HAA 10.8.3:

```
{
  "c":{"b":[{"g":0,"t":5}], "o":3},
  "a": [{
    "t":24,
    "g":5,
    "j":3,
    "y0": [{
      "v": 0,
      "r": 1,
      "0": { "h": [{ "h": "192.168.1.101", "m":2, "u": "write3.php", "c": "temperature=#HAA@0000" }] }
    }]
  }]
}

```

But in case of POST ("m":2) there are no vars passed to host, GET - I simple get same string as in script: temperature=#HAA@0000", vars are not parsed to substitute values

GET Nginx log (with "u": "write3.php?temp=#HAA@0000"):
`192.168.1.195 - - [20/Aug/2022:18:57:40 +0300] "GET /write3.php?temp=#HAA@0000 HTTP/1.1" 200 5 "-" "HAA/10.8.3 esp8266"`

POST Nginx log ("m":2, "u": "write3.php", "c": "temperature=#HAA@0000"):
`192.168.1.195 - - [20/Aug/2022:19:35:57 +0300] "POST /write3.php HTTP/1.1" 200 418 "-" "HAA/10.8.3 esp8266"`

POST Haa log:
`
Advanced ESP Logger (c) 2022 José A. Jiménez Campos

Jan 01 00:00:43 192.168.1.195-121A66 [5] Upd Ch
Jan 01 00:00:43 192.168.1.195-121A66 NTP 192.168.1.1 (-1)
Jan 01 00:00:45 192.168.1.195-121A66 <1> TEMP 24.7C
Jan 01 00:00:48 192.168.1.195-121A66 [5] Closing
Jan 01 00:00:48 192.168.1.195-121A66 [5] Closed (0/20)
Jan 01 00:00:48 192.168.1.195-121A66 <1> TH sensor
Jan 01 00:00:49 192.168.1.195-121A66 >>> mDNS probing 2
Jan 01 00:00:51 192.168.1.195-121A66 <1> TH sensor
Jan 01 00:00:51 192.168.1.195-121A66 <1> TEMP 24.7C
Jan 01 00:00:51 192.168.1.195-121A66 <1> HUM 65
Jan 01 00:00:53 192.168.1.195-121A66 [5] New 192.168.1.201:60360 (1/20) Free HEAP 34580
Jan 01 00:00:53 192.168.1.195-121A66 [5] Verify 1/2
Jan 01 00:00:53 192.168.1.195-121A66 NTP 192.168.1.1 (-1)
Jan 01 00:00:53 192.168.1.195-121A66 [5] Pair found
Jan 01 00:00:53 192.168.1.195-121A66 [5] Verify OK
Jan 01 00:00:53 192.168.1.195-121A66 [3] New 192.168.1.204:43210 (2/20) Free HEAP 32676
Jan 01 00:00:53 192.168.1.195-121A66 [3] Verify 1/2
Jan 01 00:00:54 192.168.1.195-121A66 [5] Get Acc
Jan 01 00:00:54 192.168.1.195-121A66 [3] Verify 2/2
Jan 01 00:00:54 192.168.1.195-121A66 [3] Pair found
Jan 01 00:00:54 192.168.1.195-121A66 [3] Verify OK
Jan 01 00:00:54 192.168.1.195-121A66 [5] Get Ch
Jan 01 00:00:54 192.168.1.195-121A66 [3] Get Acc
Jan 01 00:00:54 192.168.1.195-121A66 [5] Get Ch
Jan 01 00:00:54 192.168.1.195-121A66 <1> TH sensor
Jan 01 00:00:54 192.168.1.195-121A66 <1> TEMP 24.7C
Jan 01 00:00:54 192.168.1.195-121A66 <1> HUM 65
Jan 01 00:00:56 192.168.1.195-121A66 >>> mDNS working TTL 4500 each 2223s
Jan 01 00:00:57 192.168.1.195-121A66 <1> TH sensor
Jan 01 00:00:57 192.168.1.195-121A66 <1> TEMP 24.6C
Jan 01 00:00:57 192.168.1.195-121A66 <1> Wilcard 0 0.00
Jan 01 00:00:57 192.168.1.195-121A66 <1> Exec Act 51
Jan 01 00:00:57 192.168.1.195-121A66 [5] Send Ev
Jan 01 00:00:57 192.168.1.195-121A66 Wildcard val: 24.6
Jan 01 00:01:00 192.168.1.195-121A66 <1> Payload:
Jan 01 00:01:00 192.168.1.195-121A66 POST /write3.php HTTP/1.1
Jan 01 00:01:00 192.168.1.195-121A66 Host: 192.168.1.101
Jan 01 00:01:00 192.168.1.195-121A66 <1> TH sensor
Jan 01 00:01:00 192.168.1.195-121A66 <1> TEMP 24.6C
Jan 01 00:01:00 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:24 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:24 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:27:24 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:27 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:27 192.168.1.195-121A66 <1> TEMP 24.7C
Aug 20 16:27:27 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:27:27 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:27:27 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:29 192.168.1.195-121A66 <1> Payload:
Aug 20 16:27:29 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:27:29 192.168.1.195-121A66 User-Agent: HAA/10.8.3 esp8266
Aug 20 16:27:29 192.168.1.195-121A66 Connection: close
Aug 20 16:27:30 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:30 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:27:30 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:27:30 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:27:30 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:27:30 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:30 192.168.1.195-121A66 <1> Net Action 192.168.1.101:80
Aug 20 16:27:32 192.168.1.195-121A66 <1> Payload:
Aug 20 16:27:32 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:27:32 192.168.1.195-121A66 User-Agent: HAA/10.8.3 esp8266
Aug 20 16:27:33 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:27:33 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:27:33 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:27:35 192.168.1.195-121A66 <1> Payload:
Aug 20 16:27:35 192.168.1.195-121A66 POST /write3.php HTTP/1.1
Aug 20 16:27:35 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:27:35 192.168.1.195-121A66 User-Agent: HAA/10.8.3 esp8266
Aug 20 16:27:36 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:36 192.168.1.195-121A66 <1> TEMP 24.7C
Aug 20 16:27:36 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:39 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:39 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:27:39 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:27:39 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:27:39 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:27:39 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:39 192.168.1.195-121A66 <1> Net Action 192.168.1.101:80
Aug 20 16:27:41 192.168.1.195-121A66 <1> Payload:
Aug 20 16:27:41 192.168.1.195-121A66 POST /write3.php HTTP/1.1
Aug 20 16:27:41 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:27:41 192.168.1.195-121A66 User-Agent: HAA/10.8.3 esp8266
Aug 20 16:27:42 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:42 192.168.1.195-121A66 ! <1> Read
Aug 20 16:27:45 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:45 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:27:45 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:48 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:48 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:27:48 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:51 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:51 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:54 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:54 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:27:54 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:57 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:27:57 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:27:57 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:27:58 192.168.1.195-121A66 [5] Get Ch
Aug 20 16:27:58 192.168.1.195-121A66 [5] for 1.6
Aug 20 16:28:00 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:00 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:00 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:03 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:03 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:03 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:06 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:06 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:06 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:09 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:09 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:12 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:12 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:12 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:15 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:15 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:18 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:21 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:21 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:21 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:24 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:24 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:27 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:27 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:30 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:30 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:30 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:33 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:33 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:33 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:36 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:36 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:36 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:39 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:39 192.168.1.195-121A66 <1> TEMP 24.6C
Aug 20 16:28:39 192.168.1.195-121A66 <1> HUM 65
Aug 20 16:28:42 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:42 192.168.1.195-121A66 <1> TEMP 28.7C
Aug 20 16:28:42 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:28:42 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:28:42 192.168.1.195-121A66 <1> HUM 99
Aug 20 16:28:42 192.168.1.195-121A66 <1> Net Action 192.168.1.101:80
Aug 20 16:28:42 192.168.1.195-121A66 Wildcard val: 28.7
Aug 20 16:28:42 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:28:44 192.168.1.195-121A66 <1> Payload:
Aug 20 16:28:44 192.168.1.195-121A66 POST /write3.php HTTP/1.1
Aug 20 16:28:44 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:28:45 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:45 192.168.1.195-121A66 <1> TEMP 27.6C
Aug 20 16:28:45 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:28:45 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:28:45 192.168.1.195-121A66 <1> HUM 99
Aug 20 16:28:45 192.168.1.195-121A66 <1> Net Action 192.168.1.101:80
Aug 20 16:28:45 192.168.1.195-121A66 Wildcard val: 27.6
Aug 20 16:28:45 192.168.1.195-121A66 <1> Payload:
Aug 20 16:28:45 192.168.1.195-121A66 POST /write3.php HTTP/1.1
Aug 20 16:28:45 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:28:45 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:28:48 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:48 192.168.1.195-121A66 <1> TEMP 26.9C
Aug 20 16:28:48 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:28:48 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:28:48 192.168.1.195-121A66 <1> HUM 99
Aug 20 16:28:48 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:28:50 192.168.1.195-121A66 <1> Payload:
Aug 20 16:28:50 192.168.1.195-121A66 POST /write3.php HTTP/1.1
Aug 20 16:28:50 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:28:50 192.168.1.195-121A66 User-Agent: HAA/10.8.3 esp8266
Aug 20 16:28:51 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:51 192.168.1.195-121A66 <1> TEMP 26.4C
Aug 20 16:28:51 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:28:51 192.168.1.195-121A66 <1> HUM 99
Aug 20 16:28:51 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:28:53 192.168.1.195-121A66 <1> Payload:
Aug 20 16:28:53 192.168.1.195-121A66 Host: 192.168.1.101
Aug 20 16:28:53 192.168.1.195-121A66 User-Agent: HAA/10.8.3 esp8266
Aug 20 16:28:53 192.168.1.195-121A66 Connection: close
Aug 20 16:28:54 192.168.1.195-121A66 <1> TH sensor
Aug 20 16:28:54 192.168.1.195-121A66 <1> TEMP 26.1C
Aug 20 16:28:54 192.168.1.195-121A66 <1> Wilcard 0 0.00
Aug 20 16:28:54 192.168.1.195-121A66 <1> Exec Act 51
Aug 20 16:28:54 192.168.1.195-121A66 <1> HUM 99
Aug 20 16:28:54 192.168.1.195-121A66 [5] Send Ev
Aug 20 16:28:54 192.168.1.195-121A66 <1> Net Action 192.168.1.101:80
Aug 20 16:28:54 192.168.1`

**Comment by RavenSystem** [comment]
GET method has not content. Then, [Content String Enrichment](https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#content-string-enrichment) can not be used.

I have tested POST, and it is working fine. Check if your server needs specific headers.
