### ISSUE TITLE
HAA Security System controlling real Alarm System with Sonoff SV

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#1870]
Hi,
I used to use an SV with my Alarm System to control it:
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12,"v":1,"i":1}]},"1":{"r":[{"g":12,"v":1,"i":1}]},"t":4,"b":[],"s":5},{"t":4,"b":[],"s":5,"f0":[{"g":4,"t":1}],"f1":[{"g":4,"t":0}]},{"t":12,"s":0,"f0":[{"g":14,"t":1}],"f1":[{"g":14,"t":0}]}]}

This SV was on old HAA boot, so I did an update to newest firmware.
HAA already has Security System, so I would like to use it.

I write it how would it work:
- relay switches between OFF/Away, armed/disarmed to my Alarm System,
- G4 input triggers armed (it not 100% necessary),
- G14 input triggers alarm

Could someone create me the correct json code?
Thanks!

**Comment by WojtekWro** [comment]
Hi @claire078 
It seems that what you need is easy to create when you someone has the same alarm. Real alarm systems can differ in terms of arming / disarming and triggering. 
In Wiki of this repo you can find really good instructions how to create your script. 

I can share with you my config. It is quite complex and there are couple of services. I hope this inspires you. 

{"c":{ "ntp":"pl.pool.ntp.org", "tz":"CET-1CEST,M3.5.0,M10.5.0", "ic":[[ 5,4,100]],"mc":[[0,39,255,256]],"z":0,"b":[{"g":114,"t":5}]},
"a":[
{   "A1": "Sofa Lamp",
    "1":{"r":[{"g":105}]}, "0":{"r":[{"g":105,"v":1}]}, "b":[{"g":111,"t":0},{"g":111}],
    "es":[
    {   "A2": "Table Lamp",
        "1":{"r":[{"g":104}]}, "0":{"r":[{"g":104,"v":1}]}, "b":[{"g":110,"t":0},{"g":110}]},
    {   "A3": "Speakers",
        "t":2, "1":{"r":[{"g":101}]}, "0":{"r":[{"g":101,"v":1}]}}]
},
{   "A4": "Kitchen Spots",
    "1":{"r":[{"g":102}]}, "0":{"r":[{"g":102,"v":1}]}, "b":[{"g":108,"t":0},{"g":108}],
    "es":[
    {   "A5": "Kitech Lamp",
        "1":{"r":[{"g":103}]}, "0":{"r":[{"g":103,"v":1}]}, "b":[{"g":109,"t":0},{"g":109}]}]
},
{   "A6": "Cabinets lED",
    "t":30, "st":1024, "g":[12], "0":{"m":[[7001]]},
    "es":[
    {   "A7": "FS A6",
        "t":1, "h":2, "0":{"m":[[-1]]}, "1":{"m":[[-1,1],[-1,102]]},  "b":[{"g":114}]
    },
    {   "A8": "MS",
        "t":12,"i":10, "f1":[{"g":115,"p":1,"t":1}], "1":{"m":[[7001,1],[7001,-1]]}
    },
    {   "A9": "FS for A10",
        "t":1, "h":2, "i":300, "1":{"m":[[7001,1]]}, "0":{"m":[[7001]]}
    },
    {   "A10": "OS",
        "t":6
    },
    {   "A11": "FS OFF ALL",
        "t":1, "h":2, "i":2, "b":[{"g":114,"t":3}], "1":{"m":[[1],[2],[4],[5]]}
    }
]
},
{   "A12": "Security",
    "t": 55, "s":5, "n":[0,1,3],
    "1": { "r": [{"g":100}], "m": [[7001,1]] },
    "0": { "r": [{"g":100, "v":1}], "m": [[7001,-10001],[7001],[7002,-10001]] },
    "3": { "r": [{"g":100, "v":1}], "m": [[7001],[7001,-10000],[7002,-10000]] }

},
{   "A13": "FS to ON/OFF",
    "0": {"m":[[-1,0]], "h": [{ "h": "192.168.8.31", "p":1880, "u":"HAA2?Alarm=0"}]},
    "1": {"m":[[-1,1]], "h": [{ "h": "192.168.8.31", "p":1880, "u":"HAA2?Alarm=1"}]},
    "es":[
    {   "A14": "Trigger AWAY",
        "i":1, "1": {"m":[[-2,4]]}
    }]
}]
}
