### ISSUE TITLE
Sonoff T1 2CH 0.5.11 switch no1 does'nt work

### ISSUE THREAD

**Issue by pawelosin** [RavenSystem/esp-homekit-devices#188]
Hi to all!
I have problem with Sonoff T1 2CH. When I set SWITCH 2CH in setup, in home app works perfectly, but when i press the sonoff switch, then works only button no 2. It seems that's configuration is for Sonoff dual. Before I configured external toggle to 1 any button does'nt work.
What's correct configuration for Sonoff T1 2 CH?

**Comment by RavenSystem** [comment]
Never mind. I found the bug.

**Comment by RavenSystem** [comment]
Update to version 0.5.12 and test.

**Comment by pawelosin** [comment]
Now the Sonoff works fine, thanks.
