### ISSUE TITLE
No Blue or Green output from R-G-B-CW-WW bulb

### ISSUE THREAD

**Issue by danielhelmstedt** [RavenSystem/esp-homekit-devices#1885]
**Detailed steps to reproduce it**
After update, I am no longer able to get any blue or green out of a 5 channel bulb - Red and both whites work as expected.
Swapping Red/Green GPIO values results in Red LED working when green colour selected, no output when red is selected
Has there been any change in FW that would affect the function of GPIO 12 and 14?

**MEPLHAA Script**
{"c": {},"a": [{"t": 30, "s": 1, "g": [4,12,14,5,13]}]}

**Used device**
[Arlec GLD122HA ](https://templates.blakadder.com/arlec_GLD122HA.html)

**HAA version**
11.3

**iOS/iPadOS version**
16.0

**Comment by RavenSystem** [comment]
Nothing has changed. My color lightbulbs, that uses GPIO 12 and 14, work fine. Try declaring only one GPIO, and test GPIO 12 and 14.
