### ISSUE TITLE
the light flickers above version 11.0.0

### ISSUE THREAD

**Issue by belkone** [RavenSystem/esp-homekit-devices#1889]
Hi,
I have a problem with dimming/brightening and switching on/off - The light is flickering.
I am using an LED driver with the following MEPLHAA Script:
`{"c":{"q":600,"b":[{"g":0,"t":5}]},"a":[{"t":30,"g":[5,13],"b":[{"g":0}]}]}`

Up to version 11.0.0 it worked fine. Then the problems started. I tested the following HAA versions:
11.3.1 - works wrong(flickering)
11.2.0 - works wrong(flickering)
11.1.2 - works wrong(flickering)
11.1.1 - not available for installation
11.1.0 - not available for installation
11.0.0 - works fine

**Comment by belkone** [comment]
thanks for the information :) I'm waiting for the new version and then I let you know if the problem is resolved :)

**Comment by RavenSystem** [comment]
Fixed in https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_11.3.2

**Comment by belkone** [comment]
I confirm, everything works fine again, thanks! :)
