### ISSUE TITLE
web,wifi,json

### ISSUE THREAD

**Issue by ceg117** [RavenSystem/esp-homekit-devices#1894]
@RavenSystem I'm sorry to bother you. First of all, thank you very much for your contribution. Second, I have a question. Why does the configuration json and option settings in the web configuration wifi page not set a second layer page in the link wifi interface? Isn't that more concise?
![Uploading WechatIMG
![WechatIMG171](https://user-images.githubusercontent.com/101453973/194528158-5d873ffc-cd67-4878-b2c2-c575a1514a96.png)
170.png…]()

**Comment by RavenSystem** [comment]
Image is not uploaded.

**Comment by ceg117** [comment]
![1701665136689_ pic](https://user-images.githubusercontent.com/101453973/196090121-196087c9-8720-4de3-8b5e-e56902cd36a8.jpg)
![1711665136689_ pic](https://user-images.githubusercontent.com/101453973/196090142-fd415212-8a33-4a0c-bffb-5fc399eff9c9.jpg)
