### ISSUE TITLE
MagicHome RGBW not working (ZJ-WFMN-B v1.1)

### ISSUE THREAD

**Issue by iondarie** [RavenSystem/esp-homekit-devices#1896]
Hello,

I recently purchased a MagicHome ZJ-WFMN-B v1.1) RGBW controller, i flashed the latest release and i used the config from the wiki:
```
{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"g":[15,13,12,14],"ld":[0,1,0,1],"b":[{"g":0}]}]}
```
But the light strip will not power on. What am i doing wrong? 

Thank you,

**Comment by ceg117** [comment]
What colors do your gpio correspond to? I use esp8266 to control rgbw's json for this
{"c":{"o":0},"a":[{"t":30,"s":5,"q":1024,"d":5,"e":10,"fr":1,"fg":1,"fv":1,"b":[],"r":4,"g":5,"v":12,"w":13,"fw":1}]}
