### ISSUE TITLE
Sonoff 5V inching relay - PSF-B01

### ISSUE THREAD

**Issue by 1rado1** [RavenSystem/esp-homekit-devices#1897]
Hello All,
I am seeking for support to create MEPLHAA Script for this device. I am looking for a lock mechanism with inching time 3 seconds. Intent to use as a buzzer for for door. 
I was not able to get it work with working examples.

**Comment by ceg117** [comment]
{"c":{"o":0},"a":[{"0":{"r":[{"g":4,"v":0,"i":3}]},"1":{"r":[{"g":4,"v":1}]},"t":4,"b":[],"s":5}]}

**Comment by 1rado1** [comment]
@ceg117 Thanks, seems that issue is different. After reboot device inching in a loop and doesn’t respond to virtual button.
