### ISSUE TITLE
Problem with Shelly1 on 230v, 3.3v working

### ISSUE THREAD

**Issue by EpureLight** [RavenSystem/esp-homekit-devices#191]
I just bought a Shelly1 and installer the latest RavenSystem software (0.5.15) and my shelly works fine but only when it's connected to the FTDI232 3.3v then everything works fine, I can add the accessory in the home and and the switching works. But when I connect it to the main 230v shelly stops working. When powering back the 3.3v works again. The issue looks exactly like this one https://github.com/RavenSystem/esp-homekit-devices/issues/95

Could you please help me? I think it's a bug.

**Comment by RavenSystem** [comment]
Can you post here your Setup settings (from EVE App)?

**Comment by jubudu** [comment]
Hello, I have just the same issue with 230V mains operation. My Eve-Setup:
Show Setup     on
Board Type     3
Device Type     1
External Toggle1     2
Init State SW1     0
Log output     0
Reboot     off
Reverse SW1     off
Wifi Reset off

**Comment by RavenSystem** [comment]
@jubudu My Shelly1 has same config and works fine connected to 230VAC (v0.5.15). It manages one of the lights of my house. I don’t know what happens with yours.
