### ISSUE TITLE
ESP32 Compatibility

### ISSUE THREAD

**Issue by eucciferri** [RavenSystem/esp-homekit-devices#1919]
Hi Guys! Is there any plans to add ESP32 compatibility in HAA? Thanks!

**Comment by bencharlesrhys** [comment]
Following. Would be great seeing as all new Sonoff devices are moving to ESP32.

**Comment by blackspeck** [comment]
+1

**Comment by Rickth64** [comment]
+1

**Comment by freedreamer82** [comment]
+1

**Comment by TheoPOZ** [comment]
+1

**Comment by Hl2run** [comment]
It would be great. Thank you.

**Comment by nikollou** [comment]
+1

**Comment by Kienz** [comment]
https://youtu.be/HGW_83Cf4xw
