### ISSUE TITLE
Water valve duration

### ISSUE THREAD

**Issue by shingle-smith** [RavenSystem/esp-homekit-devices#193]
Can the default run time for water valves be increased from 1 hour to 4 hours? The option is available in the Eve app but can not be selected.

**Comment by RavenSystem** [comment]
It is an Apple defined characteristic. And max default is 3600 secs. I must try to override that and see if Apple HomeKit allow it.

**Comment by jubudu** [comment]
I have set duration to 8h (28800s) insteD of 3600s and it works.

**Comment by i3laze** [comment]
I also noticed, Eve.app have much more timer durations, than standard Home.app
The chosen timer then persists on Home.app

**Comment by RavenSystem** [comment]
Version 0.6.1 has up 4 hours.
