### ISSUE TITLE
can not add device

### ISSUE THREAD

**Issue by bankmaan** [RavenSystem/esp-homekit-devices#1942]
**Detailed steps to reproduce it**
I'm a novice, why can't I add devices to my home after flashing the firmware and configuring it?
**MEPLHAA Script**
{
"a":[{
"t":30,
"ty":8,
"g":[0,1,60]
}]
}
**Used device**

**HAA version**
6.4.0
**iOS/iPadOS version**

**Logs**
A .txt file with logs. Read [how to capture logs from your device](https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#capture-logs)

**Screen-shots or videos showing issue**

**Comment by Kienz** [comment]
Why do you use HAA 6.4.0 and not latest 11.8.0?

**Comment by RavenSystem** [comment]
HAA v6.4.0 is currently unsupported. Update to last version. Thanks.
