### ISSUE TITLE
shelly 2.5 push button step by step

### ISSUE THREAD

**Issue by kx3kx3kx3** [RavenSystem/esp-homekit-devices#1943]
Hi, it's possible to make a step by step relay with haa latest firmware on shelly 2.5? Do you have a json?

best regards

**Comment by vglucas** [comment]
kx3kx3kx3

shelly 2.5 

Interruttore ciclo - 
Premendo un pulsante, la sequenza è: 

Ch1-On Ch-2-Off, 
Ch1-Off Ch-On, 
Ch1 e Ch2 On, 
Ch1 e Ch2 Off.



{"c":{"l":0,"b":[{"g":2,"t":5}],"ic":[[14,12,100]]},"a":[{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"es":[{"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]}},{"t":22,"h":2,"n":5,"j":10,"y0":[{"v":75,"r":1,"0":{"m":[[1],[2]]}}]}]},{"t":65,"h":0,"e":5,"s":1,"xa":0,"y0":[{"v":1,"0":{"m":[[1],[2]]}},{"v":2,"0":{"m":[[1,1],[2]]}},{"v":3,"0":{"m":[[1],[2,1]]}},{"v":4,"0":{"m":[[1,1],[2,1]]}},{"v":5,"0":{"m":[[0,1]]}}]},{"h":0,"i":0.1,"1":{"m":[[-1,-1]]},"f1":[{"g":5,"p":0,"i":1,"t":0}]}]}
