### ISSUE TITLE
Shelly 2 ravencore 5.10 2 switch not working 

### ISSUE THREAD

**Issue by wroblewski6** [RavenSystem/esp-homekit-devices#195]
Hi  i have ravencoee 5.10 on my shelly 5.10 but when i choose device 2 switch I can and board type 3 than only switch 2 is working and when I chose device type 13 switch 1 is working but I can not see switch 2 so I can use only 1 switch at the same time , maybe I made some mistake ? 

I’m eve app I do not see option to update software so what can I do update my Shelly if I do not have working ft232 adapter ?? Ota update is now visible ??

**Comment by RavenSystem** [comment]
You must update to last firmware in order to fix the second missing switch bug.

To update with OTA, you must install firmware using LCM. If you don’t see “firmware update” option in EVE setup, you haven’t used LCM. See Wiki.
