### ISSUE TITLE
HAA-C21DAD pairing code

### ISSUE THREAD

**Issue by emilleszczak2** [RavenSystem/esp-homekit-devices#1959]
I have a HAA-C21DAD and tried to add device to HomeAssistant by HomeKit Controller. There is needed  pairing code, how can I get it?

**Comment by Kienz** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation#homekit-setup

**Comment by emilleszczak2** [comment]
@Kienz thanks
