### ISSUE TITLE
can't get to setup mode, update, reboot or wifi reconnection using the app

### ISSUE THREAD

**Issue by toshibochan** [RavenSystem/esp-homekit-devices#1966]
firmware 11.9.1
I'm using the HAA Manager to trying get to setup mode but not working. I don't know if is the app or the new firmware.i try all setup mode, update, reboot or wifi reconnection but not working.

**Comment by InJecTeD-** [comment]
Same here.
First thought firmware is to old (11.7.1).
Erased (blank file) one of my shellys and flashed 11.9.1 .
Still no setup mode etc. using HAA Manager. 
Log shows "Upd CH" - nothing more. 
I think one of the last app updates broke it.

**Comment by RavenSystem** [comment]
It is a known bug. It is fixed in v3.4.4, but I am waiting Apple approval.

**Comment by RavenSystem** [comment]
HAA Home Manager v3.4.4 is now ready at App Store.

**Comment by spacemannz** [comment]
Hi, the issue seems to persist for me with 3.4.4 - same as described above.

**Comment by InJecTeD-** [comment]
Strange, for me 3.4.4 fixed it. (thank you @RavenSystem)
