### ISSUE TITLE
HomeKit server: error

### ISSUE THREAD

**Issue by deviann877** [RavenSystem/esp-homekit-devices#1968]
Hi, I keep when asking Siri "what's the status of...". I get a message "some of your devices failed to respond"

Has only just started happening. When viewing settings of the devices in HAA manager it says HomeKit Server: error 

![image](https://user-images.githubusercontent.com/76647355/217790624-05f72626-f871-4fa0-9a3c-699bb79669b9.jpeg)

![image](https://user-images.githubusercontent.com/76647355/217790656-8f6746d3-d27e-43f7-a63a-2a7505e7cf20.jpeg)

**Comment by RavenSystem** [comment]
It is a wifi connection issue. Check your network.
