### ISSUE TITLE
cannot connect to device after initial setup.

### ISSUE THREAD

**Issue by DonLeeFK** [RavenSystem/esp-homekit-devices#1982]
cannot connect to device after initial setup.

so I checked port 4567, but its not open.

`Nmap scan report for 192.168.1.32
Host is up (0.015s latency).
All 1000 scanned ports on 192.168.1.32 are in ignored states.
Not shown: 1000 closed tcp ports (reset)
MAC Address: 18:FE:34:E2:39:0B (Espressif)`

**Comment by RavenSystem** [comment]
Please, read the Wiki: https://github.com/RavenSystem/esp-homekit-devices/wiki/Setup-Mode#entering-setup-mode
