### ISSUE TITLE
esp32 IR/RF Capture GPIO

### ISSUE THREAD

**Issue by PhaseAngle** [RavenSystem/esp-homekit-devices#1996]
**Detailed steps to reproduce it**
use esp32 setup
**Used device**
Kincony KC868-A4
**HAA version**
12.0.1

My IR is GPIO23
My RF is GPIO19

neither of these are in the drop down list

**Comment by RavenSystem** [comment]
You are right. I forgot to add more GPIOs for ESP32 models.

**Comment by RavenSystem** [comment]
IR-RF Capture Mode is broken for esp8266 too since v12.0.0. It will be fixed in v12.0.2.
