### ISSUE TITLE
Sonoff Basic

### ISSUE THREAD

**Issue by ageorgios** [RavenSystem/esp-homekit-devices#2]
Actually when having load (like a 5W lamp) the sonoff basic devices reset and go to AP mode forgetting the Homekit configuration.
It works when no lamp is connected

**Comment by RavenSystem** [comment]
???

**Comment by ageorgios** [comment]
my mistake

**Comment by RavenSystem** [comment]
It sounds like a hardware issue. I can not reproduce your issue. My Sonoff Basic works well having load. And actually, the only way to do a factory reset is hold down button for 10 seconds.

Can you provide more info? (UART output; try to connect another thing...)

**Comment by ageorgios** [comment]
Possible hardware failure
