### ISSUE TITLE
iFan03 Incorrect work

### ISSUE THREAD

**Issue by fiska1** [RavenSystem/esp-homekit-devices#2008]
1) When using the Home Kit, % shows correctly, but the fan immediately turns on at maximum speed and is not adjustable. Photos 1, 2, 3,
2) When using the remote control, the speed is regulated (vice versa), 1- maximum, 3-minimum. At the same time, the slider in the Home Kit immediately shows the maximum, % of the speed shows 1000 , 2000 , 3333 . Photo 4,5,6.
3) JSON used with Devises Database.
{"c":{"io":[[[13],3],[[0],6],[[9,12,14,15],2]],"z":12,"r":[{"n":10,"s":9600,"l":[8,8]}],"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":65,"0":{"r":[{"g":15},{"g":12},{"g":14}]},"y0":[{"v":1,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]}},{"v":33,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]}},{"v":67,"0":{"r":[{"g":15,"v":1},{"g":12},{"g":14,"v":1}]}}],"es":[{"s":1,"1":{"r":[{"g":9}]},"0":{"r":[{"g":9,"v":1}]},"b":[{"g":0}]}]},{"t":80,"h":0,"n":24,"pt":[["AA",5]],"dt":[2,0],"y0":[{"v":260,"r":1,"0":{"m":[[7002,1]]}},{"v":517,"r":1,"0":{"m":[[7002,1]]}},{"v":6,"r":1,"0":{"m":[[7001,1],[-2]]}},{"v":263,"r":1,"0":{"m":[[7001,1],[-2,30],[-2,101]]}},{"v":520,"r":1,"0":{"m":[[7001,1],[-2,60],[-2,101]]}},{"v":777,"r":1,"0":{"m":[[7001,1],[-2,100],[-2,101]]}},{"v":1034,"r":1,"0":{"m":[[7001,1],[-1,4]]}},{"v":265,"r":1,"0":{"m":[[7004,1]]}},{"v":266,"r":1,"0":{"m":[[7003,1]]}}]},{"h":0,"i":0.1,"1":{"u":[{"v":"AA550104000005"}]}},{"h":0,"i":0.1,"1":{"u":[{"v":"AA550101000002"}]}},{"h":0,"i":0.1,"1":{"u":[{"v":"AA550107000008"}]}},{"h":0,"i":0.1,"1":{"u":[{"v":"AA550106000007"}]}}]}
![3](https://user-
![4](https://user-images.githubusercontent.com/30092533/235448091-272d8c61-6582-4e2d-a8e8-d28a95d35756.jpg)
![5](https://user-images.githubusercontent.com/30092533/235448096-95e8a431-74a7-41f6-8106-45e1c74e3376.jpg)
![6](https://user-images.githubusercontent.com/30092533/235448097-63a93f1f-4684-4ec7-83fd-6c4d513624b8.jpg)
![2](https://user-images.githubusercontent.com/30092533/235448098-813e44f4-7a93-43dc-8023-76ca1e1e10d3.jpg)
![1](https://user-images.githubusercontent.com/30092533/235448099-daf61370-7927-494f-a127-98b5cdd27221.jpg)
![1](https://user-images.githubusercontent.com/30092533/235448238-9a86f676-1859-4870-b781-f5429ecfaf63.jpg)
![2](https://user-images.githubusercontent.com/30092533/235448242-8c870d3c-72ff-4a36-85bb-5adaaf7211d8.jpg)
![3](https://user-images.githubusercontent.com/30092533/235448243-65840567-78eb-4a5a-a532-3e587164c37b.jpg)
![4](https://user-images.githubusercontent.com/30092533/235448244-f31a35e6-1124-4404-bec8-cc55896da861.jpg)
![5](https://user-images.githubusercontent.com/30092533/235448246-fdcaf1e9-4cbe-4b40-bc26-3e904f5141c1.jpg)
![6](https://user-images.githubusercontent.com/30092533/235448250-f41fb921-c233-4c2b-9dd4-f311ccf61772.jpg)
images.githubusercontent.com/30092533/235448071-5f1ccbb1-1902-48c3-8768-24c1ea37c635.jpg)

**Comment by fiska1** [comment]
On HAA v.11, everything worked correctly with such JSON
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":65,"e":3,"0":{"r":[{"g":15},{"g":12},{"g":14}]},"y0":[{"v":3,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]}},{"v":2,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]}},{"v":1,"0":{"r":[{"g":15,"v":1},{"g":4},{"g":14}]}}]},{"1":{"r":[{"g":9}]},"0":{"r":[{"g":9,"v":1}]},"b":[{"g":0}]}]}

**Comment by RavenSystem** [comment]
Your script has different HomeKit services. You must use same services with same % configuration to avoid issues if you don't want to re-pair it to HomeKit. Use this v12 Merlin updated script base on your old script:

```json
{"c":{"io":[[[13],3],[[0],6],[[15,12,14,9],2]],"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":65,"e":3,"0":{"r":[{"g":15},{"g":12},{"g":14}]},"y0":[{"v":3,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]}},{"v":2,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]}},{"v":1,"0":{"r":[{"g":15,"v":1},{"g":4},{"g":14}]}}]},{"1":{"r":[{"g":9}]},"0":{"r":[{"g":9,"v":1}]},"b":[{"g":0}]}]}
```

**Comment by RavenSystem** [comment]
Please, use issues only for firmware issues.
