### ISSUE TITLE
12.1.1 stop working and stop manage by haa manager

### ISSUE THREAD

**Issue by richardlimaa** [RavenSystem/esp-homekit-devices#2022]
After update yesterday from 12.0.2, cant manager by HAA manager and cant add again to homekit

**Comment by richardlimaa** [comment]
Can i downgrade to 12.0.2?

**Comment by Ucoz3000** [comment]
Firmware can also be downgraded by placing an older copy of the files on your web server.

**Comment by Ucoz3000** [comment]
after updating to version 12.1.1 from 12.0.3, some Sonoff Basics are no longer controlled. After rolling back to 12.0.3 everything worked.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki#issues
