### ISSUE TITLE
DS18B20 and temperature offset

### ISSUE THREAD

**Issue by digiservice2001** [RavenSystem/esp-homekit-devices#207]
I used DS18B20 sensors and two different esp based device.  (Sonoff Basic and Wemos D1 mini)
When I set temperature offset to not zero, and reboot device, it goes to No response status.
Maybe that is a bug, eg. temperature values are out of range?

**Comment by digiservice2001** [comment]
Nobody has this issue, just me?  :-)

**Comment by RavenSystem** [comment]
Try to set an integer number for temp offset (1.0, 2.0, 3.0...). I think there is a bug with floats.

**Comment by digiservice2001** [comment]
I think, i'm looking forward to bugfix. :-)

**Comment by digiservice2001** [comment]
It works like a charm!
