### ISSUE TITLE
the problem of choice. Esp8266 or esp32

### ISSUE THREAD

**Issue by jukorp** [RavenSystem/esp-homekit-devices#21]
I will build a dual channel pwm dimmer -> trailing edge dimmer. Include local dim up and dim down buttons.
esp32 is much faster?

**Comment by RavenSystem** [comment]
Esp32 is much faster than 8266. Higher clock frecuency and dual core. And many improvements and Bluetooth support too. And mDNS used in esp32 HomeKit framework is full compatible with Apple Bonjour (it passes official Bonjour Apple tests).

**Comment by jukorp** [comment]
This ravencode support only esp8266?
If i need esp32 :)

**Comment by RavenSystem** [comment]
Sonoff RavenCore is only for several Sonoff devices, and they use esp8266.

I want to play with esp32, but for now I haven't a protoboard with an esp32 chip.

**Comment by jukorp** [comment]
Maybe this is good?
I have this kind of myself.

Aliexpress or ebay about 5€

https://m.ebay.com/itm/ESP-32-ESP32S-Development-Board-2-4GHz-Dual-Mode-WiFi-Bluetooth-Antenna-Module-M/152479854433?epid=17016407741&hash=item238081ef61:g:HcsAAOSwDVtaVJGO

**Comment by jukorp** [comment]
does something happen in lwip development?
is this helpful?

https://github.com/espressif/esp-idf/issues/1512#issuecomment-405095172

**Comment by RavenSystem** [comment]
Sorry, I haven't any experience coding for esp32 yet. And yes, I'm going to buy a esp32 development board from Aliexpress asap.
