### ISSUE TITLE
Issue - GPIO2 new board

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#211]
Hi,
I experienced a problem with new layout board and GPIO2. When GPIO2 is closed with ground and device boots, it hangs and does nothing. 
Is there any solution for this?

**Comment by ymyshko** [comment]
GPIO2 must be high when ESP82xx boots.

**Comment by claire078** [comment]
Yes, that is what I’m talking about.
😔
I read somewhere RX pin also can use it to control switch?
But it should be programmed in firmware.

**Comment by RavenSystem** [comment]
Update to version 0.6.0 and use RX with board type 4.
