### ISSUE TITLE
ESP32-S2 glitch filter makes GPIO unusable

### ISSUE THREAD

**Issue by Tellicious** [RavenSystem/esp-homekit-devices#2116]
Setting glitch-filter on an ESP32-S2 stops the input pin from working.

when GPIO 0 is defined with pull-up setting `11`, it no longer works to launch setup mode. I even tried using GPIO 0 with setting `11` for a switch, but it doesn't work either. Changing its pull-up setting back to `1` makes it work again.

Non-working script: 
`{"c":{"io":[[[15],2],[[0],6,11,1]],"l":15,"i":0,"ic":[[9,8,90,1,1]],"v":2,"o":8,"b":[[0,5]],"n":"HAA-CO2"},"a":[{"t":10,"i":60},{"t":24},{"t":80,"n":20,"cd":7,"in":[[0,33,177]],"ic":[0,98],"dt":[2,0],"l":[400,5000],"y0":[{"v":1000,"r":1,"0":{"m":[[1,1],[1,-1]]}}]},{"t":80,"n":20,"cd":7,"tg":[2,0],"ic":[0,98],"io":3,"dt":[2,0],"ff":0.00267033,"fo":-45,"l":[-10,60]},{"t":80,"n":20,"tg":[2,1],"ic":[0,98],"io":6,"dt":[2,0],"ff":0.0015259}]}`

Working script:
`{"c":{"io":[[[15],2],[[0],6,1,1]],"l":15,"i":0,"ic":[[9,8,90,1,1]],"v":2,"o":8,"b":[[0,5]],"n":"HAA-CO2"},"a":[{"t":10,"i":60},{"t":24},{"t":80,"n":20,"cd":7,"in":[[0,33,177]],"ic":[0,98],"dt":[2,0],"l":[400,5000],"y0":[{"v":1000,"r":1,"0":{"m":[[1,1],[1,-1]]}}]},{"t":80,"n":20,"cd":7,"tg":[2,0],"ic":[0,98],"io":3,"dt":[2,0],"ff":0.00267033,"fo":-45,"l":[-10,60]},{"t":80,"n":20,"tg":[2,1],"ic":[0,98],"io":6,"dt":[2,0],"ff":0.0015259}]}`

**Comment by RavenSystem** [comment]
Glitch filter works fine. Each board has different hardware, and glitch filter is not very well documented im Espressif web. HAA has the ability to use it, but user must understand how hardware works and possible incompatibilities. Try using an external pull-up resistor instead internal to avoid drain from internal chip, try other GPIO that is not a strapping pin...
