### ISSUE TITLE
Incorrect reading with low-speed I2C

### ISSUE THREAD

**Issue by Tellicious** [RavenSystem/esp-homekit-devices#2133]
When running an I2C bus at low frequency (10 kHz) the reading returned is incorrect. At normal I2C frequencies (100-400 kHz) everything seems to work fine. Unfortunately I cannot test this very same device at 100 kHz as it supports only up to 15 kHz. Tried with and without pull-ups but the behavior is the same. As you can see in the log, service 3 is reading `63` while, on the bus, the data being transmitted (4th byte) is `0x57 = 87`.

<img width="1298" alt="Screenshot 2023-10-13 at 10 41 13" src="https://github.com/RavenSystem/esp-homekit-devices/assets/9076397/44d1ee0b-9d34-4d9d-8cba-f1017a53f089">

Looking at a longer-term log of this issue, what I noticed is that all values read by HAA never have a single 1 followed by 0. All 1s are always in "couples". Like in this example, `63 = 00111111` while the correct value is `87 = 01010111`.

HAA always sees data with a pattern such as: `11001100` or `00111100` but never `01010101` or `01110100`.

It kind of looks like it "duplicates" the 4 least significant bits: `87 = 01010111 -> xxxx0111 -> 00 11 11 11 = 63`.

**MEPLHAA Script:**
 ```
{"c":{"io":[[[15],2],[[0],6,1,1],[[3],6,10]],"l":15,"i":0,"ic":[[11, 10, 10,1,1]],"v":2,"o":8,"b":[[0,5]],"n":"HAA-Test","ntp":"ntp1.inrim.it","tz":"CET-1CEST-2,M3.5.0/2,M10.5.0/3"},
"a":[{"t":24,"g":2,"n":2,"j":30,"es":[
    {"t":12,"cd":1,"i":10,"f1":[[3,1]]},
   {
    "t": 80,
    "h": 2,
    "n": 20,
    "cd": 0.01,
    "ic": [0,26,0],
    "io": 1,
    "dt": [3,0],
    "j": 2.5
    },
   {"t": 95,"h": [3, 0, 10],"j": 300,"x": 1}
   ]}]}
```
**Log:**
[Oct 13 104024 HAA Log.log](https://github.com/RavenSystem/esp-homekit-devices/files/12891378/Oct.13.104024.HAA.Log.log)

**Device Info:**
HAA version: 12.9.0
Device: ESP32-S2

**Comment by RavenSystem** [comment]
I am aware of this. I2C driver has some bugs with clock when low speed is used, but since it is a hardware feature managed directly by ESP-IDF SDK, accessing through its API, it is completely out my control. You can try with different external pull-up resistors, and avoid using internal pull-up resistors, because they can create issues with I2C driver due to their values.

From official documentation at https://docs.espressif.com/projects/esp-idf/en/v5.1.1/esp32s2/api-reference/peripherals/i2c.html

> The clock frequency of SCL will be influenced by the pull-up resistors and wire capacitance (or might slave capacitance) together. Therefore, users need to choose correct pull-up resistors by themselves to make the frequency accurate. It is recommended by I2C protocol that the pull-up resistors commonly range from 1KOhms to 10KOhms, but different frequencies need different resistors.
>
> Generally speaking, the higher frequency is selected, the smaller resistor should be used (but not less than 1KOhms). This is because high resistor will decline the current, which will lengthen the rising time and reduce the frequency. Usually, range 2KOhms to 5KOhms is what we recommend, but users also might need to make some adjustment depends on their reality.
