### ISSUE TITLE
Shelly 2 & Rolling Shutters

### ISSUE THREAD

**Issue by raffi961** [RavenSystem/esp-homekit-devices#214]
Hi
I will be receiving my Shelly 2 and would like to know if i will be able to control my rolling shutters using the latest firmware ?

Thank you

**Comment by RavenSystem** [comment]
No. Rolling shutters are not implemented yet.

**Comment by totos21** [comment]
hi, any news about this request? I would like to control my rolling shutters using your firmware. 
thank you very much

**Comment by RavenSystem** [comment]
Rolling shutters was added 3 months ago: https://github.com/RavenSystem/esp-homekit-devices/releases/tag/RC_0.7.0
