### ISSUE TITLE
Type 4 for Sonoff Dual? 

### ISSUE THREAD

**Issue by seritos** [RavenSystem/esp-homekit-devices#215]
I have seen your upgrade allowing to use the RX pin as a toggle. Thnx!! 
Would be possible to allow this in the Sonoff Dual to avoid the boot issue if set to low? 
This is, button 0 = RX and Button 1 remains as original when set the external toggle=2

**Comment by RavenSystem** [comment]
Yes, it will be implemented with the next update.
