### ISSUE TITLE
“Show setup” enabled after OTA firmware update

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#216]
Just curious:

I just did a routine OTA firmware upgrade and device stayed in “Show setup” mode after.
It required me to switch off the “Show setup” toggle and reboot to get back to basic work mode.

As Wiki mentioned, it’s not desired to stay in “Show setup” mode, so why don’t turn it off during FW update too?
I got 4+ devices, it might save me some time during batch update.

**Comment by RavenSystem** [comment]
Show setup keeps on because sometimes OTA update fails and you must try it again, and to ensure that new setup features are loaded correctly when there are.

**Comment by i3laze** [comment]
I was just suggesting.

Most of the time OTA goes pretty fine.

**Comment by RavenSystem** [comment]
If you want, you can toggle off show setup before toggle on firmware update.
