### ISSUE TITLE
Multiple GPIO uses

### ISSUE THREAD

**Issue by seritos** [RavenSystem/esp-homekit-devices#217]
Good Morning!

Will be possible to use the new RX port in combination with GPIO 2/14 for multiple uses? This is, use the RX port for external toggle and GPIO2/14 for ( for example) temperature and humidity.
We have previously commented this, but the case was closed yesterday.
This is very useful to know the temperature of every room in combination maintaining the original room switches. 

Thanx Jose!

**Comment by RavenSystem** [comment]
This will be possible with new HomeKit Accessory architect, not with RavenCore.

**Comment by seritos** [comment]
Awesome.

Thanx @RavenSystem !
