### ISSUE TITLE
Remove WI-Fi Settings should re-enable AP mode

### ISSUE THREAD

**Issue by tokamac** [RavenSystem/esp-homekit-devices#2179]
When removing Wi-Fi settings, if AP mode has been previously disabled, the accessory reboots and is definitely unreachable from any system, and can't be modified anymore, unless it is erased and reinstalled completely again through a serial connection.

AP mode should remain disabled only while the accessory is connected to the Wi-Fi network; or if the accessory reboots with the credential of that Wi-Fi network still saved, even if the Wi-Fi network is not available at the moment.

When Wi-Fi Settings are removed completely, this process should also enable again AP mode.

**Comment by RavenSystem** [comment]
Fixed with https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_12.10.2
