### ISSUE TITLE
Can’t update from 0.5.14 OTA

### ISSUE THREAD

**Issue by St0nehead** [RavenSystem/esp-homekit-devices#218]
Yesterday i successfully updated all my 0.5.15 devices over the air. But still can’t update Sonoff Basic using same procedure..

**Comment by GPL71** [comment]
unplug and plug it and try again

**Comment by St0nehead** [comment]
Tried about 10 times without any result (((

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#lcm-ota-logs

**Comment by GPL71** [comment]
@St0nehead
I'd have some issue too, solved reflashing using MAC. I don't know why but windows have problems

**Comment by Partizan7676** [comment]
did you try to erase it first?

**Comment by RavenSystem** [comment]
@St0nehead logs, please.

**Comment by St0nehead** [comment]
How to dowload logs?

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#lcm-ota-logs

**Comment by St0nehead** [comment]
Last login: Fri Feb 15 00:50:56 on console
Mac-Pro:~ reber$ screen /dev/tty.SLAB_USBtoUART 115200
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: [Client 5] Add Pairing
>>> HomeKit: Added pairing with EE14DB0C-9DEB-4E52-8400-E879xxxxxxxx
>>> HomeKit: [Client 4] Update Characteristics
>>> HomeKit: [Client 4] Update Characteristics
>>> HomeKit: [Client 4] Get Characteristics
RC > Toggle SW 1
RC > Relay 1 -> 1
>>> HomeKit: Got new client connection: 7
>>> HomeKit: [Client 7] Pair Verify Step 1/2
>>> HomeKit: Got new client connection: 8
>>> HomeKit: [Client 8] Pair Verify Step 1/2
>>> HomeKit: [Client 7] Pair Verify Step 2/2
>>> HomeKit: [Client 7] Found pairing with D14F350F-988C-490B-90A1-1E07A5xxxxxx
RC > Saving last states
>>> HomeKit: [Client 7] Verification successful, secure session established
>>> HomeKit: [Client 8] Pair Verify Step 2/2
>>> HomeKit: [Client 8] Found pairing with CE91B9DA-A299-4226-B61D-255D4xxxxxxxx
>>> HomeKit: [Client 8] Verification successful, secure session established
>>> HomeKit: [Client 7] Get Accessories
>>> HomeKit: [Client 8] Get Accessories
>>> HomeKit: [Client 8] Add Pairing
>>> HomeKit: Updated pairing with EE14DB0C-9DEB-4E52-8400-E879xxxxxxxx
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Update Characteristics
RC > Toggle SW 1
RC > Relay 1 -> 0
RC > Saving last states
>>> HomeKit: [Client 5] Closing client connection
>>> HomeKit: [Client 8] Closing client connection
>>> HomeKit: [Client 6] Closing client connection
>>> HomeKit: [Client 4] Closing client connection
>>> HomeKit: [Client 7] Closing client connection
>>> HomeKit: Got new client connection: 4
>>> HomeKit: [Client 4] Pair Verify Step 1/2
>>> HomeKit: [Client 4] Pair Verify Step 2/2
>>> HomeKit: [Client 4] Found pairing with CE91B9DA-A299-4226-B61D-255Dxxxxxxxxx
>>> HomeKit: [Client 4] Verification successful, secure session established
>>> HomeKit: [Client 4] Closing client connection
>>> HomeKit: Got new client connection: 4
>>> HomeKit: [Client 4] Pair Verify Step 1/2
>>> HomeKit: Got new client connection: 5
>>> HomeKit: [Client 5] Pair Verify Step 1/2
>>> HomeKit: [Client 4] Closing client connection
>>> HomeKit: [Client 5] Closing client connection

**Comment by RavenSystem** [comment]
Log from OTA firmware is needed.
