### ISSUE TITLE
relay active low clicking on restart/boot

### ISSUE THREAD

**Issue by duku602** [RavenSystem/esp-homekit-devices#2184]
### Discussed in https://github.com/RavenSystem/esp-homekit-devices/discussions/2183

<div type='discussions-op-text'>

<sup>Originally posted by **duku602** January  5, 2024</sup>
Hello,
I have multiple board relays that are set to activate the relays when gpio is low thus needing me to declare them with pull-up but, when the esp8266 d1 mini restarts/boots, it activates the relays making the lights/garage to open.. 

is there any way in the script to bypass this issue, I've read (not tested) that the code should be digitalWrite(GPIO#, HIGH); before delaring the pinMode(GPIO#, OUTPUT); (but we cannot actually write it as we can only use json).

any help will be appreciated!
Thanks

script example
`{
  "c":{
    "io":[[[0],6],[[5,4,14,12],2,1],[[13],6,1]],
    "b":[[0,5]], "u":1
  },
  "a":[{
    "t":1,
    "s":5,
    "0":{"r":[[12,1]]},
    "1":{"r":[[12,0]]},
    "es": [{
    "t":1,
    "s":5,
    "0":{"r":[[4,1]]},
    "1":{"r":[[4,0]]}
     },{
    "t":1,
    "s":5,
    "0":{"r":[[5,1]]},
    "1":{"r":[[5,0]]}
     },{
    "t":1,
    "s":5,
    "0":{"r":[[14,1]]},
    "1":{"r":[[14,0]]}
     },{
    "t":1,
    "s":5,
    "g0":[[13]],
    "g1":[[13,0]]
     }]
  }]
}`</div>

**Comment by RavenSystem** [comment]
Duplicated: https://github.com/RavenSystem/esp-homekit-devices/discussions/2183
