### ISSUE TITLE
How to update multiple devices at once

### ISSUE THREAD

**Issue by rechin304** [RavenSystem/esp-homekit-devices#219]
Hi,

There is any way to trigger multiple devices to update to latest version. For example I have more than 15 devices now and is annoying to go to every device and trigger it.
Thanks.

**Comment by RavenSystem** [comment]
Create Scenes into EVE App.

**Comment by rechin304** [comment]
can you please elaborate more ? thx How to

**Comment by rechin304** [comment]
Solved. Thanks allot.
