### ISSUE TITLE
WiFi version drops after updates

### ISSUE THREAD

**Issue by miguelpruivo** [RavenSystem/esp-homekit-devices#2197]
Hi, been noticing this for a while now and think it would be helpful to provide this info.

**Problem**
basically every now and then, after updating HAA to whatever versions are released, during the update process (which occurs without issues) the devices sometimes will start connecting back using WiFi 3 instead of WiFi 4. It seems to be **always** WiFi 3 when this happens. Rebooting doesn't solve. This has been happening with all my Shelly devices randomly, I don't know what or how often it happens, but it's random and _always_ after an update. Sometimes happens to 2 of my devices, sometimes to 5 or to none.

**Solution**
The only viable solution is to reset settings or remove WiFi settings, entering the AP mode and then entering the WiFi settings again. The it will start connecting back with WiFi 4.

I suspect that the issue is due to some corruption while updating, but you should have more insights. Not a major issue, but I think it may be improved during the update process if something is "breaking" some data. :)

**Comment by RavenSystem** [comment]
Fixed with v12.11.3.
