### ISSUE TITLE
Sonoff Touch T1 1CH, support?

### ISSUE THREAD

**Issue by pandarek** [RavenSystem/esp-homekit-devices#220]
Sonoff Touch T1 1CH is based on ESP8285. Will RavenCore work with this device?

**Comment by RavenSystem** [comment]
Yes. ESP8285 is an ESP8266 with a 1MB internal flash.

**Comment by mu2004** [comment]
Is the 3 CH Sonoff Touch supported too? Does it show up as 3 devices in HomeKit? That seems to be the best solution for installation.
