### ISSUE TITLE
i2c not working properly (iAQ-Core, ESP32)

### ISSUE THREAD

**Issue by paulzhdanov** [RavenSystem/esp-homekit-devices#2216]
ESP8266 config with 5,4 gpio works fine, but at ESP32 (with proper gpio change) it doesn't. Here's the script

{
  "c":{"b":[[0,5]],"n":"haaco2","io":[ [[0],6,1,0]], "ic":[[22,21,100]],"ntp":"time.apple.com","tz":"CET-1CEST-2,M3.5.0/2,M10.5.0/3","o":4},
  "a":[{
    "t":10,
    "dt":1,
    "i":60
  },{
    "t":15,
    "dt":[6]
  },{
    "t":80,
    "n":20,
    "h":0,
    "ic":[0,90],
    "dt":[2,0],
    "io":7,
    "tg":[2,1],
    "y0":[
      {"v":0,"0":{ "m":[[2,1]]}},
      {"v":50,"0":{ "m":[[2,2]]}},
      {"v":100,"0":{ "m":[[2,3]]}},
      {"v":200,"0":{ "m":[[2,4]]}},
      {"v":300,"0":{ "m":[[2,5],[2,-1]]},"r":1}
    ]
  },{
   "t":80,
    "n":20,
    "h":0,
    "ic":[0,90],
    "dt":[2,0],
    "tg":[1,1],
    "y0":[
      {"v":1100,"0":{"m":[[1,1],[1,-1]]},"r":1}
    ]
  }]
}

ESP32

12.11.4

17.2.1

Log:
Feb 17 19:46:01 192.168.1.184-13B190 ! <3> I2C 263
Feb 17 19:46:01 192.168.1.184-13B190 ! <4> I2C 263

Displayed level in HomeKit: 46387

**Screen-shots or videos showing issue**

**Comment by RavenSystem** [comment]
Sorry, nothing to do from my side: For ESP32, C and S, I2C driver comes directly from official ESP-IDF SDK. Try new HAA version 12.12, that is compiled with the new SDK version.
