### ISSUE TITLE
Total Consumption in the Eve app

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#222]
How to add an total consumption.
I found these UUID - E863F10C-079E-48FF-8F27-9C2605A29F52 here https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d
which displays data in the Eve App.
Do I have to create HOMEKIT SERVICE and how?

**Comment by RavenSystem** [comment]
You must create a custom HomeKit characteristic with that UUID. You can see examples here: 
https://github.com/RavenSystem/esp-homekit-devices/blob/master/devices/common/custom_characteristics.h
