### ISSUE TITLE
Device shows wrong temperature after updating from 12.12.4 --> 12.12.5

### ISSUE THREAD

**Issue by Gandalf8266** [RavenSystem/esp-homekit-devices#2262]
I have a ESP8266 microcontroller with a DHT22 connected. 
Device works fine so far, but on every update it shows wrong temperature (-99°C) and humidity (0%).

It happens on every update, but now, I made screenshots bevor und after update. 
It's easy to fix, I only disconnect from power and connect again, but this is annoying.

The config is here:
{"c":{"o":0},"a":[{"t":24,"b":[],"n":2,"g":2}]}

I have attached screenshots bevor und after update. 
![60B4C2C2-883E-49BD-BABF-5D34BF610072_1_105_c](https://github.com/RavenSystem/esp-homekit-devices/assets/38372908/cb399070-98b9-499e-955a-ad23558a61ea)
![F040EF1D-E3D7-43E1-89E9-D2D261DC7670_1_105_c](https://github.com/RavenSystem/esp-homekit-devices/assets/38372908/046d06e8-4ba7-41b7-9726-81ccfe813719)
![3982D7D4-4354-4433-AC18-F88CB375CC4F_1_105_c](https://github.com/RavenSystem/esp-homekit-devices/assets/38372908/652f9721-c0a9-41b8-aa02-86972ce021b9)
![68446734-B470-4665-BAFA-72240B0F9BD0_1_105_c](https://github.com/RavenSystem/esp-homekit-devices/assets/38372908/a9c269ef-e005-484a-b037-0f6d970f1a71)

**Comment by RavenSystem** [comment]
It is hardware related. GPIO 2 is pulled up and high at boot. This can not be changed by firmware. Better, use other GPIO.
https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

**Comment by vsidlu** [comment]
Strange, but sometimes it shows the correct reading, but sometimes -99. What could this be related to?

**Comment by vsidlu** [comment]
I replaced all DHT22 temperature sensors. I no longer encounter this issue.
