### ISSUE TITLE
Window rolling shutter, for Sonoff Dual 

### ISSUE THREAD

**Issue by WimVanHonacker** [RavenSystem/esp-homekit-devices#227]
Hello,
have you any idea when you will implement the window roller shutter?
I will use the in my Homekit automation.
thanks in advance.

Wim

**Comment by RavenSystem** [comment]
Sorry, no idea. When I have enough free time ;)

**Comment by gijsstegehuis** [comment]
Looks like it's here @WimVanHonacker :)
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#12-window-covering
