### ISSUE TITLE
Shelly 2.5

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#228]
@RavenSystem
Hello ... 
Shelly is near to release the Shelly 2.5
Something in the hardware will change (power of relay and current meter should be)
Is Ravencore firmware compatible with Shelly 2.5 yet?
Thank you Josè

**Comment by GPL71** [comment]
@RavenSystem 
Hello ... Is ravencore compatible with Shelly 2.5?

**Comment by RavenSystem** [comment]
I don't know, because I don't know its GPIO map, but I think is the same as Shelly2. Shelly 2.5 has an external UART conector, and I think shelly.cloud will publish GPIO map soon.

**Comment by i3laze** [comment]
Got Shelly 2 recently and I already know why it's been discontinued - this needle magic sucks:
![img_1645](https://user-images.githubusercontent.com/16850291/52771124-1afad180-3046-11e9-9015-9ecb64413bb3.jpg)

**Comment by RavenSystem** [comment]
I will support Shelly 2.5 when available.

**Comment by greensouth** [comment]
Yummyyyyy!!

Any news on the Shelly 2.5 support? 

Btw, I had my first experience with Ravencore flashing a Magic Home LED wifi controller and … "$)( I'm really excited and impressed with the results!! Keep on the hard work, it's really impressive.

Now waiting for the 2.5, very excited :)

**Comment by RavenSystem** [comment]
@greensouth I am glad you like it!

Shelly 2.5 support was added in version 0.8.3. Remember that you can see changelogs under Releases tab: https://github.com/RavenSystem/esp-homekit-devices/releases

I haven't any Shelly 2.5 yet, so I don't know if there are bugs about that.

**Comment by greensouth** [comment]
> @greensouth I am glad you like it!
> 
> Shelly 2.5 support was added in version 0.8.3. Remember that you can see changelogs under Releases tab: https://github.com/RavenSystem/esp-homekit-devices/releases
> 
> I haven't any Shelly 2.5 yet, so I don't know if there are bugs about that.

YOU - MADE - MY - DAY!! Thank you!! I'll be trying it in the next days!

Coño, que bien me lo voy a pasar este puente! :)

**Comment by RavenSystem** [comment]
Jajaja, pues dale caña! Y esperemos que no haya fallos. Si los hubiera, abre una nueva incidencia (issue) con los detalles.

**Comment by greensouth** [comment]
Ya te digo! este puente intentare motorizar una persiana, con que no me salga ardiendo la casa, me apaño jajajjaja! Soy bastante novato con el tema relés  y tal.

**Comment by mafyata** [comment]
> Yummyyyyy!!
> 
> Any news on the Shelly 2.5 support?
> 
> Btw, I had my first experience with Ravencore flashing a Magic Home LED wifi controller and … "$)( I'm really excited and impressed with the results!! Keep on the hard work, it's really impressive.
> 
> Now waiting for the 2.5, very excited :)

Can you give me your contact like facebook or viber to ask you about magic home flashing with ravencore ?

**Comment by greensouth** [comment]
> > Yummyyyyy!!
> > Any news on the Shelly 2.5 support?
> > Btw, I had my first experience with Ravencore flashing a Magic Home LED wifi controller and … "$)( I'm really excited and impressed with the results!! Keep on the hard work, it's really impressive.
> > Now waiting for the 2.5, very excited :)
> 
> Can you give me your contact like facebook or viber to ask you about magic home flashing with ravencore ?

What do you want to know?

**Comment by mafyata** [comment]
Eve setup options and did you get ir remote working with raven core

**Comment by greensouth** [comment]
> Eve setup options and did you get ir remote working with raven core

I don't have an IR remote, so I never had to configure it. 

In eve I just set:

```
board = 1
device = 14
color boost = 2%
```

(mine is a RGBW controller so had to add the W gpio also -even if it's unused, if not, you will getting unexpected colors):

```
Pin B = 12
Pin G = 5
Pin R = 14
Pin W = 13
```

For GPIO equivalences, I used this pic [https://user-images.githubusercontent.com/29731130/31029735-2f99db9c-a553-11e7-896c-2f71c3d04551.jpg
](url) at [https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-LED-strip-controller](url)

**Comment by mafyata** [comment]
Mine is RGB.
Pin B =13
Pin G =12
Pin R =5
Pin W =0
How check my GPIO equivalences ? Are the same like rgbw , but without W ?
![7A2CF488-3857-4CC5-8C25-248F165CAB6D](https://user-images.githubusercontent.com/48009267/56187750-4db44c80-602c-11e9-8a58-df9813c7afda.jpeg)

**Comment by i3laze** [comment]
Please don’t highjack this dead Shelly 2.5 thread, find or make a new RGBW one.
