### ISSUE TITLE
Revert to Shelly Firmware via OTA

### ISSUE THREAD

**Issue by buarle** [RavenSystem/esp-homekit-devices#2298]
Hi all,

is there a possible way to return to the original firmware via OTA?

It would be very pleasent not to remove the actors from the mounting location...

Thanks and best
Markus

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation#important

https://github.com/RavenSystem/mgos32toHAA?tab=readme-ov-file#warning-there-is-no-ota-way-back-to-shelly-firmware-if-the-new-zip-file-has-been-uploaded
