### ISSUE TITLE
haamain 12.13.3 installation fails

### ISSUE THREAD

**Issue by atus42** [RavenSystem/esp-homekit-devices#2306]
**Detailed steps to reproduce it**
download https://github.com/RavenSystem/haa/releases/download/12.13.3/fullhaaboot.bin
flash it to a D1 mini
let it boot, give it wifi data and watch how it tries to download newer version and eventually fails to boot after downloading and flashing 12.13.3 again.
At first I tried without forcint it to be 12.13.3 (download server) but it failed too. I flashed it two times before went to specific download version.

**MEPLHAA Script**
not relevant in my opinion, but this: 
{"c":{"io":[[[12,2],2],[[4],6],[[14],6,1]],"o":1,"l":2,"i":1,"b":[[14,5]],"n":"my-haa-device","ntp":"148.6.0.1","tz":"HU","ct":5},"a":[{"t":1,"0":{"r":[[12,0]]},"1":{"r":[[12,1]]},"b":[[4,1],[14,1],[14,0]]}]}

**Used device**
D1 mini

**HAA version**
12.13.3

**iOS/iPadOS version**
N/A
**Logs**
[haa_boot_fail.txt](https://github.com/user-attachments/files/17610506/haa_boot_fail.txt)

**Screen-shots or videos showing issue**

**Comment by atus42** [comment]
Starting from 12.13.2 has the same end result. Boot fails.
[haa_boot_fail2.txt](https://github.com/user-attachments/files/17610679/haa_boot_fail2.txt)

**Comment by atus42** [comment]
Cloning files of 12.13.3 locally and setting a local update server results the same boot failure.
Cloning files of 12.13.2 locally and setting a local update server results the same boot failure.
Setting the update server to the github url of 12.13.2 caused an infinite loop because some file download got a 'permanently moved' response (301) and I think it was not handled at all.
Attached the serial output of flashed 12.13.2 version with local clone of 12.13.2 files.
[haa_boot_fail3.txt](https://github.com/user-attachments/files/17610814/haa_boot_fail3.txt)

I don't have more idea how to get this work...

**Comment by RavenSystem** [comment]
All installation logs show perfect installations, without any loop or error. In all cases, HAAMAIN is installed right.
