### ISSUE TITLE
HAA mDNS Status wrongly reports error

### ISSUE THREAD

**Issue by miguelpruivo** [RavenSystem/esp-homekit-devices#2327]
I've described this on Discord, but anyway, the issue happens when you open the HAA app and everything is working as intended on both HAA app and Home app: all accessories respond well, no issues or disconnections, you can enter in the setup mode in everything, etc. but if you open every accessory in the HAA (and go into setup) you see: **mDNS status: error** which is being wrongly reported since if mDNS wasn't working for all accessories, they would be no-response status or/and high latency. It's not the case (HomeBench is also reporting very good scores).

What I found that fixes it, is if I open the logs in the HAA app and go into the mDNS tab, it'll show immediately HAA resolved to IP (for all accessories) and then, if I go back, they all are green showing: **mDNS status: Ok**

So, I assume it must be some minor issue in the app not checking for mDNS before you open the logs? I don't know.

**HAA version**
12.13.3 and 12.13.4

**iOS/iPadOS version**
iOS 18.1 & HAA Manager 3.8.0

**Comment by RavenSystem** [comment]
It is fixed in next HAA Manager version.
