### ISSUE TITLE
Shelly RGBW support

### ISSUE THREAD

**Issue by joemolomo** [RavenSystem/esp-homekit-devices#234]
Hi, has anyone had any luck flashing the Shelly RGBW2 light strip module. I'm struggling to find a light strip module with HomeKit support, any suggestions? Ta

**Comment by RavenSystem** [comment]
Actually, this firmware doesn't support RGB/W lights. It is a TODO task.

**Comment by mmiglier** [comment]
Hi, any update on this? Thanks

**Comment by RavenSystem** [comment]
Fully supported now with RC v1.1.0.
