### ISSUE TITLE
S22 not reading temp

### ISSUE THREAD

**Issue by Nevotic** [RavenSystem/esp-homekit-devices#235]
All I'm getting is a 0,0C reading.

I'm using a S22 with a DS18B20 plugged in through the jack on the bottom of the device. Yet it's not giving any readings. What am I doing wrong?

Board type: 1
Device Type: 9
TH Sensor Type: 3

**Comment by ymyshko** [comment]
Resistor 6-10 kOhm from GPIO14 to 3.3V and you can see temperature.

**Comment by Nevotic** [comment]
I honestly wouldn't know what that would mean. Is it possible to explain it to me in a simple way?
Thank you for your help! I really appreciate it.

**Comment by Nevotic** [comment]
Never mind. I figured it out. It's just the 3.5mm pin didn't connect properly into the port which didn't give it the 3.3V. 

Thanks again! :)
