### ISSUE TITLE
Garage Door not reading sensors on startup

### ISSUE THREAD

**Issue by MrCmonster** [RavenSystem/esp-homekit-devices#236]
Great work on this!
I'm setting up the Garage Door opener on a Sonoff SV. I believe I found a bug in the Garage Door function.

Prerequisite:
The device has both an open and a close sensor correctly configured.

Steps to reproduce:
1. Open the door from HomeKit
2. Once the door is fully open, simulate a power outage by unplugging the Sonoff and plugging it back in
3. Go into the Eve app and refresh the door status

Expected result:
The Sonoff should read the door sensor on startup and see that the door is open.

Actual result:
The Sonoff sends an alert that the door was closed even though it is fully open.

I think the hardware_init() needs to read the current state but I'm not sure how to fix it.

Thanks

**Comment by RavenSystem** [comment]
Yes, sensors are not read on startup. It is necessary to implement it in future updates.

**Comment by pilot1981** [comment]
@RavenSystem  when this feature will be developed?

**Comment by pilot1981** [comment]
Any news?

**Comment by RavenSystem** [comment]
No yet.

**Comment by pilot1981** [comment]
Different question: why I can’t group two garage door together?

**Comment by i3laze** [comment]
You might add a fake switch with a relevant name and hook both doors to it in Automation.
This way I worked around the requirement to unlock an iPhone.

P.S. the only fake switch I know is running HomeBridge alongside. May be new Architect f/w will have one.

**Comment by pilot1981** [comment]
I solved using default apple home kit command: "hey siri, open all doors in garage".

@RavenSystem you can close

**Comment by drakorqs** [comment]
@RavenSystem thank you for your work!
The obstacle sensor also does not keep the last state.
When the obstacle sensor is on, the garage door cannot be opened from the app. (after power off, or reboot)
https://youtu.be/d51Lr62gfmU

**Comment by RavenSystem** [comment]
Done in RavenCore v0.9.0.

**Comment by jat80** [comment]
> Done in RavenCore v0.9.0.

Does this mean If the Sonoff has a power outage or reboots it won't trigger the garage door?  I had a power outage when the door was closed and when it came back on it opened the garage door.  Same happens if I cut power to it manually and turn it on again, it triggers the switch to open the garage door.
