### ISSUE TITLE
Sonoff US T1 2ch not work on buttons pressure

### ISSUE THREAD

**Issue by notedifabry** [RavenSystem/esp-homekit-devices#237]
Hello my Sonoff  T1 R2 US 2ch (V1.0) works remotely from App Homekit, but it does not work by pressing the buttons, neither of the 2 !!
How can I solve the problem ?

Many Thanks :-)

Board Type 1
Device n.2
Ravencore 0.6.1

**Comment by DanielMosco** [comment]
Try to change “external toggle” from ‘0’ to ‘1’. It works on my T1 EU 2 gang.

**Comment by notedifabry** [comment]
hello this weekend I try and let you know ... in the meantime, thank you, very kind :-)
