### ISSUE TITLE
I this thing compatible?

### ISSUE THREAD

**Issue by Moskvitch** [RavenSystem/esp-homekit-devices#238]
https://www.itead.cc/smart-home/inching-self-locking-wifi-wireless-switch.html

**Comment by Partizan7676** [comment]
check TODO list. it will added later.

**Comment by lizzus** [comment]
Yes, this is fully compatible! You can check here: https://www.twibuk.com/post/1090_sonoff-bassa-tensione-micro-usb-5v-oppure-ac-dc-7-32v-con-firmware-ravencore-fun.html
Racencore firmware is the best!

**Comment by pilot1981** [comment]
@lizzus which sonoff type you used? It could be the best choice for my garage door opener!?

DV

**Comment by lizzus** [comment]
@pilot1981 i used this https://www.itead.cc/smart-home/inching-self-locking-wifi-wireless-switch.html
I think this is not the best choice...

**Comment by pilot1981** [comment]
I don’t know...using sonoff basic with device type 8 I have the only option to have switch mode, but I need only button mode to send open command to my garage door (garage door close itself) so sonoff 1 channel inching could solve this problem...

DV

**Comment by GPL71** [comment]
Yes I confirm, fully compatible, and the inching function is preserved even using @RavenSystem firmware.
You'll need soldering wires for TX RX and GPIO0 to allow flashing

**Comment by GPL71** [comment]
@pilot1981 the best board for garage door is Sonoff SV.
I'd used for garage door, and yes it's perfect

**Comment by RavenSystem** [comment]
Solved.

**Comment by pilot1981** [comment]
@GPL71 I agree with you but open sensor isn’t mandatory, obstructed sensor don’t work yet, if you want integrate power supply and you want a cheaper solution SONOFF BASIC remain the best choice...
