### ISSUE TITLE
Power monitoring

### ISSUE THREAD

**Issue by aslater3** [RavenSystem/esp-homekit-devices#239]
Is it possible to add power monitoring functionality? Either via Eve or native HomeKit?

**Comment by oremic** [comment]
chip for shelly 2  power meter MCP39F501.

**Comment by RavenSystem** [comment]
Apple HomeKit doesn't support it, and I don't add other characteristics HomeKit.

**Comment by oremic** [comment]
Apple homekit does not even support customizations and yet you use EVE to do it.

**Comment by RavenSystem** [comment]
I only use custom characteristic to setup accessory. Of course, since this project is open source, you can implement by yourself all options and characteristics that you want.

**Comment by oremic** [comment]
Sorry if I was wrong to ask.
The work you did is very great, six, exceptional.
The function of the power meter would be exceptional, unfortunately I can not write a library.
