### ISSUE TITLE
How to Build RavenCore Sonoff4CH?

### ISSUE THREAD

**Issue by 88adong88** [RavenSystem/esp-homekit-devices#24]
Where should I change?

**Comment by RavenSystem** [comment]
Sorry, I need free time to write user manual in Wiki.

You don't need to rebuild nothing. For your case, install ElGato EVE App from AppStore and use it to manage RavenCore config. Show setup and then change "device type" to 4, and restart it. Close ElGato EVE, wait for Sonoff to boot again, and now you will see 4 switches.

**Comment by royfocker19** [comment]
Hi, Quick question, how do you make it posible to your accesory to be discoverable by ElGato EVE app?
