### ISSUE TITLE
Reset and lose possible reconnect Shelly1 v3

### ISSUE THREAD

**Issue by koleox90** [RavenSystem/esp-homekit-devices#244]
Hi, 

I have problem with Shelly1 V3.

I have large house and when moving Shelly to another part of house i want change Wi-Fi router. When i set board type on 3 for AC230, and i make a reset Wi-Fi on EVE, lose everything. I must flash firmware again.

How to fix this issue?

**Comment by GPL71** [comment]
It's very strange 
I have a large house too and 12 shelly.
I moved them and they work great even when I'd reset wifi

how do you set eve?

**Comment by koleox90** [comment]
Maby i do something wrong? 

That my eve setings. 
![c9342f0d-b4b0-4371-993a-8edcf247912f](https://user-images.githubusercontent.com/46854168/52666832-9c037d00-2f0f-11e9-8cbd-2a0c3b167f53.png)
![67574031-1a71-4ecc-aeb7-56b0dc1aeccf](https://user-images.githubusercontent.com/46854168/52666837-9c9c1380-2f0f-11e9-9745-945c770bf161.png)

**Comment by GPL71** [comment]
set external toggle 2
log 0

do it by ftdi 3.3v ... after connect to 230vac

**Comment by koleox90** [comment]
Thanks, I try this settings.
