### ISSUE TITLE
Button 1 of  SONOFF dual

### ISSUE THREAD

**Issue by kalety** [RavenSystem/esp-homekit-devices#245]
Hi!, I'm "Ravencorized" a Sonoff dual R2. I've used Board type 4, device type 2, external toogles 1 and 2 to type 2. Connect to RX/GND the switch 1 and button1/gnd the second. The first works flawlessly (RX/gnd), the second (button1/gnd) only responses the first time if it's off, the switch turn on, but don't turn off. I'm test the button1 with a button (type 1), and nothing. The pins are ok, because I test it with sonoff tasmota and works well.

Thank you

**Comment by RavenSystem** [comment]
Sorry, it is a bug that I found in the code just now. Thanks for your feedback. Next version will fix it, and soon.

**Comment by kalety** [comment]
Thank you very much! (Haa?, ;)))

**Comment by RavenSystem** [comment]
Fixed in 0.6.2.
