### ISSUE TITLE
Garage Door icon animation with neverending flywheel 

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#247]
@RavenSystem
Hello, I have a little problem on the icon animation of garage door.
After tap the garage door icon in the HOME APP the animation starts but never stops.
I see a neverending flywheel
In EVE I have setted the WORKING time and the TAP time and rebooted.
I have no the magnetic contact for completly opening

Any suggestion? 

Thank you

**Comment by Waniaok** [comment]
for closed status attached door closed sensor to GPIO14/GPIO2 (Board type 1 or 2).

**Comment by RavenSystem** [comment]
This can be the same cause of: https://github.com/RavenSystem/esp-homekit-devices/issues/229

**Comment by RavenSystem** [comment]
Same cause of: 
https://github.com/RavenSystem/esp-homekit-devices/issues/229
