### ISSUE TITLE
Question - DS18B20

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#248]
Hi,
anyone use the latest firmware with DS18B20 sensor?
I tested with DHT22, works perfectly, but DS18B20 shows 0,0 celsius. 
Would be the sensor defect?

**Comment by MrCmonster** [comment]
Someone asked this before and it was responded to with:

> Resistor 6-10 kOhm from GPIO14 to 3.3V and you can see temperature.

I don't have a DS18B20 to test with, but this seems reasonable. At the worst it will not hurt anything to try it.

**Comment by yusufd1** [comment]
Yes you need that resistor between 3.3v and the GPIO. Mines works.

**Comment by claire078** [comment]
Thanks. I’ll try it. 👍
