### ISSUE TITLE
Auto mode for thermostat

### ISSUE THREAD

**Issue by Partizan7676** [RavenSystem/esp-homekit-devices#249]
As i understand it is disabled. Why? Using automation i can start secondary heater or airconditioner. Logic is simple - for desired temperature we can start heating or cooling with automation just create two scenario for each states - heating(heating on and off and include to it all needed heaters) and for cooling(cooling on and off).

**Comment by RavenSystem** [comment]
Auto mode needs a device with 2 relays: one for heater, and another for cooler.
