### ISSUE TITLE
How to set temp higher than 38C in TH10 with DS18B20 ?

### ISSUE THREAD

**Issue by dimm72** [RavenSystem/esp-homekit-devices#251]
I need to control temp of hot water - set desired temp from 30C to 70C. Is it possible with Sonoff TH with DS18B20?   Now i can only set "Heat to 38C". How to set desired temp to 70C ?

**Comment by RavenSystem** [comment]
Actually, it is impossible.

**Comment by Partizan7676** [comment]
May be using offset with thermostat ?
