### ISSUE TITLE
Shelly1 disconnect 

### ISSUE THREAD

**Issue by gioz73** [RavenSystem/esp-homekit-devices#252]
Hi, I have 4 shelly1 with ravencore 0.6.1 work well but every 3/4days disconnect from network (all together). If I turn off and on the general power work well for other 3/4 days.
Any idea?
Thank

**Comment by i3laze** [comment]
Same here.
Today it’s Shelly2 unresponsive. Troubleshooting steps?

**Comment by RavenSystem** [comment]
Logs, please.

**Comment by Fussverkehr** [comment]
I have the same issues with the shelly 1 and the fritzbox wlan. how can i generat the log files?

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#capture-logs

But for sure it is a wifi network related issue.

**Comment by peros550** [comment]
Do you have Apple TV used as hub? If yes, try rebooting it (keeping the router and Shelly devices on) and advice if the issue cleared. I had a similar situation last week where all my Ravencore devices were in no response status. Rebooting Apple TV brought them back.

**Comment by Fussverkehr** [comment]
The restart of the appleTV help in my case.

**Comment by gioz73** [comment]
Reboot of AppkeTV don’t work for me
