### ISSUE TITLE
problem with sonoff basic R2 cutted tracks in garage opener scenario

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#254]
Hi,
I'm trying to use a sonoff basic R2 cutted tracks in garage opener scenario with raven core 0.6.1 but with device type 1 don't saw timer and other useful setting in EVE app (as written in wiki). Then I changed setting to device type 10 but I lost device and reset don't helped me to take again control of sonoff.

So I have two questions:
- how I can take again control of sonoff? erase flash and program it again?
- which is the right device type to use in my scenario?

regards

**Comment by pilot1981** [comment]
there is a matrix where find association between device type number and commercial product (sonoff, shelly, ...)?

**Comment by GPL71** [comment]
is device 7 garage door

**Comment by GPL71** [comment]
check the wiki

**Comment by pilot1981** [comment]
it isn't device type 8? also for sonoff basic R2 with cutted tracks?

**Comment by dvelardi** [comment]
Solved with device type number 8.

If I have garage door close itself using internal timer, with closed sensor on GPIO2 and without opened sensor: which is right configuration in EVE?

DV

**Comment by pilot1981** [comment]
@GPL71 wiki isn't so clarifying for me... If I have garage door close itself using internal timer, with closed sensor on GPIO2 and without opened sensor I need to reset button automatically, I need to obtain this result:
1. initial state: closed
2. manually push button/switch: state change to open
3. automatically reset button/switch and state

I don't need of a switch ON/OFF: I need only a button to push to open a garage...I don't understand howto to come back automatically the switch/button on home app to initial state (closed)....

you know if open sensor feature it's already developed? work fine? in this case I could decide to use a SONOFF SV with more GPIO...

**Comment by GPL71** [comment]
I'd use sonoff SV ...
however by EVE you need to set the follow 2 timers

1 duration of push button in HOME APP to lunch the opening
2 working time to open completly the door

Garge door (device 8) has a little bug.
1 is about animation icon
the second about voice control by siri. you need say hey siri open garage door even if you want close the gate

but surely @RavenSystem will correct it

**Comment by pilot1981** [comment]
my garage door close itself, I don't need close command... howto you configure other options of stop step and close sensor, for me wiki isn't so clear...

@RavenSystem I ask to you:

- create more clear wiki for duration timer, close and open contact
- how I can configure device 8 in my case? I don't need open command...my garage door already close itself...

**Comment by RavenSystem** [comment]
@pilot1981 I think timers are explain well in the wiki. Problem is that there is not a timer for auto-closing feature. In your particular case, you must use a Sonoff SV with close and open sensors. 

@GPL71 I will fix bugs asap. I hope this weekend.

**Comment by pilot1981** [comment]
so, If I use a SONOFF SV, I have to:
- attach close sensor to GPIO14 (it's NC when garage door is closed)
- attach open sensor on GPIO4 (It's NC when garage door is opened)
- config Sensor Close to ON=NC
- config Sensor Open to 2=NC
- config Working Time 240 seconds is the time to open and close garage door itself

If I send open command in apple home app, after 240 seconds are spent, switch in apple home app return to closed state and only now I can send a new open command?

it's all right? I understood well?

**Comment by GPL71** [comment]
@RavenSystem ... Thank you !!! you're a great. Please note that I discovered a second bug. I'd wrote
@Pilot1981 The SV is the best choice.... But if you have a door with autoself closing and logic board to manage safety of door (we have this systems in Italy e.g.) the basic with dry contact is enough for you....
This my opinion

**Comment by pilot1981** [comment]
I agree, but I don’t understood howto transform Apple home app switch closed-open to a button only-open....

DV

**Comment by RavenSystem** [comment]
* Working Time is the time necessary to open the door completely from a fully close status. It does not make sense if an open-sensor is used.

**Comment by pilot1981** [comment]
but i apple home app I can have a button with only open command, without close command?

**Comment by pilot1981** [comment]
So, when close sensor confirm garage door closed, the switch in Apple home app turn again to initial closed state?

**Comment by dvelardi** [comment]
@RavenSystem

Today using SONOFF BASIC R2 cutted tracks, I found best config for my project; you can find here:










But I found a strange behavior:





When close sensor send signal, Apple home app remain opening state (wrong) and EVE app change state to close (right state).

It’s a bug?

Using SONOFF BASIC, opened sensor signal came from GPIO2? The same of closed sensor?

I don’t think using SONOFF SV I can solve this issue...


DV

**Comment by RavenSystem** [comment]
Open sensor comes always from GPIO4, and close sensor from GPIO14/GPIO2 (Depending of board type): 
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#8-garage-door

**Comment by pilot1981** [comment]
@GPL71 you modified SONOFF SV removing resistor? You can share your electric schema? It’s very useful for me!



DV

**Comment by pilot1981** [comment]
@RavenSystem
Thanks for reply, but you don’t answer on inconsistent state between Apple home app and EVE app: you have an answer for me?

DV

**Comment by dvelardi** [comment]
@RavenSystem

I have this issue: when I send open command, Apple home app show garage door always in opening state and if I ask Siri which it’s the state of garage door, Siri say don’t know...

DV
3389305149<tel:3389305149>

link - PRIVACY POLICY. http://www.meadinformatica.it/privacy/

Il giorno 25 feb 2019, alle ore 23:29, pilot1981 <notifications@github.com<mailto:notifications@github.com>> ha scritto:

@RavenSystem
Thanks for reply, but you don’t answer on inconsistent state between Apple home app and EVE app: you have an answer for me?

DV

**Comment by pilot1981** [comment]
@RavenSystem close sensor seem not work for me on SONOFF basic; if I ask garage door status, Siri always respond always closed...I attached magnetic contact to GPIO2 and GND...it's a bug?

**Comment by dvelardi** [comment]
@RavenSystem I understood the problem: I’m using SONOFF BASIC R2: I suppose GPIO2 don’t work with your firmware because it’s different from GPIO14 of SONOFF BASIC R1

You agree?

You have a solution for me?

I can use RX pin to connect close sensor?

**Comment by RavenSystem** [comment]
Please, read the Wiki.

**Comment by pilot1981** [comment]
sorry, I didn't understand...where is my error? please explain...

**Comment by RavenSystem** [comment]
From the Wiki:

<img width="1029" alt="captura de pantalla 2019-02-28 a las 21 55 49" src="https://user-images.githubusercontent.com/8655274/53597957-c443da80-3ba3-11e9-83d7-0d3744800931.png">

**Comment by pilot1981** [comment]
you're right! thanks 

sonoff new board = sonoff basic R2

I go soldering right pin ...and try again

**Comment by pilot1981** [comment]
Ok, magnetic sensor now is attached to GND and GPIO3/RX, but EVE and Apple home app always say garage door is closed...what else it’s wrong?

**Comment by pilot1981** [comment]
@RavenSystem New issue in 0.6.2: first time you push button relay start, the second time relay don’t work...only led flash

**Comment by pilot1981** [comment]
@RavenSystem In 0.6.2 I notice a new strange behavior: when I push button first time relay start, when I push button second time relay don’t start and led flash...it’s expected behavior or a new bug?

**Comment by pilot1981** [comment]
@RavenSystem for sonoff basic R2 (new layout) I have to use always board type 1? I also tried 2, 3 and 4 but this don't solve my issue on close contact...

**Comment by pilot1981** [comment]
@RavenSystem sorry. I answer myself: I have to use board type 4!!!!

**Comment by pilot1981** [comment]
@RavenSystem happy news! All work fine!!! Thanks a lot for your help!

Your firmware is fantastic: great job!
