### ISSUE TITLE
request new feature to control roomba irobot without scheduler

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#256]
Hi,
I would ask to implement a new type of device type compatibile with roomba irobot to implement these features:

- schedule start to clean in the time (not all roomba robot have it)
- know status (charging, cleaning, stopped, ...)
- request to return to dock station
- control movements (in the future only for fun ;-)

you could connect ESP8266 to serial port of roomba irobot: I found many example on internet..

let me know

regards

**Comment by RavenSystem** [comment]
From the wiki:

> This work is focused on specific devices, like several Sonoff and Shelly devices. Any suggestion is welcome, but only official Apple HomeKit characteristics will be considered (Those that work with stock Apple Home App), and custom HomeKit characteristics that use third-party Apps will be rejected.

**Comment by pilot1981** [comment]
yes, I would control roomba using apple home kit....

**Comment by i3laze** [comment]
HomeBridge has this plugin (or even two):
https://github.com/AlexanderBabel/homebridge-irobot-roomba

Unless you gonna were Sonoff/Shelly to iRobot, that’s the wrong thread.

**Comment by pilot1981** [comment]
I don’t want use homebridge...

DV

**Comment by AramVartanyan** [comment]
It is using sample Switch services with Battery status and some local logic. The switch is named iRobot and that’s it.
Good idea! 👍🏻

**Comment by peros550** [comment]
Is it based on a esp8266?

**Comment by pilot1981** [comment]
@AramVartanyan can you explain better your idea?

**Comment by AramVartanyan** [comment]
It is not my idea. My curiosity took me inside this code:
https://github.com/AlexanderBabel/homebridge-irobot-roomba/blob/master/index.js
and I just share what I found inside. I believe it is worth a try.
But maybe it will be hard to do it with RavenCore. You will need custom code for it.

**Comment by pilot1981** [comment]
@AramVartanyan you think it’s possibile use part of code of @RavenSystem and ESP HOMEKIT library to control iRobot roomba?
For me it’s sufficient have scheduler, start and Dock feature...
I don’t want add an homebridge...
I think to use ESP01 and buck converter to install onboard irobot roomba...
@RavenSystem we can use your code?

**Comment by RavenSystem** [comment]
> @RavenSystem we can use your code?

You can read license terms here: 
https://github.com/RavenSystem/esp-homekit-devices/blob/master/LICENSE
