### ISSUE TITLE
Shelly 1 Impulse

### ISSUE THREAD

**Issue by apacherg** [RavenSystem/esp-homekit-devices#257]

**Comment by apacherg** [comment]
CAN YOU HAVE AN IMPULSE MODE?

**Comment by apacherg** [comment]
Come settario per impulso ?

**Comment by gijsstegehuis** [comment]
Hi @apacherg,

This issue will probably help you out: https://github.com/RavenSystem/esp-homekit-devices/issues/202

**Comment by apacherg** [comment]
Non funziona

**Comment by lizzus** [comment]
@apacherg better solution using sonoff low voltage (5v or 7-32v).

**Comment by gijsstegehuis** [comment]
@lizzus a Sonoff is not safe to use within a wall socket.

**Comment by lizzus** [comment]
@gijsstegehuis yes, it's true if we talk about high voltage sonoffs. But i suggest low voltage Sonoffs. 
Some compatible models are sold with a cover and the PCB is not exposed. (Emylo is one of these)
