### ISSUE TITLE
ESP-01 connected with relay

### ISSUE THREAD

**Issue by lizzus** [RavenSystem/esp-homekit-devices#259]
Hi, I sucessfully flash a ESP-01S (egual to ESP-01 but with 1MB mem) with Ravencore firmware and add to Home app. I also configured it with EVE app. 
I tryed to use without any relay but connecting a button to GPIO0 and GND no response on app. I also tryed to connect to a relay pcb (like this pic https://ibb.co/F6KpB51) but not work. Any suggestion?

**Comment by ymyshko** [comment]
Connect ESP01 to UART and start app like Putty.
Connect to port and you can see what happen.
Default device type 1. ESP01 have to work. Without relay.
If you don't see anything, you have bad UART device.

**Comment by lizzus** [comment]
ESP01 work without relay, but if I connect to relay not work.

**Comment by yukonx** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#board-type-default-1

GPIO0 and GPIO2 must be free or high in order to let ESP device to boo

**Comment by lizzus** [comment]
So what can I do?

**Comment by peros550** [comment]
Maybe a resistor between Vcc and GPIO0 or GPIO2 would make them see High voltage during boot up. If that's not messing up with your rest design.

**Comment by lizzus** [comment]
I’ll try

**Comment by yukonx** [comment]
https://ibb.co/52g3JQ6

I am replacing I/O

**Comment by lizzus** [comment]
I wait your response.

**Comment by ymyshko** [comment]
> So what can I do?

ESP01 have two gpio0 and gpio2 pins.
gpio0 connected to relay. But gpio0 and gpio2 must be high when esp boot. 
You can do az yukonx - replace gpio0 to gpio12 on ESP01
or replace on your relay board gpio0 to RX and recompile project.

**Comment by RavenSystem** [comment]
Please, read "board type" and "device type" in the Wiki.

**Comment by lizzus** [comment]
@RavenSystem I don’t understand what do you mean...

**Comment by RavenSystem** [comment]
Device type:
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#10-esp01-switch--button

Board type: 
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#board-type-default-1
