### ISSUE TITLE
Sonoff basic as momentary relay for doorbell

### ISSUE THREAD

**Issue by overflywingo** [RavenSystem/esp-homekit-devices#263]
Hi 

It is possible to configure a Sonoff Basic for a Doorbell ? 
 I mean connecting GND & GPIO14/2 to the doorbell push button and a momentary power (1 second) for the bell ringing ? 
Perhaps possible via Garage door option ?

**Comment by gijsstegehuis** [comment]
@overflywingo did you try [device type 3: Socket + Button](https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#3-socket--button) ?

**Comment by RavenSystem** [comment]
https://appleinsider.com/articles/18/07/18/apple-purges-doorbell-category-from-homekit-accessories-page

**Comment by AramVartanyan** [comment]
That is not exactly true.

**Comment by gijsstegehuis** [comment]
@RavenSystem It's removed from the page, but not from the HomeKit framework.
The [Netatmo HomeKit compatible doorbell](https://www.netatmo.com/en-gb/security/doorbell?force_locale=en-gb) is coming soon.

**Comment by RavenSystem** [comment]
Netatmo is going to release a video doorbell. It is not the same.

**Comment by AramVartanyan** [comment]
The only limitation is that the doorbell characteristic shell be used as an addition to another service. A switch for example, or a button, or a security system, or whatever you like.
It cannot be a stand-alone service.

**Comment by RavenSystem** [comment]
@AramVartanyan Exactly, I am working on a lock mechanism and I will try to incorporate a doorbell characteristic, but that is not a doorbell accessory. Only video doorbells accessories are allowed.

**Comment by AramVartanyan** [comment]
Yes! You are absolutely right!

**Comment by RavenSystem** [comment]
Supported in v0.8.2.
