### ISSUE TITLE
ESP-01 GPIO0 and GPIO2 config.

### ISSUE THREAD

**Issue by lizzus** [RavenSystem/esp-homekit-devices#265]
@RavenSystem I'm using a ESP-01S connected to a relay (relay v.4) with latest firmware. In your guide you write "For ESP01 with a button connected to GPIO0 and a relay connected to GPIO2". Actually my config is:
- Board Type = 2
- Device Type = 10
- Reverse SW1 = Yes (because with "NO" is inverse)
But i think is GPIO0 connected to relay and GPIO2 connected to a button". 
I checked and this is correct config. What do you think?

**Comment by RavenSystem** [comment]
From [Board Type](https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#board-type-default-1):

> 2. Sonoff new board layout: Uses GPIO2 instead GPIO14. Device type 10 has swapped relay and button GPIOs.

So, try Board Type 2 instead.

**Comment by lizzus** [comment]
Did you read what I wrote??? I’m using device type 2!!!!!! 
Correct configuration is GPIO connected to relay and GPIO2 connected to button!!!!
You must correct your wiki

**Comment by RavenSystem** [comment]
Wiki is right:

> With Board type 1 (Default):
> Button connected to GPIO0 and relay connected to GPIO2.

> With Board type 2:
> Swapped button and relay GPIOs: Button connected to GPIO2 and relay connected to GPIO0.

**Comment by netRunner0** [comment]
Board type 1/2 and device type 10 for esp01 do not work for me
How can I set up a lock in HAA on gpio0 or gpio2?

**Comment by RavenSystem** [comment]
What do you want to connect on GPIO0 and GPIO2?

**Comment by netRunner0** [comment]
![IMG_0172](https://user-images.githubusercontent.com/44049295/67164452-16847680-f394-11e9-8220-fb172f60b862.jpeg)

**Comment by netRunner0** [comment]
GPIO0

**Comment by lizzus** [comment]
model you posted idn't compatibile, because not use GPIO 0 and 2!

**Comment by netRunner0** [comment]
> model you posted idn't compatibile, because not use GPIO 0 and 2!

What does she use? There are only 2 GPIOs that go to the relay board

**Comment by netRunner0** [comment]
![IMG_0173](https://user-images.githubusercontent.com/44049295/67164839-138b8500-f398-11e9-9fee-5c45116cc465.png)

**Comment by lizzus** [comment]
this model is full compatible with Ravencore:
![IMG_9165](https://user-images.githubusercontent.com/8824834/67164835-e9799900-f37e-11e9-8c0d-7ed9ac13cba6.JPG)
![IMG_9164](https://user-images.githubusercontent.com/8824834/67164836-ea122f80-f37e-11e9-9863-c48b1b018d21.JPG)
Check version: v4! v1 is not compatible.

**Comment by netRunner0** [comment]
For this relay, you must use:
serial.write

instead

gpio.write

**Comment by RavenSystem** [comment]
Serial control is not supported.

**Comment by netRunner0** [comment]
Relay in the trash?
