### ISSUE TITLE
Lets support @Ravencore with HW for his new developments and testings!

### ISSUE THREAD

**Issue by seritos** [RavenSystem/esp-homekit-devices#272]
Hi All,

For all of those who know about Ravencore, will understand that thanks to this incredible software, we are able to use accessories with homekit for almost a ridiculous amount of money. 
Many of us have introduced into the world of home automation due to the ease of use and have been satisfied with its performance.

I know firsthand, that he is just about release a version that will suppot the window covering and door, this is, the long-awaited version  for the roller shutters!!

Is because of this new release in combination with the future FW (HAA), that I am reminding some support for him with some HW that he published on the Ravencore WIKI section (at the bottom of the page), that will directly take you to the amazon website ( http://amzn.eu/02wuKCg) to be sent to him. ...He is specially interested in Shellys... ;) !!

There is also a PayPal account were you can kindly donate any amount you consider: 

https://paypal.me/ravensystem

Thanx for your consideration!! :) 

Thanx!

**Comment by GPL71** [comment]
I agree with you 
@RavenSystem is doing the best and great free work available at moment
And I think that buy Hw form its link is a little efforts for us.

Than boys lets go using the link above becausa @RavenSystem had realized our dreams about domotica

**Comment by apacherg** [comment]
Raven you're the number one ... Thanks

**Comment by seritos** [comment]
Window rolling Shutter supported version published!!

**Comment by GPL71** [comment]
@RavenSystem
Another great work with the support to device 12!!!
Thank you!!!

Please add Amazon links from italian store and I'll forward to our italian facebook page.

**Comment by St0nehead** [comment]
Would be great if @RavenSystem adds Sonoff SC support..

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seritos** [comment]
@St0nehead
This is a thread to help ravencore and supporting him as a reminder :) 

Thanx for understanding

**Comment by RavenSystem** [comment]
@St0nehead Can you provide an email address, please?

**Comment by St0nehead** [comment]
St0nehead999(at)gmail.com

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RavenSystem** [comment]
@St0nehead did you receive my email?

**Comment by St0nehead** [comment]
Yes! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by awasspl** [comment]
@RavenSystem - Can I have the English version of "Your amazon wish list"? I can not understand how to buy anything:)

**Comment by seritos** [comment]
@awasspl

You can also donate trough PayPal.

https://paypal.me/ravensystem

**Comment by awasspl** [comment]
Yes, but i always think that paypal charges the fee.

**Comment by seritos** [comment]
I dont think it does. Have a try!

**Comment by GPL71** [comment]
Added the PayPal link in the page of our Italian Facebook Group
If the user choose 'send money to' then no fees are added to RavenSystem.

**Comment by awasspl** [comment]
Just send it, hope all is on You're account :)

**Comment by topzoe** [comment]
Hello José,
I sent you a donation on PayPal 😉 for your great  job.
Lilian PAYET.

**Comment by GPL71** [comment]
@RavenSystems Josè 
Are arriving donation from Italian Group?
We remind it to all users

Did you receive emails from me?
We would like share something with all user of community
