### ISSUE TITLE
(GARAGE DOOR) Keeping the current push button control operational

### ISSUE THREAD

**Issue by overflywingo** [RavenSystem/esp-homekit-devices#275]
HI 
I just received my Sonoff SV to use with my garage door.
My garage door is for now controlled with a simple push button .. and despite the fact that I'll put a Sonoff SV, I would like to keep that button operational.  

Where do I have to connect the 2 wires of the push button the Sonoff ? It's a bit unclear to me.

**Comment by RavenSystem** [comment]
You can keep your current push button. That is the idea. You must connect 2 wires of your button to isolated Sonoff relay, keeping your current push button connected to the garage door driver too.

**Comment by overflywingo** [comment]
Thank you, I understand that is in parallel. Right ?

Can you tell me onto witch pin of the Sonoff SV I have to connect the 2 wires of my button ?   In +  ? In - ? Out + ? Out - ? Or elsewhere ? 
Sorry for my ignorance

**Comment by overflywingo** [comment]
Hello

Can someone validate my shema  ?

**Comment by RavenSystem** [comment]
In+ and Out+ , in isolated mode.

**Comment by RavenSystem** [comment]
@overflywingo your layout is right.

**Comment by topzoe** [comment]
Very good layout! 
Thank's a lot!

> Hello Can someone validate my layout ? ![image](https://user-images.githubusercontent.com/47329193/54074838-d99dc080-4297-11e9-9c03-d6d0f8f40e4c.png)
> […](#)

**Comment by GPL71** [comment]
@overflywingo
Can I use it too in my Facebook page?
Me and @lizzus have an italian Facebook page dedicated to Ravencore firmaware and I translated Jose's wiki adding a my picture of sonoff SV.
This one is better

**Comment by pilot1981** [comment]
@GPL71 please post your facebook URL page?

**Comment by overflywingo** [comment]
@gpl71. Of course you can use it onto your FB page 😀




Le 11 mars 2019 à 11:44:51, pilot1981 (notifications@github.com) a écrit:

**Comment by lizzus** [comment]
This is not a page, but a group. We talk about HomeKit devices and firmware. Link is: https://www.facebook.com/groups/homekititalia

**Comment by jat80** [comment]
@overflywingo I'm having issues with my Sonoff SV and garage door setup issue is here:

https://github.com/RavenSystem/esp-homekit-devices/issues/428

How is your SV going?  I only have GPIO14 close sensor and not the open one but as you can read from above issue, it's not working properly.
