### ISSUE TITLE
Device 12: can be minimal time opening or closing less then 3sec ?

### ISSUE THREAD

**Issue by ymyshko** [RavenSystem/esp-homekit-devices#282]
It is the best update. Many thanks 👍 
I use device 12 to open electromagnetic lock. It work with impulse 3 sec.
But 1 sec is enough to open lock.

**Comment by RavenSystem** [comment]
No, sorry. Dev 12 is focused on window coverings, doors and windows. Wait for dev type 13, it is a lock mechanism accessory.
