### ISSUE TITLE
lock mechanism on garage door

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#285]
Hi,
different questions:
- in ravencore firmware, obstruction and open sensor are already operational?
- it's possibile attach to SONOFF SV to manage electromechanical lock mechanism?

**Comment by RavenSystem** [comment]
> in ravencore firmware, obstruction and open sensor are already operational?

Yes. 

> it's possibile attach to SONOFF SV to manage electromechanical lock mechanism?

Yes, but better wait until device type 13 is released.

**Comment by RavenSystem** [comment]
Dev type 13 released just now: 
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#13-lock-mechanism

**Comment by pilot1981** [comment]
Thanks for update and great job!

So if I would use garage door with lock mechanism you suggest to use sonoff SV with device type 7 together ESP01 with device type 13? How I can manage interaction/order to act between both devices?
