### ISSUE TITLE
1 boot after ota flash

### ISSUE THREAD

**Issue by riddik14** [RavenSystem/esp-homekit-devices#29]
When I connect with iPhone to sonoff after flashing, it show WiFi ssid near me. When I select a ssid and type a password it select always last ssid. After more page refresh I success to connect. Is a rboot.bin problem o my phone?

**Comment by RavenSystem** [comment]
I can not answer, because both characteristics are not mine.
- Wifi config: https://github.com/maximkulkin/esp-wifi-config
- OTA System: https://github.com/HomeACcessoryKid/life-cycle-manager

But I have not any issue. Wifi config and OTA system work fine for me.

**Comment by riddik14** [comment]
I’ll try with a android device for 1th boot

**Comment by RavenSystem** [comment]
Any new about that?
