### ISSUE TITLE
Proble

### ISSUE THREAD

**Issue by blackwalkerhd** [RavenSystem/esp-homekit-devices#293]
Problem with sonoff one channel, this one:
https://www.amazon.it/dp/B071ZXJZS2/ref=cm_sw_r_cp_api_i_Ew0JCb6AZYFJG

Firmware flashed ok, the one with no OTA.
Using app homekit. Searching for the ravencore-xxxxx take a lot of try and a lot of time and not always find it... last time take me about 40 min of try and i leave ... only one time find it, but when the app was finish the parring got error. Flashed again, same issue

**Comment by blackwalkerhd** [comment]
Someone use the same sonoff model and flashed fine? 
If yes witch firmaware and now do you flash it?
Suggestions?

**Comment by blackwalkerhd** [comment]
Sad no one is around :(

**Comment by RavenSystem** [comment]
Logs, please.

**Comment by blackwalkerhd** [comment]
Hi Raven, used ububtu to flash it. which log do you need? Tell me which one and i’ll try to get it as soon as possible, thanks a lot! :)

**Comment by RavenSystem** [comment]
Erase and flash it again, try to setup it again, save entire log in a TXT file, and attach it here.

**Comment by blackwalkerhd** [comment]
Ho well, i’ll do it tomorrow moorning! 
I live in italy and i like a lot your software! 
meanwhile I will see how and where to get the log file

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#capture-logs

**Comment by blackwalkerhd** [comment]
hi i write:
screen /dev/ttyUSB0 115200

blanck screen and nothing else....
trying to figure how capture the log...

**Comment by blackwalkerhd** [comment]
[hardcopy.log](https://github.com/RavenSystem/esp-homekit-devices/files/3000788/hardcopy.log)
maybe i do it, can you check if i do it correctly?
thank a lot :)

**Comment by RavenSystem** [comment]
That is your flash log. It's ok.

Now do it:
1.  Disconnect your device
2. Write `screen /dev/ttyUSB0 115200` but don't press enter key.
3. Connect your device and hit enter.

**Comment by blackwalkerhd** [comment]
I capture  the log after writing the comand “screen” i press Ctrl+a and N

I have only to connect the device, type command and hit enter?

**Comment by RavenSystem** [comment]
Connect the device, but don't flash it again.

**Comment by blackwalkerhd** [comment]
done say screen is terminating

**Comment by blackwalkerhd** [comment]
done again blank screen

**Comment by RavenSystem** [comment]
I don't know where is the problem.

**Comment by blackwalkerhd** [comment]
Disconnect your device
Write screen /dev/ttyUSB0 115200 but don't press enter key.
Connect your device and hit enter.

now i have blank screen with cursor up blinking

**Comment by blackwalkerhd** [comment]
ok i close the system if you dont have idea, i can try again by myself and see how it go

**Comment by blackwalkerhd** [comment]
thx anyway man :)

**Comment by RavenSystem** [comment]
It seems that device is not sending data to UART.

**Comment by RavenSystem** [comment]
Can you send a photo?

**Comment by blackwalkerhd** [comment]
Sure, i’ll do later, its time to sleep for me, as i do it i’ll post it! Thx a lot ;)
