### ISSUE TITLE
Is this switch supported?

### ISSUE THREAD

**Issue by 400HPMustang** [RavenSystem/esp-homekit-devices#294]
Sorry for what may be a redundant question, but is the switch linked below supported by RavenSystem? and if so, do I need anything else to flash it or can it be done over USB or wifi?

https://www.itead.cc/inching-self-locking-wifi-wireless-switch.html

**Comment by GPL71** [comment]
yes just tested .... inching function work too

**Comment by pilot1981** [comment]
which device type we have to use for it? device type 10?

**Comment by 400HPMustang** [comment]
> yes just tested .... inching function work too

Does this require additional hardware to flash? or can I do it wirelessly or just hook it up to USB?

> which device type we have to use for it? device type 10?

I believe so. Using it as a wifi enabled button to garage door in a fashion similar to the wired garage door button.

**Comment by GPL71** [comment]
@400HPMustang @pilot1981
- Use device 1
- you'll need to solder 2 wires on the esp for TX and RX. type 1 channel self/inching in internet an you'll find image
- you'll need a FTDI and ravencore  firmware

Remember pressing button on the board you'll have inching or switch function
