### ISSUE TITLE
Multiple sensors support (Motion, occupancy, leak, alarm...) Dev type 15

### ISSUE THREAD

**Issue by topzoe** [RavenSystem/esp-homekit-devices#298]
Hello José,
is it possible to make a new device like a motion sensor that pushes a notification triggered by a digital input?

Like there: http://www.kevindarrah.com/wiki/index.php?title=TrigBoard

Regards

**Comment by RavenSystem** [comment]
Yes, of course. I want to add those kind of accessories, but I need more free time to code.

**Comment by RavenSystem** [comment]
Planned for version 0.9.0.

**Comment by topzoe** [comment]
Great ! 👍🏾😁

**Comment by peros550** [comment]
Guys you have amazing ideas!

**Comment by GPL71** [comment]
@RavenSystem Hi Josè
it possible build the device with follow choose and boards

BOARDS
NODE MCU
For more sensors in a single board 
You can set number and type of sensors by EVE setup
You can set or no an output for ralay

ESP 01
You can set only on sensor type by EVE setup
You can set or no an output for ralay


LIST OF SENSORS
Motion
Occupancy
Leak
Alarm
Anemometer
Rain sensor (only yes or no)

What do you think?

**Comment by RavenSystem** [comment]
RC will not get this finally. HAA will do it.

**Comment by pilot1981** [comment]
We wait for HAA feature...

Using RC, We can use sonoff basic with dummy switch and only sensor connected to GPIO?
