### ISSUE TITLE
Add pressure/temp sensor

### ISSUE THREAD

**Issue by riddik14** [RavenSystem/esp-homekit-devices#30]
Can you add bmp085 bmp180 sensor.

**Comment by RavenSystem** [comment]
Apple HomeKit have not support for pressure sensor. I could be added using third party HomeKit Apps, but it will be a new accessory.

**Comment by riddik14** [comment]
But from eve is read

**Comment by RavenSystem** [comment]
Yes, as I have said, using a third party App (like Elgato EVE). I marked this issue as enhancement, so it is possible to add support to pressure sensor in a future, but my time for coding is limited, and there are others features that I want to add first, such as garage door opener. I will buy a pressure sensor, but not for now.

**Comment by RavenSystem** [comment]
UUIDs for Elgato EVE devices: https://github.com/ebaauw/homebridge-lib/blob/master/lib/EveHomeKitTypes.js

**Comment by RavenSystem** [comment]
@riddik14 Have you any pressure sensor?

**Comment by riddik14** [comment]
Bmp085

**Comment by RavenSystem** [comment]
I am waiting a BMP280 sensor.

**Comment by RavenSystem** [comment]
Actually I only support services supported by Apple HomeKit, and pressure sensor don't make sense.
