### ISSUE TITLE
request new feature: low salt sensor for water softener

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#300]
Hi,
I have request new feature: I would use a SONOFF basic (it's compact, cheaper and with power supply included) to implement a low salt warning sensor for water softener of my home; please see this example:

http://lowsaltalarm.com
https://youtu.be/QbCfWEYX4iA

it need only a dry contact (you already developed it in many other device type); my request is only to create a device type 14 with only dry contact (no need switch or button) and change icon and name of it in apple home app.

it's possible? it's compliant with apple home kit developer rules?

regards

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/298
