### ISSUE TITLE
Can't find/add device on HomeKit.

### ISSUE THREAD

**Issue by iBurzhuy** [RavenSystem/esp-homekit-devices#301]
Hi I flashing the NodeMCU set 
OTA repository:
RavenSystem/ravencore
OTA binary file:
main.bin
and set wifi.
I can't find/add device on HomeKit.  
On Console I see next:

RC > RavenCore
RC > Developed by RavenSystem - José Antonio Jiménez
RC > Version: 0.7.2

RC > Loading settings
RC > Loading saved states
RC > Initializing hardware...
RC > HW ready
>>> wifi_config: Initializing WiFi config
>>> wifi_config: Found configuration, connecting to ISSP Guest
mode : sta(84:f3:eb:b4:cc:16)
add if0
scandone
add 0
aid 4
cnt 

connected with My NET, channel 4
dhcp client start...
ip:192.168.130.235,mask:255.255.255.0,gw:192.168.130.254
>>> wifi_config: wifi_config_sta_connect_timeout_callback: Successfully connected
RC > Creating accessory name
RC > Creating HomeKit accessory
RC > Creating Setup accessory
RC > Starting HomeKit Server
>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: EA:B2:67:57:0B:E4
>>> HomeKit: Configuring mDNS
mDNS announcement: Name=RavenCore-B4CC16 md=RavenCorepv=1.0id=EA:B2:67:57:0B:E4c#=450s#=1ff=0sf=1ci=8 Port=5556 TTL=4500
rm match
reconnect
scandone
reconnect
scandone
reconnect
scandone

**Comment by GPL71** [comment]
It seem ready to add in HOME APP

**Comment by RavenSystem** [comment]
Something is wrong with your wifi network:
> rm match
> reconnect
> scandone
> reconnect
> scandone
> reconnect
> scandone
