### ISSUE TITLE
Implement momentary Relay for device type 1

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#303]
Hi,
I'm thinking of modding a generic 5V PCB (for Winix Air Purifier) with Sonoff SV using man-in-the-middle approach :) It will allow me to automatically power it on (it can't), especially when nobody's home.

I want to highjack power-on push button (SW1) as GPIO14 input (as External Toggle: 1), 
however I want RavenCore to provide a 0.5 sec pulse as an output, like it currently does for Garage Door (device type: 8). This way PCB can be triggered by pulse from Sonoff (by button or software).

The on/off state should better be memorized by software and support setting initial state On (1 pulse on startup). Any chance you'll add this?

P.S. That's currently possible with Tasmota, but I love RavenCore more :)
P.P.S. The idea is to replace R20 with Sonoff SV's input (GPIO14) and output (relay) wires running 5V.

![IMG_1828](https://user-images.githubusercontent.com/16850291/54863824-82e7ba80-4d5e-11e9-9063-3c96f5ecf543.jpg)
![IMG_1830](https://user-images.githubusercontent.com/16850291/54863823-824f2400-4d5e-11e9-8aa6-a89ce96d2c08.jpg)

**Comment by yukonx** [comment]
Type 13 is currently available

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#13-lock-mechanism

**Comment by i3laze** [comment]
Itching relay, now I get it! :)
Will give a try.

**Comment by i3laze** [comment]
Indeed type 13 works as I require. But... it represents a Lock!
And it doesn’t save state :(

I need a Fan/Switch!
odd click - On, even click - Off.

**Comment by RavenSystem** [comment]
Version 0.8.2 will do it.

**Comment by RavenSystem** [comment]
Supported in v0.8.2.
