### ISSUE TITLE
Garage Door "Closed"

### ISSUE THREAD

**Issue by danricho** [RavenSystem/esp-homekit-devices#310]
It appears that when the device is set to "closing" state, the working time is used to determine if the door has closed even when a "closed" sensor is fitted.

I think that the time based approach is good for transition from "opening" to "open", but the transition from "closing" to "closed" should be based on the sensor.

**Comment by RavenSystem** [comment]
I agree. Time base for closing has been removed in unreleased version 0.8.0. Stay tunned. I will release it soon.

**Comment by RavenSystem** [comment]
Supported in RavenCore v0.8.0.
