### ISSUE TITLE
Sonoff 4CH

### ISSUE THREAD

**Issue by lfiocco** [RavenSystem/esp-homekit-devices#311]
Can you use a Sonoff 4CH as 4 valves for watering. Or 4CH can only be used for switches?

**Comment by RavenSystem** [comment]
Only switches, sorry.

**Comment by lfiocco** [comment]
does it work with R2? if I use a remote will RavenCore handle this, will it refresh?

**Comment by skop1986** [comment]
I think this is possible if you make a separate firmware for sonoff ch4

**Comment by RavenSystem** [comment]
@lfiocco RF should works. With a future new firmware called HAA you will be able to use 4 Water Valves in a Sonoff 4ch.
