### ISSUE TITLE
Sonoff 4ch

### ISSUE THREAD

**Issue by STijeras91** [RavenSystem/esp-homekit-devices#315]
Buenas, ante todo gracias por el trabajazo, me gustaría saber si con el sonoff 4ch se podrían activar los external toggles, para utilizar interruptores de casa normal, a parte de poder controlarlo con HomeKit. gracias!

**Comment by skop1986** [comment]
STijeras91 
Physical buttons on sonoff ch4 pro work!

**Comment by lfiocco** [comment]
When you press the buttons on the unit, homekit also refreshed this information?

Have you paired it with a remote. How does it work? Can you toggle the remote buttons and see what’s happening on the homekit app?

**Comment by STijeras91** [comment]
> When you press the buttons on the unit, homekit also refreshed this information?
> 
> Have you paired it with a remote. How does it work? Can you toggle the remote buttons and see what’s happening on the homekit app?

Yes, the buttons integrated in the Sonoff 4CH board work perfectly and update the Homekit status.

**Comment by STijeras91** [comment]
> Physical buttons on sonoff ch4 pro work!

With the non-PRO version, can it also work?

**Comment by lfiocco** [comment]
I can confirm that on the pro R2 the remote and local buttons work, after a few seconds the changes are seen in the home app.
