### ISSUE TITLE
Ota not working

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#317]
How stable is ОТА? I have several devices, and when I click update, nothing happens. I have been trying for a few days now.

Also, if you now flash OTA, then it will not load the firmware, and it will always reboot. Although at some point I managed to flash a couple of 10 devices with OTA

**Comment by i3laze** [comment]
Sounds strange.
I suggest you try a Reboot to get rid of possible decay, then Firmware update.

F/W update may fail on low WiFi signal. Wiring up RavenCore to serial cable might give a clue.

**Comment by pixidixi88** [comment]
Hi, I have the same issue. One from 5 devices has not upgraded via OTA.

**Comment by RavenSystem** [comment]
These issues are better created in OTA repo: https://github.com/HomeACcessoryKid/life-cycle-manager
