### ISSUE TITLE
Device type 13: add possibility disable inching

### ISSUE THREAD

**Issue by lizzus** [RavenSystem/esp-homekit-devices#319]
Hi Josè, can you add possibility disable inching (from EVE) to enable and disable inching? 
I think can be a great features because if we add 2 relay we can open or close lockdoor.
What do you think?

**Comment by RavenSystem** [comment]
Good idea. Setting 0 seconds in inching time will be disable it.

**Comment by RavenSystem** [comment]
Done in unreleased version 0.8.0.

**Comment by lizzus** [comment]
Changelog or add in ne version 0.8.0

**Comment by RavenSystem** [comment]
@lizzus https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List#080

**Comment by RavenSystem** [comment]
Supported in RavenCore v0.8.0.
