### ISSUE TITLE
Tuya SWA1 with esp8266 Smart plug

### ISSUE THREAD

**Issue by massimo79** [RavenSystem/esp-homekit-devices#320]
Hy! I correctly flashed the Tuya Smart plug with the ravencore firmware since the esp is compatible. Only thing is that the GPIO connectivity is different from Sonoff and relay doesn’t trigger. GPIO should be something like this:
GPIO4: Led
GPIO5: Relay
GPIO13: Button
Since these plugs are very popular, could you make a “board type” for these?
Thanks from your friends in Italy!

**Comment by GPL71** [comment]
@RavenSystem  Josè  it would be interesting a solution like the follow
The GPIO list where default set is NONE 
The user may choose and assigne the function to GPIO e.g. output, input, led and other....

What do you think?

**Comment by RavenSystem** [comment]
@GPL71 HAA firmware will work in a similar way. You will can setup each GPIO using a JSON string like:
{
   type: "switch",
   relay_gpio: 4,
   button_gpio: 8
}

**Comment by massimo79** [comment]
Will the setup be available also in Eve?

**Comment by GPL71** [comment]
@RavenSystem Josè without words .... Great!!!!
Have you any idea when we'll see a first release about?
@massimo79 I think by web ... Josè wrote something about ...
I think this firmware will be something we can't image at the moment....

**Comment by massimo79** [comment]
@RavenSystem I can beta test (if you like) the GPIO settings in the new HAA when the beta is available.

**Comment by jorgemartins** [comment]
Hey @massimo79, out of curiosity, have you flashed the tuya device through the serial port or with OTA tool like Tuya-convert ?

I'm asking because @RavenSystem just recently created a joined `.bin` #364 that could be used in a OTA approach, but you flashed it before him doing that so you could have your methods :)

**Comment by massimo79** [comment]
Hi @jorgemartins, I flashed the Tuya switch with a usb serial adaptor and no need of soldering. Hard erasing and uploading new firmware had no issues, problem is the GPIO settings that don’t make it work!

**Comment by jorgemartins** [comment]
hey @massimo79 just noticed HAA was released → https://github.com/RavenSystem/esp-homekit-devices/wiki/Home-Accessory-Architect

have you tried it to use the correct GPIO? 🤞

**Comment by massimo79** [comment]
Hi @jorgemartins not yet! Planning to do so this weekend and I can’t wait to try. I’ll give you feedback if I succeed and will share the json!

**Comment by RavenSystem** [comment]
JSON for HAA: `{"c":{"l":4,"i":1},"a":[{"t":2,"r":[{"g":5}],"b":[{"g":13,"p":1,"t":1}]}]}`

**Comment by massimo79** [comment]
Great @jorgemartins thanks a lot! Con you confirm that I have to reflash the device? (Right now it’s running ravencore).

**Comment by jorgemartins** [comment]
I think you meant José and not Jorge 😅.
Anyway credit goes to @RavenSystem - thank you for your work, by the way!

Regarding your question I think you need to reflash as HAA is a different firmware. I'm not sure if we can simply change the OTA repository without reflash. Can we @RavenSystem ?

**Comment by massimo79** [comment]
Sorry @RavenSystem..my mistake! 🤪

**Comment by jorgemartins** [comment]
Hey @massimo79, you closed the issue but didn’t mention if you were successful with having homekit on your tuya device 😬.
Thank you

**Comment by RavenSystem** [comment]
To install HAA is necessary to erase flash and start from scratch.

**Comment by massimo79** [comment]
@jorgemartins unfortunately no! The device doesn’t work correctly in AP mode (the first time LCM showed up but wasn’t able to add device to Homekit, in other attempts LCM never showed up and I wasn’t able to download HAA). I will try again!

**Comment by massimo79** [comment]
@jorgemartins @RavenSystem issue closed by mistake and reopened.

**Comment by RavenSystem** [comment]
I suggest to flash LCM firmware, and then connect device to 230VAC and do the rest of installation (wifi setup, repo, ...).

**Comment by franklindee** [comment]
hi do you know how to reset the HAA and redo the configuration?

**Comment by mientki** [comment]
> JSON for HAA: `{"c":{"l":4,"i":1},"a":[{"t":2,"r":[{"g":5}],"b":[{"g":13,"p":1,"t":1}]}]}`
> 
> https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates#tuya-swa1-with-esp8266-smart-plug

Will it work with the Tuya PP-W162 socket? How can I change the software without soldering the wires. Access to the pins is so difficult and requires desoldering the entire motherboard. Hour of work.
