### ISSUE TITLE
Water valve without timer

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#321]
Hey. You use the device type 7 - Water Valve in your firmware. However, it looks like an irrigator, as it has a timer to shut off, which will not allow it to be used as a water control system.

Can you add this service as a tap? the tap has no timer and that would be very cool

**Comment by netRunner0** [comment]
![IMG_1720](https://user-images.githubusercontent.com/44049295/55540105-aeae5d00-56db-11e9-847a-59d28d5efef7.jpeg)
![IMG_1719](https://user-images.githubusercontent.com/44049295/55540114-b241e400-56db-11e9-8756-cd0fd5f108f1.jpeg)

**Comment by rechin304** [comment]
Check Wiki page

7. Water Valve

Use your device as a HomeKit Water Valve or Irrigation System, with a built-in timer.

Valve Type [Default: 0]

Reboot required when changed.

Select the water valve type icon to show:

0. Water Valve
1. Sprinkler
2. Shower
3. Tap

So use valve type 3

**Comment by netRunner0** [comment]
With this configuration, the situation does not change, there is still a timer

**Comment by netRunner0** [comment]
![IMG_0002](https://user-images.githubusercontent.com/44049295/55711169-9903a500-5a05-11e9-8c2c-a04df7c121d9.jpeg)

**Comment by RavenSystem** [comment]
Actually, there is no way to remove timer. A future version could bring that option.

**Comment by RavenSystem** [comment]
Supported in RavenCore v0.8.0.

**Comment by rechin304** [comment]
After update to v0.8.0 and enable Have Stop, where do you setup the time ?

**Comment by RavenSystem** [comment]
time no, timer. The new feature is the option to disable the timer.

**Comment by rechin304** [comment]
Sorry, I wanted to say timer. As now the timer is 15 sec then is off.

**Comment by RavenSystem** [comment]
> Sorry, I wanted to say timer. As now the timer is 15 sec then is off.

What do you mean?

**Comment by rechin304** [comment]
Before was default duration

**Comment by RavenSystem** [comment]
Timer is a HomeKit characteristic. Nothing has changed with water valve timer working way.

**Comment by rechin304** [comment]
That option is not anymore in Home app.

**Comment by RavenSystem** [comment]
In my case works like a charm. Remember to reboot your accessory when "Has Stop" option is changed.

**Comment by rechin304** [comment]
ok, reboot was the issue. thanks. Maybe is good idea in wiki to mention that a reboot is required.

**Comment by RavenSystem** [comment]
It is in the Wiki.

**Comment by rechin304** [comment]
Ok, then probably I missed. Thank you for your efforts !!

**Comment by netRunner0** [comment]
![IMG_0008](https://user-images.githubusercontent.com/44049295/55819414-22a09900-5b12-11e9-9771-e30f689c5531.gif)

**Comment by RavenSystem** [comment]
Don’t worry. Many thanks!!
