### ISSUE TITLE
magic home bug

### ISSUE THREAD

**Issue by curla92** [RavenSystem/esp-homekit-devices#326]
Hi josè. i have just tried your new update for the magichome. I managed to fix the colors but i can't switch off the magichome.. when i tried to turn off the strip goes to red color...
Can you help me? thank y

**Comment by RavenSystem** [comment]
Have you check RGBW pins setup?

**Comment by curla92** [comment]
GPIO 5 12 AND 13.. GPIO 5 is the first pin after the voltage?

**Comment by RavenSystem** [comment]
RGB GPIOs 5, 12 and 13 are the default setup, but your R pin will be other than 5. I don't know how is your board, but you can search tracks of esp8266 and check them here: https://github.com/esp8266/esp8266-wiki/wiki/Pin-definition

**Comment by curla92** [comment]
i have magichome zj-wfmn-a v1.1

**Comment by lizzus** [comment]
Magic Home GPIO https://ibb.co/n0HwzvX

**Comment by curla92** [comment]
mine is different

**Comment by RavenSystem** [comment]
There are a lot of different Magic Home compatible devices. That is the reason because a custom GPIOs setup is present.

**Comment by curla92** [comment]
i know. im looking for setup of my model. 

![IMG_2480](https://user-images.githubusercontent.com/22404058/55832605-351cd180-5b16-11e9-89f0-12ed148b089f.JPG)
![IMG_2481](https://user-images.githubusercontent.com/22404058/55832606-351cd180-5b16-11e9-85f3-0024b00b5499.JPG)

**Comment by RavenSystem** [comment]
Can you do a photograph with better light?

**Comment by curla92** [comment]
![IMG_2482](https://user-images.githubusercontent.com/22404058/55832913-df94f480-5b16-11e9-9d94-e79247b8fd97.JPG)
![IMG_2483](https://user-images.githubusercontent.com/22404058/55832914-df94f480-5b16-11e9-9bfe-49f1e82edbe6.JPG)
![IMG_2484](https://user-images.githubusercontent.com/22404058/55832915-e02d8b00-5b16-11e9-8da7-38c5dcc20da7.JPG)

**Comment by lizzus** [comment]
@RavenSystem sorry for O.T. 
I writed you.

**Comment by RavenSystem** [comment]
In the photo, I see that used GPIOs are 5, 12 and 13. Red pin is managed with GPIO 5. But I see a critical point very near of RXD. The critical point inside circle is the GPIO 5; try to clean it.

<img width="530" alt="Captura de pantalla 2019-04-09 a las 22 41 11" src="https://user-images.githubusercontent.com/8655274/55833843-c68d4300-5b18-11e9-868a-ec5f9e28cb1e.png">

**Comment by rechin304** [comment]
I have same version and is working fine. R-5, g-12, b-13

**Comment by curla92** [comment]
ok maybe it's this point.. damn it's very small!

**Comment by curla92** [comment]
> I have same version and is working fine. R-5, g-12, b-13

turn off works?

**Comment by RavenSystem** [comment]
@curla92 firmware has been tested and works perfectly (turn off included). Try to clean a bit the critical point. You only must remove the soldering tin next to the tiny hole to avoid contact, because the hole has not resin.

**Comment by RavenSystem** [comment]
> @RavenSystem sorry for O.T.
> I writed you.

I saw your emails, don't worry. But what's is "O.T."?

**Comment by lizzus** [comment]
over thread

**Comment by lizzus** [comment]
**Magic Home Pin configuration by model:**

1. MAGICHOME LED CONTROLLER
PIN       14      // RED
PIN       5       // GREEN
PIN       12      // BLUE
PIN       13      // WHITE

2. MAGICHOME LED CONTROLLER 20
PIN       5       // RED
PIN       12      // GREEN
PIN       13      // BLUE
PIN       15      // WHITE

3. MAGICHOME ZJ WFMN A 11
PIN       12      // RED
PIN       5       // GREEN
PIN       13      // BLUE
PIN       14      // WHITE

4. MAGICHOME ZJ WFMN B 11
PIN       14      // RED
PIN       5       // GREEN
PIN       12      // BLUE
PIN       13      // WHITE

**Comment by curla92** [comment]
hi, i want to know that i changed the maagic home device and this new works perfectly. thanks for the help josè, gpio5 on the last magichome was broken.
