### ISSUE TITLE
Sonoff shuts down in a second

### ISSUE THREAD

**Issue by kutdenis** [RavenSystem/esp-homekit-devices#330]
Relays are switched off at once, basic and 4ch. On 4ch turns off only the first channel, the other three channels work as it should& After upgrade to 0.8.2

**Comment by RavenSystem** [comment]
Set Inching time to 0.

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#inching-time-default-0

**Comment by kutdenis** [comment]
Thank you!
