### ISSUE TITLE
Option to disable wifi reset after quick external button pressing?

### ISSUE THREAD

**Issue by kittmark** [RavenSystem/esp-homekit-devices#333]
Hello, could you please add in Eve an option to disable the wifi reset that happens when somebody accidentally triggers the external toggle quickly a few times? 
I was testing my just installed Shelly by quickly pressing the external toggle and I accidentally reset the wifi...good thing it’s just the wifi and not factory reset though...I was afraid I had to reopen everything...

I know for sure it can be done because I know another firmware that does it (disable reset sequence for sonoff and shelly).

**Comment by kittmark** [comment]
Wait, is the trigger sequence already restricted within the first minutes from powering on?

If so, never mind, it’s already safe enough I guess.

**Comment by RavenSystem** [comment]
Yes, reset must be triggered within 2 first minutes.
