### ISSUE TITLE
ESP32-CAM 

### ISSUE THREAD

**Issue by arturodiazad1** [RavenSystem/esp-homekit-devices#334]
Enhorabuena por todo tu trabajo gracias a ravencore tengo ya practicamente domotizada toda mi casa, hay alguna posibilidad de agregar a la lista de futuros dispositivos el ESP32-CAM? sería posible hacerlo funcionar?

**Comment by GPL71** [comment]
It would be interesting!!

**Comment by topzoe** [comment]
yes! very, very interesting!!! an ESP32-CAM lowcost with homekit compatibility!!!

**Comment by RavenSystem** [comment]
Maybe someday, I want it too, but actually not enough time. I have an ESP-EYE, but it keeps into its box.
