### ISSUE TITLE
Mode 4 Inching - Relay 3&4

### ISSUE THREAD

**Issue by dwhp** [RavenSystem/esp-homekit-devices#335]
Hi
I noticed after latest update. Using a Sonoff 4ch pro, inching only works for Relay 1&2 however NOT for Relay 3&4. 

Is this just me? I have rebooted a few times, changing back and forth from 0 to a preset time with no success.

**Comment by RavenSystem** [comment]
It is a bug.

**Comment by RavenSystem** [comment]
Fixed in version 0.8.4.
