### ISSUE TITLE
about garage controller

### ISSUE THREAD

**Issue by xfce** [RavenSystem/esp-homekit-devices#338]
Hi developers, 
    actually, I found garage door controllers mostly have two or three keys: up, down,  or  up, down, and down. do you have a plan to support these controllers. thanks

**Comment by RavenSystem** [comment]
No, sorry. Instead, there are plans to create a fully HomeKit garage door driver, eve with electro-lock included.

**Comment by xfce** [comment]
@RavenSystem ok, thanks, waiting for the fully driver.and if you want to design the hardware maybe i can help^-^
