### ISSUE TITLE
Update issues OTA

### ISSUE THREAD

**Issue by fiska1** [RavenSystem/esp-homekit-devices#339]
Hey.  Problems with OTA firmware updates.  Last successful update to version 0.8.1.  After it, I only see that new versions have been released (0.8.2, 0.8.3, 0.8.4), but I cannot upgrade.  What could be the problem?  How to solve it?  Thank.

**Comment by topzoe** [comment]
no problems for me...

**Comment by RavenSystem** [comment]
These issues are better created in OTA repo: https://github.com/HomeACcessoryKid/life-cycle-manager
