### ISSUE TITLE
Auto-off (like water valve) or longer inching time for all dev types?

### ISSUE THREAD

**Issue by kittmark** [RavenSystem/esp-homekit-devices#340]
Would it be possible to set auto-off time (in Eve) for switches dev types or have a longer inching time, like up to 120min instead of up to 12s? If doing it on the same slide is incovenient, you could implement a toggle option between “short inching” (=1) and “long inching” (=2) and no inching (=0)...

**Comment by peros550** [comment]
+1

**Comment by RavenSystem** [comment]
Impossible with RavenCore: Not enough resources to add the necessary custom HomeKit characteristics. With HAA will b possible because you will set as a float outside HomeKit.

**Comment by kittmark** [comment]
I see, thanks for the answer.
