### ISSUE TITLE
New functions - water valve

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#346]
Hey. Thanks for the tap without a timer!

I use the leakage wieste system with nodemcu. I can control the tap from Homekit.

But I don’t mind feedback if the system has detected a leak through its sensors and shut off the faucet. Do you have the option to add gpio for this feature? For example, when closing 2 gpio, the status of the tap in HomeKit will change to closed, and vice versa. Thanks

**Comment by RavenSystem** [comment]
Sorry, that will not be implemented. You can use other water leak sensor and an automation to do it.
