### ISSUE TITLE
New simple feature for device nr. 10

### ISSUE THREAD

**Issue by lizzus** [RavenSystem/esp-homekit-devices#347]
Hi Josè, I wanted to ask you if in the next release you can insert a small modification to the device nr. 10 (ESP01 Switch + Button). I have heard so many people who would like only one button, without the relay, to create wireless buttons, even considering the reduced dimensions of esp01. 
Currently the device 10 has both button and relay and I thought it would be very convenient to give people the possibility of having only 1 device, simply setting it in EVE. 
In this way with the 
setting 0 = socket + button (default)
o
setting 1 = button only
People can choose the solution that best suits their needs. Of course after the restart the devices will also be updated at home.

**Comment by GPL71** [comment]
I agree it would be interesting

**Comment by curla92** [comment]
> I agree it would be interesting

me too

**Comment by GuyCoast** [comment]
idem

**Comment by vglucas** [comment]
very interesting, it interests me too 👍

**Comment by lizzus** [comment]
hi @RavenSystem didi you read?

**Comment by maxnasva** [comment]
oh yes,it's very interesting.I hope this change is not too difficult to include in the firmware.

**Comment by GPL71** [comment]
It would be interesting if you need add an automation for a group of devices.
An example about:

1 stateless button on wall-switch
2 different devices with their relay and bulbs connected

Then
Press 1 time button and device 1 turn on
Double press and device 1 turn off, while device 2 turn on
Long press and devices 1 and 2 turn on

It imitate the relays mad by FINDER

What do you think

**Comment by maxnasva** [comment]
commutador ref.27.05/25 finder
![sequenza finder](https://user-images.githubusercontent.com/47340771/56605102-a8890d80-6603-11e9-9325-604c754dc478.png)

**Comment by maxnasva** [comment]
commutador finder ref.27.05/25
https://gfinder.findernet.com/public/attachments/27/ES/S27ES.pdf
![sequenza finder](https://user-images.githubusercontent.com/47340771/56605258-03226980-6604-11e9-8d4e-944f61538a40.png)

**Comment by RavenSystem** [comment]
@lizzus With HAA you will can create an event button. I don't want to improve dev type 10 anymore. Sorry.

**Comment by lizzus** [comment]
event o stateless button?

**Comment by RavenSystem** [comment]
stateless button, same button with dev type 10 (without switch and relay).

**Comment by RavenSystem** [comment]
Try version 0.8.7 with dev type 15 and configure pin w GPIO with your button.

**Comment by GPL71** [comment]
It working!!!
Thank you so much

**Comment by lizzus** [comment]
works fine. thanks!
