### ISSUE TITLE
0.8.5 Dummy switch

### ISSUE THREAD

**Issue by kalety** [RavenSystem/esp-homekit-devices#350]
Hi Jose!, I've updated one of my switches to 0.8.5 version. At Eve's app appears the dummy switch option, but no idea how to manage it, not appears at Home app. Can you explain in more detail how works it?.

Thanks in advance!

**Comment by RavenSystem** [comment]
I am busy now, but give me a chance to write documentation about it in Wiki.

**Comment by lizzus** [comment]
Please after link me where you add, so I can add in my Italian translation. Thanks.

**Comment by RavenSystem** [comment]
Instructions about Dummy Switch:

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#dummy-switch-default-off

**Comment by RavenSystem** [comment]
@lizzus Check https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#pins-r-g-b-w too

**Comment by lizzus** [comment]
Ok, thanks.

**Comment by RavenSystem** [comment]
@lizzus If you want, I can add a link to your Italian translation in the Wiki.

**Comment by lizzus** [comment]
Really? Yes, off course!

**Comment by RavenSystem** [comment]
@lizzus What is the url?

**Comment by lizzus** [comment]
https://www.twibuk.com/read-blog/22_guida-completa-in-italiano-del-firmware-ravencore.html

**Comment by RavenSystem** [comment]
@lizzus Done!!

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore

**Comment by kalety** [comment]
> Instructions about Dummy Switch:
> 
> https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#dummy-switch-default-off

Mil gracias!

**Comment by i3laze** [comment]
Great dummy!
I’d personally use it with Garage door (instead of extra dummy from HomeBridge) to overcome the need of unlocking iPhone before “someone arrives” automation or saying “Open garage door”.

However I still willing to see Inching relay saving it’s logical state (1st click on, 2nd off) in such a dummy, actually.
