### ISSUE TITLE
Esp-8266 goes offline... 

### ISSUE THREAD

**Issue by Manelvallsvila** [RavenSystem/esp-homekit-devices#352]
At home I have tried to set up some push button with hidden wemos D1 mini flashed with ravensystem.

I follow the wiki instructions, everything works, configuring it in home app for the 3 actions, and still works, but after some hours, the device goes offline...

I repeat all the process and after few hours it goes offline.

I have tried with sonoff basic, and the same result.

If any knows what can I do I’d appreciate it.

Thanks Jose for your hard work!

**Comment by RavenSystem** [comment]
This can be a router/wifi network issue. What router do you have?
