### ISSUE TITLE
Shelly 1 as a Water valve

### ISSUE THREAD

**Issue by tohmc** [RavenSystem/esp-homekit-devices#353]
Hi,

when I set up my shelly 1 to Device type 7
it have no function.
I think its on other GPIO as in Shelly.
it is possible to add a GPIO setting or when setting to Shelly board type that it uses Shelly GPIO?

**Comment by Aaronwithanat** [comment]
The shelly 1 GPIO cannot and should not be used while connected to mains voltage. The GPIO headers on the shelly are directly tied to the AC lines.  Specifically the ground on the header is tied directly to the hot wire or line voltage pin from the AC input.

**Comment by tohmc** [comment]
Thanks But  i know this.

Shelly is Jumped to 12V 
But no relay is triggered when connecting it and test it.

**Comment by tohmc** [comment]
Nobody an idea?

**Comment by RavenSystem** [comment]
Shelly1 is not supported as Water Valve yet.

**Comment by tohmc** [comment]
Thanks,

Will ist ne supported in the Future?

**Comment by RavenSystem** [comment]
Yes, sure, and soon, because I will use it in my garden.

**Comment by RavenSystem** [comment]
0.8.8 supports it.
