### ISSUE TITLE
RGB/W brightness issue

### ISSUE THREAD

**Issue by greensouth** [RavenSystem/esp-homekit-devices#355]
Hi Jose!

It's possible that since I applied Ravencore to a RGB Magic Home its bright is lower than the exposed with the original firm?

Maybe it's not, but I would swear that it's about 10% less bright.

I fiddled with the color boost option but it seems that it only lowered even more to me.

Maybe there are demons in my controller!

Also, a couple of times I lost connection and had to reflash it in order to link it to my wifi again. Tried to perform a reset (10 reboots in less than 3 seconds.... But it is impossible when you have to switch it on and off pulling the cable xD)

Thanks! And great exposition at Reddit

**Comment by RavenSystem** [comment]
> Hi Jose!
> 
> It's possible that since I applied Ravencore to a RGB Magic Home its bright is lower than the exposed with the original firm?
> 
> Maybe it's not, but I would swear that it's about 10% less bright.
> 
> I fiddled with the color boost option but it seems that it only lowered even more to me.

Set color boost to 100% and select a different color. Color boost value is applied in the next color change. Tell me your results, please.
 
> Maybe there are demons in my controller!

Demons are always welcome ;)

> Also, a couple of times I lost connection and had to reflash it in order to link it to my wifi again. Tried to perform a reset (10 reboots in less than 3 seconds.... But it is impossible when you have to switch it on and off pulling the cable xD)

If you lose wifi connection, you don't need to refresh. Try to put your device is other place with better wifi coverage and repower it. Actually, you can not reset RGBW device switching it on and off. The only way is to push and hold the button (GPIO0). In next version, you will be able to reset any accessory switching it quickly from Home App too.

> Thanks! And great exposition at Reddit

Cheers! :)

**Comment by mafyata** [comment]
> Hi Jose!
> 
> It's possible that since I applied Ravencore to a RGB Magic Home its bright is lower than the exposed with the original firm?
> 
> Maybe it's not, but I would swear that it's about 10% less bright.
> 
> I fiddled with the color boost option but it seems that it only lowered even more to me.
> 
> Maybe there are demons in my controller!
> 
> Also, a couple of times I lost connection and had to reflash it in order to link it to my wifi again. Tried to perform a reset (10 reboots in less than 3 seconds.... But it is impossible when you have to switch it on and off pulling the cable xD)
> 
> Thanks! And great exposition at Reddit

Do you have original software of magic home rgb controller ? I forget to backup mine before flash it.

**Comment by greensouth** [comment]
Nope, same bright but color changing. I suppose it's happening because I have no white channel. But anyways still low bright.

When set boost at 100%, some colors just blinks and turns off.

Maybe voltage passed to the strip is not enough? I don't know if this is managed when programing a firmware for the controller.

:(

**Comment by RavenSystem** [comment]
> Nope, same bright but color changing. I suppose it's happening because I have no white channel. But anyways still low bright.
> 
> When set boost at 100%, some colors just blinks and turns off.
> 
> Maybe voltage passed to the strip is not enough? I don't know if this is managed when programing a firmware for the controller.
> 
> :(

Don't worry about white channel.

Try this: With brightness at max and color boost 100%, set pure red color, and same with pure blue and pure green; and post here the results, please.

**Comment by RavenSystem** [comment]
@greensouth Any news about that? Did you try what I said?

**Comment by greensouth** [comment]
Wenas José!
Actually I have nothing installed on my iPhone which let me set RGB values manually or pure colors, I move the color picker as close as I think it's the most pure values in both EVE and Home App. Still see them a bit dim. I think I was able to set color boost to about 30% to get the maximum fidelity of colors/brightness with my RGB controller. 

I suppose that it's having some difficult matching the color wheel (which uses WHITE as a color to mix all the possible combinations) with only 3 channels. 

I'm expecting to receive some RGBW Led stripes + Controller this week and I'm planning on flashing one with Ravencore and let the other with the default firmware and I will check both.

I'm curious about what is exactly the function of color boosting when getting / setting the color values.

Btw, were you able to take a look at what I told you about adding some custom delay for the timers when beginning the movement of the rolling shutters? 

Thanks!

**Comment by RavenSystem** [comment]
@greensouth 

If you want a good white color, RGBW led strip is your best choice. Mixing RGB to get white is... well... is a shit.

Color boost is a factor from 1 to 3 (0% to 100%) to mix RGB colors and try to match with your led strip in a better way.

> Btw, were you able to take a look at what I told you about adding some custom delay for the timers when beginning the movement of the rolling shutters?

I remember something about this, but I am not able to find it now. Can you post the link of the issue?

**Comment by greensouth** [comment]
Hey @RavenSystem I've just received the rgbw strip and WORKS LIKE A CHARM! With Ravencore. I'm changing all my RGB stuff.

The roller shutter thing is a little miss-adjustment when setting the time that takes to open and close the rolling shutter.

It takes a couple of seconds, maybe three, to tight the hooks before it begins to move. That adds some extra time where it's not moving at all but enough to break the calculations for setting %. In my case, closing at 50% is far from the half of the window.

Adding extra time for opening/closing doesn't work. It would be needed to add a setting for adding a configurable delay for 0 and 100 positions, before starting to count the real time once the hooks are tight, which is when the rolling shutter begins to move.

Maybe it's a bit difficult to explain :/

**Comment by RavenSystem** [comment]
@greensouth Más cómodo en español:

Sé que te refieres a las persianas que tenemos todos en nuestras casas, al menos en España, que las puedes bajar pero dejando las ranuras esas abiertas para que entre algo de luz, o aire. Obviamente, el % de HomeKit se refiere realmente a la posición del motor, y no de la persiana en sí.
Al 0%, la persiana está totalmente cerrada, sin ranuras abiertas ni nada, en modo búnker.
Al 10%, la persiana seguro que seguirá cerrada, pero con las ranuras abiertas.
Y al 50%, la persiana estará un poco abierta, pero no a la mitad. Aunque el motor sí que estará a su mitad de recorrido.

Poniendo tiempos más altos de lo que realmente tarda la persiana en subir y en bajar no sirve para nada. De hecho, es mejor poner el tiempo exacto, ya que luego esto sirve para que en los casos en los que pierda un poco de sincronización (estos motores no tienen unos tiempo de trabajo exactos), el accesorio pueda volver a sincronizarse automáticamente cuando subas o bajes la persiana del todo.

Ahora bien, tú sugieres poder indicar el tiempo que tarda la persiana de estar totalmente cerrada, a estar cerrada pero con las ranuras abiertas, y que empieza a contar el porcentaje una vez que ha alcanzado esa posición. Así si le dices que la abra al 50%, se abrirá al 50%, pero ¿qué pasa si quieres poner la persiana con las ranuras medio abiertas, o solo un poco por la parte de arriba? Yo a veces las quiero así. No te creas que no le he dado ya vueltas a este tema, y sigo en ello. Por ahora la mejor idea que he tenido es que del 0 al 5% corresponda a cuando la persiana está de totalmente cerrada a cerrada pero con todas las ranuras abiertas. Y ya del 5% al 100%, sería de la persiana cerrada (ranuras abiertas), a la persiana abierta. De esta manera, el 50% estaría muy cerca de la mitad real.

**Comment by greensouth** [comment]
Es que parece una chuminada, pero al final tiene la cosa más enrea de lo que parece. Todo tiende a liarse ;) además veo que estás a tope con el otro proyecto.

Te va a echar el coco lumbres!! 

X cierto el tema Magic Home he estado dándole unas cuantas vueltas más, y cuando hace el Fade al cambiar de color, sube a tope la intensidad y luego cuando llega al color final, es cuando la baja. 

Ahí es donde está la pequeña pérdida de brillo que te comentaba. 

;)

**Comment by RavenSystem** [comment]
Por el otro proyecto no te preocupes. En realidad tengo un interés personal en el tema de las persianas. ¿Qué te parece lo de dejar un 5% para la parte de las ranuras?

Respecto a lo de los LEDs, es posible que pase lo que dices. Mejoraré el algoritmo, pero puedo asegurarte que el color final  que te pone ya fijo es el color seleccionado.

**Comment by greensouth** [comment]
Acabo de probarlo y a mí se me empiezan a ver todas las rajitas a partir de casi el 10%, pero todo esto es muy elástico, supongo que dependerá del motor, de los flejes y tal.

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
Claro, por eso digo de configurar el primer 5% aparte con el tiempo que tarda el motor en poner la persiana a punto para empezar a abrirse (ya con todas las ranuras abiertas).

Ya que estás, haz una cosa: Pon la persiana en el % que sea para dejarla en el punto justo antes de empezar a abrirse, y dime en qué % es.

**Comment by RavenSystem** [comment]
Y prueba la version 0.8.11 que acabo de sacar con lo de los LEDs y me cuentas.

**Comment by greensouth** [comment]
En mi motor sobre el 10%

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
> En mi motor sobre el 10%

Entonces si le dices que te ponga la persiana al 55% tendría que estar abierta a la mitad, ¿no?

**Comment by greensouth** [comment]
Tal cual está ahora mismo, para notar que está subida al 50% , tendría que ponerla al 70% sin exagerte

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
> Tal cual está ahora mismo, para notar que está subida al 50% , tendría que ponerla al 70% sin exagerte

¿Y tienes los tiempos exactos puestos? (De un final de carrera a otro del motor)

**Comment by greensouth** [comment]
Si tío, es súper raro, pero tb lo monté en casa de un vecino con el mismo motor y tal, y le pasa igual, de 0 a 100 cuadran los tiempos con los finales de carrera, pero visualmente por lo que te comenté hasta que se tensan los flejes, se queda muy corto en los porcentajes intermedios.

**Comment by RavenSystem** [comment]
Ahhh, claro. Ya sé por qué pasa eso. Cuanta más persiana hay recogida, más radio tiene el eje, y más longitud de persiana recoge por vuelta.

**Comment by greensouth** [comment]
Le vas a tener.que meter un multiplicador o algo! Jajajajaja 

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
Ya pensaré un algoritmo para solucionar esa chapuza de controlador de persianas, y digo chapuza por ser suave, porque es una m... bueno, esta es la parte divertida de la programación.

Y no te olvides de probar la 0.8.11 con los LEDs.

**Comment by greensouth** [comment]
Mañana lo pruebo con el que más problemas me da, porque cuando lo flashee no me dejó hacerlo con OTA (no sé si ese día estaría el servidor caido o algo)  y tengo que volver a soldar e intentarlo a ver si esta vez me deja la actualización :/ 

Oye muchas gracias por el currazo que te estás pegando. Estoy deseando de que me llegue el NodeMCU a ver si tengo huevos de echar a andar y probar lo otro!

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
De nada hombre. Yo me alegro de que mis firmwares sirvan para algo medio útil, aunque como controlador de persianas sea chapuzero (aún). Y yo odio las chapuzas.

**Comment by RavenSystem** [comment]
@greensouth Actualiza alguna de tus persianas a la 0.8.12, ciérrala del todo, y luego entra en EVE y pon la opción "Boost" al 100% (Es una opción nueva), y prueba a ver qué tal van ahora las posiciones intermedias.

https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#boost-default-0

**Comment by greensouth** [comment]
Justamente lo estaba haciendo!!

Con el 71% de boost LO-CLA-VA

Ahora es PERFECTO!!! Muchas gracias tiaco!!!!!! Fíjate si estoy contento que en cuanto cobre (y pague las rift s) tiro a pillar el motor para el salón !!

Ayer estuve dándole a los LED y he llegado a la conclusión de que la transición entre colores satura mucho al controlador, y le mete lagazos, y más cuando usas la rueda de HomeKit, que es impreciso y te hace moverte muchas veces entre colores en un espacio muy corto de tiempo,  creo que la transición animada debería ser opcional con un switch, qué opinas?

Enviado desde mi iPhone

**Comment by mafyata** [comment]
Can someone tell me which command to use to download original magichome firmware before flash with ravencore ?

**Comment by RavenSystem** [comment]
@mafyata `esptool.py -p /dev/espport read_flash 0x0 firmware.bin`

**Comment by mafyata** [comment]
Where will be downloaded ? Is only one file to download?

**Comment by RavenSystem** [comment]
> Where will be downloaded ?

In the working directory.

> Is only one file to download?

Yes, only a file with a full firmware backup. Then you only must write it at 0x0 address.

**Comment by mafyata** [comment]
I don’t know the directory, may be esptool directory. Thank you very much. :)

**Comment by RavenSystem** [comment]
> I don’t know the directory, may be esptool directory. Thank you very much. :)

The working directory is where you run the command. Instead, you can run:
`esptool.py -p /dev/espport read_flash 0x0 C:\firmware.bin`

**Comment by mafyata** [comment]
This command will do the job easier. Thanks again

**Comment by RavenSystem** [comment]
@mafyata With that command, you can do a backup of any firmware, not only of Magic Home.

**Comment by mafyata** [comment]
🥇

**Comment by mafyata** [comment]
Problem with reading flash:
C:\WINDOWS\system32>esptool.py -p com4 read_flash 0x0 firmware.bin
usage: esptool read_flash [-h] [--spi-connection SPI_CONNECTION]
                          [--no-progress]
                          address size filename
esptool read_flash: error: argument size: invalid arg_auto_int value: 'firmware.bin'

**Comment by mafyata** [comment]
I find an issue:
esptool.py -p com4 -b 115200 read_flash 0 0x200000 c:/firmware.bin

**Comment by RavenSystem** [comment]
@greensouth Prueba la versión 0.8.13 a ver si ya no te da tirones la transición de colores.

**Comment by greensouth** [comment]
Te cuento,

En el cambio de color es como si partiera no del color inicial, sino de un blanco o algo más intenso.

Si estoy en rojo y muevo al azul, hace algo así como ROJO - BLANCO - AZUL. Estoy intentando subirte un vídeo a ver si lo puedes ver, y gratis y por cortesía, las conversaciones de mis vecinos que se escuchan por el lavadero. 🤪

https://www.youtube.com/watch?v=KPsYG5qgAWY&feature=youtu.be

**Comment by RavenSystem** [comment]
@greensouth Ahora lo veo claro, reproduciendo el vídeo al 25% de su velocidad. En problema es que funciona demasiado bien, es decir, la respuesta es tan inmediata al cambio de color, que junto con la porquería de rueda de selección de color de la aplicación Casa, da como resultado una verdadera m... Fíjate que en cuanto tu pones el dedo sobre la rueda ya está aplicando el color seleccionado, que es más blanco que el que tú realmente quieres, y cuando tú pones el dedo, te aparece la lupa de ajuste fino, y tú desplazas el dedo hacia el exterior de la rueda, pero antes de empezar a desplazarlo, ya te ha cambiado el color al seleccionado nada más posar el dedo. No sé si me explico. El caso es que ya sé cómo solucionarlo.

**Comment by greensouth** [comment]
> @greensouth Ahora lo veo claro, reproduciendo el vídeo al 25% de su velocidad. En problema es que funciona demasiado bien, es decir, la respuesta es tan inmediata al cambio de color, que junto con la porquería de rueda de selección de color de la aplicación Casa, da como resultado una verdadera m... Fíjate que en cuanto tu pones el dedo sobre la rueda ya está aplicando el color seleccionado, que es más blanco que el que tú realmente quieres, y cuando tú pones el dedo, te aparece la lupa de ajuste fino, y tú desplazas el dedo hacia el exterior de la rueda, pero antes de empezar a desplazarlo, ya te ha cambiado el color al seleccionado nada más posar el dedo. No sé si me explico. El caso es que ya sé cómo solucionarlo.

si es que al final una imagen... ;) Justo ahora estoy flasheando otro magic home que me ha llegado

**Comment by RavenSystem** [comment]
Pues vas a tener que actualizarlo en breve, porque en unos minutos saco nueva versión.

**Comment by RavenSystem** [comment]
@greensouth Prueba la 0.8.14 a ver qué tal.

**Comment by greensouth** [comment]
> @greensouth Prueba la 0.8.14 a ver qué tal.

en ello está, me ha pillado la actualización en mitad del flasheo y no lo veía Homekit, tenía que haber echado la Bonoloto!

**Comment by RavenSystem** [comment]
@greensouth Cuando dices "muchísimo más estable" quieres decir que aún no es totalmente estable? O ya sí lo es?

Y sí, puede que me haya columpiado con el segundo de retardo, pero eso tiene fácil arreglo.

**Comment by greensouth** [comment]
> @greensouth Cuando dices "muchísimo más estable" quieres decir que aún no es totalmente estable? O ya sí lo es?
> 
> Y sí, puede que me haya columpiado con el segundo de retardo, pero eso tiene fácil arreglo.

eso es que va fino filipino, ya no parece que estés empastillao en una discoteca! ;)

**Comment by RavenSystem** [comment]
> eso es que va fino filipino, ya no parece que estés empastillao en una discoteca! ;)

@greensouth Mmm, y si le pongo una opción adicional que sea modo disco y se ponga a poner colores aleatorios? De hecho se podrían precargar varios modos: color fijo, brisa mañanera, lumbre de hogar, bar de luces de colores...

**Comment by greensouth** [comment]
> > eso es que va fino filipino, ya no parece que estés empastillao en una discoteca! ;)
> 
> @greensouth Mmm, y si le pongo una opción adicional que sea modo disco y se ponga a poner colores aleatorios? De hecho se podrían precargar varios modos: color fijo, brisa mañanera, lumbre de hogar, bar de luces de colores...

... lupanar, casa de pelos... hay tantas posibilidades! jajajajj de hecho la app del magic home tiene alguna movida de esas.

**Comment by RavenSystem** [comment]
@greensouth pues puede que cuando tenga tiempo y ganas lo haga. Por cierto, nueva versión 0.8.15 con el retardo a 300ms, a ver qué tal.

**Comment by greensouth** [comment]
> @greensouth pues puede que cuando tenga tiempo y ganas lo haga. Por cierto, nueva versión 0.8.15 con el retardo a 300ms, a ver qué tal.

actualizando!

**Comment by greensouth** [comment]
Vaya ahora no conectan a homekit... se le ha ido la olla a todos.

**Comment by RavenSystem** [comment]
Vaya cagada, que no había llegado a subir el firmware... ya está arreglado.

**Comment by RavenSystem** [comment]
@greensouth Has podido actualizar ya?

**Comment by greensouth** [comment]
Acaba de terminar hasta el que me daba problemas para flashear, era todo eso, la ruta del main, y va por fin todo genial, sin flashes, sin locuras. Muchas gracias!!!

Oye tengo curiosidad, si se atasca al actualizar, se queda buscando hasta que esta disponible el fichero? O como funciona en caso de quedarse a mitad de una descarga OTA?

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
Cierro incidencia, puesto que ya está solucionado el problema inicial de los LEDs.

> Oye tengo curiosidad, si se atasca al actualizar, se queda buscando hasta que esta disponible el fichero? O como funciona en caso de quedarse a mitad de una descarga OTA?

@greensouth Si se atasca actualizando se pueden dar 2 situaciones:
1.- Que no se haya empezado a descargar la actualización: En este caso, basta con apagar el cacharro, volverlo a encender  y decirle de nuevo que actualice.
2.- Que ya haya empezado a descargar la actualización: apagar el cacharro, volverlo a encender y dejar que continúe la actualización por sí mismo.

Se puede ver el progreso de la actualización/instalación OTA usando el siguiente [comando de NetCat](https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-instructions#lcm-ota-logs) en macOS o GNU/Linux:
`nc -kulnw0 45678`

Si quieres saber más acerca de cómo funciona el sistema LCM (OTA), puedes preguntar tus dudas en su repositorio https://github.com/HomeACcessoryKid/life-cycle-manager . @HomeACcessoryKid te responderá gustosamente a todo.

**Comment by greensouth** [comment]
Pues esto te va a encantar, por cerrar el hilo! Con la intensidad ocurre algo parecido. 
[https://www.youtube.com/watch?v=hihsIyb47wo&feature=youtu.be](url)

**Comment by mafyata** [comment]
Can’t open video link

**Comment by RavenSystem** [comment]
@greensouth Pues eso sí que no es normal.

**Comment by greensouth** [comment]
No te olvides de subir el main.bin! ;)

**Comment by RavenSystem** [comment]
@greensouth Jajajaja, ya lo he revisado, por si acaso. Por cierto, lo del parpadeo ese no me lo explico. EL blanco es manejado igual que los otros colores. Puede que sea por falta de potencia. ¿Puedes hacer más pruebas a ver si te pasa con todas tus tiras LED, o con otros colores?

**Comment by greensouth** [comment]
En todas las de casa pasa eso. Con los colores igual, parpadean en blanco y vuelve al color correspondiente: turquea 100% - blanco - turquesa 90% - blanco - turquesa 80%…

Curiosamente pasa en la mezcla de colores. Los primarios que van sin mezcla no lo experimentan, hacen un parpadeo encendido / apagado extraño, pero no intercalan el blanco.

**Comment by RavenSystem** [comment]
Pero yo pensaba que ya estaba solucionado el tema de la transición de colores.

**Comment by greensouth** [comment]
Y lo está, pasa al cambiar el brillo. El cambio de colores va perfecto.

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
@greensouth Es muy extraño, ya que el brillo es igual que un cambio de color, y de hecho se usa la misma función. Pero está claro que no va bien. ¿A cuánto tienes puesto el Boost (supongo que dará igual, pero bueno)? Es para hacer pruebas con tu misma configuración.

**Comment by greensouth** [comment]
El boost a 0 pero no me ha dado tiempo a probar la 9

Enviado desde mi iPhone

**Comment by RavenSystem** [comment]
@greensouth No te molestes. La v0.9.0 no tiene ningún cambio al respecto.

**Comment by Jaguaza** [comment]
Buenas tardes.

Antes en la 0.8.7 iba mejor los magic home. Ahora en la 0.9 estos dan demasiado saltos de intensidad cuando les das intensidad. Es como si a la vez que subiera o baja intensidad se pone al 100% unos segundos y después se ajusta al tanto % señalado.

Además en mi caso tengo una automatización que por la noche se ponen a un 4% para hacer de luz de cortesía para ir a la cocina en mitad de la noche. El problema es que esta automatización cuando se activa se pone al 100% y después al 4% pegando destellazo en mitad de la oscuridad poco deseable.

Espero por favor puedas solucionarlo, gracias . Te dejo vídeo para que lo veas lo que hace.

https://m.youtube.com/watch?v=Dkmlne14HLU&feature=youtu.be

**Comment by Jaguaza** [comment]
Por favor volver a valores de la 8.0.7 en versiones posteriores hay más fallos que el que he reportado.

**Comment by DanielMosco** [comment]
Hi all. I use koogeek light strip but it is only 2m long. Noticed that ravencore can be applied to magic home controller which is used to power longer light strips. There are few models on Aliexpress. Could someone post a link to the exact controller that had experience to flash? Is the flashing process similar to other devices, i mean connect GPI0 to GND in order to put the device into flash mode? Thanks in advance.

**Comment by greensouth** [comment]
https://s.click.aliexpress.com/e/cBIfDKg

Take a look at this. You can choose from RGB or RGBW controllers.

IOO to ground
3v to 3.3v
TRX to RCV
RCV to TRX
And ground to ground

And you can flash it (IOO to ground to enter flash mode)

**Comment by DanielMosco** [comment]
Thank You Greensouth !!! You just saved me a lot of money as i move to a new home where i want to create a lot of ambient lights.

**Comment by mafyata** [comment]
There are 2 GND on the bottom side. Only one can put it in flash mode. The other one can’t enter flash mode.

**Comment by mafyata** [comment]
Don’t buy with IR because ravencore doesn’t support it. I bought 2 with IR but after flash I can’t use remote controllers. I use it with 5M RGB led strip with 5050 smd , 60smd/1m.

**Comment by DanielMosco** [comment]
Thanks for input !!!!

**Comment by RavenSystem** [comment]
@greensouth Ya puedes probar la última versión (0.9.5) con alguna de tus tiras LED, a ver qué resultados te da.

**Comment by Jaguaza** [comment]
Mucho mejor, diría que mejor que en la versión 8,7.


Aún parpadea un poco cuando le regulas el brillo, pero mucho más suave. Voy a actualizar las 6 restantes que tengo y si veo algo raro te comento si quieres.

**Comment by greensouth** [comment]
Si te soy sincero yo lo veo igual, sigue pegandos saltitos y parpadeos al cambiar el brillo pero tampoco estoy cambiando ese ajuste continuamente. Pero si a @Jaguaza le va mejor, lo aplaudo :)

Por cierto, lo que va a venir muy bien es la parada esa entre cambios de sentido para la persiana, justamente creo que me acabo de cargar un motor por hacer eso. Curiosamente tengo uno en un dormitorio, más barato y que tiene protección en el caso de que los dos canales del relé estén abiertos a la misma vez, y el que compré que se me ha roto, no. Menos mal que va con Prime ;)

**Comment by Jaguaza** [comment]
@greensouth a mí también petardea con el brillo, pero mucho más suave que antes.

**Comment by RavenSystem** [comment]
Estáis con la 0.9.6???

**Comment by Jaguaza** [comment]
Sip actualice ayer todos los led 7 módulos en mi casa y en todos mismo resultado. Pero como digo se ha suavizado ese parpadeo en el brillo. Si lo necesitas te puedo poner vídeo para que veas ahora mismo como efectúa él dimmer.

**Comment by RavenSystem** [comment]
@greensouth la protección para que no se activen a la vez los dos relés ha estado desde siempre. El problema viene con los motores baratos que tienen una mierda de freno o que no aplican frenada en el cambio de sentido, y cuando están en movimiento al cambiar de sentido tienen que hacer el esfuerzo de parar con el motor en vez de con el freno y eso lo quema. Es como si vas en coche hacia adelante y pones la marcha atrás y le pisas antes de haber parado el coche. Byebye embrague y puede que transmisión.

**Comment by RavenSystem** [comment]
@jaguaza prueba a pulsar directamente en la barra de brillo en vez de deslizar el dedo sobre ella. A ver qué pasa.

**Comment by greensouth** [comment]
Sí, al cambiar de color hace esa subida de intensidad instantánea y baja hasta ajustarse al color. Pero uno se acostumbra. Es como si al enviar los valores nuevos, se iniciaran durante unas décimas de segundo con todo encendido, para quedarse en el valor final. Lo de pulsar directamente sobre la barra va bien, sólo parpadea al arrastrar.

**Comment by Jaguaza** [comment]
Exacto es como si cada vez que bajas o subes intensidad volviera a 100. Por ejemplo para pasar lentamente de 68 a 70 el lo interpretará así: 68 - 100 - 69 - 100 - 70. Esos 100 son escasos segundos pero se aprecia el parpadeo. Esta tarde te lo paso en vídeo.

**Comment by greensouth** [comment]
> Exacto es como si cada vez que bajas o subes intensidad volviera a 100. Por ejemplo para pasar lentamente de 68 a 70 el lo interpretará así: 68 - 100 - 69 - 100 - 70. Esos 100 son escasos segundos pero se aprecia el parpadeo. Esta tarde te lo paso en vídeo.

exacto, para cada cambio de valor tanto en color como en brillo, que deduzco que serán los mismos parámetros pero subiendo o bajando el valor.

**Comment by greensouth** [comment]
Wenas Jose, un offtopic total. Estoy intentando aprender algo de las movidas estas con esp-open-rtos el sdk y tal. La verdad es que con el IDE y en lenguaje del arduino todo se ve más fácil.

Querría preguntarte si tú sabrías como se lee un valor analógico con la movida está. Estoy intentando meter un sensor de humedad de la tierra en HomeKit con tu librería y solo veo GPIO_read y Write que deduzco que será para valores digitales.

Una ayudita porfa? Si te digo que ni se en que lenguaje se programa...

**Comment by RavenSystem** [comment]
Analógico, no es buena idea usarlo; yo huyo de lo analógico porque a la larga da muchos problemas con las interferencias y hasta se te puede quedar la placa tostada. Si mal no recuerdo, el esp8266 acepta lecturas analógicas en alguno de sus pines, de 0 a 1V, o 3,3V usando un multiplicador interno, pero yo personalmente ni lo he probado con ese chip.  Por qué no te pillas un sensor I2C y pasas del analógico? Además, así de paso le metes mano al bus I2C con el que se oueden hacer cosas muy interesantes, por ejemplo, puedes controlar 16 relés usando solo 2 GPIOs.
