### ISSUE TITLE
Select Characteristic

### ISSUE THREAD

**Issue by MarcioPlaza** [RavenSystem/esp-homekit-devices#357]
Good Morning,
Download the .bin files and run as per instructions, worked perfectly, however I'm trying to switch to Garage Door and I do not know when I do this? Sorry for the question maybe this is simple but as I'm starting up in development I'm having these difficulties of understanding if I have to compile main.c for main.bin or if it's some simple procedure I'm doing wrong. Thank you and thank you very much.

**Comment by tohmc** [comment]
Do it with Eve App.
Ther you have your Option „Show Setup“
Under this you have your options like device Type and Board Type.

**Comment by MarcioPlaza** [comment]
wow it worked did not know it was that easy.  Thank you so much, I earned my Sunday.
