### ISSUE TITLE
Feature - External toggle mode 3

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#359]
Hi,
I use a normal thermostat to switch a Sonoff Basic to control heater. 
There is two external modes: button or wall switch. 
It would be good if would a third mode, in this mode always switches according the state of RX - Ground (closed or open). 
If thermostat on and if I manually switch off Sonoff then if thermostat changes state switch stays off.
I hope I could explain it. 😊

**Comment by RavenSystem** [comment]
I really dont understand you. 😅

**Comment by claire078** [comment]
Try to ask. 😉
Switch according to RX-Ground opened or closed. 
Don’t change state if there’s a short on RX-Ground.
If it is closed then ON if open then OFF.

**Comment by RavenSystem** [comment]
And "board type = 4" and "external toggle 1 = 2" doesn't make sense?

**Comment by claire078** [comment]
I use it now with this settings. 
What if thermostat OFF I turn sonoff ON then thermostat turn on..?

**Comment by claire078** [comment]
Never mind. I’ll figure it out how could I use it as normal thermostat with sensor.

**Comment by claire078** [comment]
Is this in 0.8.10?
Thanks. 👍

**Comment by claire078** [comment]
I tested it but external toggle mode 3 makes nothing at all. 😟
There is nothing about it in wiki.
