### ISSUE TITLE
Plug when WiFi is not yet available, stays in unresponsive homekit state.

### ISSUE THREAD

**Issue by ageorgios** [RavenSystem/esp-homekit-devices#36]
When I plug in the sonoff device while the WiFi is not available yet, the state stays unresponsive even though the WiFi becomes available later.

If I unplug-replug while WiFi is available it is discovered normally.

**Comment by RavenSystem** [comment]
Sonoff RavenCore 0.2.4 keeps searching wifi for 75 secs, then it turns into AP mode. Wifi must be available into first 75 secs since device boots.

**Comment by ageorgios** [comment]
This means that my FritzBox 7490 router needs more than 75sec... please consider doubling the timeout on a next release

Thanx.

**Comment by RavenSystem** [comment]
Try version 0.2.5.

**Comment by ageorgios** [comment]
awesome thanks!

**Comment by peros550** [comment]
Hi Jose, 

in latest version 3.0.0 I still have this issue. My router is an ASUS RT-AC68U and it takes a lot to boot and activate wifi. Would it be possible to implement it in a way that if no client is connected in AP mode for 1-2 minutes, it will try again to connect to old known Wifi network?

**Comment by RavenSystem** [comment]
Now I have an ASUS ROG Rapture GT-AC5300 and it takes a lot to boot too.

**Comment by xtianpaiva** [comment]
Same situation here with Unifi AP in my house, taking too long to boot... probaby the solution is something similar to @peros550 "retry" proposal. Gran trabajo, saludos!
