### ISSUE TITLE
Magic home single color 

### ISSUE THREAD

**Issue by arturodiazad1** [RavenSystem/esp-homekit-devices#361]
Hola he visto que hay unos controladores magic home de un solo color, permite regular la intensidad, creo que lo podría utilizar además de para las tiras de led de un solo color, para controlar unos focos led dimables que tengo empotrados en el salón ya que admite hasta 96w. Sería posible crear un accesorio HomeKit para este controlador?

**Comment by RavenSystem** [comment]
Sí, pero ya sería con HAA, no con RavenCore.

**Comment by arturodiazad1** [comment]
Ok, espero ya impaciente el lanzamiento de HAA. Gracias
