### ISSUE TITLE
Device 14

### ISSUE THREAD

**Issue by PNM96** [RavenSystem/esp-homekit-devices#368]
Hello! I have a light bulb that, I can't get to work with device 14. It's based on esp8266 but managed by MY9291 LED driver. 
I think the gpio are different ... do you have some suggestions?
The name of this bulb is AiLight. 
Thank you

**Comment by lizzus** [comment]
did you try setting correct pin?

**Comment by PNM96** [comment]
Yes! I have tried with all pins. 
I also posted the question on our group 😁@lizzus

**Comment by RavenSystem** [comment]
MY9291 LED driver is not supported. Only PWM MagicHome based.

**Comment by PNM96** [comment]
Thank you very much! 
In the future can be the possibility that it is supported?

P.S. Thank you for your work and for your support

**Comment by RavenSystem** [comment]
I want to add other RGBW chips, selected under "board type" user option.

**Comment by PNM96** [comment]
Great
