### ISSUE TITLE
Ball valve and Sonoff Dual

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#369]
I’m thinking of buying a 220V rotary ball water valve.
It differs from solenoid valves as it uses two line wires for control (1st to rotate ball to open position, 2nd to close), thus requiring Sonoff Dual in interlock mode.

Any way you can present such valve as 1 device natively?

**Comment by RavenSystem** [comment]
It must be a new device type, with new functions.

**Comment by RavenSystem** [comment]
You will can do it with HAA when it supports water valves.

**Comment by i3laze** [comment]
Actually, RavenCore with dummy switch to store state and bunch of HomeKit rules would do the trick too..)

**Comment by i3laze** [comment]
So.. I've finally got the shipment, including Sonoff Dual R2.
Here's my nifty setup:

It works absolutely great in Device 12 mode (Window Covertings).. with several hickups:

1.  Although Button worked at Device 2 (Dual Switch), it does nothing for Device 12.. (I've tryied board types 1,2,4).
2.  I'd still prefer it as Water Valve type :) can you introduce one for RavenCore some day?
