### ISSUE TITLE
QR CODE pairing enabled for RavenCore firmware

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#371]
Hi to all of you ....
@RavenSystem Josè has enabled the qr code pairing system in the Ravencore firmware.
Now we can use the label below to join our devices to Home APP
![qrcode](https://user-images.githubusercontent.com/34108470/57192334-91b1b780-6f2f-11e9-92ff-d035e1b85892.png)

**Comment by RavenSystem** [comment]
@GPL71 Can I add this image to Wiki?

**Comment by GPL71** [comment]
@RavenSystem ..... It's generated using @MaximKulkin routine

**Comment by RavenSystem** [comment]
@GPL71 I know it, but you are the person who has used your time to generate it.

**Comment by GPL71** [comment]
@RavenSystem  Thank you for your kind consideration ... I'll hope you'll use it in the WiKi

**Comment by mohamedkeven** [comment]
code not working

**Comment by RavenSystem** [comment]
@GPL71 Please, can you create a new qrcode for RC 1.0?

**Comment by GPL71** [comment]
Yes, surely @RavenSystem

**Comment by GPL71** [comment]
![qrcode](https://user-images.githubusercontent.com/34108470/61582491-eb3b8280-ab2b-11e9-8497-2a5aaa0db7bd.png)

This is a Maxim Kulkin routine
