### ISSUE TITLE
REQUEST: Power saving

### ISSUE THREAD

**Issue by kugelkopf123** [RavenSystem/esp-homekit-devices#372]
First of all thank you!
I do not know if it's even possible, but it would be cool if there was some kind of energy-saving feature like in the tasmota firmware. They made the ESP sleeps for X milliseconds. Currently, measured at my USB2Serial adapter, it is 80mAh throughout with Ravencore on it.

Thanks!

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/221
