### ISSUE TITLE
ISSUE - Value different

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#374]
Hi Jose,
I have problem with temp values by thermostat. If I set 20C in Home it shows 20,2C in Ewe app. If I set temp in Ewe it shows correct value in Home App. 
Could You fix it?
Thanks.

**Comment by RavenSystem** [comment]
It is not a bug. Stock Home App rounds to 0.5ºC. I can not do anything, it is managed by Apple.

**Comment by claire078** [comment]
No, I mean different. 
If I set temp 20C in Home app Ewe app shows 20.2C. 
How can I set it exactly to 20?

**Comment by RavenSystem** [comment]
I repeat: You can not do it with stock Apple Home App, because it rounds temp to 0.5ºC, and you are not able to know which temp are you setting exactly.
