### ISSUE TITLE
FREE Flasher tool for RavenCore firmware

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#375]
Hello to all of you ...
@Lizzus and I are the admin of the Italian facebook group and forum dedicated to HomeKit .

Our Group **Homekit Italia Group** is reachable by following links:
[https://www.facebook.com/groups/homekititalia](url)
[https://www.homekititalia.group/](url)
[https://www.twibuk.com/homekititalia](url)
[https://www.instagram.com/homekititalia/](url)
[https://www.youtube.com/channel/UCu-BuCBRsIKAmImSbkvB_LA](url)
[https://www.twitter.com/homekititalia1](url)

We're @RavenSystem fans and followers too and we wants thanks for its great work.

 **Gianluca Scarlino**, an user of our Group has compiled a free flasher tool for our Italian community.
According to Gianluca we want share the tool with all RavenCore users. 
The tool is a contribute for the great work made by Josè.
The tool is setted for RavenCore, but it can be used for other firmware too.

Gianluca Scarlino works hardly to improve features and provide upgrades.
Below link to download the tool and instructions.
https://www.homekititalia.group/forum/viewtopic.php?f=40&t=46

Thank you very much to Josè from @Lizzus and me for allow us publish this message and the links of free Italian Group.
Thank you very much to Gianluca Scarlino for its free wonderful work

For any issue and suggestion open an issue in the forum

Thank you
@GPL71 @Lizzus

**Comment by lizzus** [comment]
This program is for windows O.S. 
Has, among its various features, two buttons: one to flash the OTA firmware and one to flash the latest version of the Ravencore firmware (when the system starts it checks the latest version available. If. a new version is detected the program updates the local repository)

![flash](https://user-images.githubusercontent.com/8824834/57254291-32e45f00-7051-11e9-91ce-fb824cb0eda5.jpg)
Support forum (in italian language, but english accepted) avaible here: https://www.homekititalia.group/forum/viewforum.php?f=40

**Comment by St0nehead** [comment]
Homekit flasher for Windows? What? 🤦🏻‍♂️

**Comment by mafyata** [comment]
Why not? I flashed my sonoff devices with my windows laptop.

**Comment by GPL71** [comment]
> Homekit flasher for Windows? What? 🤦🏻‍♂️

There are a lot of windows users ....
However we hope release for osx users

**Comment by greensouth** [comment]
Well a GUI is always welcomed but I do it with my PI via terminal with my Mac hahaha

**Comment by mafyata** [comment]
Excuse me , but I am not rich like you to own a macbook. This program is useful for me (windows user). Thanks to homekititalia guys.

**Comment by RavenSystem** [comment]
I personally don't use MS Windows, but I think that many people that has iPhone/ipad... uses it. Apple supports MS Windows for iTunes, Apple Music, iCloud, Mail, and a lot of Apple features.

If anyone doesn't want to use this flasher tool, good, but let other people to do what they want. It is a tool that a person has created and shared for free.

And other thing: Maybe some people prefer to flash from a cheaper Windows machine instead from an iMac Pro with 12 cores because some FTDI adapters can be dangerous in some cases and can burn up your USB port... 

Using this software is your choice, but doing destructive critics, no (In my repo, that is not allowed -> Why? My repo, my rules).

**Comment by tohmc** [comment]
Wotka Great!

Thank you for your work!

**Comment by lizzus** [comment]
I'm very happy. If you like it, you can click on "like button" on app
![Q5UAx3hWgIdbmqThFbG6_14_04765bdb5ea91030d06b7279712d477b_image](https://user-images.githubusercontent.com/8824834/57812292-eb568500-776c-11e9-9f1a-ffe44d28c753.jpg)

**Comment by peros550** [comment]
Well done for creating and providing this tool to the community. May I ask two questions. 

Is the tool able to download latest firmware files from github?

What the “Extract Mac” button is used for ?

**Comment by lizzus** [comment]
I answer:
1. Yes tool download automatically latest version of Ravencore, but not from github. It download from our repository
2. The extract Mac is only for extract MAC address of a device.

**Comment by cyberhusky69** [comment]
Hello
I'm new to all this homekit possibilities and fascinated by it. 
Can I run the Ravencore flasher tool in Virtualbox under Windows 10 on my iMac?
Or is it better to use a PC?

Thx

**Comment by lizzus** [comment]
Yes, you can
