### ISSUE TITLE
Rain sensor for new release

### ISSUE THREAD

**Issue by lizzus** [RavenSystem/esp-homekit-devices#376]
Rain sensor is your "sensors list" of new release?

![71CfnB5V-SL _SL1500_](https://user-images.githubusercontent.com/8824834/57253321-bc466200-704e-11e9-9417-064d1a6425e7.jpg)

**Comment by RavenSystem** [comment]
Sure, but has Aple HomeKit raim sensor? Or is it like water leak sensor?

**Comment by lizzus** [comment]
mmm i check... water sure... i don't know if rain exist...

**Comment by GPL71** [comment]
@RavenSystem @lizzus
Apple doesn't include rain sensor...
It's necessary a trick such a water leak connected to the rain sensor in the picture...
