### ISSUE TITLE
Can you add pwm dimmer

### ISSUE THREAD

**Issue by jukorp** [RavenSystem/esp-homekit-devices#38]
can you help me?
I need pwm dimmer. ”One color led strip”

-One button. ”Long press to dimming and short press on/off”
-Initial state is off.
-Remember dimmable settings.

**Comment by RavenSystem** [comment]
Sorry, but this is not a custom firmware build service. If you need a specific firmware for your custom device supporting HomeKit, you can code it by yourself.

Here there are some examples: https://github.com/maximkulkin/esp-homekit-demo
