### ISSUE TITLE
Temperature BBQ

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#381]
Hi,
I would ask if I can use device type 6 or 9 to take temperature of BBQ (between 0 and 350°C) and temperature of meat on BBQ (between 0 and 90C); I would use a different type of sensor form which in wiki...it's possibile? I obtain correct values?

It's possibile to setup an alarm/notification if temperature go outside a range or reach a selected temperature?

**Comment by RavenSystem** [comment]
> I would ask if I can use device type 6 or 9 to take temperature of BBQ (between 0 and 350°C) and temperature of meat on BBQ (between 0 and 90C); I would use a different type of sensor form which in wiki...it's possibile? I obtain correct values?

Other sensors are not supported.

> It's possibile to setup an alarm/notification if temperature go outside a range or reach a selected temperature?

No, that is an Apple HomeKit limitation.
