### ISSUE TITLE
HAA question

### ISSUE THREAD

**Issue by tohmc** [RavenSystem/esp-homekit-devices#386]
In HAA Wiki you explain these:

"t" Type:

Select accessory type:

1: Default. Switch.
2: Outlet.
3: ...
Depending of selected accessory type, there will be different options to configure.

What are the other types?
3,4,5,6... and so on.

**Comment by RavenSystem** [comment]
Other types could be water valve, stateless button, lock mechanism, garage door, motion sensor... There is nothing planed yet.

**Comment by tohmc** [comment]
A ok.
Its the First step and you added only 1 and 2.

Ok what if u make the Type like the Original UUID2?
Example:
Type „BB“ for air purifier

**Comment by tohmc** [comment]
So Everyone can do it on his own. And can select via Type what functions it has and Get an symbol matching to it Function.

**Comment by RavenSystem** [comment]
Because “BB” is a char[2] while 1, 2, 3 are numbers. It is a great difference. Compare numbers is easier than compare strings.

**Comment by greensouth** [comment]
I've ordered a couple of NodeMCU boards for testing!! Can't wait to learn a few things about this.
Thinking of installing a little step motor to build a watering pump with some 3d printer pieces.

I've been schemes and Arduino IDE code to control the steps of the motor, but I'm a bit lost about using HAA instead. 

I would just choose the right device (one which could let an GPIO active in order to continuosly move the motor) right?

**Comment by lizzus** [comment]
I tryed to add follow JSON for a ESP-01
{“c”:{“o”:0,”l”:1,”i”:1},”a”:[{“t”:1,”r”:[{“g”:3}],”b”:[{“g”:0,”t”:1}]}]}
but maybe something is wrong...

**Comment by RavenSystem** [comment]
I think problem are the quotes. Try it: {"c":{"o":0,"l":1,"i":1},"a":[{"t":1,"r":[{"g":3}],"b":[{"g":0,"t":1}]}]}

**Comment by lizzus** [comment]
OMG.... yes it's true. When i Copy and paste string! Now work! Thanks Josè

**Comment by skop1986** [comment]
@RavenSystem 

is it possible to make a web interface for customization, as it is done in tasmota firmware?

P.S. thank you for your work!    what you do is super!

**Comment by lizzus** [comment]
Do you mean in captive portale page?

**Comment by skop1986** [comment]
@lizzus 

I mean, an inteface like this one.
![391_image](https://user-images.githubusercontent.com/38746202/57854094-09b19480-77f0-11e9-9663-1d61c02399d5.png)

**Comment by RavenSystem** [comment]
> is it possible to make a web interface for customization, as it is done in tasmota firmware?

@skop1986 https://github.com/RavenSystem/esp-homekit-devices/issues/206#issuecomment-491975743

**Comment by tohmc** [comment]
Hi, I have 3 questions.

Could you please add Temperatur/humidity sensor to your define# sensor todo-list?
Maybe DHT-11 or/and DHT-22 support like in ravencore firmware.

Is it possible to add MQTT to your firmware? Or will it have to much space usage?

And last one 
How can I make your firmware to show in HomeKit as a sprinkler or other devices and not the standard switch/light/Ventilator ?
