### ISSUE TITLE
Hide switch on device type 6

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#393]
Hi , I have many devices with your software. It is wonderfull. Can you make on/off switch(eve app setup) to hide switch on device type 6. I have NodeMcu and attached DHT22 sensor to it. I flashed it with your firmware and change it to device type 6 to monitor temp and humidity, but I see the switch button. Can we hide this switch button because it is unused, or at device type 16 to make a sensor for temp and humidity?

**Comment by greensouth** [comment]
That is exactly my plan!

I’ve ordered some nodeMCU to attach a motor and build a watering system. I suppose that Jose will add support for more types of devices.

**Comment by mafyata** [comment]
![6BBA37D5-6A98-4717-98F7-C745F9316910](https://user-images.githubusercontent.com/48009267/57922605-c6672c80-78a8-11e9-85c4-b6b48a6ea675.png)

**Comment by RavenSystem** [comment]
RavenCore will not support that. HAA, yes.
