### ISSUE TITLE
HAA configuring accessory as stateless switch

### ISSUE THREAD

**Issue by gijsstegehuis** [RavenSystem/esp-homekit-devices#396]
I configured my button to support single, double and long press, but they show up as separate Homekit buttons that way. Can i configure them to show up as a single stateless Homekit button?

This is the configuration i am using at the moment:
```{
  "a": [
    {
      "r": [
        {
          "g": 4
        }
      ],
      "b": [
        {
          "g": 5,
          "p": 0
        }
      ]
    },
    {
      "r": [
        {
          "g": 4
        }
      ],
      "b": [
        {
          "g": 5,
          "t": 2
        }
      ]
    },
    {
      "r": [
        {
          "g": 4
        }
      ],
      "b": [
        {
          "g": 5,
          "t": 3
        }
      ]
    }
  ]
}```

**Comment by RavenSystem** [comment]
Stateless Homekit button is not supported yet.

**Comment by RavenSystem** [comment]
Supported: https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_0.0.5
