### ISSUE TITLE
Problem with pairing when board 4 was choosen

### ISSUE THREAD

**Issue by kompak23** [RavenSystem/esp-homekit-devices#397]
Hi,
I am very satisfied with your software, but I have one problem. 
When I change board type: 4 and then reset Sonoff to default settings - it is unable to pair with Homekit.
Before changing - everithing work well. 
I need this board type to connect to RX - DS18B20 or DHT sensor.

Have you an idea why it is like so? 

Thanks for reply.

**Comment by RavenSystem** [comment]
Have you try to repower device?

**Comment by kompak23** [comment]
Yes, many times. 
But problem is only when I choose board type: 4.

**Comment by RavenSystem** [comment]
Can you pair with other type board selected and then change to 4 once it is paired??

**Comment by kompak23** [comment]
Flashed device which has default setted "device type = 1" works well. 
After pairing, when I change device type to 4 and then I want to reset every value to default  by pushing button 10 second, then It is unable to pair with HomeApp.

**Comment by RavenSystem** [comment]
But why do you want to do a full reset?

**Comment by kompak23** [comment]
Maybe it is enough to do Wifi Reset, but after should I do pairing again?

**Comment by RavenSystem** [comment]
Wifi reset will not remove pairing info.

**Comment by RavenSystem** [comment]
Fixed in v0.9.3.
