### ISSUE TITLE
question double buttons

### ISSUE THREAD

**Issue by curla92** [RavenSystem/esp-homekit-devices#398]
Hi josè, i would to know if possible clone 1 button with firmware haa. i have a lamp with 2 buttons in kitchen and living room, i want 2 buttons replicated in homekit. thanks

**Comment by RavenSystem** [comment]
I am not sure what you want...

**Comment by curla92** [comment]
Ok. I have a lamp with two physical buttons(1 in kitchen and 1 in living room). I would to replicated these same buttons in homekit with a shelly. I know that it’s impossible divided 2 toggles in 2 different rooms in homekit. I hope it’s clear. Thanks

**Comment by RavenSystem** [comment]
HAA supports multiroom. You can place each switch in different Homekit rooms. But you will need automations to do what you want.

**Comment by curla92** [comment]
resolved. it's work perfectly. very thanks josè
