### ISSUE TITLE
Water valve lost wifi BUG

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#399]
Hey. I noticed such a feature that when Sonoff 12v loses the network or reconnects to another point, it returns the relay to its original position and closes the water for me)

**Comment by mafyata** [comment]
Did you set correct Init State SW via eve app ?

**Comment by netRunner0** [comment]
Init State - 2 0 not working ]

**Comment by RavenSystem** [comment]
@netRunner0 What is the bug? I don't understand if you want a feature that closes relay when wifi is lost...

**Comment by netRunner0** [comment]
Yes, I would like the relay to not change its position when the network is lost)

**Comment by RavenSystem** [comment]
Relay doesn’t change when wifi is lost.

**Comment by netRunner0** [comment]
https://www.itead.cc/ru/inching-self-locking-wifi-wireless-switch.html

I used normal and reverse connections, but once every 1-2 weeks the device either reboots or loses the network and changes the position of the relay.

**Comment by i3laze** [comment]
What exactly happens when you power cycle?
Did you try different Initial State settings?
