### ISSUE TITLE
Lock mechanism external toggle

### ISSUE THREAD

**Issue by bj-tracer** [RavenSystem/esp-homekit-devices#400]
Hello!
Can you make the relay button change its state?
I tried to press button at Sonoff basic and it’s make Lock Open only. It’s nothing to do if I press it second time.
External toggle at gpio14 (or gpio2) doing same as built-in button (gpio0).

**Comment by RavenSystem** [comment]
I forgot to implement it... :D

**Comment by RavenSystem** [comment]
Try ravenCore v0.8.13.
