### ISSUE TITLE
Is it possible to flash Sonoff RF Bridge with RavenCore???

### ISSUE THREAD

**Issue by kkwwm** [RavenSystem/esp-homekit-devices#403]
Hi,
Is it possible to flash Sonoff RF Bridge with RavenCore??? I'd like to add flood and door sensor to HomeKit.

https://www.itead.cc/smart-home/sonoff-rf-bridge-433.html

**Comment by RavenSystem** [comment]
Sonoff RF bridge is not supported. If you want those sensors, you must wait until RavenCore v0.9.0 is released.

**Comment by Soldiiier** [comment]
is this now supported?
