### ISSUE TITLE
Thermostat + Si7021

### ISSUE THREAD

**Issue by skanico** [RavenSystem/esp-homekit-devices#404]
Hello,
After some research, I found some topics explaining the protocol used by Si7021.

[https://github.com/arendst/Sonoff-Tasmota/issues/735#issuecomment-348718383](https://github.com/arendst/Sonoff-Tasmota/issues/735#issuecomment-348718383)

and some source code :

[https://github.com/arendst/Sonoff-Tasmota/commit/253d60fd2b0c3d452d0dd8798ff767a1b143be98](https://github.com/arendst/Sonoff-Tasmota/commit/253d60fd2b0c3d452d0dd8798ff767a1b143be98)

Maybe this could help you add support for this probe.

Thanks

**Comment by mafyata** [comment]
It will be very good if device type 6 support Si7021 sensor. I have sonoff th16 with Si7021 sensor and want to use it. Sonoff recommend to use this sensor  with th10/th16.

**Comment by skanico** [comment]
I had a look in the code, and it seems the implementation of the Si7021 has to be done in esp-open-rtos. I have opened an issue there.

**Comment by RavenSystem** [comment]
If esp-open-rtos supports Si7021 finally, for sure that I will add it in RC and HAA.

**Comment by mafyata** [comment]
I have th16 + si7021 and can test it if you work on it.

**Comment by mafyata** [comment]
If it help:
https://github.com/arendst/Sonoff-Tasmota/commit/253d60fd2b0c3d452d0dd8798ff767a1b143be98

**Comment by RavenSystem** [comment]
https://github.com/SuperHouse/esp-open-rtos/issues/719

**Comment by oremic** [comment]
Hi my th10 and Itead si7021 not work
![image](https://user-images.githubusercontent.com/42227735/66489844-89e2da00-eab0-11e9-9322-1411f40df887.jpg)

**Comment by mafyata** [comment]
Push the plug harder to th10

**Comment by oremic** [comment]
> Push the plug harder to th10
read value no real.
TEMP 0, HUM 2
Si7021: 2
dht: Sensor data: humidity=20, temp=0

**Comment by mafyata** [comment]
Device type: 6
TH Sensor Type: 4
I have th16 + Si7021 and work.

**Comment by oremic** [comment]
Same my photo sensor

**Comment by ateodorescu** [comment]
First of all congrats for the great work you did with this firmware. I have a bunch of Sonoffs and Shellys that already work with Ravencore and wanted to have temp and humidity sensors too.
I have both th10 and th16 (v2.1 for both of them) and a Si7021 sensor. They both don't work.
I have configured in Eve boardType 1, deviceType 6, sensorType 4 and I only get something like temp = 1 and humidity 1. Not sure what's wrong. Any way I can debug this?

Thanks!

**Comment by xrust83** [comment]
temp = 1 and humidity 1
I have the same result
