### ISSUE TITLE
Dimmer Light

### ISSUE THREAD

**Issue by walvespit** [RavenSystem/esp-homekit-devices#405]
Hello, Thank you for this amazing project!!

It is possible with any configuration to dimmer a lamp?

**Comment by mafyata** [comment]
You want this ?
![A9D7F948-AD27-4A2A-8D3B-0E3E25B9E10A](https://user-images.githubusercontent.com/48009267/58655596-1de2af00-8323-11e9-8a48-1e36f49b0f75.png)

**Comment by walvespit** [comment]
> You want this ?
> ![A9D7F948-AD27-4A2A-8D3B-0E3E25B9E10A](https://user-images.githubusercontent.com/48009267/58655596-1de2af00-8323-11e9-8a48-1e36f49b0f75.png)

Yes, Exactly!

**Comment by mafyata** [comment]
This is rgb led strip. I don’t know light bulb with dimmer settings at ravencore. Waiting the Boss to reply :)

**Comment by RavenSystem** [comment]
> It is possible with any configuration to dimmer a lamp?

Actually, no. And RC will not support it, and anything new. But Home Accessory Architect will do it.

**Comment by walvespit** [comment]
> > It is possible with any configuration to dimmer a lamp?
> 
> Actually, no. And RC will not support it, and anything new. But Home Accessory Architect will do it.

Thank you! By the way, i was just checking HAA now and i think at this time RavenCore have more options right? For example i use a sonoff with device type 13, it is not possible in HAA yet, thats correct?

**Comment by RavenSystem** [comment]
Yes. RC is near of its end of roadmap, while HAA is in a early stage. But actually HAA can do many things that RC can not with switches, outlets and stateless buttons.

**Comment by 1nutty1** [comment]
Would the first of your HAA Templates be the correct one to use with a dimmer that has 3 touch switches? (on/off, brighter and dimmer)
Such as the following:
https://github.com/arendst/Sonoff-Tasmota/wiki/Dimmer-switch-with-Nuvoton-chip

**Comment by RavenSystem** [comment]
Dimmer is not supported yet.

**Comment by 1nutty1** [comment]
Thanks for the swift response.
Any idea as to when this might be looked at?

**Comment by RavenSystem** [comment]
> Any idea as to when this might be looked at?

No, sorry.
