### ISSUE TITLE
raven code 

### ISSUE THREAD

**Issue by mohamedkeven** [RavenSystem/esp-homekit-devices#406]
hi i installed ravencore v9 main.bin with blank and rboot bin but when i add in homekit i have to enter accessory code but i haven't i test 11111111 but not work can you giveme the code

**Comment by mafyata** [comment]
Read wiki.
![D005A27E-E03C-427F-B604-B3A90DD37452](https://user-images.githubusercontent.com/48009267/58724734-0ae4e300-83e6-11e9-9cdb-27245bb7abea.png)

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore

**Comment by vojtechtambor** [comment]
just flashed v 0.90 onto a sonoff basic. wifi connected OK, device discoverable in HomeKit

pairing refuses both "02182017" as well as "11111111", tried QR, tried manually entering, tried power cycling several times.. 

Sonoff unit works using manual button to toggle the lamp

thanks

**Comment by RavenSystem** [comment]
Code was, is and will be 02182017 forever and ever. Try version 0.9.1.
