### ISSUE TITLE
Can someone give me steps to Flash a US T1 2ch?

### ISSUE THREAD

**Issue by 1nutty1** [RavenSystem/esp-homekit-devices#407]
I cant get my T1 R2 US Touch Board V1.0. Into flash mode, can anyone give me a step by step breakdown?

**Comment by xtremedays** [comment]
you have to ground GPIO0, shown here...

<img width="933" alt="Screen Shot 2019-03-11 at 8 38 16 PM" src="https://user-images.githubusercontent.com/44820710/58743842-628a5980-848d-11e9-956c-9ab96516e39c.png">

**Comment by 1nutty1** [comment]
Thanks a million.
