### ISSUE TITLE
v0.9.0 Garage Door behavior when dummy enabled

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#408]
I’ve bumped f/w on my two doors (modded Sonoff Basic) from v0.8.7/v0.8.11. One door has NC close sensor, second has NO. Both have dummy switches enabled (off state mostly).

On v0.9.0 when I toggle state via Eve.app or HomeBridge the door is calm, state doesn’t change - status returns to Closed immediately :(
Tried different board types and Inch Values.

UPD: It’s dummies. Doors don’t work with dummies enabled.
However I rely on them (to bypass TouchID requirement for door automations).

UPD2: 
> Now dummy switch is used to secure lock mechanism and garage door.

So now door doesn’t work till dummy switch On? Nah - it could have been done by Eve rule conditions, please turn it off/make it “dummy as lock” option.

P.S. Indeed v0.9.0 now reads sensor state on startup just fine.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/releases/tag/RC_0.9.0
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#8-garage-door

**Comment by i3laze** [comment]
I’d prefer the old way of Dummy..(
I used it for other purpose.
