### ISSUE TITLE
Type 12 Window Covering and Dual R2 button

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#409]
Thanks again for your passion for this HomeKit project!

I’m using Sonoff Dual R2 (https://github.com/RavenSystem/esp-homekit-devices/issues/369#issuecomment-495996616)

Although big white Button worked for Device Type 2 (Dual Switch, triggers SW1), it does nothing for Type 12:
`!!! AdvButton: No function defined`
I've tried Board Types 1, 2, 4. Should the big button generally work for 12? 
I’d love the button to toggle device state.

However pinning these BTN0 and BTN1 pins to GND does the trick (BTN0 opens, BTN1 closes):
![DDB2E2EE-6A29-48CA-AB74-4FFC45303677](https://user-images.githubusercontent.com/16850291/58384606-3a61ad00-7fec-11e9-888f-3666f5e46a3b.jpeg)

2.  I'd also prefer LED staying on after process completed.
Currently DualR2 shows green LED _during_ opening and red when closing.

**Comment by RavenSystem** [comment]
Built-in button has not any function to open, close or stop.

**Comment by i3laze** [comment]
Please, make it to toggle the state.

**Comment by RavenSystem** [comment]
Try version 0.9.1.

**Comment by i3laze** [comment]
Sorry for a delayed feedback.

Regardless board type 1,2,4 button Opens.
Despite my original request was state toggle.. open will solve my current task :)

**Comment by RavenSystem** [comment]
And double press close.

**Comment by RavenSystem** [comment]
And double press close.
