### ISSUE TITLE
Resetting the device / only wifi

### ISSUE THREAD

**Issue by hexardavies** [RavenSystem/esp-homekit-devices#413]
Is there a way to reset the unit but keep the setup of the device.. but only the wifi is reset??
Eg press a input to reset wifi only?

**Comment by RavenSystem** [comment]
RC?? HAA?? In both cases is possible. Please, read Wiki.

**Comment by hexardavies** [comment]
RC setup

**Comment by RavenSystem** [comment]
From Wiki:
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#entering-wifi-ap-mode
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#wifi-reset-default-off

**Comment by peros550** [comment]
@RavenSystem have you thought about using esp-wifi-config latest update ? You may not need to wait 5 minutes before the device turns on the AP mode. I believe Maxim has done some pretty good optimizations there
