### ISSUE TITLE
Device 12 with sonoff 4ch

### ISSUE THREAD

**Issue by kafes33** [RavenSystem/esp-homekit-devices#415]

**Comment by kafes33** [comment]
Hi, Thank you for your greate work!
I have a questions about device 12. Is it poosible use sonoff 4ch as device 12 (Windows shutter) for two windows? Now Is device 12 supports only sonoff 2ch. I set it up sonoff 4ch for 12, but works only 2 channel, but not all 4 channel. 

Thank you for response. Best regards

**Comment by RavenSystem** [comment]
Sorry, it is not possible.

**Comment by kafes33** [comment]
OK, thank you
