### ISSUE TITLE
Thermostat button behavior 

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#416]
Currently pressing a button cycles between Off-Heat-Cool modes.

However people mostly install static configurations: just for heating or cooling.

Please, leave mode configuration to the Eve.app and allow button to cycle just between Off-Chosen mode (either Heat or Cool).

**Comment by RavenSystem** [comment]
I agree.

**Comment by i3laze** [comment]
> Init State TH
I suggest a better last state for a static config:
- off
- on
- last state

**Comment by RavenSystem** [comment]
Try version 0.9.2.
