### ISSUE TITLE
4ch firmware 0.7.1 stuck ? 

### ISSUE THREAD

**Issue by nathsea** [RavenSystem/esp-homekit-devices#418]
Hi I have been trying to update my 4ch to latest firmware but every time I click update firmware it stays stuck after a reboot , is there anything I can do without having to connect back to a computer as it is tucked away !! I have the beta switched to on ? 
The reason for the update is that the connection is a bit poor and doesn’t readily connect. It is right next to a wireless access point as well . 

Cheers
Nath

**Comment by RavenSystem** [comment]
Maybe problem is poor wifi. See LCM network logs when updating.

**Comment by nathsea** [comment]
All sorted now , think you were right WiFi issues. Cheers
