### ISSUE TITLE
RavenCore support SONOFF Mini?

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#419]
Hi,
Ravencore support SONOFF Mini Two Way Smart Switch For Smart Home Can Work With An External Switch?

please, see this link:

https://www.banggood.com/SONOFF-Mini-Two-Way-Smart-Switch-For-Smart-Home-Can-Work-With-An-External-Switch-p-1484758.html?utmid=9067&cur_warehouse=CN

P.S: SONOFF Basic R3 is arriving...

**Comment by RavenSystem** [comment]
It works in the same way as a Sonoff Basic. I can add it knowing its GPIO map.

**Comment by CooperNick** [comment]
Hi
I received Sonoff Minis
What info do you need about GPIO?
Regards

**Comment by RavenSystem** [comment]
Try RavenCore first.

**Comment by den23rus** [comment]
> Hi
> I received Sonoff Minis
> What info do you need about GPIO?
> Regards

Hi please tell me do u try flash sonoff mini by ravencore? what about result? work?

**Comment by CooperNick** [comment]
>> Hi please tell me do u try flash sonoff mini by ravencore? what about result? work?

Not yet, will try to make pogo-pin connector.

**Comment by brunokelo** [comment]
@RavenSystem 

Hello, is it available?

basically the same as the basic sonoff except that GPIO4 is a switch input.

**Comment by skv6** [comment]
Sonoff mini work but like sonoff basic - only remote control - external toggle not supported like in original software.

**Comment by JefersonSchramm** [comment]
Sonoff Mini with external toggle and built-in button configure to enter setup mode:
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":4},{"g":4,"t":0}]}]}
