### ISSUE TITLE
SonOff POW support

### ISSUE THREAD

**Issue by faronov** [RavenSystem/esp-homekit-devices#42]
Is it possible to implement HLW8012 support?
with power reporting to Elgato eve
I remember that's company have the power socket, with power measurement
and also have to report power usage to Elgato Eve app
(I know that official home kit app does not support that)

**Comment by i3laze** [comment]
+1 here. Got 2 Pow R2 units and one Pow v1 to test around.

P.S. Pow R2 flashing is a bit [tricky](https://github.com/arendst/Sonoff-Tasmota/issues/1203#issuecomment-417854726).

**Comment by RavenSystem** [comment]
Sorry, I only work with services supported by Apple HomeKit, and power measurements is not supported.
