### ISSUE TITLE
Relay does not trigger

### ISSUE THREAD

**Issue by RajuRah** [RavenSystem/esp-homekit-devices#420]
Thanks for the amazing work!!!! On sonoff basic works perfect, but thats not enough for me, i can not toggle sonoff and manual switch .... so i tried on shelly 1:

but i have problem with Shelly 1:
   - i was able to flash and get into homekit - works fine with setting up / finding device in homekit etc. also the status on Homekit app shows correctly
   - but the Light turns not ON or OFF - no sounds from relay
   - the wiring should be fine, because I used the same setup to connect to the shelly APP before, which worked fine ... and i was able to toggle

Any idea what can be the problem? i tried with ravencode and HAA flash ...
then tried with tasmotag to check and did not work at all ... any help will be great. Thanks.

**Comment by RavenSystem** [comment]
You must configure your device. Read Wiki, please.

**Comment by RajuRah** [comment]
> You must configure your device. Read Wiki, please.

Thank you for the information, I am searching in WIKI for an 1/2 hour ... and still not sure about where i can configure the device ... do i have to make the change in EVE app?

**Comment by mafyata** [comment]
Yes , you must configure it in eve app.

**Comment by RajuRah** [comment]
> Yes , you must configure it in eve app.

Thank you very much, it works perfect ... :)
