### ISSUE TITLE
How reset Shelly 2.5 ?

### ISSUE THREAD

**Issue by Fudalii** [RavenSystem/esp-homekit-devices#421]
Hello.

How reset Shelly 2.5. After entering the WiFi (eg. I have mistaken WIfI) i can't reset device. 

Reset button works only when the device is added to the application and the BoardType is set.

Kamil

**Comment by epoppis** [comment]
Hi,

Taken from documentation (https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore):

> When a power cycle occurs, device will try to connect to its known wifi network. If after 5 minutes wifi network is unreachable, device will enter in AP mode so you can connect to it and reconfigure wifi settings.
