### ISSUE TITLE
Question: is Sonoff BasicR3 Supported?

### ISSUE THREAD

**Issue by dkossman** [RavenSystem/esp-homekit-devices#422]
Does this firmware/installation process work with the new Sonoff BasicR3?  https://sonoff.itead.cc/en/products/sonoff/sonoff-basicr3

My understanding is that this version of the Basic Sonoff switch includes a REST API which could be used e.g. with homebridge , but it still requires use of the Sonoff eWeLink app for initial setup and still "calls home" to the Sonoff back end.

thanks

**Comment by RavenSystem** [comment]
With HAA, sure. With RC, I did not test it, maybe somebody will do it.

**Comment by RAZRu** [comment]
> Does this firmware/installation process work with the new Sonoff BasicR3? https://sonoff.itead.cc/en/products/sonoff/sonoff-basicr3
> 
> My understanding is that this version of the Basic Sonoff switch includes a REST API which could be used e.g. with homebridge , but it still requires use of the Sonoff eWeLink app for initial setup and still "calls home" to the Sonoff back end.
> 
> thanks

Works fine with default settings RC(dev type1 board type 1)
