### ISSUE TITLE
HAA looks frozen when in Setup mode

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#426]
Doing my first steps with HAA - very promising.
I’ve just enabled Sonoff Basic R2 with a relay and a button - was working great.

Then I’ve _just_ added a LED (seems, I forgot to invert it) and device is irresponsive now:
LED blinks on startup and then glows, button doesn’t trigger relay, _not responding_ in Home.app. Can’t go setup by 10x button too.

Please, give a try: 
{"c":{"l":13},"a":[{"r":[{"g":12}],"b":[{"g":0,"p":0},{"g":0,"t":0}]}]}

**Comment by RavenSystem** [comment]
Can you post logs, please?

**Comment by i3laze** [comment]
Hi, yeap, but during the day.

**Comment by RavenSystem** [comment]
> P.S. iOS Safari inputs italic double quotes “ (not ") into JSON field on setup webpage, can you fix this?

Please, open a new issue about this because I can forget. :)

**Comment by RavenSystem** [comment]
For Sonoff is better to enable internal pull-up resistors (In Shelly it must be disabled). But if your device doesn't respond, you must erase and flash it again. Omitting LED inverted should not have negative effects, only it will work in the opposite way.

**Comment by i3laze** [comment]
UPD: Cold start made it working.. with a configuration older, then I remember I've set.
Sorry, no traces left in log.

Hovewer, I guess.. the cause might be this one:
`HAA` ! ERROR: Invalid JSON
though the device may have stuck with LED enabled in setup mode.

I suggest when such JSON startup error occurs some LED signaling should be in place, like S-O-S in morse code.

P.S. Here's most basic template for Sonoff with button and switch:
{"c":{"l":13,"i":1},"a":[{"r":[{"g":12}],"b":[{"g":0,"t":0}]}]}
I figured out GPIO from a device library at Tasmota Wiki here:
https://blakadder.github.io/templates/sonoff_basic.html

**Comment by i3laze** [comment]
I've also noticed setup page doesn't do JSON validation
(however device does it on boot, which may be not enough)..

And HAA doesn't format JSON input field to a compact one-liner after Save. It might be visually nice.

**Comment by i3laze** [comment]
UPD: Another Cold start: now device is in "Invalid JSON" + SoftAP mode.
If I hadn't have Serial attached I wouldn't have known I should go look for a SSID. 

Definitely some GPIO13 signaling scheme required.

**Comment by RavenSystem** [comment]
It is not possible, because LEDs are defined in JSON.
