### ISSUE TITLE
Raven core v0.3 about the device type 8

### ISSUE THREAD

**Issue by sunwon2018** [RavenSystem/esp-homekit-devices#43]
I like this program very much. It’s really useful. 
I am trying to control my garage door. I saw the device type 8 . Even you said it’s still not  complete. I can Trun on the door but just HomeKit displays  it’s opneing and looks like waiting a status returned. 
Could you please tell me about these gpio4 gpio5 gpio14 function. How to connect them so that esp8266 can get a status of the door? 
 ThankS

**Comment by RavenSystem** [comment]
Garage door is not completed. gpio5 and 14 will be used for open and close sensors. gpio4 will not be used.

**Comment by GPL71** [comment]
@RavenSystem
Jose garage door it's a wonderful idea.. Wich SONOFF will be compatible? 4CH pro?
Some garage door hasn't switch for open/close position, but use current limiter (in italy we have this model too)
Then is possible set a timer for open and close operation?

Thank you for this wonderful work

**Comment by GPL71** [comment]
I'm sorry I'd forgot
Is it possible manage rollers?

Thank you again

**Comment by RavenSystem** [comment]
Garage Door update has been released.
