### ISSUE TITLE
iOS 13

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#430]
Hi, no settings(
![IMG_0234](https://user-images.githubusercontent.com/44049295/59712035-c9499a00-9225-11e9-9b6d-0036483f5d22.png)
![IMG_0235](https://user-images.githubusercontent.com/44049295/59712043-cbabf400-9225-11e9-933b-624770cd7585.png)

**Comment by archiolochos** [comment]
same here. I am using ios13beta2.i am sure that there were settings in ios13beta1.

**Comment by claire078** [comment]
You must set it to off and on again.

**Comment by i3laze** [comment]
Cool house у тебя!
I guess that's an Eve.app bug..  to be fixed when iOS 13 released in autumn.

**Comment by caligari74** [comment]
This didn't work for me on beta2.
I slid "Show Setup" to off and back to on.  The settings still don't show.

**Comment by RavenSystem** [comment]
iOS 13 is beta, so testing actual EVE app with it not make sense.
