### ISSUE TITLE
DHT11/22 as Sensor in Home App

### ISSUE THREAD

**Issue by Codkit** [RavenSystem/esp-homekit-devices#431]
Hi José

Thanks for all your time and efforts ,this really improve my home automation system.
Right now i have a question if its possible to use dht11/22 as a sensor in home app so it can trigger remotely other homekit devices in the same network ?
Currently if i create a new automation in home app,the “sensor” is greyed out (device type 5/6/9/ in Eve).
Thanks again for all your contribution !

Regards
Cod

**Comment by mafyata** [comment]
IFTTT

**Comment by claire078** [comment]
Eve app

**Comment by Codkit** [comment]
Thanks mafyata and Claire, can you show me how in ifttt or eve ? Thank you

**Comment by St0nehead** [comment]
https://apps.apple.com/kz/app/home-3/id995994352

You can add new automation with your “greyed” sensors within this app. Then, your automations appears in Home.app

**Comment by Codkit** [comment]
I wish the app is free... anyway thanks for the link
