### ISSUE TITLE
Garage door: Has stop step options..

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#436]
Noticed a **bug**, which might (or might not) cause cascade/wrong behavior:

With Has Stop Step On and NC both Off or On:
State: _Open_ -> Closing -> I click -> Opening back.. -> Open.
Device doesn't respect _"Has Stop Step On"_ and does 1 click only.

It still does two clicks when Closed -> Opening -> I Click -> Closing.

UPD: Not a bug actually, indeed some _Nice_ garage doors have **current** RavenCore scenario:
_Open - Stop - Close - Open_
Most others, like mine, have:
_Open - Stop - Close - Stop_

I suggest "Has Stop step" should be a detailed 0/1/2 option.
Guys, please post which one is your garage door's stop behavior via remote.

**Comment by i3laze** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/428#issuecomment-504132744

**Comment by i3laze** [comment]
UPD: I suggest just fix it back.
_Nice_ doors have an option to configure it to RC default behavior.

**Comment by RavenSystem** [comment]
@i3laze Thanks!
