### ISSUE TITLE
SonOff Basic Switch not working

### ISSUE THREAD

**Issue by felixmayr** [RavenSystem/esp-homekit-devices#44]
Soldered wires to GPIO 14, Ground and connected a switch to it but Sonoff not responding to input.

**Comment by yukonx** [comment]
WIKI  

eve app
https://github.com/RavenSystem/esp-homekit-devices/wiki/Sonoff-RavenCore#user-settings

GPIO14
https://github.com/RavenSystem/esp-homekit-devices/wiki/Sonoff-RavenCore#gpio14-toggle-default-off
