### ISSUE TITLE
HAA updates

### ISSUE THREAD

**Issue by xtremedays** [RavenSystem/esp-homekit-devices#440]
Just a quick question, is there a quick easy way to update the firmware on haa devices or do you have to go into setup mode?

**Comment by i3laze** [comment]
Looks like:
1. Power cycle
2. 10x toggle via Home.app
3. Logging into your router to find correct IP-address DHCP lease
4. Logging into web interface of HAA
5. Checking OTA Update box + Save.

**Comment by xtremedays** [comment]
That’s what I read too, but if they’re light switches behind a wall it’s not the easiest thing to cycle the power!

**Comment by RavenSystem** [comment]
Actually, that is the only way to update HAA. Other methods will be added in the future. Remember that HAA is in a beta status, and it has only a few functions.

**Comment by dwhp** [comment]
Hi José. 

May I suggest one future method to reset WiFi in HAA is to have the option to set a gpio dedicated to do so. Like hold for 10secs or whatever. Then we could add or use buttons as dedicated Wifi reset. 

Sorry to put this in the bottom of a closed issue and if I missed reference to idea prior.

**Comment by RavenSystem** [comment]
@dwhp That option is one that will be in future versions.
