### ISSUE TITLE
Th as basic

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#441]
Hi , I have Sonoff TH16. Can I configure it in eve to work as Sonoff basic(without temp and humidity info, only switch)? Will it be safe for use ?

**Comment by RavenSystem** [comment]
Of course. It is safe, and you will be able to manage 16A instead 10A. I used that setup with some devices to power 3500W without risks.

**Comment by mafyata** [comment]
Board type 1 or 2 ?

**Comment by RavenSystem** [comment]
That depends of your TH16 model. But board type only makes sense if you use an external toggle connected to sensor GPIO.

**Comment by mafyata** [comment]
![F6D6562F-2FF6-48AB-A5E1-AAAB33C7D332](https://user-images.githubusercontent.com/48009267/59974445-fe9f1080-95b4-11e9-9166-362b10e37e2a.jpeg)
I think mine is newer model, I bought it May 2019
