### ISSUE TITLE
Using non sonoff devices - ESP8266 based power strip

### ISSUE THREAD

**Issue by Nekomae** [RavenSystem/esp-homekit-devices#442]
Hello

Thanks for the amazing firmware!

I was wondering if it would be possible to use this firmware with a non sonoff ESP8266 based power strip. It's known as SM-SO301, koi or teepad power strip. 4 independent relay mains sockets and bank of 4 usb ports via single relay. 

Someone has it working with tasmota and has shared GPIO info. 

https://github.com/arendst/Sonoff-Tasmota/wiki/SM-SO301

I don't know much about programming but it seems like it might be possible to add as ESP8266 based and we know the GPIO info. It is also similar hardware to sonoff.

Could one of the profiles for sonoff be modified to work?

Thanks!

**Comment by mafyata** [comment]
i am using this led controller for my led strip. It is not sonoff. I use ravencore with esp 8266 and esp 8285.
![1F08F608-61F8-4DD9-B4A9-13B4686E6E33](https://user-images.githubusercontent.com/48009267/60074368-67a89480-972b-11e9-9c05-0244d30e9eb7.jpeg)

**Comment by Nekomae** [comment]
very cool!

How did you got about doing it?

**Comment by mafyata** [comment]
Same way you flash sonoff. Open the case of controller and solder cables. I will search for instructions for soldering.

**Comment by mafyata** [comment]
![6D3E2427-0E2E-430A-BC90-43E3298D4329](https://user-images.githubusercontent.com/48009267/60114344-5b005c80-977c-11e9-81f4-616588a134ff.png)

**Comment by mafyata** [comment]
Ground and IOO connect together.
You can read here:
https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-LED-strip-controller

**Comment by Nekomae** [comment]
ahh i see. The programming bit is no problem. 

Did you have to change the code at all?

**Comment by Nekomae** [comment]
ahh i see. The programming bit is no problem. 

Did you have to change the code at all?

**Comment by mafyata** [comment]
Code?

**Comment by Nekomae** [comment]
ahh i mean the ravenscore source code. Or did you just pick the nearest device listed in the firmware?

**Comment by mafyata** [comment]
While flashing use the same code - esptool.py........ In eve app use device type 14

**Comment by Nekomae** [comment]
ok. So you used the eve app to configure the GPIO for LED's. 

Can I use the same device type to turn on 4 power relays for each socket?

**Comment by Nekomae** [comment]
Actually there are 5 relays. 

/Users/NekoNeko/Downloads/43324706-6d14d972-917a-11e8-9be3-b6f6f4ef4dcf.JPG

**Comment by Nekomae** [comment]
Actually there are 5 relays. 

https://user-images.githubusercontent.com/3240875/43324706-6d14d972-917a-11e8-9be3-b6f6f4ef4dcf.JPG

**Comment by mafyata** [comment]
![D06C63CB-8E75-4593-926B-23491F10F0CA](https://user-images.githubusercontent.com/48009267/60169009-89c71300-980e-11e9-881f-3f05a241fe4d.png)
![7AAEC9CA-FA53-4F69-B59C-CA0B95529960](https://user-images.githubusercontent.com/48009267/60169012-89c71300-980e-11e9-9bb3-df0826a13667.png)
This is for led strip in eve app. Your picture is not for ravencore. I think that you can’t use this device type for relays. See wiki page. There may find answer and device type for your relays.

**Comment by Nekomae** [comment]
The closest device is the 4 ch switch. 

It appears that i can change the GPIO pin numbers in the source code and recompile it. 

I would still need to control one more relay. I don't know if this is possible to add in the code or not. 

This is what i was asking originally. Can the source code be modified to work with this power strip.

**Comment by RavenSystem** [comment]
Use Home Accessory Architect firmware instead RavenCore.

**Comment by Nekomae** [comment]
D'OH!

Reading the first paragraph of HAA it seems exactly what i need. 

Thanks for the help!
