### ISSUE TITLE
Sonoff s20 pcb revisions and ravencore compatibility + power mods

### ISSUE THREAD

**Issue by Nekomae** [RavenSystem/esp-homekit-devices#443]
Just some useful info i found from flashing varios sonoff s20 sockets and the different pcb revs out there. Hope it helps someone. YMMV.

PCB Rev 1.3
Had to add 4.7uf or 10uf capacitor to the 3v3 power line as close to 3v3 regulator as you can fit it. This helped with non responsive sockets in homekit. Super stable now. 

PCB 2.3 (possibly unofficial)
Has extra capacitor mentioned above. Could only flash with non OTA firmware or socket would not get past initial OTA install. No pcb fuse or air gap.

**Comment by RavenSystem** [comment]
Many thanks for your info!

**Comment by fanlessfan** [comment]
@Nekomae is PCB Rev 1.3 print "S20_US v1.3"? thx
