### ISSUE TITLE
Shelly 1PM doesn't change relay state

### ISSUE THREAD

**Issue by GrzesKe** [RavenSystem/esp-homekit-devices#444]
Hi, I have problem with my shelly 1 PM.I changed firmware to Raven Core 0.9.6.
It is possible to add shelly to HomeKit, but it doesn't change the state of the relay.
In EVE app I changed board type to 3 before connecting shelly to 230V. It didn't help.
Any sugestions?

**Comment by RavenSystem** [comment]
Shelly 1PM is not supported by RvenCore. You must use Home Accessory Architect firmware.
