### ISSUE TITLE
Is Sonoff RF Bridge 433 already supported?

### ISSUE THREAD

**Issue by kkwwm** [RavenSystem/esp-homekit-devices#445]
Hi,
is the newest version of RavenCore suport RF Bridge like this: https://sonoff.itead.cc/en/products/appliances/sonoff-rf-bridge-433 ??

Regards,
Konrad

**Comment by RavenSystem** [comment]
No, sorry. RF functions will not be supported.

**Comment by Alinoe1** [comment]
Are you working on it?
