### ISSUE TITLE
Request new feature: triggering http urls

### ISSUE THREAD

**Issue by massimo79** [RavenSystem/esp-homekit-devices#446]
@RavenSystem 
Hi! Would it be possibile for HAA to implement a dummy switch/sensor to trigger an http request (or a short bit.ly url)? Thanks, it would avoid many users to implement node.js servers like Homebridge and would be a really nice feature to add!

**Comment by RavenSystem** [comment]
It is interesting.

**Comment by massimo79** [comment]
@RavenSystem 
I can give you a couple of examples if you want. My a/c (Daikin) and my alarm panel (Visonic) have optional online controllers. Both of these can be DIY with esp8266 devices running native api’s.

The result is that they can be easily controlled via http calling  internal ip’s or even remotely via port forwarding.

Would be great to remote access via Homekit triggering the http commands, for example:

http://ip.address/armhome 
http://ip.address/armaway
http://ip.address/off

Furthermore they are always in sync even when controlled locally with ir remotes!!!

Tks! Keep up the great work!

**Comment by i3laze** [comment]
Sorry for highjacking, I’ve got opposite request:
Allow HAA to be triggered (on/off/toggle) by http-GET request (via wget or curl).

Same reason: to get rid of HomeBridge.

**Comment by noobydp** [comment]
@massimo79 could you link me to the daikin API info?

**Comment by massimo79** [comment]
@noobydp check these out:
https://github.com/andreacucci/IR-Daikin-Server-ESP8266
https://github.com/ael-code/daikin-control

**Comment by RavenSystem** [comment]
Featured added with v1.3.0.
