### ISSUE TITLE
Tested device

### ISSUE THREAD

**Issue by egorist** [RavenSystem/esp-homekit-devices#449]
Hello. I bought esp device to control dc motor. I don't know it's [name,](https://aliexpress.com/item/32944121554.html) but it is working good with ravencore device 12 board type  2, external toggle 1. Maybe it helps someone.
![IMG_6349](https://user-images.githubusercontent.com/43891696/60760428-d1834100-a03d-11e9-990a-1b5750db5a7e.jpeg)

![HTB17Sc_XozrK1RjSspmq6AOdFXae](https://user-images.githubusercontent.com/43891696/60760457-53736a00-a03e-11e9-8420-64e73c8ee951.jpg)

**Comment by RavenSystem** [comment]
Many thanks!!

**Comment by egorist** [comment]
sorry, but is it possible to add this icon to device 12?
![faucet-icon](https://user-images.githubusercontent.com/43891696/60772514-4dde5880-a100-11e9-98fc-a361424c6023.jpg)

**Comment by RavenSystem** [comment]
No, that is a different accessory type. In future, HAA will let you do what you want.
