### ISSUE TITLE
sonoff basic "No response" status

### ISSUE THREAD

**Issue by 3uperduck** [RavenSystem/esp-homekit-devices#452]
My homekit device has 1 sonoff basic @ 0.5.4, 6 sonoff basic @ 1.0.0 and with 2 homepods.
AP is 1 Cisco Aironet 3702i fat ap mode.

They're randomly no response happen when I open homekit, have to wait about 10~60sec or even more. I've no idea what's wrong. Btw, 2 homepods never happened.

I've tried to change other ap, re-flash the devices, isolate the device with 0.5.4 firmware but it just keeps happening. 

When devices show "no response" I ping it, it replies ping, and if I ping a good condition device around 3 or more mins, device show "no response" unreachable in homekit, but still reply ping, dame wired.

Does anyone know what to deal with?

Thanks.
![IMG_2311](https://user-images.githubusercontent.com/52876446/61180366-c638a280-a647-11e9-935d-7b659c0b47ea.PNG)
![IMG_2312](https://user-images.githubusercontent.com/52876446/61180367-c638a280-a647-11e9-8beb-190d6eaeb7bb.PNG)

**Comment by RavenSystem** [comment]
Your network has a problem managing multicast DNS traffic.

**Comment by 3uperduck** [comment]
Ok, I'll change a router to try soon

**Comment by RavenSystem** [comment]
Maybe it is a router configuration problem.

**Comment by 3uperduck** [comment]
![image](https://user-images.githubusercontent.com/52876446/61212044-b26a6a80-a733-11e9-8790-d22eccb5665f.png)
Should be not, that's a simple, basic, ISP provided device.

**Comment by RavenSystem** [comment]
Can you show wan/lan and wireless options?

**Comment by 3uperduck** [comment]
sure

for wan/lan on router, yeap, that's all.
![image](https://user-images.githubusercontent.com/52876446/61216411-df247f00-a73f-11e9-9707-c5c6421b57fb.png)
for wireless
![image](https://user-images.githubusercontent.com/52876446/61217627-ad60e780-a742-11e9-9768-9b662e325181.png)

If need anything more just tell me, thanks

**Comment by RavenSystem** [comment]
Try setting DTIM to 3, and enabling Reliable multicast to WGB. Remember to reset your router to ensure changes will be applied.

**Comment by 3uperduck** [comment]
Nothing change, I think maybe my router doesn't support mDNS? I borrowed another one from my friend. Let's see.

**Comment by 3uperduck** [comment]
It seems Cisco AP configuration has some problem. Yesterday I use original Cisco AP via netgear router I borrowed, it just work at fist few hours (around 2~3) than, all device randomly "No Response". Then I try AP on netgear's router, it works fine till now.

I'll try to use CLI to config more, thanks.

**Comment by RavenSystem** [comment]
I hope you can solve the issue with your Cisco IOS.
