### ISSUE TITLE
Request new feature (HAA): switch timeout.

### ISSUE THREAD

**Issue by fcesc** [RavenSystem/esp-homekit-devices#457]
Hi! 

Would be possible to implement a timeout option for switches that after few seconds (lets say 2, 3, ...) they come back to initial state? This option it would be useful for an electric strike lock that needs a pulse to open the door.

I knows that you can achieve this feature from homekit app, but it would be interesting in order to prevent that door would remain opened accidentally if homekit connection has lost.

BR,
Francesc.

**Comment by RavenSystem** [comment]
Don't worry, inching mode is planned since the beginning because is an actual RavenCore feature.

**Comment by RavenSystem** [comment]
Done.
