### ISSUE TITLE
Question - Edge Switch Type for Shelly 

### ISSUE THREAD

**Issue by wsc96** [RavenSystem/esp-homekit-devices#460]
I’ve ordered a couple of Shelly 1 devices that i’d like to run RavenCore on (I'm currently doing this with a few Sonoff Basic devices). My question is regarding the Shelly button type of “Edge” and whether this is supported with RavenCore?

From the Shelly API docs - “an "edge" switch. In this input mode, every switch state transition causes a toggle of the output state.” (https://shelly-api-docs.shelly.cloud/#shelly-family-overview)

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#external-toggle1-2-default-0
