### ISSUE TITLE
Hello. Compile

### ISSUE THREAD

**Issue by totkom** [RavenSystem/esp-homekit-devices#461]
I have a question.
Can I compile edited HAA/main.c - I want to change the config.password.

In toolchain I have error 127

$ make
CC /c/jj/esp/sdk/esp-open-rtos/open_esplibs/libmain/timers.c
/bin/sh: xtensa-lx106-elf-gcc: nie znaleziono polecenia
make: *** [/c/jj/esp/sdk/esp-open-rtos/open_esplibs/component.mk:17: build/open_esplibs_libmain//timers.o] Error 127

Thank's
JJ

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/blob/master/LICENSE#L179
