### ISSUE TITLE
OTA Setup Bug

### ISSUE THREAD

**Issue by maslyankov** [RavenSystem/esp-homekit-devices#462]
Having a hard time to setup devices because LCM is not showing the captive portal...
Here is a screen of me trying to do it via a Mac and then an iPhone.
![screen](https://i.ibb.co/z4nGBr0/Screen-Shot-2019-07-31-at-12-43-46.png "Screen")
Ignore the AAA, tried to scroll 😄

**Comment by Yoshi325** [comment]
Same here. No captive portal appears.

**Comment by Yoshi325** [comment]
Just got it after power-cycling multiple times (as suggested on Discord).

**Comment by maslyankov** [comment]
Yes, power-cycling does help, but it feels like a game of chance
