### ISSUE TITLE
SONOFF 4CH PRO - HAA Template

### ISSUE THREAD

**Issue by fcesc** [RavenSystem/esp-homekit-devices#466]
Hi,

Here you are the template for the SONOFF 4CH Pro (buttons + relays).

{"c":{"l":13,"i":1},"a":[{"r":[{"g":12}],"b":[{"g":0,"p":0},{"g":0,"t":1}]},{"r":[{"g":5}],"b":[{"g":9,"p":0},{"g":9,"t":1}]},{"r":[{"g":4}],"b":[{"g":10,"p":0},{"g":10,"t":1}]},{"r":[{"g":15}],"b":[{"g":14,"p":0},{"g":14,"t":1}]}]}

José Antonio, thank you for your great job.

**Comment by Partizan7676** [comment]
is it works for latest HAA release ? 0.0.7 ?

**Comment by RavenSystem** [comment]
That template is deprecated old style.
