### ISSUE TITLE
Wait for the SSID forever

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#468]
I personally prefer “wait for the SSID forever”
Me too.I personally preferI personally prefer “wait for the SSID forever”
Me too.
_Originally posted by @RavenSystem in https://github.com/RavenSystem/esp-homekit-devices/issues/328#issuecomment-481803451_

I took down my outdoor AP for a maintenance bigger than 300 sec..
And now several RC devices are stated unresponsive and broadcast own SSID.

What will happen if I just power cycle them? Will they reconnect to WiFi?
How about at last implementing “wait/scan forever” as an option?

How currently client roaming works? What if RC connected to -80 dBi AP and a -50 dBi AP (with a same SSID) comes back online?

**Comment by peros550** [comment]
Latest version of [esp-wifi-config](https://github.com/maximkulkin/esp-wifi-config/issues/13) does both. It fires up an AP pretty quickly (maybe in 30sec) but at the same time it waits for the known SSID forever. I believe it combines the best from both worlds.

**Comment by RavenSystem** [comment]
Security issue fixed. Now device will wait for the SSID forever.
