### ISSUE TITLE
Shelly 2.5 Window Covering Opening/ Closing Time

### ISSUE THREAD

**Issue by Hanimaniac** [RavenSystem/esp-homekit-devices#470]
Hello at all,
i use the shelly 2.5 for window covering. 
In my livingroom, I have a huge window which opening time is about 64 seconds. 
In the eve app, the max open/ close time is 60s. Is there a possibility for chanching the max time?
Thanks
Martin

**Comment by RavenSystem** [comment]
Times increased to 90 secs with RC 1.1.0.

**Comment by Hanimaniac** [comment]
Thank You. Thats good news.
