### ISSUE TITLE
Sonoff T1 R2 US Touch Board V1.0 flashing issue

### ISSUE THREAD

**Issue by 1nutty1** [RavenSystem/esp-homekit-devices#473]
Hi all, hoping someone can help.
I am having issues getting a Sonoff T1 R2 US TOUCH BOARD V1.0 into flash mode.
Any definitive way to get this into flash mode?
![IMG_5552](https://user-images.githubusercontent.com/38528842/63669144-91d50c00-c7d9-11e9-8c3c-e12b46fe0fba.jpg)

**Comment by pandarek** [comment]
Try this
https://user-images.githubusercontent.com/36041520/50041600-25bad980-008a-11e9-840b-86e431c12968.jpg

https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-T1-UK,-EU,-and-US

**Comment by 1nutty1** [comment]
> Try this
> https://user-images.githubusercontent.com/36041520/50041600-25bad980-008a-11e9-840b-86e431c12968.jpg
> 
> https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-T1-UK,-EU,-and-US

Thanks, will give it another go tonight when I get home.

**Comment by 1nutty1** [comment]
> Try this
> https://user-images.githubusercontent.com/36041520/50041600-25bad980-008a-11e9-840b-86e431c12968.jpg
> 
> https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-T1-UK,-EU,-and-US

No luck. I try shorting R19 to ground and the button light stays stable but I am unable to erase the flash, I try double clicking S1 same result, I try holding the capacitive button and then pressing S1 nothing...
When I power on without shorting R19 to ground the button light is stable but if I dont it pulsates...

Any other ideas?

**Comment by 1nutty1** [comment]
> Try this
> https://user-images.githubusercontent.com/36041520/50041600-25bad980-008a-11e9-840b-86e431c12968.jpg
> 
> https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-T1-UK,-EU,-and-US

Just had a good look at the chip, the one I have has an ESP8285... would this make any difference?

**Comment by pandarek** [comment]
ESP8285 is just like ESP8266 but with 1MB built-in Flash.

You need to connect GND and GPIO0 together and then connect the power supply (from USB flasher). Then you can disconnect GPIO0.

Before uploading new software, delete the current software.
(esptool.py -p / dev / <your_ESPPort> erase_flash)

Then, set your device in flash-mode again (disconnect power, reconnect GND + GIPO0, reconnect power).

One more thing, I had a problem with USB power, too low power. (Sonoff Touch T1 EU)
I connected 3.3v and GND from external power supply (about 1A). Only TX and RX to usb flasher.

**Comment by 1nutty1** [comment]
> ESP8285 is just like ESP8266 but with 1MB built-in Flash.
> 
> You need to connect GND and GPIO0 together and then connect the power supply (from USB flasher). Then you can disconnect GPIO0.
> 
> Before uploading new software, delete the current software.
> (esptool.py -p / dev / <your_ESPPort> erase_flash)
> 
> Then, set your device in flash-mode again (disconnect power, reconnect GND + GIPO0, reconnect power).
> 
> One more thing, I had a problem with USB power, too low power. (Sonoff Touch T1 EU)
> I connected 3.3v and GND from external power supply (about 1A). Only TX and RX to usb flasher.

Thanks a million, I will organise external power and give it another go.

**Comment by 1nutty1** [comment]
> can you post a photo of the other side of this board?

I will post this afternoon for you when I get home.

**Comment by 1nutty1** [comment]
> can you post a photo of the other side of this board?

![IMG_5569](https://user-images.githubusercontent.com/38528842/63869524-90156f00-c9b8-11e9-8b57-a4fe436501a0.JPG)

**Comment by xtremedays** [comment]
I’ve done a few of the us t1 3ch by jumping as per pic in the link. Hold it on, power up, wait 5ish seconds and disconnect the r19. Worked every time for me

**Comment by walvespit** [comment]
i also did some t1 and t2 using the R19 , try both sides of it!

**Comment by 1nutty1** [comment]
> i also did some t1 and t2 using the R19 , try both sides of it!

Thanks for this, I have tried that to no avail.

**Comment by 1nutty1** [comment]
> i also did some t1 and t2 using the R19 , try both sides of it!

What TTL adapter did you use?

**Comment by 1nutty1** [comment]
Still pulling my hair out with this one, what adapters are you guys using?
Mine is the CH34
![IMG_5574](https://user-images.githubusercontent.com/38528842/64027646-6fc4ec00-cb41-11e9-8901-060de83b5242.JPG)
0

**Comment by AramVartanyan** [comment]
Your wiring isn't seems to be right.
As far as I see at your picture - the programmer’s TxD (white cable) is not connected to the board. Instead it is connected to GND.
Also you have to connect the programmer’s GND to the power supply’s OUT-.

As I remember for this product:
TxD (programmer) -> RxD (board)
RxD (programmer) -> TxD (board),
but it might be the opposite. Try both.

**Comment by walvespit** [comment]
> Still pulling my hair out with this one, what adapters are you guys using?
> Mine is the CH34
> ![IMG_5574](https://user-images.githubusercontent.com/38528842/64027646-6fc4ec00-cb41-11e9-8901-060de83b5242.JPG)
> 0
you even use an external power source? wow i never needed that!

i use an CH340G adapter

**Comment by 1nutty1** [comment]
> > Still pulling my hair out with this one, what adapters are you guys using?
> > Mine is the CH34
> > ![IMG_5574](https://user-images.githubusercontent.com/38528842/64027646-6fc4ec00-cb41-11e9-8901-060de83b5242.JPG)
> > 0
> > you even use an external power source? wow i never needed that!
> 
> i use an CH340G adapter

Using the same, all the other switches I have flashed have not given me this headache.
I have 7 to do for my house so will try another and see if it is maybe just this board...
Will let you know.

**Comment by walvespit** [comment]
> Using the same

mine is physically different than yours but its the same chip.

im not sure if it is a good idea to use an external power source because it would use diferente GND.. 

anyway, have you ever flashed any other sonoff device yet?

**Comment by 1nutty1** [comment]
> > Using the same
> 
> mine is physically different than yours but its the same chip.
> 
> im not sure if it is a good idea to use an external power source because it would use diferente GND..
> 
> anyway, have you ever flashed any other sonoff device yet?

Flashed a bunch of Basics,RF s Th16 s, T1 2Ch... just tested the TTL adapter and it wont even flash a basic anymore so would appear that I need to get a new adapter?!? Rather strange that it just died tho...
Will let you know if I come right after acquiring a new adapter...

**Comment by 1nutty1** [comment]
As it turns out my TTL went belly up.
New TTL and all is well in the world.

Thanks for all the suggestions and help, it is greatly appreciated.
