### ISSUE TITLE
What is new in 1.1 version

### ISSUE THREAD

**Issue by mientki** [RavenSystem/esp-homekit-devices#474]
Where I find changelog?

**Comment by mafyata** [comment]
![0021B449-F8AB-4EBC-9006-915FF70B6499](https://user-images.githubusercontent.com/48009267/63678816-abd21700-c7f8-11e9-8e4f-5eb969a06117.png)

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/releases
