### ISSUE TITLE
OTA 

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#477]
hello i have a problem i dont know how to solve.
I created an accessory that I updated through OTA and the firmware version is the repository version, but after deleting and creating a new repository with version 0.0.1 now every subsequent repository version 0.0.2, 0.0.3 is displayed in the accessory 0.0.0.  if flash my code via usb then the firmware and manufacturer versions match my repository. 
Why when I upload my code through the OTA firmware version is 0.0.0

**Comment by RavenSystem** [comment]
Better post your issue here: https://github.com/HomeACcessoryKid/life-cycle-manager
