### ISSUE TITLE
[Sonoff DIY] New sonoff installation mode

### ISSUE THREAD

**Issue by walvespit** [RavenSystem/esp-homekit-devices#478]
Hello, the new Sonoff Mini and basic R3 have this new DIY mode that allow us to change the firmware over the lan using this software https://github.com/itead/Sonoff_Devices_DIY_Tools

The problem is, the software ask for a single .bin file to flash but HAA use 3 bins (main, rboot and blankconfig), i tried flashing only with main.bin and it didnt do anything (looks like it wont boot at all), also i lost my device.

The main problem here is that this devices are very hard to flash by usual methods (the pins on the board are so tiny).

Have anyone sucefully flashed HAA on this devices?

**Comment by RavenSystem** [comment]
Supporting the new DIY installation process of Sonoff is outside this project, sorry.
