### ISSUE TITLE
Find correct firmaware for sonoff switch T1 2ch 

### ISSUE THREAD

**Issue by ConradoP** [RavenSystem/esp-homekit-devices#481]
Hello, I am trying to put the firmware for sonoff t1 2ch, but it is showing 4ch when I synchronize with home app. What is the correct firmware for switch t1 2ch?

Where can I find the right firmware to download?
Thank you

Thank you

**Comment by walvespit** [comment]
Which device type are you setting ?

**Comment by ConradoP** [comment]
the device is Sonoff t1 US 2channel

![image](https://user-images.githubusercontent.com/49329259/63960840-c3620780-ca65-11e9-945f-e50980bbcd1a.png)

**Comment by walvespit** [comment]
> the device is Sonoff t1 US 2channel
> 
> ![image](https://user-images.githubusercontent.com/49329259/63960840-c3620780-ca65-11e9-945f-e50980bbcd1a.png)

i meant how did you configured at eve ? you should put device type 2 ! I have one exactly like yours and it works fine!

**Comment by ConradoP** [comment]
I used a firmware that I believe is not the correct one. because this one that I used works perfectly in sonoff 4ch (pro r2). I understand that I should use a specific firmware for T1, and I don't know where to download it. 
My question is, where is the correct firmware for T1?

**Comment by walvespit** [comment]
> I used a firmware that I believe is not the correct one. because this one that I used works perfectly in sonoff 4ch (pro r2). I understand that I should use a specific firmware for T1, and I don't know where to download it.
> My question is, where is the correct firmware for T1?

If you're talking about Ravencore firmware, the firmware is the same, the only thing that changes its the configuration inside eve, you must change device type to 2. 

Now if you're talking about HAA, the firmware is also the same, you just need to change the JSON config.

**Comment by ConradoP** [comment]
Thanks, I'm using revencore, where do I add option 2?

The steps I follow are:

1 - Flash Erase
2 - ./flash.sh sonoff_4ch.bin

Where do I add device 2?

**Comment by walvespit** [comment]
> Thanks, I'm using revencore, where do I add option 2?
> 
> The steps I follow are:
> 
> 1 - Flash Erase
> 2 - ./flash.sh sonoff_4ch.bin
> 
> Where do I add device 2?

Are you sure you using RavenCore? i dont recognize this sonoff_4ch.bin

take a look at https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation

**Comment by ConradoP** [comment]
I'm sorry, this firmware is main.bin but I renamed it.

I downloaded it right here by ravencore.

Doesn't the link you pass say where I point device 2?

i am not understanding how to change the firmware to different devices

**Comment by ConradoP** [comment]
I saw in the link the steps:

1 - firmware download
2- Connect cable
3- erase flash
4- burn the firmware ...

when I add device 2 to the firmware to understand that it is t1?

**Comment by walvespit** [comment]
> I'm sorry, this firmware is main.bin but I renamed it.
> 
> I downloaded it right here by ravencore.
> 
> Doesn't the link you pass say where I point device 2?
> 
> i am not understanding how to change the firmware to different devices

oh okay, so after you done flashing the firmware, you're going to your home app, add acessory and add the sonoff there etc, after that, you download this app "Eve for homekit", you go to acessorys, than you gonna see an setup option for the sonoff device there, in this setup option there will be a "device type" option, you change it to 2 and apply and its done

**Comment by ConradoP** [comment]
THanksssssssssssssssssssssssssssss
