### ISSUE TITLE
Question: BlitzWolf SHP6 support?

### ISSUE THREAD

**Issue by peros550** [RavenSystem/esp-homekit-devices#485]
I found this nice smart plug. It's made by [Blitzwolf](https://www.banggood.com/BlitzWolf-BW-SHP6-EU-Plug-Metering-Version-WIFI-Smart-Socket-220V-240V-10A-Work-with-Amazon-Alexa-p-1356981.html?rmmds=search) 

It looks that with some additional effort it can be flashed. Anybody tried so far? 

There is also a nice adapter for easier programming: 
https://www.thingiverse.com/thing:3342913

Anybody knows if HAA or Ravecore support it?

**Comment by RavenSystem** [comment]
If it uses esp8266 and you know its GPIO map, you can flash it with HAA.
