### ISSUE TITLE
Specific state on disconnetion timeout

### ISSUE THREAD

**Issue by Locutus73** [RavenSystem/esp-homekit-devices#487]
Feature request: two new parameters
	a) Disconnection timeout: in seconds
	b) Disconnection state SW1/2/n: 0/1
If the ESP gets disconnected for a consecutive amount of time greater than a) (if a=0 this mechanism should be ignored), then SW1, SW2, SWn are set in the specific state configured with b).
Use case: we connect an alarm Siren to HAA/RC and we use this as an anti-tamper mechanism; if Wi-Fi is jammed or the ESP is disconnected through a deauth attack, we can set off the Alarm siren autonomously.

Thank you in advance.
Regards.

**Comment by RavenSystem** [comment]
Maybe with HAA.

**Comment by RavenSystem** [comment]
Maybe with HAA.
