### ISSUE TITLE
Sonoff T1 2C

### ISSUE THREAD

**Issue by egorist** [RavenSystem/esp-homekit-devices#49]
Please, add Sonoff T1 with 2 buttons. in "Sonoff dual" mode only button №2 works
![34905168-6128981a-f84b-11e7-9cf0-e0e4c3b0bd55](https://user-images.githubusercontent.com/43891696/46554275-74106700-c8e8-11e8-9009-1c1a514d57b4.jpg)

**Comment by egorist** [comment]
After update everything works!))

**Comment by RavenSystem** [comment]
Sonoff T1 works too?

**Comment by RavenSystem** [comment]
Many thanks. T1-2C added to Wiki.

**Comment by egorist** [comment]
After update to 0.3.4 button 1 turns on randomly without commands
