### ISSUE TITLE
Sonoff TH16 Json String

### ISSUE THREAD

**Issue by blackwalkerhd** [RavenSystem/esp-homekit-devices#493]
hi all, 
someone knows the string for Sonoff TH16 with temperature and humidity sensor?
thanks :)

**Comment by RavenSystem** [comment]
That is not supported yet.

**Comment by blackwalkerhd** [comment]
thx for your time and answer :)
Hope it'll be soon.

For the Sonoff 4CH Pro R2 i read somewhere that the string is:

{"c":{"l":13,"i":1},"a":[{"r":[{"g":12}],"b":[{"g":0,"p":0},{"g":0,"t":1}]},{"r":[{"g":5}],"b":[{"g":9,"p":0},{"g":9,"t":1}]},{"r":[{"g":4}],"b":[{"g":10,"p":0},{"g":10,"t":1}]},{"r":[{"g":15}],"b":[{"g":14,"p":0},{"g":14,"t":1}]}]}

i have to test it.

thanks again Josè
