### ISSUE TITLE
HAA Templates page not up to date with HAA v0.0.6

### ISSUE THREAD

**Issue by macjl** [RavenSystem/esp-homekit-devices#495]
Hello,

The Wiki page of HAA templates seems not up to date with the new release of HAA v0.0.6 : 
https://github.com/RavenSystem/esp-homekit-devices/releases
https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates

I'm trying to install a new Sonoff Basic with this JSON inspired from Templates, and it doesn't work : 
{"c":{"l":13,"i":1},"a":[{"t":1,"r":[{"g":12}],"b":[{"g":0,"p":1,"t":1},{"g":2,"p":1,"t":1}]}]}

Regards

**Comment by RavenSystem** [comment]
https://twitter.com/RavenSystem/status/1169017948591329281

**Comment by macjl** [comment]
Thanks for your quick reply. Is there a way to downgrade to the v0.0.5 release to be able to use old configs?

**Comment by macjl** [comment]
Hello,

I was finally able to produce a valid JSon for 0.0.6 by analysing the code. Here it is :
`{"c":{"l":13,"i":1},"h":[{"t":1,"a":{"0":{"r":[{"g":12,"v":0}]},"1":{"r":[{"g":12,"v":1}]}},"b":[{"g":0},{"g":2}]}]}`
=> Sonoff Basic with button on GPIO 2 and GPIO 0, and Relay on GPIO 12.

I could suggest to change this sentence in documentation : 

> "a" Actions:
> Actions performed on each state of the accessory. Are defined by a integer number.

I search long time to understand what it means. And in the source code, it's commented as an array which confuses me a lot. But it's just a list of states. Why not : 

> "a" Actions:
> List of actions performed on relays, at each state of accessory. Are defined by a integer number starting at 0.

**Comment by macjl** [comment]
And if you want the the Sonoff S20 example:

> Sonoff S20/S26 without UART output, with status LED and working button:
`{"c":{"l":13,"i":1},"h":[{"t":2,"a":{"0":{"r":[{"g":12,"v":0}]},"1":{"r":[{"g":12,"v":1}]}},"b":[{"g":0}]}]}`

**Comment by mientki** [comment]
I need a template for sonoff touch t1 2 channel. Can You help me?

**Comment by mientki** [comment]
"h":
"v":
What is this parametr?

**Comment by macjl** [comment]
From Wiki :

> "h" HomeKit Accessories
> This section is mandatory. It contains an array of HomeKit accessories.

> "v": Value:
>  0: Low, normally off.
>  1: High, normally on.

**Comment by mientki** [comment]
There was a small commotion. Is now the description of HAA Templates https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates and the description https://github.com/RavenSystem/esp-homekit-devices/wiki/Home-Accessory-Architect is compatible with HAA version 0.0.7?

**Comment by RavenSystem** [comment]
> There was a small commotion. Is now the description of HAA Templates https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates and the description https://github.com/RavenSystem/esp-homekit-devices/wiki/Home-Accessory-Architect is compatible with HAA version 0.0.7?

Yes.

**Comment by RavenSystem** [comment]
All documentation is updated.
