### ISSUE TITLE
New dimmer by Shelly. Possible to support?

### ISSUE THREAD

**Issue by LyoshaDovolen** [RavenSystem/esp-homekit-devices#497]
https://shelly.cloud/wifi-smart-home-automation-shelly-dimmer/

**Comment by epl2005** [comment]
Any news on this request ?

**Comment by RavenSystem** [comment]
First, we need info about how it works.

**Comment by RavenSystem** [comment]
If Shelly Dimmer uses PWM like Shelly RGBW2, now HAA v0.6.0 has PWM Lights support.

**Comment by epl2005** [comment]
Good news ... shelly  dimmer I ordered finally it's arriving. Have You got already any confirmation  about PWM support ?

**Comment by mafyata** [comment]
Read wiki. Haa support it.

**Comment by epl2005** [comment]
> Read wiki. Haa support it.

If you are referring to PWM itself I know it. I was asking for Shelly dimmer fully support in reply to RavenSystem post

**Comment by RavenSystem** [comment]
@epl2005 I don't know yet if Shelly Dimmer works with PWM like Shelly RGBW2.

**Comment by epl2005** [comment]
> @epl2005 I don't know yet if Shelly Dimmer works with PWM like Shelly RGBW2.

I finally got mine. Is there anything I can do to verify if it’s support ? Do you have any Json config to try ? Thank you

**Comment by kompak23** [comment]
Oficially, Shelly Dimmer does not use PWM modulation. It contains MOSFET transistors which conduct part of waveform. There is STM32 to control MOSFETS.  It isn't good news, we cannot use Raven software to control it under Homekit :(

**Comment by epl2005** [comment]
> Oficially, Shelly Dimmer does not use PWM modulation. It contains MOSFET transistors which conduct part of waveform. There is STM32 to control MOSFETS. It isn't good news, we cannot use Raven software to control it under Homekit :(

Yes not a good news with the current HAA version ... any chance in the future ?

**Comment by RavenSystem** [comment]
We need to know how esp8266 manages stm32 chip.

**Comment by RavenSystem** [comment]
Bad news: https://github.com/arendst/Tasmota/issues/6914#issuecomment-562109267

**Comment by pilot1981** [comment]
@RavenSystem you use TASMOTA code for your firmware?

**Comment by RavenSystem** [comment]
No. Tasmota is Arduino based.

**Comment by GPL71** [comment]
@RavenSystem the best would be join efforts ... draw a pcb and code ...                                        
                                                                                                                                                                  
 If people are interested work together to develop a custom pcb, it would be possible realize 220v dimmer

**Comment by aleroot** [comment]
It looks like in Tasmota they figured out the way to make it work,  reverse engeneering it ... https://github.com/arendst/Tasmota/issues/6914#issuecomment-577355864

**Comment by edge90** [comment]
@aleroot yeah, the two mcus communicate via uart. :)

**Comment by iCarl** [comment]
Any news on this?

**Comment by RavenSystem** [comment]
This must be opened.

**Comment by RavenSystem** [comment]
@edge90 Shelly Dimmer uses UART from GPIO 1 and 3 of esp8266, right?

**Comment by edge90** [comment]
@RavenSystem Yes, check the tasmota thread and you'll find a lot of dumps etc.

**Comment by RavenSystem** [comment]
@edge90 
I am using some codes from here: https://github.com/arendst/Tasmota/issues/6914#issuecomment-575899122

And I think this is right: https://github.com/arendst/Tasmota/issues/6914#issuecomment-575747738

What do you think?

**Comment by RavenSystem** [comment]
@edge90 How is checksum calculated?

**Comment by aleroot** [comment]
If you have a look at this tasmota version, they seem to have completed the integration :

https://github.com/arendst/Tasmota/issues/6914#issuecomment-636297822

Shelly dimmer is working now with tasmota ...

**Comment by aleroot** [comment]
Is there any plan to support this dimmer from Shelly ?
Has this ticket been closed because there is no plan to support it?

**Comment by tokamac** [comment]
I concur, why this has been closed (for the 2nd time) without being resolved, just at the moment Tasmota guys seem to have found a working solution? IMHO a dimming module compatible with HomeKit would be a must-have, if not the best possible feature for HAA.

I see that Shelly Dimmer (first version) is listed in [Devices Database](https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database). But does the Shelly Dimmer **2** work with HAA? 

Shelly Dimmer 2 does not need neutral wire (first version needs it) which is a killer feature, since many switch boxes do not have neutral wires. There is no other small dimmer module working with no neutral wire on the market that I am aware of, besides Fibaro Dimmer 2 (which is Z-Wave and needs homebridge if one wants HomeKit compatibility).
