### ISSUE TITLE
Sonoff S26 without button

### ISSUE THREAD

**Issue by straubus** [RavenSystem/esp-homekit-devices#499]
Hi, I would like to know how to configure the device to disable button functionality, while sonoff s26 still remains as socket.  I am using ravencore

**Comment by RavenSystem** [comment]
It is not possible with RavenCore; use Home Accessory Architect instead.

**Comment by straubus** [comment]
Thanks, Is there any way to install HAA on top of Ravencore using ota, and without soldering?

**Comment by RavenSystem** [comment]
@straubus Yes. Update RavenCore to last version and read this: https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#firmware-haa-default-off
