### ISSUE TITLE
Sonoff 4ch Pro - only Ch1 responds to switch settings

### ISSUE THREAD

**Issue by omarkmsft** [RavenSystem/esp-homekit-devices#5]
Tested the 4ch device firmware on 4ch Pro.  Only Ch1 seems to be respecting the inching behavior set by the K5/K6 switches defined here - http://ewelink.coolkit.cc/?p=458.  All other channels behave like 'self-locking' regardless of how the switches are set.  Good thing homekit is working well in initial tests and I only use Ch1 so fine for me.

**Comment by RavenSystem** [comment]
Can you test with this DYP switch setup?
S6: 1
K5: all 1
K6: all 0

**Comment by RavenSystem** [comment]
Please, can you try the latest commit (0.3b1) to test if all CH work?

Many thanks.

**Comment by omarkmsft** [comment]
verified this is fixed with 0.4 version.
