### ISSUE TITLE
Sonoff B1

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#500]
Hi, this bulb is supported?
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-B1

**Comment by RavenSystem** [comment]
Not yet, but HAA will do it.

**Comment by RavenSystem** [comment]
If it uses PWM to manage colors, now HAA v0.6.0 has PWM Lights support.

**Comment by mientki** [comment]
Can you provide the correct JSON configuration to work with this bulb? Unfortunately, I have no idea what GPIO individual RGBW colors have.

**Comment by RavenSystem** [comment]
Sonoff B1 does not use PWM to manage colors.
