### ISSUE TITLE
Window opening like garage dor opening

### ISSUE THREAD

**Issue by lukaszwitkowski** [RavenSystem/esp-homekit-devices#501]
hello do you think you can add window opening like garage for opening tool?
i see there is window opening sensor but do you think there is problem to add window opening mechanizm I think that is not hard to do. just change icon from garage door to windows

**Comment by RavenSystem** [comment]
It is not possible. Icons are selected by Apple. If you want a door driver, use Device Type 12 with Type = 2. https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#12-window-covering
