### ISSUE TITLE
Help needed with Magic Home Single Channel

### ISSUE THREAD

**Issue by Olepir** [RavenSystem/esp-homekit-devices#502]
How to flash Magic Home Single Channel with RavenCore or HAA?
Can I flash it with RavenCore? If not – how to use HAA and is there template available for this LED controller?
Thanks

**Comment by mafyata** [comment]
Ravencore. I have 2 magic home rgb led controllers flashed with ravencore. After flash with ravencore you can’t controll it with normal ir controller, only with phone/tablet. You need to solder pins on the board.

**Comment by Olepir** [comment]
> Ravencore. I have 2 magic home rgb led controllers flashed with ravencore. After flash with ravencore you can’t controll it with normal ir controller, only with phone/tablet. You need to solder pins on the board.

Are you sure that Ravencore is compatible with single channel controllers?

**Comment by mafyata** [comment]
Sorry , I don’t know for 1 channel. I have rgb.

**Comment by curla92** [comment]
> How to flash Magic Home Single Channel with RavenCore or HAA?
> Can I flash it with RavenCore? If not – how to use HAA and is there template available for this LED controller?
> Thanks

https://github.com/curla92/LED-Dimmer-Homekit

**Comment by Olepir** [comment]
> https://github.com/curla92/LED-Dimmer-Homekit

Any tutorials hot to use it?

**Comment by curla92** [comment]
> > https://github.com/curla92/LED-Dimmer-Homekit
> 
> Any tutorials hot to use it?

you have to install with ota method. After you have to set it into eve app

**Comment by Olepir** [comment]
> you have to install with ota method. After you have to set it into eve app

Any links for this ota method? I only familiar with RavenCore flashing.

**Comment by curla92** [comment]
> > you have to install with ota method. After you have to set it into eve app
> 
> Any links for this “ota method”? I only familiar with RavenCore flashing.

```
esptool.py -p /dev/<your_ESPPort> --baud 115200 write_flash -fs 1MB -fm dout -ff 40m \
0x0 rboot.bin 0x1000 blank_config.bin 0x2000 otaboot.bin
```

OTA REPO

`curla92/LED-Dimmer-Homekit
`
as raven method.

**Comment by Olepir** [comment]
> OTA REPO
> 
> `curla92/LED-Dimmer-Homekit `

So everything is the same except OTA Repo?

**Comment by curla92** [comment]
> > OTA REPO
> > `curla92/LED-Dimmer-Homekit `
> 
> So everything is the same except OTA Repo?

yes.

**Comment by Olepir** [comment]
Thanks! Will try it now.

**Comment by Olepir** [comment]
> yes.

Standard RavenCore pin is not accepted. Any ideas?

**Comment by curla92** [comment]
![IMG_CD653627D249-1](https://user-images.githubusercontent.com/22404058/65042146-8b5d2e80-d958-11e9-8601-acbe92942aa6.jpeg)

**Comment by Olepir** [comment]
I don’t see it in Eve because I can’t add it to HomeKit. RavenCore pin number is incorrect.

**Comment by curla92** [comment]
> I don’t see it in Eve because I can’t add it to HomeKit. RavenCore pin number is incorrect.

code is 111-111-111

**Comment by Olepir** [comment]
Thanks, working now, but ON is OFF, brightness minus is plus and vice versa. Polarity is ok.
Also how can I change wi-fi network?

**Comment by curla92** [comment]
Check eve config. Please reebot after set. What kind of magichome do you have?

**Comment by Olepir** [comment]
Working now, don’t know what I did… Is there any way to reset wifi setting for reconnect to different wiffi?

**Comment by bj-tracer** [comment]
> Working now, don’t know what I did… Is there any way to reset wifi setting for reconnect to different wifi?

"Within first minute since device boots, wait about 5 seconds to allow device to boot completely, and then toggle any switch quickly (from Home App or from external switches) at least 10 times."
It's from wiki fo RavenCore firmware.
But you haven't any button... Use EVE for wi-fi reseting :)

**Comment by Olepir** [comment]
> > Working now, don’t know what I did… Is there any way to reset wifi setting for reconnect to different wifi?
> 
> "Within first minute since device boots, wait about 5 seconds to allow device to boot completely, and then toggle any switch quickly (from Home App or from external switches) at least 10 times."
> It's from wiki fo RavenCore firmware.
> But you haven't any button... Use EVE for wi-fi reseting :)

Firmware from curla92 doesn’t have it.

**Comment by RavenSystem** [comment]
I think if you have questions about a firmware outside of this project, you should ask them in the corresponding repo, not here.
