### ISSUE TITLE
Connecting to hidden Wifi Network

### ISSUE THREAD

**Issue by Dirk23** [RavenSystem/esp-homekit-devices#503]
Hi,

is there a way to connect to a Wifi Network wich doesn't Broadcast SSID (Hidden Wifi)?
I couldn't find any way to connect to such Wifi.

Thank you.

Regards

Dirk

**Comment by RavenSystem** [comment]
I think that you can select "Other" in Wifi Config.

**Comment by Dirk23** [comment]
No there is no "other" in Wifi Config
