### ISSUE TITLE
Sonoff iFan HAA

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#510]
I really need support. While there is tasmota, what data is needed?

**Comment by RavenSystem** [comment]
Support is on the way.

**Comment by mgoeller** [comment]
The GPIOs for the iFan03 are straight forward connected to the relays, according to the [Tasmota template](https://templates.blakadder.com/sonoff_ifan03.html).

My only question is how to keep the compatibility with the MCU for the RF signals. Apparently it is connected via serial to the ESP. Did anyone sniff the commands yet what a correctly paired remote will send?
