### ISSUE TITLE
Wemos D1 Mini + DS18b20 + DHT 22

### ISSUE THREAD

**Issue by cima37** [RavenSystem/esp-homekit-devices#511]
Hi!
I have a Wemos D1 mini and would like to connect to these 4 DS18b20 on i2c and then maybe a dht22 to do so! Is that possible? Which board and which device should I use? Which configuration makes sense?

Thanks!

**Comment by mafyata** [comment]
I use nodemcu v3 + dht22. Set as device type 6. On ios 12.4.1 was good but on ios 13.1 is bad. I see only “switch” and must long press to see temp or humidity.

**Comment by cima37** [comment]
Do you have only the dht 22 on the nodemcu? I need 4 ds18b20 and 1 dht22

**Comment by mafyata** [comment]
Only one dht22. If you want 2 sensors you must wait for HAA to support it.

**Comment by cima37** [comment]
Thank you!
