### ISSUE TITLE
Any HAA tutorial for 3gang Switch with status led ?

### ISSUE THREAD

**Issue by Codkit** [RavenSystem/esp-homekit-devices#516]
Hi all

I have a 3gang wall switch ,there are 3 leds corresponding to each switch, how should I add the “c” and “l” data ? Also any other parameters for the “l” like on and off, right now the led on my Switch only blink once whenever I press it, it won’t stay on. Thanks all for your help.

**Comment by bj-tracer** [comment]
Hi!
I think you may use for it relay declaration at relay array.
"c" using for led indicated status of esp. You no need to use it for your case.

**Comment by Codkit** [comment]
Hi bj-tracer

Thanks for your help , I put led’s gpio with “g” in relay array , it seems ok
But the leds status is reversed whenever reboot is needed.

**Comment by Codkit** [comment]
Hi all
gpio13 = relay
gpio16 = Switch led
{"c":{"l":0,"i":1},"a":[{"0":{"r":[{"g":13,"v":0},{"g":16,"v":1}]},"1":{"r":[{"g":13,"v":1},{"g":16,"v":0}]},"b":[{"g":12}]}]}
Appreciate if anyone can help me figure how to reverse the led state when reboot, should I use “s” and where to put it ? Right now after reboot relay is off but led is on.
Thanks everyone

**Comment by Codkit** [comment]
Seems ok after updated to 0.1.1, leds initial state is off (reversed).
I’d like to apply “s”:5 (last state), can anyone show me an example of how to apply “s” with last state ? I keep getting error....... thanks very much

**Comment by pilot1981** [comment]
Initial state 5 last state

{"c":{"l":0,"i":1},"a":[{"s":5,"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":13,"p":0},{"g":13,"t":0}]},{"s":5,"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":5,"p":0},{"g":5,"t":0}]}]}

**Comment by Codkit** [comment]
Hi pilot1981

Thanks you so much for your quick reply !

**Comment by pilot1981** [comment]
Say thanks to @RavenSystem !!!

**Comment by Codkit** [comment]
Yes , big thanks to José , amazing work ! Few of my old wall switches are back to life !

**Comment by RavenSystem** [comment]
You are welcome. But users' feedbacks and community helps are very important too!
