### ISSUE TITLE
Problem with Sonoff Touch T1 1 channel

### ISSUE THREAD

**Issue by LukasNowak** [RavenSystem/esp-homekit-devices#517]
Dear's 
I install the software correctly in Sonoff Touch T1, after I connect them to the power I can't find the WiFi network of the device, WiFi LED is off, also when I click the main button nothing happened, when I click the reset button the backlight of the main button goes out, after releasing the button it lights up again. Can you help me?

**Comment by RavenSystem** [comment]
What firmware did you installed? RC or HAA? With or without OTA? We need more details of your steps.

**Comment by LukasNowak** [comment]
RC with OTA

Z wyrazami szacunku/Best regards

Łukasz Nowak

**Comment by LukasNowak** [comment]
Can I ask about short manual how to install RavenCore in Sonoff T1 1 channel? Which version?

**Comment by RavenSystem** [comment]
RC is deprecated.
