### ISSUE TITLE
HAA T2EU 3 Gang Template

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#518]
{"c":{"l":13,"i":1,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":10}]}]}

**Comment by RavenSystem** [comment]
Many thanks! Added to Wiki: https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates#sonoff-t2-eu-3-gangs
