### ISSUE TITLE
Use different buttons for on/off

### ISSUE THREAD

**Issue by bj-tracer** [RavenSystem/esp-homekit-devices#521]
Hi!
how can i use different buttons for change switch state? i want On the switch with a button gpio0  and Off it with button gpio2, for example.
is it possible with HAA?

**Comment by RavenSystem** [comment]
Not possible, yet... HAA will support it.

**Comment by RavenSystem** [comment]
Now, since v0.2.2, you can do it using f0 and f1 keys.

**Comment by bj-tracer** [comment]
Thanks! 👍
