### ISSUE TITLE
Shelley RGBW2 - color mismatch.

### ISSUE THREAD

**Issue by myxa27** [RavenSystem/esp-homekit-devices#522]
Hello!
I requested Shelly RGBW2 on RavenCore, Firmware 1.1.1. I set it up as indicated in the instructions, while the colors of the LED strip do not match the colors in the home application. It seems that the colors are mixed up green and red.
When I choose green, red is on.
I choose red - green is on.
I choose blue - blue is on.

In this case, before the firmware on RavenCore, the colors were displayed correctly. The wires are connected correctly.

My settings:
Board type: 1
Boost: 0
Button filter: 0
Device Type: 14
Dummy switch: off
External Toggle 1: 0
Firmware HAA: off
Inching time DM: 0
Init state DM: 0
Init state SW1: 0
Log output: 0
Pin B: 14
Pin G: 12
Pin R: 15
Pin W: 0

**Comment by RavenSystem** [comment]
Swap G and R pins in EVE accessory setup.
