### ISSUE TITLE
Reset WiFi option in HAA

### ISSUE THREAD

**Issue by mientki** [RavenSystem/esp-homekit-devices#523]
Can you add the "reset wifi settings" option in the next release version. This option will shorten the time the HAA-xxxxx network appears, when the known one is no longer available. This is the only way to change the network for another one at the moment. I do not want to wait 10 minutes, I would like to force the reset of wifi settings.

**Comment by RavenSystem** [comment]
That is not make sense. You can change your wifi settings entering into setup mode. And the 10 minutes timeout was deprecated and removed some time ago for security reasons.

**Comment by mientki** [comment]
OK. I had preview version which it has not been on yet. Now it works as it should. Configuration mode also introduces AP mode. Thank you. This soft is amazing. :-)
