### ISSUE TITLE
HAA Garage Device

### ISSUE THREAD

**Issue by noobydp** [RavenSystem/esp-homekit-devices#524]
Hi José,
Thanks for all your hard work on HAA.

Would it be possible to have the garage controller added to HAA?
I know its available in ravencore already but I'd rather use HAA.

Thanks,
David

**Comment by tunip** [comment]
I am in the procedure to flash all my devices with HAA. Garagedoor (Sonoff SV) is the only device which i can not flash with HAA.
Would be awesoume if garagedoor type would find its way into HAA.

Thx Joseph

**Comment by RavenSystem** [comment]
Don't worry. Garage door will be in HAA.

**Comment by perezjosue** [comment]
I am in the process of starting off with HAA. Would you recommend I just go ahead with RavenCore for the garage for now or will it be added to HAA soon?

**Comment by RavenSystem** [comment]
If RavenCore garage door config is good for you, use it. If you want, then you can migrate to HAA without reflashing.

**Comment by perezjosue** [comment]
> If RavenCore garage door config is good for you, use it. If you want, then you can migrate to HAA without reflashing.

Thank you for your reply and for creating all this.
