### ISSUE TITLE
RavenCore development is dead. Long live the HAA!!

### ISSUE THREAD

**Issue by RavenSystem** [RavenSystem/esp-homekit-devices#525]
I have decided to finish RavenCore development to focus all my efforts in the development of Home Accessory Architect (aka HAA).

All RavenCore accessory types will be included in HAA with many enhancements ASAP.

**Comment by bj-tracer** [comment]
Thanks for your hard work!

**Comment by ex725** [comment]
Thank you for your work

**Comment by shinyuan** [comment]
Thank you for your work.

**Comment by shinyuan** [comment]
Can you post a video in Youtube from Entering Setup Mode from a Type 1: SWITCH or Type 12: MOTION SENSOR?! Thank you.

**Comment by slakul69** [comment]
Thanks for  your hard work!
