### ISSUE TITLE
Shelly 2.5 water valve

### ISSUE THREAD

**Issue by simart11** [RavenSystem/esp-homekit-devices#527]
Is it possible to set the device type "Water Valve" for shelly 2.5 to display homekit as 2 separate water valves?

**Comment by RavenSystem** [comment]
Not yet. Wait until "water valve" is available in HAA.

**Comment by simart11** [comment]
When will that be?" Can I link to HHA?

**Comment by RavenSystem** [comment]
I do not give time estimations, sorry.

**Comment by pilot1981** [comment]
I saw water valve in feature list of HAA: it's already possibile to use shelly 2.5 to control 2 water valves?
