### ISSUE TITLE
Reducing power consumption

### ISSUE THREAD

**Issue by bj-tracer** [RavenSystem/esp-homekit-devices#529]
Hi, @RavenSystem !
Can you realize a power safe mode for esp8266 controllers?
It has 3 sleep modes - Modem-sleep, Light-sleep and Deep-sleep.
Must whanted mode is the Deep-sleep. Peoples say that will be reduce power consumption for 2500 mAh battery to 300 hours of ESP working.
This mode can be using at autonomus sensors.

**Comment by bj-tracer** [comment]
I found same question at Max Kulkin's git.
It's not possible with HK :(

**Comment by RavenSystem** [comment]
Yes, it is not possible because each HK accessory is a server that must be connected permanently to WiFi network to listen entry requests.

**Comment by ericklil** [comment]
I would like to think `Deep-sleep` would be possible with the `Stateless Switch `sample. This unit does nor give error messages if left powered off as it appears there is only one way communication. It would be a simple way to make a remote control that can run on a `LiPo` battery.. Any chance of adding this?
