### ISSUE TITLE
HAA firwmare for Sonoff with Temperature sensor? TH10 or TH16 

### ISSUE THREAD

**Issue by milonet** [RavenSystem/esp-homekit-devices#530]
Hi @RavenSystem  the latest 0.2.2 version support the TH sensor?

Thank you for very good job

**Comment by claire078** [comment]
Basic with TH would be awesome. 
I haven’t try this firmware but if thermostat would work I would try it. 😂

**Comment by RavenSystem** [comment]
TH is not supported yet.

**Comment by caligari74** [comment]
Look here:
https://github.com/RavenSystem/esp-homekit-devices/issues/560
