### ISSUE TITLE
Video instructions - Shelly and HomeKit , available?

### ISSUE THREAD

**Issue by macguru341** [RavenSystem/esp-homekit-devices#532]
Hello
I have 5 Shelly switchers in my home that works fine worn Homebridge , I want to make them HomeKit enabled and purchased all the accessories to flash them.
Is there a good manual or YouTube video in English that can help me in the process? I’m new to this kind of stuff 
Thanks

**Comment by RavenSystem** [comment]
I don't know any video, but if you want, you can join to the chat and ask there.

**Comment by brymonster** [comment]
Would love this as well. 
As detailed as the instructions are, there is a lot left out. Installing esptool, finding esp port, etc..
