### ISSUE TITLE
Ravencore - Thermostat “freezed”

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#537]
I have a device with DHT22 sensor, use it for heater thermostat (type5). 
It would work great, but once a day it freezes and values don’t updated anymore. I have to power cut (restart) and works again. 
It has an isolated relay, heater work with 230V. 
What could causes this problem?

**Comment by RavenSystem** [comment]
It can be a hardware problem. Maybe a problem with the power stage.

**Comment by claire078** [comment]
I just Sonoff haven’t changed yet. Sensor, cable, new programming done. 
OK, I will try it. I will come back with info.

**Comment by claire078** [comment]
I have already changed. It works same. ☹️
I have no idea why.

**Comment by Kristian8606** [comment]
i had this problem with my thermostat.  it may sound strange, but the problem came from hardware buttons that were realized by interruptions.  if you have an interrupt feature isolate it to test if it will freeze.

**Comment by Kristian8606** [comment]
For some reason EMI is affecting the interrupt function but I still don't understand why.

**Comment by claire078** [comment]
> i had this problem with my thermostat. it may sound strange, but the problem came from hardware buttons that were realized by interruptions. if you have an interrupt feature isolate it to test if it will freeze.

Interrupt function? how can I isolate it?
Remove GPIO01 button?

**Comment by Kristian8606** [comment]
Comment on the interrupt and callback features in the code

**Comment by claire078** [comment]
@RavenSystem : could you check it please? maybe make a test version? or with HAA it will be works 100%?

**Comment by bj-tracer** [comment]
Wich GPIO you used for connection TH-sensor?
If you use any sonoff basic relay than check it for model of esp chip. New revision of relay has a esp8285 chip and GPIO2 instead GPIO14. And if you connected your TH-sensor to this pin than you have a freezes.
You need to use GPIO3 (RX-pin) and sensor will be working properly ;)))

**Comment by claire078** [comment]
> Wich GPIO you used for connection TH-sensor?
> If you use any sonoff basic relay than check it for model of esp chip. New revision of relay has a esp8285 chip and GPIO2 instead GPIO14. And if you connected your TH-sensor to this pin than you have a freezes.
> You need to use GPIO3 (RX-pin) and sensor will be working properly ;)))

I use RX-pin and chip 8285, newer version of board.

**Comment by bj-tracer** [comment]
> I use RX-pin and chip 8285, newer version of board.

Hmmmm... I had freezes when used GPIO2. But it has become properly with GPIO3.
I use sonoff on 8285 chip too.
