### ISSUE TITLE
RavenCore / HAA on ESP2866 lights 

### ISSUE THREAD

**Issue by shimon88** [RavenSystem/esp-homekit-devices#544]
Hi all,

First I would like to appreciate your amazing hard work! This FW is great. Thank you!

Is any version supporting light bulbs with ESP8266 chip inside? Like the Xiaomi-Philips smart light bulbs?

I know they support Tasmota...so I thought they might support RC/HAA as well..

Again, thank you!

**Comment by RavenSystem** [comment]
RavenCore supports PWM RGB/W lights.

**Comment by shimon88** [comment]
thank you.
is HAA supporting PWM lights?
