### ISSUE TITLE
Need HAA Template

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#547]
![IMG_0175](https://user-images.githubusercontent.com/44049295/67165890-d927e500-f3a3-11e9-9be5-e0e1ff1707f6.png)

It works great with equals, board type 1 and with any type of device (ravencore)

I want to make a lock and a button out of it (on any free gpio)

thanks for the help

**Comment by RavenSystem** [comment]
What is the GPIO map?

**Comment by netRunner0** [comment]
Can take any free 😀

**Comment by gnomosg** [comment]
Try Sonoff Basic template, should work

**Comment by netRunner0** [comment]
I need a lock type and a button together

**Comment by RavenSystem** [comment]
GPIO map, please.
