### ISSUE TITLE
Window Covering - close after a power outage

### ISSUE THREAD

**Issue by Fudalii** [RavenSystem/esp-homekit-devices#551]
Hello.
Device: Shelly 2.5

After a power outage, when the Shelly is ON again (power return), the window blinds move down?? Is there any relay memory option for "Window Covering"?

Apple TV connection is not yet available. For now, work only locally WiFi.

Txh for Help!

**Comment by mafyata** [comment]
Did you set “init state” to “last state”

**Comment by Fudalii** [comment]
At deice type 12. "Window Covering" -  From what I remember I didn't see the Init State SW option ??

**Comment by mafyata** [comment]
I don’t use windows covering and don’t know if there is init state sw. I use it with my light and led strip.
