### ISSUE TITLE
ESP01S Switch

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#552]
{"c":{"o":1,"l":13,"i":1},"a":[{"t":1,”s”:5,"0":{"r":[{"g":2,"v":0}]},"1":{"r":[{"g":2,"v":1}]},"b":[{"g":0,"p":1,"t":1},{"g":14,"p":1,"t":1},{"g":14,"t":0}]}]}

**Comment by RavenSystem** [comment]
I need a way to get and save all these templates...

**Comment by RavenSystem** [comment]
Better:

`{"c":{"l":13},"a":[{"s":5,"0":{"r":[{"g":2}]},"1":{"r":[{"g":2,"v":1}]},"b":[{"g":0}]}]}`
