### ISSUE TITLE
Sonoff Dual with Raven Core 1.2

### ISSUE THREAD

**Issue by Codkit** [RavenSystem/esp-homekit-devices#555]
Hi

Shorting Button 0(gpio0) pin to Gnd doesn’t work for factory reset, device was in mode 2 and deleted in home app, is there a way to factory reset sonoff dual physically ? Thanks very much.

**Comment by mafyata** [comment]
Flash it again.

**Comment by RavenSystem** [comment]
In a Sonoff Dual, you must use built-in button, that is not GPIO-0.

**Comment by Codkit** [comment]
> In a Sonoff Dual, you must use built-in button, that is not GPIO-0.

Hi 
I tried 10 times with built-in button , didn’t work, which GPIO should I short to Gnd to reset ?thanks

**Comment by RavenSystem** [comment]
10 times no. Pressing and holding it for 10 seconds.

**Comment by Codkit** [comment]
I tried holding the physical button on Sonoff dual fro 10 seconds, still no go .....hopefully I can find a way without reflash it , thanks very muvh
