### ISSUE TITLE
Nodemcu + Temp/hum

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#559]
Hi , I have nodemcu and dht22 for temp and humidity.
If I use haa and want only to show temp and humidity(type 24), what template to use ?
Is it correct:
{
  "c": {
    "o": 0
  },
  "a": [
    {
      "t": 24,
      "g" : 14,
      "z": -1
    }
  ]
}

**Comment by RavenSystem** [comment]
Yes.

**Comment by mafyata** [comment]
Can I enter setup mode with this template?

**Comment by RavenSystem** [comment]
Ops, no. You must declare a way to do that. With a physical button or with a dummy switch.

**Comment by mafyata** [comment]
I don’t want switch in home app. I think to enter setup mode with connecting pins with jumper.

**Comment by RavenSystem** [comment]
That is the best way. Dummy switch sucks, IMO, but I tell you all options.

**Comment by mafyata** [comment]
IMO?

**Comment by RavenSystem** [comment]
In My Opinion.

**Comment by mafyata** [comment]
I think for using GPIO 1 and GND for setup mode. Can you tell me the json with them for setup mode.

**Comment by RavenSystem** [comment]
Sure, what press type do you want? Single, double, holding for 10 seconds...

**Comment by mafyata** [comment]
single

**Comment by RavenSystem** [comment]
`{"c":{"b":[{"g":1,"t":0}]},"a":[{"t": 24,"g":14,"z":-1}]}`

Be sure that gpio1 works as expected in node mcu.

**Comment by mafyata** [comment]
Here is a picture with all pins on nodemcu
![ESP-12E-Development-Board-ESP8266-NodeMCU-Pinout](https://user-images.githubusercontent.com/48009267/67606867-5b8d1c00-f78b-11e9-84c5-7a78ec614328.jpg)

**Comment by RavenSystem** [comment]
Gpio1 is uart tx. Better use other. 5 is good.

**Comment by mafyata** [comment]
Gpio 6?

**Comment by RavenSystem** [comment]
Don’t use 6, 7 and 8.

**Comment by mafyata** [comment]
ok , I will use 5.
{"c":{"b":[{"g":5,"t":0}]},"a":[{"t":24,"g":14,"z":-1}]}
Is this correct?

**Comment by RavenSystem** [comment]
Yes.

**Comment by mafyata** [comment]
Works perfect. Thanks. How to update the firmware in future? With entering in setup mode only ?

**Comment by RavenSystem** [comment]
“ If you installed it using OTA procedure, there is an option called "Auto OTA Updates" that allows to search updates every time device enters in setup mode, 90 seconds pasts, and setup web page is not loaded.”

https://github.com/RavenSystem/esp-homekit-devices/wiki/Home-Accessory-Architect#setup-mode

**Comment by mafyata** [comment]
Yes , I selected auto ota update. So to update I must enter the device in setup mode , it will auto update and restart itself to normal mode ?

**Comment by RavenSystem** [comment]
Exactly, always you don’t load setup mode web page.
