### ISSUE TITLE
GPIO init

### ISSUE THREAD

**Issue by Partizan7676** [RavenSystem/esp-homekit-devices#56]
Probably current init state is right for Sonoff devices, but not good for NodeMCU or other based on esp8266.
As i understand with Raspberry GPIO - it's same if you init pins with direction OUT and state HIGH(if you connect relay module to it - you get relay on). in that case sensor will not work - you get HIGH signal from all pins. My init script for pins for example:
  export_pin 5 out low 0 
  export_pin 20 in high 0
5 is for switch door, 20 is for close sensor
Don't know if you can init pins separately, but for NodeMCU better create fork.

**Comment by RavenSystem** [comment]
Sonoff uses inverted GPIO for relays (It's not only for the initial state).

This project is focused on comercial devices (Mainly Sonoff devices), so users can flash this firmware to enable HomeKit. If you want to  build your owns, you can try this repo: https://github.com/maximkulkin/esp-homekit-demo
