### ISSUE TITLE
TH10/TH16 Switches

### ISSUE THREAD

**Issue by caligari74** [RavenSystem/esp-homekit-devices#560]
I thought I'd leave this TH10/TH16 template here, as it may help someone:

{"c":{"l":13,"i":1},"a":[{"0":{"r":[{"g":12,"v":0}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0,"t":0}]},{"t":24,"g":14,"h":-2,"z":-3}]}

It creates two accessories--one for the relay and one for two sensors (the default DHT22).

**Comment by RavenSystem** [comment]
I suggest tis better, to allow enter setup mode holding button:
