### ISSUE TITLE
HAA Templates for H801

### ISSUE THREAD

**Issue by kutdenis** [RavenSystem/esp-homekit-devices#565]
Now running on ravencore, wanted to upgrade to HAA. Is there a working configuration on this device?

https://github.com/arendst/Tasmota/wiki/H801

**Comment by RavenSystem** [comment]
HAA does not support RGBW lights yet.

**Comment by RavenSystem** [comment]
Last version of HAA supports RGBW lights. Can you provide info about your RavenCore setup, please?

**Comment by kutdenis** [comment]
Board type 1, Device type 14, Pin B 12, Pin G 13, Pin R 15, Pin W 14

**Comment by RavenSystem** [comment]
`{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":15,"g":13,"v":12,"w":14,"b":[{"g":0}]}]}`

**Comment by RavenSystem** [comment]
Ensure that you are using last HAA version (v0.6.1).

**Comment by kutdenis** [comment]
Can't go into setup mode now. Removed and updated to 0.6.6 through the computer, configured the new and installed back. But can't update over the air to 0.6.7. Also not included in the setup mode. Entered the setup mode as specified in the wiki

**Comment by kutdenis** [comment]
Sonoff switches are perfectly updated

**Comment by RavenSystem** [comment]
How are you trying to enter in setup mode?

**Comment by kutdenis** [comment]
10 taps in the home app. It works with sonoff

**Comment by RavenSystem** [comment]
0.6.6 is less responsive with lightbulbs. Try doing it slower. A little less than a second between each tap.

**Comment by kutdenis** [comment]
Updated, very slowly clicked 10 times!

**Comment by RavenSystem** [comment]
This works better with last version.

**Comment by kutdenis** [comment]
At some point, the device stopped responding, tried to flash it, but it still does not respond. Maybe the template has changed?
