### ISSUE TITLE
HAA

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#567]
Hello!

Please add a type of intercom with the ability to select gpio to call (short, long press)

Thanks

**Comment by RavenSystem** [comment]
Intercom? Do you mean video doorbell?

**Comment by netRunner0** [comment]
Yes:

**Comment by netRunner0** [comment]
![IMG_0260](https://user-images.githubusercontent.com/44049295/67677685-7ab3c580-f9a6-11e9-93dd-9fa24faca8ea.jpeg)

**Comment by RavenSystem** [comment]
That is totally impossible. ESP8266 chip can not manage a video camera.

**Comment by netRunner0** [comment]
No camera needed. The main thing is the notification intercom

**Comment by RavenSystem** [comment]
You can not make a HomeKit doorbell without a camera. It is mandatory.

**Comment by netRunner0** [comment]
can I take a static screenshot?

**Comment by RavenSystem** [comment]
No, you can not. ESP8266 has not enough power to manage and process images.

**Comment by RavenSystem** [comment]
A good alternative could be to use HomeKit occupancy sensor accessory type.

**Comment by netRunner0** [comment]
Is it possible to implement on esp32?

**Comment by RavenSystem** [comment]
Yes.

**Comment by netRunner0** [comment]
I would like to see this feature in future releases of the HAA)

Thanks for the quick answers ;)
