### ISSUE TITLE
Ravencore RGBW external toggle - HAA needed!

### ISSUE THREAD

**Issue by manimac79** [RavenSystem/esp-homekit-devices#571]
Hello, I've just flashed my Shelly RGBW2 with Ravencore OTA firmware.

It's nice, everything works properly except the external toggle button. As instructions on shelly website i've connected a button/switch on "I" and "GND" pins but i'm unable to getting any result.

On EVE setup i've set the Board Type: 3 and Device Type: 14

I've tried Board Type 0, 1, 2, 3, 4, 5.
I've tried also External Toggle 0, 1, 2, 3 without lucky.

Please help me, thanks ;)

**Comment by RavenSystem** [comment]
INow HAA v0.6.0 has PWM Lights support.
