### ISSUE TITLE
Interlock function Sonoff T2EU2C

### ISSUE THREAD

**Issue by CaptainTib** [RavenSystem/esp-homekit-devices#573]
Hi, 

Is it possible to add interlock function on Sonoff T2EU2C ?
The original firmware allow this (see picture attached).

Thanks ! 

![IMG_2611](https://user-images.githubusercontent.com/10421100/67938283-7c140680-fbcf-11e9-8651-5c31a0e2bfc9.PNG)

**Comment by RavenSystem** [comment]
Sorry, no. You must use HomeKit automations to do that.

**Comment by CaptainTib** [comment]
Ty for adding interlocks in HAA templates !
