### ISSUE TITLE
HAA - Init last state - Sonoff MINI

### ISSUE THREAD

**Issue by Fudalii** [RavenSystem/esp-homekit-devices#576]
Hello.

Does the parameter Init State (las state: 5) work with Sonoff MINI ?? I don't know where I am making a mistake. I tried to add "s": 5 as below but it doesn't work

{"c": {"l": 13, "b": [{"g": 0, "t": 5}]}, "a": [{**"s":5**, "0": {"r": [{ „g”: 12}]}, „1”: {„r”: [{"g”: 12, „v”: 1}]}, „b”: [{„g”: 0}, {” g ": 4}, {" g ": 4," t ": 0}]}]}

**Comment by RavenSystem** [comment]
Your "s" key is right, but last state is not saved immediately. It takes 5 seconds since last state changes to preserve flash integrity.

`{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"s":5,"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":4},{"g":4,"t":0}]}]}`
