### ISSUE TITLE
Floureon type Display Thermostat HAA

### ISSUE THREAD

**Issue by tohmc** [RavenSystem/esp-homekit-devices#578]
Hi Jose,

Is it possible to use HAA with an Fluoreon WiFi Display Thermostat?
It would be great!

Regards
Tohmc

**Comment by RavenSystem** [comment]
We need more info about that device. First, does it use esp8266 chip? And then... how it works?

**Comment by tohmc** [comment]
Ok I will find these informations.
Maybe I buy one of these for you?
