### ISSUE TITLE
WiFi AP 

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#58]
When the network is not available, esp launches the WiFi AP how to increase the waiting time until the network is available.
This happens when electricity is interrupted.

**Comment by RavenSystem** [comment]
You can define the waiting time (in milliseconds)  in your Makefile:
`EXTRA_CFLAGS += -I../.. -DHOMEKIT_SHORT_APPLE_UUIDS -DWIFI_CONFIG_CONNECT_TIMEOUT=<waiting_time_msec>`

You can see an example here: 
https://github.com/RavenSystem/esp-homekit-devices/blob/master/devices/Sonoff_RavenCore/Makefile

**Comment by Kristian8606** [comment]
thank you
