### ISSUE TITLE
Sonoff Basic+Switch+DHT22 template done

### ISSUE THREAD

**Issue by straubus** [RavenSystem/esp-homekit-devices#582]
Hi, I've created template for Sonoff basic ( RF R2) with wall switch connected to GPIO12 (tx) and DHT22 on GPIO2 (IO2 pin)

{"c":{"o":1,"l":13,"i":1},"a":[{"t":1,"0":{"r":[{"g":12,"v":0}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0,"p":1,"t":1},{"g":3,"p":1,"t":1},{"g":3,"t":0}]},{"t":24,"g":2}]}

It works great, so You could try it.

**Comment by nmartyd** [comment]
Can you share how you connected the DHT22 please?  Maybe a picture?

**Comment by RavenSystem** [comment]
Many thanks!

Better removing default values and disabling UART output: 
`{"c":{"l":13},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":3},{"g":3,"t":0}]},{"t":24,"g":2}]}`
