### ISSUE TITLE
Looking for HAA JSON for Magic Home LED Single Channel

### ISSUE THREAD

**Issue by Olepir** [RavenSystem/esp-homekit-devices#585]
Looking for HAA JSON for Magic Home LED Single Channel
Thanks in advance

**Comment by RavenSystem** [comment]
Example using only a channel in GPIO14.

`{"a":[{"t":30,"w":14}]}`

**Comment by straubus** [comment]
For magicLED single controller on esp8285 {"a":[{"t":30,"w":12}]}

**Comment by mafyata** [comment]
You can add "s":5  for last state if power down and back again.
