### ISSUE TITLE
Shelly 2.5 rolling shutters with external double push switch

### ISSUE THREAD

**Issue by Kienz** [RavenSystem/esp-homekit-devices#587]
Is it possible with the Shelly 2.5 to control a rolling shutter and have an external double push switch? Do you have an configuration example?
The double push switch have two buttons - one to open and one to close the rolling shutter.

**Comment by RavenSystem** [comment]
You can try RavenCore and set external SW to 1.

**Comment by Shimakuchi** [comment]
will there be a HAA Solution (soon)? thx
