### ISSUE TITLE
Sonoff Basic R2 ds18b20

### ISSUE THREAD

**Issue by ahg675** [RavenSystem/esp-homekit-devices#589]
Hi 
I have sonoff basic r2 with ds18b20 on gpio2 .
How to change gpio14 to gpio2 in this template:

Sonoff Basic/SV/TH10/TH16 HomeKit Switch and Temperature with DS18B20 sensor at GPIO 14:
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"t":22,"g":14,"n":3}]}

**Comment by RavenSystem** [comment]
Replace "g":14 with "g":2  ;)

**Comment by ahg675** [comment]
Thank You

**Comment by ahg675** [comment]
One more question
It is possible to make
Sonoff TH16 HomeKit Switch plus Temperature and Humidity sensor at GPIO 14

**Comment by RavenSystem** [comment]
Theorically, yes. Never try.

**Comment by ahg675** [comment]
"n": Sensor type:
DHT11.
Default. DHT22.
DS18B20.
Si7021 (Not recommended).

**Comment by RavenSystem** [comment]
Sorry, I read your question better. Answer is: sure, you can.

**Comment by ahg675** [comment]
Working with n2 but only shows temp
Here is my example:
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"t":22,"g":14,"n":2}]}

**Comment by RavenSystem** [comment]
DS18B20 is only a temperature sensor, not humidity.

**Comment by ahg675** [comment]
I have DHT22

**Comment by ahg675** [comment]
Sonoff Basic R2 ds18b20 is working now
I have another sonoff th16 with DHT22

**Comment by ahg675** [comment]
Sorry for mix-up

**Comment by RavenSystem** [comment]
You must use type 24 instead 22:

https://github.com/RavenSystem/esp-homekit-devices/wiki/Home-Accessory-Architect#type-24-temperature-and-humidity-sensor

**Comment by ahg675** [comment]
Thank You very much

**Comment by RavenSystem** [comment]
You are welcome. 😉

**Comment by ahg675** [comment]
Sorry but I'm still here :)
I did changes but humidity not show at all

TH16 plus DTH22

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"t":24,"g":14,"n":2}]}

**Comment by ahg675** [comment]
Can You correct me, please

**Comment by RavenSystem** [comment]
Have you reset Homekit ID of your device?
 
> If you make changes in your JSON that involve accessory types, number of used accessories or change order of them, you must check "Reset HomeKit ID" from "Setup mode" and remove your device from HomeKit; and then you must pair it again.

https://github.com/RavenSystem/esp-homekit-devices/wiki/Home-Accessory-Architect#json-config

**Comment by ahg675** [comment]
Thank You again
Now I understand everything

**Comment by RavenSystem** [comment]
Is it working fine now?

**Comment by ahg675** [comment]
Yes

**Comment by RavenSystem** [comment]
Good!
