### ISSUE TITLE
GPIO 14 as momentary switch

### ISSUE THREAD

**Issue by Fernyman79** [RavenSystem/esp-homekit-devices#59]
I'm trying to use a Sonoff SV with a touch sensor connected to GPIO 14. The sensor works, but it seems that the current implementation is for a toggle, or a mechanical switch, so as soon as I stop touching the sensor, the Sonoff (switch) turns off. The onboard button acts as a momentary switch, but I couldn't find a way to wire the sensor to it's contacts. Any idea on how this can be achieved?

**Comment by RavenSystem** [comment]
Yes, GPIO14 in dev type 1 is for a toggle. I can add a setup option to select it for a touch button.

**Comment by Fernyman79** [comment]
That would be awesome!

I'm really enjoying your work on this project, btw. It finally made HomeKit viable to me. I can't really contribute, since I'm not an experienced programmer, but I'd love to support it on any other way.

**Comment by Fernyman79** [comment]
Curious, is this this something I can change in the source and compile myself? I tried to find any reference in the code, but I'm not sure what I'm looking for.

**Comment by RavenSystem** [comment]
It's a new feature that must be developed and implemented.

**Comment by RavenSystem** [comment]
Version 0.4.4 changes the way to manage GPIO14 in dev type 1. If new way works fine to avoid AC interferences, I will can add an option to setup GPIO 14 as momentary switch easily.

**Comment by RavenSystem** [comment]
Added to TODO list: https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List

**Comment by RavenSystem** [comment]
Ready and tested!

https://github.com/RavenSystem/esp-homekit-devices/releases/tag/0.4.7
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#gpio14-toggle-default-off
