### ISSUE TITLE
MagicHome LED Dimmer

### ISSUE THREAD

**Issue by mientki** [RavenSystem/esp-homekit-devices#592]
Hello

Is it possible to set HAA as a bulb with a dimmer? In the sample templates I can only see MagicHome RGBW and RGB. What should JSON look like? I have MagicHome LED Dimmer with single channel for monochrome led strip.

**Comment by RavenSystem** [comment]
Declare only "w" pin.

**Comment by bj-tracer** [comment]
Hello!
How to reset that bulb with HAA (or going to setup mode)?
This device hasn't buttons. You need to switch on/off it 10 times for reset with original firmware.

**Comment by mientki** [comment]
I have MagicHome single channel and I'm trying to set up HAA. I don't know what I'm doing wrong, but configuration doesn't work. Please help. My configuration:


```
 {
   "c": {
     "b": [{
       "g": 0,
       "t": 5
     }]
   },
   "a": [{
     "t": 30,
     "w": 12,
     "b": [{
       "g": 0
     }]
   }]
 }
```


Correct settings of this device on other software:
(https://github.com/curla92/LED-Dimmer-Homekit)

![Ustawienia EVE - RavenCore LED Dimmer](https://user-images.githubusercontent.com/37380727/71646865-e0e1ff00-2ced-11ea-8470-b3b2635e679e.png)
