### ISSUE TITLE
Sonoff 5V - A Fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header

### ISSUE THREAD

**Issue by jakudo** [RavenSystem/esp-homekit-devices#593]
Hi,

I'm a newbie here. I'm trying to flash Sonoff 5V - to work with HomeKit for my Gate.
Here is how I connected it:
<img width="1053" alt="Screenshot 2019-11-09 at 21 52 37" src="https://user-images.githubusercontent.com/57570372/68534953-42639e00-033b-11ea-9332-1f332f540d10.png">

I've tried to put it into the Flash mode as described here:
https://www.youtube.com/watch?v=E0WBoFCcnYY

and it does the same as in the video.

However, when I try to run command:

 `esptool.py -p /dev/ttyUSB0 erase_flash`
it starts connecting, shows several .......______.......... and then 
`A Fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header`

Any idea what am I doing wrong?

**Comment by Bene2103** [comment]
Are you using the right port?

try "ls /dev/" and see what the right port is. It should look something like "tty.usbserialxxxxx"

What OS are you running?

**Comment by jakudo** [comment]
sorry, forgot to mention it. I use Ubuntu 19.04

The only difference between "ls /dev/" before and after I plug it in is "ttyUSB0"

**Comment by Bene2103** [comment]
Ok then this device should be the right one.

Maybe RX and TX are switched?

**Comment by jakudo** [comment]
Tried that too with the same result.

**Comment by jakudo** [comment]
Hello,

so for other I found what the probelem was. The pins 1 and 4 on the first picture was ok, however 2 nad 3 was incorret.
The Tx and Rx should be connected directly on the chip (see red rectangle) on 5th and 6th pin from button.
So it might help somebody.
![2019-11-14 11_33_48-Sonoff 5V - A Fatal error occurred_ Failed to connect to Espressif device_ Timed](https://user-images.githubusercontent.com/57570372/68849857-22cdcc00-06d3-11ea-8709-a4555ed0ab35.png)
