### ISSUE TITLE
New free Windows flasher

### ISSUE THREAD

**Issue by vglucas** [RavenSystem/esp-homekit-devices#597]
HomekitFlasher is a simple application for Windows desktop environments developed for free and downloadable from https://github.com/vglucas/HomeKitFlasher. An excellent tool dedicated to those who are not familiar with the terminal and want to make, and speed up, the flash of their device. The main and predefined actions of the system also allow the Ravencore firmware flash, developed by José A. Jiménez and Life Cycle Manager called OTA (acronym of Over The Air) and created by HacK (HomeACcessoryKid). As we will see below, the program also allows third-party firmware flashes thanks to a simplified interface.

For any signaling from the menu? - Report and send your report

**Comment by than-sad** [comment]
Hi, I bought 8 sonoff basic r3 and searching on internet I found one website using this app like the only one who's able to flash this devices with old Ravencore. I bought a USB adapter based on FT232RL from FTDI, got an old laptop, installed windows, installed this app, installed the USB adapter drivers, and when I Tried to flash the devices, the app didn't recognized the FTDI adapter. Finally I went back to my mac and done it easier than expected just with two command lines (delete, and flash). Supposedly the only way to flash this devices was flashing first the firmware with blank_config.bin in three different addresses after erase it. Probably was my fault because I didn't understand it properly (wasn't my language (es) or english). I'm absolutely newbie in the flashing firmwares world.

It's just my experience, I'm sure this app can be really useful for a lot of people. Wasn't my case.

Best regards,
Than.

**Comment by vglucas** [comment]
Hi, there are some devices that are not detected by windows, the manufacturer of the FT232 has included in its latest Driver a control if the FT232 is not a fake one. If it finds it falsified it resets the VID with which Windows recognizes the USB device. perform this procedure or from the menu? and SEGNALA, send a message to me and I will be happy to help you
![ALL](https://user-images.githubusercontent.com/49847470/68803242-aa79f300-065f-11ea-9a4d-fa6e92c24992.jpg)

**Comment by than-sad** [comment]
Hi, I downloaded signed drivers from website, connected the device and after detected by windows installed it and checked in device manager if the device was present and with no conflicts. In your app, tried several times to detect it but always with message 0 devices found. Anyway is windows, there are thousand reasons to fail. Thanks for your interest in help. Im a happy Mac user (hackintosh in my case) and to be honest every time I run Windows OS I finish frustrated and tired of install eternal updates and stupid errors.

Best regards.

**Comment by batista16** [comment]
I also have issues with this, no devices found.

**Comment by vglucas** [comment]
what kind of device do you use? perform the procedure described above
![IMG_9974](https://user-images.githubusercontent.com/49847470/69183013-69c42300-0b12-11ea-8010-7589a00beb90.jpg)

**Comment by batista16** [comment]
![image](https://user-images.githubusercontent.com/6854591/69183970-d982df80-0b0b-11ea-9a74-ce9f32137617.png)

This is the error that I get when I try to scan. 

I have a FTDI232, and the device works with other methods.

**Comment by vglucas** [comment]
did you run the full scan as described above ? Open a report from the menu ? and then SEGNALA it and I'll contact you and I'll be happy to help you

**Comment by vglucas** [comment]
I made changes, can you update and check?

**Comment by diodo157** [comment]
Hi everyone ... tried the program is really very nice ... easy and intuitive ... it works fine for me. for those who have some problems, I suggest you uninstall Pyton and also delete the files that remain in the folder, then reinstall everything. Really very happy to have found this program

**Comment by diodo157** [comment]
![0101](https://user-images.githubusercontent.com/36050040/69196281-5b840000-0b2e-11ea-840e-ed30e6ef17b0.png)

**Comment by batista16** [comment]
now I see this: 
![image](https://user-images.githubusercontent.com/6854591/69220300-8db45280-0b6c-11ea-9d71-b07ff01e0ab9.png)

I see an FTDI there but doesn't look like the COM port.

**Comment by vglucas** [comment]
I have found that the FTD2XX chips are not detected by the program, I am working fully on this.

**Comment by maxnasva** [comment]
hello,I tested the program successfully with these devices:
CP2102 chip usb interface
nodemcu (3 item different)
arduino
see attached photos
![IMG_6031](https://user-images.githubusercontent.com/47340771/69323537-3800a880-0c47-11ea-88e6-65e9fb826345.jpg)
![IMG_6030](https://user-images.githubusercontent.com/47340771/69323553-3cc55c80-0c47-11ea-84fa-961d5a277da1.JPG)
![IMG_6027](https://user-images.githubusercontent.com/47340771/69323559-4058e380-0c47-11ea-94fb-865949dd6d55.JPG)

**Comment by slidset** [comment]
I used the program with the serial converter FTD1232, it works.
just download the drivers:
https://www.ftdichip.com/Drivers/CDM/CDM21228_Setup.zip
![IMG_2147](https://user-images.githubusercontent.com/57323956/69484190-bff5d680-0e30-11ea-8d49-78ff63715ec1.jpg)
