### ISSUE TITLE
Device freezed after HAA 0.6.10 update

### ISSUE THREAD

**Issue by macjl** [RavenSystem/esp-homekit-devices#598]
Hello,

I have updated some of my sonoff devices today. I have updated them to the version 0.6.10 before seeing there were an issue with it :

> Fixed a bug introduced in v0.6.9 that resets device when a sensor is activated.

I was able to update most of the devices to 0.6.11, but one of them seems to be freezed now. It is not accessible from Home App, doesn't respond ton ping, and I'm not seeing any Wifi SSID from it. I tried to switch off and on the power without luck.

Should I have to re-flash to recover it? Or is there another way? The sonoff is not very accessible, and if there is an other solution it would be great.

**Comment by mafyata** [comment]
Did you try to power off and on again?

**Comment by mafyata** [comment]
I had one frozen device and when I unpluged and pluged again to the wall ac source it work again.

**Comment by macjl** [comment]
I tried it multiple time without success.

**Comment by mafyata** [comment]
Check in home app to add accessories. I had device waiting to be added after power failure with haa 0.5

**Comment by macjl** [comment]
Thank you for your help, but still no success with this...
I think I will have to re-flash it.

**Comment by than-sad** [comment]
Hi, I had similar problem with one TH16 in Thermostat mode. After OTA update, it didn't responded until I checked trying to add new device in Home and detected it as a new one. Deleted the old one and problem solved.

Regards, Than.

**Comment by RavenSystem** [comment]
Sorry for the bug update. But it only affected to accessories with sensors (but not temperature sensors). In my case, I cut general power and reposer it, and then I updated my faulty device using OTA.

**Comment by macjl** [comment]
It was a Sonoff Basic with switch and stateless button on GPIO 0 + contact sensor on GPIO 2.
I have re-flashed it and it’s working now.

**Comment by RavenSystem** [comment]
Using a contact sensor in gpio 2 is not a good idea, because gpio 2 must be high when device boots.

**Comment by macjl** [comment]
I know that. But this contact sensor is normally high, except when someone push the doorbell. So the reboot go right most of time.
Do you know if I can use Rx or Tx pin instead of GPIO2 ? What are their PIN number ?

**Comment by RavenSystem** [comment]
@macjl Ok, I only told you it ;). You can use GPIO 3 if you want (I think it is RX).

**Comment by macjl** [comment]
Thank you!
For my future devices, I will prefer the use of GPIO 3.
