### ISSUE TITLE
Question - Sonoff TX -Single gang switch

### ISSUE THREAD

**Issue by hexardavies** [RavenSystem/esp-homekit-devices#599]
Can you use a sonoff basic HAA code in a TX unit??

**Comment by hexardavies** [comment]
I think i answered my own question.  Sonoff TX single gang wall switch.

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":9},{"g":0,"t":1}],"s":0,"f0":[]}]}

**Comment by RavenSystem** [comment]
Better:

`{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":9},{"g":0]}]}`
