### ISSUE TITLE
PWM dimmer. Single color led strip or cct ”dual color”

### ISSUE THREAD

**Issue by jukorp** [RavenSystem/esp-homekit-devices#60]
can you help me?
I need pwm dimmer. ”One color led strip”

-One button. ”Long press to dimming and short press on/off”
-Initial state is off.
-Remember dimmable settings.

**Comment by RavenSystem** [comment]
Sorry. This repo is focused on Sonoff devices, but not in custom prototypes. Maybe you should do your question is this repo: 
https://github.com/maximkulkin/esp-homekit-demo

**Comment by Kristian8606** [comment]
This is the same
https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/magic_home_strip/magic_home.c

**Comment by jukorp** [comment]
Can you check this?
This is sonoff product.
https://www.itead.cc/sonoff-led.html

Includes a features Cct and rgb.

**Comment by Kristian8606** [comment]
I have a similar device going i give the code when it's completely done

**Comment by Kristian8606** [comment]
https://github.com/Kristian8606/simple_dimming_LED

**Comment by homkittoby** [comment]
@Kristian8606 

Hi,
Did you also write a version with bin file for the original MagicHome LED strip controller?
#define RED_PWM_PIN 5
#define GREEN_PWM_PIN 12
#define BLUE_PWM_PIN 13
greetings

**Comment by Kristian8606** [comment]
My English is very bad, and I'm not sure I understand your question properly
