### ISSUE TITLE
Sonoff 5V - can't see it outside of WiFi

### ISSUE THREAD

**Issue by jakudo** [RavenSystem/esp-homekit-devices#602]
Hi,

I'd like to ask you for a help. I've instaled Ravencore to Sonoff 5V to be able to open/close main gate from CarPlay. When I'm at home on WiFi, I can Sonoff in HomeKit and I'm able to open/close it. However, when I leave home or disconnect from WiFi, it shows "No Response" in HomeKit (other devices are ok outside WiFi). Any idea what did I do wrong?

Thanks,
Jakub

**Comment by RavenSystem** [comment]
Sorry, RavenCore is not supported. I suggest to migrate to HAA.

**Comment by jakudo** [comment]
Yes, I know it is not supported yet, but HAA does not have the garage door function yet.
However, it fixed itself somehow after restart both Sonoff 5V and Apple TV
