### ISSUE TITLE
Problem V.6.14 on magic home led rgb

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#604]
Hi , I updated to v6.14 and my led strips have a problem. The light is very very low. I don’t have a problem when I was on v6.11
![8292FE7D-68F1-4E77-9F76-E697ADDA79F5](https://user-images.githubusercontent.com/48009267/68852746-32eca800-06e1-11ea-8ef6-9e422b4f957c.jpeg)

**Comment by mafyata** [comment]
This is my config and was working good.
 {"c":{"b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13}]}
Can I downgrade to v.6.11 ?

**Comment by bj-tracer** [comment]
https://github.com/RavenSystem/haa/releases/tag/0.6.11 - You may download main.bin and install it without OTA.

**Comment by mafyata** [comment]
Thanks. I prefer ota . Where may be is the problem? I tried “p”,”d” actions , but no success, same result.

**Comment by bj-tracer** [comment]
p & d  is for transitions effects
try to use RGBW Factor

**Comment by mafyata** [comment]
Tried just now , nothing happens.

**Comment by mafyata** [comment]
And i am seeing a mistake. Auto dimmer has 2 option with same initial - “d”

**Comment by kutdenis** [comment]
Same problem, but on H801. Very faint light. 
{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":15,"g":13,"v":12,"w":14,"b":[{"g":0}]}]}

**Comment by mafyata** [comment]
With 6.15 is good , but when changing brightness or on/off it is blinking brighter. On 6.11 was perfect.

**Comment by RavenSystem** [comment]
@mafyata Can you try this to know if issue is PWM freq?

`{"c":{"q":65535,"b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13}]}`

**Comment by mafyata** [comment]
I will try it later and will write the result.

**Comment by mafyata** [comment]
No, no changes .

**Comment by RavenSystem** [comment]
@mafyata And with this?

`{"c":{"q":1000,"b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13}]}`

**Comment by mafyata** [comment]
No

**Comment by RavenSystem** [comment]
@mafyata Try last version 0.6.16 with your original JSON:

`{"c":{"b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13}]}`

**Comment by mafyata** [comment]
Yes , now is ok

**Comment by mafyata** [comment]
On 0.6.15 it was blinking brighter when I was set it to 100%. Is it mean that my led strip was not lighting at 100%?

**Comment by RavenSystem** [comment]
@mafyata it depends of selected color. To keep brightness stable, when you select white, color channels are at 33% and white is at 100%. You can play with factor options, depending what you want:

For example, try this:
`{"c":{"b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13,"fr":3,"fg":3,"fv":3}]}`
