### ISSUE TITLE
Flash Mode

### ISSUE THREAD

**Issue by tonysprenk** [RavenSystem/esp-homekit-devices#606]
I'm trying to flash this firmware on some wall sockets OTA with [Tuya-Convert](https://github.com/ct-Open-Source/tuya-convert). I've bundled rboot.bin, blank_config.bin and OTAboot.bin into one binary file as Tuya-Convert only allows for 1 file to be used when flashing. Then I found out that rboot.bin is set to flash mode QIO @ 2MB while the device with the esp8266 in it is set to DOUT @ 1MB. How can I change the flash mode of rboot.bin?

**Comment by tonysprenk** [comment]
figured it out. thanks!

**Comment by pawelosin** [comment]
I have the same issue. How did you resolve that?

**Comment by gerardwr** [comment]
https://github.com/ct-Open-Source/tuya-convert/issues/389
