### ISSUE TITLE
Support for Window Covering

### ISSUE THREAD

**Issue by tonysprenk** [RavenSystem/esp-homekit-devices#608]
Hi, I have a few [curtain devices](https://s.click.aliexpress.com/e/n3g3Q1For) that I would like to flash to be compatible with HomeKit. Could anybody point me in the right direction?

**Comment by RavenSystem** [comment]
RavenCore firmware with Shelly 2.5 devices is compatible, but you will need HAA firmware to do what you want. Problem is that HAA is not compatible with coverings yet. You must wait.

**Comment by tonysprenk** [comment]
Ok! Let me know if I can do any testing! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RavenSystem** [comment]
Sure! But first of all, it is necessary to know the GPIOs used by those devices.

**Comment by mientki** [comment]
is there a chance of support for window blinds and shelly 2.5 in the near future? RavenCore is very difficult for beginners.

**Comment by mafyata** [comment]
Haa is more difficult.

**Comment by tonysprenk** [comment]
https://github.com/arendst/Tasmota/wiki/Zemismart-Curtain-Motor this is the device. hopefully it helps.

**Comment by mientki** [comment]
> Haa is more difficult.

it is not more difficult if I configure the device :) and a friend will only add it to their home application.

**Comment by mafyata** [comment]
Yes , but more people here will flash, configure and you use it without friend.

**Comment by RavenSystem** [comment]
If a JSON template exists, HAA is easier than RC. But that is not the matter, because RC is outdated, deprecated and is no longer developed. Only Garage Doors and Window Covers left to migrate to HAA. And when you control your air conditioner or your TV using only an ESP-01 with an IR-LED, you will forget RC very quickly.

**Comment by mientki** [comment]
We are all patiently waiting for support for windows blinds. :)
