### ISSUE TITLE
Firmware for Sonoff SC

### ISSUE THREAD

**Issue by kutdenis** [RavenSystem/esp-homekit-devices#611]
For a long time is not used such a device. Can there is opportunity flash his on HAA? 

https://www.itead.cc/sonoff-sc.html

**Comment by Bene2103** [comment]
I don't think air quality, sound level and light intensity is implemented in HAA yet. But temperature and humidity should work if the sensors are the supported ones.

**Comment by RavenSystem** [comment]
@Bene2103 is right.

**Comment by St0nehead** [comment]
Also waiting for Sonoff SC compatible firmware..
🙏

**Comment by pilot1981** [comment]
SONOFF SC was disconitued, you can use SONOFF TH10/TH16 with temperature monitor and humidity monitor sensors to access the same functionality
