### ISSUE TITLE
Sonoff Basic pinouts remap

### ISSUE THREAD

**Issue by dbartelmus** [RavenSystem/esp-homekit-devices#616]
Hi there, I wonder is it possible to **remap Sonoff Basic** default 5 pins (GND, TX, RX, 3.3, IO2) to work as RGB/**RGBW** accessory?

Similar to: MagicHome RGBW LED Strip Controller (R pin 15, G pin 13, B pin 12, W pin 14):
`{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":15,"g":13,"v":12,"w":14,"b":[{"g":0}]}]}`

**Comment by RavenSystem** [comment]
You can remap GPIOs (GND and 3.3V are not GPIOs), but then you must connect them a PWM manager with final transistors to work as RGB accessory.
