### ISSUE TITLE
Setup Mode for HAA 0.0.4 and 0.0.7 

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#619]
Hi to all of you
Please is there anyone can help me remember how to enter in setup mode for firmware 0.0.4 and 0.0.7
I need update to last release.

And another request is if I need change json after update or that json is ok again.

Thank you in advance

**Comment by RavenSystem** [comment]
To enter setup mode, you must turn on and off quickly  your accessory more than 10 times, BUT within **first 30 seconds** since it boots.

**Comment by GPL71** [comment]
ok  ... then is different respect to latest releases and maybe a new json is necessary. thank you

**Comment by RavenSystem** [comment]
If you need help with JSON, you can ask ;)
