### ISSUE TITLE
Problems accessing setup mode HAA 0.6.12

### ISSUE THREAD

**Issue by Ni88-dpb** [RavenSystem/esp-homekit-devices#622]
Good evening, use the haa firmware on some sonoff4ch. I have to change the wifi network to which they connect, but it is impossible to enter the setup mode. I disconnect, reconnect, wait a few seconds and then press the sequence of 10 times on / off ... the AP appears but when I try to connect to access the configuration page there is no way to connect. I always get an access error. after about 1 hour and a half of tests I succeeded, by pure chance, in changing one out of three ... is it possible that every time I have to change the WiFi network I have to repeat the flash procedure? isn't there a more convenient way to access the wifi configuration as it was on ravencore? thank you very much!

![BD3D5EF9-85B3-4E0D-A8B6-E1C19D0C9B15](https://user-images.githubusercontent.com/57964358/69182427-46e53f00-0b11-11ea-81b4-a849e1cec20e.png)

**Comment by RavenSystem** [comment]
You can access directly using the IP address of your network that device has.
