### ISSUE TITLE
Does sonoff t3 supported by HAA?

### ISSUE THREAD

**Issue by johndeee** [RavenSystem/esp-homekit-devices#635]
Can I flash Sonoff T3 3 gang using HAA?

**Comment by Bolshoylu** [comment]
yes it works fine for me

**Comment by leonealex** [comment]
Witch configuration do you use (json)

**Comment by Bolshoylu** [comment]
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":10}]}]}

**Comment by am-basto** [comment]
ola...teria como me informar o codigo Json para T2 ?

**Comment by am-basto** [comment]
ola....teria o código para 2 botões  ( teclas )
