### ISSUE TITLE
Better support for CCT Bulbs

### ISSUE THREAD

**Issue by danielhelmstedt** [RavenSystem/esp-homekit-devices#641]
Hi! is it possible to get control for 2-channel CCT bulbs where one channel is a dimmer and the other controls temperature via PWM between WW and CW?

See this Tasmota template - https://blakadder.github.io/templates/arlec_GLD112HA.html

Thank you!

**Comment by danielhelmstedt** [comment]
Just bumping this, any chance it’s possible?

**Comment by RavenSystem** [comment]
Not possible. Only normal PWM devices are supported. That device uses PWM in a custom way.

**Comment by danielhelmstedt** [comment]
Is this something that should be taken up with esp-homekit then? Are you getting the temperature value from the HSI or from the Mired characteristic?If you are using mired, it seems like it should be easy to implement a function that converts mired to pwm value -

assuming say 3000K/~333mired and 5700K/~175 (my bulbs in question). That’s a difference of 158, so all you need is to divide 255/158 and apply that value as a Pwm output, no?

**Comment by danielhelmstedt** [comment]
I know at least some Trådfri bulbs work this way as well, so it has at least been done before
