### ISSUE TITLE
Hostname is not recognized by network

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#642]
Hi , I updated to 7.10 but can’t enter in setup mode. Tried http://hol-led and http://haa-f8f4fc
I entered hol-led in hostname in json

**Comment by RavenSystem** [comment]
Custom hostname doesn't work with setup mode, but haa-f8f4fc must work. Can you try `ping haa-f8f4fc` ?

**Comment by mafyata** [comment]
I entered setup mode by ip : http://10.0.1.104/
ping HAA-F8F4FC
Ping request could not find host HAA-F8F4FC. Please check the name and try again.

Pinging 10.0.1.104 with 32 bytes of data:
Reply from 10.0.1.104: bytes=32 time=29ms TTL=255
Reply from 10.0.1.104: bytes=32 time=15ms TTL=255
Reply from 10.0.1.104: bytes=32 time=29ms TTL=255
Reply from 10.0.1.104: bytes=32 time=16ms TTL=255

**Comment by mafyata** [comment]
I use latest apple airport extreme router. May be the problem is with the router.

**Comment by RavenSystem** [comment]
What DNS server are your using?

Can you try nslookup?
`nslookup 10.0.1.104`

**Comment by mafyata** [comment]
Server:  UnKnown
Address:  10.0.1.1

*** UnKnown can't find 10.0.1.104: Non-existent domain

**Comment by mafyata** [comment]
Now I tried Bonjour Browser. It is not showing anything. The problem is with apple airport routers.

**Comment by RavenSystem** [comment]
It is strange that an Apple Airport doesn't allow DHCP hostname option. I have an Asus router and I have not any problem.

**Comment by mafyata** [comment]
I can give you access to my computer for some tests.

**Comment by macjl** [comment]
Have you tried to use : 
ping HAA-F8F4FC.local

**Comment by mafyata** [comment]
>ping haa-f8f4fc.local
Ping request could not find host haa-f8f4fc.local. Please check the name and try again.

**Comment by N3mo72** [comment]
Sorry for off-topic but : what is the correct JSON syntax to insert the custom hostname and its position in the string?
Thank you.

**Comment by mafyata** [comment]
Here is one example of my device:
{"c":{"n":"Kuhnq-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13}]}
Hostname is: Kuhnq-Led

**Comment by N3mo72** [comment]
This is mine code but not work :
{"c":{"n":"my-switch","l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}],"s":5}]}

What's wrong ?

**Comment by mafyata** [comment]
It looks ok. What is the problem?

**Comment by N3mo72** [comment]
This is the Json config that use in first configuration. After reboot, i have always HAA-XXXXXX. I tried to select the option “Reset ID” but not work
