### ISSUE TITLE
HAA - Sonoff T1 EU 2Gang

### ISSUE THREAD

**Issue by quartist** [RavenSystem/esp-homekit-devices#646]
Hello,

I looking for HAA template for Sonoff T1 EU 2Gang.
Does anyone have this template?

**Comment by Bolshoylu** [comment]
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]}]}]}
