### ISSUE TITLE
Sonoff SV as Garage Door Template

### ISSUE THREAD

**Issue by kokos1405** [RavenSystem/esp-homekit-devices#649]
Has anyone managed to setup sonoff sv as garage door?
Is there a ready template?

**Comment by mientki** [comment]
I have waited a long time for this functionality :)  I also ask for an example Template for garage door opener.

**Comment by noobydp** [comment]
👍

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates#sonoff-with-homekit-garage-door-adaptation-working-time-18-seconds-only-close-sensor-connected-to-gpio-14-and-stop-step-dry-relay-connected-to-action-garage-door-button

**Comment by macjl** [comment]
Hello,

I've set up pretty similar Json. But can you explain this part?

`"2":{  
            "r":[  
               {  
                  "g":12,
                  "i":1.5
               },
               {  
                  "g":12,
                  "v":1,
                  "i":0.5
               },
               {  
                  "g":12,
                  "v":1,
                  "i":2
               }
            ]
         }`

I think it's for making two pushes on relay, but how does it work?

**Comment by lfiocco** [comment]
Something does not work with the SV JSON you have on the template page. HAA keeps going into setup mode. I loaded a simple switch, it find. Garage Door, no..

**Comment by noobydp** [comment]
> Something does not work with the SV JSON you have on the template page. HAA keeps going into setup mode. I loaded a simple switch, it works, it's not the device.


The sample json worked for me.

**Comment by RavenSystem** [comment]
@lfiocco fixed.

**Comment by RavenSystem** [comment]
@macjl 
v=0 i=1.5 relay is off and will on after 1.5 secs.

**Comment by lfiocco** [comment]
Thank you working great
