### ISSUE TITLE
any way to save state ? am in a place where current cut a lot

### ISSUE THREAD

**Issue by mahdy89** [RavenSystem/esp-homekit-devices#65]
any way to save state ? am in a place where current cut a lot

**Comment by RavenSystem** [comment]
Saved states is on the way. That is the next feature to be released in a mayor version update (v0.5.0).

**Comment by RavenSystem** [comment]
Added to TODO list: https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List
