### ISSUE TITLE
Shelly1 PIR motion sensor

### ISSUE THREAD

**Issue by Kienz** [RavenSystem/esp-homekit-devices#651]
I want to use a Shelly 1 to make a standard PIR motion sensor smart. There should be two devices in HomeKit - motion sensor and toggle switch.
eg. https://gist.github.com/xbmcnut/6d239de9523246d7a831ca55be6564c2

The motion sensor and the toggle switch should be seperated - the light is turned on by an HomeKit automation.

Is this possible? If yes, what would the JSON look like?

**Comment by mafyata** [comment]
Try this:
 {"c":{"l":13,"i":1,"b":[{"g":0,"t":5}]},"a":[{"t":1,"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"t":12,"i":10,"f1":[{"g":14}]}]}

Just check which gpio will you use. Here is for gpio14

**Comment by Kienz** [comment]
@mafyata How can I use gpio14 on Shelly1. I'm new to this and I don't know how to use the gpio's. How do I wire the PIR motion sensor. Equal to the picture form https://gist.github.com/xbmcnut/6d239de9523246d7a831ca55be6564c2?

**Comment by mafyata** [comment]
I don’t know shelly’s gpio. I don’t use shelly.

**Comment by mafyata** [comment]
I use sonoff devices

**Comment by Kienz** [comment]
@RavenSystem Is the following json for Shelly 1 correct?
Toggle Switch on I/O and Motion Sensor on SW.
![image](https://user-images.githubusercontent.com/954545/70504876-f2891a00-1b26-11ea-9b14-a5e53861c7fc.png)


```json
{"a":[{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"t":1,"b":[],"s":0},{"t":12,"i":10,"f1":[{"g":5}],"s":0}]}
```

**Comment by RavenSystem** [comment]
Shelly devices must disable pull-up resistor for digital inputs ("p":0):

```json
{"a":[{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]}},{"t":12,"i":10,"f1":[{"g":5,"p":0}]}]}
```

**Comment by Kienz** [comment]
With this config I don’t get 240V on I/O if toggle is on. What is wrong?
