### ISSUE TITLE
HAA: 2-Outlet Outdoor Wi-Fi Remote Control (Prime Wire & Cable Inc. - RCWFI0)

### ISSUE THREAD

**Issue by KevinMiddleton** [RavenSystem/esp-homekit-devices#653]
It took a bit of trial and error but here is a HAA template for the 2-Outlet Outdoor Wi-Fi Remote Control (Prime Wire & Cable Inc. - RCWFI0) :: found these at Costco in Canada.

     {"c":{"l":5,"b":[{"g":13,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":13}]}]}

If you prefer the blue LED to flash, change the "l": to 4 instead of 5

The physical button works but I only see the red LED flash briefly when issuing on/off commands - I know that some people may want the LED to remain on when powered but not sure how to address that issue.  Suggestions are welcome.

**Comment by RavenSystem** [comment]
Great job! A LED a digital output, like a relay, but normally is inverted.
```
{"c":{"l":4,"b":[{"g":13,"t":5}]},"a":[{"0":{"r":[{"g":12},{"g":5,"v":1}]},"1":{"r":[{"g":12,"v":1},{"g":5}]},"b":[{"g":13}]}]}
```
