### ISSUE TITLE
JSON help - Garage Door

### ISSUE THREAD

**Issue by yusufd1** [RavenSystem/esp-homekit-devices#655]
Hi please can someone help me with a json. It will be on a Wemos D1 Mini and requires the following:
- Relay on GPIO 12 that inches for 0.6 seconds to open or close garage door
- Close Sensor on GPIO 13 
- Open Sensor on GPIO 14
- if door is opening/closing and home app button pressed then GPIO 12 must fire twice so door stops and changes direction [I think this is called stop step]
- the normal time for door to open or close is  15 seconds 

Thanks for the help.

**Comment by RavenSystem** [comment]
Try this, but I don't know if your sensors are NO (normal open) or NC (normal close):

`{"a":[{"t":40,"d":15,"f3":[{"g":13,"t":0}],"f4":[{"g":13},"f2":[{"g":14,"t":0}],"f5":[{"g":14}],"0":{"r":[{"g":12,"v":1,"i":0.6}]},"1":{"a":0},"2":{"r":[{"g":12,"i":1.2},{"g":12,"v":1,"i":0.6},{"g":12,"v":1,"i":1.8}]},"3":{"a":2}}]}`

**Comment by yusufd1** [comment]
I will try it. Is it correct I saying that no and no will just change the “t” in the GPIO 13 and 14 to either 0 or 1. If that’s the case then I can test it and use trial and error with the json?

**Comment by yusufd1** [comment]
I will try it. Is it correct I saying that no and nc will just change the “t” in the GPIO 13 and 14 to either 0 or 1. If that’s the case then I can test it and use trial and error with the json?

**Comment by yusufd1** [comment]
@RavenSystem please help. Having problems with the json. The garage door worked perfectly on the below pictured RC settings. What will be the json for these exact settings?
![533CE5CC-477B-40DC-B109-41DA3080A5AB](https://user-images.githubusercontent.com/7950910/70740517-fe8cfb80-1d21-11ea-831f-cd3ba2df72b7.png)
![E028593A-92A5-42CA-966F-58321C769E7F](https://user-images.githubusercontent.com/7950910/70740518-fe8cfb80-1d21-11ea-8c83-594dfbb89d13.png)

**Comment by yusufd1** [comment]
As you can see reverse switch is on and while open sensor is off in these settings I used to have it on 2 when I had the open sensor connected which I do wish to have in HAA.
