### ISSUE TITLE
HAA - HomeKit App reject QR Code as it is already taken

### ISSUE THREAD

**Issue by Shimakuchi** [RavenSystem/esp-homekit-devices#658]
I flashed a shelly 2.5 with the older RavenCore Firmware (need the capability of control Roller Shutter). As described [here](https://github.com/RavenSystem/esp-homekit-devices/issues/657#issuecomment-565039540) the code gets rejected.

Now I flashed a shelly 1 with the newest HAA, the same result.

![IMG_9660](https://user-images.githubusercontent.com/2376419/70722321-5bbf8780-1cf7-11ea-8b1d-28f820272c86.PNG)

_Originally posted by @Shimakuchi in https://github.com/RavenSystem/esp-homekit-devices/issues/657#issuecomment-565039540_

**Comment by PandaBoba** [comment]
I have the same problem with newest HAA

**Comment by mafyata** [comment]
Don’t scan , type the code manually 02182017

**Comment by PandaBoba** [comment]
Then in my case it doesn't search for any accessory

**Comment by mafyata** [comment]
Did you click on this button ?
![DDB45228-79D8-4C2E-ADC0-BFD5785C9C2E](https://user-images.githubusercontent.com/48009267/70737235-b9190000-1d1a-11ea-94f0-643643b8757d.jpeg)

**Comment by PandaBoba** [comment]
![IMG_3243](https://user-images.githubusercontent.com/58117854/70737524-05604200-1d13-11ea-80e2-47379fbad95e.PNG)
Yes

**Comment by PandaBoba** [comment]
Ok for me it was wrong json. Now everything working fine

**Comment by Shimakuchi** [comment]
Hi @mafyata. Yes I did try to enter the code manually

@PandaBoba In case of my shelly 1 (HAA) the faulty json could be the problem. I thought I could add it to HomeKit and then configure the json.

In case of the shelly 2.5 (RavenCore) there is no json. The device can be configured after adding it to HomeKit via the Eve app

**Comment by RavenSystem** [comment]
RavenCore has not a QR-Code. You must use simple code `021-82-017`.

HAA has QR-Code, but you must setup JSON first.

**Comment by pilot1981** [comment]
I notice some different behaviour using QR code and normal code: sometime when QR code don't work I have to use normal code...
