### ISSUE TITLE
Switch and Temperature Reverse SW

### ISSUE THREAD

**Issue by skv6** [RavenSystem/esp-homekit-devices#659]
Could You tel how in «Switch and Temperature with DS18B20 sensor at GPIO 14» 
JSON
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":22,"g":14,"n":3},{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]}]}

I can make Reverse SW?

**Comment by RavenSystem** [comment]
`{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":22,"g":14,"n":3},{"0":{"r":[{"g":12,"v":1}]},"1":{"r":[{"g":12}]},"b":[{"g":0}]}]}`
