### ISSUE TITLE
Setup mode problem 0.8.3

### ISSUE THREAD

**Issue by skv6** [RavenSystem/esp-homekit-devices#665]
Have a problem for entering to setup mode in 0.8.3. Device entering to setup mode (toggle quickly any action switch/button 8 times or hold more that 10 seconds, Emergency Setup Mode doesnt work). I can see WiFi network HAA but it doesnt work. if chang to 0.7.9 - its work. In 0.8.3 I can use setup mode only fist time after firmware after that just see WiFi HAA but not use. 

JSON
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]}]}

**Comment by mafyata** [comment]
In 0.8.3 entering setup mode is changed. You must open browser and type ip address of the device , not to search for wifi has-xxx
