### ISSUE TITLE
Freeze sonoff 4ch

### ISSUE THREAD

**Issue by simoneorsi** [RavenSystem/esp-homekit-devices#667]
I upgrade my son off 4ch pro to the last one version.
If I switch fast more and more time the 4 switch the system freeze.
I tried to take a log file but my Mac terminal windows leave blank without nothing message.
thanks

**Comment by skv6** [comment]
Sonoff mini too. Work some seconds after that freeze. 0.8.6

**Comment by hillaliy** [comment]
Sonoff T1 US 2 Gang freeze too. 0.8.6

**Comment by RavenSystem** [comment]
JSON string and logs, please.

**Comment by hillaliy** [comment]
How i get logs?
JSON: {"c": {"l": 13,"b": [{"g": 0,"t": 5}],"i": 1},"a": [{"0": {"r": [{"g": 12}]},"1": {"r": [{"g": 12,"v": 1}]},"b": [{"g": 0}],"s": 0},{"0": {"r": [{"g": 5}]},"1": {"r": [{"g": 5,"v": 1}]},"b": [{"g": 9}],"s": 0}]}

**Comment by RavenSystem** [comment]
I tested your JSON with a protoboard and there is not any freeze.

You can see how capture logs here in the Wiki:
https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-Instructions#capture-logs

**Comment by simoneorsi** [comment]
I try to do how explain in to the instruction to capture log but the window dindn’t send any info. To calture log I need to use the same rs232 usb converter that I use to program the sonoff? Only rx and tx or another wire. Sorry for my incompetence!

**Comment by RavenSystem** [comment]
Sorry, yes. You must connect your device only to your rs232 (rx, yx, vcc and ground). Don’t connect it to 230VAC.

**Comment by hillaliy** [comment]
Sorry it dosn't freeze it get to setup mode. I add Setup Mode Time to Json hope it will help.

**Comment by RavenSystem** [comment]
If device enters in setup, is because you toggle quickly switches up to 8 times in a row. You can use setup mode time key or new "z" key. Check this: https://github.com/RavenSystem/esp-homekit-devices/releases
