### ISSUE TITLE
Auto OTA on Boot?

### ISSUE THREAD

**Issue by noobydp** [RavenSystem/esp-homekit-devices#669]
Hi Jose, I was wondering if you’d consider letting the device auto-update via OTA when its rebooted, if the Auto OTA Update option was selected when first setup?

I’ve setup a few devices and I want to keep them up to date, but they’re in inconvenient places so pressing the setup button when it powers on will be difficult.

Thanks

**Comment by St0nehead** [comment]
Agree!

**Comment by sancheztineo** [comment]
I add a dummy switch with JSon. When I want update, with app home, I press 8 times the dummy switch and the devices updates the firmware.

**Comment by RavenSystem** [comment]
Full auto updates is not a good idea, because boot will be very slow, and there is a risk that device enters into an infinite loop.

@sancheztineo that is a very good idea. And you can put those dummy switches at other room.

**Comment by noobydp** [comment]
Thanks!
The dummy switch is a great idea.

**Comment by sancheztineo** [comment]
I’ve put a room with all Dummy Switch for OTA Updates. 
![4076C7F9-254D-46BD-9C5C-671E92F23B7F](https://user-images.githubusercontent.com/54850966/71070565-550f9500-217b-11ea-842e-6729d816d010.png)

**Comment by mafyata** [comment]
I have one idea. Can you make option in HAA , to enable setup button instead of dummy switch? When I press setup button to enter setup mode. 1 press instead of 8 press.

**Comment by RavenSystem** [comment]
This is better: https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_0.8.7
