### ISSUE TITLE
Change Occupancy Sensor NC to NO

### ISSUE THREAD

**Issue by Kienz** [RavenSystem/esp-homekit-devices#673]
How can I change normal close (NC) to normal open (NO) of an occupancy sensor.
My actual JSON with NC:
{"a":[{"t":4,"i":4,"0":{"r":[{"g":4,"v":1,"i":1.5}]}},{"t":6,"i":10,"f1":[{"g":5,"p":0}]}]}

**Comment by RavenSystem** [comment]
Add "i":1 after "p":0 to invert gpio 5 input.
