### ISSUE TITLE
Setup new feature - system actions

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#675]
Hi , how to setup this new feature - system actions?

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#system-actions

**Comment by homkittoby** [comment]
Idea!
Is the device in setup mode and nothing happens for 2 minutes. The device boots again in normal mode.
So the device does not get caught in setup mode if it is started accidentally.

**Comment by mafyata** [comment]
{"c":{"n":"Hol-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"1":{"s": [{ "a": 1}]},"r":5,"g":12,"v":13,"fr":5,"fg":5,"fv":5}]}
What is wrong?

**Comment by RavenSystem** [comment]
What is the issue?

**Comment by mafyata** [comment]
The led strip is off. Press 1 time turn the light on and the second press enter setup mode instead of turning off the light.

**Comment by RavenSystem** [comment]
Well, order to enter setup mode is coming with your first press: "1":{"s": [{ "a": 1}]}, but there is a delay of 3 seconds until device reboots.

**Comment by mafyata** [comment]
But it is with mine main button, not second for setup mode. I think that with this function I will receive second button for this device for entering setup mode.

**Comment by RavenSystem** [comment]
Your setup has one accessory, and you set "1" to enter setup mode. Action "1" is executed when light is turned on.

**Comment by mafyata** [comment]
Hmmm. Can you help me?
This is my json: 
{"c":{"n":"Hol-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13,"fr":5,"fg":5,"fv":5}]}
Can you tell me the correct json with second button for entering setup mode?

**Comment by homkittoby** [comment]
{"c":{"n":"Hol-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13,"fr":5,"fg":5,"fv":5},{"0":{"r":[]},"1":{"r":[],"s":[{"a":1}]},"t":1,"b":[],"s":0}]}

???

**Comment by homkittoby** [comment]
@RavenSystem 

**Thank you** 

(Changelog: General: Now device in setup mode will reboot in normal mode automatically after 90 seconds is setup web page is not loaded and Auto OTA Updates is disabled.)

**Comment by mafyata** [comment]
It works. Thanks.

**Comment by mafyata** [comment]
why it is not working on my other device? i copy the setup you added to my 1st device.
{"c":{"n":"Kuhnq-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13},{"0":{"r":[]},"1":{"r":[],"s":[{"a":1}]},"t":1,"b":[],"s":0}]}

**Comment by RavenSystem** [comment]
Try reset HomeKit ID.

**Comment by mafyata** [comment]
I forgot to update from 0.8.2 Not it is ok.
