### ISSUE TITLE
Rocker switch as stateless button single press

### ISSUE THREAD

**Issue by danielhelmstedt** [RavenSystem/esp-homekit-devices#679]
Hi, is it possible to set up a standard rocker switch/lightswitch to act as a single button press when toggled?
 I tried setting 2 single press state inputs - one default and one falling edge, both GPIO12 for my sonoff mini, but no luck. Do I need to invert one or something?

**Comment by danielhelmstedt** [comment]
Just realised GPIO 12 is the relay and I want GPIO 4, duh 🙄

**Comment by rasod** [comment]
@danielhelmstedt i'm trying something similar what configuration and wiring did you end up using?

**Comment by danielhelmstedt** [comment]
Just wire the switch up normally to a GPIO, and configure 2 single press inputs - one with default activation and the other with falling edge. Then you’ll probably want to configure the single press button in HomeKit to use a shortcut with an If statement (I.e. if light is ON, turn OFF, else turn ON)

**Comment by chenfengfeng** [comment]
@danielhelmstedt Can you share your JSON configuration?
