### ISSUE TITLE
change the GPIO output for normal ESP01 Relaysmodul

### ISSUE THREAD

**Issue by heizie** [RavenSystem/esp-homekit-devices#68]
Hi, I've already tried the sonoff_ravencore and otaboot.bin for my ESP01 Relaysmodul. None of them can change the state of **GPIO 0**  (i can see the response from homekit but relay didn't works). Any chances to give a update or give me some advise to change the C code?  thx

**Comment by RavenSystem** [comment]
In ESP01 (Device type 10) GPIO 0 is used only as button, to allow stateless switch button control and factory reset. Relay must be connected to GPIO 2.

**Comment by heizie** [comment]
But it didn't has a button. it looks like this
![s-l1600](https://user-images.githubusercontent.com/44361882/47865854-9d47e880-ddfd-11e8-9ea5-01190d6621bf.jpg)

I've search it's manual:
![12](https://user-images.githubusercontent.com/44361882/47866035-00397f80-ddfe-11e8-91dc-9223b5cce685.png)

**Comment by RavenSystem** [comment]
Sorry, but in this firmware, GPIO0 is used to connect a button, and GPIO2 is used to connect a relay. If you want to use it in other way, you must build your custom firmware adapted to your needs.
