### ISSUE TITLE
Problem to upgrade to RC 1.3 using OTA

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#681]
Hi,
I have sonoff with RAVENCORE 1.1, but it I try to upgrade to 1.3 using Eve App nothing happen...
What is wrong?

Regards

**Comment by pilot1981** [comment]
I tried again: sonoff died! No AP MODE...
Suggestions?

**Comment by mafyata** [comment]
Try to flash again.

**Comment by pilot1981** [comment]
Very confortable...

**Comment by GPL71** [comment]
Hey guys... if I understand well, RavenCore 1.3 is only an automatic procedure for upgrading to HAA.
Then it’s necessary have a valid json to complete operation.

@RavenSystem Josè help is necessary

**Comment by mafyata** [comment]
No , you are wrong. 1.3 is security update.

**Comment by RavenSystem** [comment]
@GPL71 you are right. 

@mafyata you are wrong. I said that RaveCore will not be updated anymore. And now HAA supports all RC features. Please, read release notes and Wiki information about that.

**Comment by pilot1981** [comment]
ok, now I have some problem with JSON of garage door, I try using discord...but with a shelly 1 I receive error message: this device is already added to homekit...
how I can solve it?

I already removed it from my home app...

**Comment by GPL71** [comment]
@pilot1981 Did you flag HomeKit Reset ID?

**Comment by pilot1981** [comment]
no, I have to do it? I already removed device from my home app..

**Comment by GPL71** [comment]
yes ... try it too ..

**Comment by pilot1981** [comment]
I tried many times to reset HomeKit, but this don’t solve my problem using QR CODE.

Only solution is to use normal code...
