### ISSUE TITLE
1 Accessory with 2 buttons

### ISSUE THREAD

**Issue by egorist** [RavenSystem/esp-homekit-devices#685]
Sorry. Is it possible to make with HAA one accessory with 2 buttons like original iOS 13 way. 
This is code for sonoff T1 EU2, but it makes 2 accessories with 1 button each:
{"c":{"l":13,"i":1,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]}]}
How I should change it?

**Comment by RavenSystem** [comment]
No, but you can group them in Home App.

**Comment by egorist** [comment]
Making groups means that one button changes state of several devices. It’s not the same. I just want to use more buttons in “favorites” from lock screen. 
Thanks for your answer.
