### ISSUE TITLE
Upgrade from RavenCore to HAA

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#686]
**IMPORTANT**
This guide allows upgrade from RavenCore firmware to the new HAA.
Whatever RavenCore firmware is on the device, the update will install version 1.3.0 and then the upgrade to HAA.
Upgrade to HAA is strongly recommended because it solves the ESP8266 HomeKit library bug.
Furthermore, now all the functions available in RavenCore have been imported into HAA and more customizable.

To upgrade follow the steps:

1. Create or copy from RavenSystem examples page the suitable JSON configuration for wanted accessory. 
2. Open EVE and enter SETUP mode
3. Take note of device IP address you'll update
4. Set FIRMWARE UPDATE to "YES", set REBOOT to "YES" and close EVE.

![no_haa_toggle](https://user-images.githubusercontent.com/34108470/71382783-b56a6080-25d9-11ea-925a-4e768473d8b6.jpeg)

5. Wait approximately 5-7 minutes. That time is necessary for HAA download and installation
6. Open browser and enter the device IP address 
7. When configuration web page opens, enter following information:

- JSON configuration
- Reset Homekit ID
- Save

8. Web page closes and configuration begins
9. Open HOME app and remove the old device
10. Add new device
11. Type the code or read QR Code
12. Wait for 30 to 60 seconds and device will added to HomeKit

NOTE: If upgraded device include only one accessory (for example Shelly 1 as 1 accessory), perform Reset Homekit ID in point 7 or points 9 to 12 are not necessary.

**Comment by Dirk23** [comment]
Thank you very much for this manual. Unfortunately I cannot upgrade my Sonoff Dual R2 to HAA firmware.  I have followed every step up to point 5 and I am not getting anywhere. There is no website under the IP address of the device.  I also have a point called Firmware HAA in my settings (in the Eve App) which is mentioned in the manual. Does this switch possibly have to be set as well? 
![IMG_0F60D53AF45C-1](https://user-images.githubusercontent.com/4200682/71437277-3a946900-26f1-11ea-9731-ad231ed0eb0e.jpeg)

**Comment by GPL71** [comment]
@Dirk23 toggle on REBOOT too and continue closing HOME app.

**Comment by Dirk23** [comment]
> @Dirk23 toggle on REBOOT too and continue closing HOME app.

I found the Problem, it seems that my firewall blocked Something the HAA needs to load.

**Comment by GPL71** [comment]
> > @Dirk23 toggle on REBOOT too and continue closing HOME app.
> 
> I found the Problem, it seems that my firewall blocked Something the HAA needs to load.

can you disable it?

**Comment by Dirk23** [comment]
> > > @Dirk23 toggle on REBOOT too and continue closing HOME app.
> > 
> > 
> > I found the Problem, it seems that my firewall blocked Something the HAA needs to load.
> 
> can you disable it?

Sure, i disabled the Firewall and everything works fine now.

**Comment by Quoshak** [comment]
> 
>     2. Open EVE and enter SETUP mode
> 

How do you enter setup mode in EVE app? I cannot find anything that would bring me features that I can see on your screenshot.

**Comment by frazer81** [comment]
> 
> 
> > ```
> > 2. Open EVE and enter SETUP mode
> > ```
> 
> How do you enter setup mode in EVE app? I cannot find anything that would bring me features that I can see on your screenshot.

Hi - i'm also looking for the same interface on the EVE app - is anyone able to provide guidance on how to access the setup page within? It something we need to enable within the JSON to access perhaps? Appreciate the assistance!!

**Comment by asbesto01** [comment]
> **IMPORTANT**
> This guide allows upgrade from RavenCore firmware to the new HAA.
> Whatever RavenCore firmware is on the device, the update will install version 1.3.0 and then the upgrade to HAA.
> Upgrade to HAA is strongly recommended because it solves the ESP8266 HomeKit library bug.
> Furthermore, now all the functions available in RavenCore have been imported into HAA and more customizable.
> 
> To upgrade follow the steps:
> 
> 1. Create or copy from RavenSystem examples page the suitable JSON configuration for wanted accessory.
> 2. Open EVE and enter SETUP mode
> 3. Take note of device IP address you'll update
> 4. Set FIRMWARE UPDATE to "YES", set REBOOT to "YES" and close EVE.
> 
> ![no_haa_toggle](https://user-images.githubusercontent.com/34108470/71382783-b56a6080-25d9-11ea-925a-4e768473d8b6.jpeg)
> 
> 1. Wait approximately 5-7 minutes. That time is necessary for HAA download and installation
> 2. Open browser and enter the device IP address
> 3. When configuration web page opens, enter following information:
> 
> * JSON configuration
> * Reset Homekit ID
> * Save
> 
> 1. Web page closes and configuration begins
> 2. Open HOME app and remove the old device
> 3. Add new device
> 4. Type the code or read QR Code
> 5. Wait for 30 to 60 seconds and device will added to HomeKit
> 
> NOTE: If upgraded device include only one accessory (for example Shelly 1 as 1 accessory), perform Reset Homekit ID in point 7 or points 9 to 12 are not necessary.

after point 4, device reboots but does not upgrade the ravencore to 1.3, nor download the haa.
I am now on ravencore 1.1.1

any help?

**Comment by pilot1981** [comment]
There is a problem with GITHUB ORA procedure...
