### ISSUE TITLE
Template Help: Curtain Motor

### ISSUE THREAD

**Issue by tonysprenk** [RavenSystem/esp-homekit-devices#688]
This is the device: https://s.click.aliexpress.com/e/n3g3Q1For
More info [here](https://github.com/arendst/Tasmota/wiki/Zemismart-Curtain-Motor).

Any help would be greatly appreciated!

**Comment by tonysprenk** [comment]
https://tasmota.github.io/docs/#/TuyaMCU?id=curtain-motors this might help too!

**Comment by RavenSystem** [comment]
Sorry, it is not compatible with HAA because esp chip does not manage curtain directly. It uses serial commands to communicate with the chip that manages it.

**Comment by tonysprenk** [comment]
Thats really bad news... Any plans on adding this feature into HAA? Tasmota seems to have it implemented, but I love HAA as I don't need a bridge, and it's very stable for my other accessories... I think more info on how Tasmota achieves this can be found [here](https://tasmota.github.io/docs/#/TuyaMCU).

**Comment by RavenSystem** [comment]
Maybe in the future, but not soon.

**Comment by bj-tracer** [comment]
You may use other curtain drives with the direct motor control and any dual relay with esp8266 controller.
If you want to use Zemismart motor than you need a tiny controller that may convert hi/low signals from esp8266 with HAA to serial comands.

**Comment by bj-tracer** [comment]
or... you can remove Zemismart logic and inser any dual relay module with esp8266 ;)

**Comment by tonysprenk** [comment]
Yes I’m researching this. It has a rj45 connection for dry connecting a low voltage relay. I guess something like this (https://s.click.aliexpress.com/e/FzW1z1iXv) should work?

**Comment by tonysprenk** [comment]
![B8D83745-DA45-4745-972E-8AD3CA1A7AFB](https://user-images.githubusercontent.com/38426377/71475217-93422f80-27df-11ea-8dc1-d58ce6f61710.jpeg)

**Comment by tonysprenk** [comment]
I’d like to keep the internal components intact as I use the RF remote as wel as the “manual open and close” functionality.

**Comment by RavenSystem** [comment]
Using externals controls (Like RF) is not good, because HomeKit loses position sync.

Other way could be to build a device that works over RF remote, connecting relays to RF buttons, to open, close and stop. You lose RF remote, but as I say, using controls outside HomeKit is not a good idea.

**Comment by tonysprenk** [comment]
Hmmm okay, maybe I should just resort to using the homeassistant Tuya component as it has the ability to get the state, unfortunately I’ll be connected to a Chinese server. Thanks for all your suggestions!

**Comment by bj-tracer** [comment]
You can use RF that connected to esp8266 board and working like an external switches.
Then Zemismart board will to drive the motor only.

So you need to make the stick that will be connect to the Zemismart drive trough RJ45 with 1/2 logic (for example).
Unfortunately there is no power in this RJ45 connection. But you can use for it USB-port ;)
