### ISSUE TITLE
Error in initial Setup, can't reflash

### ISSUE THREAD

**Issue by brymonster** [RavenSystem/esp-homekit-devices#690]
Hello all. 
Successfully flash another Magic Home RGBW device identical to the [previous.](https://github.com/RavenSystem/esp-homekit-devices/issues/654#issuecomment-564269037) Unfortunately, when connecting to the initial Setup page I was only shown the Network List. No OTA repository or OTA binary file fields.
I selected my network, entered password and joined. Now the device is on the network, but I have no way to enter Setup Mode again. 
The install guide mentions "If installation fails, you must start all process again from step 2."
I have tried reflashing but keep getting the `Connecting........_____....._____` 
Could something be preventing refreshing?

Previously I was able to get the device into flash mode by plugging in to FDTI while jumping the io0 to ⏚ for 3-5 seconds. Now im trying lots of variations, nothing is working so far. 

Ideas?

**Comment by brymonster** [comment]
have been able to test on another computer. Same result:
```
$ esptool.py -p /dev/tty.usbserial-A50285BI erase_flash
esptool.py v2.8
Serial port /dev/tty.usbserial-A50285BI
Connecting........_____....._____.....
```

**Comment by GPL71** [comment]
Try swap TX and RX on FTDI

**Comment by brymonster** [comment]
No joy 
Would something on a bad flash be preventing a device entering Flashing Mode?
How long to you hold the io0 to ⏚?

**Comment by brymonster** [comment]
Sorry to bother friends. My FTDI had a loose solder on the ⏚.
Solved!
