### ISSUE TITLE
Flashing with esptool throws an Error

### ISSUE THREAD

**Issue by Dirk23** [RavenSystem/esp-homekit-devices#692]
Hi,

i tried to flash a Sonoff Dual R2 with HAA. In your Wiki is written:

`esptool.py -p /dev/<your_ESPPort> --baud 115200 write_flash -fs 1MB -fmdout -ff 40m \
0x0 rboot.bin 0x1000 blank_config.bin 0x2000 otaboot.bin` but the option fmdout is unkown:

<img width="1126" alt="Bildschirmfoto 2019-12-25 um 18 43 37" src="https://user-images.githubusercontent.com/4200682/71449107-a8b74b00-2746-11ea-95b9-75acd3ee50f3.png">

I changed it to `--flash_mode dout` but i don't know if this correct. Anyways, after flashing the Sonoff, i could setup wifi, but i can't enter Setup Mode. I press the OnBoard Button 8 times, and i tried it with the 2 external Switch Pins (button0 and button1) but there is no Webpage reachable after pressing these Buttons 8 times.

What am i missing?

Regards

Dirk

**Comment by GPL71** [comment]
Simply enlarge (horizontal) the terminal window ... you have typed command in 2 rows.

**Comment by Dirk23** [comment]
Nope, that is not the problem, there was no linebreak or anything:
<img width="1678" alt="Bildschirmfoto 2019-12-25 um 22 31 13" src="https://user-images.githubusercontent.com/4200682/71450678-6f8ed300-2766-11ea-9185-984b9568d6b8.png">
I just realized that `fmdout` is wrong and that it needs a blank space between -fm and dout like `-fm dout`
I think you need to correct your wiki.
