### ISSUE TITLE
Eve App Setup

### ISSUE THREAD

**Issue by quartist** [RavenSystem/esp-homekit-devices#694]
Hi,

after upgrade from RC to HAA in Eve App im lost option "setup". How to restore setup for accessories in eve app?

**Comment by mafyata** [comment]
With haa you can’t setup in eve.

**Comment by quartist** [comment]
hmm...
so how to change "filter" for sonoff T1. In my case Im using filter value 20 in RC.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/General-Configuration#digital-input-filter

**Comment by quartist** [comment]
Thanks!
