### ISSUE TITLE
Possible error in HAA 0.9.2 thermometer and DS18B20

### ISSUE THREAD

**Issue by viccur** [RavenSystem/esp-homekit-devices#695]
Hello.
I have flashed one esp8266 with HAA 0.9.2.
This is the JSON:
{"c":{"o":0,"m":300,"u":1},"a":[{"5":{"r":[]},"t":22,"b":[],"n":3,"g":0},{"0":{"r":[{"g":5,"v":0}]},"1":{"r":[{"g":5,"v":1}]},"t":1,"b":[],"s":5}]}
It is conformed for a thermometer with DS18B20 and a switch for reset it.
Sometimes, it has good read (about 9ºC) but other times it value is 85ºC.
The hardware is working along 2 years with Espeasy and it works well.
Is there some wrong in the JSON?
Thank you for you incredible work.

**Comment by RavenSystem** [comment]
JSON is right. DS18B20 driver is included in esp-open-rtos. I suggest you open an issue in its repo.
