### ISSUE TITLE
Magic Home external toggle? 

### ISSUE THREAD

**Issue by brymonster** [RavenSystem/esp-homekit-devices#696]
Hi all. Wondering if it’s possible to use one of the GPIOs to have an external toggle on a Magic Home RGBW.

**Comment by mafyata** [comment]
Yes, try IO0

**Comment by brymonster** [comment]
Thanks @mafyata!
How exactly do you have that set up? 
12v into io0 when the switch is on?

**Comment by mafyata** [comment]
IO0 and GRN connected for a second. Like push button.

**Comment by brymonster** [comment]
Ok I will have to try that when I gets home. 

Momentary grounding io0 will turn on.. and off? 
Any changes to the JSON needed?

**Comment by mafyata** [comment]
You must set external button for IO0 in your json.

**Comment by maccoylton** [comment]
>You must set external button for IO0 in your json.

@brymonster if you have the model WIU the the IR remote can you not use that? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mafyata** [comment]
I have 2 rgb devices with ir and after flashing with haa the ir is not working. Haa don’t support ir control.

**Comment by brymonster** [comment]
Thanks for the help so far @mafyata. 
Here is the JSON I’m using currently: 
```
{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":12,"g":5,"v":13,"w":15,"b":[{"g":0}]}]}
```
I have been messing with the [JSON Configurator](https://glumb.github.io/haa-configurator/) But don’t have a full grasp of it. 
I think the t: value needs to be adjusted. 
Can you share the JSON your using?

**Comment by mafyata** [comment]
I don’t use external button. I have a switch for setup mode.
1- {"c":{"n":"Kuhnq-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13},{"0":{"r":[]},"1":{"r":[],"s":[{"a":1}]},"t":1,"b":[],"s":0}]}

2- {"c":{"n":"Hol-Led","b":[{"g":0,"t":0}]},"a":[{"t":30,"s":5,"r":5,"g":12,"v":13,"fr":5,"fg":5,"fv":5},{"0":{"r":[]},"1":{"r":[],"s":[{"a":1}]},"t":1,"b":[],"s":0}]}

**Comment by maccoylton** [comment]
I have firmware here that has IR support :- https://github.com/maccoylton/esp-homekit-rgbw-strip

**Comment by brymonster** [comment]
I will check it out. Thanks @maccoylton. 
My current Magic Home devices don’t have IR. That why I was looking to add a connected switch. 
But maybe my future ones will. HAA also has IR on the todo list!

**Comment by brymonster** [comment]
Momentary grounding io0 works with my current JSON. Thanks!
