### ISSUE TITLE
RavenCore: Sonoff Basic as Lock mechanism with contact sensor

### ISSUE THREAD

**Issue by teymur1988** [RavenSystem/esp-homekit-devices#698]
Hi all!
Could you please advise, I trying to use a sonoff basic as a lock mechanism to turn on/off an electrical lock. Now in the Eve app I enabled "has contact sensor 1" and in homekit I see 2 accessories: the lock and the contact sensor. As the Wiki suggests the contact sensor has to be connected to GPIO 4 to change it's status. I've looked up the board layout of sonoff basic and it looks like I have to do some delicate soldering on pin 16 of the esp8285. So my question is, for that to work do I have to connect GPIO4 (pin16 of esp8285) to ground via a 10kOhm resistor? Could you please advise @RavenSystem

**Comment by RavenSystem** [comment]
Better update to HAA and you will can use any other GPIO.
