### ISSUE TITLE
Sonoff Basic Wall Switch Problem

### ISSUE THREAD

**Issue by osvaldoasn** [RavenSystem/esp-homekit-devices#7]
Hi,

I'm testing a wall switch on GPIO14, but when i connect anything on GPIO14, without connecting GND Sonoff turn on and off continuosly, and when i connect GPIO14 to GND and try to turn switch on or off it goes on and off, same on HomeApp and Sonoff button.
When GPIO14 is disconnected it works ok but without the wall switch.

Thanks.

**Comment by RavenSystem** [comment]
I don't understand you well. What kind of wall-switch are you using? You must use a normal on-off switch, not a button switch, and you must connect it to GPIO14 and GND, but not only to GPIO14 (I don't know how this is possible). I have tested just now, and works as expected. Each time the wall-switch is operated, Sonoff changes its status. Can you provide more detailed info, please?

**Comment by osvaldoasn** [comment]
Hi, 
I'm sorry the problem was the wire that i was using.
Thank you.

**Comment by osvaldoasn** [comment]
Hi,
I'm trying to use a ON/OFF wall-switch with GPIO14 and GND, now it works to turn ON and OFF, but when the wall-switch is in OFF position I can't turn ON with HomeApp, it turns ON and OFF (same time) and remains OFF. When wall-switch is in ON position HomeApp work as expected.

Thanks.

**Comment by RavenSystem** [comment]
Hello, 
Are you using the last version (binary or built by yourself)?
Thanks.

**Comment by osvaldoasn** [comment]
Hi,
I builded it by myself.
Thanks.

**Comment by RavenSystem** [comment]
I'm sorry, but I'm unable to reproduce your issue. Please, can you compile it with `export HOMEKIT_DEBUG=1` and then send logs when your issue occurs? 

Many thanks.

**Comment by osvaldoasn** [comment]
Hi,
HOMEK IT_DEBUG=1 generates a file or I must to save monitor output?
I'll send videos reproducing bug and I've tried on two Sonoffs.
Thanks.

**Comment by RavenSystem** [comment]
It is better that you save monitor output.

Thanks.

**Comment by osvaldoasn** [comment]
Hi,

I've updated last comment with output.
With 3.3v it works better, but with 220v, even induction changes switch status.

Thanks.

**Comment by RavenSystem** [comment]
Please, can you provide some photos about how you wired the circuit?

Many thanks.

**Comment by osvaldoasn** [comment]
![img_1608](https://user-images.githubusercontent.com/8234974/37298868-5c090f76-2600-11e8-9fb6-73299efe55ae.png)
![img_1607](https://user-images.githubusercontent.com/8234974/37298869-5c241208-2600-11e8-94de-9e5b4d910fd1.png)
![img_1606](https://user-images.githubusercontent.com/8234974/37298870-5c466ede-2600-11e8-92c6-9a5721c8f4c9.png)

**Comment by RavenSystem** [comment]
Yeah, now I can reproduce your issue!! Maybe I will need sometime to fix it, but I have made a little change. Please, try the latest commit and comment.

**Comment by RavenSystem** [comment]
As far I can read [here](https://groups.google.com/forum/#!topic/sonoffusers/5vmtT6mRxHE), problem can not be solved in code. When my Sonoff is connected to 220v, induction interferences cause a lot of issues; for example, if I turn on lights of the room (not Sonoff), Sonoff toggle too automatically. I'm using 3 mts of wire for the wall-switch. I will try to connect an external ceramic capacitor to GPIO14 and GND to avoid interferences and test if this solves the issue.

**Comment by osvaldoasn** [comment]
Hi, Maybe it could be solved by software because with this firmware (https://github.com/arendst/Sonoff-Tasmota) GPIO14 works ok as switch (and other functions), without induction bug.

Thanks for your work!

**Comment by pcsaito** [comment]
@osvaldoasn I think I solved this with software only, if you still have this issue please try my branch and tell me if it solves for you:
https://github.com/pcsaito/esp-homekit-demo/tree/LPFToggle

**Comment by RavenSystem** [comment]
Solved in Sonoff RavenCore firmware.

**Comment by peros550** [comment]
Hi, sorry for this out of topic question, if sonoff is connected in 220V mains, how would you monitor the output in case of an issue?

**Comment by RavenSystem** [comment]
You must connect UART without connecting 3.3V wire. And Sonoff and computer must connected to same 230VAC circuit to minimize risk. But yes, there is a little risk. I personally do that, but I use a low cost PC, not my iMac.
