### ISSUE TITLE
HAA Sonofff basic - how to configure The Initial State when device enters on boot 

### ISSUE THREAD

**Issue by sblitzer** [RavenSystem/esp-homekit-devices#701]
Hello

For Sonofff basic i used the examples in the WIKI:
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]}]}

my question is : how do i configure Initial State of the switch when device enters on boot ?
I know that Initial state is defined by the "s" object contained within the accessory object.
For exp. i need it to be ON so the State is "1"
But how it reflected in the code?

Thanks

**Comment by mafyata** [comment]
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"s":1,"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]}]}

**Comment by sblitzer** [comment]
mafyata - thanks for your replay - will try it today.
Have a nice day :)

**Comment by sblitzer** [comment]
BTW - can you please also help with the same issue but on Sonoff dual?
I'm using this:

{"c": {"l": 13,"b": [{"g": 10}]},"a": [{"0": {"r": [{"g": 5}]},"1": {"r": [{"g": 5,"v": 1}]},"b": [{"g": 0}]},{"0": {"r": [{"g": 12}]},"1": {"r": [{"g": 12,"v": 1}]},"b": [{"g": 9}]}]}

Many thanks

**Comment by mafyata** [comment]
{"c": {"l": 13,"b": [{"g": 10}]},"a": [{"s":1,"0": {"r": [{"g": 5}]},"1": {"r": [{"g": 5,"v": 1}]},"b": [{"g": 0}]},{"0": {"r": [{"g": 12}]},"1": {"r": [{"g": 12,"v": 1}]},"b": [{"g": 9}]}]}

**Comment by sblitzer** [comment]
U the best !!
Many thanks
