### ISSUE TITLE
Cant complete setup, no web appears on LCM AP

### ISSUE THREAD

**Issue by jvhtec** [RavenSystem/esp-homekit-devices#702]
Hi, just flashed a generic ESP breaker with LCM via Tasmota firmware upgrade with a file provided here on this forum. Now my device is broadcasting LCM AP but doesnt show the web configuration page on connecting. Tried from PC (Chrome, Firefox), MacOS (Safari) and iOS to no avail. Any ideas?

**Comment by Rocket200** [comment]
same problem here

**Comment by Dirk23** [comment]
I have the same problem with my Sonoff Dual R2. What helped me was rebooting the device. Only at the 2nd start after flashing the setup page was displayed. It seems to me that the device does not get an Ip address from the HAA Access Point.

**Comment by peros550** [comment]
Same problem was found, one or multiple reboots definitely helped. AP does not assign IP when is stuck.

**Comment by Rocket200** [comment]
I can now connect to the LCM Settings always (sometimes need unplug the device)
i can write everything inside wifipassword,OTA, but nothing happens after i Click Join Button (i Try Safari,Mozilla,Brave)

**Comment by dbartelmus** [comment]
Whole process is not working well, I’m always  struggling to install haa in sonoff - need to wait for fix

**Comment by Rocket200** [comment]
It need sometimes a reboot then get connected! (Flash with esptool)

The best way is to connect Serial and look in the log what happened

**Comment by Rocket200** [comment]
> It need sometimes a reboot then get connected! (Flash with esptool)
> 
> The best way is to connect Serial and look in the log what happened
