### ISSUE TITLE
separate accessory for LED light on smart plug

### ISSUE THREAD

**Issue by tonysprenk** [RavenSystem/esp-homekit-devices#704]
Can someone help me tweak my template so I can get I separate switch in the home app for the LED on my smart plug? 

this is the template so far:

{"c":{"b":[{"g":13,"t":5}]},"a":[{"t":2,"0":{"r":[{"g":5},{"g":12}]},"1":{"r":[{"g":5,"v":1},{"g":12,"v":1}]},"b":[{"g":13}]}]}

Thanks a lot!!

**Comment by peros550** [comment]
So you want to separate the LED function from the operation of your smart plug?

**Comment by tonysprenk** [comment]
Yes, I have two smart plugs in the bedroom and the led light is quite bright when the room is dark. Would be nice to be able to turn it off separately from the relay.

**Comment by peros550** [comment]
So you would still need the Led light to follow the plug operation, but at times you would like this to be completely turned off despite the plug's relay status. I'm don't know how this conditional behavior could be implemented. But maybe someone more experienced could provide more feedback...

**Comment by RavenSystem** [comment]
Relay: GPIO 5
LED: GPIO 12

`{"c":{"b":[{"g":13,"t":5}]},"a":[{"t":2,"0":{"r":[{"g":5}],"m":[{"g":2}]},"1":{"r":[{"g":5,"v":1}],"m":[{"g":2,"v":1}]},"b":[{"g":13}]},{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]}}]}`

**Comment by tonysprenk** [comment]
Amazing thank you!
