### ISSUE TITLE
Garage Door shows as Opening in Home when powered on with door closed

### ISSUE THREAD

**Issue by MrCmonster** [RavenSystem/esp-homekit-devices#707]
Great work on this!
I'm using a Sonoff SV for a Garage Door opener with HAA 1.0.0. I'm getting odd behavior when the device boots up.

**Prerequisite:**
The device has both an open and a close sensor correctly configured.

**Steps to reproduce:**

1. Close the door
2. Once the door is fully closed, simulate a power outage by unplugging the Sonoff and plugging it back in
3. Go into the Home app and check the door status

**Expected result:**
The Sonoff should read the door sensor on startup and see that the door is closed.

**Actual result:**
The Sonoff shows that the door is Opening.
![IMG_0617](https://user-images.githubusercontent.com/22509056/71634051-e9471680-2bd5-11ea-9900-55dbee5fe5a9.PNG)

Note:
If the door is fully open when the Sonoff is power cycled, then it shows correctly that the door is open. 

This is my current JSON:
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":40,"d":25,"f3":[{"g":14,"t":0}],"f4":[{"g":14}],"f2":[{"g":4,"t":0}],"f5":[{"g":4}],"0":{"r":[{"g":12,"v":1,"i":0.5}]},"1":{"a":0},"2":{"r":[{"g":12,"i":1.5},{"g":12,"v":1,"i":0.5},{"g":12,"v":1,"i":2}]},"3":{"a":2},"10":{"a":0}},{"i":1,"1":{"m":[{"g":1,"v":2}]}}]}

Everything is working fine except for this one issue.

Thanks!

**Comment by RavenSystem** [comment]
I will check it.

**Comment by pilot1981** [comment]
@MrCmonster what happen if there is power outage or a security stop when door is opening or closing? Your Sto arrivando! Able to start again relays to open/close garage door?

**Comment by RavenSystem** [comment]
@MrCmonster Bug confirmed and fixed in new version 1.1.0. Try it and comment, please.

**Comment by MrCmonster** [comment]
It’s fixed in 1.1.0 
Thank you very much for all of your hard work!
