### ISSUE TITLE
1.0 broke my light bulbs. 

### ISSUE THREAD

**Issue by tonysprenk** [RavenSystem/esp-homekit-devices#709]
After updating my lightbulbs I can’t switch them on anymore from the home app. Here’s my JSON:

{"c":{"b":[{"g":0}]},"a":[{"t":30,"r":14,"g":12,"v":13,"w":4,"fr":4,"fg":4,"fv":4}]}

**Comment by pawelosin** [comment]
The same issue with Magic Home RGB led strip.
{"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":15,"g":13,"v":12,"w":14,"b":[{"g":0}]}]}

**Comment by RavenSystem** [comment]
Try v1.0.1.

**Comment by tonysprenk** [comment]
This was fixed in 1.0.1
