### ISSUE TITLE
Feature request: Last state on startup

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#71]
I’d like to ask for two features for a basic mode 1:

1. Start mode: Off(default)/On/Last state/Opposite to last 
(I need On/Last State mostly)
2. LED mode: light during On

Currently, when I switch Sonoff Basic to On, it just blinks once - it’s impossible visually to guess it’s current state.

**Comment by RavenSystem** [comment]
1. This matter has been discussed many times in other threads. Version 0.5.0 will add the feature.
2. If you want a status LED for relay, you must use a Sonoff TH, S20, S22 or any model that includes it. Sonoff Basic has only one LED, and it will be used for device status only.

**Comment by RavenSystem** [comment]
Added to TODO list: https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List

**Comment by RavenSystem** [comment]
Same answer that issue #79 .

**Comment by nov-** [comment]
Thanks a lot for this great firmware and hard work :) . Is there any hope to get some configuration ability to change green LED behaviour from device status only (blinks once) to displaying current state (ON or OFF)? Thank You.
