### ISSUE TITLE
Kill switches as Characteristic of accessory, instead of separate switches

### ISSUE THREAD

**Issue by macjl** [RavenSystem/esp-homekit-devices#713]
Hello José,

I'l not an HomeKit expert, but do you think that kill switch could be grouped with the accessory it is controlling? Since iOS 13.2, user can choose if they want to group or not the devices that are in the same accessory. The benefits would be less icon in Home app.

With HAA, the kill switches are separate accessory from the ones they controls. By grouping the characteristic of the kill switch within the same accessory, I think it will permit grouping them.

Do you know if it's doable?

**Comment by RavenSystem** [comment]
You could separate them, but you could not move to a different room. And would be necessary to recode all "kill switches" subsystem.

**Comment by RavenSystem** [comment]
Remember that you can group "kill switches" (o any other switch) from different accessories.

**Comment by macjl** [comment]
Manually grouping accessories don't work the same way. If you group multiple switches, by activating the group, all switches will be triggered at the same time.
When an accessory contain different characteristics, if you click on the accessory in Home, only the principal characteristic will be triggered. For the others, you have to open the accessory details. I think it's much better for the use case of kill switches.

**Comment by macjl** [comment]
> You could separate them, but you could not move to a different room.

I didn’t noticed that. Thank you for pointing it as it would be a regression for some users.

**Comment by pilot1981** [comment]
You can use specific room...
Kill switch what means? To enter in setup mode? Which difference there is with dummy switch?

**Comment by macjl** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#Kill-Switch
