### ISSUE TITLE
Feature request - MAX31865 support for RTD as temperature sensors

### ISSUE THREAD

**Issue by therealbat** [RavenSystem/esp-homekit-devices#715]
Hi Jose,
i love what you did so far. i'm wondering whether you only focus on supporting out-of-the-box devices or maybe some custom made open-source hw as well.
i am working on a shield for the wemos mini / esp-01m that has a max31865 and an analog multiplexer to support multiple RTDs (up to 4) - and i'm wondering if there are any known guidelines on the GPIO assignments etc with HAA - it would be so great to have it working natively with homekit without extra bridges.

or if there's any ideas of future API to communicate with HAA over I2C or serial - and map the returned data to objects or actions - so specific functions will not pollute the codebase.

**Comment by RavenSystem** [comment]
I2C is not supported... yet.
