### ISSUE TITLE
how to get ravencore work with dht11

### ISSUE THREAD

**Issue by edmundhei** [RavenSystem/esp-homekit-devices#72]
I manage to install ravencore on esp8266 and add it to homekit. But homekit detect it as a switch. How do I set it to work with dht 11?

**Comment by hmbarbosa** [comment]
Follow the instructions and use Eve for HomeKit by Eve Systems GmbH from app store to change. :) cheers

**Comment by edmundhei** [comment]
i have look at the wiki and not quite sure how to edit it with the eve app. I don’t see there is any option to change the settings.

**Comment by mmiglier** [comment]
“Show Setup” virtual type is not visible by default on the Eve app. There’s an option to make hidden types visible.

**Comment by edmundhei** [comment]
How to change that option? where can i change it from?

**Comment by hmbarbosa** [comment]
Open Eve, selects Rooms, open your switch and it should be there ”show Setup” move to ”on” and wait the reboot... Refresh Eve.. :)

**Comment by edmundhei** [comment]
Ok Thanks for the quick reply. i managed to change the device type to thermostat but i can’t change the sensor type to 1 which is dht -11 . default is22. Also which gpio pin should i connect the dht11 to? Thanks

**Comment by RavenSystem** [comment]
Sensor must be connected to GPIO14, VCC and GND. This is the default GPIO used by Sonoff TH and S22.
