### ISSUE TITLE
Setup mode not working

### ISSUE THREAD

**Issue by LukasHa89** [RavenSystem/esp-homekit-devices#720]
Hi,
I have a problem enter the setting mode to change WiFi or change HomeKit ID.
The first setup is OK and everything works, but if I need to enter setup mode, nothing happens if I press the button for 8 seconds. The device looks stuck. Sometimes the device appears in AP mode, but cannot connect to it and disappears after a while. I've tried other JSON settings and it doesn't work either. Emergency mode too not work.
Where can the problem be? I tried Sonoff Basic, RF and Shelly 1.
Thanks.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Setup-Mode#device-connection
