### ISSUE TITLE
sonoff basic toujours en mode configuration

### ISSUE THREAD

**Issue by clint80** [RavenSystem/esp-homekit-devices#723]
bonjour
j,ai flasher mon sonff basic avec la methode OTA
apres avoir configurer mon Json puis sauvegarder 
mon sonoff clignote une fois puis 8s apres clignote 5 fois
avez vous deja eu ce probleme 
merci

**Comment by RavenSystem** [comment]
English, please.

**Comment by clint80** [comment]
hello I  have flash my sonoff basic with the OTA method
 after having configured my Json then save 
 mon sonoff flashes once then 8s after flashes 5 times 
you have already had this problem 
thank you

**Comment by RavenSystem** [comment]
Can you add them to HomeKit?

**Comment by clint80** [comment]
in HomeKit, I see the HAA-XXXXXX icon
I type the code, it tries to synchronize it, but each time it fails

**Comment by RavenSystem** [comment]
What JSON are you using?

**Comment by clint80** [comment]
this is the model that is on your site: https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":40,"d":18,"f3":[{"g":14,"t":0}],"f4":[{"g":14}],"f2":[{"g":4,"t":0}],"f5":[{"g":4}],"0":{"r":[{"g":12,"v":1,"i":0.5}]},"1":{"a":0},"2":{"r":[{"g":12,"i":1.5},{"g":12,"v":1,"i":0.5},{"g":12,"v":1,"i":2}]},"3":{"a":2},"10":{"a":0}},{"i":1,"1":{"m":[{"g":1,"v":2}]}}]}

**Comment by clint80** [comment]
I was wrong for the sonoff basic, I took this one
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]}]}

**Comment by clint80** [comment]
after several flashes
I have successfully synchronized with HomeKit
thank you for all the work you do
