### ISSUE TITLE
Custom Hostname

### ISSUE THREAD

**Issue by dominikkosciolek** [RavenSystem/esp-homekit-devices#724]
Custom Hostname option for the following configuration does not work
{"c":
{"l":0,"b":[{"g":2,"t":5}],"n": "HostName"},
"a":[{
"0":{"r":[{"g":15}]},
"1":{"r":[{"g":15,"v":1}]},
"b":[{"g":5,"p":0,"i":1}]},
{"0":{"r":[{"g":4}]},
"1":{"r":[{"g":4,"v":1}]},
"b":[{"g":13,"p":0,"i":1}]}
]}

**Comment by RavenSystem** [comment]
It works for me. Check your network.
<img width="773" alt="Captura de pantalla 2020-01-10 a las 14 20 06" src="https://user-images.githubusercontent.com/8655274/72155842-4dc35c00-33b4-11ea-924d-b5b82d863723.png">
