### ISSUE TITLE
HAA - Window

### ISSUE THREAD

**Issue by netRunner0** [RavenSystem/esp-homekit-devices#725]
Hi
Is it possible to track the position of the window on the analog input?
I also want to detect obstacles through a digital input

**Comment by RavenSystem** [comment]
> Is it possible to track the position of the window on the analog input?

No.

> I also want to detect obstacles through a digital input
Use `"f5"` and `"f6"`: More info: https://github.com/RavenSystem/esp-homekit-devices/wiki/Window-Covering#state-inputs
