### ISSUE TITLE
couldn't add HAA-XXXXX

### ISSUE THREAD

**Issue by toshibochan** [RavenSystem/esp-homekit-devices#726]
I have MagicHome led controller with {"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":12,"g":5,"v":13,"b":[{"g":0}]}]}

but I getting this on home app
couldn't add HAA-XXXXX
 please help

**Comment by RavenSystem** [comment]
Logs, please.

**Comment by toshibochan** [comment]
How get log? I’m using Ubuntu.
