### ISSUE TITLE
after reboot enters setup mode

### ISSUE THREAD

**Issue by remobil** [RavenSystem/esp-homekit-devices#731]
after a reboot, it enters setup mode, I save everything, it works until the first power off, then again setup. What could be the problem?
Here is my json

{"c":{"o":0,"f":10,"m":30},"a":[{"0":{"r":[{"g":12,"v":1}]},"1":{"r":[{"g":12,"v":0}]},"t":4,"i":1,"b":[],"s":4},{"t":22,"b":[],"n":3,"g":5,"j":20,"z":8.5},{"t":6,"s":0,"i":10,"f1":[{"g":14,"t":0,"i":0,"p":1}]}]}

**Comment by remobil** [comment]
Esp12

**Comment by marcoscv-work** [comment]
The same happened to me when I used a JSON with the wrong quotation marks format, I cannot fix it
