### ISSUE TITLE
RavenCore vs HAA

### ISSUE THREAD

**Issue by Olepir** [RavenSystem/esp-homekit-devices#733]
RavenCore was pulled too soon, it was working fine for many people, also it needs less knowledge to work with.
HAA and json are confusing, also lacking support from community, for example no one answered my question about json for a power strip for two weeks and an issue was just closed unresolved.
People should be able to use RavenCore till HAA is matured.

**Comment by RavenSystem** [comment]
RavenCore had many bugs with iOS13, even a several security bug. HAA is matured, with a great documentation and a great community, growing every day.

I can not find your issue about json for a power strip, or you issue that was just closed unresolved. I only see  a couple of issues about single channel lightbulbs, and in one of them, you are talking about issues from other firmware outside this project. In the other, I personally reply you 2 days after you open it, and you never said anything more. If you want a firmware that makes you happy with all your requirements, learn how to code and make it by yourself instead saying others what we must do.
