### ISSUE TITLE
Is it right JSON for a power strip?

### ISSUE THREAD

**Issue by Olepir** [RavenSystem/esp-homekit-devices#734]
arendst/Tasmota#4590

{"c":{"l":1,"i":1,"b":[{"g":3,"t":5}]},"a":[{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"t":2,"b":[{"g":3,"t":2}]},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"t":2,"b":[{"g":3,"t":2}]},{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"t":2,"b":[{"g":3,"t":2}]},{"0":{"r":[{"g":13}]},"1":{"r":[{"g":13,"v":1}]},"t":2,"b":[{"g":3,"t":2}]},{"0":{"r":[{"g":14}]},"1":{"r":[{"g":14,"v":1}]},"t":2,"b":[{"g":3,"t":2}]}]}

**Comment by gauix4** [comment]
https://glumb.github.io/haa-configurator/

:)

**Comment by Olepir** [comment]
> https://glumb.github.io/haa-configurator/

doesn’t help
