### ISSUE TITLE
Feature request : ability to send serial commands

### ISSUE THREAD

**Issue by tonysprenk** [RavenSystem/esp-homekit-devices#738]
Some devices use a second chip to which the esp chip sends a serial command to trigger an action, it would be great if HAA supported these devices. Tasmota supports this so it should be possible.

**Comment by tonysprenk** [comment]
More info on how this is achieved by Tasmota can be found here: https://tasmota.github.io/docs/#/TuyaMCU?id=tuya-protocols

**Comment by RavenSystem** [comment]
This will be a new action type.

**Comment by mriksman** [comment]
Yeah this would be amazing. Right now, the only 'Dimmers' HAA supports is PWM output type. But if TuyaMCU could be added, then a whole bunch of cheap glass touch wall switches could be used.
