### ISSUE TITLE
V0.4.4 GPIO14 AC interferences with dev type 1

### ISSUE THREAD

**Issue by sercitecotf** [RavenSystem/esp-homekit-devices#74]
He actualizado varios sonoff basic con la 0.4.3 y una vez ha terminado el proceso reviso y tienen la 0.4.4, y después de activar el GPIO14 empieza hacer cosas raras, al pulsar el interruptor hace doble encendido y apagadlo, y también retardo en encendido o apagado.
como puedo poner la 0.4.3 sin que se actualice a la 0.4.4?

**Comment by sercitecotf** [comment]
he actualizado uno que tenia con la versión 0.4.3 y ahora hace lo mismo que los otros :-(

**Comment by RavenSystem** [comment]
En un rato voy a publicar la versión 0.4.5 con un intento de corregir el problema. Es que estoy usando otro sistema para evitar las interferencias, pero aún hay que hacer más pruebas.

**Comment by sercitecotf** [comment]
ok
gracias

**Comment by RavenSystem** [comment]
v.0.4.5 publicada. Por favor, actualiza y comenta los resultados. ¡Muchas gracias!

**Comment by sercitecotf** [comment]
sigue igual, pulsas el interruptor GPIO14 se enciende si se apaga y aveces no hace nada, si esta encendido y pulsas para apagar no hace nada

**Comment by sercitecotf** [comment]
y hace interferencia con otro, al encender y apagar varias veces se enciende los dos o se apagan los dos

**Comment by sercitecotf** [comment]
podre actualizar la v 0.4.3 sin que en el proceso se actualice a la 0.4.5?

**Comment by RavenSystem** [comment]
No, tienes que esperar un poco a la 0.4.6.

**Comment by sercitecotf** [comment]
ok
gracias

**Comment by sercitecotf** [comment]
probada y me va bien, por mi parte no le he notado nada raro :-)
