### ISSUE TITLE
Thermostat automation

### ISSUE THREAD

**Issue by pixidixi88** [RavenSystem/esp-homekit-devices#742]
Hi,
I have a solution for floor heating at my house based on HAA. I have one thermostat which steers a pump. It means turn on pump when water in pipes is above 30 degrees. I have also 4 valves steer by 4 HAA thermostat devices.
Is there any possibility to switch off this pump  when all of others get status “idle” close the valves? When all loops are closed pump is very noisy because water comes only through safety loop. Pump needs to be turn on again if at least one thermostat change the status to heating. Thanks for ideas.

**Comment by RavenSystem** [comment]
You can do an automation with some conditions, in this case: thermostat 1 is off, th 2 is off, th 3... and turn on selected thermostat; but you need a third party HomeKit client like Home+ because stock Home App does can not do it.

**Comment by pixidixi88** [comment]
Eve app cannot do this neither. Do you know which app could work? I have found many home+ apps in AppStore.

**Comment by RavenSystem** [comment]
https://apps.apple.com/es/app/home-4/id995994352

**Comment by RavenSystem** [comment]
You must create one automation for each thermostat to trigger it, and then include the others thermostats under conditions.

**Comment by diodo157** [comment]
You can use EVE, creating rule
Must be 4.
3 which start the pump for each thermostat
and one when the condition of all three stationary thermostats causes the pump to switch off
![IMG_0082](https://user-images.githubusercontent.com/36050040/72429764-014f9600-3791-11ea-9d50-754efdd1149f.PNG)
