### ISSUE TITLE
Temperature & Humidity Sensor are not sensors

### ISSUE THREAD

**Issue by skv6** [RavenSystem/esp-homekit-devices#744]
My HomeKit can see Temperature & Humidity Sensors but they are not sensors. I can see temperature but cant make a automation which start from temperature sensor. The is Contact Sensor but not temperature and Humidity.

**Comment by ptath** [comment]
>> I can see temperature but cant make a automation which start from temperature sensor.

Yes, you can not, this is a stupid home.app restriction =)
