### ISSUE TITLE
Json help: send http commands

### ISSUE THREAD

**Issue by tonysprenk** [RavenSystem/esp-homekit-devices#749]
Can someone help me with my json? I have a smart outlet which is working perfectly with HAA but I would like it to also be able to send http commands to my tasmota curtains. Is it possible to have the smart socket keep it’s functionality and to also create a curtain accessory in the home app? This is the current json string:  {"c":{"b":[{"g":13,"t":5}]},"a":[{"t":2,"0":{"r":[{"g":5},{"g":12}]},"1":{"r":[{"g":5,"v":1},{"g":12,"v":1}]},"b":[{"g":13}]}]}

**Comment by RavenSystem** [comment]
Yes, you can do it.

Example of an action:
This HTTP request: `http://<ip>/cm?cmnd=Power%20ON`
is this HAA Action: `"1":{"h":[{"h":"<ip>","u":"cm?cmnd=Power%20ON"}]}`
