### ISSUE TITLE
Unable to update 

### ISSUE THREAD

**Issue by mafyata** [RavenSystem/esp-homekit-devices#750]
Hi , I have working device with Haa 0.9.1. I want to update to 1.3.1(latest) version. 
1. Enter the device in setup mode(auto ota update is on)- no luck.
2. Enter setup mode and click on “update ota” - no luck. 

I tried 2 methods many times.

**Comment by mafyata** [comment]
I can update my devices from 1.2.1 to 1.3.1. The problem is only from 0.9.1

**Comment by RavenSystem** [comment]
Logs, please.

**Comment by Kienz** [comment]
I have the same from 1.3.1 to 1.5.x. Two devices not updating and bricked after I want to update. Both devices are not connecting to HomeKit. ping to the device is working. But I can't get logs (https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-Instructions#capture-logs).
