### ISSUE TITLE
Temporary Childlock the Wall-Switch?

### ISSUE THREAD

**Issue by Shimakuchi** [RavenSystem/esp-homekit-devices#752]
Hi, I have some shelly 2.5 which control my roller shutters. My 1,5 year old son now discovers the wall mounted switches. Is it possible to add a option which allows me to temporarily disable the wall switches in Home(Kit) App?

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#kill-switch
