### ISSUE TITLE
Sonoff Basic RF R3 supported by HAA?

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#753]
Hi,
Sonoff Basic RF R3 is or will be supported by HAA?

**Comment by RavenSystem** [comment]
I have not tested it, but as far I know, HAA must work with Basic R3.

**Comment by pilot1981** [comment]
so HAA firmware manage ESP8266 and then I have to config it to interface to RF chip?

**Comment by RavenSystem** [comment]
In other devices, like Sonoff POW with RF, RF trigger GPIO-0 (that is the built-in button too).

**Comment by pilot1981** [comment]
I think you are right:
![Sonoff-Tasmota-configurazione-a-impulsi](https://user-images.githubusercontent.com/46350465/72996228-a6561880-3dfa-11ea-8bbc-82376ff9921b.png)

**Comment by pilot1981** [comment]
I will try to install HAA firmware and I let you know in next weeks
