### ISSUE TITLE
v1.4.0 ICMP Ping - how it works?

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#758]
At first I understood the feature a “push” way of HAA remote control, so a better description might be needed. Moreover Wiki pages still miss this new part.

I still have questions on a scenario how this ICMP feature might be used.

1. Looks like HAA pings some remote device IP (resolved from netbios name or FQDN) and sets own status according to remote device reachability. Right?
2. What is the default ping interval? 1 sec?
3. So there are actually two hosts: p0 and p1. How the device will react if they are different? Last event wins?

**Comment by RavenSystem** [comment]
Wiki is under development, but @WizBangCrash need more time to finish it. Please, be patient.

> 1. Looks like HAA pings some remote device IP (resolved from netbios name or FQDN) and sets own status according to remote device reachability. Right?

Yes, in the same way digital inputs work.

> 2. What is the default ping interval? 1 sec?

5 seconds, and for now there is not way to change this. But to set a ping as "not response" must be 3 fails in a row.

> 3. So there are actually two hosts: p0 and p1. How the device will react if they are different? Last event wins?

Both wins. Two hosts is like 2 buttons, what happens if you press both (one and then other)? Here is the same.

**Comment by WizBangCrash** [comment]
@i3laze I've updated the Wiki with details of the new ICMP Ping feature. Let me know if any further clarification should be added to the docs.
https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#icmp-ping-inputs

**Comment by i3laze** [comment]
> @i3laze I've updated the Wiki with details of the new ICMP Ping feature. Let me know if any further clarification should be added to the docs.
> https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#icmp-ping-inputs

Quite detailed. However all examples contain both reply and no-reply inputs so its hard to guess which accessory one triggers.
