### ISSUE TITLE
sonoff touch switch 

### ISSUE THREAD

**Issue by sercitecotf** [RavenSystem/esp-homekit-devices#76]
una pregunta, el ravencore 0.4.6 vale para el sonoff touch switch de dos pulsadores?

**Comment by RavenSystem** [comment]
Teóricamente sí, seleccionando el tipo 2 (dev type 2), pero yo no lo he probado. Sé que funciona con el T1 de 2 canales, que es la versión de Reino Unido del Touch Switch EU de 2 pulsadores..

**Comment by sercitecotf** [comment]
ok, te voy comentando los resultados

**Comment by sercitecotf** [comment]
pruebas realizadas satisfactoriamente :-) en una placa eu de las nuevas, tengo fotos del pinout, si las necesitas, te las envió

**Comment by RavenSystem** [comment]
¡Fantástico! Toda información útil siempre es bien recibida.
