### ISSUE TITLE
How do I add to JASON the option : Initial State - Last state before restart (5) 

### ISSUE THREAD

**Issue by sblitzer** [RavenSystem/esp-homekit-devices#760]
Hi All,

I use this JASON for Sonoff Dual Window Cover
{"c":{"l":13,"b":[{"g":10,"t":5}]},"a":[{"t":45,"o":19,"c":19,"f":0,"0":{"r":[{"g":12,"v":1},{"g":5}]},"1":{"r":[{"g":12},{"g":5,"v":1}]},"2":{"r":[{"g":12},{"g":5}]},"3":{"r":[{"g":12,"i":1},{"g":5}]},"4":{"r":[{"g":12},{"g":5,"i":1}]},"f0":[{"g":0}],"f1":[{"g":9}]}]}
How do I add Initial State - Last state before restart (5)

Thanks for your help.

**Comment by mafyata** [comment]
"s":5 must be added

**Comment by sblitzer** [comment]
I know, but where should I add it?

**Comment by RavenSystem** [comment]
Window covering has not that option, because last position are saved always when cover is stopped for at least 5 seconds.

**Comment by sblitzer** [comment]
If you say last position is always saved, why when the power is down for some time and up  - homekit see the covering closed while in fact its open?

**Comment by RavenSystem** [comment]
Logs, please.
