### ISSUE TITLE
Shutter Problem Shelly2.5

### ISSUE THREAD

**Issue by SMMMN** [RavenSystem/esp-homekit-devices#762]
Hello everybody,

I bought a shelly2.5 and successfully installed the Haa firmware. Thanks for this great work. I am already successfully switching my roller shutter with two switches. My question is now: when I press the button of the shutter in the home app it only switches between fully open and fully closed. Is it possible that the roller shutter stops when I press the button in the home app a second time?

**Comment by marcoscv-work** [comment]
You can use the percent opening/closing option by using long-press in your roller

![image](https://user-images.githubusercontent.com/7963804/72945232-93e8ca00-3d7b-11ea-8325-77f0a5cfedf8.png)

**Comment by SMMMN** [comment]
Thanks, I found that out too. So is this the normal HomeKit behaving, like a lamp that is either on or off, and so the blinds are fully open or fully closed? It would actually be easier for me to stop the blind with a second tap on the button in the Home app.

**Comment by RavenSystem** [comment]
@SMMMN Ask Apple to implement stop function in HAP.

**Comment by marcoscv-work** [comment]
I see your point...  yeah, sometimes I have to run to press the switch :-P  or you can order to siri to stop in an opening percent...
