### ISSUE TITLE
RavenCore current state

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#763]
I still find HAA too complicated for generic use. Setup is too advanced and prone to errors.
Huge flexibility and extra features come at multiple disadvantages compared to RC like:
- You need to know device IP address to set it up.
- You need to read JSON and don’t mess up with the {[{markup}]}.
- No startup templates - you get one from Wiki and hope it will just work.
- Entering setup is more complicated than it was via Eve.app. 
- Any changes require significant time and hustle.

I’ve just upgraded f/w on RC v1.2 and eventually got HAA (I hoped to get RC v1.3.1).
Then I erased flash and configured LCM with ”RavenSystem/ravencore” repo, but again I received HAA!
Is that by design now? I was totally OK with RC and an ability to move forward to HAA via OTA when I need extra features or GUI & [HAA JSON Configurator](https://glumb.github.io/haa-configurator/) simplifies up to a level.

**Comment by RavenSystem** [comment]
> You need to know device IP address to set it up.

You can use hostname instead (Showed in Home App under Serial number label).

> You need to read JSON and don’t mess up with the {[{markup}]}.

Use a JSON validator. Many people use JSON to configure services like HomeBridge without any issue.

> No startup templates - you get one from Wiki and hope it will just work.

All templates from the Wiki page work perfectly.

> Entering setup is more complicated than it was via Eve.app.

Entering setup is very easy. Even you can define custom ways to do that.

> Any changes require significant time and hustle.

No, if you know what are you doing.

**Comment by RavenSystem** [comment]
Read the Wiki and release notes. You can get info about RavenCore here:
https://github.com/RavenSystem/esp-homekit-devices/releases/tag/RC_1.3.0
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore

**Comment by i3laze** [comment]
In the end, the current only option to install RC is without OTA?

**Comment by RavenSystem** [comment]
Yes, but RC is not currently available.
