### ISSUE TITLE
Salt level sensor for water softener

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#767]
Hi,
There is a chance to have new device Salt level sensor for water softener? This is already allowed by Apple?

I need only a sensor 0/1 to to when to add new salt in my water softner...

In worst case I could use a sonoff/Shelly with a sensor attached to a micro switch which go on/off depending from salt level...

**Comment by RavenSystem** [comment]
HomeKit does not provide a salt level sensor. You can use any other supported sensor (Maybe filter change sensor could be a good option): https://github.com/RavenSystem/esp-homekit-devices/wiki/Sensors

**Comment by pilot1981** [comment]
I used a JSN SR04T with water leak sensor HAA accessory and a fixed distance: it works fine!
