### ISSUE TITLE
HAA_boot.bin release

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#768]
Great job on the new one.

Looks like a fork of LCM, just without repo input (this input was prone to errors and extra hustle indeed).
Any other changes unnoticed?
Any benefits from reflashing existing LCM+HAA devices to this OTA?
Any way to reflash boot partition without Serial?
What other features are on the roadmap?

**Comment by macjl** [comment]
Hello,

Is there a way to flash the new OTA firware (with Serial), and keep HAA all settings (JSON, Homekit data, etc...)?

I would like to keep all my automations and settings in Home

**Comment by RavenSystem** [comment]
@macjl Yes (I think), but try first with a device without automations to have not a big lost.

- Save a copy of your JSON.
- Flash it with this command, using only haaboot.bin (Don't erase it before):
`esptool.py -p /dev/<your_ESPPort> --baud 115200 write_flash -fs 1MB -fm dout -ff 40m 0x2000 haaboot.bin`
- Connect to it, and configure WiFi and JSON (Don't reset HomeKit ID).
- Click Save, and wait about 5-7 minutes.

**Comment by RavenSystem** [comment]
@i3laze 

> Any other changes unnoticed?

Removed the Private Key to verify LCM firmware.

> Any benefits from reflashing existing LCM+HAA devices to this OTA?

A bigger user storage to save greater JSON configs.

> Any way to reflash boot partition without Serial?

No.

> What other features are on the roadmap?

None.

**Comment by macjl** [comment]
> Yes (I think), but try first with a device without automations to have not a big lost.
> 
> * Save a copy of your JSON.
> * Flash it with this command, using only haaboot.bin (Don't erase it before):
>   `esptool.py -p /dev/<your_ESPPort> --baud 115200 write_flash -fs 1MB -fm dout -ff 40m 0x2000 haaboot.bin`
> * Connect to it, and configure WiFi and JSON (Don't reset HomeKit ID).
> * Click Save, and wait about 5-7 minutes.

I tried it on a tes device, and it worked!
I had to reboot twice after last step, but all works perfectly now! Thank you!

**Comment by peros550** [comment]
> @macjl Yes (I think), but try first with a device without automations to have not a big lost.
> 
> 
> 
> - Save a copy of your JSON.
> 
> - Flash it with this command, using only haaboot.bin (Don't erase it before):
> 
> `esptool.py -p /dev/<your_ESPPort> --baud 115200 write_flash -fs 1MB -fm dout -ff 40m 0x2000 haaboot.bin`
> 
> - Connect to it, and configure WiFi and JSON (Don't reset HomeKit ID).
> 
> - Click Save, and wait about 5-7 minutes.
> 
> 

Just for me to understand. Are those steps used to go from LCM+HAA —> HAA_OTA + HAA preserving existing HomeKit ID?

**Comment by i3laze** [comment]
> Just for me to understand. Are those steps used to go from LCM+HAA —> HAA_OTA + HAA preserving existing HomeKit ID?

Yeap, you’ll get up-to-date from any HAA revision.

**Comment by peros550** [comment]
So this is a way to go from LCM to HAA_ OTA right ?
