### ISSUE TITLE
Sonoff T0EU2C + Window Covering

### ISSUE THREAD

**Issue by STijeras91** [RavenSystem/esp-homekit-devices#769]
Buenas a todos, me gustaría saber cual es la configuración JSON para una persiana con este dispositivo, funcionando los botones táctiles.

Me podéis echar una mano, muchísimas gracias

Un saludo!

**Comment by RavenSystem** [comment]
Debería servirte el mismo JSON que para el Sonoff Dual:
https://github.com/RavenSystem/esp-homekit-devices/wiki/HAA-Templates#sonoff-dual-window-covering-driver-with-external-push-buttons-status-led-and-built-in-setup-button-opening-time-18-seconds-closing-time-14-seconds-non-lineal-correction-70

Métete en el chat, en el canal español, que estas dudas suelen responderse mucho más rápido allí.
