### ISSUE TITLE
Sonoff TH with Sensor Si7021

### ISSUE THREAD

**Issue by hmbarbosa** [RavenSystem/esp-homekit-devices#77]
Any chance to add support for Sonoff TH10  Si7021 sensor? I have flashed the sono TH10 but not reading the sensor. 

Gracias
Berto

**Comment by RavenSystem** [comment]
If you find a Si7021 sensor library for esp-open-rtos, I can add support for it.

**Comment by gpeter62** [comment]
http://www.esp32learning.com/code/esp32-and-si7021-temperature-sensor-example.php

**Comment by gpeter62** [comment]
https://github.com/NSBum/esp32-si7021

**Comment by ialidigital** [comment]
@RavenSystem looks like the support for Itead specific has made it into trunk from this [PR](https://github.com/SuperHouse/esp-open-rtos/pull/725)
