### ISSUE TITLE
Thermostat Initial State

### ISSUE THREAD

**Issue by Fudalii** [RavenSystem/esp-homekit-devices#770]
Can I set TH16 thermostat or other - initial state. What I mean is that after connecting to the power supply the thermostat should be automatically turned on or to remember the last state (
as in classic relays). I added s:5 but that's probably not it :)

{"c":{"l":13,"b":[{"g":0,"t":5}],"m":120},"a":[{"t":21,**"s":5**,"g":14, "n":3, "0":{"r":[{"g":12}]},"1":{"a":0},"3":{"r":[{"g":12,"v":1}]},"5":{"a":0}}]}

**Comment by RavenSystem** [comment]
Your JSON is right.
