### ISSUE TITLE
Garage door opener - No response 50% of the time

### ISSUE THREAD

**Issue by lockpicker** [RavenSystem/esp-homekit-devices#771]
I've been using a (homebridge + wemo maker) garage door controller on HomeKit for over 18 months without any issues. 
I decided to switch to a native HomeKit garage controller with a HAA on Sonoff Basic setup in the last few weeks. 
HAA on Sonoff basic as a garage door controller with HAA seems to be unresponsive rather frequently (about 50% of the time or more). 
Just to isolate any hardware issues, I flashed another Sonoff basic with HAA which shows the same issue, to isolate any network issues (although given all my other HomeKit devices work perfectly, I don't think this is a problem), I tried it at a friends place (his network) and the setup displayed the same issues.

This is causing significant reliability issues as I can't trust the setup to work every time. 
Any pointers would be much appreciated. 

![Garage Door - No response](https://user-images.githubusercontent.com/905805/73355319-07468a80-42ec-11ea-8090-123539602c1b.png)

**Comment by ymyshko** [comment]
I would advise checking the signal level at the module installation point. mDNS does not forgive the loss of packets and long pings. If signal level is -70db or less, there will be similar problems. Homebridge server can stand closer to the Wi-Fi access point and you just don’t see the inaccessibility of the module to homekit.
Sorry for my english&

**Comment by wwns** [comment]
Check what is happening, connect the module to the Uart port, if you have a Mac computer:
ls /dev/tty.*
screen /dev/tty.xxx_xxxx 115200
windows putty 👍
you'll know what's wrong!

**Comment by lockpicker** [comment]
Thanks @ymyshko and @wwns 
I’ll give these a shot and report back.

**Comment by Huege** [comment]
Dear all,
I'm facing the same issue.
log/console did not give any hint about an problem. Signal strength is ok.
Is it only a garadoor or a general issue?
BR

**Comment by yusufd1** [comment]
A lot of no response issues are now resolved in 1.6.4. Also wifi signal at the device must be pretty strong probably minimum of -75db. Check the signal strength and ensure that your have at least around that amount of strength.
