### ISSUE TITLE
Xiaomi-Philips bulb support

### ISSUE THREAD

**Issue by MaxLesichniy** [RavenSystem/esp-homekit-devices#774]
Hi, I really liked the project. Already flashed 5 devices on haa. But I wanted to reflash the Xiomi Philips led bulb. Appearance, she uses a different principle to control color temperature and intensity. This is described here https://github.com/arendst/Tasmota/issues/3055.

Can HAA support this type of LED control?

**Comment by dbartelmus** [comment]
So did you open your bulb already? Can you show us internals?

PWM is OK, DIgital not as far as I asked for RGBW strip before.

**Comment by MaxLesichniy** [comment]
Here is a photo of the board. The driver microcircuit marking is jammed, the lamp is in working condition.

![IMG_8309](https://user-images.githubusercontent.com/8543552/73826421-69305400-4806-11ea-8f2d-f60b3a2243a0.jpeg)
![IMG_8306](https://user-images.githubusercontent.com/8543552/73826434-6e8d9e80-4806-11ea-83c6-9b382e2dc77e.jpeg)
![IMG_8305](https://user-images.githubusercontent.com/8543552/73826438-6fbecb80-4806-11ea-9b89-19a40e4855c1.jpeg)
![IMG_8303](https://user-images.githubusercontent.com/8543552/73826444-72212580-4806-11ea-9835-ec5f1d66dfbc.jpeg)
![IMG_8304](https://user-images.githubusercontent.com/8543552/73826448-73525280-4806-11ea-896c-829fe9788fd2.jpeg)
![IMG_8302](https://user-images.githubusercontent.com/8543552/73826451-75b4ac80-4806-11ea-8106-fae2d9883e3e.jpeg)
![camphoto_1903590565](https://user-images.githubusercontent.com/8543552/73826455-76e5d980-4806-11ea-8984-2a5a35f43726.jpeg)

**Comment by dbartelmus** [comment]
As far as I know PWM has separate channels (wires) for R G and B, you have combined so it's digital communication (1 lane). HAA is not supporting it yet, ask politely author about this.

**Comment by dbartelmus** [comment]
Wait, this is not RGB bulb? Fool me.

Go ahead, plug RX, TX GND and V and try to flash it... simple. Trace signal wire with multimeter to find out which GPIO is it, looks like IO15 or IO12.
I would rather change JSON few time to figure this, in worst case scenario you have 15 tries

**Comment by MaxLesichniy** [comment]
@dbartelmus  Thanks for answers. 
Thanks for answers. 
> Wait, this is not RGB bulb? Fool me.

No, this is not an RGB bulb. This is a white bulb with adjustable light temperature.

I quote:
> To make it short I discovered GPIO12 controls color temperature without modifying total intensity, and GPIO15 controls light intensity without changing color temperature. It is different from other lamps where one GPIO usually controls the cold leds, and another one the warm leds, so I had to modify the code to accomodate this lamp.

GPIO12 controls the temperature by PWM. Warm and cold channel connected inverted to each other. When the PWM signal is at a high level that cold LEDs turn on, and when at a low level - warm LEDs turn on. When PMW operating cycle is 100% - the bulb shines completely cold light. At ~ 0%  - bulb shines warm light.

GPIO15 - is the same signal, but this pin is adjusts the overall brightness of all LEDs.

I am ran the light bulb with follow configuration:

```
{
  "c": {
    "b": [
      {
        "g": 0
      }
    ]
  },
  "a": [
    {
      "t": 30,
      "w": 15,
      "s": 0,
      "p": 1024,
      "d": 1,
      "e": 10,
      "b": [],
      "fg": 1,
      "fr": 1,
      "fv": 1,
      "fw": 1
    },
    {
      "t": 30,
      "s": 0,
      "p": 1024,
      "d": 1,
      "e": 10,
      "fr": 1,
      "fg": 1,
      "fv": 1,
      "b": [],
      "w": 12,
      "fw": 1
    }
  ]
}
```
The Home application has two sliders (as two accessories) now. One slider are control a light temperature, and the other - controls the intensity.

Can the firmware author add support for such bulb?
I don't know the code as the author knows it :/
I suggest add a new parameter to json file, which will indicate the temperature control pin. For example:
```
....
"a": [
    {
      "t": 30,
      "w": 15,
      "tm": 12, <--
      "s": 0,
      "p": 1024,
      "d": 1,
      "e": 10,
      "b": [],
      "fg": 1,
      "fr": 1,
      "fv": 1,
      "fw": 1
    },
 ...
```

**Comment by dbartelmus** [comment]
Can you show some screenshots from your accessory inside home app?
One slider for brightness and color wheel for light temperature sounds right
![sylvania-homekit-01](https://user-images.githubusercontent.com/6240915/74273644-188e8e80-4d11-11ea-8af8-f70a12180c50.jpeg)

**Comment by MaxLesichniy** [comment]
I don't have color wheel for light temperature. I have two sliders. And this sliders as a two accessories.

![image](https://user-images.githubusercontent.com/8543552/74275006-c6069f80-4d1b-11ea-8aaf-60bc8c1569f8.jpg)

**Comment by dbartelmus** [comment]
Privet! Please join discord channel to get more help, I do not have so much experience in this area but it can be done proper somehow for sure.
https://discord.gg/v8hyxj2

**Comment by RavenSystem** [comment]
Sorry, I have not any future plan to support this kind of devices.
