### ISSUE TITLE
does anyone have an example of using ICMP Ping Inputs and/or HTTP Request Actions?

### ISSUE THREAD

**Issue by diodo157** [RavenSystem/esp-homekit-devices#776]
Hi Everyone, Anyone have an example of Json for two nodemcu or sonoffs, which talk to each other? I with two nodemcu I did not succeed. I would need, to understand, both Json Thank you

**Comment by RavenSystem** [comment]
You have 2 examples in the Wiki: https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#icmp-ping-example-1
