### ISSUE TITLE
lock key button to esp

### ISSUE THREAD

**Issue by vsidlu** [RavenSystem/esp-homekit-devices#777]
![Image](https://user-images.githubusercontent.com/30963646/73580957-444b8200-4490-11ea-8506-17accce044c6.jpeg)

{"c":{"o":1,"l":2,"i":1,"b":[{"g":0,"p":1,"t":1}]},"a":[{"t":4,"v":1,"f0":[{"g":14,"v":1}],"f1":[{"g":14,"v":1}],"0":{"r":[{"g":14,"v":0,"i":2}]},"1":{"r":[{"g":14,"v":0,"i":1}]}}]}

need help with json -

lock opened when button is pushed twice. locks closed when button is pushed once. how can i make two digital output changes in a row so the lock is opened? with json above it only closes.

**Comment by vsidlu** [comment]
@RavenSystem is there a way to imitate double press? starting to get crazy sorting it out! can you help me?

**Comment by RavenSystem** [comment]
I am not sure what you want. It is?

Button on GPIO 14:
- Double press opens lock.
- Single press closes lock.

`{"c":{"o":1,"l":2,"i":1,"b":[{"g":0}]},"a":[{"t":4,"f0":[{"g":14,"t":2}],"f1":[{"g":14}],"0":{"r":[{"g":14,"i":2}]},"1":{"r":[{"g":14,"i":1}]}}]}`

(I removed all default and unused keys).

**Comment by vsidlu** [comment]
I want when I press 
- open lock in homekit - gpio 14 is changing from high to low to high to low and back to high.
- close lock in homekit - gpio 14 is changing from high to low and back to high.

1.- I’ve noticed that the GPIO needs to be HIGH STATE as normal, and when you want to activate it, you need to write LOW_STATE in the GPIO.
2.- 1 pulse from high to low close the lock, 2 pulses from high to low open it…
3.- If I put HIGH STATE as normal mode since Boot, there’s a glitch that tries to close the door when the ESP8286 boots

**Comment by RavenSystem** [comment]
Use my JSON.

> 1.- I’ve noticed that the GPIO needs to be HIGH STATE as normal, and when you want to activate it, you need to write LOW_STATE in the GPIO.

You can change this adding `"i":1` in the first GPIO 14 declaration.

> 3.- If I put HIGH STATE as normal mode since Boot, there’s a glitch that tries to close the door when the ESP8286 boots

When device boots, it will execute actions of actual lock state, in this case, action `"1"`, related to closed state.

**Comment by vsidlu** [comment]
i checked your JSON, but it is not what I want.

I need digital output 1 -> 0 -> 1  -> 0 so it imitates two button pushes.

digital output on gpio
1 pulse from high to low close the lock, 
2 pulses from high to low open it…

**Comment by RavenSystem** [comment]
Ahh, now I understand what you want.

`{"c":{"o":1,"l":2,"b":[{"g":0}]},"a":[{"t":4,"0":{"r":[{"g":14,"v":1,"i":1},{"g":14,"i":1.5},{"g":14,"i":0.5}]},"1":{"r":[{"g":14,"i":0.5}]}}]}`

**Comment by vsidlu** [comment]
Thanks! Needed small modification in inching time but now it works - 
{"c":{"o":1,"l":2,"b":[{"g":0}]},"a":[{"t":4,"0":{"r":[{"g":14,"i":0.5},{"g":14,"v":1,"i":0.6},{"g":14,"i":2}]},"1":{"r":[{"g":14,"i":0.5}]}}]}

Thank you for your effort! Now I am heading to search donation button! Have a nice weekend!

**Comment by RavenSystem** [comment]
Many thanks!!
