### ISSUE TITLE
Thermostat cooler problem

### ISSUE THREAD

**Issue by preatavus** [RavenSystem/esp-homekit-devices#779]
I need thermonstats as cooling. I use sonoff basic.
I used the following Json configuration:
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[]},"3":{"r":[]},"4":{"r":[{"g":12,"v":0}]},"5":{"a":0},"t":21,"s":5,"g":14,"b":[],"n":3,"w":2,"m":1,"x":100}]}
unfortunately they don't work, it doesn't control the relay.

when I use this configuration (thermostat heater and cooler):
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"a":0},"3":{"r":[{"g":12,"v":1}]},"4":{"r":[{"g":12,"v":0}]},"5":{"a":0},"t":21,"n":3,"s":5,"x":100,"g":14,"b":[{"g":0}],"m":1,"w":3}]}
heating works, but cooling no longer (I only needs cooler)

what am I doing wrong?

**Comment by RavenSystem** [comment]
You must define actions for cooling, and you are missing action `"2"`: https://github.com/RavenSystem/esp-homekit-devices/wiki/Thermostat#actions

And if you only need cooler, change `"w"` from 3 to 2: https://github.com/RavenSystem/esp-homekit-devices/wiki/Thermostat#thermostat-type
