### ISSUE TITLE
Firmware H801

### ISSUE THREAD

**Issue by kutdenis** [RavenSystem/esp-homekit-devices#792]
When flashing the h801 controller, this is an error. Previously, there were no problems, Calmly filled in the settings and connected to HomeKit. When erasing and flashing the device itself, there are no problems. Only at this stage. The error occurred "unable to load the web page"
![Снимок экрана 2020-02-10 в 15 36 52](https://user-images.githubusercontent.com/734349/74150873-e6e7cb80-4c1b-11ea-86a7-6fe65a2d230b.png)

**Comment by quartist** [comment]
Problem exist on mobile devices or only on mac?

**Comment by kutdenis** [comment]
> Problem exist on mobile devices or only on mac?

Mac(10.15.4), iOS, Ubuntu (20.04)
