### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by quartist** [RavenSystem/esp-homekit-devices#793]
Hi,

could you add support for static IPs?
In first setup when we connect to HAA-device WiFI user shoul be define: ssid, pass, ip, net mask, gw, dns. When ip, net mask, gw, dns are empty then try dhcp client. This options solving dhcp leases expiring time, reduce transfer scope in TCP/IP stack, and helps keep order with IP/device when we have a lot of devices in house.

**Comment by RavenSystem** [comment]
I never have had any issue with DHCP leases expiring time, and using a static IP address for every device is a bad way to manage a network. A better way is using a good DHCP server, and if you want to fix IP address to devices manually, you can use DHCP MAC assignments. But normally, people who want a better control, use custom hostnames and DNS resolution.
