### ISSUE TITLE
esp-wifi-config issues with Safari and iOS12/Mojave (Before: v 0.4.6)

### ISSUE THREAD

**Issue by sercitecotf** [RavenSystem/esp-homekit-devices#80]
buenas tardes
he notado que al instalar la versión 0.4.6 desde cero y después de conectar y al introducir los datos en el portal cautivo, se desconecta la wifi y no puedes terminar el proceso, pero si instalas la v 0.4.3 si que puedes poner los datos y una vez a terminado, esta actualizado a la 0.4.6 y va bien, pero si realizas un master reset no hay manera de poder poner la clave wifi

**Comment by RavenSystem** [comment]
Es un fallo esporádico y aleatorio de la librería wifi-config y da igual la versión que se use. Yo lo he notado desde que actualicé a iOS12/Mojave. La versión 0.4.3 y 0.4.6 no tienen ninguna diferencia al respecto.

**Comment by xtianpaiva** [comment]
Me pasa lo mismo, con Chrome en MacOS Mojave si funciona, con Safari no no permite ingresar la contraseña WiFi. En iOS con Safari, mismo problema.

**Comment by RavenSystem** [comment]
A mí me pasa lo mismo con Safari en iOS12 y Mojave, y repito, da igual la versión del firmware. De hecho, a veces conecta, aparece el portal cautivo, pero se desconecta antes de terminar de escribir todos los datos de configuración.
