### ISSUE TITLE
Shelly 1 HAA 1.6.4 keeps in setup mode

### ISSUE THREAD

**Issue by VincenzoDV** [RavenSystem/esp-homekit-devices#801]
Hello, I've updated to HAA 1.6.4 my shelly 1 via serial, Ota installation.
At the initial setup I put the follow json:
{"c":{"b":[{"g":5,"p":0,"i":1,"t":5}],"n":"dvhouse-domo-bagnogrande-luce"},"a":[{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":5}]}]}
and the result is that it stay in setup mode and never connect to the wifi.
This is pretty strange, the json is the one I use on other Shelly 1 not updated and with 1.5.4 version.
Help!! I'm with no light in the bathroom!

**Comment by RavenSystem** [comment]
Log, please.
