### ISSUE TITLE
Sonoff 433 RF support?

### ISSUE THREAD

**Issue by mitchoklemen** [RavenSystem/esp-homekit-devices#803]
Will be there support for SOnoff 433 RF bridge and also for PIR and window/door sensors?
Thanx, Mitcho

**Comment by DanielSergienko** [comment]
I’m not sure about Rf bridge but PIR & door/window sensors are already supported.

**Comment by RavenSystem** [comment]
> Will be there support for SOnoff 433 RF bridge?

No.

> and also for PIR and window/door sensors?

Actually, both are supported.
