### ISSUE TITLE
Status via http-request?

### ISSUE THREAD

**Issue by michis0806** [RavenSystem/esp-homekit-devices#804]
Hi there,

I didn't find the question answered: I set up a Garage Door opener with this fantastic system. Everything works fine with HomeKit. But is there any chance to get the door-Status via http-request?

Thanks
Michael

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/General-Configuration#Enable-HomeKit-rest-API

**Comment by michis0806** [comment]
Thanks! That's what I was looking for!
