### ISSUE TITLE
"h" action and non existing host

### ISSUE THREAD

**Issue by ymyshko** [RavenSystem/esp-homekit-devices#805]
If the action "h" set a nonexistent host module with HAA is rebooted.
Below is the log when I press GPIO0

Setter ON
DigO GPIO 12 -> 1
HTTP Action http://10.10.14.198:80/cm?cmnd=Power%20ON
Timer Start Failed
Timer Stop Failed
Timer Start Failed
Timer Stop Failed
Timer Start Failed

Then HAA reboot

---------------
My config

{"c":{"l":2,"o":1,"u":1,"b":[{"g":0,"t":5}]},
"a":[
{"0":{"r":[{"g":12}],"h":[{"h":"10.10.14.198","u":"cm?cmnd=Power%20OFF"}]},
"1":{"r":[{"g":12,"v":1}],"h":[{"h":"10.10.14.198","u":"cm?cmnd=Power%20ON"}]},
"b":[{"g":0}]},
{"t":6,"i":10,"f1":[{"g":14}]},
{"t": 1,"1": { "s":[{ "a": 1}]}}
]
}

**Comment by RavenSystem** [comment]
Fixed: https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_1.6.6
