### ISSUE TITLE
Shelly 1 HAA & lock mechanism

### ISSUE THREAD

**Issue by Ni88-dpb** [RavenSystem/esp-homekit-devices#806]
Hello to all. I have a shelly1 with ravencore because I use it as a lock for the gate. How can I configure it with haa? It's the only device I still keep with ravencore because I can't set it ... thanks to anyone who can help me!

**Comment by RavenSystem** [comment]
Please, take screenshots of your RaveCore settings.

**Comment by Ni88-dpb** [comment]
> Please, take screenshots of your RaveCore settings.

Here you are

![2DA37477-96C6-4A3A-B43D-A99E095CBEEE](https://user-images.githubusercontent.com/57964358/74838250-92330780-5323-11ea-88c0-78e240cfceeb.png)


![65E2581B-F111-4B3A-A20B-45F46A726F47](https://user-images.githubusercontent.com/57964358/74838243-8d6e5380-5323-11ea-83bc-f0f74502244c.png)

**Comment by Ni88-dpb** [comment]
Thanks, I managed to set haa as a button and it works, but I can't replicate the lock. on homekit it is important because I ask siri to "open the gate" and if I set the shelly as a standard button, siri does not open it.

**Comment by RavenSystem** [comment]
If you look at https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database there is a Shelly 1 configured as "Lock Mechanism with external push".
