### ISSUE TITLE
How to prevent module to go config mode after 8x push button ?

### ISSUE THREAD

**Issue by homekiciarz** [RavenSystem/esp-homekit-devices#808]
How to prevent module to go config mode after 8x push button ?

I have JSON for sonoff basic.

`{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":22,"g":2,"n":3},{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":3},{"g":3,"t":0}]}]}`

But when i fast click 8x button my module go to configuration mode. How to disable that ?

**Comment by Kienz** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/General-Configuration#Setup-Mode-Toggle-Count

```json
{"c":{"l":13,"b":[{"g":0,"t":5}],"z":0},"a":[{"t":22,"g":2,"n":3},{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":3},{"g":3,"t":0}]}]}
```

**Comment by homekiciarz** [comment]
Thank You.
