### ISSUE TITLE
sonoff dual o t2 touch para persianas

### ISSUE THREAD

**Issue by sercitecotf** [RavenSystem/esp-homekit-devices#82]
se podría usar sonoff t2 para persianas, de tal manera que uno interruptor suba la persiana y otro la baje, configurando un tiempo de subida y uno de bajada? lo ideal en el t2 touch seria que en vez de encender y bajar fuese pulsadores. 
Se puede hacer algo parecido?

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/32

**Comment by RavenSystem** [comment]
In TODO list some time ago:
https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List
