### ISSUE TITLE
Support for Tuya/eWelink 2 Way WiFi Switch

### ISSUE THREAD

**Issue by aleroot** [RavenSystem/esp-homekit-devices#822]
Has anyone tried to use haa with [Tuya/eWelink 2 Way WiFi Switch](https://www.banggood.com/TuyaeWelink-2-Way-WiFi-Switch-Independently-Controls-Smart-Switch-Support-Alexa-Google-Home-p-1615832.html), I wanted to buy one of these but I'm not sure if they may be compatible with this firmware...

Has anyone had any experience with those switches ?

Thanks.

**Comment by seritos** [comment]
There is a list supported devices in the official tuya Github:

https://github.com/ct-Open-Source/tuya-convert/wiki

You can also join to the official chat, there is more people there
