### ISSUE TITLE
JSON string for Sonoff Dual

### ISSUE THREAD

**Issue by Crosss** [RavenSystem/esp-homekit-devices#829]
Does anyone have a working JASON string for Sonoff Dual?
These relays are not controlled via any of GPIO. 
This device has another chip for relay control.
I tryed JSON for 2ch Relay and others, it doesn`t work.
I can`t solve a problem:(

**Comment by tonysprenk** [comment]
It could be that the esp is talking to a secondary mcu through serial commands. Serial commands are not (yet) supported by HAA.

**Comment by xtremedays** [comment]
this works for my dual 

{"c":{"l":13,"b":[{"g":10,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9}]}]}

**Comment by Crosss** [comment]
Thank you!
Unfortunately this string does not switch the relays too.
It just blinks with led when i press icon in HomeKit, but relays still dead:(

**Comment by xtremedays** [comment]
Potentially a faulty dual then? Mines been working on that JSON since day one...

**Comment by teymur1988** [comment]
Hi, 
You might have an old version of sonoff dual, not the R2. In the old version a separate chip is used to control the relays, and that chip gets commands from the ESP chip. HAA works with Sonoff Dual R2. In that version of sonoff the relays are controlled directly by GPIOs of the ESP chip.

**Comment by Crosss** [comment]
Hi! You are right. This device is not vR2.
Will have to use another:(
