### ISSUE TITLE
Change fan icon

### ISSUE THREAD

**Issue by danielhelmstedt** [RavenSystem/esp-homekit-devices#830]
Hi,
Fans using the new HAA implementation do not have the option to change the icon between pedestal, desk and ceiling fan, like they do when using a switch (set to display as fan) or another firmware like Tasmota via Homebridge MQTT Fan.

This is discovered on an iFan03 using @egorist JSON from #165

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_1.8.5
