### ISSUE TITLE
Fan speed in steps rather than %

### ISSUE THREAD

**Issue by danielhelmstedt** [RavenSystem/esp-homekit-devices#831]
Hi, is it possible to have a fan display it’s speed in steps instead of in percentage, when using something like iFan which are 3 steps, or Arlec GridConnect fans (new in Australia) which have 6 steps. 

This used to be done on the Home Assistant homebridge plug-in before homekit got built in to HA (iFan02 via Tasmota just had off,1,2,3 slider in HK), and Hunter fans go up in 25,50,75,100 increments, so i think it is technically possible right?

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_1.8.5
