### ISSUE TITLE
Network local

### ISSUE THREAD

**Issue by Neu59** [RavenSystem/esp-homekit-devices#832]
and installed in my sonoff basic main.bin works very well but only when I am in my local network when I am out does not connect, is there any solution, thanks

**Comment by DanielSergienko** [comment]
You need a Home Hub (Apple TV, HomePod, iPad etc) so you can control it outside your home.

**Comment by Gremore** [comment]
Hi, I have Apple TV 4K as a hub and my garage Sonoff SV doesn’t work remotely. I have other Sonoffs Basic with latest build and no problem with connectivity. Being connected to one of AP in my network it works fine. I have installed AP inside garage to be sure of good signal.
