### ISSUE TITLE
MagicHome Led Strip Controller 

### ISSUE THREAD

**Issue by stefantitu** [RavenSystem/esp-homekit-devices#836]
Today I flashed one led strip controller from magic home. The flash was a success but after I connect to the WiFi network and save the json config I can not see any new accessory in home app. 
What I noticed is that the WiFi network (HAA-a10df8) keeps appearing among the WiFi networks and if I try to connect again it fails.
I reflashed it for 3-4 times but the same issue appeared.
I used this config : {"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":14,"g":5,"v":12,"w":13,"b":[{"g":0}]}]}

All my Sonoff were flashed this way and I had no issues connecting them.  
Any ideas?

**Comment by brymonster** [comment]
If there’s an issue with that JSON your device will continue booting into setup mode.
What magic home are u using?

**Comment by stefantitu** [comment]
![image](https://user-images.githubusercontent.com/40542317/76160147-3e505d00-6130-11ea-9994-f0c94dd0302f.jpg)

**Comment by stefantitu** [comment]
I tried to figure out if there is any mistake in the json code but I don’t find it. I also change the GPIO numbers according to the esp module.

**Comment by RavenSystem** [comment]
Logs, please.

**Comment by stefantitu** [comment]
> Logs, please.
I not an expert and I don't know where to find the logs, but if you tell me then I paste them here.

**Comment by tonysprenk** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Build-Instructions

**Comment by stefantitu** [comment]
[screenlog.txt](https://github.com/RavenSystem/esp-homekit-devices/files/4303140/screenlog.txt)
this is the log. thank you

**Comment by RavenSystem** [comment]
You are using an old version of haaboot.bin.

**Comment by stefantitu** [comment]
Where do I find a newer version?
