### ISSUE TITLE
Sensor de Movimiento DW1

### ISSUE THREAD

**Issue by STijeras91** [RavenSystem/esp-homekit-devices#84]
Buenas! Ante todo muchísimas gracias por compartir este pedazo de curro, he instalado en todos mis sonoff’s y funcionando perfecto. Ahora mi pregunta es, ¿Existe alguna manera de hacer compatible el sensor de movimiento y apertura de puertas y ventanas? Con actualizacion del estado. Y perdona mi ignorancia xq no se muy bien como funcionan estos dos sensores, si son independientes o solo a través del bridge de Sonoff. 

Muchísimas gracias

**Comment by RavenSystem** [comment]
Pues no tengo ni idea. De hecho, desconocía la existencia de esos sensores. Tendré que mirarlo.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/119
