### ISSUE TITLE
Configuring HAA devices through EVE app

### ISSUE THREAD

**Issue by frazer81** [RavenSystem/esp-homekit-devices#841]
Hi all,
I realised i've raised questions to a case that has been closed.
Upgrade from RavenCore to HAA #686
https://github.com/RavenSystem/esp-homekit-devices/issues/686
How do I configure HAA devices through the EVE app as described in the case in the link above?
Really appreciate your assistance!
Sean

**Comment by nov-** [comment]
Same question :) Any guides/tutorials?

**Comment by xrust83** [comment]
HAA cannot be disordered in Eve. HAA is configured only through JSON string
https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database
https://glumb.github.io/haa-configurator/

**Comment by frazer81** [comment]
Thanks @xrust83 - appreciate the guidance!!
