### ISSUE TITLE
how to flash Sonoff mini with DIY tool 

### ISSUE THREAD

**Issue by mitchoklemen** [RavenSystem/esp-homekit-devices#846]
How to flash Sonoff mini with DIY tool over wifi with ESP homekit? howto flash all 3 bin files? haaboot.bin, rboot.bin and blank_config.bin.
Or is there any .BIN file that combines all 3?
Any video to watch?
Thanx, Mitcho

**Comment by hillaliy** [comment]
truncate -s 4k rboot.bin
truncate -s 4k blank_config.bin
cat rboot.bin blank_config.bin haaboot.bin > thirdparty.bin

**Comment by ymyshko** [comment]
I tried.
DIY tool write "..firmware must be less 506kb..." and don't  flash.
Only soldering? :(

**Comment by RavenSystem** [comment]
What is the size of your file?

**Comment by mitchoklemen** [comment]
Raven... can U do that BIN file that can be flashed with DIY tool?
That would be great. Thanx for Your work!

**Comment by RavenSystem** [comment]
See comment: https://github.com/RavenSystem/esp-homekit-devices/issues/846#issuecomment-598875071

**Comment by rispie** [comment]
I tried this earlier today using these instructions: https://blog.bilka.sk/how-to-flash-sonoff-mini-in-mac-os/ and the comment above. All seem to went fine, however I don't see a HAA- AP. So I guess something went wrong. I also read some other issues and comments and there it was mentioned that DIY mode was not supported. So I was wondering if it's supported and if so what did I do wrong?

**Comment by ymyshko** [comment]
> What is the size of your file?

420k

**Comment by ymyshko** [comment]
I flashed tasmota early. But there is spesial version tasmota to flash sonoff mini thru DIY mode.
tasmota-wifiman.bin 477k
We can't to flash tasmota-minimal 380k

**Comment by xrust83** [comment]
> so, it's now possible to flash HAA using this method?
> 
> 1. SONOFF DIY-> TASMOTA
> 2. TASMOTA -> HAA
>    if the answer is yes, @RavenSystem can pin this issue?!

https://www.youtube.com/watch?v=q3sY5w66qeY
