### ISSUE TITLE
Show as single/separate tile

### ISSUE THREAD

**Issue by pllb** [RavenSystem/esp-homekit-devices#847]
Is there's a way to show multiple accessories as a single tile ? By default HomeKit is presenting a single tile with the possibility to ungroup those accessories
![home-app-separate-tiles-option](https://user-images.githubusercontent.com/61800462/76545588-586ca100-648a-11ea-8459-1fb6e7151da5.jpg)

**Comment by egorist** [comment]
https://github.com/RavenSystem/esp-homekit-devices/issues/685

It’s impossible 😟
