### ISSUE TITLE
Sonoff S55 Support

### ISSUE THREAD

**Issue by buarle** [RavenSystem/esp-homekit-devices#849]
Hi and thanks for this awesome work.

Could you please let me know, if it's possible to flash a Sonoff s55 with your software?
Would be really nice to use this outdoor (IP55) outlet via Homekit.

Thanks a lot and BR!
Buarle

**Comment by buarle** [comment]
It's build with an ESP8285.
Some information to this device:
https://fccid.io/2APN5-S55/Internal-Photos/Int-Photos-4013503

**Comment by stefantitu** [comment]
I flashed a magichome led strip controller that has esp8285, and it works ok. So it should also work on sonoff s55

**Comment by buarle** [comment]
I ordered one and will tell you the result!

**Comment by Bogdis** [comment]
> I ordered one and will tell you the result!
Hi, did you manage to flash the outlet? If so can you tell me how you did it?
Thanks
