### ISSUE TITLE
sonoff POW problem

### ISSUE THREAD

**Issue by sangkooki** [RavenSystem/esp-homekit-devices#85]
Hi,

Thank you for this project.

I have some sonoff POW.

It's working well until 0.4.6

Updating 0.4.7 then it's On & Off infinitely.

On, some seconds, Off, some seconds, On, some seconds, Off..........

**Comment by RavenSystem** [comment]
0.4.6 was ok?

**Comment by sangkooki** [comment]
yes. 0.4.6  works fine.

**Comment by RavenSystem** [comment]
What is your GPIO14 toggle status in setup?

**Comment by sangkooki** [comment]
it’s off

**Comment by RavenSystem** [comment]
Can you set it to ON and test?

**Comment by sangkooki** [comment]
I had a test when gpio is on. but result is same.

**Comment by sangkooki** [comment]
thank you for your efforts

**Comment by RavenSystem** [comment]
Try 0.4.8.

**Comment by sangkooki** [comment]
wow, it’s perfect. thank you so much.

**Comment by seritos** [comment]
I have a doubt regarding the pow version. Is it possible to see the consumption from the Eve app? 
I understean this would work as a basic switch in homekit, but i dont know about the W in Eve.

Thanx!
