### ISSUE TITLE
Window cover force close/open on toggle switch press

### ISSUE THREAD

**Issue by Kienz** [RavenSystem/esp-homekit-devices#852]
Sometimes my window covers are not fully opened/closed (the open/close time is set correctly). It would be nice to force open/close on toggle switch press.

**Comment by WojtekWro** [comment]
May I ask which device do you use?

**Comment by Kienz** [comment]
Shelly 2.5

**Comment by Kienz** [comment]
@RavenSystem Any comment? I think it would be helpful to force open/close the roller shutter if closing/opening doesn't work normal. And it has no effect to roller shutter motors with limit switch.
