### ISSUE TITLE
Compile main.bin and OTA main.bin

### ISSUE THREAD

**Issue by wwns** [RavenSystem/esp-homekit-devices#854]
Hi
I have small question, when i'm compile main.bin have different size 505 KB.
How you compile main.bin, for ota haa have the same size (main.bin and ha eboot.bin 402 KB).?

**Comment by RavenSystem** [comment]
505KB main.bin is from HAA.
402KB main.bin and haaboot.bin are from OTA.

**Comment by wwns** [comment]
main and haaboot have the same size for ota, when I compared them in hexeditor, I noticed differences.
How to compile main.bin 402 kb
haa - C devices / HAA 502 kb
with haa_lcm make -C devices / HAA_LCM 402 kb only haaboot.bin
how to make main.bin 402 kb
sorry for my english i know it's poor.
