### ISSUE TITLE
Add HAA to Home Assistant not possible

### ISSUE THREAD

**Issue by URBANsUNITED** [RavenSystem/esp-homekit-devices#855]
Hi!

I have 1.7 and 1.86 devices which worker earlier fine with home assistant.
Now I started all new and HA doesn't recorgnizes my Sonoff Basics at all.
Other devices like my Sony TV are recorgnized fine.

Yes, I've resetted my Homekit ID from the setup menu.

Looks like a HAA problem.

Can you please help? 

Thanks
URBANsUNITED

**Comment by Manelvallsvila** [comment]
Hi have the same problem.

All new devices with OTA 2.2.2 or earlier releases like 1.7.0 don't pair

Followed instructions:

1. Enter Setup Mode on the device
2. Remove your device from the Home App
3. Select Reset HomeKit ID
4. Select Save
5. Pair the device with your Home App again

But it's still not possible to pair.

Any help?

Thankyou
