### ISSUE TITLE
Special Template for 2 Motion Sensors with a Shelly 2.5

### ISSUE THREAD

**Issue by Hanimaniac** [RavenSystem/esp-homekit-devices#856]
Hello Community,

I use the HAA System and it‘s awsome. I also made my own Templates but for my next Project i‘m not fit enough. 
Is it possible to use a Shelly 2.5 as „2“ Motion Sensors? So that each Sensor triggers at one Switch input?
![B7AE49E0-275E-4987-903A-B7CD8C3B0D83](https://user-images.githubusercontent.com/45320732/77257636-e3614e80-6c75-11ea-975c-f37bfd2182c7.jpeg)

Like in my sketch I‘d like to use 2 230V Sensors which trigger the Shelly and in Homekit it should attach as 2 Motionsensors. 
I hope you can help me. 
Greetings from Germany. 
Hanimaniac

**Comment by Kienz** [comment]
```json
{"c":{"l":0,"b":[{"g":2,"t":5}]},"a":[{"t":12,"i":10,"f1":[{"g":5,"p":0,"i":1,"t":0}],"s":0},{"t":12,"i":10,"f1":[{"g":13,"p":0,"i":1,"t":0}],"s":0},{"1":{"s":[{"a":1}]}},{"1":{"s":[{"a":2}]}}]}
```
Two motions sensors and two virtual switches to enter setup mode and start ota-update.
I've tested multiple PIR sensors - for me only the one mentioned in #741 are working.

**Comment by Hanimaniac** [comment]
Thanks for your fast Answer. I‘ll test it soon.

**Comment by Kienz** [comment]
@Hanimaniac Does it work?

**Comment by Hanimaniac** [comment]
Sorry, I forgot to report 🙈
It works perfectly with my two pir Sensor.
I use these:
 https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.de%2Fulk%2Fitm%2F123703914364
Thank you

**Comment by Hanimaniac** [comment]
@Kienz 
Can I contact you pm?

**Comment by Kienz** [comment]
> @Kienz
> Can I contact you pm?

Yes.
Twitter @kienzle_s

**Comment by Hanimaniac** [comment]
Ich hab kein Twitter 🙈

Von meinem iPhone gesendet

**Comment by Kienz** [comment]
@Hanimaniac How can I help you?

**Comment by Hanimaniac** [comment]
It‘s off topic. 
I use ca. 20 haa/ ravencore device in my wifi. 
I have a Fritzbox 6591 wit a fritz repeater. 
Fron time to time i have no response from my devices. completly random. no specific typ. its shelly 1 Shelly 2.5 and Magic Home LED Controller. 
So my automations sometimes dont work because a device is not responding. 
I‘d like to ask you about your wifi settings and if you may have simillar problems.

Am 20.04.2020 um 22:34 schrieb Stefan Kienzle <notifications@github.com>:

**Comment by Kienz** [comment]
I'm using UniFi APs and have this issues if the device connects to a poor AP. Since I select a fix AP in HAA wifi config I don't have issues. Currently I'm using 18 HAA devices (Shelly 1, Shelly 2.5 and Blitzwolf BW-LT21).

**Comment by Hanimaniac** [comment]
ok. thanks for your answer.
