### ISSUE TITLE
Shelly 1 toggle with pushbutton

### ISSUE THREAD

**Issue by peterduyts** [RavenSystem/esp-homekit-devices#858]
Like the title says : is it possible to use an external pushbutton to toggle the relay in a Shelley 1 ? 
just push -> on -> push -> off -> push -> on ... etc

**Comment by Kienz** [comment]
```json
{"a":[{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"s":5,"b":[{"g":5,"p":0},{"g":5,"t":0}]},{"1":{"s":[{"a":1}]}},{"1":{"s":[{"a":2}]}}]}
```
External toggle button with virtual switches for enter setup-mode and start ota-update.

Enter setup-mode and start ota-update:
```json
{"1":{"s":[{"a":1}]}},{"1":{"s":[{"a":2}]}}
```

**Comment by peterduyts** [comment]
Thank you !

**Comment by Kienz** [comment]
@peterduyts Does it work?

**Comment by peterduyts** [comment]
Well, I'm in lockdown now and don't have access to the Shelly things here  :/
