### ISSUE TITLE
Sonoff does not show temperatures below 0 Celsius

### ISSUE THREAD

**Issue by Codi878** [RavenSystem/esp-homekit-devices#86]
Hi Jose,

I have a problem with the device type 6. Sonoff TH is placed outside and measures temperature and humidity and controls the lighting outside. Everything worked great until the temperature dropped below 0 degrees Celsius. 
Attached are some photos of how it looks in the application. Firmware version 3.4

Best Regards

![img_1441](https://user-images.githubusercontent.com/42392107/48658527-b8dd0100-ea43-11e8-9bda-caedb88f457f.jpg)
![img_1439](https://user-images.githubusercontent.com/42392107/48658528-b8dd0100-ea43-11e8-84e2-5ee1015bb8c1.jpg)
![img_1440](https://user-images.githubusercontent.com/42392107/48658529-b8dd0100-ea43-11e8-8d86-446b4b544b43.jpg)

**Comment by RavenSystem** [comment]
Yes, it's annoying. Official Apple HomeKit Protocol set Temperature between 0 and 100, as you can see in this document: 
https://developer.apple.com/homekit/specification/

Here is a thread about this matter: https://github.com/KhaosT/HAP-NodeJS/issues/147

I'm going to set minimum temperature to -100, ignoring Apple specifications.

**Comment by RavenSystem** [comment]
Update to version 0.4.9, please.

**Comment by Codi878** [comment]
Hi Jose

On 4.9 firmware everything works fine :) Thank You for your quick fix.

![img_1456](https://user-images.githubusercontent.com/42392107/48675335-eca94b00-eb57-11e8-86b4-d2335b94ea7a.jpg)

**Comment by RavenSystem** [comment]
Thanks to you for your feedback.
