### ISSUE TITLE
iFan03 433mhz remote not working

### ISSUE THREAD

**Issue by Codkit** [RavenSystem/esp-homekit-devices#860]
Hi all

Anyone possible to teach me how to make it work ? Thank you.

**Comment by pilot1981** [comment]
also me interested...you are using it with sonoff basic RF R3?

**Comment by Codkit** [comment]
hi
I mean the original RF remote with iFan03

**Comment by hillaliy** [comment]
To pair the remote control, hold down any button on the remote control and apply power to the iFan03. Once the device boots up you should hear a series of clicks as the internal relays operate. Once completed you can test the remote and it should all be operational.

**Comment by Codkit** [comment]
Hi
It doesn’t work after flashing the firmware

**Comment by hillaliy** [comment]
it's work after tasmota flash

**Comment by fiska1** [comment]
Hello.  I have the same problem.  The remote does not work.  Has anyone made it work after firmware?

**Comment by Jeroen207** [comment]
So, the remote seems to work with some people here?

**Comment by 400HPMustang** [comment]
I'm also interested in how to get the remote working. I flashed an iFan03 and cannot get the remote to work.

**Comment by RavenSystem** [comment]
iFan03 remote will no be supported soon.
