### ISSUE TITLE
Shelly Plug S Json

### ISSUE THREAD

**Issue by OnKram** [RavenSystem/esp-homekit-devices#862]
Hi all,
I have trouble with Json for Shelly Plug S. 
If I connect device to Home App so it works fine, but manual switch not working.
I used GPIO pins from this page: https://templates.blakadder.com/shelly_plug_S.html and I also try others pins but still not working it.

Any idea please?
{"c":{"l":0,"b":[{"g":13,"t":5}]},"a":[{"0":{"r":[{"g":15},{"g":2,"v":1}]},"1":{"r":[{"g":15,"v":1},{"g":2,"v":0}]},"t":2,"b":[{"g":13,"t":1,"i":0,"p":0}],"s":0}]}

**Comment by RavenSystem** [comment]
"i":0,"p":0 must be set at the first declaration of GPIO to be used. Try moving them.

**Comment by OnKram** [comment]
Ok, I tried this setup, but still not working.

{"c":{"l":0,"b":[{"g":13,"t":5,"i":0,"p":0}]},"a":[{"0":{"r":[{"g":15},{"g":2,"v":1}]},"1":{"r":[{"g":15,"v":1},{"g":2,"v":0}]},"t":2,"b":[{"g":13,"t":1}],"s":0}]}
