### ISSUE TITLE
OTA

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#868]
Hello my english is bad and i can't figure out exactly how to compile the three files into one to flash the firmware using tuya convert.  can i flash haa main.bin file without LCM with tuya convert

**Comment by wwns** [comment]
hexeditor

**Comment by tonysprenk** [comment]
https://github.com/ct-Open-Source/tuya-convert/wiki/Flash-a-multipart-binary

**Comment by Kristian8606** [comment]
Thanks the problem is that when I place a bin file in the directory and start the flashing procedure, the bin file cannot be selected just doesn't show

**Comment by tonysprenk** [comment]
Are you sure you put it in the right directory?

**Comment by Kristian8606** [comment]
Directory /files

**Comment by tonysprenk** [comment]
Hmm it should work than. Maybe open an issue on the tuya-convert repo.

**Comment by Kristian8606** [comment]
i suspect that bin is wrong someone can give me bin

**Comment by Kristian8606** [comment]
https://github.com/Kristian8606/LED_Strip/releases/download/4.0.2/thirdparty.bin

the problem was in the bin file. I was able to build working with the last version of HAA
