### ISSUE TITLE
iFan03-It doesn't work correctly

### ISSUE THREAD

**Issue by fiska1** [RavenSystem/esp-homekit-devices#869]
Hello. After firmware and JSON installation from the database, the fan does not work correctly. At 33% - the maximum speed, at 100 %-the minimum. How do I fix it ?
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":65,"e":3,"0":{"r":[{"g":15},{"g":12},{"g":14}]},"y0":[{"v":1,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]}},{"v":2,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]}},{"v":3,"0":{"r":[{"g":15,"v":1},{"g":4},{"g":14}]}}]},{"1":{"r":[{"g":9}]},"0":{"r":[{"g":9,"v":1}]},"b":[{"g":0}]}]}

**Comment by RavenSystem** [comment]
Try this and comment results, please:

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":65,"e":3,"0":{"r":[{"g":15},{"g":12},{"g":14}]},"y0":[{"v":3,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]}},{"v":2,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]}},{"v":1,"0":{"r":[{"g":15,"v":1},{"g":4},{"g":14}]}}]},{"1":{"r":[{"g":9}]},"0":{"r":[{"g":9,"v":1}]},"b":[{"g":0}]}]}

**Comment by fiska1** [comment]
Thanks, now it works correctly. I don't use it for ceiling fans, but for exhaust fans.Can't the code fix the speed? 100% rotates very strongly (non-standard).. Without the iFan 03 device the maximum rpm is 67%

**Comment by Partizan7676** [comment]
@fiska1 does RF-remote works too? when you use it is status changed in home app ???

**Comment by fiska1** [comment]
No.  The remote does not work.

**Comment by Gwyki** [comment]
Apologies for jumping into this issue, but I don't think a new one is warranted for my questions...

@RavenSystem Can you provide a quick bit of documentation for these settings here? The small hint in the release notes doesn't cover the accessory specific action variables like the "i" here?

Should home app be displaying this as a continuous bar, or the segmented switch? I am getting a continuous slider...

**Comment by Jeroen207** [comment]
Is it possible to add RF remote capability with json?

**Comment by i3laze** [comment]
> Apologies for jumping into this issue, but I don't think a new one is warranted for my questions...
> 
> @RavenSystem Can you provide a quick bit of documentation for these settings here? The small hint in the release notes doesn't cover the accessory specific action variables like the "i" here?
> 
> Should home app be displaying this as a continuous bar, or the segmented switch? I am getting a continuous slider...

@Gwyki , Wiki is at your disposal:
https://github.com/RavenSystem/esp-homekit-devices/wiki/Fan

**Comment by bj-tracer** [comment]
Hello!
Can it control with external buttons?

**Comment by brymonster** [comment]
@fiska1 did u get the ifan03 working with an external wired switch?
