### ISSUE TITLE
Implement Outlet type for device type 1 (Before: Implement Outlet type in homekit)

### ISSUE THREAD

**Issue by rechin304** [RavenSystem/esp-homekit-devices#87]
Dear Raven,

I have a suggestion for Sonoff Basic. Can be implemented Outlet type display in homekit ?
For example the Sonoff basic or TH can be used behind a socket wall and power on or off the wall socket.

**Comment by RavenSystem** [comment]
Outlet is used for device type 3.

**Comment by rechin304** [comment]
I see, but additional button is added and that is not necessary all the time.

**Comment by RavenSystem** [comment]
Yes, for now it is the only workaround.

**Comment by RavenSystem** [comment]
This will be only a cosmetic custom option. I prefer to save RAM and flash to use in other purposes.
