### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#870]
Is it possible to add support for this bulb
Flashing successfully with tuya convert

![57A55ACD-B230-4947-94CF-98299D614B9D](https://user-images.githubusercontent.com/34716572/78356098-9d7e8180-75b7-11ea-92f4-4a76b4c2f60e.jpeg)
![FA93258F-8A90-4492-BFAF-FCBB77370CC6](https://user-images.githubusercontent.com/34716572/78356102-9eafae80-75b7-11ea-86b6-22fe009f42f5.jpeg)
![40666911-571B-4916-A980-26098DB1F8E2](https://user-images.githubusercontent.com/34716572/78356103-9f484500-75b7-11ea-856e-71a5d83f6c77.jpeg)
![C375474C-C068-4846-9525-EE63F0270FDC](https://user-images.githubusercontent.com/34716572/78356106-9fe0db80-75b7-11ea-8e0b-b9a1c361fb9f.jpeg)

**Comment by tonysprenk** [comment]
The chip is covered by the white glue so it’s impossible to see if it’s ESP based. Easiest way to find out is to google the MAC adres of the device. It will tell you who the manufacturer of the chip is. Post the results when you have them.

**Comment by tonysprenk** [comment]
Looking at the pictures it looks like this is not an ESP chip but rather a newer chip that tuya has been putting into their devices. It’s based around an ARM micro controller. But to know for sure google the Mac adres or remove the glue and share a picture.

**Comment by Kristian8606** [comment]
The chip is esp8266 I managed to flash it HAA

**Comment by tonysprenk** [comment]
Oh ok that’s good! Try this json: 

```

{"c":{"b":[{"g":0}]},"a":[{"t":30,"r":14,"g":12,"v":13,"w":4,"fr":4,"fg":4,"fv":4}]}

```

It’s from the device database innige wiki.

**Comment by Kristian8606** [comment]
Did not work. I don't understand how this json works but as far as i understand esp manages this driver through sda clk pins

**Comment by Kristian8606** [comment]
uses pin 4 and 14 of esp which are connected to the led driver

**Comment by tonysprenk** [comment]
So it sends serial commands to a secondary micro controller? This feature is not yet enabled in HAA but @RavenSystem is working on it.

**Comment by Kristian8606** [comment]
https://git.koehlerweb.org/frodovdr/Sonoff-Tasmota/src/commit/6997626077c18b11f2c2e672b9ba8e88f37c9046/sonoff/xdrv_26_sm2135.ino
