### ISSUE TITLE
JSON readability suggestion

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#871]
As @RavenSystem told million times there's little space in the Flash to store all the "Relay" "Accessory" and other Words of the JSON config, that is why shortened "l","e","t","t","e","r","s" were introduced.

Every time once a year when I try to reconfig HAA, I'm down for an hour into Wiki.
It's always hard for me to decipher JSON, and https://glumb.github.io/haa-configurator/ barely helps.

**Suggestion:**
Please, introduce an alternate JSON view (some checkbox on HAA Setup webpage) with words exploded to "Accessory", "Type", "Relay" and then strip them on the fly back to "a","t","r" when saving to flash.
I believe such two-way replace code for Setup page will be dozen lines long.

Example - empty accessory:
`{"c":{},"a":[]}`
Same example with explode checkbox On:
`{"Config":{},"Accessory":[]}`

As your JSON input field is too narrow I cross-posted a suggestion here:
https://github.com/glumb/haa-configurator/issues/8

**Comment by i3laze** [comment]
Just an illustration of Config Readability:
![Screenshot at Apr 04 21-01-16](https://user-images.githubusercontent.com/16850291/78458085-81620980-76b7-11ea-90fa-7c3980a3090c.png)
RavenCore << Tasmota << HAA

**Comment by freddair** [comment]
+1 for this!

**Comment by RavenSystem** [comment]
JSON is as it because memory and storage are very important. You can use a simple find and replace to create your own tool.

**Comment by beren12** [comment]
It would be nice to have the ability to switch back and forth though, feed the tool one and it spits out the other :)
