### ISSUE TITLE
HAA Installer initial Config

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#873]
When you flash the device and connect to HAA-setup-SSID for the first time, you get a captive portal popup with HAA **Installer** webpage, this one:

![](https://raw.githubusercontent.com/RavenSystem/ravensystem-media/master/OTA_config.jpeg)

As it is quite easy to setup a WiFi there it is almost impossible to input any JSON config right in the captive popup, unless you copy it beforehand or from the second iOS device (Universal Clipboard).

Then it takes up to 10 min to get from HAA Installer to fully downloaded & flashed HAA running. However it is *mandatory to input a config in advance, which is odd.

I suggest adding an empty accessory as an initial startup JSON Config:
`{"c":{},"a":[]}`
or a config with Setup-mode switch:
`{"c":{},"a":[{"1":{"s":[{"a":1}]},"b":[],"s":0}]}`
or similarly booting into Setup mode, if JSON input was empty.

**Comment by RavenSystem** [comment]
When JSON is empty or not valid, device entera automatically in setup mode.
