### ISSUE TITLE
problem on captive portal of HAA

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#874]
Hi,
using Mac OSX 10.15.4 and Safari 13.1 I have this error on captive portal during installation:

<img width="903" alt="Schermata 2020-04-06 alle 00 06 41" src="https://user-images.githubusercontent.com/46350465/78511393-96fd2f00-779c-11ea-8607-78e30659a4b9.png">

any idea?

**Comment by Kienz** [comment]
This problem is fixed with latest version - see #866.

**Comment by pilot1981** [comment]
So, I have to download lastest haaboot.bin?

**Comment by Kienz** [comment]
Yes.

**Comment by pilot1981** [comment]
Very strange, it worked fine 5 minutes before for another Shelly 2.5...

**Comment by pilot1981** [comment]
ok, solved.
thanks
