### ISSUE TITLE
Shelly 2.5 Step by Step Relay

### ISSUE THREAD

**Issue by milonet** [RavenSystem/esp-homekit-devices#876]
Hi, it's possible to make a step by step relay with haa latest firmware on shelly 2.5? Do you have a json?

best regards

**Comment by kx3kx3kx3** [comment]
try this:
{"c":{"l":0,"i":1},"a":[{"s":5,"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":5,"p":0,"i":1}]},{"s":5,"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":13,"p":0,"i":1}]}]}

**Comment by milonet** [comment]
Hi, thank you but it's not working. Work normally as two
separate switch/outleet.
I need
- First press on input1 -> Outlet 1 On
- Second press -> Outlet 1 OFF, Outlet 2 ON
- Third press -> Outlet 1 On, Outlet 2 On
- Fourth press -> Outlet 1 OFF, Outlet 2 OFF

Like as step by step Relay

Thansk

Il giorno lun 6 apr 2020 alle ore 09:50 kx3kx3kx3 <notifications@github.com>
ha scritto:

**Comment by kx3kx3kx3** [comment]
> Hi, thank you but it's not working. Work normally as two separate switch/outleet. I need - First press on input1 -> Outlet 1 On - Second press -> Outlet 1 OFF, Outlet 2 ON - Third press -> Outlet 1 On, Outlet 2 On - Fourth press -> Outlet 1 OFF, Outlet 2 OFF Like as step by step Relay Thansk Il giorno lun 6 apr 2020 alle ore 09:50 kx3kx3kx3 <notifications@github.com> ha scritto:
> […](#)

On home app or on a physical button?

**Comment by milonet** [comment]
On physical button

Il giorno lun 6 apr 2020 alle ore 13:44 kx3kx3kx3 <notifications@github.com>
ha scritto:

**Comment by kx3kx3kx3** [comment]
try this one  : 
{"c":{"l":0,"b":[{"g":2,"t":5}]},"a":[{"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":5,"p":0,"i":1,"t":0}]},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":13,"p":0,"i":1,"t":0}]}]}
 
and let me know

**Comment by milonet** [comment]
thank you but it's still not working.. the switch/outles works independently

best regards

Il giorno gio 9 apr 2020 alle ore 16:09 kx3kx3kx3 <notifications@github.com>
ha scritto:

**Comment by kx3kx3kx3** [comment]
if you want to try another json for shelly 2.5
{"c":{"l":0,"b":[{"g":2,"p":0,"t":5}]},"a":[{"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":5,"p":0},{"g":5,"t":0}],"s":0},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":13,"p":0},{"g":13,"t":0} ],"s":0}]}

**Comment by milonet** [comment]
it's not working. with this configuration the outlets not keeping the state. when release the physical button the outlets goes off
