### ISSUE TITLE
Shelly 1 with temperature sensor?

### ISSUE THREAD

**Issue by morphix9** [RavenSystem/esp-homekit-devices#878]
Hey guys, 

is anyone of you using temperature sensors with a Shelly 1?
Could you share the JSON and explain the wiring? Which sensors do you use?

Do you need the add-on from Shelly or could you wire it directly?
https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#313

Thanks for your help

**Comment by Quoshak** [comment]
I am also interested. I have Shelly temperature addon and DS18B20 sensor. And chance to make this work?
