### ISSUE TITLE
Ravencore to HAA full copy of external button functions

### ISSUE THREAD

**Issue by xrust83** [RavenSystem/esp-homekit-devices#879]
help configure sonoff dual with HAA firmware to work like ravencore
![076A06B3-4746-406A-A040-ACB9498FDD5F](https://user-images.githubusercontent.com/58448955/78921619-d7f78b00-7a9d-11ea-8a9b-e1c21cd2648e.jpeg)

**Comment by RavenSystem** [comment]
`{"c":{"l":13,"b":[{"g":10,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0},{"g":0,"t":0}]},{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g":9},{"g":9,"t":0}]}]}`

**Comment by xrust83** [comment]
It works. Thanks = -D. Will I be able to update all the switches by air or will I have to remove them from the ceiling? I already compared both codes in the editor https://glumb.github.io/haa-configurator/ and figured out how to install it
