### ISSUE TITLE
Sonoff D1 (ESP8285)

### ISSUE THREAD

**Issue by Jeroen207** [RavenSystem/esp-homekit-devices#881]
Hi!

I was wondering if the ESP8285 chip is supported as well? I'm looking for a library which support this chip. So far I have seen is that the Sonoff D1 dimmer uses this chip and I would really like to convert it to a homekit accessory.

**Comment by RavenSystem** [comment]
ESP8285 is an ESP8266 with integrated flash chip, then ESP8285 is supported, but I think Sonoff D1 uses serial output to manage colors, and that feature is not supported yet by HAA.

**Comment by Jeroen207** [comment]
Allright, 

What do you mean specifically by colors? I thought the Sonoff D1 only dims the light
