### ISSUE TITLE
Garage door opener Eachen GD-DC5

### ISSUE THREAD

**Issue by mientki** [RavenSystem/esp-homekit-devices#884]
I bought an interesting and well-made device for opening the garage door on AliExpress.  has 1 opening sensor.  all accessories to facilitate assembly.  has ewelink software.  I changed soft to HAA but I have a problem with JSON configuration.  I have no idea what are the gpio of the relay, sensor, button and LED.  did any of you have experience with this device and help?  this can be found on the internet under the name EACHEN GD-DC5.  Will this device work with HAA?  on the motherboard I see 2 connectors for flashing.  the other is labeled MCU.  what is this?
![0D778CED-5BEA-4660-BAFD-21EDA2D9428E](https://user-images.githubusercontent.com/37380727/79070385-cd273b00-7cd5-11ea-88ab-5a987579f110.jpeg)
![9D1D7FA9-A811-49F6-8C9D-727E2558CFA7](https://user-images.githubusercontent.com/37380727/79070389-d2848580-7cd5-11ea-8ca0-5f97a5a4f350.jpeg)
![F9BF9A99-7D6F-4BEE-BAD0-7C476ABF05D2](https://user-images.githubusercontent.com/37380727/79070391-d44e4900-7cd5-11ea-9bed-af163864790d.jpeg)

**Comment by tonysprenk** [comment]
Looks like this device might communicate through serial commands with a secondary micro controller. This is not yet supported by HAA but @ravensystem has confirmed that it will be in an upcoming release.

**Comment by mientki** [comment]
will you need to reprogram 2 systems separately?  how does such a device work?

**Comment by tonysprenk** [comment]
No the esp chip sends serial commands to the second controller telling it what to do.

**Comment by wwns** [comment]
[Here's a sample code](https://github.com/doleron/esp8266-1-channel-relay-board-with-mqtt)

`void setup() {
  Serial.begin(9600);
}

void loop() {
  byte close[] = {0xA0, 0x01, 0x01, 0xA2};
  Serial.write(close, sizeof(close)); 
  delay(2000); 
  
  byte open[] = {0xA0, 0x01, 0x00, 0xA1};
  Serial.write(open, sizeof(open)); 
  delay(2000);      
} `

**Comment by Thiso6** [comment]
Hi, I successfully flashed tasmota by using the 4 pins (VDD, GND, RX, TX) of the WIFI part (not MCU). I'm now trying to configure it properly

**Comment by Be2daErtin** [comment]
> Hi, I successfully flashed tasmota by using the 4 pins (VDD, GND, RX, TX) of the WIFI part (not MCU). I'm now trying to configure it properly

Hi, Did you manage to get it working?

**Comment by Thiso6** [comment]
Yes it is working properly. The problem is that the microcontroller unit (MCU) is in conflict with the tasmota control. That caused it to keep toggling. The solution is to remove the MCU and the solder some bypass wires. It is running perfectly now. I followed this thread: https://community.home-assistant.io/t/gd-dc5-tasmota-ha/149245/22

**Comment by gogreenpower** [comment]
> Hi, I successfully flashed tasmota by using the 4 pins (VDD, GND, RX, TX) of the WIFI part (not MCU). I'm now trying to configure it properly

Any idea how to access those 4 pins on this style of board?

![20210219_093936](https://user-images.githubusercontent.com/9656919/108446699-80b76f00-7299-11eb-832a-340aeaa61da7.jpg)
