### ISSUE TITLE
MagicHome RGBW + IR remote control and HAA

### ISSUE THREAD

**Issue by topzoe** [RavenSystem/esp-homekit-devices#886]
Hi,
I want flash a MagicHome RGBW+IR remote (like this:https://templates.blakadder.com/magichome_ZJ-WFMN-A_RGBW.html)

Question: is it possible to keep the IR fonctionality with the IR remote control?
If yes, did someone have HAA Json exemple?
GPIO04 = IRrecv
GPIO05 = PWM2
GPIO12 = PWM1
GPIO13 = PWM3
GPIO15 = PWM4

Thank's a lot

**Comment by toshibochan** [comment]
@topzoe You can use this https://github.com/maccoylton/esp-homekit-rgbw-strip
Go to wiki page, have instructions for install.

**Comment by vniehues** [comment]
@toshibochan could you elaborate on how to use this? 
Im looking to do the exact same thing as @topzoe but i cant find the right config.json for my strip...

Thank you!

**Comment by toshibochan** [comment]
Maccoylton firmware can chose the gpio pins using the EVE app and If your magic home led strip is RGB or RGB + IR turn off pure white on EVE app and if is RGBW or RGBW + IR you switch on pure white on EVE app.

**Comment by vniehues** [comment]
nice, thank you!
Do you, by any chance, know a working config for RavenCore MagicHome RGBW? I'd rather not use the IR and not flash again...

**Comment by topzoe** [comment]
> @topzoe You can use this https://github.com/maccoylton/esp-homekit-rgbw-strip
> Go to wiki page, have instructions for install. And you can use EVE app for setup the settings for your device. In the EVE app you can chose the gpio pins and if is RGB or RGBW.

Thank you a lot! It works great!!!  (Don't forget the code for add the accessory is "11111111")

**Comment by vniehues** [comment]
@topzoe Can you tell me which pins you used for which color? Im about to flash it aswell :)

**Comment by toshibochan** [comment]
@vniehues Don’t change the code. You can change the gpio using the EVE app.

**Comment by vniehues** [comment]
@toshibochan okay thank you! 
I've seen you opened [this Issue](https://github.com/maccoylton/esp-homekit-rgbw-strip/issues/10)... Did you get that resolved?Because thats exactly my issue right now with raven. Everything else works as expected.

**Comment by toshibochan** [comment]
You using RGBWW or RGB led strip? If you using RGBWW you switch ON pure white on eve app. If you use RGB led strip pure white have to be off and the light will be cold white.

**Comment by vniehues** [comment]
@toshibochan Already found it. Thank you! :)
