### ISSUE TITLE
Universal IR Device

### ISSUE THREAD

**Issue by TriderG75** [RavenSystem/esp-homekit-devices#888]
- Universal IR device
https://gearbest.app.link/7kIjGiVCz5 (Tested Type B and Type C versions)
https://a.aliexpress.com/_d7NKf18 (Not tested)
https://s.click.aliexpress.com/e/_d7qlxvI (Tested)
(Thanks to carminedelia, micheletorrini and PSB on Discord)

- This json is for managing a Samsung TV with an IR device (see links above).
IR commands can be found here : https://github.com/RavenSystem/esp-homekit-devices/wiki/IR-Codes-Database.
Also available Philips and LG IR commands.
Json has also an IP function to know if smart Tv is On or Off using ping and a dummy switch that allows to enter in setup mode by pressing it one time.

- Json:
{"c":{"t":14,"p":"J*J*AaAaAaDFAa"},"a":[{"t":60,"xa":0,"i":[{"n":"MENU","0":{"i":   [{"r":2,"c":"CeCfAaBcAaAbC"}]}},{"n":"SOURCE","0":{"i":[{"r":2,"c":"CeCeAhG"}]}},{"n":"MUTE","0":{"i":[{"r":2,"c":"CeCeDhD"}]}}],"0":{"i":[{"r":4,"c":"CeCfAfAaF"}]},"1":{"i":[{"r":4,"c":"CeCfAfAaF"}]},"6":{"i":[{"r":2,"c":"CeCjBaEbA"}]},"7":{"i":[{"r":2,"c":"CeCeAdBbDbA"}]},"8":{"i":[{"r":2,"c":"CeCeAaAbBbAaBbA"}]},"9":{"i":[{"r":2,"c":"CeCfAcBaAaCbA"}]},"10":{"i":[{"r":2,"c":"CeChAaBaCaAbA"}]},"11":{"i":[{"r":2,"c":"CeChBaAaCbAaA"}]},"13":{"i":[{"r":2,"c":"CeCeBaAaBcAaAbA"}]},"17":{"i":[{"r":2,"c":"CeCeEhC"}]},"22":{"i":[{"r":2,"c":"CeCeChE"}]},"23":{"i":[{"r":2,"c":"CeCeBaAfAaD"}]},"q0":[{"h":"192.168.1.100","r":0}],"q1":[{"h":"192.168.1.100","r":1}]},{"i":0.5,"1":{"s":[{"a":1}]}}]}

![Tv_actions](https://user-images.githubusercontent.com/62612806/79312446-3047e600-7eff-11ea-87f3-ef8e1f5e7ca5.png)

-  Gocomma Type B

![Gocomma_B1](https://user-images.githubusercontent.com/62612806/79313847-4060c500-7f01-11ea-987c-eab080b12252.png)
![Gocomma_B2](https://user-images.githubusercontent.com/62612806/79313863-4787d300-7f01-11ea-9fd8-488a702a8981.png)
![Gocomma_B3](https://user-images.githubusercontent.com/62612806/79313877-4ce51d80-7f01-11ea-93ae-a7097e82eb2f.png)

- Cogomma Type C

![Gocomma_C1](https://user-images.githubusercontent.com/62612806/79313963-69815580-7f01-11ea-9a41-bd6c55826b25.png)
![Gocomma_C2](https://user-images.githubusercontent.com/62612806/79313969-6d14dc80-7f01-11ea-90f5-4271713e74e3.png)
![Gocomma_C3](https://user-images.githubusercontent.com/62612806/79313979-6f773680-7f01-11ea-944c-654d8f9269a5.png)

- Avatto S07

![Avatto_s07_1](https://user-images.githubusercontent.com/62612806/79314099-9d5c7b00-7f01-11ea-82c0-4c88379de457.png)
![Avatto_s07_2](https://user-images.githubusercontent.com/62612806/79314118-a2b9c580-7f01-11ea-89fe-c1da803df5bb.png)

**Comment by vijaydembla1** [comment]
Hi Trider,

I copied the exact same code , however i just get 3 buttons  (menu, source and mute) with one-off on my homekit. Any reason why i can’t see the remote or the other buttons?

Thanks

**Comment by TriderG75** [comment]
> Hi Trider,
> 
> I copied the exact same code , however i just get 3 buttons (menu, source and mute) with one-off on my homekit. Any reason why i can’t see the remote or the other buttons?
> 
> Thanks
Hi, you can find the other commands in the remote in the control centre. When you use that remote for volume up/down you must use iPhone volume up/down side keys.

**Comment by vijaydembla1** [comment]
Wow, i always thought i was technically smart but you proved me otherwise, i was looking in the remote app and not one in control centre.
What's the best way to include other tv's items in here, the question is to understand the way to caputre the code from the other remotes and incude them in my json

Thanks again for your help :-)
