### ISSUE TITLE
Interferences (Before: T1-2C)

### ISSUE THREAD

**Issue by egorist** [RavenSystem/esp-homekit-devices#89]
Sorry, but the device begins to on/off randomly again. Only main button. With advanced button everything is good.

**Comment by RavenSystem** [comment]
Try version 0.5.1.

**Comment by egorist** [comment]
I see the is new repository. I need to setup new repository in ota firmware again? Because I can’t set new firmware by ota now.

**Comment by RavenSystem** [comment]
It’s automatic. If you are running a version prior to 0.4.10, you must update twice to get version 0.5.1 and above:
Old_version -> 0.4.10 -> 0.5.1

v0.4.10 changes ota repo automatically.

**Comment by egorist** [comment]
Yes, I done it, thanks. Need some days for testing

**Comment by egorist** [comment]
2 times device switches on randomly for this time. So update doesn’t work ((

**Comment by RavenSystem** [comment]
Try version 0.5.2.

**Comment by egorist** [comment]
For now, It works, thanks)
