### ISSUE TITLE
Sonoff L1 RGB , HomeKit pls help

### ISSUE THREAD

**Issue by msdem98** [RavenSystem/esp-homekit-devices#893]
Good day,
Is it possible to add this accessory to HomeKit, I am already flashed controller but after adding to HomeKit no any reaction of trying change color or switch on/off. I am noob, is the problem in wrong Json code and if yes, can somebody give me right code. 
![41D71F44-AFD7-4684-9824-3CA6F42A2635](https://user-images.githubusercontent.com/63857260/79572404-91211b00-80c5-11ea-9b15-f082cef29e72.jpeg)
![19316C34-FB51-458F-9E2A-CD6B65B06F1F](https://user-images.githubusercontent.com/63857260/79572416-954d3880-80c5-11ea-9406-09ec64b34882.jpeg)
![69289626-206A-49BB-AE77-06F486066D22](https://user-images.githubusercontent.com/63857260/79572419-967e6580-80c5-11ea-8356-2823ee8460c1.jpeg)
![42A40CE1-BF45-4B73-AE30-DDA31E85033D](https://user-images.githubusercontent.com/63857260/79572420-967e6580-80c5-11ea-9bb4-e4bc95535d79.png)

**Comment by msdem98** [comment]
![6930C0A0-4299-430A-833E-30BD3D88E91D](https://user-images.githubusercontent.com/63857260/79642455-33183480-81a6-11ea-8302-ceb7ebbe734e.jpeg)

**Comment by tonysprenk** [comment]
This device uses serial commands to communicate with a secondary MCU this is not (yet) supported by HAA. @RavenSystem is working hard to have it supported in an upcoming update.

**Comment by mwouda** [comment]
Did anyone have any success with getting the L1 controler to work? 

Can you share the JSON?
I'm not having any success

thx.

**Comment by DrDaKen** [comment]
Hi, i have the same problem, cannot figure out the json strings.
please help to share!
regards,

**Comment by mwouda** [comment]
> This device uses serial commands to communicate with a secondary MCU this is not (yet) supported by HAA. @RavenSystem is working hard to have it supported in an upcoming update.

Any Progress with  communicate with a secondary MCU

**Comment by nikogeek** [comment]
any new info about it?
