### ISSUE TITLE
Can entering the setup mode be solved more elegant?

### ISSUE THREAD

**Issue by morphix9** [RavenSystem/esp-homekit-devices#896]
What I really "hate" right now is triggering of the setup mode. I'm using Shelly 1's mostly, which don't have a physical button and turning off those shelly's and then triggering the switch 8 times, is really cumbersome if you have many devices throughout the house. Is there a way to trigger the setup mode over HTTP? Is it possible to run a simple web server all the time on the device (while working with HomeKit)? This would really make our life easier :)

**Comment by pilot1981** [comment]
You can create a dummy switch to enter in setup mode when you want!

**Comment by PsbDxb** [comment]
add this code along
{"i":0.5,"1":{"s":[{"a":1}]}}

it will add a dummy switch in homekit, once triggered it will put the device into setup mode.

example of a sonoff basic  with dummy switch code 
{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"i":0.5,"1":{"s":[{"a":1}]}}]}

**Comment by morphix9** [comment]
Thanks, a dummy switch would be great. This is clearly missing in the wiki.

**Comment by morphix9** [comment]
Is it possible that by adding an extra switch to trigger setup mode, Siri gets confused and thinks I have 2 devices with the same name (although the switch is named HAA-XXXXX)?

**Comment by pilot1981** [comment]
yes, one is for setup mode and the other is for real relay.
I suggest you to rename dummy switch and move it to dummy room.
To find the right switch you have to try!

**Comment by morphix9** [comment]
Exactly what I've done. One is "Garage Door" in room "Garage", other is "HAA-XXXXX" in room "Setup mode". Looks like Siri gets confused because it's the same device behind those two accessories.

**Comment by pilot1981** [comment]
Which type of problem you have?
I haven’t any similar issue.


Please share some screenshoot of your configuration.

**Comment by morphix9** [comment]
<img width="415" alt="Screenshot 2020-04-23 at 12 32 06" src="https://user-images.githubusercontent.com/13349638/80090364-b0092c80-855f-11ea-8a8a-d93f087b8c9d.png">
![Uploading Screenshot 2020-04-23 at 12.40.48.png…]()

**Comment by Kienz** [comment]
Never had this issue. I have some devices with multiple switches (Setup-Mode, OTA-Update, Light, Switch). I renamed all accessories (eg. "... SetupMode", "... OTAUpdate", "... Light", "... Switch"). And Siri works without any issues.

**Comment by pilot1981** [comment]
You can do an example of Siri problem?

**Comment by morphix9** [comment]
![siri_bug](https://user-images.githubusercontent.com/13349638/80185041-fc11ab00-860b-11ea-9e75-3e4419145714.jpg)

**Comment by pilot1981** [comment]
Have you already tried to rename dummy switch?
