### ISSUE TITLE
SONOFF SV Relay Not Triggering.

### ISSUE THREAD

**Issue by the1maximus** [RavenSystem/esp-homekit-devices#898]
Thank you for your time with developing this firmware. 

I have found that using either the templates provided in the Wiki, or developing my own with the configurator does not allow for the Relay to trigger. Also GPIO 0 on the SV does not cycle the relay either. 

I have been successful with it as a Garage Door opener, but when setting it up as a switch, nothing happens when toggled from within the Home App, or when pressing the button on the board.

**Comment by wwns** [comment]
give json string

**Comment by the1maximus** [comment]
@wwns I found the issue to be with the 3rd party configurator. For whatever reason it was not pushing the digital output to GPIO 12. 

I went back to the beginning and used the code from the device data base and started modifying that and have not had the problem.

**Comment by mestregroda** [comment]
@the1maximus I am stuck with the same issue, but I am using sonoff mini. Could you post the json the was sucessfull for your setup?

**Comment by the1maximus** [comment]
> @the1maximus I am stuck with the same issue, but I am using sonoff mini. Could you post the json the was sucessfull for your setup?

This is the only code I could get to work. The relay will trigger when power cycled. in the home app, it will either show on or off, but each trigger is actually a press of a momentary button. 

{
	"c": {
		"l": 13,
		"b": [{
			"g": 0,
			"t": 5
		}]
	},
	"a": [{
		"0": {
			"r": [{
				"g": 12,
				"v": 1,
				"i": 0.5
			}]
		},
		"1": {
			"a": 0
		},
		"b": [{
			"g": 0
		}]
	}]
}

**Comment by RavenSystem** [comment]
To avoid initial relay trigger:
`{"c":{"l":13,"b":[{"g":0,"t":5}],"0":{"r":[{"g":12}]}},"a":[{"xa":0,"0":{"r":[{"g":12,"v":1,"i":0.5}]},"1":{"a":0},"b":[{"g":0}]}]}`

**Comment by the1maximus** [comment]
> To avoid initial relay trigger:
> `{"c":{"l":13,"b":[{"g":0,"t":5}],"0":{"r":[{"g":12}]}},"a":[{"xa":0,"0":{"r":[{"g":12,"v":1,"i":0.5}]},"1":{"a":0},"b":[{"g":0}]}]}`

Thanks for the reply, I’ll try this out and let you know.
