### ISSUE TITLE
How to use the extra multi-channel PWM ic

### ISSUE THREAD

**Issue by xfce** [RavenSystem/esp-homekit-devices#9]
Hi, all
     I want to use PCA9685(multi-channel PWM IC) , and test the channel output is ok, test pca9685_set_pwm_value(&dev, CHANNEL, VAL) in init function is OK, but I don't know how to add them, so the IPAD's Home can use the multi-channel IC, could someone give some advices, thanks

**Comment by RavenSystem** [comment]
Hello, 

I'm sorry, but this section is for issues about this repository. If you have any question about other topics, please, open your issue at the correspondent repository, for example https://github.com/maximkulkin/esp-homekit

Many thanks.
