### ISSUE TITLE
Lightbulb Color Transition Step - is it "p" or "st"

### ISSUE THREAD

**Issue by vincentl** [RavenSystem/esp-homekit-devices#907]
The documentation for Lightbulb Color Transition Step at https://github.com/RavenSystem/esp-homekit-devices/wiki/Lightbulb uses "p" in the text and "st" in the table for the name of the object that controls the step value.  

When I try to use "p", the configuration fails.  "st" is accepted, but I can't tell if it has any effect.

Use HAA v2.0.0.

**Comment by CryptonWind** [comment]
I have realized the same issue. Maybe it is a typo in the documentation.

**Comment by WizBangCrash** [comment]
The documentation was incorrect and has been updated to reflect the "st" key now.
