### ISSUE TITLE
More than 18h for 'Maximum Use Time' ?

### ISSUE THREAD

**Issue by macjl** [RavenSystem/esp-homekit-devices#912]
Hello,

I have an use case where I need a 'Maximum Use Time' for a switch of 24h.
I have an automation that activate a switch for 24h according to the weather forecast.

Do you think it's possible to increase the maximum value of 'Maximum Use Time' to more than 65535?

**Comment by RavenSystem** [comment]
It is a typo in the Wiki. Max duration is very higher.

**Comment by macjl** [comment]
Nice! I'll try a higher value.
Thanks!
