### ISSUE TITLE
HAA - Automate sprinkler

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#913]
Hi,

I’d like to automate my watering system but I cannot set a time schedule because I can not select sprinkler in Home App. HAA 2.1
Is there a solution?

**Comment by macjl** [comment]
Use Eve to create a scene that activate Sprinkler (and you can also choose the duration with Eve if you want). Then you can launch this scene with a schedule in Home.

**Comment by claire078** [comment]
Yes, this can work. 👍
But it works with Ravencore, HAA will support it as well?

**Comment by pilot1981** [comment]
Yes, it work also for HAA
![AA0EF032-FA19-485F-B20A-A10D31A27815](https://user-images.githubusercontent.com/46350465/80747706-22f84180-8b24-11ea-9d06-c57b33d0a5a7.png)
![EBA24620-BC22-407D-9FA9-B36F5B912B13](https://user-images.githubusercontent.com/46350465/80747718-268bc880-8b24-11ea-9fad-acd0fe978b38.png)
![Uploading 92BD7B79-3EE0-4AEA-83FA-7EB006D435C6.jpeg…]()

**Comment by claire078** [comment]
I meant HAA automation works without EVE app.

**Comment by pilot1981** [comment]
Yes

**Comment by claire078** [comment]
OK, again: could we will use watering accessories in automate rules without set a scene in Eve app?

**Comment by RavenSystem** [comment]
@claire078 Ask Apple.

**Comment by claire078** [comment]
> @claire078 Ask Apple.

You say, it does not work cause apple disabled these functions?
But why would they did that?
A sprinkler accessory without schedule option? That is make no sense...
