### ISSUE TITLE
UART commands

### ISSUE THREAD

**Issue by asbesto01** [RavenSystem/esp-homekit-devices#916]
I have seen the demo of UART Commands running on the Shelly dimmer. It seems an interesting feature, can it be applied also to sonoff basic, for example, to manage lights dimming?

Gracias!

**Comment by shanghaix** [comment]
That's not possible as the Sonoff basic lacks the internal hardware to be able to dim the lights. It's like asking if a Fiat can do the same things as a Ferrari.

**Comment by asbesto01** [comment]
> That's not possible as the Sonoff basic lacks the internal hardware to be able to dim the lights. It's like asking if a Fiat can do the same things as a Ferrari.

Super clear!

Any device in the sonoff range compatible with uart dimming?

Otherwise I should use the Shelly dimmer!

**Comment by shanghaix** [comment]
The Sonoff D1 (dimmer) came out earlier this year but so far it's only been compatible with Tasmota https://github.com/arendst/Tasmota/issues/7598. If I were you I would buy a shelly, they have a model that runs without a neutral wire coming out this month, on top of the regular one, and they are smaller than the Sonoff D1.

**Comment by asbesto01** [comment]
> The Sonoff D1 (dimmer) came out earlier this year but so far it's only been compatible with Tasmota https://github.com/arendst/Tasmota/issues/7598. If I were you I would buy a shelly, they have a model that runs without a neutral wire coming out this month, on top of the regular one, and they are smaller than the Sonoff D1.

Let me give you a little bit of background:

Currently I have dimming capable lights, connected to sonoff basic with haa flashed, and physical buttons soldered to them to manually turn on and off lights.

Working perfect, but I want to add dimming. I have neutral everywhere (currently using it with the sonoff basic).

This considered, which is my best option? I want HAA, I want dimming, I have neutral everywhere.

Which is the perfect Shelly for me?


Thanks a lot!

**Comment by shanghaix** [comment]
Then I would go with the regular shelly dimmer, its the best bang for your buck at the moment if you want a dimmer and use HAA to get homekit compatiblity!

**Comment by asbesto01** [comment]
> Then I would go with the regular shelly dimmer, its the best bang for your buck at the moment if you want a dimmer and use HAA to get homekit compatiblity!

Great, can someone please share a config.json for the Shelly dimmer supporting uart dimming via HomeKit haa?

Thank you so much!

**Comment by shanghaix** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database

**Comment by asbesto01** [comment]
> Config is there:
> https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database

ok purchased one; I see that for programming I need to use this wiring scheme:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/Sndzp0w/Schermata-2020-05-08-alle-18-52-14.png" alt="Schermata-2020-05-08-alle-18-52-14" border="0"></a>


the only problem is that I don't know which pins to short-cut to enter flash mode. Any suggestions?

**Comment by tonysprenk** [comment]
Gpio0 to gnd during startup.

**Comment by asbesto01** [comment]
Great, I correctly flashed it.

Now I have an issue; the shelly is able to actually dim my dimmable lamps, however at 0% it does not shut off, only flickering  (and intense) light.

What am I doing wrong?

**Comment by RavenSystem** [comment]
Shelly Dimmer is not a good device, and it has some incompatibility with some lamps. I used them with Amazon lightbulbs and results were bad. Better use a TRIAC based dimmer.

**Comment by asbesto01** [comment]
Any suggestions on HAA dimmers?

**Comment by tokamac** [comment]
> > any suggestions on TRIAC dimmers that can be flashed with HAA?

Have a look at **QS-WiFi-D01-TRIAC**, it is listed in the [device database](https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database) also. Please report here your findings, trials and errors with this one.

**Comment by asbesto01** [comment]
> QS-WiFi-D01-TRIAC



> > > any suggestions on TRIAC dimmers that can be flashed with HAA?
> 
> Have a look at **QS-WiFi-D01-TRIAC**, it is listed in the [device database](https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database) also. Please report here your findings, trials and errors with this one.

Thank you! Do you have a guide to flash it? And also the correct json please!
