### ISSUE TITLE
Xiaomi Philips

### ISSUE THREAD

**Issue by ahg675** [RavenSystem/esp-homekit-devices#919]
Hi everyone 

Xiaomi Philips LED Smart Bulb White (E27)
I have problem with bulb. Can somebody help me with this. 

In tasmota firmware I have 
GPIO12 PWM2
GPIO15 PWM1
And bulb working well

Already I’ve flashed newest firmware haa and I can’t set this to work. 

Can somebody write example configuration 

Thanks for help

Sorry for my English.

**Comment by ahg675** [comment]
Is this correct:

{
	"a": [{
		"t": 30,
		"v": 15,
		"w": 12,
		"s": 1
	}]
}

**Comment by RavenSystem** [comment]
> Is this correct:

Yes, if lightbulb uses each PWM channel to manage one color. In other case, it is not supported by HAA.
