### ISSUE TITLE
Sensor BME 280

### ISSUE THREAD

**Issue by ur5zeb** [RavenSystem/esp-homekit-devices#92]
HI. Is it possible to add support for the BME280 sensor?

**Comment by RavenSystem** [comment]
Is BME280 an one-wire sensor?

**Comment by ur5zeb** [comment]
i2s https://github.com/arendst/Sonoff-Tasmota/wiki/BME280-Temperature,-Humidity-and-Pressure-Sensor-and-Sonoff-Basic-with-Tasmota
Convenient to use in Sonoff T1

**Comment by RavenSystem** [comment]
I want to keep UART function.

**Comment by denis-mrd** [comment]
I want to add BME280 on NodeMCU with your firmware to my home

**Comment by Kristian8606** [comment]
https://github.com/Kristian8606/Temperature_sensor/blob/master/main.c
