### ISSUE TITLE
Devices not loading with latest release.

### ISSUE THREAD

**Issue by the1maximus** [RavenSystem/esp-homekit-devices#924]
Tried to setup another Sonoff SV, Checked the releases and saw that there was a new release from the day before.  After setting up, I came upon the new install screen asking for the custom OTA server.  After entering my json code and wifi credentials, the device stops responding.  I can see it on my network, but trying to get it into setup mode via the button, or through emergency mode does nothing.  I ended up having to refresh multiple times.  

End result was to move to an older release that I knew that worked.

**Comment by shanghaix** [comment]
Seems like the exact same issue from #922
