### ISSUE TITLE
Sonoff iFan03 RF Remote

### ISSUE THREAD

**Issue by 400HPMustang** [RavenSystem/esp-homekit-devices#926]
I have flashed a Sonoff iFan03 with HAA 2.1.2 and control via HomeKit works great but I'm not able to get the remote to work. I'm using the JSON below from the [wiki](https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database). 

Is there any way to get the remote to work with the Sonoff iFan03?

`{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"t":65,"e":3,"0":{"r":[{"g":15},{"g":12},{"g":14}]},"y0":[{"v":1,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12},{"g":14,"i":0.6}]}},{"v":2,"0":{"r":[{"g":15,"v":1,"i":0.5},{"g":12,"i":0.6},{"g":14,"i":0.6}]}},{"v":3,"0":{"r":[{"g":15,"v":1},{"g":4},{"g":14}]}}]},{"1":{"r":[{"g":9}]},"0":{"r":[{"g":9,"v":1}]},"b":[{"g":0}]}]}`

**Comment by RavenSystem** [comment]
RF will not work with iFan03.
