### ISSUE TITLE
init state shutters shelly 2.5 and sonoff dual

### ISSUE THREAD

**Issue by curla92** [RavenSystem/esp-homekit-devices#929]
Default init state sonoff dual works while shelly 2.5 when i power on shutter opens.

**Comment by shanghaix** [comment]
Did you try this? https://github.com/RavenSystem/esp-homekit-devices/issues/839

**Comment by curla92** [comment]
> Did you try this? #839

yes but shelly 2.5 is bugged.

**Comment by shanghaix** [comment]
You're right, I just tried "s":5 and it shows closed every time the shelly is rebooted even though the blinds were open before.

"s": Initial state:
0: Default. OFF.
1: ON.
4: Defined by fixed inputs.
5: Last state.
6: Opposite to last state.
