### ISSUE TITLE
D1 Mini as a Temp/Hum Sensor with no Switch

### ISSUE THREAD

**Issue by hmbarbosa** [RavenSystem/esp-homekit-devices#93]
Hello José 

Wondering if you could add an option to remove the switch from (6. Switch Basic + TH Sensor) I'm using this setup with a D1 Mini + DHT22 and works perfectly with a sensor connected on GPIO14. Is any change to hide the switch option as the main intention is to use the D1 Mini + DHT22 as a sensor only.

Thank you very much for your time expended on this project mate!!! that's Awesome.

**Comment by rechin304** [comment]
Maybe additional repo for this :) as there is no such implementation directly, they all use homebrige as middle man. Temp, Hum, PIR are few example where D1 mini can be used.

**Comment by RavenSystem** [comment]
@hmbarbosa Added to [TODO List](https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List)

**Comment by RavenSystem** [comment]
@hmbarbosa Sorry, but for now it's impossible to hide switch, because is the main service, and custom setup characteristic needs it; changing this is too complex because involves a lot of code. Removing from TODO list.
