### ISSUE TITLE
SPRINKLER @ Sonoff BASIC

### ISSUE THREAD

**Issue by KrzysiekRadek** [RavenSystem/esp-homekit-devices#931]
Hi All :)
I need a sprinkler string for Sonoff BASIC ...
can you help me?

**Comment by i3laze** [comment]
Try the online configurator:
https://glumb.github.io/haa-configurator/

1. Use a template for Sonoff Basic standard switch.
2. Remember GPIOs:
0 - cyclic input (push button)
12 - output
13 - LED
3. Remove switch accessory and add Water valve.
4. Change valve type to sprinkler (optional).
5. Add cyclic input 0 an digital output 12 on, 12 low off
6. Profit!
