### ISSUE TITLE
Sonoff 4ch pro r2

### ISSUE THREAD

**Issue by QDUNI** [RavenSystem/esp-homekit-devices#935]
hi, im trying to flash my Sonoff 4ch pro r2 with raven core. flash is succesfull but after flashing the haa-XXXXX is not visible or even online... any ideas? I tried flashing more than once but no changes. 
thnx !

**Comment by Hornett69** [comment]
Version for HAA OTA firmware and Home Architecture Accessory ? With latest version?

**Comment by QDUNI** [comment]
latest version

**Comment by Hornett69** [comment]
For the first connection... You try to access at the device with an iPhone or Android or anything else?

**Comment by Hornett69** [comment]
>

For both?

**Comment by Hornett69** [comment]
For the first connection... You try to access at the device with an iPhone or Android or anything else?

**Comment by Hornett69** [comment]
> latest version

For both

**Comment by QDUNI** [comment]
latest version for both. iPhone or MacBook. Imac
