### ISSUE TITLE
Sensor initial state

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#936]
I'm struggling with leakage sensor (GPIO9), that should perform action (close valve GPIO12) on state change. The valve can be controlled manually, so I need to force close it no matter the valve accessory state.

Seems, it's either possible to correctly read sensor state on startup:
`{"t":7,"0":{"r":[{"g":12,"v":1}]},"g0":[{"g":9,"t":1}],"g1":[{"g":9,"t":0}]}`
or perform an action after state change, but startup always sets "Sensor Status OFF" until sensor flaps once:
`{"t":7,"0":{"r":[{"g":12,"v":1}]},"f0":[{"g":9,"t":1}],"g1":[{"g":9,"t":0}]}`

According to [Sensors Wiki page](https://github.com/RavenSystem/esp-homekit-devices/wiki/Sensors#Initial-State):
> The Initial State key is not supported by sensor accessory. Refer to Initial State for more details.

What's the difference again between "f0" and "g0"? 
Why I can’t have best of two worlds (actions and initial state read at startup)?

**Comment by i3laze** [comment]
Up.

**Comment by i3laze** [comment]
I’d say Up again,

**Comment by RavenSystem** [comment]
Initial sensor states are determined by GPIOs.
