### ISSUE TITLE
Weird AP BSSID displayed in Setup mode

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#940]
I've got two exact same 2.4Ghz WiFi Access Points: 
TP-Link TL-WR842N v3 running latest OpenWRT 19.07.2
Second one I purchased recently, and it's BSSID for some reason is displayed in HAA Setup mode wrong. 

All the devices (MacBooks, Nest Thermostats, HAA devices) connect to the new AP in Normal mode just fine. All of them, except HAA, display correct AP BSSID, when I use WiFi Scanner or Option+click on WiFi icon.

I've noticed this while testing Sonoff Dual.  Confirmed with Sonoff Basic R2v1.0 (its output below).

Funny facts about the issue:
1. AP MAC address/BSSID is 84:16:F9:00:C9:AA
2. In Normal mode HAA connects to this AP just fine.
3. In HAA Setup mode for some reason I see its BSSID as 8416f9000000:
![image](https://user-images.githubusercontent.com/16850291/81705125-59648380-9477-11ea-814f-2d84c017cd3c.png)
4. When I Force BSSID on by clicking on this 8416f9000000, I get:
```
WiFi config init
WiFi Mode: Forced BSSID 8416f9000000
...
scandone
no WiFi found, reconnect after 1s
reconnect
scandone
```
5. When I Force BSSID by entering manually **8416F900C9AA**, I still got same 0000 output:
```
WiFi config init
WiFi Mode: Forced BSSID 8416f9000000
Hostname: HAA-024460
scandone
no WiFi found, reconnect after 1s
Disarming Emergency Setup Mode
reconnect
Saving states
scandone
no WiFi found, reconnect after 1s
reconnect
```
Eventually by any means I can't force BSSID on this AP.
Something is out of range?)

Issue is easily reproducible -  just input my BSSID manually.

**Comment by RavenSystem** [comment]
Fixed now with last version. Thanks for report!
