### ISSUE TITLE
garage door opener enhancement

### ISSUE THREAD

**Issue by therealbat** [RavenSystem/esp-homekit-devices#943]
Hi, great work.
i'm wondering whether the garage door plugin could be changed to support different timers for open and close commands. my hoermann supramatic has significantly different operation times.

it opens in 13 seconds, but takes 20-21 seconds to close.
an option for separate timers would be a nice addition.
thx

**Comment by PEA71** [comment]
See the wiki please:

Door Opening Time	"d"	Time door takes to open
Door Closing Time	"c"	Time door takes to close

https://github.com/RavenSystem/esp-homekit-devices/wiki/Garage-Door
