### ISSUE TITLE
KellyTron testing

### ISSUE THREAD

**Issue by mgoeller** [RavenSystem/esp-homekit-devices#95]
I can flash the firmware to a Shelly 1 successfully as described in the Wiki, even configure the device as type "Shelly 1" with the virtual accessory in the Eve App. All this is done while powering the Shelly 1 through the FTDI232 usb serial adapter. I can successfully ping the device as well. Of course I don't hear the relay clicking because the Shelly isn't powered by 230 V yet but I can see the relay toggling in the serial monitor.

When I now unplug the serial adapter and power the shelly with 230 V it doesn't even connect to my WiFi, e.g. I can't ping it. If I connect the Shelly 1 directly to 230 V after flashing the firmware, I can see the OTA-XXXXXX WiFi Access Point and connect / ping it. After entering the WiFi credentials and OTA repository the Shelly is supposed to reboot and connect to the WiFi, which it never does. When plugging it after this again to the serial adapter, everything works as intended.

I tested this with multiple Shelly 1's, that otherwise (with the original firmware) work fine.

Any suggestions how to debug? Or what I am doing wrong?

**Comment by RavenSystem** [comment]
Actually, I haven’t a Shelly 1. I burned it, and I’m waiting for a new one. I will investigate this bug, because I’m very interested in a working HomeKit with those devices.

**Comment by Codi878** [comment]
Hi Jose,
I confirm that bug, I also tested 4.9 firmware on shelly1 v2 and unfortunately, after uploading without OTA the module is not visible on 230V power supply. It is not visible as AP mode.

**Comment by RavenSystem** [comment]
Info about Shelly 1: 
http://www.thesmarthomehookup.com/the-shelly-1-smart-relay-is-it-better-than-the-sonoff-basic/

**Comment by Codi878** [comment]
HI Jose

Thank you for a nice article. Today I have tested again and I am really able to pair with homekit shelly1 when connecting low voltage to programming pins and I can control it. When connected to 230v it does not show signs of life in the home app. Where is a problem ?

**Comment by RavenSystem** [comment]
IMHO The problem is the high voltage used by Shelly GPIOs. I'm going to release a separated firmware for Shelly 1, and drop it from RavenCore support.

**Comment by RavenSystem** [comment]
RavenCore 0.5.0 has been released just now. Next step will be work on KellyTron firmware (Shelly 1 firmware with native HomeKit).

**Comment by AramVartanyan** [comment]
I want to try out the Shelly 1 with a basic switch firmware, but I do not want to burn it out (because of the mains reference voltage for the GPIOs).
Jose, would you give me an advice how to configure the I/Os or if I can use that part of your unfinished KellyTron?

**Comment by AramVartanyan** [comment]
How did you burned your Shelly1?

**Comment by AramVartanyan** [comment]
Wow! You are lucky that you are not injured and the Mac is up and running!

Very good! Shelly looks like a good product and it will be nice to add it to the HomeKit family of devices.

Thank you for your great work!

**Comment by RavenSystem** [comment]
Yes, my iMac is alive, but my FTDI adapter burned out too. Amazon sent another unit soon. I'm interested in Shelly 1, it's smaller than Sonoff Basic, and it has a GPIO dedicated to connect a mount-wall switch with 230VAC. I want to use these devices in all lights of my house.

**Comment by Wissoation** [comment]
Hey Ravensystem which FTDI Adapter have you bought from Amazon for the IMac

**Comment by RavenSystem** [comment]
@Wissoation this one: https://www.amazon.es/dp/B01N9RZK6I/

**Comment by Codi878** [comment]
Shelly will be the best homekit upgrade in Home app

**Comment by blamus777** [comment]
Any news?

**Comment by Codi878** [comment]
Hi Jose,

I uploaded the software and shelly works ok, but after some time it's no longer visible in the home app. It helps to disconnect from the power and reconnect again.

**Comment by RavenSystem** [comment]
@Codi878 Mine works well. Now it's up for 27 hours without any issue.

**Comment by Codi878** [comment]
Hmm, I do not know, but all my Sonoff work perfectly but Shelly1 ver2 on KellyTron firmware does not respond after a few minutes

**Comment by RavenSystem** [comment]
Is connected to 230VAC or FTDI?

**Comment by Codi878** [comment]
230v

**Comment by RavenSystem** [comment]
Disconnect it from 230VAC and connect to FTDI to recollect logs.

**Comment by Codi878** [comment]
Jose on 3,3V everything works good

**Comment by RavenSystem** [comment]
Ok, try version 0.0.2 and comment.

**Comment by RavenSystem** [comment]
KellyTron firmware has been discontinued. Now RavenCore supports Shelly1.
