### ISSUE TITLE
Unable to update WiFi SSID after first setup.

### ISSUE THREAD

**Issue by seshaln** [RavenSystem/esp-homekit-devices#951]
Sonoff R4 (ESP8285)
HAA v3.0.2
Steps to reproduce:
1.Install HAA according to manual https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation
2. Connect to HAA-xxxxxx Wi-Fi, select my SSID MY_NETWORK, enter a password.
3. Wait for OTA update(about 5 minutes)
4. Sonoff rebooted, and successfully connected to MY_NETWORK. HomeKit works OK.
5. Reboot Sonoff R4 in setup mode. Connect to HAA-xxxxxx, select new SSID SSID MY_NETWORK_NEW, enter a password.
6. FAIL - Sonoff R4 still trying to connect to old network (MY_NETWORK), and showing it in UART logs.
I found only one way to set up new SSID - reflash Sonoff R4 form start.

**Comment by i3laze** [comment]
As usually simple SSID select is working, in your case it might be needed to use Reset WiFi option - it is available in the same Setup mode.

**Comment by seshaln** [comment]
Of course, I checked `Reset WiFi` option - no success 😞

**Comment by RavenSystem** [comment]
Use last version.
