### ISSUE TITLE
Use multiple Shellies on my homekit 

### ISSUE THREAD

**Issue by VanAxl** [RavenSystem/esp-homekit-devices#952]
Hi Everyone, 
Well I'm wondering if I miss something on the installation guide, because I did successfully install one of my Shelly 1 device with this firmware (garage door). But I have a second one I would like to use on my homekit installation, I've setup this second as a simple switch, but when I try to scan the homekit code, it says that this device is already registered !

So if someone could tell me how to add multiple shells on my homekit ? 
Would be nice.

Thanks a lot.
VanAxl.

**Comment by Kienz** [comment]
Enter the code 02182017 manually. This works - sometimes on the 2nd attempt.
I have about 20 devices from Shelly and all ca be added.

**Comment by VanAxl** [comment]
Great, you are right, it was that simple, manually adding the code ! I was always scanning .... thanks a lot.
