### ISSUE TITLE
ws2812

### ISSUE THREAD

**Issue by Kristian8606** [RavenSystem/esp-homekit-devices#963]
Any plans for ws2812 led strip?

**Comment by RavenSystem** [comment]
Yes.

**Comment by wayn3** [comment]
If HAA could do Neopixels that would be next level amazing

**Comment by Kristian8606** [comment]
There are examples.  It's a matter of time

**Comment by wayn3** [comment]
👆🏼

**Comment by RavenSystem** [comment]
Added to TODO list.

**Comment by arkn666l** [comment]
almost 2 years ago, is there a neopixel module ?

**Comment by RavenSystem** [comment]
It was introduced years ago: https://github.com/RavenSystem/esp-homekit-devices/wiki/Lightbulb#NRZ-Protocol

**Comment by arkn666l** [comment]
si justo acabo de verlo, dentro de lightbulb, gracias por tan maravilloso firmware, fiel seguidor de YT y discord, estoy viendo si hay alugun apartado de efectos, saludos!
