### ISSUE TITLE
Problem Add Second Devices of Sonoff Basic on Homekit

### ISSUE THREAD

**Issue by Romadhonfajar** [RavenSystem/esp-homekit-devices#968]
Dear All, recently I try to add another Sonoff Basic that flash with esp-homekit-devices to My Home app on iPhone. But I get error accessories already added.

Can you help Me? Thanks before 🙏🏼

**Comment by aleroot** [comment]
I get the same error trying to add a second Shelly 1 to an already added SonOff Mini

**Comment by Kienz** [comment]
Please try enter HomeKit Code manually.

**Comment by aleroot** [comment]
In my case the problem was that the other HAA device, the shelly 1, was already added to another apple ID,  Had to remove from that one and add in the other ... Then problem was solved.
