### ISSUE TITLE
4ch pro - watering

### ISSUE THREAD

**Issue by dwhp** [RavenSystem/esp-homekit-devices#97]
Hi. Love your work. I was wondering if the switch 4ch (4) could possibly have watering vale options (7) put in as an option individually for each channel. To give you an ide of our project, We are installing 2x backyard  watering zones and pump power on/off AND fountain pump on/off utilizing a single 4ch pro. Obviously can use firmware as is, however would be nice to have the features of option (7). Garage door would also be nice for future project, but understand maybe a pain by running out of gpio’s unless forfeiting 2 relays for sensors. Thanks :) look forward to your reply

**Comment by RavenSystem** [comment]
Using Sonoff 4ch for 4xWater Valve: https://github.com/RavenSystem/esp-homekit-devices/issues/98

Garage Door is ready with device type 8: https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#8-garage-door
