### ISSUE TITLE
Missing Reset Homekit ID

### ISSUE THREAD

**Issue by jakudo** [RavenSystem/esp-homekit-devices#970]
Hi,

I had one Sonoff mini with an old HAA firmware (0.7.x). I've just updated to the latest firmware but can't add it to the Homekit. I wanted to "Reset Homekit ID" but there is no option for that... Any idea what am I doing wrong?

Thanks,
Jakub

<img width="950" alt="Screenshot 2020-05-23 at 11 54 34" src="https://user-images.githubusercontent.com/57570372/82727661-35613780-9cec-11ea-9460-a06d68473984.png">
<img width="974" alt="Screenshot 2020-05-23 at 11 54 41" src="https://user-images.githubusercontent.com/57570372/82727666-38f4be80-9cec-11ea-9d1e-b7264ec1954d.png">

**Comment by tonysprenk** [comment]
This screen is initial setup. Select auto Ota updates and the WiFi network and click save. Wait ten minutes for it to download HAA and then add it to HomeKit.

**Comment by jakudo** [comment]
Thanks, that worked. Strange that before I didn't need to wait that long. Next time, I have to be more patient :)

**Comment by skupu** [comment]
now it doesn't download...
