### ISSUE TITLE
HAA dimmer support

### ISSUE THREAD

**Issue by mrmaximas** [RavenSystem/esp-homekit-devices#973]
Dear sirs!
It is possible to make HAA JSON for trial edge dimmer like this?
https://templates.blakadder.com/rjwf-02a.html
Thanks!

**Comment by Bolshoylu** [comment]
try it:
{"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"w":14,"b":[{"g":0}]}]}

**Comment by mrmaximas** [comment]
> try it:
> {"c":{"q":850,"b":[{"g":0,"t":5}]},"a":[{"t":30,"w":14,"b":[{"g":0}]}]}

thanks, but this JSON is dimming dimmer's LED, not lamp.

**Comment by TheReiner** [comment]
Hi Mr Maximas,
Did you find the good solution ? Can i have the JSON ? 
Thanks.
