### ISSUE TITLE
Unable to connect HHA xxxxx after entering setup mode

### ISSUE THREAD

**Issue by tarontop** [RavenSystem/esp-homekit-devices#974]
I have successfully connected to Homekit and realized the control. However, when I entered the setting mode, I could not connect to hha-xxxx, indicating that I could not join the network
![IMG_6020(20200526-201631)](https://user-images.githubusercontent.com/37043404/82900128-a6277e80-9f8e-11ea-932e-d8829ab68693.JPEG)

**Comment by grivenDE** [comment]
Once installed and registered with your network setup mode will work over the Devices IP instead of connecting to it's own WLAN Network. Try pointing your Browser to your Devices IP while it is in setup mode ;)

**Comment by tarontop** [comment]
> 一旦安装并向您的网络设置模式注册，它将可以通过设备IP工作，而不是连接到它自己的无线网络。在设置模式下，尝试将浏览器指向设备IP；）

It's settled. Thank you！
