### ISSUE TITLE
Can’t reset homekit id

### ISSUE THREAD

**Issue by karnas99** [RavenSystem/esp-homekit-devices#975]
Hi,

I just flashed sonoff sv to HAA. Problem is that web does not offer reset homekit ID so I can’t add device to homekit. Please help.

![00530A16-4FB4-4A25-BE28-7ED57C236090](https://user-images.githubusercontent.com/65977799/82942466-47ff9900-9f98-11ea-8a3d-5c8f808a6c76.png)

**Comment by karnas99** [comment]
Ok After some time page reloaded with all options so I reset homekit id. However now I get another error. 
![D3911C43-65D2-4D01-BF7D-D9EC96BAFD55](https://user-images.githubusercontent.com/65977799/82948724-9b76e480-9fa2-11ea-912a-dc7871bfd923.png)

**Comment by Kienz** [comment]
The HomeKit code of HAA devices is 0218-2017 - in your screenshot you are using the HomeKit code 0941-4037.

**Comment by karnas99** [comment]
Thanks for help it is working now!
