### ISSUE TITLE
Unable to Add Second device 

### ISSUE THREAD

**Issue by kartikch143** [RavenSystem/esp-homekit-devices#982]
I have flashed my esp-8266 with fullhaaboot.bin but when I try to add the device to my phone (Homekit) its keep on showing error the device is already added

Code:
{
  "c": {
    "b": [
      {
        "g": 0,
        "t": 5
      }
    ],
    "o": 1,
    "l": 2
  },
  "a": [
    {
      "t": 30,
      "r": 14,
      "g": 13,
      "v": 12,
      "b": [
        {
          "g": 0
        }
      ],
      "s": 0,
      "p": 1024,
      "d": 1,
      "e": 10,
      "fr": 1,
      "fg": 1,
      "fv": 1
    }
  ]
}

**Comment by Kienz** [comment]
How do you add the second device? With qr-code? If so, please try to add the second device by manually enter der HomeKit code 0218-2017.
