### ISSUE TITLE
Can not enter to the setup mode - sonoff mini.

### ISSUE THREAD

**Issue by karnas99** [RavenSystem/esp-homekit-devices#983]
Hi,

I have a problem with entering to the setup mode. I changed json configuration to the sensor. Unfortunately I remove button configuration so button is not working now. Problem is that I can not find the way how to access to the setup mode. It is sonoff mini.

**Comment by karnas99** [comment]
Ok solved by reflashing via cable

**Comment by nikbyte** [comment]
Emergency setup mode:
Plug it.
Unplug after 1 second.
Plug it.
Device is in setup mode.

**Comment by karnas99** [comment]
This did not work for me

**Comment by nikbyte** [comment]
I did it few times with my sonoff mini. Maybe you need to try 2-3 seconds, but this is working.
