### ISSUE TITLE
nc -kulnw0 45678 (UDP Logger)

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#987]
Does anybody has _netcat_ UDP logger working on MacOS Catalina?

Although my Wireshark sees all UDP:45678 Broadcast packets sent by HAAs around, embeded _netcat_ on Mac somehow doesn't listen to broadcast, only direct single cast is displayed:
```
echo "test" | nc -u 127.0.0.1 45678  -> received
echo "broadtest" | nc -u 255.255.255.255 45678 -> not received

sudo nc -kulnw0 45678
test
socat -u udp-recv:45678,reuseaddr -
test
```
 I even tried _socat_ utility and sudo (running as root), with no luck.

Issue is relevant to previous versions and latest OTA 3.1.5/HAA 2.4.3
So, that's not a HAA issue, but a MacOS one.. Nevertheless, any ideas?

**Comment by RavenSystem** [comment]
I use `nc -kulnw0 45678` from macOS Catalina (now 10.15.5) without any issue (running as normal user).

**Comment by RavenSystem** [comment]
Have you any firewall or something similar that blocks unknown multicast network traffic? Maybe a recent update of your router?

**Comment by i3laze** [comment]
Thank you for involvement. Your assurance of this netcat working fine is enough.

I believe I know a VPN tool, messing Mitch my MAC connectivity.
I‘ll post the result when I’ll fix it.
