### ISSUE TITLE
Help! Shelly 2.5, configuration for outlet, motion sensor and thermostat with ds18b20 sensor

### ISSUE THREAD

**Issue by skop1986** [RavenSystem/esp-homekit-devices#991]
Please help me create a configuration, I don't know what pins to use

**Comment by i3laze** [comment]
I hope it’s not a single device :) however why not.
You were lucky to flash Shelly 2.5 - I hate their smallest pin holes.

Ok, go to HAA online configurator, use some templates or just add accessories at the bottom:
https://glumb.github.io/haa-configurator/
Use there a template for Shelly 2.5 dual switch to start with.

Your GPIOs are:

GPIO	Component
0	LED
2	Reset Button
13	Switch1 - input
4	Relay1 - output
5	Switch2 - input
15	Relay2 - output
From here: https://tasmota.github.io/docs/devices/Shelly-2.5/

**Comment by skop1986** [comment]
Kaya I realized you can only connect one sensor. Here's what I got, can anyone check how it works?


      "0": {
        "r": [
         {
  "c": {
    "b": [
      {
        "g": 2,
        "p": 0,
        "t": 5
      }
    ]
  },
  "a": [
    {
      "0": {
        "r": [
          {
            "g": 15,
            "v": 0
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 15,
            "v": 1
          }
        ]
      },
      "t": 2,
      "b": [
        {
          "g": 5,
          "t": 1,
          "i": 0,
          "p": 0
        }
      ],
      "s": 5
    },
    { 
      {
            "g": 4,
            "v": 0
          }
        ]
      },
      "3": {
        "r": [
          {
            "g": 4,
            "v": 1
          }
        ]
      },
      "4": {
        "r": []
      },
      "t": 21,
      "b": [
        {
          "g": 13,
          "t": 1
        }
      ],
      "g": 0,
      "n": 3,
      "w": 1,
      "m": 0,
      "x": 50,
      "s": 5,
      "j": 60,
      "d": 2
    }
  ]
}

**Comment by i3laze** [comment]
Sorry, I had to through my Shelly 2.5 away, cause torn up the pins. 
So, You’re the tester here)
I also suggest you to purchase Sonoff TH16 for such thermo tasks.

Regarding JSON it looks promising. Go trial and error.

**Comment by skop1986** [comment]
@i3laze 

I also lost my shelly pins, they are made there very unreliably. Sonoff TH16 does not fit because of the size, I want to shove shelly into the outlet so that she can control the outlet and the floor heating from there
