### ISSUE TITLE
Will HAA be compatible with Sonoff Micro 5V USB?

### ISSUE THREAD

**Issue by sblitzer** [RavenSystem/esp-homekit-devices#993]
Will HAA be compatible with Sonoff Micro 5V USB?

<img width="549" alt="Screen Shot 2020-06-04 at 18 54 29" src="https://user-images.githubusercontent.com/44753136/83779607-dc52b580-a694-11ea-9185-103df368083c.png">

**Comment by shanghaix** [comment]
It’s not using en ESP8266 so probably not. Even Tasmota is not compatible.
