### ISSUE TITLE
Sonoff Basic with dummy switch

### ISSUE THREAD

**Issue by asbesto01** [RavenSystem/esp-homekit-devices#995]
Hello everybody,

could someone with a big heart add a dummy switch to this config?

{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]}]}

Thank you!

**Comment by RavenSystem** [comment]
My heart has a normal size, but here is:

`{"c":{"l":13,"b":[{"g":0,"t":5}]},"a":[{"0":{"r":[{"g":12}]},"1":{"r":[{"g":12,"v":1}]},"b":[{"g":0}]},{"t":1}]}`

**Comment by asbesto01** [comment]
Jose your heart has a way bigger size compared to the other ones, thanks for everything as always, hermano!!!

Hope you and your family are doing all fine in Espana, we are still safe in Italy :)
